### ISSUE TITLE
Huge battery drain

### ISSUE THREAD

**Issue by soum91** [pwn20wndstuff/Undecimus#100]
So many people are have really bad battery drain issue. Drainage spikes up to 150% and sometimes draws 800mA currently. Backboard spikes up cpu usage.

**Comment by GeoSn0w** [comment]
Backboardd? I suspect a tweak shenanigan

**Comment by Samgisaninja** [comment]
Issue closed, this is not a code-level issue with unc0ver. 

I recommend you uninstall or disable some of your tweaks, as tweak battery drain is counted as backboardd by iOS, so that's the issue here.

**Comment by soum91** [comment]
GeoSn0w, what does the Ref column in Module section mean in CocoaTop? Tweakloader has the highest number.

**Comment by jake1970** [comment]
any updates i have the same error
