### ISSUE TITLE
RootFS-restore not working on iPhone6

### ISSUE THREAD

**Issue by Haeckli** [pwn20wndstuff/Undecimus#1004]
So, i finally needed my iPhone6 unbroken for some reason so I decided to restore the RootFS which I successfully did with my iPad a couple of times before. I enabled the "RootFS" switch and ran unc0ver (3.0.1). It worked well, confirmed the successsful RootFS-restore in the first run, confirmed the renaming of the snapshot in the second run and finally confirmed "jailbroken" after the 3rd run. NO single error was presented in the Unc0ver log; all actions were confirmed "OK". 

The big surprise then was, that I ended up with all my tweaks and mods still installed and fully functional. So, obviously either the Root-restore never happened (although confirmed in the log-file) or it somehow maintains a "jailbroken" snapshot on top of the RootFS to which it restored. I tried a few times, always with the same result - NO RootFS happening. 

"snappy -f / -l" just lists one single snapshot: "orig-fs". 

So I tried renaming the snapshot via the console (snappy -f / -r orig-fs -x), rebooted manually and NOW I was able to restore to the RootFS. I also repeated this a few times and it also repeats 100%. 

I finally thought, that I have messed up my system by playing around in the SSH console, so I decided to FutureRestore the device to 12.1.2 and try from scratch. So this is what I did: 

- FurureRestore to 12.1.2
- Jailbreak (Unc0ver 3.0.1)
- Install a few tweaks
- Re-run Unc0ver with "RootFS" enabled

And even with this totally fresh IOS installation it couldn't restore the RootFS. Each time the tweaks are still there and functional. Also here the only way to root-FS was using snappy. 

Next I tried the exact same procedure but using "Unc0ver 3.0.0 b43" to check if it has ever worked before but the result was the same. So I guess, it has never ever worked although I can't believe that the issue was never raised before... 

The attached log-file was created during my test on a future-restored device (iPhone6, 64GB, IOS 12.1.2, Unc0ver 3.0.1). It contains the initial jailbraking after restoring the device and about 20 minutes later the re-jailbreaking with "RootFS" enabled. As to my little knowledge even the log does not show any errors. Fun-fact that even after a RootFS-restore the log still contains all previous records.... 

This whole thing can be 100% reproduced at any time. I tried at least 20 times....
So did anybody ever find something similar or what am I doing wrong? 
Because it works fine on my iPdaAir2 I guess that this is somehow connected to either the iPhone6 or 4K-devices in general.... 

[3-0-1 - log_file.zip](https://github.com/pwn20wndstuff/Undecimus/files/3136897/3-0-1.-.log_file.zip)

**Comment by Haeckli** [comment]
Could it be that the iPhone6 is not restoring to RootFS because of the "Fortnight-Bug"? 
All my tests and experiences are with a future-restored device using 12.2 SEP. 
RootFS restore on my iPad may still be working because it ist restored with 12.1.3 SEP.
Just a thought...

**Comment by akukatala** [comment]
HELP!! I have JB in iOS 12.1.1 but I don't have a PC and when I give the option of unc0ver to remove the JB the option to update software in the iPhone options does not open and if I give it to reset the cell phone it gives me a respring and does not erase anything
