### ISSUE TITLE
cannot jailbreak previously jailbroken device. unable to remove app sync unified

### ISSUE THREAD

**Issue by n-other** [pwn20wndstuff/Undecimus#1007]
**Describe the bug**
cannot jailbreak previously jailbroken device. getting error regarding inability to remove app sync unified package  

**To Reproduce**
1. Start jailbreak
2. Get jailbreak fail error message

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iphone-6s
 - unc0ver Version: 3.0.0~b48

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[*] runCommandv(311): Get:1 file:/var/lib/undecimus/apt ./ openssh 7.9p1-3 [1760 kB]
[*] runCommandv(311): (Reading database ... 8163 files and directories currently installed.)
[*] runCommandv(311): Removing com.hackyouriphone.appsyncunified (31.1) ...
[*] runCommandv(311): dpkg: error processing package com.hackyouriphone.appsyncunified (--remove):
[*] runCommandv(311):  subprocess installed pre-removal script was killed by signal (Killed: 9)
[*] runCommandv(311): dpkg: error while cleaning up:
[*] runCommandv(311):  subprocess installed post-installation script was killed by signal (Killed: 9)
[*] runCommandv(311): Removing io.pangu.fuxiqin9 (1.3) ...
[*] runCommandv(311): You can't uninstall this jailbreak package. If you want, please use Cydia Eraser.
[*] runCommandv(311): dpkg: error processing package io.pangu.fuxiqin9 (--remove):
[*] runCommandv(311):  subprocess installed pre-removal script returned error exit status 1
[*] runCommandv(311): Errors were encountered while processing:
[*] runCommandv(311):  com.hackyouriphone.appsyncunified
[*] runCommandv(311):  io.pangu.fuxiqin9
[*] runCommandv(311): E: Sub-process /usr/bin/dpkg returned an error code (1)
[*] runCommandv(311) completed with exit status 100
[*] __assert(0:aptInstall(@[@"-f"]))@JailbreakViewController.m:1837[jailbreak]

**Comment by Haeckli** [comment]
Maybe you want to review your repos and remove those with piracy tweaks. „hackyouriphone“ is NOT a legit source for AppSync Unified. Also: Why you install tweaks for pangu IOS 9 Jailbreak into unc0ver? 
So don‘t blame Unc0ver for not being able to deal with it....

**Comment by n-other** [comment]
> Maybe you want to review your repos and remove those with piracy tweaks. „hackyouriphone“ is NOT a legit source for AppSync Unified. Also: Why you install tweaks for pangu IOS 9 Jailbreak into unc0ver?
> So don‘t blame Unc0ver for not being able to deal with it....

I guess you didn't read my post carefully. The device used to be jailbroken before. It's not jailbroken now. I can't remove those packages without device being jailbroken.

**Comment by Un4givenPG** [comment]
You can’t re-jailbreak because you have installed shit from the pirate repo, do a RootFS restore before you bootloop your phone
