### ISSUE TITLE
Molotov TV (french tv streaming app) not working after JB

### ISSUE THREAD

**Issue by elcarooo** [pwn20wndstuff/Undecimus#1011]
This very famous french app doesn’t work after JB but works before JB
ipad air 1
unc0ver 3.0.1
ios 12.1.1 beta 3
molotov tv : latest version

**Comment by Un4givenPG** [comment]
That is your problem they are using JB detection, if you weren’t a newbie you would know that.

**Comment by Un4givenPG** [comment]
Close this issue
