### ISSUE TITLE
Random resprings

### ISSUE THREAD

**Issue by theTobster500** [pwn20wndstuff/Undecimus#1015]
Sorry if someone's already reported this;I looked through most recent reports and couldn't find anything.

My iPhone 6s on iOS 12.1.2 resprings at random times. Often it's when i want to take a picture, but it's not relyable enough to reproduce predictivley

**To Reproduce**
As I said, I haven't been able to reproduce it on purpose. It often happens when I take a picture in the stock camera or when I open the camera in WhatsApp. It happens at random times as well, like when I press a button in a game or when i switch apps.

**Device**
 - iOS 12.1.2
 - iPhone 6s
 - unc0ver Version: 3.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

I don't believe it's a tweak causing this because the tweak list I currently have worked fine on the beta versions of unc0ver. Since I can't reproduce it I haven't tried disabling all tweaks as I'm not sure what I can do to test if the issue is still there.

**Comment by theTobster500** [comment]
sorry for all the edits, this is the first time I've posted on this site

**Comment by ZerOneX** [comment]
everyone is facing the Random resprings issues.... the solution as of now is to wait or migrate to electra/chimera

**Comment by rctfan929** [comment]
Also getting random resprings w/ same device @theTobster500.
Could not get chimera to work. When it happens randomly, how often does it occur?
