### ISSUE TITLE
Random Reboots with logs

### ISSUE THREAD

**Issue by TheSniperzzz** [pwn20wndstuff/Undecimus#1019]
**Describe the bug**
The device randomly reboot while using it. It usually seems to happen during the 3rd day of uptime but this time even earlier.
I do not have any random resprings, no nightly reboot. This is the only issue I have.

First log: 1st day of uptime, happened while launching camera app.
Second log: 3rd day of uptime, happened randomly.

**To Reproduce**
Seems like many people have random reboots after some days of uptime but I don't know how to exactly reproduce it.

**Device (please complete the following information):**
 - iOS Version: 12.1.1beta
 - iOS Device: iPhone 5s
 - unc0ver Version:  v3.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[panic-full-2019-05-08-150425.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3168763/panic-full-2019-05-08-150425.ips.txt)
[panic-full-2019-05-10-171220.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3168765/panic-full-2019-05-10-171220.ips.txt)

**Comment by Bitrik** [comment]
Finally, some reassurance that I am not the only one, I believe this is an issue with older devices and how much memory they have. I enabled "Increase Memory Limit" in unc0ver and use PowerSelector to idrestart every so often, as of 1 day of uptime, I have not experienced a random restart. These restarts typically happen between 6-12 hours of uptime. I have done everything to fix my issue, as much as tweeting at pwn with the information of my device, unc0ver version, iOS version and the problem in question.

**Comment by TheSniperzzz** [comment]
Probably older devices have more problems but I read people with newer phones having similiar issues.
The increase memory limit seems to not fix it, at least in my experience, but it may help so I don't know.

Anyway, restarts every 12hours is seriously bad, maybe you have too many tweaks?

Also, you can find the logs in the settings app, then privacy, analytics, analytics data, find the latest file named panic_full and upload it somewhere, rename it by adding a .txt and upload it under the github issue you posted. 
Hope these logs will be useful for fixing the issue.

**Comment by ZerOneX** [comment]
I have an iphone 8+ and have the same behavior.... 

My ipad mini 4 behaves exactly the same.

**Comment by Bitrik** [comment]
> 
> 
> Probably older devices have more problems but I read people with newer phones having similiar issues.
> The increase memory limit seems to not fix it, at least in my experience, but it may help so I don't know.
> 
> Anyway, restarts every 12hours is seriously bad, maybe you have too many tweaks?
> 
> Also, you can find the logs in the settings app, then privacy, analytics, analytics data, find the latest file named panic_full and upload it somewhere, rename it by adding a .txt and upload it under the github issue you posted.
> Hope these logs will be useful for fixing the issue.

After deleting snapchat and noticing the sudden improvement in uptime, I went from 3 tweaks to about 15. After uninstalling Snapchat, I have not had many issues. I recently kept going into safemode but FloatyDock was the culprit. If you have snapchat, I would consider finding an alternative, which I made instagram because they won't ban me for having a jailbroken phone, nor does it give me any stability issues.

**Comment by TheSniperzzz** [comment]
> > Probably older devices have more problems but I read people with newer phones having similiar issues.
> > The increase memory limit seems to not fix it, at least in my experience, but it may help so I don't know.
> > Anyway, restarts every 12hours is seriously bad, maybe you have too many tweaks?
> > Also, you can find the logs in the settings app, then privacy, analytics, analytics data, find the latest file named panic_full and upload it somewhere, rename it by adding a .txt and upload it under the github issue you posted.
> > Hope these logs will be useful for fixing the issue.
> 
> After deleting snapchat and noticing the sudden improvement in uptime, I went from 3 tweaks to about 15. After uninstalling Snapchat, I have not had many issues. I recently kept going into safemode but FloatyDock was the culprit. If you have snapchat, I would consider finding an alternative, which I made instagram because they won't ban me for having a jailbroken phone, nor does it give me any stability issues.

Never used snapchat so unfortunately my problem is not related to it. I don't know what could be the cause but thanks for reporting :)
