### ISSUE TITLE
Beug Safari

### ISSUE THREAD

**Issue by StigiTT** [pwn20wndstuff/Undecimus#1023]
**Describe the bug**
Hello, When I click on the private button on safari my safari freeze

**To Reproduce**
1. Go to 'Safari'
2. Click on 'Private Boutton'
3. Safari Freeze

**Device (please complete the following information):**
 - iOS Version: 12.1.1 b3
 - iOS Device:IPhone SE
 - unc0ver Version: 3.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

**Comment by Bitrik** [comment]
Do you have any notable tweaks installed? This is an issue I do not experience this on my iPhone 6s, running iOS 12.1.2.

**Comment by StigiTT** [comment]
No it just unc0ver I disabled load tweaks and I jailbreaker no more tweaks were activated and its working no more I tried with chimera I tried with chimera I created a snap back chimera and I jailbreaker I reinstalled the same tweaks as on unc0ver and the with chimera it works the private safari button
