### ISSUE TITLE
Random Restarts

### ISSUE THREAD

**Issue by Bitrik** [pwn20wndstuff/Undecimus#1024]
**Describe the bug**
I am experiencing random restarts after about 6-12 hours of uptime, I have reached a day of uptime by idrestarting my phone every so often. I have tried just about everything, including uninstalling all tweaks. I still get these random restarts, I am starting believe that it is a hardware error, as the iPhone 6s is a bit outdated, but still quick.

**To Reproduce**
1. It happens completely randomly, I do not experience overnight restarts, but random restarts.
2. See error

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by iAppleLuvr** [comment]
Are you on the latest version of unc0ver? If so, downgrade to v3.0.0~b49, it seems to be more stable for most.

**Comment by AXL-Kiki** [comment]
I have t say only one « thing » : THANXS !!

**Comment by ZerOneX** [comment]
For sure pwn is already aware about it.... everyone is facing the same issue.

**Comment by beastronz** [comment]
Do you use Snapchat?

**Comment by Bitrik** [comment]
> 
> 
> Do you use Snapchat?

Yes I was recently banned because of the jailbreak, I am on the latest version of unc0ver as well.

**Comment by Bitrik** [comment]
> 
> 
> Are you on the latest version of unc0ver? If so, downgrade to v3.0.0~b49, it seems to be more stable for most.

I tried downgrading to b39 and couldn't jailbreak successfully for some reason, I had System Daemons off and I would respring loop, I turned off tweaks and then the phone would freeze after jailbreaking.

**Comment by StigiTT** [comment]
Restor RootFS And Rejailbreak with unc0ver 3.0.1

**Comment by Bitrik** [comment]
> 
> 
> Do you use Snapchat?

It's funny because I was banned for 24 hours from snapchat and still haven't had a single restart

**Comment by Bitrik** [comment]
> 
> 
> Restore RootFS And Rejailbreak with unc0ver 3.0.1

I can't do what I've already done, after uninstalling snapchat I have had zero issues. Thank god they banned me or I wouldn't have found this out

**Comment by beastronz** [comment]
> > Do you use Snapchat?
> 
> Yes I was recently banned because of the jailbreak, I am on the latest version of unc0ver as well.

A lot of people are having issues with rebooting while using snapchat

**Comment by Bitrik** [comment]
> 
> 
> > > Do you use Snapchat?
> > 
> > 
> > Yes I was recently banned because of the jailbreak, I am on the latest version of unc0ver as well.
> 
> A lot of people are having issues with rebooting while using snapchat

Snapchat is a rat deployed by apple to ruin the jb experience confirmed

**Comment by luixiuno** [comment]
I got the same issue

**Comment by luixiuno** [comment]
No Snapchat
