### ISSUE TITLE
Low Success Rate with MachSwap2 on A10. 

### ISSUE THREAD

**Issue by Jake-12** [pwn20wndstuff/Undecimus#1029]
**Device (please complete the following information):**
 - iOS Version:  11.4.1
 - iOS Device:  iPhone 7+ 
 - unc0ver Version:  3.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Notes**
~Either Reboot after Step 1 
~”Failed to export kernel_task”

**Comment by pwn20wndstuff** [comment]
Fixed in the upcoming version 3.1.0.
