### ISSUE TITLE
iOS 12.2 support

### ISSUE THREAD

**Issue by kalebe2** [pwn20wndstuff/Undecimus#1038]
You see I recently got a new phone a couple weeks ago. It automatically came installed with 12.2. There is now way to downgrade bc 12.1.2 is unsigned and since its new there is no way to get 12.1.2 blobs. Please release a JB for iOS 12.2! A lot of people are in my same boat... stuck in 12.2

**Comment by clarityzzz** [comment]
Pulling out my magic wand to magically suport 12.2... Bam, it works! /s

**Comment by jimmyboyy76** [comment]
I agree, I am on iOS 12.2 and i believe that should be the main priority for the next release of Unc0ver. I know pwn20wnd are struggling for this jailbreak but there are loads of people looking for a jb for iOS 12.2 so hopefully it it released within the best few weeks.

**Comment by jammehcow** [comment]
Also pulling out my magic wand which stops people creating "iOS 12.2/12.1.3+" issues on this repo. Does my wand also close this?
