### ISSUE TITLE
no reload sysyem daemon, no respiring 

### ISSUE THREAD

**Issue by qingfengyishun** [pwn20wndstuff/Undecimus#1039]
the device do not respir after jb once do not open “reload system daemon” , please help to slove the problem, thanks.

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iphone 6pm
 - unc0ver Version: 3.1.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by TheRealKeto** [comment]
Toggle RSD back on. This is an essensial option in order for the jailbreak to work.
