### ISSUE TITLE
unc0ver reboots phone with automatic respring enabled ver 3.1.2

### ISSUE THREAD

**Issue by Cucklord420** [pwn20wndstuff/Undecimus#1040]
When i turn on automatically respring in version 3.1.2 after pressing jailbreak 1 second later my phone reboots and I need to try it again

**Comment by Extremejor** [comment]
Me too.  Have tried Restore RootFS several times, re-installed unc0ver so many times I've lost count.  Everything relevant is up to date (unc0ver 3.1.2, Impactor 0.9.51, using Mac w/10.11.6), even did a restore of my iPhone SE, 11.3.1.  Getting nowhere & giving up.  Sileo didn't work prior and couldn't get iCleaner so I did a restore - I'm glad this is my spare phone!  
![IMG_1784](https://user-images.githubusercontent.com/49847002/58432098-3c178900-805d-11e9-9b4f-cae277108418.jpg)
