### ISSUE TITLE
respring logo freeze

### ISSUE THREAD

**Issue by rutvik1110** [pwn20wndstuff/Undecimus#1041]
when we install new tweak and then we restart our respring board it crases and freezes. And black screen appear. afte a while it turns back to the device

ios version: 11.3.1
uncover version: 3.1.0
ios device: iphone 6s
**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by abear1619** [comment]
I also have this issue when rsd is toggled on. Stuck in respring loop until I reboot. 
When it's toggled off, it properly jailbreaks. 
ios version: 11.3.1
uncover version: 3.1.2 
ios device: iphone 7+

**Comment by 9matson** [comment]
Does it kick you out of the jailbreak entirely after attempting to respring?

**Comment by abear1619** [comment]
No, I have to reboot to get out of the loop.
