### ISSUE TITLE
overnight wireless charging black screen

### ISSUE THREAD

**Issue by SpottiGianmarco** [pwn20wndstuff/Undecimus#1042]
**Describe the bug**
Every morning after overnight wireless charging, the iPhone is blocked on black screen and I'm forced to reboot it (Volume up, Volume down, Power)

 - iOS Version: 12.1.1 beta
 - iOS Device: iPhone 8 Plus
 - unc0ver Version: 3.1.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by 9matson** [comment]
Have you tried the latest version? Offer details if you can. Could be a compatibility issue with a tweak installed. Try experimenting with iCleaner Pro and see what happens.

**Comment by SpottiGianmarco** [comment]
Yes it's the latest version (updated to 3.2.0)
thank you, I'll try iCleaner.

**Comment by SpottiGianmarco** [comment]
Don't work!
