### ISSUE TITLE
Unsupported on iphone 6 plus

### ISSUE THREAD

**Issue by q8wii** [pwn20wndstuff/Undecimus#1045]
Dear all
when i am trying to jailbreak my iphone 6 plus on 12.2 i get message : unsupported .
Please help me with it .

**Comment by yousef157** [comment]
unc0ver currently supports iOS 11.0 - 12.1.2.


please stop believing fake ass 12.1.3 - 12.3.1 fake ass jailbreaks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
