### ISSUE TITLE
Respring & safe mode entry loop

### ISSUE THREAD

**Issue by Diam0ndCrack3d** [pwn20wndstuff/Undecimus#105]
Sometimes when one of my apps is acting up & bugging out. I normally just try to close the app and hold the power button and hold the home button after letting go of the power button and all devices memory is cleared. But when I was jb with electra this is one issue that I did not have. So this is due to the new tool Unc0ver. I'm on latest ver. 1.1.2 and ios 11.3, iphone 6. This happens everytime that an app starts to act up such as youtube and twitter like a lag or stutter. Then when using power-selector by ichitaso to both enter a re-spring and safemode they both do a endless loop.

**Comment by Samgisaninja** [comment]
This is not a code-level issue with unc0ver, you can get technical support with your setup via r/jailbreak
