### ISSUE TITLE
 (not cydia) Freezes on the latest 3.1.2

### ISSUE THREAD

**Issue by JamieBerghmans** [pwn20wndstuff/Undecimus#1050]
At a random moment the phone will freeze for a minute and then respring (not reboot). This has happened about 5 times since installing it yesterday. Note: I am running the same tweaks as on 3.0.1. (Multiple people on reddit and on the jb discord have also reported this problem). Just in case I also tried rootfs but that didn't fix it (and didn't for the other users either).

I wish I could tell you how to reproduce it, but I've been trying for 15 minutes and I can't find it a trigger for it, seems like it's happening randomly (Like it was on b50)

 - iOS Version: 12.1.1b3
 - iOS Device: iPhone X
 - unc0ver Version: 3.1.2

 - [ ] this is a bug others will be able to reproduce
 - [ X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ X ] this issue is present after a rootfs restore
 - [ X ] this issue is present on the latest version of unc0ver

I've checked from CrashReporter and Cr4shed but there are no crashes reported. Any other way I can provide logs?

**Comment by joelkwek** [comment]
having this issue as well, randomly the device would, with no new tweaks installed:
1. App in use becomes unresponsive
2. Swiping up to minimize the unresponsive app would cause any icon in home screen being tapped to freeze the entire phone
3. few minutes later, phone re-springs and problem disappears
4. this issue repeats randomly 3-4 times a day :(
