### ISSUE TITLE
App says there is an update available while on the latest version 

### ISSUE THREAD

**Issue by ctalbot2004** [pwn20wndstuff/Undecimus#1051]
**Describe the bug**
When clicking check for update in the Unc0ver app, it says there is an update available even if you are on the latest version. 

**To Reproduce**
1. Go to settings page
2. Scroll down and click “check for update”
3. It says “an update is available”

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.0
 - iOS Device: iPhone X
 - unc0ver Version: 3.1.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

**Comment by Assfugil** [comment]
Fixed in v3.1.3

**Comment by 9matson** [comment]
Close the issue too
