### ISSUE TITLE
Going into an infinite respring loop. 

### ISSUE THREAD

**Issue by xlln00bllx** [pwn20wndstuff/Undecimus#1054]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
Whenever I try to respring my device, it goes into an infinite restring loop and I have to soft reset to get out of it and then re-jailbreak my phone.

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone X
 - unc0ver Version: 3.1.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by xlln00bllx** [comment]
Update: It seems that is it not the update, I have tried multiple restoreFS, I've tried reseting everything in my phone and reinstalling unc0ver 3.2.1 and even older ones like 3.0.1 which is the one that I had when everything was running perfectly. However, I'm still having issues when I respring my phone and another bug that I also notice is with the UnSub tweak. Here is what I'm getting. Please Help :(
![IMG_0001](https://user-images.githubusercontent.com/51066121/58453684-aa9e2a80-80e1-11e9-9b7a-cb1b053852e8.png)

**Comment by 9matson** [comment]
Try installing everything. (If you haven't already). If you end up going into a respring loop, do a "Hard reset" on your iPhone to get out of it. Check your version of iOS to see if is compatible. Check "iPhone Storage" in "Settings - General" to see if you have ANY OTA Updates of a future, uncompatible version. If you do, delete it immediately.
