### ISSUE TITLE
Error Fatal  45 Unable to refresh icon cache

### ISSUE THREAD

**Issue by alekssamos** [pwn20wndstuff/Undecimus#1055]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to 'settings'
2. Click on 'reinstall Cydia' or 'refresh icon  cache'.
3. Sjailbreak.
Error (Fatal)
Errno: 45 Test: runCommand("/usr/bin/uicache", NULL) == ERR_SUCCESS Filename: jailbreak.m Line: 1545 Function: jailbreak Description: Unable to refresh icon cache.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iphone se 32 gb
 - unc0ver Version: 3.1.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Murrotini** [comment]
Hi,

Cydia  and the tweaks are still actuaaly working . I have just uninstalled " icleaner" and now everything is fine.

**Comment by 9matson** [comment]
I'm having the same problem too.

It all started with two installed tweaks interfering with each other, which caused my phone to be sent out of the jailbreak state. I was never able to get back in.

 I've tried to delete everything and start from scratch, tried the xCode "revoke certificates", Restore RootFS, Deactivating Reload System Daemons, Activating Reset Cydia Cache, Deactivating "Load Tweaks" etc etc.

I've gotten errors such as a white unc0ver screen upon opening (I shutdown and boot my phone to fix this)

The Fatal error Errno: 45 mentioned above,

The Fatal Error Erno: 2

I'm at a loss as for what to do. i would appreciate some help.

Thanks.

**Comment by Murrotini** [comment]
Hi 

Install the latest Version of uncover 3.1.2 and select option to reinstall cydia and load tweaks only.. After done, uninstall the Last tweaks you had and respring your Device..keep your internet is on before attempting the jailbreak...

**Comment by 9matson** [comment]
Thank you for your response!


I tried doing this with the latest version of unc0ver (3.1.3). First opened the app and the white background was there, but nothing was loading, (had to reboot). After that and activating the reinstall cydia and load tweaks only, I got the same result. 

Error (Fatal) Errno:45 Unable to refresh icon cache. Line 1562

**Comment by sritarun3** [comment]
Even i get the same problem on iphone 7

**Comment by theTobster500** [comment]
i had the same problem and noticed, that even without respringing some tweaks had been loaded. i went into icleaner and cleaned and resprung and after the respring everything was fine.

**Comment by NainRouge** [comment]
Error persisted into version 3.2.0

**Comment by 9matson** [comment]
The error is gone in version 3.2.1. Update to this one if you're having any problems.
