### ISSUE TITLE
Errno 30 Snapshot (iPhone Storage Calculating Size bug)

### ISSUE THREAD

**Issue by OnionHacks101** [pwn20wndstuff/Undecimus#106]
I understand this has been shown as a problem before however mine seems to be unfixable. I'm using an iPhone 6s on iOS 11.2.5. I've never had serious problems until I upgraded from RC8 to version 1.1.1 and greater. I have the glitch where my iPhone storage is infinitely calculating. It started when my cydia glitched and I had to re-jailbreak but I wanted the newest version in hopes of bug fixes. It wouldn't get passed step 25/56. I attempted to use ElectraRemover to get back to a sort of Rooted state (Restore RootFS via unc0ver won't work at all. I turn it on, wait like 30 seconds, then go to jailbreak and click it while restore rootfs is still on, it still can't pass 25/56) and ElectraRemover successfully removed my cydia yet I still had the glitch. I've even gone as far as attempting to get Th0r and Electra instead but I've had absolutely no luck and I refuse to upgrade my phone to ios12+. I beg I get some kind of positive feedback instead of an empty handed response because I've stressed myself over attempting to solve the problem with no luck.

**Comment by yungmichael** [comment]
I was in the same boat I used jb remover  iOS  11.2xx  users I’m running 11.2 i been stuck for 6 days until I found this on twitter 
I’m back jail broken :)
https://twitter.com/pwned4ever/status/1058831893196562432?s=12

**Comment by OnionHacks101** [comment]
@yungmichael thanks for the feedback, i’m currently in classes but i’ll update you on if this works later.

**Comment by Samgisaninja** [comment]
Comment removed due to pwned4ever violating Electra team copyright. 

Please don’t use that, it’s stolen code.

**Comment by Samgisaninja** [comment]
Sorry didn’t mean to close.

**Comment by OnionHacks101** [comment]
@yungmichael @Samgisaninja (sorry if I'm not suppose to/annoys you for pinging) My key problem was fixed thank you very much for your help, tho I get the Errno 2 error sometimes now I don't mind as much, my problem has been solved though, thanks again!

**Comment by Cryptiiiic** [comment]
@OnionHacks101 please don't listen to michael, he is recommending something we don't allow here. It's made by an average user that is trying to be a developer.
