### ISSUE TITLE
Uncover Dark iOS 12.1.1 iPhone 8 PLUS 64gb

### ISSUE THREAD

**Issue by Gerardo323** [pwn20wndstuff/Undecimus#1065]
![GitHawk Upload by Gerardo323](https://i.imgur.com/bqjptmT.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gerardo323** [comment]
Was jailbroken with uncover 3.1.2 until I started getting random reboots and ran into a crash ![GitHawk Upload by Gerardo323](https://i.imgur.com/1E8jxlO.jpg) 

So I decided to try out uncover dark to see if it will fix the problem but no 😕 

I still had tweaks installed I dont know if that’s causing the problem. Did the root recover and nothing still  



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HelloDefender12** [comment]
Yeah this even happened in my iPhone 5s :(

**Comment by corurhaw** [comment]
You guys have some missing dependencies. Switching jailbreaks could cause issues, however as unc0ver dark is branched off of un0ver, it should largely use the same files. Try turning on airplane mode on the OP. I’m not the developer, but if the code has inline documentation at the least, I may be able to give you more information. I would restore rootfs. Do a clean install with the latest version of unc0ver. Run the app after a fresh reboot. Turn on airplane mode, wait 30-60 seconds. Make sure Power is plugged in, low power mode is not on, and dnd probably doesn’t need to be on. There’s a variety of things to try.

**Comment by corurhaw** [comment]
Also note, unc0ver dark uses a different apt version, and attempts to make unc0ver compatible with Sileo. It’s not quite the same. BigBoss repo isn’t supported by Sileo. Without knowing more, I could not say that they are interchangeable, but it doesn’t seem so on it’s face. I may be wrong. Don’t use them both w/o the technical knowledge to know the apt are compatible.
