### ISSUE TITLE
post.sh: dpkg-scanpackages: command not found

### ISSUE THREAD

**Issue by piaoapiao** [pwn20wndstuff/Undecimus#1066]
**Describe the bug**
open project build. produce the error message "/Undecimus/post.sh: line 74: dpkg-scanpackages: command not found". I can call  dpkg-scanpackages normally  in console ,but Xcode install unC0ver ,the shell produce error, I modify the  below shell   ,solve this  problem .what is the reason ?
 
#if [ -f ~/.profile ]; then
#    ....
#fi

if [ -f ~/.bash_profile ]; then
     . ~/.bash_profile
fi

why the result ?

**To Reproduce**
1. open project 
2. run Xcode to install unC0ver

**Screenshots**
<img width="614" alt="image" src="https://user-images.githubusercontent.com/1860851/58446101-fbd60a80-8131-11e9-9c7e-d68cb2025a49.png">

**Comment by CoderTonyChan** [comment]
I have the same question.I should install dpkg-scanpackages?

**Comment by CoderTonyChan** [comment]
I install dpkg and It is OK now.

**Comment by kotireddyaluri** [comment]
resolved after installing dpkg
brew install dpkg

**Comment by qq280948982** [comment]
> resolved after installing dpkg
> brew install dpkg

it works for me, thanks~
