### ISSUE TITLE
Error (Fatal) : ErrNo 2

### ISSUE THREAD

**Issue by Axavius** [pwn20wndstuff/Undecimus#1068]
**Describe the bug**
Errno: 2
Test: runCommand("/usr/bin/uicache", NULL) == ERR_SUCCESS
Filename: jailbreak.m
Line: 1545
Function: jailbreak
Description: Unable to refresh icon cache.

**To Reproduce**
1. Go to 'settings'
2. Click on 're-install cydia'
3. Jailbreak

**Screenshots**
![image1](https://user-images.githubusercontent.com/51120399/58476118-c805df80-8147-11e9-8fdc-da3f36e506fe.png)

**Device (please complete the following information):**
 - iOS Version:  12.1.2
 - iOS Device:  iPhone 6 16gb
 - unc0ver Version:  3.1.0 / 3.1.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by thecoldblooded** [comment]
same error. please help

**Comment by Gurjeetchahal91** [comment]
Same Situation with me , unable to jailbreak even with latest version of Uncover

**Comment by 9matson** [comment]
Have you tried uninstalling everything first, then starting from scratch. Delete cydia and uncover completely. When redownloading uncover using cydia impactor, first try to revoke certificates using "Xcode" then go from there.

**Comment by Gurjeetchahal91** [comment]
Actually I moved to electra 1.3.2 , jailbreak with electra successfully , then again move back to unc0ver and everything works fine , thanks for your help ,

Get Outlook<https://aka.ms/qtex0l> for iOS📱
________________________________

**Comment by HelloDefender12** [comment]
Same it also seemed to have damaged my apps I just downloaded.
