### ISSUE TITLE
successful jailbreak but no cydia or tweaks

### ISSUE THREAD

**Issue by kid1carus** [pwn20wndstuff/Undecimus#1072]
I am able to successfully jailbreak and it seems as though cydia does get installed because I can open it from the unc0ver settings page; however, it does not show up on my springboard nor do any of the tweaks i install.  I ran both uicache and ldrestsrt and neither have made a difference.  The issue persists even if I restore rootfs and attempt the process again.  

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device:  iPad Mini 2 with Retina (Wifi only)
 - unc0ver Version: 3.1.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

[unc0ver Log file](https://pastebin.com/5uM7HADv)

**Comment by yousef157** [comment]
Did you try Refresh Icon Cache? It's in unc0ver settings.
