### ISSUE TITLE
Can’t Log In to Cydia via Google

### ISSUE THREAD

**Issue by RichardFairbanks** [pwn20wndstuff/Undecimus#1074]
**Describe the Bug**
Since jailbreaking iPhone 7 Plus running iOS 12.1.2 with unc0ver a week ago (currently running 3.1.3),  I can’t login to Cydia; I try many times every day.
I keep getting the error:
> Cydia experienced a server error.
> Please check back again in a few hours.

Any suggestions? I can login via Facebook, but all my purchases were via a Google login.
Thanks!

**To Reproduce**
1. I launch Cydia
2. I choose “Manage Account”
3. I select “Sign in with Google”
4. Cydia launches Safari
5. My Google account is properly listed, and I select it
6. I get to the alert, “Open this page in “Cydia”?
7. I select “Open”
8. Cydia reports the error:
> Cydia experienced a server error.
> Please check back again in a few hours.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: 9,2 (iPhone 7 Plus)
 - unc0ver Version: 3.1.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Comment by TheRealKeto** [comment]
The Cydia Store was unfortunetly closed down. I don't see why you would need to access your purchases as most of they may not be compatible with your device and firmware, however, you should not be restricted to accessing your purchases. It could just be that the Cydia Store was closed and with it the ability to sign into Google.

**Comment by RichardFairbanks** [comment]
Thanks for the response!

I am running the Cydia that is installed with unc0ver v3.2.1: Cydia64_1.1.32-b16, and still getting the same error:
```
Cydia experienced a server error.
Please check back again in a few hours.
```
