### ISSUE TITLE
Flickering bug

### ISSUE THREAD

**Issue by the-casle** [pwn20wndstuff/Undecimus#1077]
Apps are flickering when entering and exiting, easiest way to replicate is through the official reddit app and accessing the app switcher a couple of times. Like to add that this only started occurring when I upgraded from b50 to the most recent version. 

https://m.imgur.com/a/z0xhndr

**Comment by Un4givenPG** [comment]
I would like to report the same issue, it happens even in safe mode, so it isn't caused by a tweak.

**Comment by Un4givenPG** [comment]
> Apps are flickering when entering and exiting, easiest way to replicate is through the official reddit app and accessing the app switcher a couple of times. Like to add that this only started occurring when I upgraded from b50 to the most recent version.
> 
> https://m.imgur.com/a/z0xhndr

Maybe reopen the issue with the official issue template for it to not be ignored, cause it is annoying af to deal with it.
