### ISSUE TITLE
Phone not jailbreaking

### ISSUE THREAD

**Issue by Lettucecake** [pwn20wndstuff/Undecimus#1079]
Hey,
My phone isn't jailbreaking on 3.2.0, I have no idea why. It successfully "jailbreaks", but doesn't respring - just goes blank. Left it for 10 mins, still nothing. 

iPhone SE - iOS 12.0.1
Works on 3.0.1 and 3.1.3., not 3.2.0(tried with RSD off)
Tweaks kept at a minimum, only snowboard and eclipse 12

**Comment by EzaDragon** [comment]
I have the same problem. Any ideas?
