### ISSUE TITLE
Utilities section is buggy

### ISSUE THREAD

**Issue by KMamedoff** [pwn20wndstuff/Undecimus#108]
It is almost impossible to tap and select one on unc0ver 1.1.4 and some older versions.

**Comment by Samgisaninja** [comment]
Can you please explain what you mean? what device are you on, what do you mean by "impossible to tap" (works fine for me on my X and 5S)?

**Comment by KMamedoff** [comment]
[Please watch this](https://youtu.be/kLmGexfawo8)

**Comment by Cryptiiiic** [comment]
@KMamedoff Seems like you are the only person with this issue. Unless you can find other people with this issue, I'm going to close this in around a day or 2.

**Comment by KMamedoff** [comment]
it seems to be only happening to me. I cannot reproduce this issue on other devices and I tried to download unc0ver from different sources including using my own developer account with Cydia Impactor and issue still persists. Interesting.

**Comment by Samgisaninja** [comment]
I’ve reproduced this issue and will fix as soon as we merge substrate into master.

**Comment by KMamedoff** [comment]
How did you reproduce it? Is that "didUnhighlightItemAt" issue?

**Comment by Samgisaninja** [comment]
Was an autolayout mistake
