### ISSUE TITLE
Camera app reboots the device

### ISSUE THREAD

**Issue by TheSniperzzz** [pwn20wndstuff/Undecimus#1086]
**Describe the bug**
Opening or using (example: taking a photo) the camera app completely reboots the phone.
This happens randomly, not everytime.
Please, let me know if I can provide more info / logs, I'd like to help fixing this annoying issue.

**To Reproduce**
No idea what's the cause but many people seems to have this problem.
Check this reddit comment: https://bit.ly/319Ju58

**Device (please complete the following information):**
 - iOS Version: 12.1.1beta
 - iOS Device: iPhone 5s
 - unc0ver Version: v3.2.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[panic-full-2019-06-03-214210.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3251017/panic-full-2019-06-03-214210.ips.txt)

**Comment by PoulPe67** [comment]
Same here for iPhone 7 Plus, iOs 12.1.2, Unc0ver 3.2.1 i try to take a picture in message app, and i touch the bouton. And respring :/ gl

**Comment by 420Dope** [comment]
Same for me in my iPhone 7, iOS 12.1.2, unc0ver 3.2.1.  Phone respring randomly when i try to take a photo.

**Comment by Pflegusch** [comment]
Same here, iPhone 6s, iOS 12.1.2, unc0ver 3.2.1. For me the issue also appears in Snapchat when I try to take a photo.

**Comment by TheSniperzzz** [comment]
lucky you that you only respring, mine reboots into non jailbroken state :D

**Comment by Greg212** [comment]
Same here! iPhone 7 on iOS 12.1.2 with unc0ver 3.2.1. It randomly reboots when I open camera app. Sometimes even when I try to take a picture inside the Messages app.

It's been there since unc0ver 2.x

**Comment by Pflegusch** [comment]
Fixed it by uninstalling 2 tweaks that were probably causing problems. Get yourself iCleaner and disable some of the newest or suspicious tweaks and see if it helps. Been runing unc0ver 3.2.1 for the last few days without any problems.

**Comment by DOCaCola** [comment]
My Iphone 5s 12.1.1 also reboots (not resprings) very regularly when invoking the camera app in jailbroken state. Everyone here who reported a respring actually doesn't have an Iphone 5s.

**Comment by TheSniperzzz** [comment]
> My Iphone 5s 12.1.1 also reboots (not resprings) very regularly when invoking the camera app in jailbroken state. Everyone here who reported a respring actually doesn't have an Iphone 5s.

Have you found a fix? this problem is getting so annoying.
I restored rootfs and I got a reboot the following day (and I didn't install anything), so it's not tweak related

**Comment by TheSniperzzz** [comment]
> Same here! iPhone 7 on iOS 12.1.2 with unc0ver 3.2.1. It randomly reboots when I open camera app. Sometimes even when I try to take a picture inside the Messages app.
> 
> Installed tweaks:
> AnsweringMachine X
> Callbar X
> Dune
> Neptune
> Cuboid

It's probably not tweak related since I restored rootfs and I got a reboot the following day, without installing tweaks.

**Comment by TheSniperzzz** [comment]
> My Iphone 5s 12.1.1 also reboots (not resprings) very regularly when invoking the camera app in jailbroken state. Everyone here who reported a respring actually doesn't have an Iphone 5s.

Have you updated to iOS 12.4? If so, do you still have the camera random reboots with latest uncover + iOS 12.4?

**Comment by TheSniperzzz** [comment]
> Same here! iPhone 7 on iOS 12.1.2 with unc0ver 3.2.1. It randomly reboots when I open camera app. Sometimes even when I try to take a picture inside the Messages app.
> 
> Installed tweaks:
> AnsweringMachine X
> Callbar X
> Dune
> Neptune
> Cuboid

Have you updated to iOS 12.4? If so, do you still have the camera random reboots with latest uncover + iOS 12.4?

**Comment by DOCaCola** [comment]
The issue disappeared for me with the later versions of unc0ver. Still on 12.1.1

**Comment by TheSniperzzz** [comment]
> The issue disappeared for me with the later versions of unc0ver. Still on 12.1.1

Thanks :) If you get a reboot please let me know, I would really appreaciate it :)
