### ISSUE TITLE
Unable to find kernel offset for trustcache

### ISSUE THREAD

**Issue by TinhoXu** [pwn20wndstuff/Undecimus#1088]
iOS Version: 12.1.1beta
iOS Device: iPhone 7P
unc0ver Version: v3.2.1

![微信图片_20190605171213](https://user-images.githubusercontent.com/6636310/58944872-3c2e2c00-87b5-11e9-85e7-13e6386d1a21.png)

**Comment by pwn20wndstuff** [comment]
What’s your iOS build version?

**Comment by c0d3z3r0** [comment]
same here with current master and iOS 11.2.2

**Comment by TinhoXu** [comment]
12.1.1(16C5050a)

**Comment by Yongle-Fu** [comment]
same 11.1.2(15B202)

**Comment by ppamorim** [comment]
same 11.2.6 (15D100)
