### ISSUE TITLE
Assets are too huge

### ISSUE THREAD

**Issue by hirakujira** [pwn20wndstuff/Undecimus#109]
The "cloud" background is too huge and is not necessary for a jailbreak tool. By editing (remove) the background images, the IPA can be resized from 61MB to 12MB.

**Comment by sagexy** [comment]
@pwn20wndstuff the "Clouds" images can be compressed?

**Comment by hirakujira** [comment]
They might can be converted to .jpg file to decrease the size, or just use one resolution for all devices, since @2x @3x files are much bigger. Another solution is cropping the image, since the resolution of @3x is 6717x3618, which is bigger than the screen resolution of iPhone XS Max.

**Comment by pwn20wndstuff** [comment]
I have tried that before but then it sucks on the bigger iPads.. (e.g. iPad Pro 12.9”)

**Comment by Samgisaninja** [comment]
why do we need theos?

**Comment by Cryptiiiic** [comment]
@Samgisaninja I asked months ago and never got a clear answer other than "this was based on the Rollectra11 project"
