### ISSUE TITLE
SSH Only option toggles itself back on

### ISSUE THREAD

**Issue by sagyakwa** [pwn20wndstuff/Undecimus#1091]
Whenever I toggle off the 'SSH Only' option, it seems like it toggles itself back on, and doesn't install Cydia. After I jailbreak with it off, when I look later, it's back on, and it seems like that's what it did during the JB process. No Cydia, but able to ssh into device.

 - iOS 12.1:
 - iPhone XS Max 
 - unc0ver Version 3.2.1

 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by scotchdelisser** [comment]
Dude their ain’t no Cydia on A12 so ur completely wasting ur time having Unc0ver installed!

**Comment by TheRealKeto** [comment]
unc0ver currently does not fully support devices with an A12 bionic chip. The only support for A12 currently is SSH, hence why the option "SSH Only" toggles itself back on. This isn't a bug. 

If you're trying to have tweak injection support, wait for unc0ver to have support for your devices or look for alternatives that are currently available (this being Chimera only, which does have A12 support).
