### ISSUE TITLE
Random Reboots Every Few Hours (iP8)

### ISSUE THREAD

**Issue by flappy-pat** [pwn20wndstuff/Undecimus#1093]
**Describe the bug**
My iPhone 8 running 12.1.2 will randomly restart every few hours on the latest unc0ver (3.2.1). Before the reboot, my screen will go completely black for a moment before the apple logo appears. I have tried restoring with Succession but the issue remains.

**To Reproduce**
I do not think there are steps that 100% guarantee a reproduction of this bug. 

**Screenshots**
No screenshots are available/applicable. 

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 8 (10,4)
 - unc0ver Version: 3.2.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver
 - [x] this issue is present after a restore using Succession

**Logs**
No logs are available.

**Comment by clarityzzz** [comment]
Without logs, there's no way to debug this.

**Comment by TheRealKeto** [comment]
@flappy-pat What version of Succession did you use? Did this issue begin after upgrading to the latest version of unc0ver? Have you attempted to downgrade to another version of unc0ver?

**Comment by flappy-pat** [comment]
I used Succession v1.0 as newer version were not working for me. I do not
remember when exactly the issue began, but it was before I used Succession
for the first time (the issue was what prompted me to use succession). I
have tried downgrading unc0ver, beta 49 did not work for me, nor did
another I forget the name of.
