### ISSUE TITLE
A12 -12X support availability?

### ISSUE THREAD

**Issue by chadie002** [pwn20wndstuff/Undecimus#1094]
When will the support for tha a12 - 12x will come out.

Specially Cydia substrate and Cydia app itself.

Hope to use it..

#ipxsmax user here

**Comment by scotchdelisser** [comment]
Sometime in 2020.

**Comment by ZenIsBestWolf** [comment]
Cydia Substrate is not under the control of Pwn, and shouldn't be posted here. Cydia Substrate is owned and maintained by Jay Freeman aka saurik. Just be patient for A12 support, it will be coming eventually.
