### ISSUE TITLE
[Bug] unc0ver app "Share Diagnostics Data"

### ISSUE THREAD

**Issue by jackyjacker88** [pwn20wndstuff/Undecimus#1095]
The UI shows just the background image of unc0ver app after pressing "Share Diagnostics Data"

**To Reproduce**
1. Go to unc0ver App
2. Click on 'Settings'
3. Click on 'Share Diagnostics Data'
4. Select 'Save in Files'
5. Save it. Now it jumps back to the unc0ver app and now just the background image is shown.

**Screenshots**
![IMG_2020](https://user-images.githubusercontent.com/24219803/59149939-4c941000-8a1c-11e9-9f6b-fd699f5db480.png)

**Device (please complete the following information):**
 - iOS Version: 12.1.1b3
 - iOS Device: iPhone9,3
 - unc0ver Version: 3.2.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by 877dev** [comment]
Same here, mine shows black background as I have the dark theme. Happens every time and I have to force quit the app.

iOS 12.1.2
iPhone 10,4
Model D201AP
Unc0ver 3.2.1
