### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by johnsmith1232541** [pwn20wndstuff/Undecimus#1103]
**Describe the bug**
I clones the repository to Xcode 10.2.1. I attempted to build but there were several errors. I made sure all files were downloaded correctly and I even tried using the source code from other versions, but the same errors are still there. I'm uploading a screenshot.

![Screen Shot 2019-06-12 at 8 50 18 AM](https://user-images.githubusercontent.com/51755293/59366458-31145800-8cef-11e9-912e-027f62dd1ef9.png)

**Device (please complete the following information):**
 - iOS Version: 12.2, though I'm just interested on making it build.
 - iOS Device: iPhone XS Max
 - unc0ver Version: Latest

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Halo-Michael** [comment]
You are not downloaded correctly

**Comment by johnsmith1232541** [comment]
How should I download it?

**Comment by johnsmith1232541** [comment]
Actually I got it to work. Apparently, when I use my actual phone it works no problem but when I use a simulator the problem happens.

**Comment by bigrck64** [comment]
Confirmed, you have to connect one real iphone to your mac to generate a working build of undecimus.

**Comment by bigrck64** [comment]
After more test, I can also confirm that "Generic iOS Device" is working well (so without connecting any real phone on your computer). The important point is to keep the undecimus scheme in "Debug" state when you build project. If you are generating on "Release" build (with Product > Archive for example), unc0ver won't be able to find "offset for trustcache" during jailbreak process.
