### ISSUE TITLE
“No service”

### ISSUE THREAD

**Issue by NaniNexro** [pwn20wndstuff/Undecimus#1104]
Okay so this just recently started being an issue when I was jailbroken a month  ago EVERYTHING was fine but now all it keeps saying is “no service you need to update the iPhone in order to use it” but I wanna keep my jailbreak
![AF1AED67-1B4F-4A1E-AD39-18A58B1371AC](https://user-images.githubusercontent.com/51763699/59385433-54142b80-8d32-11e9-8d84-d0abd989e088.png)

**Comment by johnsmith1232541** [comment]
Do they mean an iOS update or a carrier update?
If it's a carrier update, you can install it without losing the jailbreak (I believe, I've never done one myself). In this case you'd have to go to Settings -> General -> About. Go down the page to Operator / Carrier. Click Operato, wait about 10-15 seconds.There should be an update available for you there

**Comment by hsharma96** [comment]
I've been getting that "No service" as well. Started to drop signal all of sudden and I thought I was the only one. It's definitely a bug. I'm using version 3.1.3.

**Comment by qiuyi21** [comment]
If enable "Reload System Daemons", cellular service is randomly crashing. It happens on my iPhone7(iOS 12.1) often.
