### ISSUE TITLE
Mach error

### ISSUE THREAD

**Issue by ASCEND1NG-VO1D** [pwn20wndstuff/Undecimus#1108]
This is the error when using AutoTouch “Send message failed, error operation couldn’t be completed. (Mach error 268435459 - (ipc/send) invalid destination port)” it makes autotouch unusabel and is very annoying. I am using the iPhone 8 on iOS 11.4.1. I have done much troubleshooting and have used autotouch fresh after restoring to the original root file system and determined it is the Un0ver jailbreak as this problem does not occur on Electra

**To Reproduce**
1. Go to 'http://apt.autotouch.net/ or http://beta.autotouch.net/‘
2. Download Autotouch
3. Open the Autotouch application

**Screenshots**
(I already typed the error)

**Device (please complete the following information):**
 - iOS Version: iPhone 8
 - iOS Device: 11.4.1
 - unc0ver Version: 3.2.1 (latest)

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by itseverydsybrosieyhthr** [comment]
What
