### ISSUE TITLE
Can I jail fresh new device without activation?

### ISSUE THREAD

**Issue by hasnogaems** [pwn20wndstuff/Undecimus#1112]
I want to jailbreak fresh new ipad air, I connected it to the pc, in itunes pressed next and that is what on the screen: https://imgur.com/LUTE9uf
On some sites it tells me "If device not activated and requires enter Apple ID -> jailbreak not possible."
But it ask me nowhere to activate or enter apple id, but device is new, I never login into any apple id on it, can I just go with jailbreak?

**Comment by TheRealKeto** [comment]
Please provide more info about what you see when you are setting up you iPad (ex: Provide screenshots of (perhaps) a screen where you think you are stuck on) as I'm not sure what you mean by "having to activate" your iPad. If your iPad is iCloud locked, this can easily be bypassed by several tools (such as 3uTools).
