### ISSUE TITLE
Cant install IPA onto my phone?

### ISSUE THREAD

**Issue by vinchenzo543** [pwn20wndstuff/Undecimus#1113]
Whenever i try to use impactor to install the ipa i get the error code
file: provision.cpp; line 81; what;

ios/submitDevelopmentCSR =7460
You already have a current iOS Development certificate or a pending certificate request.
![Capture](https://user-images.githubusercontent.com/52139271/59981930-70388800-95d0-11e9-83e3-9261a77ccac2.PNG)

Ive got an iphone 6s on 11.4.1
i have tried ignition but it wont install it either, it keeps failing "unable to download unc0ver at this time"
Can anyone help with my issue?

**Comment by yousef157** [comment]
Ignition is revoked. Use TweakBox.

**Comment by vinchenzo543** [comment]
Thankyou, i didnt know tweakbox had unc0ver
