### ISSUE TITLE
How can I donate

### ISSUE THREAD

**Issue by xiaozhuai** [pwn20wndstuff/Undecimus#1114]
You did a great job! Thank you!
It's there a way to donate? PayPal or something ?

**Comment by luigia** [comment]
Patreon and PayPal links can be found on the [releases page](https://github.com/pwn20wndstuff/Undecimus/releases).

**Comment by xiaozhuai** [comment]
Thank you luigia.
Thank you pwn, I just donate $100 for your hard work with all my respect.
<img width="842" src="https://user-images.githubusercontent.com/4773701/60147887-9ee97500-9801-11e9-8554-759cc021960e.png">
