### ISSUE TITLE
Unable to update after unjailbreaking

### ISSUE THREAD

**Issue by q-lng** [pwn20wndstuff/Undecimus#1115]
**Describe the bug**
I am unable to do OTA updates after unjailbreaking my iPhone.

**To Reproduce**
Go to Settings > General > Software Updates

**Screenshots**
![IMG_69C002890A15-1](https://user-images.githubusercontent.com/48022083/60105639-f3d6ae00-9763-11e9-8c5a-0ec4c4655252.jpeg)
(means : "Unable to Check for Update. An error occurred while checking for a software update." )

**Device (please complete the following information):**
 - iOS Version: 12.0 (12.3.1 now, see below)
 - iOS Device: iPhone X
 - unc0ver Version: 3.0.0b-49

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

More infos : 

So, i was using iOS 12.0 with unc0ver 3.0.0b-49. With the iOS 13 beta available i was curious and like to try it.
so i unjailbreak my iPhone; doing a RootFS restore, and after installing the iOS13 beta profile, i saw that OTA updates are unavailable.

So i was locked in 12.0 with no jailbreak. With my iPad OTA Updates works (i have installed iPadOS13 on it), so it don't comes from my network or something like that.

Also i can do updates from iTunes, so now i am on 12.3.1 and the problem isn't solved.

I think it comes from the hosts file, but can't be sure because i am not jailbroken anymore and can't read / modify it.

I would like to add that this topic is more here to know if it is "normal" because of unc0ver or this is an unknown issue. Also it can prevent some of you that want to unjailbreak your iDevice to install iOS13 directly.

**Comment by q-lng** [comment]
ok little update:
![Capture d’écran 2019-06-25 à 16 42 55](https://user-images.githubusercontent.com/48022083/60108081-53cf5380-9768-11e9-9beb-092e022577d6.png)
"iPhone cannot be restored because the internal program is damaged"

in DFU mode i have the same. that's quite scary right now.

**Comment by q-lng** [comment]
is https://github.com/pwn20wndstuff/Undecimus/pull/1063 the answer to my question basically ?

**Comment by q-lng** [comment]
Ok so for people who want a solution : 

MAKE A SAVE OF YOUR IDEVICE ON ITUNES ! Even if you have the same problem.

Restore your iDevice from iOS directly, not from iTunes.

After that you can restore your save and make OTA updates :)

I close the thread

**Comment by reiyua** [comment]
@q-lng Hiya! i have tried your steps but they still do not work for me.

**Comment by lanadelclown** [comment]
> @q-lng Hiya! i have tried your steps but they still do not work for me.

Did you ever find a solution for this?

**Comment by reiyua** [comment]
> > @q-lng Hiya! i have tried your steps but they still do not work for me.
> 
> Did you ever find a solution for this?

I ended up just reinstalling the iPad via iTunes on my Windows workstation. I had to wipe all my data in the process off my phone but I had everything backed up via thins like Google Drive and OneDrive.
