### ISSUE TITLE
SSL Troubles

### ISSUE THREAD

**Issue by icYFTL** [pwn20wndstuff/Undecimus#1125]
**Description**
I can't add some repos and install some tweaks-dependences.
For example [repo]: repo.xarold.com (look at pic1)
For example [tweak]: NewTerm2 (look at pic2)

**Screenshots**
![pic1](https://user-images.githubusercontent.com/27778089/61097666-d5132f80-a464-11e9-8aee-77b34a3af5f8.png)
![pic2](https://user-images.githubusercontent.com/27778089/61097682-e3f9e200-a464-11e9-875d-2ae736b5ef7f.png)

**Device (please complete the following information):**
 - iOS Version: 12.1.4
 - iOS Device: iPhone 6s Plus
 - unc0ver Version: Undecimus-v3.3.0.b2

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Request it.

**Comment by ZenIsBestWolf** [comment]
This is a sketchy and illegitimate looking website/repo. The SSL certificates for the webpage are probably garbage, remove that repo. This has nothing to do with unc0ver itself.
