### ISSUE TITLE
jailbreak successfully,no cydia icon.open cydia in unc0ver settings and installed several apps,no icon too.icon cache already refreshed many times

### ISSUE THREAD

**Issue by SINOPW** [pwn20wndstuff/Undecimus#1128]
![image](https://user-images.githubusercontent.com/44157509/61108528-13d0d600-a4b5-11e9-8615-2b9165cddac3.jpg)
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ZenIsBestWolf** [comment]
update to beta 4, and toggle "Reinstall Cydia" in your settings before jailbreaking, and see if that helps.
