### ISSUE TITLE
I have 12.2 Beta, but the unc0ver not recognizing it and show "Unsupported" message!

### ISSUE THREAD

**Issue by Y0usefmahdi** [pwn20wndstuff/Undecimus#1129]
**Describe the bug**
I have 12.2 Beta, but the unc0ver not recognizing it and show "Unsupported" message!
The Beta build Number "16E5227a" - iOS 12.2 Beta - iPhone 9,4 - Model: D111AP

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by SoulSen** [comment]
Also can reproduce

**Comment by clarityzzz** [comment]
You'll have to wait for pwn, GitHub source isn't updated, so I can't submit a pull request to fix this :/
