### ISSUE TITLE
iOS Security Code Autofill

### ISSUE THREAD

**Issue by frognep** [pwn20wndstuff/Undecimus#1136]
**Describe the bug**
Not sure about other banking apps but this should be able to be reproduced on any app or service that requires a SMS code and utilizes iOS's code autofill feature.  Whenever I want to unlock a debit card to use, my bank app sends me a code via SMS. Usually in unjailbroken mode, the code is sent and the autofill feature in iOS displays the code from the text message (without having you leave the app)and you just click on the autofill section on top of the keyboard without having to go to the imessage app or type it in yourself.
In jailbroken mode it's somewhat broken, and for some reason, it appears separated into three columns as it would in regular word autofill suggestions on on the first column to the left when it is usually in the middle with no separators. The code shows up in keyboard suggestion, but when clicked it doesnt auto fill into the input box. 

**To Reproduce**
1. Go to 'Bank of America'
2. Click on 'Menu > Manage Debit Card'
3. Scroll down to 'Unlock debit card'

**Screenshots**
 
![DC688BE1-ECE7-4DE3-B942-7BE899EE2795](https://user-images.githubusercontent.com/40965142/61153157-082ee080-a4b0-11e9-8387-e5e01b308aa8.jpeg)

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 7 (9,3)
 - unc0ver Version: 3.3.0~b5

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by clarityzzz** [comment]
Can you jailbreak with tweaks off and share the result, please?

**Comment by dbdoan** [comment]
What exactly are you looking for? I was jailbroken and disabled all my tweaks via icleaner pro. still same result.

**Comment by clarityzzz** [comment]
Reboot and upon jailbreaking turn tweaks off from within the unc0ver app.

**Comment by dbdoan** [comment]
Strange.. i rejailbroke and it fixed itself. With tweaks off and on from the uncover app. I guess I can close this thread now. Thank you!
