### ISSUE TITLE
Unsupported bug Max with 12.2

### ISSUE THREAD

**Issue by ramyelgenany** [pwn20wndstuff/Undecimus#1139]
I'm having an issue with b3 also b5 getting msg " Unsupported " and i'm using iPhone xs Max with 12.2 (16E227) . 
![46C6CE05-9FDD-4805-A043-E886E40CBF40](https://user-images.githubusercontent.com/25175220/61161800-dd6f7700-a505-11e9-942c-9a4a42a84111.png)
![4C9D4D6D-5444-4295-9757-1F7695F52C9B](https://user-images.githubusercontent.com/25175220/61161801-dd6f7700-a505-11e9-95f7-bf414411db49.png)

**Comment by ZenIsBestWolf** [comment]
There's no bug, this is intentional. We need a PAC bypass to get A12 working.

**Comment by ramyelgenany** [comment]
but from the description i see that A12 is supported in last beta
