### ISSUE TITLE
Abnormal battery drain!

### ISSUE THREAD

**Issue by soum91** [pwn20wndstuff/Undecimus#114]
I opened an issue before regarding this. But it was closed by saying that it’s being caused by some tweak. But I have been testing with all tweaks turned off except mobilesubstrate and few dependencies. Still I’m having 145% battery drain! How is that possible? How can any tweak cause battery drain if all the dylib are disabled? Other than that I had all tweaks installed but battery was not this bad. And I’m the only one who is complaining. If you search in Reddit, you will see others are suffering from this too!

I think the issue is itself the tweakloader/substitute. Pwn20wnd should really properly switch back to mobilesubstrate or fix the problem with substitute.
I don’t know what does Ref of module in CocoaTop means but in all the system daemon, tweakloader has the highest Ref count. All random daemon acting crazy and hogging cpu usage randomly is the main reason.

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb

**Comment by soum91** [comment]
@Samisaninja Since when ‘jailbreak itself causing  battery drain’ became ‘eta/wen/halp/etc’?
Just because I’m pointing out that something wrong in jailbreak is spiking random system daemon’s cpu usage even when all the TWEAKS DISABLED, you will start trolling me?
You’re starting to behaving as arrogant as coolstar, @Samisninja!
Just because you can’t solve a problem with your jailbreak doesn’t mean you will start dissing someone with demeaning comment!
Such an asshole behavior!!

**Comment by soum91** [comment]
@Samgisaninja, and you’re talking about getting ‘halp’ on discord? I opened an issue on discord’s genius-bar and there you said me to disable all the tweaks. And now that I have followed your saying and confirming the issue, you’re trolling me?
Why would you get such butthurt if someone is pointing a legit problem??

**Comment by Samgisaninja** [comment]
My apologies for sounding “butthurt”, to be honest I only glanced over your initial issue and only really read cryptic’s response, and the close message is mostly tongue-in-cheek, although I suppose sarcasm doesn’t travel well over the internet...

Substrate support has been the goal all along and will be coming shortly, we’re working with saurik on that. 

Feel free to upload a battery usage settings screenshot though. I’d recommend detailedbatteryusage so that it enables Apple’s internal graph/etc.
