### ISSUE TITLE
Not Supported IPhone 6+ iOS 12.1.4

### ISSUE THREAD

**Issue by kieradev** [pwn20wndstuff/Undecimus#1150]
**No A8 Support On iOS 12.1.4 Even Though There Should Be.**

**Describe the bug**
With iOS 12.1.4 and iPhone 6+ (A8) Unc0ver says not supported even though a7-a8 is now meant to be supported in 12.1.3-12.2?

**To Reproduce**
1. iOS 12.1.4 iPhone 6+ Install Unc0ver
2. It will say “Not Supported”

**Screenshots**
Screenshot: 
![E1B8F3F6-8358-4705-8E92-BEFC64CC2FFE](https://user-images.githubusercontent.com/49366907/61180938-94f3ae80-a616-11e9-81d0-b6753ca26962.jpeg)

**Device (please complete the following information):**
 - iOS Version: iOS 12.1.4
 - iOS Device:  iPhone 6+
 - unc0ver Version: Beta 3.3.0 b7

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Log:
`[*] unc0ver Version: 3.3.0~b7
[*] Machine Name: iPhone7,1
[*] Model Name: N56AP
[*] Kernel Version: Darwin Kernel Version 18.2.0: Wed Dec 19 20:28:48 PST 2018; root:xnu-4903.242.2~1/RELEASE_ARM64_T7000
[*] Kernel Page Size: 0x1000
[*] System Version: iOS 12.1.4 (Stable) (Build: 16D57)
[*] Bundled Resources Version: 1.0~b23
[*] Status: Unsupported
[*] Progress: Unsupported`

**Comment by yt2639** [comment]
Yes, it shows unsupported on IPhone 6 as well. I am using 3.2.1 Release. Will this be addressed? Thanks!

**Comment by Devscribe** [comment]
Same problem on iphone 6 ios 12.2 (v3.3.0~b7)

**Comment by mrthickle** [comment]
Also on iPhone 6 iOS 12.1.4
![67196641_2164237467200613_174137443266592768_n](https://user-images.githubusercontent.com/52881899/61182590-f12ef080-a65f-11e9-8619-6fabf76dd19f.jpg)

**Comment by asdfugil** [comment]
4K devices are unsupported.

**Comment by willerhehehe** [comment]
same problem on iphone7
