### ISSUE TITLE
Unsupported iPhone6 on 12.1.3 with Unc0ver 3.3.0~b7

### ISSUE THREAD

**Issue by is171827** [pwn20wndstuff/Undecimus#1152]
Beta5 to Beta7 says unsupported on iPhone6 running ios 12.1.3

![Download](https://user-images.githubusercontent.com/52885141/61184138-6f809800-a64a-11e9-980d-e7aa91ebe1dc.png)

**Comment by CobreDev** [comment]
iOS 12.3 release isn't supported by unc0ver currently

**Comment by strejda603** [comment]
It's cause A7~A8 and A12X devices are not supported with Unc0ver yet... They are supported only till iOS 12.1.2..

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553

**Comment by is171827** [comment]
Works now with 3.3.8 release! Thank you!
