### ISSUE TITLE
Having to rejailbreak after installing tweaks

### ISSUE THREAD

**Issue by Zeridiant** [pwn20wndstuff/Undecimus#1154]
I am using iOS 12.2 on an iPhone 7. I encounter an issue with having to rejailbreak after installing a tweak.

All I did is click jailbreak, go into Cydia and install any tweak/app. I needed to reboot phone so I did and jailbreak was removed. I can easily jailbreak again by clicking jailbreak in unc0ver and it’ll work again. Why does it remove itself after installing a tweak?

 - iOS Version: 12.2
 - iOS Device: iPhone 7
 - unc0ver version: 3.3.0~b6

 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all  uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by qiwihui** [comment]
same issue also happens to beta 7
