### ISSUE TITLE
"Unsupported" with beta7 on my A8 device...

### ISSUE THREAD

**Issue by strejda603** [pwn20wndstuff/Undecimus#1156]
It sais that my A8 device (iPhone 6 12.1.4) is unsupported... Is it bug, or it supposed to be like that?

![109D32FA-F419-4C8E-B1F8-CD127932CB26](https://user-images.githubusercontent.com/32793325/61189264-403e4b00-a68b-11e9-88bb-71d394cfece5.png)

**Comment by Martin-SF** [comment]
this should be fixed by b7 hm. It shouldnt make a difference but try the newest build

**Comment by strejda603** [comment]
I've tried, but still have the same problem...

**Comment by Martin-SF** [comment]
That I guess pwn didn’t really fixed the issue with b7... seems like you can only wait for a quick fix or try to locate the error by your self an make a pull request... shouldn’t be that complicated

**Comment by MaltronCraft** [comment]
[https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553](https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553)

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553
