### ISSUE TITLE
Unable to jailbreak with reload system daemons on

### ISSUE THREAD

**Issue by rctfan929** [pwn20wndstuff/Undecimus#1161]
When I jailbreak with reload system daemons on I get put into a respring loop.

1. Jailbreak w/ reload system daemons on
2. Respring loop

 - iOS Version: 12.1.2
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.3.0

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by zpersondude9** [comment]
same issue 6s 11.3.1, latest unc0ver

**Comment by lilu0826** [comment]
You can off it.

**Comment by rctfan929** [comment]
Fixed since v 3.3.1
