### ISSUE TITLE
iPhone 5s Unsupported 12.2 (A7)

### ISSUE THREAD

**Issue by akashag** [pwn20wndstuff/Undecimus#1165]
It says that A7 chip devices are supported but i am unable to jailbreak my iPhone 5s. It shows that the device is unsupported even after following all the instructions.

 - iOS Version: 12.2
 - iOS Device: iPhone 5s
 - unc0ver Version: 3.3.0

![IMG_0001](https://user-images.githubusercontent.com/13604745/61240425-d1cabd00-a75e-11e9-9323-fe2011f8e479.jpg)

**Comment by a-essawy** [comment]
i have the same iphone running on the same OS and i tested the same version of unc0ver and i have the same bug

**Comment by CedricPriouret** [comment]
UP !!

**Comment by andychiakangwey** [comment]
I have an iPad Air 2 (A8) running on 12.2 is unsupported as well.. HELP!

**Comment by slvrndblck34** [comment]
Same here on iPad Air 2 also 😢

**Comment by jbpallingayan** [comment]
up reproduceable on new version 3.3.2

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553

**Comment by BilalAhmedKhan-IosDeveloper** [comment]
they have said currently its unsupported on iphone 5s,6,6plus...!
lets c when they release JB for these devices.

**Comment by The-SamminAter** [comment]
Same here on iPhone 5s, iOS 12.1.4

> they have said currently its unsupported on iphone 5s,6,6plus...!
> lets c when they release JB for these devices.
I believe that Chimera supports those devices, if you don't mind using something other than Cydia Substrate.

**Comment by BilalAhmedKhan-IosDeveloper** [comment]
> Same here on iPhone 5s, iOS 12.1.4
> 
> > they have said currently its unsupported on iphone 5s,6,6plus...!
> > lets c when they release JB for these devices.
> > I believe that Chimera supports those devices, if you don't mind using something other than Cydia Substrate.

Chimera also have same issue.4k devices with ios 12.2 are unsupported.Stl there is one news beta are made working on 4k but its unreliable...so they are delaying

**Comment by kysokzla** [comment]
I have the same issue, i have 5s device, what could be done to make unc0ver work on 5s device? Anyone have an idea? Could we commit to make it work on 5s?
