### ISSUE TITLE
iPad 4 mini not supported

### ISSUE THREAD

**Issue by guteSeite** [pwn20wndstuff/Undecimus#1168]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.4
 - iOS Device: iPad 5,1 J96AP
 - unc0ver Version: 3.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by guteSeite** [comment]
![3067477D-F48D-41A0-9833-BBC37AF34CC7](https://user-images.githubusercontent.com/34644251/61314450-e8275600-a7fc-11e9-9dc3-61f2220397bd.png)
where can I download the experimental build?

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553
