### ISSUE TITLE
iPhone 6 on iOS 11: can't jailbreak since v3.3.0

### ISSUE THREAD

**Issue by a1ex4** [pwn20wndstuff/Undecimus#1175]
**Describe the bug**
Can't believe there's no one else with my problem, I triple checked everything but u0 either crashes or restart the device at 'Process initialazing jailbreak', using AS, M1 and M2.

Also "Share diagnostic data" instantly crashes the app, and I don't know how can I retrieve the log of a previous jailbreak attempt after a restart (I mean unc0ver's log).

Went back to v3.2.1, can jailbreak just fine using M1, although 'Share diagnostic data' crashes the app too. I grabbed the logs with CrashReporter from the previous attempts:

* [v3.3.2](https://pastebin.com/uhpzvpt3)
* [v3.3.0](https://pastebin.com/BVKXuB1S)

I hope this will help you, thank you for being an amazing dev and making the best jailbreak tools !
**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 11.1.2
 - iOS Device: iPhone 6
 - unc0ver Version: happening in v3.3.0 through v3.3.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by RobinHood1975** [comment]
My 3.2.1 wouldn't work anymore after losing jb on a restart. Tried 14 times to get it to work, starts jailbreak crashes and restarts. ios 11.0 iphone 6s 32gig. New one isn't working either.

**Comment by coenkcore** [comment]
Just use v3.2.1 on ios 11
