### ISSUE TITLE
3.3.2 iPad Air 12.1.4 (A7) - unsupported

### ISSUE THREAD

**Issue by oakid** [pwn20wndstuff/Undecimus#1177]
3.3.2 iPad Air 12.1.4 (A7) - unsupported

- iOS Version: 12.1.4
- iOS Device: iPad Air (cellular)
- unc0ver Version: 3.3.2

**Comment by Capts** [comment]
Iphone 6+ A8 - unsupported

iOS Version: 12.2
iOS Device: iphone (cellular)
unc0ver Version: 3.3.2

**Comment by chaiguolong** [comment]
3.3.3 iPad Air 12.1.4 (A7) - unsupported

iOS Version: 12.2
iOS Device: iPad Air (cellular)
unc0ver Version: 3.3.3

**Comment by willt80** [comment]
3.3.2 iPad Air 2 12.2 (A8X) - unsupported

iOS Version: 12.2
iOS Device: iPad Air 2 (wifi)
unc0ver Version: 3.3.2

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553

**Comment by mmmsq-shiq** [comment]
3.3.3 iPad Air 2 12.1.3 (A8X) - unsupported

iOS Version: 12.1.3
iOS Device: iPad Air 2 (wifi)
unc0ver Version: 3.3.3
