### ISSUE TITLE
Unsupported Jailbreak on iPhone 5S 12.1.4

### ISSUE THREAD

**Issue by CedricPriouret** [pwn20wndstuff/Undecimus#1179]
**Describe the bug**
Unsupported Jailbreak

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.4 (16D57)
 - iOS Device: iPhone 5S Model A1457
 - unc0ver Version: Undecimus-v3.3.0.ipa

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Thoshuno** [comment]
Para el iPhone 5s aún no está disponible o para ser más específicos los 4K, estamos en la espera de pwn20wnd

**Comment by Franaa** [comment]
Why is not available ?

**Comment by CedricPriouret** [comment]
> Para el iPhone 5s aún no está disponible o para ser más específicos los 4K, estamos en la espera de pwn20wnd

Why is not available ?

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553

**Comment by CedricPriouret** [comment]
> [#1180 (comment)](https://github.com/pwn20wndstuff/Undecimus/issues/1180#issuecomment-512263553)

Thanks :)
