### ISSUE TITLE
Cydia showing connection appears to be offline after jailbereak

### ISSUE THREAD

**Issue by iamibson** [pwn20wndstuff/Undecimus#1181]
Hello, i managed to jailbreak my iphone 7+ running ios 12.1.4 with the new unc0ver jailbreak that was released to support ios 12.1.3-12.2 Anytime i opened cydia i get the prompt that "unable to load (the internet connection appears to be offline)" and after much research, i found out my device is one of the chinese supported device that ask for way of connection in all application. Please i need a help

**Comment by Officeyutong** [comment]
I got the same problem like yours.

**Comment by iamibson** [comment]
Please can someone help us out on this issue 🙏

**Comment by iamibson** [comment]
Please someone should help out

**Comment by lilu0826** [comment]
Use VPN can fix this bug. and then setup the tweak name of 'ConditionalWifi', after that you can connect this network normally whitout VPN.

**Comment by qiwihui** [comment]
@iamibson Maybe you can refer to this issue commnet:

https://github.com/pwn20wndstuff/Undecimus/issues/499#issuecomment-478285158

As described:

1. Toggle (Re)Install OpenSSH in unc0ver and re-jailbreak.
2. Find your local ip, use a computer and type in the command "ssh root@[ip]". It will ask to confirm the RSA fingerprint, type yes and continue. Password is "alpine"
3. `rm -rf /var/preferences/com.apple.networkextension*`
4. Respring/jailbreak your phone and it should be fixed.

**Comment by iamibson** [comment]
I powered my VPN and opened cydia but still there’s no internet connection

**Comment by iamibson** [comment]
I also run the above on Openssh but still even after deleting the files, they still reappear again

**Comment by iamibson** [comment]
Please i need help

**Comment by qiwihui** [comment]
Maybe you can retry with the newest unc0ver and the process above. Is there any log you can find about this issue?

**Comment by iamibson** [comment]
The issue is that I kept trying all what i see from the internet especially the procedure above. I’ll run successfully and delete the files but from no where if i check again, they reappear. For more than 10 times i did it but still

**Comment by iamibson** [comment]
I figured out a way to solve this actually. Tested on 7 plus running iOS 12.1.4  unc0ver3.3.8

​

So starting from fresh (like unjailbroken state)

1: Open unc0ver and select install openSSH upon jailbreaking.
2: Wait until it is finished
3: On iPhone, go to Settings > Wifi, type on the i to find out the IP address of the iPhone.
4: On you laptop, (I am on Mac but use Powershell if on Windows), open Terminal
5: In Terminal, type the following: ssh root@"REPLACE_WITH_IP_ADDRESS_OF_IPHONE", press enter
6: Type in the following: alpine. <- This is the default password of SSH on iPhone, change it once you get a chance.
7: Type in cd /var/preferences && ls | grep networkex
8: Now in terminal you should see some files with .plist at the end
9: Type in mv com.apple.networkextension.necp.plist com.apple.networkextension.necp.plist.bak
10: Type in mv com.apple.networkextension.plist com.apple.networkextension.plist.bak
11: Type in mv com.apple.networkextension.uuidcache.plist com.apple.networkextension.uuidcache.plist.bak
12: Type in ls | grep networkex to verify if all .plist are now in .bak
13: IF you still have some with .plist ending, Type rm "FILE_NAME.plist" to remove them.
14: Type in reboot to reboot the device.
15: Rejailbreak
16: Profit

Now Cydia should be able to connect to the internet.

Reference: https://www.reddit.com/r/jailbreak/comments/7mhwa3/question_ios_1033_cydia_wont_connect/dv1c38p

​

**Comment by iamibson** [comment]
> I got the same problem like yours.

check out the fix i just updated
