### ISSUE TITLE
no permission  /var/mobile/Library/WebClips

### ISSUE THREAD

**Issue by guteSeite** [pwn20wndstuff/Undecimus#1188]
Jailbreak on iPhone SE fine - great !!!!!
but I can't change my icons on  /var/mobile/Library/WebClips
readonly by filza, terminal....
any idea?

**Comment by guteSeite** [comment]
...same on iPad mini 4 - but jabreak is great - big thanx !!!

**Comment by Cregin** [comment]
how to fix? @guteSeite
