### ISSUE TITLE
Unc0ver doesn't respring after jailbreaking

### ISSUE THREAD

**Issue by dhellwich** [pwn20wndstuff/Undecimus#1189]
**Describe the bug**
The problem exists in Unc0ver v3.3.1 and higher. 
After successfully jailbreaking the iPhone, it doesn't respring / reload springboard

**To Reproduce**
1. Go to UncOver
2. Click on 'Jailbreak'
3. Click on "OK" when the notice appears that the iPhone was succesfully jailbroken
4. Unc0ver app crashes to springboard. Springboard does not respring / reload

**Device (please complete the following information):**
 - iOS Version: 11.3.1
 - iOS Device: iPhone 6S
 - unc0ver Version: 3.3.1 and higher

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Unc0ver doesn't open anymore after it has (supposedly) succesfully jailbroken the iPhone (can't access logs)

**Comment by asdfugil** [comment]
Have you turn on `Load Tweaks`?

**Comment by dhellwich** [comment]
Yes, I have `Load Tweaks` turned on

**Comment by dhellwich** [comment]
Strange. All of a sudden it started working. I think disabling and enabling `Load Tweaks` fixed the issue...

**Comment by PeterTheDeveloper** [comment]
Since no one has commented. I solved the issue by putting my phone in the freezer. After I turn my phone off, and let my phone cool down for about 5 minutes I was able to respring into a jailbroken state.
