### ISSUE TITLE
Uncover shows wrong device

### ISSUE THREAD

**Issue by DNHarpal** [pwn20wndstuff/Undecimus#1191]
**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device:  iPhone 8
 - unc0ver Version: 3.3.3 and all previous too

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Uncover and Cydia both shows wrong ios version on my device
I have iphone8 but it shows iPhone 10.
First section (page) is not working where ever I touch it stays as a green and nothing more.
![IMG_0001 1](https://user-images.githubusercontent.com/53062738/61496026-f0140100-a988-11e9-91ba-7e3d189466fc.PNG)

![IMG_0002 1](https://user-images.githubusercontent.com/53062738/61496084-1a65be80-a989-11e9-9450-dd7e5cb03b33.PNG)

**Comment by LoganMD** [comment]
iPhones are identified differently in code than IRL, this is not a bug

**Comment by DNHarpal** [comment]
Classification of the error might be wrong but there is an error that keeps me annoying.

**Comment by anazhd** [comment]
> Classification of the error might be wrong but there is an error that keeps me annoying.

What do you mean? iPhone10,4 is iPhone 8. It's just how the real model number is. refer here https://everymac.com/ultimate-mac-lookup/?search_keywords=iPhone10,4
