### ISSUE TITLE
unsupported but should work

### ISSUE THREAD

**Issue by Spooney926** [pwn20wndstuff/Undecimus#1195]
Im using an iphone 6 that is still on ios 12.2 and i can not jailbreak as it says my phone is unsupported

**Comment by AnanasHaus** [comment]
Yeah, the same for me with Unc0ver 3.3.3. Seems like we're stuck for now :(

![Foto 19 07 19, 14 26 38](https://user-images.githubusercontent.com/8365725/61535006-666c3e00-aa31-11e9-8fe0-2340a551776d.png)
