### ISSUE TITLE
Unc0ver isnt supporting my device.

### ISSUE THREAD

**Issue by mmmsq-shiq** [pwn20wndstuff/Undecimus#1196]
Describe the bug
Opening the app displays an unsupported screen yet I was told my device type and version was supported. 

I have an A8X Core, Im on 12.1.3, im on a relatively new ipad, so why isnt it supported??

To Reproduce
   1.Open Uncover on my device type and version
 Error message
     
![image](https://user-images.githubusercontent.com/38556399/61534203-83b90080-aa61-11e9-84b6-2e79ecc5bb93.png)

Device (please complete the following information):

iOS Version: 12.1.3
iOS Device: iPad Air2/IPAD5,3
unc0ver Version: 3.3.3

**Comment by slvrndblck34** [comment]
Same here iPad Air 2 on 12.2 :(
