### ISSUE TITLE
No more + sources option?

### ISSUE THREAD

**Issue by ic3cr34m** [pwn20wndstuff/Undecimus#120]
I could have sworn earlier there was an option for a list of sources in cydia to add them from there. What happened to it?

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb

**Comment by me246813579** [comment]
That was CyDown, nothing to do with unc0ver
