### ISSUE TITLE
ipad air2 12.2 "Unable to repair system" unc0ver 3.3.6-3.3.7

### ISSUE THREAD

**Issue by condonsky** [pwn20wndstuff/Undecimus#1206]
**Describe the bug**
When 22/31 ,   it is happen.

**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'Jailbreak'
3. See error at 22/31

**Screenshots**
<a href="https://imgchr.com/i/eS4LJ1"><img src="https://s2.ax1x.com/2019/07/21/eS4LJ1.png" alt="eS4LJ1.png" border="0" /></a>
 - iOS Version: 12.2 (16E227)
 - CPU:A8X
 - Machine: iPad5,3 (A1566) 
 - unc0ver Version: 3.3.7    also   3.3.6

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
[*] runCommandv(500): WARNING: The following packages cannot be authenticated!
[*] runCommandv(500):   shell-cmds org.thebigboss.repo.icons
[*] runCommandv(500): Authentication warning overridden.
[*] runCommandv(500): Get:1 file:/var/lib/undecimus/apt ./ shell-cmds 118-8 [12.7 kB]
[*] runCommandv(500): Get:2 file:/var/lib/undecimus/apt ./ org.thebigboss.repo.icons 1.0 [11.5 kB]
[*] runCommandv(500): (Reading database ... 3829 files and directories currently installed.)
[*] runCommandv(500): Removing app.weiphone.net.angelxwind.appsyncunified (6.0-b1) ...
[*] runCommandv(500): dpkg: error processing package app.weiphone.net.angelxwind.appsyncunified (--remove):
[*] runCommandv(500):  subprocess installed pre-removal script was killed by signal (Killed: 9)
[*] runCommandv(500): dpkg: error while cleaning up:
[*] runCommandv(500):  subprocess installed post-installation script was killed by signal (Killed: 9)
[*] runCommandv(500): Errors were encountered while processing:
[*] runCommandv(500):  app.weiphone.net.angelxwind.appsyncunified
[*] runCommandv(500): W: Unable to read /etc/apt/''/ - DirectoryExists (2: No such file or directory)
[*] runCommandv(500): E: Sub-process /usr/bin/dpkg returned an error code (1)
[*] runCommandv(500) completed with exit status 100
[*] Unable to repair system.

**Comment by condonsky** [comment]
I  have  complete!   yeah!

**Comment by LoveOFF** [comment]
> I have complete! yeah!

I have the same problem. Can you help me? Pleasee

**Comment by compucat** [comment]
Reproduced on iPhone SE with iOS 12.4 and iPhone 5S with some earlier version of iOS (12.2? I forget, it's been a while). Seems to be related to dpkg packages from earlier jailbreaks; if we could access dpkg over SSH, this could be fixed manually. Unfortunately, while I can get unc0ver to give me SSH, iOS returns `Killed: 9` for any process I try to run (even something like `ls`!)

**Comment by compucat** [comment]
Seems to be sheer luck, but I got around this issue. We should work to figure out a better solution.
My sequence of steps:
- Backup to iTunes
- Erase All Content/Settings
- Restore backup
- Restore RootFS
- Jailbreak

**Comment by akukatala** [comment]
HELP!! I have JB in iOS 12.1.1 but I don't have a PC and when I give the option of unc0ver to remove the JB the option to update software in the iPhone options does not open and if I give it to reset the cell phone it gives me a respring and does not erase anything  

iPhone 6S Plus

**Comment by alboltdrogo** [comment]
I had the same error and used the following steps to fix it:
- Run unc0ver in SSH only mode
- Open an SSH session with your iOS device
- Re-jailbreak with SSH only mode off (otherwise you won't have commands like apt, ls, etc)
- Add https://cydia.akemi.ai/ to cydia sources (/etc/apt/sources.list.d/cydia.list)
- Run apt-get update & apt-get upgrade
- Restart your device & jailbreak again

I think the cause of this error is having some older sources / tweaks still installed on your device from a previous jailbreak.
Running a full restore like @compucat suggested would solve that of course, but seemed like a bit too much hassle for me ;)

**Comment by dpmaycry** [comment]
> I had the same error and used the following steps to fix it:
> 
> * Run unc0ver in SSH only mode
> * Open an SSH session with your iOS device
> * Re-jailbreak with SSH only mode off (otherwise you won't have commands like apt, ls, etc)
> * Add https://cydia.akemi.ai/ to cydia sources (/etc/apt/sources.list.d/cydia.list)
> * Run apt-get update & apt-get upgrade
> * Restart your device & jailbreak again
> 
> I think the cause of this error is having some older sources / tweaks still installed on your device from a previous jailbreak.
> Running a full restore like @compucat suggested would solve that of course, but seemed like a bit too much hassle for me ;)

seems to be helpful, I will try this one.

It worked~~~!!! thanks
