### ISSUE TITLE
bootloop

### ISSUE THREAD

**Issue by InesID** [pwn20wndstuff/Undecimus#1211]
**Describe the bug**
After a force restart of the phone (power+volume down buttoms), my iPhone is in a bootloop. When I turn on the phone, it does show the apple logo for less than 10 seconds, then crashed an restart et so on. I tried to update it using iTunes and 3uTools, but it doesn't work, and I don't want to restore it because it's my main device

**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'Jailbreak'
3. Hard reset de device

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 7 plus (iPhone 9,4)
 - unc0ver Version: 3.3.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by zpersondude9** [comment]
have you tried Reiboot?

**Comment by InesID** [comment]
> have you tried Reiboot?

I won't throw 30€+ just for updating my device, I'll try something with 3utools

**Comment by JesseLT** [comment]
open Safari then go to unc0ver and jailbreak. Good luck!

**Comment by InesID** [comment]
> open Safari then go to unc0ver and jailbreak. Good luck!

My iDevice won't turn on

**Comment by zpersondude9** [comment]
> I won't throw 30€+ just for updating my device, I'll try something with 3utools  

I'm almost certain there is a free version of Reiboot that I've used before to get out of a bootloop.
