### ISSUE TITLE
0x1111 doesn't generate The specific APnonce on A8X. iOS12.2 u0 3.3.7 [Emergency!]

### ISSUE THREAD

**Issue by hamid0015** [pwn20wndstuff/Undecimus#1212]
**Describe the bug**
.
Title is clear and says everything you need to know.
I have this issue with other generators tho.

**To Reproduce**

Set generator 0x1^16 then Jailbroke my idvece  w/o getting error;
Then, Checked the apnonce with igetnonce;
I expected that appnoce will be 3a88b7c3802f2f0510abc432104a15ebd8bd7154 but it wasn’t. 
I checked this in Recovery mode too and it wasn’t either!
Aftar that;
I changed the nvram, but nope! this didn’t help either

**Screenshots**
http://imgur.com/a/zK4S5Ju

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: Air 2
 - unc0ver Version: 3.3.7

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

[log_file.txt](https://github.com/pwn20wndstuff/Undecimus/files/3414643/log_file.txt)

**Comment by hamid0015** [comment]
One thing more, 
When u0 3.3.0 was released somebody messed up his iPhone 7 (A10) and I helped him to FTR on 12.2 by his shsh2 0x1111 
The point is the nonce was correct for his device. I mean 0x1111 generate 27325c(...) apnonce
So i think this problem should be on A8x, no other devices(maybe on 4k too. idk!)

For ppl that interested to know what’s going on:
Apnonce of 0x1111111111111111 

Old devices =<A9 
3a88b7c3802f2f0510abc432104a15ebd8bd7154

New devices A9X-A11
27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae

**Comment by arx8x** [comment]
The problem is that when you use igetnonce once in normal mode, the kext ignores whatever you have set in nvram and overwrites it with a random generator. This is then used to generate an apnonce. This apnonce is cached for that boot session but the generator the kernel wrote is kept until it's consumed. So, when you ran igetnonce in normal mode, the kernel wrote its own generator. The apnonce igetnonce read corresponds to this generator. The generator exists in nvram and will be read in recovery mode to generate the apnonce. 
So you'll need to set the generator, boot into recovery and then use irecovery or igetnonce.

**Comment by hamid0015** [comment]
> The problem is that when you use igetnonce once in normal mode, the kext ignores whatever you have set in nvram and overwrites it with a random generator. This is then used to generate an apnonce. This apnonce is cached for that boot session but the generator the kernel wrote is kept until it's consumed. So, when you ran igetnonce in normal mode, the kernel wrote its own generator. The apnonce igetnonce read corresponds to this generator. The generator exists in nvram and will be read in recovery mode to generate the apnonce.
> So you'll need to set the generator, boot into recovery and then use irecovery or igetnonce.

absolutely!
![rec ok](https://user-images.githubusercontent.com/53143890/61638118-fcac9800-acad-11e9-96e2-96ae1db5c491.PNG)
