### ISSUE TITLE
panic-full 12.2 A9 3.3.2

### ISSUE THREAD

**Issue by Martin-SF** [pwn20wndstuff/Undecimus#1213]
**Describe the bug**
I was jailbroken and killed the last tab in safari, then the panic-full happened. Happend like maybe the second time since I jailbroke 1 week ago.

more infos:
- When trying to jailbreak after crash, the explotiting kernel (1/31) took like 20 seconds instead of like 0.5s.
- I restarted my device like an half our before the panic-full.
- I always "overwrite" unc0ver with Impactor, no delete beforehand.

**Tweaks installed**
(all marked as compatible with 12.2)
- tweakCompatible
- TapVideoConfig
- System Info
- BrickFix
- PullToRespring
- WeatherVane

- Reprovision
- Homegestures
- iCleaner Pro (diabled deamons:
                      airprint,
                      assistiveTouch,
                      chinese wifi,
                      game center,
                      HelathKit,
                      HomeKit,
                      OTA update)

**To Reproduce**
- (to few times happened, no pattern recognized)

**Device:**
 - iOS Version: 12.2
 - iOS Device: iPhone 6s A9
 - unc0ver Version: 3.3.2

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [?] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [?] this issue is present after a rootfs restore
 - [?] this issue is present on the latest version of unc0ver

**Logs**
[panic-full-2019-07-21-155031.833.ips.log](https://github.com/pwn20wndstuff/Undecimus/files/3414669/panic-full-2019-07-21-155031.833.ips.log)

**Comment by Martin-SF** [comment]
(since the versions >3.3.2 look like to fix nothing for my device/iOS I guess it will happend even with newest, but I updated now, just in case)

**Comment by Pythonic-Rainbow** [comment]
Same on 3.3.7 iOS12.2 A9, but it wasn’t caused by Safari kill and it doesn’t take 20s on first step, I’ll paste log later

**Comment by Martin-SF** [comment]
Yeah was very expecting to not be a specific issue with safari

**Comment by thekio1984** [comment]
I think these issues are in all versions of uncover..i think its more substrate than the jailbreak..& only saurik can fix it & the freezes are random af, trust me lol
