### ISSUE TITLE
Failed with error: Unable to install manually extracted debs.

### ISSUE THREAD

**Issue by kid1carus** [pwn20wndstuff/Undecimus#1214]
Jailbreak fails at stage 22 repeatedly.  Error code is as stated above:  "Cant install manually extracted debs"

![IMG_5657](https://user-images.githubusercontent.com/45052773/61624299-58433b00-ac46-11e9-999b-b4859c121be6.PNG)
![IMG_5379](https://user-images.githubusercontent.com/45052773/61624304-5a0cfe80-ac46-11e9-84e4-a10f0bb02a49.PNG)
![IMG_5378](https://user-images.githubusercontent.com/45052773/61624310-5c6f5880-ac46-11e9-9ce5-aa506f278769.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.3.7

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/CJyFsheu

**Comment by Martin-SF** [comment]
your pastebin is private.
Have you tried restore rootFS?

**Comment by PChemProf** [comment]
I had the exact same error at the exact same stage.  iPad Air 2 (A8 device) running iOS 12.1.4 trying to use unc0ver v. 3.3.8.  Not sure what restore rootFS is, so some advice would be greatly appreciated; thanks!

**Comment by Martin-SF** [comment]
you can enable it in unc0ver settings. then press jailbreak like 2-3 time until youre jailbroken.
It wipes everything jailbreak related exept the user data (settings for tweaks, repos).
If the error persists after it, it likely to be fixed with unc0ver.

**Comment by lol7344** [comment]
if the error persists after a rootfs restore you most likely used chimera in the past and it messed up your filesystem. read this reddit guide and report if you can fix your problem: https://www.reddit.com/r/jailbreak/comments/cgjv1b/tutorial_how_to_fix_unable_to_install_firmware/?utm_source=share&utm_medium=ios_app

**Comment by kid1carus** [comment]
**[sorry...Logs are now viewable!](https://pastebin.com/CJyFsheu)**
