### ISSUE TITLE
Sileo or Cydia 

### ISSUE THREAD

**Issue by Arthur2709o** [pwn20wndstuff/Undecimus#1215]
Hi everyone ! I’ve a question, is it possible to get sileo after a jailbreak with Unc0ver and Conversely ? I'm afraid that cydia disappears slowly and that sileo controls the "market"? I don’t know... Sileo of cydia ( Uncover or chimera ) ?

**Comment by Martin-SF** [comment]
iam not sure if this discussion should take place on the issues page of unc0ver. 
One problem is, that sileo was made with anti-unc0ver features by the dev team, so in the first place, its not so easy to integrate it in unc0ver.

**Comment by zpersondude9** [comment]
> iam not sure if this discussion should take place on the issues page of unc0ver.  

Agreed. This can be closed.
Sileo can't be installed on unc0ver because they put code in place that prevents it from running properly on non-substitute platforms. You can install any of Cydia, Installer5, Zebra, etc. on unc0ver and use those. So you do have choice in the matter.

**Comment by lol7344** [comment]
what were you thinking when you tagged this as a bug. this is just a simple question (with many answers already present on the web)

**Comment by Connor0p76** [comment]
You can try unc0ver dark
