### ISSUE TITLE
Cydia's homepage buttons do not work

### ISSUE THREAD

**Issue by lol7344** [pwn20wndstuff/Undecimus#1218]
**Describe the bug**
Cydia's homepage buttons become grey when tapped and nothing else happens.

**To Reproduce**
1. Open Cydia
2. Tap a button (bottom ones not included)

**Screenshots**
Video showing the problem: https://youtu.be/Iuuu8a2m9MM

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 6 (7,2)
 - unc0ver Version: 3.3.8 with sock_port

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver.

**Comment by tam3m** [comment]
I have this problem too 🖐

**Comment by pez307** [comment]
Same

**Comment by jokeman33** [comment]
same iphone 5s on 12.2

**Comment by lol7344** [comment]
tested on an iPhone 7 @ 12.1.2 and an iPhone 5s @ 11.4.1. seems to only happen in new iOS versions.
I think the issue could be restricted to 12.1.3-12.2 range as it works good on lower versions, but I'm unable to test and verify if it's a 12.2 only issue or if it also happens on 12.1.3 and 12.1.4.

**Comment by Vastomo** [comment]
Same, iPhone 7+ 12.2

**Comment by teefixx** [comment]
Same here, iPhone 7, iOS 12.2

**Comment by tam3m** [comment]
I have a solution i think.
Just press and hold those links for a little bit and it will open.
Works for me....
https://youtu.be/4VST5UQMjyA

**Comment by teefixx** [comment]
Thanx
Unfortunately it doesm‘t work for me...

**Comment by lol7344** [comment]
> 
> 
> I have a solution i think.
> Just press and hold those links for a little bit and it will open.
> Works for me....
> https://youtu.be/4VST5UQMjyA

@tam3m Did you really have to press a button for 10 whole seconds for it to simply open a page? Wow.
