### ISSUE TITLE
[HELP] Unable to create virtual dependencies

### ISSUE THREAD

**Issue by bxbx69** [pwn20wndstuff/Undecimus#1219]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

Screenshot: https://gyazo.com/e5b6a82d6a1d5d3dae00da46b84529cf

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 6
 - unc0ver Version: 3.3.8

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Reflexions4444** [comment]
IOS Version:12.2
IOS Device: Ipad Air 1
unc0ver version 3.3.8
Did a full reset and tried to jailbreak.
Tried without Cydia and with re-install Cydia settings.
Line 153: /usr/libexec/cydia/firmware.ver: No such file or directory
[log_file.txt](https://github.com/pwn20wndstuff/Undecimus/files/3421290/log_file.txt)

**Comment by bxbx69** [comment]
what can i start with that dude
