### ISSUE TITLE
Bug Cydia 

### ISSUE THREAD

**Issue by Arthur2709o** [pwn20wndstuff/Undecimus#1227]
After my jailbreak, I have install some tweaks very famous and I have turn off my iPhone and when I decide to turn on, there was impossible to open Cydia and my tweaks was faded away... I don’t understand ! I had to re-jailbreak my iPhone but same problem right now ? I use an iPhone 6 on IOS 12.1.3 and uncover 3.3.8

**Comment by Kai0KenX20** [comment]
unc0ver is not an "untethered jailbreak" eveytime you restart your phone (REBOOT/HARDRESET not RESPRING) you have to rejailbreak to escape sandbox and gain Privileges required for all tweaks...... without rejailbreaking when you try to open Cydia or something similar it appears to open and closes immediately this is normal behavior and not an issue if this is the case

**Comment by BilalAhmedKhan-IosDeveloper** [comment]
its not untethered jailbreak so dont expect that.if u power off and power on.jst click on unc0ver again and jailbreak.

**Comment by Martin-SF** [comment]
If this fixed your problem please „close“ this issue 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
