### ISSUE TITLE
Jailbreak done, but apps from cydia not working

### ISSUE THREAD

**Issue by bxbx69** [pwn20wndstuff/Undecimus#1229]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 6
 - unc0ver Version: 3.3.8

Jailbreak Succesfully, but when i download something from Cydia its not showing on iPhone settings

Screenshot of my unCover Settings :

https://gyazo.com/74492eafd5a988f27bce1b3d7beb2dd5

https://gyazo.com/fbd87bcc298f72f3d0fa7ff90ea7a376

**Comment by BilalAhmedKhan-IosDeveloper** [comment]
Umm check this out i think u missed these.try with new 3.4 udecimus.
https://imgur.com/1FGCqZh
https://imgur.com/KhyTNQv
