### ISSUE TITLE
  v. 3.4.0 Jailbreak Fails at 22/31:  Unable to install firmware debs

### ISSUE THREAD

**Issue by kid1carus** [pwn20wndstuff/Undecimus#1230]
**Describe the bug**
the jailbreak fails to complete at process 22/31 with the error message "unable to install firmware debs."

**To Reproduce**
re-run the jailbreak.  the issue is repeatable and happens every time.

**Screenshots**
![IMG_5717](https://user-images.githubusercontent.com/45052773/61749612-22e73c00-ad71-11e9-82e8-a5565587b5f3.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.4.0

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/sW3v5Jx5

**Comment by DanKoder0801** [comment]
Did you try and jailbreak with chimera ??

**Comment by BilalAhmedKhan-IosDeveloper** [comment]
remove the profile from general management.resintall 3.4.0 udecimus.
Main Thing put ur device in airplane mode.I saw in pic its not in airplane mode.

**Comment by conthom** [comment]
I also have the same issue and it still happens on airplane mode and I have reinstalled it many tines. Im using tweakbox because appvalley download never seems to work for me. Also Im using uncover after already installing chimera but removing it. Idk what to do maybe ill get lucky and it will work..

**Comment by Zvelteufs** [comment]
i have the same problem, i'm on iOS 12.0.1 on my iPhone SE.
I tried on airplane mode, also with location off..

**Comment by BilalAhmedKhan-IosDeveloper** [comment]
sometimes in airplane wifi doesnt gets off.so trying ur luck with this.and if u get error in recent versions then try with the old compatible version as the new version bug gets fixed.

**Comment by klubber** [comment]
I also have the same problem.
How to solve?
Anyone got it?
After installing IOS 12.4 JB worked but then started giving this error and I can't complete the installation anymore.

IPHONE SE - IOS 12.4 Unc0ver 3.6.3 
![WhatsApp Image 2019-09-13 at 16 13 25](https://user-images.githubusercontent.com/55297688/64891629-d9b4b980-d648-11e9-8ab9-7a8b3616496e.jpeg)

**Comment by drewsha82** [comment]
the same problem with SE
