### ISSUE TITLE
Cydia bug

### ISSUE THREAD

**Issue by Arthur2709o** [pwn20wndstuff/Undecimus#1233]
I have a little problem! when I launch Cydia, there is a little time to zoom out before it starts? it's really disturbing

![DBEA185B-F2E7-407B-BC30-2845B96700D6](https://user-images.githubusercontent.com/52976602/61809022-cc473400-ae3c-11e9-9518-f2e11db14793.png)
![Uploading 759D7873-2680-41C0-8A4D-95FBF54C72F5.png…]()
![Uploading EFF16576-DBC0-49E9-97B5-9F54E865FCE2.png…]()

**Comment by Renwar111** [comment]
Me 2
