### ISSUE TITLE
Restore RootFs

### ISSUE THREAD

**Issue by shivasharma63420** [pwn20wndstuff/Undecimus#1236]
I have iphone 6 ios12.2 m not restore my iphone

**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by shivasharma63420** [comment]
m restore my rootfs after my all tweaks working and i cant found my cydia app plz help me

**Comment by Martin-SF** [comment]
You solved your problem? Than please close this thread. Otherwise try to tick „reinstall Cydia“, „reload cache“ and „refresh icon cache“ for jailbreaking

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akukatala** [comment]
HELP!! I have JB in iOS 12.1.1 but I don't have a PC and when I give the option of unc0ver to remove the JB the option to update software in the iPhone options does not open and if I give it to reset the cell phone it gives me a respring and does not erase anything  

iPhone 6S Plus
