### ISSUE TITLE
Provided IPA doesn't work with Impactor

### ISSUE THREAD

**Issue by FivePixels** [pwn20wndstuff/Undecimus#124]
The (c7f49ca) provided IPA throws the following error when signing with Impactor:

![halp png](https://user-images.githubusercontent.com/37427166/49025646-bbd1a300-f161-11e8-83a5-160b9b161c34.jpeg)

- If you're building on Xcode 10, you can go to Product > Archive and archive the project successfully.  - After this, right click the archive and Show in Finder. 
 - Next, Show the Package Contents of the File and navigate to the Products/Applications directory where you can find Undecimus.app. 
 - Create a folder named Payload and copy Undecimus.app into the Payload folder. 
 - Next, compress the file and rename the compressed file to Undecimus.ipa.

**Comment by Samgisaninja** [comment]
If you look at the actual "ipa file" I think you'll see why: it's not an ipa. We had previously hosted the latest unc0ver release at https://github.com/pwn20wndstuff/Undecimus/blob/master/Resources/Undecimus.ipa but we've started using GitHub releases now, and so we replaced the old IPA with a text file that we have set up to redirect any lost puppies who happen to find the old link online somewhere to what they're looking for.

Unfortunately, we can't change the name or extension of Undecimus.ipa, or else the link will also change.
