### ISSUE TITLE
Cydia question bug 

### ISSUE THREAD

**Issue by Arthur2709o** [pwn20wndstuff/Undecimus#1240]
little question, it may be stupid but why are there tweaks in this list that I did not even want to download? on cydia
![CEE31769-1C83-4E33-8B1E-B598D916D85B](https://user-images.githubusercontent.com/52976602/61939466-a08a9200-af93-11e9-8d9c-f09d6f68e301.png)

**Comment by yousef157** [comment]
These are libraries/support for the tweaks you installed. Without them, you can't use the tweaks you installed.
