### ISSUE TITLE
Respring loop on iPhone 8+, ios 12.1

### ISSUE THREAD

**Issue by jozefwitek** [pwn20wndstuff/Undecimus#1241]
**Describe the bug**
When I am jailbreaking with option „Reload deamons” I got respring loop, without this option all is good but sometimes I got system freezes and it restart after ~60sec

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone 8+
 - unc0ver Version: 3.4.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
I’ll attach it later

**Comment by jozefwitek** [comment]
[logs.txt](https://github.com/pwn20wndstuff/Undecimus/files/3435773/logs.txt)

**Comment by Yaya48** [comment]
Disable loads tweaks in unc0ver and delete your last tweak installed

**Comment by jozefwitek** [comment]
It keeps repeating
