### ISSUE TITLE
iPad mini 5 on 12.2 not supported

### ISSUE THREAD

**Issue by tangqianzhi** [pwn20wndstuff/Undecimus#1242]
iPad mini 5 on 12.2 not supported
Please tell us How long will it take to jailbreak the iPad mini 5.

**Comment by blackma9ick** [comment]
Your iPad has A12.
unc0ver is **not** for A12 devices !
Chimera is.

**Comment by ghost** [comment]
chimera is not for a12+12.2 but ok
