### ISSUE TITLE
Error "Command PhaseScriptExecution failed with a nonzero exit code" while building

### ISSUE THREAD

**Issue by meponderR** [pwn20wndstuff/Undecimus#1243]
**Describe the bug**
I get "Command PhaseScriptExecution failed with a nonzero exit code" when building in Xcode.

**To Reproduce**
1. Build Undecimus in Xcode

**Screenshots**
<img width="1512" alt="Screen Shot 2019-07-26 at 8 51 12 PM" src="https://user-images.githubusercontent.com/33591888/61988468-5e8b3b80-afe7-11e9-8753-a4f1571b5002.png">
**Device (please complete the following information):**
 - unc0ver Version: Latest GitHub

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[Build target Undecimus_2019-07-26T19-57-08.txt](https://github.com/pwn20wndstuff/Undecimus/files/3437749/Build.target.Undecimus_2019-07-26T19-57-08.txt)

**Comment by meponderR** [comment]
I had to install dpkg.

**Comment by GhostHalston** [comment]
go to Build Phases and delete PhaseScriptExecution
