### ISSUE TITLE
Get frequent freezes / reboots / initial respring takes forever

### ISSUE THREAD

**Issue by jweinraub** [pwn20wndstuff/Undecimus#1246]
**Describe the bug**
Nearly every day, maybe every other, I will be in a random app, not just camera.  I can be doing a crossword puzzle.  I can be reading something on Wikipedia, where the screen stops responding whereby it will eventually reboot on its own, or I force it.  

When I rejailbreak, the intiial respring takes a very long time.  I think this is the daemons issue that was apparent several versions ago.  Battery life drains fairly fast but it is due to crash report, I don't see anything being logged, or at least no culprit, so I disabled the daemon for now.  However, iMessage disables itself almost daily and the Notification Centre is now blank.  I do not know if any or all of these are related but I started noticing all of these issues when trying to figure out the daily lockups.

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X/A1865
 - unc0ver Version: 3.3.7

**Place an "x" between the brackets if true:**
 - [maybe] this is a bug others will be able to reproduce
 - [hard to tell/didnt test long enough] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
Not sure which ones you would want I can restart the crash report daemon, let me know if you need any

**Comment by asdfugil** [comment]
Me too iPhone 6s+ (N66AP),iOS 12.1.1 (stable)

**Comment by rutvik1110** [comment]
same problem on my device too 
device name: iphone 6s
ios version:11.3.1(stable)
uncover version: 3.4.0
