### ISSUE TITLE
cydia

### ISSUE THREAD

**Issue by aDhafeeri** [pwn20wndstuff/Undecimus#1247]
Why when I restart my iPad mini 4 iOS12.2, cydia app not working? so I need to jailbreak it again by Undecimus-v3.4.2
Is this issue normal?

**Comment by mandarimboladao** [comment]
this is not a bug or issue. every time you restart the device you will need rejailbreak to open cydia.

**Comment by aDhafeeri** [comment]
Thanks for ur reply
