### ISSUE TITLE
Camera app reboots the device (12.x issue)

### ISSUE THREAD

**Issue by UnderEu** [pwn20wndstuff/Undecimus#1248]
**Describe the bug**
In random times, when using the camera app, the phone simply reboots. There's no tweaks within the camera or photos app, it occurs when using the camera in lock screen and home screen.
Issue started occuring in 12.1.2 (16C104) and keeps occuring in 12.2 (16E227). Always used the latest u0 releases to date.

**To Reproduce**
1. Open the camera app
2. Shoot one or two photos
3. Open the shoot gallery and return to camera interface

Issue occurs randomly but every singe time it reboots the phone.

**Device (please complete the following information):**
 - iOS Version: 12.2 (16E227)
 - iOS Device: iPhone 5s (N53AP)
 - unc0ver Version: 3.4.2 (Latest, at this moment)

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
[panic-full-2019-07-30-182414.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3449173/panic-full-2019-07-30-182414.ips.txt)

**Comment by TheSniperzzz** [comment]
I've been having the same problems, even with no tweaks after a restore rootfs.
I have a 5s too, ios 12.1.1b3

**Comment by TheSniperzzz** [comment]
Have you updated to iOS 12.4? If so, do you still have the camera random reboots with latest uncover + iOS 12.4?

**Comment by UnderEu** [comment]
> Have you updated to iOS 12.4? If so, do you still have the camera random reboots with latest uncover + iOS 12.4?

Just updated to 12.4 this week and haven't tested the camera, yet. I'll keep an eye on that.

**Comment by TheSniperzzz** [comment]
> > Have you updated to iOS 12.4? If so, do you still have the camera random reboots with latest uncover + iOS 12.4?
> 
> Just updated to 12.4 this week and haven't tested the camera, yet. I'll keep an eye on that.

Thanks a lot, if you get a reboot please let me know, I would really appreaciate your help :)
