### ISSUE TITLE
Cydia Crash IOS 12.2

### ISSUE THREAD

**Issue by bxbx69** [pwn20wndstuff/Undecimus#1250]
iPhone 6
IOS 12.2

Problem: Cydia Crash everytime when i want to open it, tried alrdy re jailbreak but still the same problem

Thanks

**Comment by Soheilnliehos** [comment]
i'd faced to this problem too on my SE running ios 12.2 Jailbroken. to solve this problem all you need to do is to turn off reload deamons & turn on Re-install Cydia then hit jailbreak or Re-jailbreak Button.

**Comment by rfpanfil** [comment]
Same problem. All tweaks working fine but the Cydia app just close when i try to open it.
iPhone 6s, IOS 12.2

**Comment by rfpanfil** [comment]
> i'd faced to this problem too on my SE running ios 12.2 Jailbroken. to solve this problem all you need to do is to turn off reload deamons & turn on Re-install Cydia then hit jailbreak or Re-jailbreak Button.

Didn't worked to me.

**Comment by 3a4oT** [comment]
same thing on iOS 12.4 iPhone 6s
