### ISSUE TITLE
"Auto jailbreak" settings

### ISSUE THREAD

**Issue by bigrck64** [pwn20wndstuff/Undecimus#1252]
enhancement :

Hello all !
I would like to see a new setting after **Auto respring** called **Auto jailbreak**.
When activated, it will auto start the jailbreak task 2 seconds after unc0ver launch. (only in unjailbroken state)

Simple, but usefull :-)
Best regards !

**Comment by bigrck64** [comment]
Hey, am I the only one want this cool settings ? :+1: 
Please, it would be nice.

**Comment by iVosey** [comment]
U not think would be tethered if they could do that ?

**Comment by bigrck64** [comment]
I don't want to change the tethered status of unc0ver !
I just want a setting which auto click on the 'jailbreak' button when I launch the unc0ver app :)
It's like the "auto respring" setting who auto click on "ok" after the jailbreak is done.

**Comment by bigrck64** [comment]
Dear unc0ver team,

Could you have a look into this simple request ?
It's just a new setting who auto launch tappedOnJailbreak{} process at the end of viewDidLoad {} function. 

I coded it when the project was open-source, but now I need your help to add it to official release :-)
Thanks for reading
