### ISSUE TITLE
Cydia menu won’t work properly

### ISSUE THREAD

**Issue by MaltronCraft** [pwn20wndstuff/Undecimus#1253]
**Describe the bug**
When I’m on Cydia on iOS 7,2 version 12.2 and Cydia version 1.1.32 beta 16 and I cannot use the home screen features. I am on the latest Unc0ver version 3.4.2

**Screenshots**
![A2388170-0D2E-48DB-BB6A-5D30E35E7BF3](https://user-images.githubusercontent.com/41383245/62406508-c69ace00-b561-11e9-97ed-cdfe5f5634a9.png)

![F8C31847-6AAD-40B8-906B-ED53320A1B17](https://user-images.githubusercontent.com/41383245/62406507-c69ace00-b561-11e9-9dde-d20456fa070f.png)

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by xMilesManx** [comment]
Known issue. Swipe right on the cells slightly I believe

**Comment by MaltronCraft** [comment]
@xMilesManx That worked! Thanks for the workaround!
