### ISSUE TITLE
I hope to support ios 12.3

### ISSUE THREAD

**Issue by lsl05072239** [pwn20wndstuff/Undecimus#1254]
I hope to support ios 12.3

**Comment by amdy55** [comment]
+1

**Comment by liger89** [comment]
+1

**Comment by clubby789** [comment]
This is just unhelpful spam, don't post things like this so actual issues can be seen.

**Comment by GeoSn0w** [comment]
How is this even an issue?

**Comment by lumciaro** [comment]
THE TIME HAS COME

**Comment by liger89** [comment]
It doesn’t support yet. 12.3 still unsupported for 3.5.0 v

**Comment by zol7r** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1254#issuecomment-522344371

**Comment by 55gY** [comment]
V3.5 does not support iphone6s+ 12.3.1. Will it support it? Do I need to upgrade to 12.4?

**Comment by clubby789** [comment]
Yes you need to upgrade
