### ISSUE TITLE
Bootloop on 12.2 

### ISSUE THREAD

**Issue by kritonpc** [pwn20wndstuff/Undecimus#1255]
I performed the latest unc0ver jailbreak 4 days ago and my phone battery died and it's stuck in a bootloop, but when i connect it to iTunes it appears as if it has 12.4 installed so I can't open the phone, as I can't restore it!

**Comment by Yaya48** [comment]
Put the iphone in DFU Mode and restore it with 3utools

**Comment by kritonpc** [comment]
I tried it but it didn't work either. It appears as if it is in 12.4 and it can't be as I was jailbroken on 12.2 with ota disabled
