### ISSUE TITLE
This app is not allowed to query for scheme Cydia

### ISSUE THREAD

**Issue by bxbx69** [pwn20wndstuff/Undecimus#1261]
unc0ver 3.4.2
iPhone 6
IO 12.2

cant install Cydia and its not doing respring

Please need help

**Comment by dbouras** [comment]
Try the following:
- tap the gear (top right) for options
- turn on "Refresh Icon Cache" and "Reinstall Cydia"
- tap "Done"
- tap "Re-Jailbreak"

**Comment by bxbx69** [comment]
i did it, but still its doing not a respring its only doing exit from uncOver, and there is no Cydia ://

**Comment by dbouras** [comment]
Don't give up :)
Restart phone and try above steps again, preferably without network connection (in airplane mode)
I have experienced the same multiple times on 12.1.2 and 12.1.4

**Comment by bxbx69** [comment]
now its doing respring but stucks on looping
