### ISSUE TITLE
Cannot jailbreak

### ISSUE THREAD

**Issue by versionDefect** [pwn20wndstuff/Undecimus#1265]
**Describe the bug**
Cannot jailbreak

**To Reproduce**
Start Jailbreak

**Screenshots**
It just fails **Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: 7P
 - unc0ver Version: 3.5.0

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x this issue is present on the latest version of unc0ver

**Logs**
(https://github.com/pwn20wndstuff/Undecimus/files/3513367/diagnostics.txt)

**Comment by t00fi** [comment]
Why it says unsupported

**Comment by versionDefect** [comment]
To be honestly I really don’t know it worked in the end so that’s all I care ab
