### ISSUE TITLE
unable to jailbreak

### ISSUE THREAD

**Issue by kornjudistic** [pwn20wndstuff/Undecimus#1268]
**Describe the bug**
cannot jailbreak. got prompted with "unable to repair system" error on 22/31 step

**Screenshots**

![IMG_1684](https://user-images.githubusercontent.com/54249698/63231490-a6157980-c1d9-11e9-88ec-d3a7edaac09c.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone 6
 - unc0ver Version:  3.5.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by dbouras** [comment]
Uninstall, reboot, deploy with impactor and try again. It may take a while (as it also happened on an iphone 6 of mine) but it will eventually succeed.

**Comment by kornjudistic** [comment]
> Uninstall, reboot, deploy with impactor and try again. It may take a while (as it also happened on an iphone 6 of mine) but it will eventually succeed.

hi Dbouras..I previously had yalu ios10.2 jb and updated to 12.4. Should i reset my iphone before i proceed with 12.4jb??

**Comment by dbouras** [comment]
You're always better off restoring to 12.4 (not updating) and then restoring your backup. So make sure to backup using iTunes first.

**Comment by profiles** [comment]
I have fixed this without reset or re-flash firmware.
1. jailbreak with ssh only mode
2. ssh connect to your device
3. do everything you want to fix with shell command provided in /jb/ directory
4. disable ssh only mode and rejailbreak

such as: clear /var/lib/dpkg/info/net.angelxwind.appsyncunified.prerm file contents with "echo" can fix your problem

**Comment by kornjudistic** [comment]
V3.5.2 works fine..got the process done in whooping 7sec. Fastest time for now. But i did get stuck at respring for some time.
