### ISSUE TITLE
 Failed to extract bootstrap

### ISSUE THREAD

**Issue by ios11iphone6s** [pwn20wndstuff/Undecimus#127]
45/65

Errno:0
Test: WEXITSTATUS(rv) == 0
Filename: ViewController.m
Line: 1894
Function: installDeb
Description: Failed to extract bootstrap

Rolectra done on iPhone6S iOS1131 just now.
This is 4th time i'm acing same issue.

Any solution?
______________________________________

Errno:2
Test: WEXITSTATUS(rv) == 0
Filename: ViewController.m
Line: 1894
Function: installDeb
Description: Failed to extract bootstrap

**Comment by sbingner** [comment]
This was fixed in a0b7992c
