### ISSUE TITLE
Cydia Signin failed

### ISSUE THREAD

**Issue by Jessomadic** [pwn20wndstuff/Undecimus#1272]
Using Google to try to signin to Cydia brings up a never ending "Wait" screen. Facebook won't let me sign in at all

**Comment by Aerozolic** [comment]
When tapping on the Google option to sign in you got to do a sort of tap/swipe movement.

**Comment by burt111** [comment]
Having the same issue just purchased tetherme but can’t get my Cydia id

**Comment by Sakisawa101** [comment]
Same here. iPhone 7 iOS 12.4. Taping on sign in with google brings me to a Wait screen.

**Comment by goedenstorfer** [comment]
Facebook lock in does not work. Always get kicked back to the side, where I can choose fb or Google lock in.
iPhone 8, iOS12.4, u0 3.5.6
