### ISSUE TITLE
Cydia network f

### ISSUE THREAD

**Issue by kararalsadi** [pwn20wndstuff/Undecimus#1273]
![B4D808E1-D39A-49E2-91D9-8544A51A9C2A](https://user-images.githubusercontent.com/54262848/63245893-f2a89580-c269-11e9-9e46-09754c98e24b.png)
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by 701yekeparG** [comment]
Very useful to write in english but send screenshot with an language, which really not many people understand!!
