### ISSUE TITLE
Cydia is missing splash screen when opening up

### ISSUE THREAD

**Issue by s0m3sushi** [pwn20wndstuff/Undecimus#1274]
**Describe the bug**
Cydia is missing splash screen when opening up

**To Reproduce**
1. Go to 'Homescreen'
2. Click on 'Cydia'

**Screenshots**
![8-19-2019 161762](https://user-images.githubusercontent.com/30410170/63246122-23012b80-c28c-11e9-8cbd-72c6312cdef0.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 5s
 - unc0ver Version: 3.5.1

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by xMilesManx** [comment]
This should fix itself after a period of time. The first couple of openings will have this for some reason

**Comment by s0m3sushi** [comment]
This bug happens after every respring

**Comment by marcelofares** [comment]
I have the same problem.

**Comment by s0m3sushi** [comment]
nvm it's normal again
