### ISSUE TITLE
Battery Drain 

### ISSUE THREAD

**Issue by Yaya48** [pwn20wndstuff/Undecimus#1275]
Battery Drain On my IPhone 8 IOS 12.4

my tweaks:
![17E47E64-CBFE-4569-B0C2-6D38378DC1BF](https://user-images.githubusercontent.com/34249303/63250996-233dfe80-c26d-11e9-90a1-24bb1cc05127.jpeg)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: IPhone 8
 - unc0ver Version: 3.5.0

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by DKMamba** [comment]
having the same problem with battery draing wait too fast at 1% every 2 minutes with all tweaks uninstalled and have just essentials
