### ISSUE TITLE
IOS 12.4

### ISSUE THREAD

**Issue by olejohanovreas** [pwn20wndstuff/Undecimus#1279]
IOS 12.4 is aparenatly unsupported
![EEF5D008-CCE6-4215-8884-E769941A1CC4](https://user-images.githubusercontent.com/10588365/63263293-7bcec500-c288-11e9-86d7-077253147543.png)

**Comment by Tarang74** [comment]
A12 is not supported, only A11 or lower is supported. 
You're on a 2019 model iPhone.

**Comment by olejohanovreas** [comment]
> A12 not supported, only A11 or lower is supported.
> You're on a 2019 model iPhone.

Will it be supported in the future?

**Comment by Tarang74** [comment]
> > A12 not supported, only A11 or lower is supported.
> > You're on a 2019 model iPhone.
> 
> Will it be supported in the future?

Yes definitely, but most probably when iOS 13 is released, but hopefully soon.

**Comment by olejohanovreas** [comment]
Looking forward to it!
