### ISSUE TITLE
Cydia Bug

### ISSUE THREAD

**Issue by geesehoward79** [pwn20wndstuff/Undecimus#1282]
Cannot acess Cydia's Change package settings.

1. Go to a cydia package
2. Click on Change package settings
3. Nothing happens

![Image-1](https://user-images.githubusercontent.com/54275290/63268146-dc9ad500-c269-11e9-9493-ef2195d7808c.jpg)

 - iOS Version: 12.4
 - iOS Device: iphone 10,4
 - unc0ver Version: 3.5.2
- Cydia 64_1.1.32~b16(en-us)

 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver, since 3.5.0

**Comment by rbnflp** [comment]
i am having the same issue

**Comment by kremedved** [comment]
the same here with iphone x and ipad mini 4, ios 12.4.

**Comment by larrybml** [comment]
Same with iPhone X ios 12.4 unc0ver 3.5.2

**Comment by do4Mother** [comment]
Same with iphone 6s ios 12.4 unc0ver 3.5.2

**Comment by TonyVee73** [comment]
This happens to me on my iPhone X (currently on 12.4 but the issue was happening on 12.2 also)

You need to tap and hold the link then swipe right. It may take a couple of swipes for it to work.

**Comment by TonyVee73** [comment]
Here''s a quick video I uploaded to YouTube. Hopefully it can get soon fixed cause it's annoying.
https://youtu.be/4DfcVHct5TU

**Comment by geesehoward79** [comment]
It works, however is not the right way...

**Comment by paiinnxD** [comment]
can you install apps like this? because I tried to install whatsapp ++ and couldn't, install everything right but no icon appears after installation

**Comment by geesehoward79** [comment]
> can you install apps like this? because I tried to install whatsapp ++ and couldn't, install everything right but no icon appears after installation

Here works normally.

**Comment by paiinnxD** [comment]
> > can you install apps like this? because I tried to install whatsapp ++ and couldn't, install everything right but no icon appears after installation
> 
> Here works normally.

https://www.youtube.com/watch?v=y4DiAUDNP80 see please

**Comment by paiinnxD** [comment]
https://www.youtube.com/watch?v=y4DiAUDNP80 help me please

**Comment by nik312123** [comment]
Tapping “Change Package Settings” on any tweak only highlights the label and does not actually allow one to change the package settings. A temporary workaround to this issue is [here](https://mobile.twitter.com/cpdigdarkroom/status/812111245889388546).

This issue occurs for me on iOS 12.4 and did not occur on iOS 12.1.2 beta 3.

1. Go to Cydia.
2. Tap the “Installed” tab.
3. Tap any installed package shown.
4. Tap “Change Package Settings” without swiping.
5. Note that it simply highlights and does not open.
6. Tap “Change Package Settings” but swipe slightly left upon touching the option.
7. The package settings will now open.

**Comment by ianchow224** [comment]
^can confirm that this works 


> Tapping “Change Package Settings” on any tweak only highlights the label and does not actually allow one to change the package settings. A temporary workaround to this issue is [here](https://mobile.twitter.com/cpdigdarkroom/status/812111245889388546).
> 
> This issue occurs for me on iOS 12.4 and did not occur on iOS 12.1.2 beta 3.
> 
> 1. Go to Cydia.
> 2. Tap the “Installed” tab.
> 3. Tap any installed package shown.
> 4. Tap “Change Package Settings” without swiping.
> 5. Note that it simply highlights and does not open.
> 6. Tap “Change Package Settings” but swipe slightly left upon touching the option.
> 7. The package settings will now open.

**Comment by geesehoward79** [comment]
> Tapping “Change Package Settings” on any tweak only highlights the label and does not actually allow one to change the package settings. A temporary workaround to this issue is [here](https://mobile.twitter.com/cpdigdarkroom/status/812111245889388546).
> 
> This issue occurs for me on iOS 12.4 and did not occur on iOS 12.1.2 beta 3.
> 
> 1. Go to Cydia.
> 2. Tap the “Installed” tab.
> 3. Tap any installed package shown.
> 4. Tap “Change Package Settings” without swiping.
> 5. Note that it simply highlights and does not open.
> 6. Tap “Change Package Settings” but swipe slightly left upon touching the option.
> 7. The package settings will now open.

That was TonyVee73 said before.
