### ISSUE TITLE
ALL JAILBREAK

### ISSUE THREAD

**Issue by kanji77** [pwn20wndstuff/Undecimus#1285]
When i am rebooting device and im trying to get into cydia i cant open it. ( when i am trying to open it it pops and crashes ) also tweaks which i installed before reboot. I cant see it and i could not see it before rebooting.

 - iOS Version: 12.4
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Kalakus** [comment]
Every time you restart your device you need to re-jailbreak with unc0ver. This **aren't** untethered jailbreak!

**Comment by kanji77** [comment]
OK... i installed tweak named PreferenceLoader and it’s works fine. I am closing this issue
