### ISSUE TITLE
provision.cpp; line: 81

### ISSUE THREAD

**Issue by zhangzhenpeng** [pwn20wndstuff/Undecimus#1286]
file: provision.cpp; line: 81; what:

ios/addAppId =9313
The 'Network Extensions' feature is only available to users enrolled in Apple Developer Program. Please visit  https://developer.apple.com/programs/ to enroll.

**Comment by TheNightRider12** [comment]
If you are pressing Start in Cydia impactor, you cannot do that because that goes to install Cydia Extender which requires a $99 a year developer account. You need to drag and drop the IPA into the Cydia impactor window and not press Start.
