### ISSUE TITLE
iPhone 7

### ISSUE THREAD

**Issue by Ryderbike1** [pwn20wndstuff/Undecimus#1288]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

Open unc0ver and click jailbreak from a brand new iOS 12.4 install. Gets to step 2 and errors out. The message on the screen says: “Error. Unable to find kernels credentials in kernel memory”

**To Reproduce**
1. Go to 'unc0ver '
2. Click on 'jailbreak'
3. See error

**Screenshots**

![3BE8C749-59FB-47B3-B91B-625FD7FDE519](https://user-images.githubusercontent.com/54283821/63283849-2930e100-c267-11e9-90b6-ce78fbe12bb1.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 7 (iPhone 9,3)
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by nik312123** [comment]
Try doing the following:
1) Disable Find My iPhone
2) Disable your password and touch ID to unlock
3) Delete the unc0ver application completely
4) Reboot your device
5) Reinstall unc0ver via Cydia Impactor
6) Jailbreak as you would normally

**Comment by Ryderbike1** [comment]
I fixed it by reinstalling unc0ver 3.5.2. Not sure what the first problem was but that fixed it. I should have messed around with it more before submitting a bug message. Oh well
