### ISSUE TITLE
请问A12设备12.2什么时候可以越狱

### ISSUE THREAD

**Issue by hello3280** [pwn20wndstuff/Undecimus#1289]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Pythonic-Rainbow** [comment]
我們還沒有確切日期
Pwn從二月開始已經研究A12支援，可惜A12並沒有unc0ver 所需要的漏洞，所以需要等好一段時間

**Comment by Pythonic-Rainbow** [comment]
The issue can be closed

**Comment by asdfugil** [comment]
OK let me translate the title.
The title is: When will the A12 Devices running iOS12.2 have a jailbreak?

**Comment by Pythonic-Rainbow** [comment]
unc0ver 在v3.5.3為A12提供了局部支援 ,Pwn建議你停留在iOS 12.2, 不要更新
