### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by seedyra1n** [pwn20wndstuff/Undecimus#1292]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to 'youtube...'
2. Click on '..a video..'
3. Scroll down the ’.notification bar ..'
4. resprings to safe mode

**Screenshots**

**Device (please complete the following information):**
 - iOS Version:12.4 
 - iOS Device: iPhone 6
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by xchemical** [comment]
I have the same problem, but it was with the ios messenger and I tested by having my bro send me a message. When the notification try to pop up it will crash and need to restart the respring. It seem like it was asteroid notification thing that was having a conflict for me, so I turn off asteroid notification to fix the problem till it is updated or whatever.
