### ISSUE TITLE
Facetime Skype messenger etc

### ISSUE THREAD

**Issue by seedyra1n** [pwn20wndstuff/Undecimus#1293]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to '.skype..'
2. Click on '..call someone..'
3. Scroll down the '..notification bar..'
4. Resprings to safe mode

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by xchemical** [comment]
The cause could be one of the jailbroken app try to restore rootfs and try installing one jailbroken app one at a time to find out which app is causing the problem.
