### ISSUE TITLE
Uncover crashes at "offsets selected for iOS 12.0 or above"

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1295]
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/3517652/diagnostics.txt)
I am on an iPhone XR on ios 12.1.3 beta 3, and every time i click jailbreak it crashes at 
"offsets selected for iOS 12.0 or above"

edit - ive looked through the logs of Unc0ver and it seems that any time it tries to do anything with offsets, it crashes.

**Comment by ghost** [comment]
[More diagnostocs.txt](https://github.com/pwn20wndstuff/Undecimus/files/3517915/More.diagnostocs.txt)
here is more diagnostic data if needed

**Comment by wanderingbox** [comment]
Happening on my IPhone XS Max 12.1.4, appears to be a a12/a12x issue.

**Comment by marek90** [comment]
Have this problem as well :(
