### ISSUE TITLE
Reboot Step 8/31

### ISSUE THREAD

**Issue by TadeSox** [pwn20wndstuff/Undecimus#1298]
**Describe the bug**
Downloaded the JB for the first time. Started it (over 30 tries now) and it crashes at Step 8.
Seen in twitter comments multiple times.

**To Reproduce**
1. Go to 'u0 App'
2. Click on 'Jailbreak'
3. /
4. Device reboot (not respring, clearly reboots)

**Screenshots**
/

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: 8 Plus
 - unc0ver Version: 3.5.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
/

**Comment by ghost** [comment]
can you attach a log? im having a similar issue and i want to check if its the same issue

**Comment by TadeSox** [comment]
If you tell me how to do it ':D

**Comment by chriskross6** [comment]
Having the same issue as well, iPhone 8 Plus on latest uncover version (3.5.3)

**Comment by chriskross6** [comment]
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/3518002/diagnostics.zip)

**Comment by leedsy** [comment]
Same issue here:
 unc0ver 3.5.3
iPhone X 
iOS 12.1

**Comment by TadeSox** [comment]
From many comments on tweets and YT-Videos it seems like it's an A11 problem

**Comment by 3sphynxes** [comment]
I am having the exact same issues as well. 

I also am not able to use Restore RootFS it crashes immediately after step 8/31. 

I am also not able to install 3.5.2 with CydiaImpactor I am getting a weird error about having the certificate already installed. I used the revoke certificates and remove ID option but it isn't working.

**Comment by 3sphynxes** [comment]
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/3518047/diagnostics.txt)

**Comment by 3sphynxes** [comment]
[Log2.txt](https://github.com/pwn20wndstuff/Undecimus/files/3518052/Log2.txt)

**Comment by tyler-b-nichols** [comment]
Mine also crashes on step 8/31 on iPod 6th gen on iOS 12.4

**Comment by MohamedHassanNasr** [comment]
I had the same issue on both my iPhone 6s Plus and iPhone X, but after removing the last version and installing Undecimus-v3.5.2.ipa, phones are rebooted at step 10 (system snapshot are taken) then after reboot i had run unc0ver again and now both are jailbroken successfully :)

**Comment by ssmith29** [comment]
Use 3.5.2 it works fine on ios 12.4 and iPhone x

**Comment by ghost** [comment]
From the logs i looked at up there it all seems to be similar, it crashes when it tries to do anything with kernel offsets

**Comment by armspkt** [comment]
3.5.3 does not work with iphone x

**Comment by ssmith29** [comment]
3.5.2 Does

**Comment by ghost** [comment]
RIP im on a12

**Comment by vlada1001** [comment]
Can confirm on A8, the latest release does not work.

**Comment by quilenle** [comment]
Can confirm on A9, the latest release does not work.

**Comment by mad2909** [comment]
Same with me, iphone 8+ 12.4

**Comment by HarrisHayat** [comment]
How do I download version 3.5.2 instead of 3.5.3 when 3.5.3 is the only version available?

**Comment by ozonostudio** [comment]
same issue here on iPhone SE with the 3.5.3 version, the Jailbreak works flawless on 3.5.2

**Comment by quilenle** [comment]
@HarrisHayat [Here](https://github.com/pwn20wndstuff/Undecimus/releases)

**Comment by littleGauze** [comment]
same issue here on iPhone 7Plus(12.4) with the 3.5.3version

**Comment by miguelr4720** [comment]
Am Having The Same Problem On The iPhone 8 Plus i Keep Pressing Jailbreak and it keeps Rebooting and Cydia Is Not Showing And Is Not Working Neither For Me 3.5.3 Please Fix???

**Comment by 701yekeparG** [comment]
Same Issue on iPhone 5S. With Unc0ver 3.5.1, 3.5.2, 3.5.3 .

**Comment by littleGauze** [comment]
> same issue here on iPhone 7Plus(12.4) with the 3.5.3version

unc0ver 3.5.2 release works for me.

**Comment by r03n-d** [comment]
I’m having the exact same issue on a 1st gen iPad Air, iOS 12.4, both 3.5.1; 3.5.2; 3.5.3. Can’t get past step 8 where it resprings.

**Comment by 0xdolan** [comment]
I have the same issue:
iOS Version: 12.4
iOS Device: iPhone 7
unc0ver Version: 3.5.3

**Comment by LaThanhSon** [comment]
I am having the exact same issues as well (8plus - iOS 12.4 - unc0ver 3.5.3)
My solution: use unc0ver 3.5.2. Successful. And you try, too.

**Comment by 0xdolan** [comment]
Thanks LaThanhSon. Your solution worked for me as well. I used 3.5.2 version.

**Comment by errorxqtr** [comment]
Hey guys i had the same issue and i found a way to fix just do the jailbreak from the pc method here is the tutorial https://www.youtube.com/watch?v=8ocsaeWqfpw enjoy!

**Comment by kaleem66** [comment]
> can you attach a log? im having a similar issue and i want to check if its the same is

> Am Having The Same Problem On The iPhone 8 Plus i Keep Pressing Jailbreak and it keeps Rebooting and Cydia Is Not Showing And Is Not Working Neither For Me 3.5.3 Please Fix???

Bro you need to downgrade your app to version 3.5.2 that’s should do the job go have a grab on it ....

**Comment by r03n-d** [comment]
This may sound crazy, but I’ve been having troubles with .2 too. I tried it a lot of times. The last time the process would stall at step 1. After a few minutes I pressed the button to go from dark to normal mode and all of a sudden the jailbreak process continues and succeeds.

**Comment by miguelr4720** [comment]
Does Any One Knows How Can i Remove Sileo i Used SnapBack on 12.1 and Sileo is There and I Use Restore root ts files and is not Removing Sileo and i re-jailbrake with Chimera and Sileo Wont Open Now Some One Please Help me With This??

**Comment by miguelr4720** [comment]
Sileo Wont Remove on 12.1 Someone Please Help Me With This

**Comment by errorxqtr** [comment]
> Sileo Wont Remove on 12.1 Someone Please Help Me With This
just update your phone to 12.4 and then jailbreak

**Comment by errorxqtr** [comment]
> **Describe the bug**
> Downloaded the JB for the first time. Started it (over 30 tries now) and it crashes at Step 8.
> Seen in twitter comments multiple times.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'u0 App'
> 2. Click on 'Jailbreak'
> 3. /
> 4. Device reboot (not respring, clearly reboots)
> 
> **Screenshots**
> /
> 
> **Device (please complete the following information):**
> 
> * iOS Version: 12.4
> * iOS Device: 8 Plus
> * unc0ver Version: 3.5.3
> 
> **Place an "x" between the brackets if true:**
> 
> * [x]  this is a bug others will be able to reproduce
> * [x]  this issue is present with all tweaks uninstalled(except for default packages) or disabled
> * [ ]  this issue is present after a rootfs restore
> * [x]  this issue is present on the latest version of unc0ver
> 
> **Logs**
> /

why you closed my answer?
