### ISSUE TITLE
Some apps are crashing with v2

### ISSUE THREAD

**Issue by kskumar9663** [pwn20wndstuff/Undecimus#130]
Some apps especially Hitman Sniper & World Cricket Championship 2 were crashing during launch. Working fine in non jailbreak mode.

**Comment by NickSB2013** [comment]
Yeah, that's not the jailbreak buddy, that's the game's/app's jailbreak detection. You need some jailbreak detection bypass.

**Comment by kskumar9663** [comment]
I used those apps while running all unc0ver versions including the latest 1.1.4 version. There isn’t an issue earlier but it happened after latest changes of unc0ver v2. I reinstalled those apps again to see if they work but it’s same issue.

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb
