### ISSUE TITLE
unc0ver 3.5.3 autoreboot

### ISSUE THREAD

**Issue by xwbchn** [pwn20wndstuff/Undecimus#1303]
**Describe the bug**
autoreboot

**To Reproduce**
1. start jailbreak
2.autoreboot

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 7 Plus
 - unc0ver Version: 3.5.3

use 3.5.2 version is ok

**Comment by saipola** [comment]
How do I get version 3.5.2 on my iphone 7? New to this

**Comment by xwbchn** [comment]
> How do I get version 3.5.2 on my iphone 7? New to this

https://github.com/pwn20wndstuff/Undecimus/releases/download/v3.5.2/Undecimus-v3.5.2.ipa

**Comment by saipola** [comment]
Sorry but can you explain what to do after downloading the link because I'm not able to do anything

**Comment by xwbchn** [comment]
> Sorry but can you explain what to do after downloading the link because I'm not able to do anything

use cydia impactor install this ipa to your phone

**Comment by misosoup7** [comment]
This issue is also happening on an iPad Air:
iOS Version: 12.4
iOS Device: iPad Air
unc0ver Version: 3.5.3

**Comment by royal44** [comment]
Hi, same with my iPad Air 12.4. I tried many times with 3.5.0, 3.5.2 & 3.5.3 and it failed (reboot while jailbreaking). It also failed with 3.5.1 but at the step 22 on 31 "Unable to repair system".

**Comment by Grz3sieK** [comment]
@xwbchn can you give a link for v.3.5.3?

**Comment by xwbchn** [comment]
> @xwbchn can you give a link for v.3.5.3?

pwn delete that

**Comment by Grz3sieK** [comment]
> 
> 
> > @xwbchn can you give a link for v.3.5.3?
> 
> pwn delete that

ok thanks
