### ISSUE TITLE
[Feature Reqeust] Add an option for "Cydia Connection Offline" fix

### ISSUE THREAD

**Issue by esterTion** [pwn20wndstuff/Undecimus#1304]
**Describe the feature you'd like**
Add an option in setting for "Network Offline" fix, and turning it on will delete `/var/preferences/com.apple.networkextension.plist`

**Describe alternatives you've considered**
Anyone can OpenSSH into their device and manually delete the file, but this would help a lot for those have no skill in doing so. 
And it also prevent people who don't use ssh at all from enabling OpenSSH with default password, which can be seen as a security issue? 

**Additional context**
Specific to machines sold in China, apps need to grant network access on first launch, both wifi & cellular. For whatever reason, Cydia failed to trigger this prompt. (Also seen in ReProvision, Flex 3 app).
To solve this issue, the only way is to delete the file mentioned above. Doing such, the system will generate a new file, and fix the Internet access for Cydia (also other failed "system" app).

**Comment by iAladdin** [comment]
@esterTion 
You can change the default jailbreak config on unc0ver:

- Switch on (Re)Install OpenSSH first
- Click jailbreak

![图像](https://user-images.githubusercontent.com/209606/63344039-0f37f100-c382-11e9-96a2-47e5f43103d2.gif)

After jailbreak, you can connect iPhone by ssh from terminal app

```
cd /var/preferences
rm com.apple.networkextension.plist
rm com.apple.networkextension.cache.plist
rm com.apple.networkextension.necp.plist
```

**Comment by esterTion** [comment]
@iAladdin 
I know I can ssh, and I know how to delete the file. 
But this can be too compilicate for majority of people, who knows zero about these things. 
Also, this can be a serious security problem, encourging people to enable OpenSSH and leave it open with `alpine`.
