### ISSUE TITLE
3.5.3 fails to jailbreak iphone 6 or iphone x (both global and on 12.4)

### ISSUE THREAD

**Issue by Hunter926** [pwn20wndstuff/Undecimus#1305]
3.5.2 works great

**Comment by larrybml** [comment]
Yes I can confirm also 3.5.2 is working great on iPhone X, just one thing, any problem with Cydia home screen menus? On my X 12.4 menus are just selecting but not opening.

**Comment by Hunter926** [comment]
Solved by 3.5.3 being pulled from releases.
