### ISSUE TITLE
iPhone Restart before the Jailbreak process is finished + Cydia is not working!

### ISSUE THREAD

**Issue by 701yekeparG** [pwn20wndstuff/Undecimus#1306]
I only updated because the jailbreak was supposed to be possible and it does not work. countless jailbreak crashes, Cydia which does not work (no matter what, on the home screen of Cydia NOTHING works). So far I was at 10.2 and everything worked. It felt like a computer-assisted prosthesis for a leg amputee. Now the handling feels like a wooden leg! Just disappointing, I think I'm switching to Android!

**To Reproduce**
1. Go to 'Cydia'
2. Click on 'Anything...'
4. See error: Nothing happen, except that all chosen tabs change color to gray, like... marked.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 5S
 - unc0ver Version: 3.5.1, 3.5.2, 3.5.3

**Place an "x" between the brackets if true:**
 - [I don't know that, but I'm sure about it.] this is a bug others will be able to reproduce
 - [I have no tweaks installed by myself.] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by larrybml** [comment]
Same problems with Cydia on iPhone X 12.4 Unc0ver 3.5.2 . None of Cydia home screen menus are working. Rest it seams to be fine.
Any idea to fix this?

**Comment by inneromost** [comment]
Also have this problem. KernelUtilities.c(1508): Assertion failure after succesfull jailbreaking. Cydia app crashing or not opening. On Undecimus 3.5.3 jailbreak not working, but on 3.5.2 cydia not opening .iPhone 5s IOS 12.4.

Update: Turn on options Reinstall Cydia and clear Cydia cache and try again to jailbreak. Now Cydia working for me.

**Comment by miguelr4720** [comment]
Someone Please Help Me With This Am Having a Problem Removing Sileo From My iPhone XS MAX i Jailbrake My iPhone a Couple of Months Ago and for Some reason i Used Chimera Jailbrake and I Used The Snapback Tweak to Remove Sileo and it did not Fully Remove Sileo.

Sileo Icon is still There and Snapback Only Remove My Tweaks from My Home Screen But it Did not Remove Sileo From My Phone and Snapback did Not Work To Un-Jailbrake My iPhone XS MAX 12.1 and am trying to Jailbrake Using Uncover Someone Please Help with this??
