### ISSUE TITLE
I'm using iPhone 6s on ios 12.1

### ISSUE THREAD

**Issue by shaikho** [pwn20wndstuff/Undecimus#1310]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by shaikho** [comment]
i downloaded the latest version and when i wanted to jailbreak it kept restarting the device once at 1 and other times at 8 i downloaded the direct previous version and worked out well, thank you.

**Comment by foxnoodles** [comment]
I +1 this. iPhone 6s - iOS 12.4.
3.5.2 worked fine. The last one just keeps restarting. 
I'm too lazy to download the previous one cuz I'm using Tweakbox. 
So I'll wait for the next version.

**Comment by shaikho** [comment]
i just used Undecimus-v3.5.6 this new version fixed this issue
