### ISSUE TITLE
Unable to start Cydia Substrate 

### ISSUE THREAD

**Issue by asdfugil** [pwn20wndstuff/Undecimus#1311]
**Describe the bug**
Same as Title

**To Reproduce**
1. Go to 'Unc0ver'
2. Click on '(Re-)Jailbreak'
3. Error: Unable to Start Cydia Substrate 

**Screenshots**
![7BC98295-0410-42E5-948C-0B882AFC8E1A](https://user-images.githubusercontent.com/42699250/63344983-47403380-c384-11e9-830c-e7b9ddbcb8fa.png)
**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device: iPhone 6s+ (N66AP)
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

**Comment by ghost** [comment]
I'm getting same issue on iPhone 6 v3.5.6 - Had constant issue's since puppet updates.  JB nuch much more difficult.  Fails 1 in 20 times now.

View logs don't work. etc.  Time for Chimera me think.

**Comment by richwincott** [comment]
I also have this issue latest version 3.7.0b1 A12X - #1558

**Comment by linux3ronga** [comment]
You need to kill Cydia from the Multi-tasking

**Comment by rcelus** [comment]
Cryptiiiic...chill out!

**Comment by Cryptiiiic** [comment]
substrate is obsolete above iOS 11 sir in regards to unc0ver @rcelus

**Comment by rcelus** [comment]
Yea! u r right...But what can u do about it? Blowing up emails will only make things move even slower...no one wants 2 b pressured...plus this not the time to expect anyone to work on their projects when so many other things are more important...like living, family, and one's health!

**Comment by Cryptiiiic** [comment]
Since when did I purposely "blow up emails"

**Comment by asdfugil** [comment]
Since you start closing issues

**Comment by rcelus** [comment]
I (we) got over 360 + conversion emails from u...(Cryptiiiic)....slow down it will happen just not right now!

**Comment by rcelus** [comment]
if and when developers get back on their grind, they will look into ur issues...remember tweaks, and jailbreaks....take time!

**Comment by asdfugil** [comment]
Well unc0ver is closed source now so this repo is kinda dead (except the releases)

**Comment by Cryptiiiic** [comment]
@rcelus you are the one that subscribed to 360 + issues lmao
how is that my fault

**Comment by asdfugil** [comment]
Yeah but I got 100+ emails too

**Comment by Cryptiiiic** [comment]
![image](https://user-images.githubusercontent.com/27748705/77823979-57f41d00-70bc-11ea-808a-0a3ea6c402ff.png)

**Comment by Cryptiiiic** [comment]
![image](https://user-images.githubusercontent.com/27748705/77823994-69d5c000-70bc-11ea-8e50-92b5f4e10248.png)
Don't click watch then

**Comment by rcelus** [comment]
....I'm done, goodnight or good morning depending on where u r n da world! Peace (Cryptiiiic)!

**Comment by asdfugil** [comment]
I never did that 
~~Although I commented on like 100 issues~~

**Comment by Cryptiiiic** [comment]
thank you, I'm sorry for the disturbance. Big changes coming to issues section.

**Comment by Cryptiiiic** [comment]
@Assfugil you subscribe to issues you reply to

**Comment by rcelus** [comment]
....and they will!

**Comment by rcelus** [comment]
...peace!
