### ISSUE TITLE
Restore RootFS actually creates system snapshot when there is none

### ISSUE THREAD

**Issue by TheChatty** [pwn20wndstuff/Undecimus#1313]
**Describe the bug**
When trying to clean devices I happen to run "Restore RootFS" on devices which no longer have a snapshot because I ran the same function before already. In this case unc0ver in fact creates a system snapshot instead of failing with an error message like "there is no snapshot to be restored".

**To Reproduce**
1. Install jailbreak
2. Run "Restore RootFS"
3. Run "Restore RootFS" a second time
4. See new snapshot being created

**Device (please complete the following information):**
 - iOS Version: anyone
 - iOS Device: anyone
 - unc0ver Version: up to 3.5.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by asdfugil** [comment]
*rename system snapshot
