### ISSUE TITLE
Eventually a Solution for iOS 12.4 JB

### ISSUE THREAD

**Issue by Cardesh38** [pwn20wndstuff/Undecimus#1316]
I had the problem since last night, that unc0ver everytime crashed at 8/32 or stucked at 1/32. i had the ios 12.1.1 jb. i updated the iphone 6 via itunes to 12.4. didnt done a fresh 12.4 install.

What i have done:

1. Uninstalled version 3.5.3
2. Restarted Phone
3. Installed Version 3.5.1
4. Done rootfs till success
5. Uninstalled version 3.5.1 
6. restarted phone
7. installed version 3.5.2
8. airplane mode activated
9. jailbreaked the phone (2 attempts till sucess)

Maybe this will work for some users.

**Comment by Pythonic-Rainbow** [comment]
You should not post this to GitHub. GitHub Issues are only for legit bugs, not a comment. You can comment this on another issue, but should not creating a new one.
