### ISSUE TITLE
Sileo Wont Remove Using Snapback Tweak on iOS 12.1

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1318]
Someone Please Help Me With This Am Having a Problem Removing Sileo From My iPhone XS MAX i Jailbrake My iPhone a Couple of Months Ago and for Some reason i Used Chimera Jailbrake and I Used The Snapback Tweak to Remove Sileo and it did not Fully Remove Sileo.

Sileo Icon is still There and Snapback Only Remove My Tweaks from My Home Screen But it Did not Remove Sileo From My Phone and Snapback did Not Work To Un-Jailbrake My iPhone XS MAX 12.1 and am trying to Jailbrake Using Uncover Someone Please Help with this??

**Comment by miguelr4720** [comment]
i Try Restore Rootfs and it did not work  and I Re-Jailbrake With Sileo 

Sileo Will Not Open any More 

I Used Uncover 3.0.0 and Cydia Does Not Come Back Neither??

**Comment by SarKaa** [comment]
It's because sileo is built to be incompatible with jailbreaks which aren't Electra or chimera. And cydia won't open because unc0ver thinks you don't need it. When jailbreaking, make sure you turn the (re)install cydia option on
