### ISSUE TITLE
ios 12.4, error report-unable to install firmware debs

### ISSUE THREAD

**Issue by 508080120** [pwn20wndstuff/Undecimus#1319]
Hi,
As my concern, my iPhone 7 Plus with ios 12.4 couldn't continue in step 22/33.
unc0ver v3.5.2

**Comment by YajunWang2002** [comment]
me too

**Comment by velkovb** [comment]
I have the same issue on 6S+ but it was like that on previous releases as well. Now on 12.4 same thing.

**Comment by andylee1890** [comment]
same issue on ipad mini4

**Comment by tayvo123** [comment]
I am having the same issue with my iPhone 7 plus on iOS 12.4. I am almost certain that it was the newest version of unc0ver as well.

**Comment by Zvelteufs** [comment]
i have the same problem, i'm on iOS 12.0.1 on my iPhone SE.
