### ISSUE TITLE
Issue at 31/31 step-completed-Partial-Jailbreak for A12 devices on IOS 12+(Uncover Jailbreak)

### ISSUE THREAD

**Issue by slenderender** [pwn20wndstuff/Undecimus#1320]
**Describe the bug**
I know this is the partial A12 jailbreak for IOS 12+ but there is a bug or some type of issue that I wouldn't say I discovered.  So I have an Iphone Xs, the jailbreak would say 31/31 completed, then it wouldn't give me Cydia.  I put the device on airplane mode and it would still have unsuccessful attempts.  Like I said again, I understand this partially works, but I've done the attempt so many times for it to say jailbreak completed.  Thanks for all your hard work on it.  You guys deserve more of the best.   

**To Reproduce**
1. Go to 'Unc0ver app'
2. Click on 'Unc0ver app'
3. Scroll down to 'Jailbreak'
4. See error- Completed 31/31 jailbreak, reboots, then Cydia doesn't show up

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: Iphone Xs
 - unc0ver Version: v3.5.3

**Place an "x" between the brackets if true:**
 - [ x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
*Images coming soon

**Comment by bromptonista** [comment]
Had similar problems with iPad Pro 12.9, iOS 12.4, uncover 3.5.2.
Solution was to keep trying... Also having uncover app on the second page of apps rather than third may have helped?
