### ISSUE TITLE
Device reboots while jailbreaking(iPhone 5s/iOS12.4

### ISSUE THREAD

**Issue by eksprestren** [pwn20wndstuff/Undecimus#1321]
**Describe the bug**
While jailbreaking, the device suddenly reboots.

**To Reproduce**
1. Open the app.
2. Click on 'Jailbreak'
3. Wait 10 seconds.
4. It will reboot.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version:12.4 
 - iOS Device:iPhone 5s
 - unc0ver Version:3.5.2 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by rekenerd** [comment]
I'm facing the same issue with iPhone 6.

**Comment by ablebodied** [comment]
I have the same problem on my iPhone 5s

**Comment by ustczzh** [comment]
I have the same problem on iPhone 6p.

**Comment by mittermayr** [comment]
TURN ON AIRPLANE MODE.

I just resolved it on my iPhone 5s by disabled everything in the settings menu except for: Reinstall Cydia, and "get-task-allow", with just those two on, it went through, gave me a note about the filesystem, then rebooted. I opened it again (second time), and tapped Jailbreak again and it got stuck. So I enabled airplane mode and it ran right through!

Before doing any of the steps I mention, go ahead and turn airplane mode on and try as-is. If it doesn't work, try disabling some settings.

**Comment by cdlenfert** [comment]
Strange. Yeah I was able to jailbreak after a restart on my iPhone 6 using 3.5.2. I was able to do so again much faster the next time I restarted. On the 3rd or so try I started getting reboots around step 3. Tried reinstalling 3.5.2 but no change. Enabling Airplane Mode the jailbreak worked on the first try.

**Comment by palxex** [comment]
Same here; iPad Air 12.4, both airplane mode on and siri off. After 1st time wait 10 minute and reboot( after reboot nothing happened , cydia not installed ), everytime reboot after 10 sec.
EDIT: succeed after follow @mittermayr guide.

**Comment by superbonaci** [comment]
I had same problem on iPhone 5S, even with unc0ver 3.5.5, but following @mittermayr advice worked: disable wifi from settings not toggle, enable airplane mode, and jailbreak with only two settings enabled (reinstall cydia and get-task-allow).

**Comment by ablebodied** [comment]
Finally succeeded on my iPhone 5S iOS12.4  with version  3.5.5

**Comment by bradxy** [comment]
@mittermayr This worked for me on 3.5.5, thanks!

> TURN ON AIRPLANE MODE.
> 
> I just resolved it on my iPhone 5s by disabled everything in the settings menu except for: Reinstall Cydia, and "get-task-allow", with just those two on, it went through, gave me a note about the filesystem, then rebooted. I opened it again (second time), and tapped Jailbreak again and it got stuck. So I enabled airplane mode and it ran right through!
> 
> Before doing any of the steps I mention, go ahead and turn airplane mode on and try as-is. If it doesn't work, try disabling some settings.

**Comment by HanseSecure** [comment]
This also worked for me with 3.5.6 on IPhone 6 with iOS 12.4

**Sum:**

1. Turn on Airplane Mode
2. Only two settings enabled (reinstall cydia and get-task-allow)

_Note:
Sometimes you have to kill the unc0ver App and restart the jailbreak process_
