### ISSUE TITLE
Amazon Music crashing on launch 12.4 iphone 6

### ISSUE THREAD

**Issue by robmartin1987** [pwn20wndstuff/Undecimus#1322]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to '...' uncover hit jailbreak after suscesful jailbreak 
2. Click on '....' amazon music 
3. Scroll down to '....' should crash almost instantly 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone 6
 - unc0ver Version: 3.5.3/3.5.2/3.5.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
[AmazonCloudPlayer-2019-08-20-173602.zip](https://github.com/pwn20wndstuff/Undecimus/files/3523803/AmazonCloudPlayer-2019-08-20-173602.zip)

**Comment by DaRealPBJ** [comment]
Same issue with my iPhone 8 plus

**Comment by cyntrifical** [comment]
having the same issue since newest updates

**Comment by TheyCallMePBJ** [comment]
Amazon Music lets me open it, but when I try to play a song, the app crashes

Steps to recreate:
i) Got to Amazon Music after a successful jailbreak using unc0ver version 3.5.2
ii)Try playing a song

Device info:
 iOS 12.4
iPhone 8+
Unc0ver version 3.5.2

✅ this is a bug others will be able to reproduce 
[X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
[    ] this issue is present after a rootfs restore
[X ] this issue is present on the latest version of unc0ver

**Comment by cyntrifical** [comment]
Sounds exactly like my problem. What happens is it will open as normal and if I play a song I have downloaded to my device it doesn’t crash but if I attempt to stream it crashes instantly, then afterwords it will begin to crash on launch and have “send error report to developers” pop up. Didn’t start happening until most recent unc0ver and will do it even in an unjailbroken state

**Comment by TheyCallMePBJ** [comment]
The issue persists even in v3.5.5

**Comment by cyntrifical** [comment]
I can confirm aswell on iPhone 8 iOS 12.4, u0 3.5.6

**Comment by thatbrooklynkidyo** [comment]
Remove the letmeblock cydia app

**Comment by cyntrifical** [comment]
I removed Let Me Block and issue still persists on iPhone 8, iOS 12.4 u0 3.5.5

**Comment by TheyCallMePBJ** [comment]
Same thing on iPhone 8+ unc0ver version 3.5.6

**Comment by indypup** [comment]
I'm having the same issue which I just discovered today.  iPhone 6s+  12.4  I installed [appstore++] and downgraded Amazon Music to 8.9.3 and now it works.   Amazon has been upgrading DRM in every version since 8.9.3

**Comment by thatbrooklynkidyo** [comment]
Try current version of Unc0ver.

**Comment by thinkingmac** [comment]
> I'm having the same issue which I just discovered today. iPhone 6s+ 12.4 I installed [appstore++] and downgraded Amazon Music to 8.9.3 and now it works. Amazon has been upgrading DRM in every version since 8.9.3

Thanks Indypup, for this information and workaround! :) I installed appstore++, installed version 8.6.0 and it works. :)
Which externalidentifier to enter for 8.9.3 ? 
(I can only find 8.6.0 and older)

**Comment by NickinAction** [comment]
> > I'm having the same issue which I just discovered today. iPhone 6s+ 12.4 I installed [appstore++] and downgraded Amazon Music to 8.9.3 and now it works. Amazon has been upgrading DRM in every version since 8.9.3
> 
> Thanks Indypup, for this information and workaround! :) I installed appstore++, installed version 8.6.0 and it works. :)
> Which externalidentifier to enter for 8.9.3 ?
> (I can only find 8.6.0 and older)

im stilll having it crash after downgrading to 8.6.0 and on 8.9.3 it opens but won't let me do anything  while telling me i have an older version running. Am using iphone 7 on ios 12.4

**Comment by 877dev** [comment]
Same crash here, I guess it has not been fixed/ cannot be fixed.

Crashes most times on startup, when it does start I get a warning popup "Low disk space". Then crashes if try to play anything.

iOS 12.4
iPhone 8 (10,4)
unc0ver version 3.6.2+1.gb9c17cb
Amazon Music app version 9.3.1.12466 64bit

**Comment by Nicholasc04** [comment]
> I'm having the same issue which I just discovered today. iPhone 6s+ 12.4 I installed [appstore++] and downgraded Amazon Music to 8.9.3 and now it works. Amazon has been upgrading DRM in every version since 8.9.3

Used the [App Admin] tweak to downgrade but it works the same way and fixed the app, for anyone else using this method make sure to delete then re-install the app, don't just downgrade the app while it's installed as it gives an error when opening the app again. Been dealing with this for months and glad to finally get it fixed.
