### ISSUE TITLE
bug no cydia Iphone 6 IOS 12.4

### ISSUE THREAD

**Issue by paiinnxD** [pwn20wndstuff/Undecimus#1325]
after installing jailbreak on ios 12.4 on my iphone 6 when opening cydia and trying to open some tab does not open anything, I have even reinstalled it and it's the same way help me

**Comment by malhal** [comment]
see here for a workaround which is to swipe on the table cell a few times, see the video

https://github.com/pwn20wndstuff/Undecimus/issues/1282
