### ISSUE TITLE
Crashes on launch 3.5.2 / iPhone 5s / 12.4

### ISSUE THREAD

**Issue by dylib** [pwn20wndstuff/Undecimus#1329]
**Describe the bug**
Installed 3.5.2 on iPhone 5s 12.4 via Impactor (0.9.52, although about says 0.9.44).

**To Reproduce**
1. Download Unc0ver jailbreak IPA onto your computer
2. Download Cydia Impactor
3. Open Cydia Impactor and connect your iPhone or iPad to your computer cydia impactor screen
4. Make sure it is detected; find the Uncover IPA file and drag it into Cydia Impactor
5. Input your Apple ID and password and leave Cydia Impactor to its work; the Unc0ver file will be signed and loaded onto your device
6. Once the process has finished, open your iOS Settings and go to General > Profiles iphone profile
7. Find the app profile or that with your Apple ID and tap on it
8. Tap Trust and check it changes to Delete
9. Disable Siri and enable Airplane mode on your device
10. Reboot and check that Airplane mode is still enabled and that Wi-Fi has been disabled
11. Tap the Uncover icon on your homepage to continue the jailbreak process

**Screenshots**
![2019-08-21 20_01_24](https://user-images.githubusercontent.com/17288131/63482646-791dcc80-c44e-11e9-96cd-e753104d97c8.gif)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 5s
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
—

**Comment by lewis0917** [comment]
I have the same issue on my a7 device, trying v3.5. So I’m not gonna update to latest iOS, till this gets fixed.
