### ISSUE TITLE
In-built sileo compatibility

### ISSUE THREAD

**Issue by SarKaa** [pwn20wndstuff/Undecimus#1331]
In built sileo compatibility, like unc0ver dark, but compatible with iOS 12.4. Sileo Is much better than cydia, so it's unfair that Electra don't let you use sileo on other jailbreaks

**Comment by debouncedgit** [comment]
There's a reason a fork such as unc0ver dark is there. To allow you to have features in which isn't going to be added into u0. This is one of them. Sileo won't be added to u0 (likely).

**Comment by SarKaa** [comment]
But Unc0ver dark doesn't support iOS 12.2-4. and isn't as advanced and as fast as unc0ver
