### ISSUE TITLE
[12.4] Cydia Crashes after Updating Substrate Compatibility Layer (99.2)

### ISSUE THREAD

**Issue by ianchow224** [pwn20wndstuff/Undecimus#1333]
1. After opening Cydia for the first time after rejailbreaking, there is a new update for "Substrate Compatibility Layer for ver. 99.2 (currently installed on 0.9.7033)
2. Once updated, sources can no longer be refreshed and when  Cydia is restarted, it will just crash
3. Afterwards, when you open Uncover, the app will freeze and generate a never ending blob of the starting screen text and when trying to change settings app will freeze
*screen recording attached*

So far, the only thing I have found that has fixed this is to either RestoreFS and rejailbreak or clear Cydia cache after restarting the phone while re-jailbreaking.

 - iOS Version: 12.4
 - iOS Device: iPhone 7
 - unc0ver Version: 3.5.2

 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

![IMG_8235](https://user-images.githubusercontent.com/42014732/63504779-14329880-c487-11e9-9311-3733b28099d0.PNG)

[IMG_8238.TRIM.mp4.zip](https://github.com/pwn20wndstuff/Undecimus/files/3529470/IMG_8238.TRIM.mp4.zip)

**Comment by AMINBOB** [comment]
I have same issue, so what is your suggestion? and what it cause if I remove it?

**Comment by ianchow224** [comment]
as i stated in the post, you have to clear cydia cache when in unjailbroken state and ignore the update for it

**Comment by AMINBOB** [comment]
Ye I did as You mentioned in the post, but still it’s showing in changes section, that mean need to be upgrade it, and when i try upgrade it i face same issue

**Comment by nickflash01** [comment]
yep same issue

**Comment by badger200** [comment]
I got this issue when I added electrarepo64.coolstar.org, that repo always wants to install a ton of conflicting shit, I think it’s run by the guy behind “Substitute” which is a competitor to Saurik’s MobileSubstrate. Either find and remove the offending repo that keeps offering those upgrades, or simply ignore them and avoid upgrading those items.

**Comment by AMINBOB** [comment]
Ye just ignore the updates
