### ISSUE TITLE
unc0ver says unsupported

### ISSUE THREAD

**Issue by Tiger312** [pwn20wndstuff/Undecimus#1338]
I got unc0ver for my iPhone XR, clicked on it and where it is meant to say Jailbreak it says Unsupported and i don't know why.

I'm running ios 12.4

**Comment by Vestaia** [comment]
The iPhone XR is not supported by the release version 3.5.2. Partial support is available if you compile 3.5.3; though Cydia is not compatible with the iPhone XR due to the A12 chipset.

**Comment by td512** [comment]
Support for A12 devices is in 3.5.5 however. I would upgrade to that point release. It doesn't as yet support tweaks though

**Comment by Tiger312** [comment]
It does say jailbreak now but it doesn't install Cydia app yet. I'll just wait untill it can fix itself

**Comment by HonoringBills** [comment]
Yeah, I believe we’re all just waiting for Cydia to be fixed at this point, does anyone know any way around this?

**Comment by Vestaia** [comment]
@HonoringBills Tweaks aren't supported yet by uncover 3.5.6 for A12/A12X devices.
Currently, the jailbreak gives you access to SSH and remount filesystem as read-write.
If you want cydia and tweaks, either help with the development or wait.
