### ISSUE TITLE
SpringBoard crash

### ISSUE THREAD

**Issue by yuvrajsab** [pwn20wndstuff/Undecimus#134]
random SpringBoard crashes on my iphone 6s.

![img_2161](https://user-images.githubusercontent.com/27115069/49335963-88d65600-f61e-11e8-9920-a7327809a84e.PNG)

**Comment by mattp12** [comment]
Post more info such as a tweak list (use Flame to easily get it).

**Comment by Cryptiiiic** [comment]
@yuvrajsab you didn't respond, so I'm closing this.
