### ISSUE TITLE
Cydiacant open

### ISSUE THREAD

**Issue by d7s** [pwn20wndstuff/Undecimus#1340]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: IPHONE X
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by misosoup7** [comment]
If you reboot the phone, you'll need to jailbreak again before Cydia or any jailbreak apps will open...
