### ISSUE TITLE
XS Max 12.4 some apps wont launch after successful jailbreak

### ISSUE THREAD

**Issue by cyberpunc** [pwn20wndstuff/Undecimus#1342]
Subject says it all.

**To Reproduce**
1. Go to Snapchat, app opens and immediately quits

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: XS Max 512gb
 - unc0ver Version: 3.5.4

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Comment by td512** [comment]
Snap seems to be working for me

- iOS Version: 12.4
- iOS Device: XS Max 256GB
- unc0ver Version: 3.5.5

You might want to update to 3.5.5

**Comment by cyberpunc** [comment]
3.5.5 fixed it
