### ISSUE TITLE
Dialog: OK / View Log

### ISSUE THREAD

**Issue by Sweepi** [pwn20wndstuff/Undecimus#1348]
Example screenshot:
![Image 23 08 19 at 01 47](https://user-images.githubusercontent.com/35932592/63557226-23c5e600-c548-11e9-8086-e07649642750.jpg)

In various situations, unc0ver shows a modal dialog which is structured as follows:
\<msg\>
Option A: OK
Option B: View Log

Are there situations where there is a difference between the two options? For me they always do the same. I suggest to replace Option A and Option B with a single button labeled "Dismiss" where both buttons would do the same.

**Comment by paperclover** [comment]
i've noticed for the popup that says "successful jailbreak etc" the OK button immedietly resprings and the "view log" delays that respring so you can see the log. but on a lot of dialogs (i think every other one) this button is useless.
