### ISSUE TITLE
cydia home screen issues

### ISSUE THREAD

**Issue by fazikamboh** [pwn20wndstuff/Undecimus#1349]
cydia home screen all options not working after flash iphone i will try jailbreak again but its not working please fix cydia home for reinstalling sorces and storage information iphone 6 A8 ios 12.4

**Comment by XpliSyL** [comment]
This sounds dumb but I found that if you slightly swipe as you tap it'll open the pages. 
That's how I managed to sign in and link my device to install purchased stuff.
