### ISSUE TITLE
Battery Is Draining on latest jailbreak

### ISSUE THREAD

**Issue by DKMamba** [pwn20wndstuff/Undecimus#1350]
**Describe the bug**
Deleted all my installed tweaks, and battery still drains about 1% every 2 mins or so.
Battery was charged to 98% overnight and in the morning it was 36%.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 7 Plus
 - unc0ver Version: 3.5.5

**Place an "x" between the brackets if true:**
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present on the latest version of unc0ver
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present after a rootfs restore

**Logs**
If applicable, add logs or error messages here.

**Comment by queerdude** [comment]
Same here, my device iPhone X, IOS 11.3. Battery drops from 75% to 48% from 01:00 to 08:00

**Comment by DKMamba** [comment]
damn how long have you been Jailbroken for and been experiencing that?
I previously had it on 11.3.1 ios and is was smooth and stable, but wanted to switch to the current ios w/ 12.4 and it has been draining like no other.

**Comment by nameless1** [comment]
Also have this happen, unc0ver 3.5.5 iPhone 7 12.4 died in 3 hours, previously on 10.3.3 and would last atleast 9 to 10 hours. There has to be a memory leak or something because that is the first time my phone died like that.

**Comment by queerdude** [comment]
to be exact what I mean is Same here, my device iPhone X, IOS 11.3. Battery drops from 75% to 48% from 01:00 to 08:00 (phone was put into sleep mode cuz I was asleep)

**Comment by DKMamba** [comment]
i was previously on u0 3.5.2, and thought the newest one 3.5.5 would fix the drain leak, but it didn't. Honestly don't know what else to do except keep an extra external or keep the phone plugged into charge. Hope they fix this soon problem soon.
