### ISSUE TITLE
Set Boot Nonce Causes Reboot

### ISSUE THREAD

**Issue by misosoup7** [pwn20wndstuff/Undecimus#1351]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. On Unc0ver 3.5.0 to 3.5.5, leave the settings as default when you first install
2. This should have Set Boot Nonce as enabled with generator of 0x1111111111111111
3. Pressing jailbreaking will result iPad Air to reboot before step 18.
4. Setting the option to off will complete jailbreak successfully

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPad Air (iPad 4,1)
 - unc0ver Version: 3.5.0 to 3.5.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
No error messages, and where are the logs? I can try to retrieve them.

**Comment by asdfugil** [comment]
The logs are in unc0ver > settings > share diagnostic data
