### ISSUE TITLE
Jailbreaking fails due to the preinit script in firmware-sbin_0-1_all.deb trying to delete /usr/sbin/ioreg, which doesn't exist

### ISSUE THREAD

**Issue by brickcollector** [pwn20wndstuff/Undecimus#1352]
**Describe the bug**
Using default settings, the jailbreaking fails at step 22/31 due to preinit script in firmware-sbin_0-1_all.deb trying to delete /usr/sbin/ioreg. The file doesn't exist, which will abort the jailbreaking procedure.

**To Reproduce**
1. Upgrade iPhone SE from iOS 9.3.2 or iOS 9.3.3 directly to 12.4
2. Install Unc0ver with Cydia Impactor
3. Launch Unc0ver with default settings
4. Jailbraking fails at 22/31 due to the above error in the preinit script.

**Screenshots**
n/a

**Device (please complete the following information):**
iOS 12.4 upgraded from 9.3.2 or 9.3.3 (reproduced on two devices).
iPhone SE model N69AP.
Unc0ver versions 3.5.0 to 3.5.5 tried.

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [untested - afraid of possible data loss] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
runCommandv(294): Preparing to unpack ..././firmware-sbin_0-1_all.deb
runCommandv(294): Expected firmware file "/usr/sbin/ioreg" missing
runCommandv(294): dpkg: error processing archive /var/lib/undecimus/apt/./firmware-sbin_0-1_all.deb (--unpack): subprocess new pre-installation script returned error status 1
<snip successfully deleted files>
runCommandv(294): E: Sub-process /usr/bin/dpkg returned an error code (1)
runCommandv(294) completed with exit status 200
Unable to upgrade apt packages

**Comment by badger200** [comment]
Yep I confirm this same exact thing happened to me on my iPad Pro 9.7” coming from iOS 10.2.1 w/doubleh3lix > 12.4 w/unc0ver. I had to tinker around to find a copy of ioreg to pass this point. 

There’s also a bug with apt.sbingner.com repository essential upgrades to unc0ver which delete launchctl which immediately causes the dpkg to fail in Cydia with a cydo error 2. I have to manually use Filza to copy /jb/bin/launchctl to /bin, which “solves” it until next time.
