### ISSUE TITLE
iOS 12.2 - XS Max 12, Jailbreak success but no Cydia

### ISSUE THREAD

**Issue by keytrap-x86** [pwn20wndstuff/Undecimus#1354]
I tryed many times to jailbreak, it works 
![image](https://user-images.githubusercontent.com/17864005/63589687-13465780-c5aa-11e9-9b86-19050cb34410.png)

When it finishes there's no Cydia installed
Tried to respring but still no Cydia

Edit: Oh, just saw  [this issue](https://github.com/pwn20wndstuff/Undecimus/issues/823)
Seem's that Cydia won't work on 12 devices.
What about Sileo then ? Why aint it install Sileo instead

**Comment by spalekg** [comment]
There is no Cydia ready for A12 devices with iOS 12.4 (iPhone XS, XR)
Somenone need to make changes in Cydia to be compatible with A12.
