### ISSUE TITLE
Can’t check for firmware update

### ISSUE THREAD

**Issue by lewis0917** [pwn20wndstuff/Undecimus#1355]
When jailbroken, even with “disable updates” set to off, it loads endlessly when selecting ‘software update’.

**Comment by lewis0917** [comment]
Would I be safe to reboot my a7 iOS 11 device and update it from Settings then jailbreak? Or would it be more proficient to update via iTunes?

**Comment by lewis0917** [comment]
Is it just me or has battery life increased exponentially with u0 3.5.5. Still running iOS 11.2.6.

**Comment by lewis0917** [comment]
Is it just me or has battery life increased exponentially with u0 3.5.5 (after sub-3.3.4). Still running iOS 11.2.6.

**Comment by res1492** [comment]
Part of the jailbreak is that it stops your phone from searching and updating...
OTA updates are fine, i did update from my SE then JB on 3.5.2....
Sorry for the late replys

**Comment by DJ-Haegi** [comment]
Don’t update with installed JB. Remove the JB via Restore RootFS, than Update ist via iTunes! Then install jailbreak again

**Comment by lewis0917** [comment]
Why so? And I’ll have to restore via iTunes anyhow for compatible iOS 12.4 only.
