### ISSUE TITLE
Help me my cydia don´t install any apps

### ISSUE THREAD

**Issue by paiinnxD** [pwn20wndstuff/Undecimus#1359]
i installed cydia v64_1.132 ~ b16 on ios 12.4 but i can't install any apps simply the app doesn't appear to use after i finish installing

see video https://www.youtube.com/watch?v=YIrujeL45DE

**Comment by nil-malh** [comment]
Did you tried to run the uicache command with SSH ?

**Comment by paiinnxD** [comment]
no, how do i do it?
