### ISSUE TITLE
Sudden respring

### ISSUE THREAD

**Issue by frncscdrjr** [pwn20wndstuff/Undecimus#1362]
**Describe the bug**
It sudden resprings twice or thrice a day I thought it was normal after I jailbreak my phone with no tweaks involved.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone SE
 - unc0ver Version: 3.5.5

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Grovre** [comment]
It sometimes straight up crashes for me. Can't JB my phone anymore until it's signed again because my phone crashed today which suuucks. Once you use JB, there aint no going back
