### ISSUE TITLE
XS MAX 12.4 Unable to find kernel's credentials in kernel memory.

### ISSUE THREAD

**Issue by taimaiduc** [pwn20wndstuff/Undecimus#1367]
**Describe the bug**
Unable to find kernel's credentials in kernel memory for XS MAX 

**Screenshots**
![image](https://user-images.githubusercontent.com/10907980/63636577-5a604580-c69b-11e9-9795-cc8b9c2b656f.png)

![image](https://user-images.githubusercontent.com/10907980/63633536-3f2e0f80-c674-11e9-8d52-5e061c4a00c8.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: XS MAX
 - unc0ver Version: 3.5.5

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Tijnderivecourt** [comment]
Try installing the application with computer instead of signing service
