### ISSUE TITLE
Unc0ver RESTART and Restart Springboard buttons not working

### ISSUE THREAD

**Issue by larrybml** [pwn20wndstuff/Undecimus#1370]
Since IOS 12.4 Jailbreak , new changes to unc0ver doesn't allow anymore users to restart device or to restart springboard from unc0ver settings page.
At least RESTART button was good to work, sometimes I want to restart device without using buttons and from that menu, restart was quick to do. 

**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'settings'
3. Scroll down to 'Restart', witch now is grayed out
4. See error : it shows credits instead of restarting device

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device:  iPhone X
 - unc0ver Version: 3.5.x 

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by IMS212** [comment]
Probably not implemented yet for 12.4, since the branch is private
