### ISSUE TITLE
on "It was working for me for the past 3 days but about 30 minutes ago it stopped working. All the tweaks were gone and I couldn’t open Cydia anymore."

### ISSUE THREAD

**Issue by mrfrijol420** [pwn20wndstuff/Undecimus#1371]
12.4 I can’t uninstall cydia either

**Comment by mrfrijol420** [comment]
Any suggestions?

**Comment by DM164** [comment]
I’m having the same problem.

**Comment by gurunanak1122** [comment]
Having the same problem, it’s been working well for about a month and today it wasn’t working. It doesn’t let me download unc0ver from any website/app. I am on iOS 12.1.2

**Comment by thatbrooklynkidyo** [comment]
If you can open uncover app try re-jailbreaking with reinstall Cydia option on.

**Comment by killtheflip** [comment]
I already erase my iPhone content still the same issue. Now I can’t delete Cydia icleanerpro safeshutdown. Very sad! Please help

**Comment by sean11213** [comment]
I am having the same problem was so excited been waiting a year to jailbreak

**Comment by thatbrooklynkidyo** [comment]
Can you get into settings in Unc0ver App?  Is the phone still jailbroken?

**Comment by killtheflip** [comment]
It’s working now!!!

Just delete the old app.
Clear cache
And now my device is JB again!!!
Thanks

**Comment by mrfrijol420** [comment]
Here is how to fix it guys!! 

https://youtu.be/wASd73gSS5c

**Comment by thatbrooklynkidyo** [comment]
Close this
