### ISSUE TITLE
Don’t work on IPhone XR iOS 12.4

### ISSUE THREAD

**Issue by jas1211** [pwn20wndstuff/Undecimus#1379]
**Describe the bug**
Don’t work on IPhone XR iOS 12.4

**To Reproduce**
1. After jailbreak, not found cydia 
2. Set prop Refresh icon cache
3. Jailbreakinsg

**Screenshots**
![7CB83C4D-A4EF-43FD-9D30-D8D3D84FD993](https://user-images.githubusercontent.com/7644240/63646120-9987a880-c726-11e9-8ef3-664a662ec7a2.png)
![Uploading 6E9DAEC5-3D7E-4C2A-A30E-264F31908D57.png…]()

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: XR
 - unc0ver Version: 3.5.6

**Comment by R4in8ow** [comment]
same error bro . my phone xsmax 12.4

**Comment by gurunanak1122** [comment]
Can someone help me. I am stuck on iOS 12.1.2 and whenever I try to update my device it comes up with an error. This is not letting me get unc0ver

**Comment by andrewlove1** [comment]
🤦🏼‍♂️🤦🏼‍♂️🤦🏼‍♂️ cydia isn't installed on the XS, XS Max, or XR yet

**Comment by DJ-Haegi** [comment]
@Gurunanak1122 First, make a Backup from your iPhone!
Is your iPhone jailbreaked?  if yes, then open Uncover -> Settings Restore Enable RootFS and then click on Restore.  If you do not jailbreak, then update with iTunes.  If that does not work, then try another PC.

Translated by Google Translater

**Comment by bumblebeems** [comment]
You can't install Cydia on a12 devices (iPhone XS/MAX, XR) yet.

**Comment by jas1211** [comment]
@andrewlove1 
Hm... how install tweaks without cydia?

**Comment by andrewlove1** [comment]
@jas1211

You can't yet. You have to wait for Cydia to come out for the XS, XS Max, and XR
