### ISSUE TITLE
Cydia apps will not open. Unc0ver 3.5.6 

### ISSUE THREAD

**Issue by ogkillavortec** [pwn20wndstuff/Undecimus#1381]
I have iPhone 6+ running iOS 12.4. I used unc0ver 3.5.6. Everything worked but none of the app I download will open.

**Comment by madwaloo** [comment]
I have the same problem on an iPad Air running IOS 12.4.

**Comment by ashraf2929** [comment]
I have iPhone 7 on iOS 12.1.4 and my problem is that every time I jailbreak the iPhone restarts.

**Comment by rhld13** [comment]
😪huuh. You guys don’t read anything do you?! Read this: https://www.idownloadblog.com/2011/10/22/untethered-jailbreak-vs-tethered-jailbreak-vs-semitethered-jailbreak/
TLDR; With semi-tethered you have jailbreak every time you turn your phone off

**Comment by ogkillavortec** [comment]
Not my problem. Everything works just none on the games or apps I download will open.
