### ISSUE TITLE
Unsupported 12.3.1 Iphone 7

### ISSUE THREAD

**Issue by Retronize** [pwn20wndstuff/Undecimus#1383]
**Describe the bug**
It appears as unsupported

**Comment by sapman1208** [comment]
12.3.1 isn’t supported 💁🏼‍♂️

**Comment by Yongle-Fu** [comment]
same iPhone6 plus

**Comment by bumblebeems** [comment]
12.3.X is not supported by unc0ver, update to 12.4

**Comment by aidanbh** [comment]
@Retronize do so straight away if you haven't already, 12.4.1 is out which means 12.4 will not be signed much longer. Go https://ipsw.me/#platform, choose your phone, download the IPSW and flash it with iTunes. If you wait until they stop signing you will not be able to install a jailbreakable version any longer.
