### ISSUE TITLE
Latest source code not on GitHub

### ISSUE THREAD

**Issue by WesternIcelander** [pwn20wndstuff/Undecimus#1384]
Your most recent commit is July 13th?

**Comment by bumblebeems** [comment]
unc0ver was made closed source a few months ago

**Comment by WesternIcelander** [comment]
In the Settings pane of the app, there's a button "View Source Code" though?  And it links to this GitHub?  The GitHub ReadMe.md also boasts about how unc0ver is open source.  The latest ReadMe.md should at the very least indicate that unc0ver is no longer open source, and maybe remove the View Source Code button in the Settings pane.

**Comment by bumblebeems** [comment]
It hasn't been updated. Pwn made a reddit post about his decision to make u0 closed source a while back though

**Comment by saagarjha** [comment]
Perhaps it should stop purporting to be open source [in the README](https://github.com/pwn20wndstuff/Undecimus#source-code) of this project?

**Comment by palxex** [comment]
@mudkipscience Could you point me the url? Failed in searching.
Just found a post: https://www.reddit.com/r/jailbreak/comments/c7ggma/discussion_my_thoughts_about_open_source/
If I understand correctly, pwn20wnd says will release source of jailbreaks after a period of time, mostly denying rebranding.

**Comment by Siggi88** [comment]
Delayed open source sounds fair enough.  Wouldn't want Coolstar to rebrand this 🤣

**Comment by lucifer662607004** [comment]
try "git checkout v3.5.6"?

**Comment by lucifer662607004** [comment]
according to git log the code should be new:

Author: Pwn20wnd <39620323+pwn20wndstuff@users.noreply.github.com>
Date:   Fri Jul 12 22:49:59 2019 +0300

    Update README.md

**Comment by WesternIcelander** [comment]
@zj299792458 That's not the latest, that's a few months ago.  That commit has been tagged v3.5.6, v3.5.5, v3.5.4, v3.5.3, etc. all the way to v3.3.0 but it's all on the same commit.

**Comment by palxex** [comment]
Those tag are just created for placing binary...

**Comment by lucifer662607004** [comment]
> @zj299792458 That's not the latest, that's a few months ago. That commit has been tagged v3.5.6, v3.5.5, v3.5.4, v3.5.3, etc. all the way to v3.3.0 but it's all on the same commit.

well, that's bad 😥
