### ISSUE TITLE
Uncover 3.5.6 can't jailbreak cydia error

### ISSUE THREAD

**Issue by zizyza** [pwn20wndstuff/Undecimus#1385]
I updated my iPhone from 11.2.6, was jailbroken with electra. Now updated to 12.4,  I tried to jailbreak with uncover 3.5.6 from Ios Ninga app And Tweekbox but it gives me error every time.

**Screenshots**
![1FF4D49D-BF8C-49FF-9BDC-9569C32FAFA5](https://user-images.githubusercontent.com/54527968/63674414-301f9c80-c7ef-11e9-87cd-d8557faa5261.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6s plus
 - unc0ver Version: 3.5.6

 - [x ] this issue is present on the latest version of unc0ver

**Comment by jgonzis** [comment]
Have you trust unc0ver app?

**Comment by blaw2906** [comment]
yeah i'm having trouble with just downloading the app in general i had already jailbreak my phone and when i restated it i couldn't re jailbreak so i deleted the app and now its not even downloading
