### ISSUE TITLE
3.5.6 ip gets dedteced as Virus  OSX.Trojan.Gen

### ISSUE THREAD

**Issue by SeaJae** [pwn20wndstuff/Undecimus#1386]
I know Trojan.Gen isn't really a virus.  But I thought I would mention the signatures are now reporting this.

**Comment by malakaldayook** [comment]
Bitdefender triggers on all versions that I scanned (3.4-3.5) claiming Trojan.MAC.Generic.XXXX. Unzipped the .ipa and Bitdefender identified the Undecimus.app/Undecimus binary as the culprit. Run it in a sandbox I suppose to see if anything explodes.

// M
