### ISSUE TITLE
Unable to repair system

### ISSUE THREAD

**Issue by kid1carus** [pwn20wndstuff/Undecimus#1388]
**Describe the bug**
Unable to repair system. 
 runCommandv(593): E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
[*] runCommandv(593) completed with exit status 100
[*] Unable to repair system

**To Reproduce**
Steps to reproduce the behavior
Rerun the Jailbreak
Same error

![D959FAD3-30B6-4673-A063-8B3457A08C91](https://user-images.githubusercontent.com/45052773/63721528-70970e80-c81f-11e9-97ef-9ed3a1520825.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device:  iPhone 6s
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/1e0jQV1A

**Comment by Victimized90** [comment]
This happened to me too out of nowhere and the only way I could ever jailbreak again was to RestoreFS, which completely deleted all of my tweaks and sources so I had to download and configure them all from scratch again.

**Comment by mendel3** [comment]
This happened to me, and unline @Victimized90 I didn't need to restore RootFS. You must either SSH into your phone or after the Unable to repair system popup shows up, if you have Filza open it and navigate to /usr/bin and open/execute the file named bash. Login with your root account password (default is alpine) and run dpkg --configure -a like the log is telling you to.

**Comment by kid1carus** [comment]
You dont even need to do all of that.  The main culprit is the update (v1.0) of Xen HTML.  After the error occurs tap the "View Log" button to be able to back out of unc0ver without having to restart your device and simply open cydia and then uninstall/downgrade Xen HTML or uninstall whatever tweak unc0ver says is causing the jailbreak error and then respring.  Run unc0ver agian after your device restarts and it should complete successfully.

**Comment by teezyapps** [comment]
As the log says, run the dpkg command 🧐 (‘dpkg —configure -a’ ..no quotes) in terminal (as root). If you aren’t able to launch terminal (or ssh from outside), try jailbreaking again with most options toggled off (particularly load tweaks and/or reload demons).

Had a similar experience with one of my devices on 12.4 uncover when jailbreaking - manually carrying out the command took care of it nice and easy :)

**Comment by linux3ronga** [comment]
Dpkg —configure -a it is that the program found debs or tweaks that weren’t configured correctly i use Linux and i needed to tan that command because an error in an update

**Comment by res1492** [comment]
> This happened to me, and unline @Victimized90 I didn't need to restore RootFS. You must either SSH into your phone or after the Unable to repair system popup shows up, if you have Filza open it and navigate to /usr/bin and open/execute the file named bash. Login with your root account password (default is alpine) and run dpkg --configure -a like the log is telling you to.

Thank you for that...worked like a charm
