### ISSUE TITLE
Iphone XS-Max 12.4 ssh issue

### ISSUE THREAD

**Issue by WayneBishop1** [pwn20wndstuff/Undecimus#1389]
**Describe the bug**
ssh is not working on 12.4 using uncover 3.5.6 in xs-max
It was working on 12.4 using uncover 3.5.5

**Device (please complete the following information):**
 - iOS Version: 12.4 
 - iOS Device: XS-Max
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce (possible)
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by mcarigs** [comment]
I can confirm that SSH is working on my XS Max running 12.4 using Uncover 3.5.6
![SSH](https://user-images.githubusercontent.com/17626930/63731567-46087e00-c83e-11e9-8f64-95f8eb745fee.PNG)
![IMG_1222](https://user-images.githubusercontent.com/17626930/63731665-ac8d9c00-c83e-11e9-9141-100da26a6884.jpg)

**Comment by WayneBishop1** [comment]
Strange ?
Version 3.5.6 dont' work for me yet version 3.5.5 does?
I have not changed anything at all.

ok so after a lot of messing around i can use putty to ssh into the iphone xs-max however i use winscp which gives me errors of bash not found and ls not a command?

@mcarigs 
What program do you use to ssh?
Is it a graphical one or command-line one?

**Comment by mcarigs** [comment]
I'm using the built-in SSH command in PowerShell. You may need to re-jailbreak and just be sure that 'Install Open-SSH' is toggled on in the Uncover settings panel

**Comment by WayneBishop1** [comment]
I have restored rootfs in uncover then re-jailbroke it and had "install open ssh" as well as "ssh" only and still i can only access the ssh by using putty?

**Comment by mcarigs** [comment]
It sounds to me like WinSCP is not actually connecting to your iPhone which is why you're getting errors of those commands not being found. I haven't used WinSCP so I'm not sure exactly what could be wrong there. Since you are able to SSH using putty, that is a good sign at least. What OS is your computer running?

**Comment by WayneBishop1** [comment]
Windows 10 eneterprise 64bit.
I also tried on Windows 7 Pro 64bit and it's the same it works on 3.5.5 but not 3.5.6 which lead me to start this bug report as i assumed it was the program?

**Comment by mcarigs** [comment]
Okay I'm on Win 10 Pro 64 bit and it works perfectly using Powershell. Can you try using Powershell and also share any error messages you receive if it does not work?

EDIT: You stated you're using Win 10 Enterprise. Is this machine also connected to a corporate network by any chance? When I try using SSH on my company's network, it's blocked by our firewall rules. So that could be a factor.

**Comment by WayneBishop1** [comment]
No it's not connected to a company network.
As i stated earlier it works on 3.5.5 but not 3.5.6 so how would the firewall be a issue anyway?
I will try poweshell and report back.
Thanks for the help so far.

Edit:
So i can still use putty and powershell they both work.
What i am really after is a drag and drop gui for the ssh that works with putty or powershell so i can copy folders and multiple files at once to the ios.

**Comment by mcarigs** [comment]
Ah I see. There is [a way](https://unix.stackexchange.com/questions/2857/copy-a-file-back-to-local-system-with-ssh) to copy files FROM the device you are connected to via SSH, but if you want to transfer files to the device, you'll need to do that over FTP/SFTP.

**Comment by WayneBishop1** [comment]
Ok thanks for the link and help.
It just baffles me on why it works on 3.5.5 but not 3.5.6 when i have not changed anything at all.
