### ISSUE TITLE
12.1.3 - iPhone XS Max - Stops at 2/31 then Reboots

### ISSUE THREAD

**Issue by 300-michael** [pwn20wndstuff/Undecimus#1390]
**Describe the bug**
iPhone XS Max 12.1.3 256GB will reboot without Jailbreak on any current version of Unc0ver at step 2/31. Have tried to turn off Siri, airplane etc. etc. with the same issue...

**To Reproduce**
1. Open Unc0ver app - !jailbreak (w/ all options disabled or enabled makes no difference).
2. Step 1/31 works, proceeds to step 2/31
3. 2/31 seems to hang, then will reboot the iPhone.

**Screenshots**
Unable to provide screenshots while iPhone is rebooting `.'

**Device (please complete the following information):**
 - iOS Version: 12.1.3
 - iOS Device: iPhone XS Max (11,6)
 - unc0ver Version: 3.5.4, 3.5.5, 3.5.6 (tried each with same error)

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by wanderingbox** [comment]
Same issue here, appears to be an A12 problem, happens on my xs max 2/32 selected offsets 12.1.4

**Comment by Mikaovich** [comment]
Yes, same issue.  12.1.4, iPad Pro 3rd Gen A12X.

Edit: Updated to ios 12.4 before the signing window closed, and this issue no longer exists.
