### ISSUE TITLE
12.4 IPhone xR Jailbreak says installed but no Cydia.

### ISSUE THREAD

**Issue by DRimmele** [pwn20wndstuff/Undecimus#1392]
I downloaded the newest version of the unv0ver jailbreak 3.5.6 and got through every step of the jailbreak until my phone rebooted with no cydia. I know that it installed the jailbreak because when I re-opened unc0ver I had the re-jailbreak option. Anyone know if there is a fix for this? (Sorry I dont have a picture I'm on a school computer lmao.)

**Comment by jordanthren** [comment]
Cydia has not be implemented for A12 devices yet.

**Comment by CARLO5ONIC** [comment]
Is there an eta? Or what do I do to revive updates?

**Comment by jordanthren** [comment]
Turn on notifications for pwn20wnd’s tweets.

**Comment by StarXcs** [comment]
A12 and A12X should be coming very soon then Cydia will work with tweaks etc.
