### ISSUE TITLE
DPKG not found a12 12.2

### ISSUE THREAD

**Issue by ArthurXHD** [pwn20wndstuff/Undecimus#1393]
![C637BAEA-EC5B-49C9-9736-B9D9A511DDB7](https://user-images.githubusercontent.com/54597772/63797809-a559a300-c8bd-11e9-80d6-68f4a92a2989.png)

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPad Pro 12.9
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by IMS212** [comment]
Pretty sure dpkg isn’t installed on a12, this is not a bug afaik

**Comment by ArthurXHD** [comment]
DPKG installed filza deb perfectly using an automated script.

**Comment by ArthurXHD** [comment]
Download and open script you can see it using dpkg and wget
https://www.reddit.com/r/jailbreak/comments/b5s2a6/tip_filza_app_manager_on_a12_x/

![28138785-5998-4ED8-AC25-0E710BD551DC](https://user-images.githubusercontent.com/54597772/63813927-f2507000-c8e3-11e9-86fc-2741a39fb396.png)

**Comment by liaobinbin** [comment]
@ArthurXHD This script used DPKG  command, if your device isn't installed DPKG, so this script will be not work

**Comment by ArthurXHD** [comment]
@liaobinbin the script worked perfectly fine as you can see below
![117882E8-4CD4-46A9-AA17-9F3B3CABDEDB](https://user-images.githubusercontent.com/54597772/63876931-61c56e80-c97b-11e9-96ab-2376d038e3f4.jpeg)
