### ISSUE TITLE
ECID in preferences in Unc0ver app is invalid

### ISSUE THREAD

**Issue by nutterthanos** [pwn20wndstuff/Undecimus#1394]
**Describe the bug**
grabbed the ECID in Unc0ver preferences

**To Reproduce**
1. Go to 'Unc0ver Preferences”
2. Click on 'ECID”
3. Click yes to copy
4. Go to tsssaver.1conan.com in Safari
5. Type in all info in with copyed ECID
6. Click Submit

**Screenshots**
![1CEA06CF-5814-416B-BAC5-63C10A4AC62F](https://user-images.githubusercontent.com/50470661/63811350-616ea880-c966-11e9-80fb-bc1672418b43.jpeg)
![77EE0DAD-D9FD-47A9-8A06-7BD6DEDE90BE](https://user-images.githubusercontent.com/50470661/63811351-62073f00-c966-11e9-9a52-f0a43aced966.jpeg)
![3AA682B1-887C-4BBE-9BF0-6270B05A4120](https://user-images.githubusercontent.com/50470661/63811352-62073f00-c966-11e9-94f3-19eba536da0b.jpeg)
![AE3F0810-9D0E-44E3-94F2-25724A6BB2A5](https://user-images.githubusercontent.com/50470661/63811353-629fd580-c966-11e9-8114-057de5b31a98.jpeg)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone SE
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ArthurXHD** [comment]
Delete 0x Correct ECID you need to take some extra steps on iOS 12 to save blobs 
https://www.reddit.com/r/jailbreak/comments/apjwhy/tutorial_new_tutorial_for_saving_shsh2_blobs_on/

**Comment by nutterthanos** [comment]
whats the 0x for then?

**Comment by nutterthanos** [comment]
Also not a bug since you said just remove the 0x and follow the new tutorial but thats for a12.
