### ISSUE TITLE
3.5.6 latest uncover with XS MAX no cydia?

### ISSUE THREAD

**Issue by Royal-Marine-42** [pwn20wndstuff/Undecimus#1399]
Anyone have any idea why cydia won’t install on my device. I have a XS Max 12.4 running 3.5.6 latest uncover. Has no JB issues what so ever instals fine but cydia isn’t in my phone 

Regards

**Comment by danno04** [comment]
no injection for a12 🤦‍♂️

**Comment by Royal-Marine-42** [comment]
Oh what does that mean? Sorry I’m a JB noob, what is the point of uncover if you have no cydia in this device then? Is there another way to add other things?

**Comment by danno04** [comment]
Have to wait until A12 chipset devices are fully supported until you can get cydia and start using tweaks, should be about a month bur thats just a guess

**Comment by Michael-Stokoe** [comment]
To answer your question @Royal-Marine-42, installing unc0ver 3.5.6 and running the jailbreak tool will disable auto updates and allow you to gain SSH so you can change root passwords.

**Comment by HonoringBills** [comment]
Add on to the dummy question @Stoekoe0990 since you seem pretty knowledgeable, what exactly does changing the root passwords do for the user?

**Comment by Michael-Stokoe** [comment]
@HonoringBills If you jailbreak your iPhone to disable auto-updates, you're going to want to change the root account's password from the default of 'alpine' as you may have enabled SSH during the jailbreaking process.

If you don't change the root password on an SSH-enabled jailbroken phone, you will be allowing other users to SSH into your device and deploy malicious code. Be it on public wi-fi or any kind of shared network.

**Comment by sooxt98** [comment]
So how to install cydia thru this jailbroken device with ssh?

**Comment by sooxt98** [comment]
![image](https://user-images.githubusercontent.com/13378059/64225771-78397000-cf0f-11e9-9c1b-12564c3f4e60.png)

what should i do?

**Comment by Michael-Stokoe** [comment]
You can't because tweak injection isn't supported yet.
