### ISSUE TITLE
Infinite Respring Loop have started haunting again.

### ISSUE THREAD

**Issue by soum91** [pwn20wndstuff/Undecimus#1400]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Install Safari Plus or Flex 3 beta 63(I guess) on iPhone 6+ iOS 12.4
2. Jailbreak with RSD
3. Boom! You have that infinite Respring loop.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6+
 - unc0ver Version: 3.5.2 and up

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Victimized90** [comment]
Yup, I have the same problem though I'm not sure what tweak actually caused it. But I've now been in an infinate respring loop for the past two hours..

**Comment by soum91** [comment]
@Victimized90, do you have Flex or Safari Plus installed? Those 2 causes loops. If you’re unable to jb for this, turn off the RSD and jb. It will stop the loop and complete the jb.
