### ISSUE TITLE
Unc0ver - Broken since 3.5.0 - Moved to Chimera, works great.  iPhone 6 12.4.

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1404]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ghost** [comment]
1 in 20 fails to jailbreak, could not SSH, moved to Chimera all working with no issue.

**Comment by Michael-Stokoe** [comment]
Please fill in the form in the opening post so the devs have a bit more information than:

> "Hurrrr, it doesn't work".

iOS device? Version? Prntscrn of the failure message etc.

Just something that can help the developers to fix the issue you encountered so that others in future won't run into the same issue you did.

**Comment by ghost** [comment]
Hurrrr, well its doesn't, so many thinks wrong now, every time I tried to JB I got a different error and then it restarted, then after all that it would not allow restore of rootfs.  Luckily I had taken a backup before JB.  Install Chimera, 1st time no issue.  So sorry Unc0ver is no more.
