### ISSUE TITLE
Unc0ver 3.5.6 not opening on iOS 11.4.1

### ISSUE THREAD

**Issue by Em3rg3ncy** [pwn20wndstuff/Undecimus#1406]
Okay, I can't launch Unc0ver at all, it just crashes at startup
https://youtu.be/v9O1oZEWKy0

When I try to launch the Unc0ver app, it just crashes.

 - iOS Version: 11.4.1
 - iOS Device: iPad Air 2
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

I tried to re-installed via Cydia Impactor. Use older version like 3.5.5. None of them worked

**Comment by OlEurolO** [comment]
I'm having the same problem
iPhone 6s Plus on iOS 1.12.2
unc0ver version 3.5.6

**Comment by TennyJP** [comment]
Same issue.
iPhone 8 Plus - iOS 11.1.2

**Comment by chacher86** [comment]
Same issue.
iPhone 8 Plus - iOS 12.4

**Comment by 502647092** [comment]
Same issue.
iPhone 6s Plus - iOS 12.4

**Comment by kuretru** [comment]
Same issue.
iPhone SE - iOS 12.4

**Comment by delro92** [comment]
Same on iPhone 7, iOS 12.4

**Comment by EnekoT2001** [comment]
Same on iPad Mini 2 - iOS 12.4
This exact same version was working but after reinstalling it (bc it expired) it wont open, i tried deleting the appid and certificate but nothing... Gonna try an older version like 3.5.4 and see if it works

**Comment by Silun** [comment]
Same issue, earlier versions crash as well. Have not yet found a working version.
iPhone SE on iOS 12.4

**Comment by TennyJP** [comment]
> Same on iPad Mini 2 - iOS 12.4
> This exact same version was working but after reinstalling it (bc it expired) it wont open, i tried deleting the appid and certificate but nothing... Gonna try an older version like 3.5.4 and see if it works

Yea i had exact the same problem.
An iPhone reset seem to solve the issue. at least for me..

**Comment by EnekoT2001** [comment]
> > Same on iPad Mini 2 - iOS 12.4
> > This exact same version was working but after reinstalling it (bc it expired) it wont open, i tried deleting the appid and certificate but nothing... Gonna try an older version like 3.5.4 and see if it works
> 
> Yea i had exact the same problem.
> An iPhone reset seem to solve the issue. at least for me..

Reset like reinstalling iOS?
I tried cleaning the RootFS with Chimera to see if it fixes it with no luck. I ended up jailbreaking my iPad with chimera and installing cydia for chimera...

**Comment by TennyJP** [comment]
> > > Same on iPad Mini 2 - iOS 12.4
> > > This exact same version was working but after reinstalling it (bc it expired) it wont open, i tried deleting the appid and certificate but nothing... Gonna try an older version like 3.5.4 and see if it works
> > 
> > 
> > Yea i had exact the same problem.
> > An iPhone reset seem to solve the issue. at least for me..
> 
> Reset like reinstalling iOS?
> I tried cleaning the RootFS with Chimera to see if it fixes it with no luck. I ended up jailbreaking my iPad with chimera and installing cydia for chimera...

Well, i upgraded to iOS Version 12.4 and Installed unc0ver but this didn't worked for me (App Crashes on Launch) so i did a reset in Settings > General > Reset > Erase All Content and Settings.
but i have no idea if this can cause any damage to your iPhone.. i did this once with Electra and almost Bricked my iPhone. Create a Backup before proceeding.

**Comment by kuretru** [comment]
* This problem seems to have nothing to do with Unc0ver.  
* There are some problem with Apple's certificate server. Therefore Cydia Impactor and Reprovision can't sign Unc0ver successful.
* Use enterprise root certificate can solve this.

I download Unc0ver from https://app.ignition.fun/ (in Jailbreaks -> Unc0ver(Official)) and it is working.  Unc0ver no longer crashes and Jailbreaks success.

iPhone SE 12.4
Unc0ver 3.5.6

**Comment by Em3rg3ncy** [comment]
> * This problem seems to have nothing to do with Unc0ver.
> * There are some problem with Apple's certificate server. Therefore Cydia Impactor and Reprovision can't sign Unc0ver successful.
> * Use enterprise root certificate can solve this.
> 
> I download Unc0ver from https://app.ignition.fun/ (in Jailbreaks -> Unc0ver(Official)) and it is working. Unc0ver no longer crashes and Jailbreaks success.
> 
> iPhone SE 12.4
> Unc0ver 3.5.6

Hello, first of all.
Your solution fixed the problem perfectly for me! Thank you very much!
But at this moment I'm worried that do I have to resign the app after 7 days? 
Even though I downloaded it directly from the Safari browser?

**Comment by EnekoT2001** [comment]
> * This problem seems to have nothing to do with Unc0ver.
> * There are some problem with Apple's certificate server. Therefore Cydia Impactor and Reprovision can't sign Unc0ver successful.
> * Use enterprise root certificate can solve this.
> 
> I download Unc0ver from https://app.ignition.fun/ (in Jailbreaks -> Unc0ver(Official)) and it is working. Unc0ver no longer crashes and Jailbreaks success.
> 
> iPhone SE 12.4
> Unc0ver 3.5.6

OMG TYSM. IT WORKED FOR ME :D

**Comment by leandroprz** [comment]
I'm experiencing the same issue on a 6s @ 12.4.

**Comment by Pirriu** [comment]
>     * This problem seems to have nothing to do with Unc0ver.
> 
>     * There are some problem with Apple's certificate server. Therefore Cydia Impactor and Reprovision can't sign Unc0ver successful.
> 
>     * Use enterprise root certificate can solve this.
> 
> 
> I download Unc0ver from https://app.ignition.fun/ (in Jailbreaks -> Unc0ver(Official)) and it is working. Unc0ver no longer crashes and Jailbreaks success.
> 
> iPhone SE 12.4
> Unc0ver 3.5.6

Same iPhone and version, Same issue.
app.ignition apps install but stays greyed out.

**Comment by vbtiger** [comment]
> > ```
> > * This problem seems to have nothing to do with Unc0ver.
> > 
> > * There are some problem with Apple's certificate server. Therefore Cydia Impactor and Reprovision can't sign Unc0ver successful.
> > 
> > * Use enterprise root certificate can solve this.
> > ```
> > 
> > 
> > I download Unc0ver from https://app.ignition.fun/ (in Jailbreaks -> Unc0ver(Official)) and it is working. Unc0ver no longer crashes and Jailbreaks success.
> > iPhone SE 12.4
> > Unc0ver 3.5.6
> 
> Same iPhone and version, Same issue.
> app.ignition apps install but stays greyed out.

Same here.
iPhone SE on 12.4
Unc0ver 3.5.6 or 3.5.2

What I've tried and failed: (between every step there was a hard reset holding down home+sleep)
- installing 3.5.6 using jailbreaks.fun -> stays greyed out
- installing 3.5.6 using app.ignition.fun -> stays greyed out
- installing 3.5.6 using cydia impactor 0.9.52 and my own apple id (basic apple id, not a dev) -> instant crash
- installing 3.5.2 using cydia impactor 0.9.52 and my own apple id -> instant crash
- in cydia impactor [Xcode]->[Delete App ID] then [Xcode]->[Revoke Certificates], after these two succeeded, I tried once installing 3.5.6 again -> instant crash
The crash looks the same as OP youtube video (https://youtu.be/v9O1oZEWKy0)

What I did however: in cydia impactor I had opened [Device]->[Watch Log...] and saved the output of the crash.
Here it is:
[unc0ver crash log.txt](https://github.com/pwn20wndstuff/Undecimus/files/3568722/unc0ver.crash.log.txt)

**Comment by OlEurolO** [comment]
Apple is unsigning ignition apps but they're currently re-signing them so you'll have to wait a bit

**Comment by romestylez** [comment]
Same here. Im using newest unc0ver and also tried older versions. Tried two different Apple IDs (revoked all Apps/Certs). Also tried ignition etc but its always greyed out and not finishing installation.
