### ISSUE TITLE
iPhone5s      unc0verb        Display is not supported

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1408]
I don't support it after installing the software. Please confirm if it is a bug.Operating system version 12.3，
Unc0verb version 3.5.5。

![image](https://user-images.githubusercontent.com/43258262/63937780-cecd2700-ca95-11e9-9b9c-32793a651666.png)

**Comment by DJ-Haegi** [comment]
12.3 - 12.3.2 is Not supported. You Must Update on iOS 12.4 via iTunes NOT 12.4.1! Make it fast. Apple will Close this
