### ISSUE TITLE
Uncover app reinstall failed

### ISSUE THREAD

**Issue by michal-i** [pwn20wndstuff/Undecimus#1409]
Hi guys, i have some issue with app installig now. After first installation and providing jailbreak everything worked. Then appeared message from Uncover App about license revoke. After this i was not able to revoke license again nor run app. I deleted uncover app but now i am not possible to install it again. After download the app still shows grey icon. Cydia is nor working too for now.

I ve tried multiple resets of iphone, and it not help.

Thanks for advices

**Screenshots**
![DDF6E2E9-CC62-4DD7-80FE-BDD4077FA9F5](https://user-images.githubusercontent.com/54693054/63986016-605a8a00-cad2-11e9-8e56-e88dee67622d.jpeg)
![D24F9687-759F-4203-9B4C-453C27919FCA](https://user-images.githubusercontent.com/54693054/63986017-605a8a00-cad2-11e9-96bf-c9c61677c11d.jpeg)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone SE
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by allashfs** [comment]
And my phone rekove license ı can’t open unc0ver, not working cydia what i need to to pls help me

**Comment by SHlSHlO** [comment]
I have the same issue with my iPhone 8 iOS 12.4 and I'm getting this error in Cydia Impactor 'file installation.cpp line 42' I tried to install it on jailbreak.fun and FilzaEscaped 12.4 but it also gets a grey icon.

**Comment by leandroprz** [comment]
I'm experiencing the same issue.

**Comment by theonlymbo** [comment]
Facing the same issue since yesterday. iPhone X/12.4. 
Phone rebooted itself. Unc0ver unable to open & upon reinstalling it, nothing shows up on profiles to trust/verify

**Comment by smilesdavis8d** [comment]
Same issue. App stays greyed out. 
iPhone SE iOS 12.4. 

Update: I installed via the GitHub link and Cydia impactor and it worked. 
All I did was uninstall the greyed out app and signed the github version myself.

**Comment by JCalandre** [comment]
iPhone SE, iOS 12.4, unc0ver version 3.5.5
What i tried :
- remove the profile
- delete the app
- reboot
- restore phone with old backup
Nothing worked, the app stay greyed out

**Comment by liljean6** [comment]
Facing the same issue, iPhone 6 ios 12.4

**Comment by theonlymbo** [comment]
Here’s a fix worked for me. 
iPhone X,12.4 

Download Chimera, install profile. 
Restore RootFS (if it works) otherwise jailbreak with Chimera and let Silo replace Cydia. 
Reinstall tweaks. 
(After a couple days, my Chimera stopped working again). Then I installed Unc0ver; rejailbroke. And then removed the whole thing cause I don’t get why the issues persisted.

**Comment by blaw2906** [comment]
yeah i'm having trouble with just downloading the app in general i had already jailbreak my phone and when i restated it i couldn't re jailbreak so i deleted the app and now its not even downloading

**Comment by asdlover** [comment]
Very easy solution:
- download unc0ver v3.6.1 from github (most stable in my opinion)
- install it with impactor (I did it with a free developer b the most stable one I think.
Had the same issue as you, but the app installed seamless, and jailbreak too.

**Comment by ShYmaNo16Hz** [comment]
on windows, impactor is showing an error about xcode 7.3

**Comment by benhacka** [comment]
> on windows, impactor is showing an error about xcode 7.3

Yeah, we were catch by apple and now we can only waiting for Saurik’s update for impactor.

**Comment by sFritsch09** [comment]
Problem solved with 3uTools!!! (on Windows only)

Just follow the guide here: https://www.techacrobat.com/fix-ios-unc0ver-apps-revoked-problem/

**Comment by jriizzyy** [comment]
> Problem solved with 3uTools!!! (on Windows only)
> 
> Just follow the guide here: https://www.techacrobat.com/fix-ios-unc0ver-apps-revoked-problem/

THIS WORKS! Only option I have found to be successful at the moment. Thank you.

**Comment by benhacka** [comment]
> Problem solved with 3uTools!!! (on Windows only)
> 
> Just follow the guide here: https://www.techacrobat.com/fix-ios-unc0ver-apps-revoked-problem/

This didn't work for me unfortunately. Failed when installing unc0ver.

![screen](https://user-images.githubusercontent.com/54145505/69754200-65c58000-1166-11ea-982c-ce928a387001.jpg)


UPD:
Ooh damn. I forgot to **_turn off passlock_**. Yeap, it really works. Many thanks for the help.

**Comment by ankyoo7** [comment]
3utools worked for me too. Thanks

**Comment by robi750** [comment]
same issue(unable to install unc0ver or any apps with No computer method), and on top of that iphone is not detected in any windows laptops, i tried 2 windows laptop(win 7 and win 10 with itunes instaled),  virtual box in mac with win 10 installed(usb pointing to virtualbox) nothing is working.. any mac sollution for installing uncover please tell me

**Comment by sFritsch09** [comment]
There is a new method:
1. Download Altstore for Mac
2. Start altstore server what you just downloaded
3. start the mail app on mac (required for installing apps)
4. Install altstore on your iphone
5. Download uncover on your iphone
6. Open uncover in the altstore app on your iphone
There you have it🤙🏼

**Comment by robi750** [comment]
> There is a new method:
> 
> 1. Download Altstore for Mac
> 2. Start altstore server what you just downloaded
> 3. start the mail app on mac (required for installing apps)
> 4. Install altstore on your iphone
> 5. Download uncover on your iphone
> 6. Open uncover in the altstore app on your iphone
>    There you have it🤙🏼

Thank you for reply, 
When i try installing alt store it gives me error 
And i tried with different apple id and it just kills the altstore from background. 
I will try few more time
