### ISSUE TITLE
unable to install deb for dpkg ios 12.4

### ISSUE THREAD

**Issue by Binahmad97** [pwn20wndstuff/Undecimus#1411]
**Describe the bug**
When I tried to jailbreak my device it stopped at 22/31 and said unable to install deb for dpkg.
**Screenshots**
![7B797E59-6862-47CF-A45D-DE371EFB2331](https://user-images.githubusercontent.com/52802742/63990736-34e99680-caf6-11e9-946e-adc16414a7c8.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone X
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by kid1carus** [comment]
Having the same problem. Here is my [log file](https://pastebin.com/PYSZYsgU).
Anyone have a solution/fix for this?

![8CA1C8A6-29E9-4C28-8F91-66F6F9AE13FD](https://user-images.githubusercontent.com/45052773/64897426-619ec180-d651-11e9-9f7e-2805ac8f0eda.png)

**Comment by klubber** [comment]
Please. I me too! "Error 21/30 enable to install deb for dpkg" Iphone SE IOS 12.4.0 Unc0ver 3.6.3

**Comment by realleyriley** [comment]
I had this error on an iPhone 6 iOS 12.4 trying to install unc0ver 3.7.0.b3. 
To fix it restore the root file system.
1. Open unc0ver app
2. Open settings (top right)
3. enable "Restore RootFS
4. Press "Done" and run it. 

Once your device restarts, go back into the app and jailbreak like normal (disable the rootFS toggle).

**Comment by jr0driguezv** [comment]
@rptallman Still doing RootFS, when I try to perform the Jailbreak again, I get the same error.

**Comment by cerebral-314** [comment]
try different versions of unc0ver.

**Comment by realleyriley** [comment]
> @rptallman Still doing RootFS, when I try to perform the Jailbreak again, I get the same error.

Did the RootFS run successfully?

**Comment by jr0driguezv** [comment]
@rptallman  If it finished correctly, but it didn't work.
I could already make it work, I did the RootFs and Rejailbreak 5 times and at the same time it worked I don't know what was the reason for so many attempts, but this solved it, thanks.
