### ISSUE TITLE
iphone8p crash：when i jailbreak again

### ISSUE THREAD

**Issue by zhaoke0513** [pwn20wndstuff/Undecimus#1414]
**Describe the bug**
rejailbreak crash。

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone 8 plus
 - unc0ver Version:  3.5.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

[crash.zip](https://github.com/pwn20wndstuff/Undecimus/files/3559426/crash.zip)

**Comment by mumuWorld** [comment]
I also have this situation when I use 3.5.6, and then I change back to 3.5.5, there will be the same problem.
我也出现了这种情况当我使用3.5.6，然后我换回3.5.5，还是会有同样的问题。
![0FA87E947BBAFA2A7FC85D0039B25EB0](https://user-images.githubusercontent.com/19208505/64057299-beb86300-cbcd-11e9-9cfa-43d5c3058a5b.jpg)
