### ISSUE TITLE
Random reboots, iPhone 6s on 12.4

### ISSUE THREAD

**Issue by Bitrik** [pwn20wndstuff/Undecimus#1416]
I cannot obtain a log, but I have a minimal amount of tweaks installed, and I get random restarts. My friend has a 7+, and his jailbreak runs smoothly, I am starting to think this is an issue with older phones. Also running unc0ver v3.5.5

**Comment by Clem-** [comment]
Same issue on iPhone 6+
After the last reboot, unc0ver won’t launch.

**Comment by Bitrik** [comment]
> Same issue on iPhone 6+
> After the last reboot, unc0ver won’t launch.

I do not have an issue with the unc0ver app itself, but I do get random restarts. Do you have snapchat installed?

**Comment by Clem-** [comment]
I don’t.

**Comment by Bitrik** [comment]
> I don’t.
> […](#)
> Le 31 août 2019 à 18:09, Will ***@***.***> a écrit : Same issue on iPhone 6+ After the last reboot, unc0ver won’t launch. I do not have an issue with the unc0ver app itself, but I do get random restarts. Do you have snapchat installed? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Okay, I use Snapchat and I believe it may be the issue

**Comment by antonioag95** [comment]
Same issue on iPhone 6s with iOS 12.4. I have like 4 tweaks installed and no Snapchat.

**Comment by Bitrik** [comment]
> Same issue on iPhone 6s with iOS 12.4. I have like 4 tweaks installed and no Snapchat.

Moved to Chimera and all of my issues are gone. I'm starting to think Substrate is just outdated and broken. Either that Pwn doesn't care about users on older devices but I don't want to jump to any conclusions.

**Comment by michaelchany** [comment]
It's not just an older device issue.  On my iPhone 8, unc0ver 3.5.6, on iOS 12.4, and I've had a couple of random reboots.  I'll open an app (the last time it was Settings) and the phone will turn off.  I don't know if there are any logs I could submit.

I tried Chimera twice but both times it threw my phone into a bad boot loop that required hours and finally updating to 12.4 to get resolved.
