### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Yaya48** [pwn20wndstuff/Undecimus#1418]
**Describe the bug**
Another new topic on battery brain

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: IPhone8
 - unc0ver Version: 3.5.6

All my tweaks
![7EC7C10C-4585-4E1C-AFB4-FC107E98B310](https://user-images.githubusercontent.com/34249303/64063139-bd4c6200-cbf0-11e9-8045-19945a797d85.png)

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ghost** [comment]
https://twitter.com/Pwn20wnd/status/1166364402880090112

FWIW, if you were having battery drain or abnormally high CPU usage with partial support for A12–A12X devices on iOS 12.1.3-12.4, I have identified the source of the issue and fixed it for the upcoming release so you don’t need to worry about it.

Long story short, In the next update it will be fixed.

**Comment by Yaya48** [comment]
Okay
