### ISSUE TITLE
Instant crash when open some apps.

### ISSUE THREAD

**Issue by WongIong** [pwn20wndstuff/Undecimus#1420]
**Describe the bug**
Firstly, I found that I can’t open some apps. So that I want to reboot for solving that problem.
But now the uncover app would crash instantly.

**To Reproduce**
I dont know how it happens...
I just remember that i saw the reprovision app crash report suddenly last night.
And before my reboot today, I cant open all apps about jb and also some normal apps.
After the reboot, I cant open the uncover app at all, it just crash crash crash like before but different is it havent jb yet.

**Screenshots**
No shots...

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone7
 - unc0ver Version: 3.5.5

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
No way to get the log...

**Comment by thatbrooklynkidyo** [comment]
Sounds like you lost jailbreak.  Delete unc0ver app and re-install unc0ver then jailbreak again.

**Comment by WongIong** [comment]
That's the problem now, I can't open the uncover app even in non-jb environment. I have tried to delete uncover and install it again but still crash.

**Comment by 1icarus2** [comment]
I am also having this issue now! My JB crashed this morning and now I cannot rejailbreak, even after deleting the app and reinstalling it.

**Comment by thatbrooklynkidyo** [comment]
Have you tried to delete the app and restart your phone and then try to re-jailbreak?

**Comment by 1icarus2** [comment]
I've tried deleting the app, reinstalling it via Cydia Impactor, rebooting my phone, downgrading to a version below 3.5, nothing seems to be working :(

**Comment by WongIong** [comment]
I found out a way to solve this!
Just use another AppleID to sign the uncover app.

**Comment by iVosey** [comment]
Revoke ur apple id with impractor and the apple id should work again

**Comment by 1icarus2** [comment]
I just tried both. Revoking all Apps/Certificates and using another Apple ID hasn't solved my problem.

**Comment by iVosey** [comment]
Have u tried restore roofs and rejailbreaking

**Comment by 1icarus2** [comment]
How do I restore RootFS without the Unc0ver app?

**Comment by iVosey** [comment]
Says ur using 3.5.5 have u tried 3.5.6

**Comment by 1icarus2** [comment]
I've tried 3.5.5, 3.5.6, 3.5.1 and 3.4.2. It seems like Pwn will have to fix this issue, since ReProvision ran into the same problem with his application. https://twitter.com/_Matchstic/status/1168571247564853248

**Comment by iVosey** [comment]
He is on vacation atm he mentioned earlier :/

**Comment by danno04** [comment]
when does he get back

**Comment by iVosey** [comment]
no idea, he obv needs a break from all this to clear his head tbf. lack ov sleep most likely as been hard at it on the u0 ;)

**Comment by thatbrooklynkidyo** [comment]
@iVosey go into Unc0ver settings and flip the switch

**Comment by romestylez** [comment]
I also tried to revoke all Apps/certificated and use another Apple ID at Impactor but its not working. So i guess we are f****d

**Comment by 1icarus2** [comment]
I managed to get mine working again by deleting uncover and installing it via Tweakbox.

**Comment by romestylez** [comment]
> I managed to get mine working again by deleting uncover and installing it via Tweakbox.

I cant instal via tweakbox as its always greyed out seems like its not finishing installation.

**//EDIT:**
Okay now its working using Tweakbox. So it seems to be an error with Cydia Impactor not signing unc0ver correctly guess that will be fixxed in a few days :)

**Comment by badger200** [comment]
Wait there are people who are actually able to sign apps with Cydia Impactor? Without the $99 developer membership? Every time I’ve tried this the past 2 years, it always, always fails with some bullshit error about how my Apple ID doesn’t have network permissions or something.

**Comment by tyrendonard** [comment]
thejd
