### ISSUE TITLE
Random freeze after updating from 3.5.2 to 3.5.5

### ISSUE THREAD

**Issue by heromantf** [pwn20wndstuff/Undecimus#1421]
**Describe the bug**
After updating from 3.5.2 to 3.5.5, I have encountered multiple random freeze in different conditions. These are the conditions that the random freezes occurred, when I click the URL bar in the safari, when I click the copy button after selecting some texts and when I open the iCleaner Pro and Fliza. Also, I found that when I take a screenshot, the progress that save the screenshot to album would take longer than before.

**To Reproduce**
Just random freeze

**Screenshots**
No screenshot.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone X
 - unc0ver Version: 3.5.5

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
No logs even crash logs.

**Comment by marcinmielnik** [comment]
True, got the same on my iphone x/12.4

**Comment by heromantf** [comment]
I went back to 3.5.2 and everything works perfect.
