### ISSUE TITLE
Fast battery drain - uncover (latest)

### ISSUE THREAD

**Issue by olibub** [pwn20wndstuff/Undecimus#1422]
[iPhone 5s, iOS 12.4.]
Issue caused by "backboardd" probably.

I am so angry for this.. my iPhone drain 1-2% off battery under 1 minute.
I tried full factory reset + clean install but not work for me.
I also check battery usage when I saw usually 60% cpu usage by backboardd "not addons installed"

I hope that will be fixed soon

ps. all tutorials which I found on reddit, yt, google and others for this doesnt work.

**Comment by CARLO5ONIC** [comment]
Also huge battery drain and overheat for my iPhone XR A12 running 12.4 and unc0ver 3.5.6

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by m3rtngs** [comment]
>Also huge battery drain and overheat for my iPhone XR A12 running 12.4 and unc0ver 3.5.6 ...

@CARLO5ONIC Pwn20wnd has stated that he knows the reason for the battery drain on A12 12.4 and he has fixed it, so just wait for an update to be pushed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jar01** [comment]
try uncover 3.6.0 or 3.6.1, they fixed battery drain problem for my iphone x, but 3.6.2 and 3.6.3 like old version NOT.
