### ISSUE TITLE
unc0ver 3.5.6 on iPhone 8 @ iOS 12.4 instantly closing

### ISSUE THREAD

**Issue by romestylez** [pwn20wndstuff/Undecimus#1427]
**Device (please complete the following information):**

**iOS Version:** 12.4
**iOS Device:** iPhone 8
**unc0ver Version:** v3.5.6

Today i opend a normal iOS App "Heineken biertegoed" and my iPhone crashed and restarted. I tried to jailbreak again but cant open unc0ver its closing directly. As i wasnt home i tried to download OTA from ignition which wasnt working as it never installed.

Now im at home reinstalled unc0ver but its still closing instantly. I also already tried to uninstall unc0ver and reinstall it no success. I dont know what happend i also restarted the phone after uninstalling unc0ver. Normally im using Reprovision to resign unc0ver so i wondered why its closing but then i thought okay maybe ReProvision failed. But its not working at all anymore just keeps closing instantly.

I also tried the newest Cydia Impactor 0.9.52 but its still not working. Further i have tried unc0ver 3.5.5 - 3.5.3 - 3.5.2 but its also not working.

iPhone 8 @ iOS 12.4

**Comment by thatbrooklynkidyo** [comment]
Have you tried to re-install using tweakbox?

**Comment by romestylez** [comment]
With tweakbox its working. So i guess its a problem with Cydia Impactor and ReProvision not signing the unc0ver App correctly. So lets hope its fixxed fast as i dont want to use stuff like tweakbox or other signing services.

**Comment by michaeljackson99** [comment]
im having the same exact problem

**Comment by romestylez** [comment]
Try to uninstall uncover and the install it via tweakbox.

Someone know if its a problem with Apples self signed certs or a error in cydia impactor or so ?

**Comment by iVosey** [comment]
Try stick ur phone on do not disturb and let me know if its any faster.

**Comment by romestylez** [comment]
Wtf ? DND got nothing to do with signing via Cydia Impactor not working ?

**Comment by umiiii** [comment]
Same problem, solved by using an developer apple id.
