### ISSUE TITLE
My tweaks are not showing up in settings and Cydia menu don’t open up on iPhone 7 IOS 12.4 how can I fix it ?

### ISSUE THREAD

**Issue by mikemike998** [pwn20wndstuff/Undecimus#1429]
My tweaks are not showing up in settings and Cydia menu don’t open up on iPhone 7 IOS 12.4 how can I fix it ?

**Comment by stonexing** [comment]
I tink it's not support iOS12.4 now.
My all iOS device is iOS 12.4(5s,7,x) it show "Unsupported" button after run unc0ver.
My iPad Pro 1gen with 12.3.1 say Unsupported too.

**Comment by mikemike998** [comment]
> I tink it's not support iOS12.4 now.
> My all iOS device is iOS 12.4(5s,7,x) it show "Unsupported" button after run unc0ver.
> My iPad Pro 1gen with 12.3.1 say Unsupported too.

It do support ios 12.4.

**Comment by thatbrooklynkidyo** [comment]
Run I-cleaner.  Also do you have Flame installed?

**Comment by mikemike998** [comment]
I have find out it is a bug  everyone’s is like that. It’s annoying, but I found if you slide your finger to the left while your tapping it helps. Sometimes takes a couple tries.

**Comment by mikemike998** [comment]
Still a issues on the new update .
