### ISSUE TITLE
unc0ver crashing - Solution for iOS 11.0-12.1.2 - iOS 12.4 still not working

### ISSUE THREAD

**Issue by HegeST** [pwn20wndstuff/Undecimus#1430]
I've had an issue on my iPhone 6s iOS 12.1.2 (16C101) and on my iPad Pro 10.5" iOS 12.4 (16G77) that I wasn't able to jailbreak after a crash. I've tried to install 3.5.6 via Impactor, jailbreaks.fun and Ignition as well but none of them worked.

**iOS 12.1.2**
The **solution** for my iPhone was to **downgrade all the way to 3.1.3**, that's the latest version that works.

**iOS 12.4**
I've tried all versions (3.5.0-3.5.6) on my iPad, but **no success**.

**Comment by romestylez** [comment]
Try to uninstall unc0ver and then install it via tweakbox. Its a problem with signing via Cydia Impactor. And it seems like jailbreaks.fun and Ignition are not signed atm because apple revoked the certificates thats the problem why the apps are downloading but greyed out then.

**Comment by HegeST** [comment]
I know that there is a problem with jailbreaks.fun and Ignition, and I don't want to use Tweakbox.

**Comment by romestylez** [comment]
> I know that there is a problem with jailbreaks.fun and Ignition, and I don't want to use Tweakbox.

Okay then you cant use unc0ver. Im using tweakbox for the next few days until Cydia Impactor is fixxed and signing is working again.

**Comment by HegeST** [comment]
I know I could use TweakBox, I just don't trust it.

**Comment by romestylez** [comment]
You could trust them. I have installed uncover via Tweakbox and then just uninstalled Tweakbox. Hopefully self signing via Impactor will work soon.

**Comment by j7evn** [comment]
> You could trust them. I have installed uncover via Tweakbox and then just uninstalled Tweakbox. Hopefully self signing via Impactor will work soon.

Do u can link official page of tweakbox?
Btw is it normal? i cant sideload uncover, but can sideload chimera...
Is it noramal or i need advanced help?

**Comment by HegeST** [comment]
jailbreaks.fun works perfectly now.

**Comment by j7evn** [comment]
Hope Impactor will work soon

**Comment by romestylez** [comment]
Impactor isnt working just tried it again. But you can uninstall unc0ver then go to www.unc0ver.dev and use the OTA method directly via Ignition. Thats working for me :)

**Comment by iVosey** [comment]
think 2factor authintication if u have that on with your apple id will stop impractor installing ipa's

**Comment by romestylez** [comment]
Had this on since you have to activate it because you cant create app specific passwords when 2factor auth isnt activated.

So i dont think thats the problem as Impactor isnt loggin in to your account like you do vis browser.

**Comment by iVosey** [comment]
impractor works for me on least 3 apple id.s i have with no 2fa switched on

**Comment by romestylez** [comment]
Since when you can create app specific passwords with 2FA off ? Thats not working bro. Read this:

To generate and use app-specific passwords, your Apple ID must be protected with two-factor authentication.

Source: https://support.apple.com/en-us/HT204397
