### ISSUE TITLE
Unc0ver 3.5.6 Jailbreak on iPhone 5S 12.1.4 Not working

### ISSUE THREAD

**Issue by Catanic** [pwn20wndstuff/Undecimus#1431]
Phone crashes every time i try to jailbreak on 3.5.6. 
The problem can be solved by installing 3.5.5 since that version jailbreaks without crashing 90% of the time.

 - iOS Version: 12.1.4
 - iOS Device: iPhone 5S
 - unc0ver Version: 3.5.6

 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by nasssr** [comment]
iOS Version: 12.1.4
