### ISSUE TITLE
unc0ver 3.5.6 cannot be opened in iOS 12.4 on iphone 6s / iphone 8

### ISSUE THREAD

**Issue by DerackHJ** [pwn20wndstuff/Undecimus#1433]
**Describe the bug**
unc0ver app will exit/terminate immediately after launch. 
After pressing on the app icon, the background of the UI would show up for less than a second. The app would be closed before any other elements show up.
After the app is closed, double tap home button to the App Switcher view, App Switcher shows the background image of the unc0ver app but with no other UI elements.

unc0ver was installed via the latest cydia impactor. 
No pending iOS update was in the storage.
App was verified in Settings before opened.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6s, iPhone 8
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
No error log showed up during using the cydia impactor or opening up the app.

PS:
iOS 12.4 on iPhone 6s was already JB, 
iOS 12.4 on iPhone 8 was not JB yet.

**Comment by PatrykMis** [comment]
I have this issue too, but with Undecimus v3.5.2 too, especially after upgrading Cydia Installer, mobile substrate and everything in "changes" cydia tab. Now my jailbreak is non-functional...

**Comment by PatrykMis** [comment]
Fixed. You have to install using Tweakbox or even better - www.unc0ver.dev via OTA method (go to this link via your iDevice using Safari).
Alternatively, wait for updated Impactor.
