### ISSUE TITLE
None of the icons in the Cydia main tab work after updating to unc0ver 3.5.x including the latest 3.5.6

### ISSUE THREAD

**Issue by DerackHJ** [pwn20wndstuff/Undecimus#1434]
**Describe the bug**
Before updating to 3.5.x, the main tab of the Cydia app worked just fine. 
After updated to 3.5.x, in the Cydia app, press any button would only "dimmer" the button which indicates the button is pressed, but then nothing would happen. 

For example, pressing on "Manage Account" would turn the icon to a "greyer" color but it would not show the account managing page. 
The same with any other buttons. 

After pressing Reload in the top-right corner, the main tab could be reset.

No error message would show up in the whole process.

**Screenshots**
![IMG_432E5671FA5F-1](https://user-images.githubusercontent.com/16249503/64401424-d00cde00-d0ab-11e9-8a0c-a0a1ee814527.jpeg)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by mikemike998** [comment]
I have find out it is a bug everyone’s is like that. It’s annoying, but I found if you slide your finger to the left while your tapping it helps. Sometimes takes a couple tries.

**Comment by mikemike998** [comment]
Same issues https://github.com/pwn20wndstuff/Undecimus/issues/1429 .

**Comment by res1492** [comment]
Thanks Mikemike998, that works perfectly......just tap loads of time while sliding to the left like you said and volia!!

Actually it seems to work sliding both ways

**Comment by mikemike998** [comment]
You are welcome .
