### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by iganniga22** [pwn20wndstuff/Undecimus#1438]
- iOS Version: 12.4
 - iOS Device: iphone xs max 11,6
 - unc0ver Version 3.5.6

**Comment by badger200** [comment]
You should retitle this to something like “ERROR posix_spawn failed (13) permission denied.” 

A title of “Bug” is totally worthless and is likely to get your issue overlooked.

**Comment by iganniga22** [comment]
hello sorry me for not knowing how to correctly point out the very essence of the errors, thanks for the explanation
