### ISSUE TITLE
My apple pencil turn to be very unfluent

### ISSUE THREAD

**Issue by realjackwang** [pwn20wndstuff/Undecimus#1440]
**Describe the bug**
apple pencil turn to be very unfluent after I jailbreak by the ver. 3.5.2 and so do the 3.5.6, even if I went to the safe mode, the apple pencil still not work well. I mean if you write a little bit fast, then the screen won't follow you.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPad Pro 2nd
 - unc0ver Version: 3.5.2 or 3.5.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by badger200** [comment]
I would start by closely monitoring CocoaTop 64 bit from CokePokes if it’s not in Cydia by default. Sort by CPU usage. In my case I had a ton of old jailbreak crud from iOS 10 tweaks I should have removed before I updated.
