### ISSUE TITLE
There are bugs in the current version that you want to solve

### ISSUE THREAD

**Issue by 3186266** [pwn20wndstuff/Undecimus#1441]
After a long time, some apps will not recognize themselves as apps and hope to be able to solve it.

**Comment by Randomblock1** [comment]
Please word this better. Are you talking about revokes? Apps disappearing? Be more specific.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 3186266** [comment]
After a period of time, the app will not admit that it is an app, prompting the need to download the app, the version before 3.5 did not come out of this situation.

**Comment by Randomblock1** [comment]
Are you talking about revokes? If the app needs to be “verified” then you’re talking about revokes. That isn’t a bug in Unc0ver.

**Comment by 3186266** [comment]
Not revocation, but after jailbreak, the software installed on the mobile phone can not identify itself as the software, which results in the jump to the download page.

**Comment by Michael-Stokoe** [comment]
Please use the proper issue format to report bugs.
