### ISSUE TITLE
When downloading Unc0ver v3.5.6 download never completes> I get a 'Virus detected' message. Plus I've ran this version on my iPhone 6 over 200 tine's and it still won't jailbreak my iPhone   

### ISSUE THREAD

**Issue by Buddha2400** [pwn20wndstuff/Undecimus#1442]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.2.4
 - iOS Device: iPhone 6
 - unc0ver Version: 3.5.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x]this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by DJ-Haegi** [comment]
Please edit your Post and add your device Infos correctly

**Comment by Randomblock1** [comment]
Sounds like this guy is experiencing issues downloading with the desktop browser. If it’s Chrome, go to downloads (press ctrl+j) and click Keep or whatever the option is to NOT delete it. Alternatively, use Ignition to install Unc0ver easier.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Buddha2400** [comment]
@Randomblock1 I’ve done that it still comes up as a virus. I have v3.5.6 installed on my phone, but with this version I can’t re-jailbreak my iPhone. I have been trying over 200 times and still can’t get it with this version. And even if I go down v3.5.5 I still can’t re-jailbreak. If on either version it looks like it’s going to work it will sit in a loop for 15 minutes before the phone reboots it’s self.

**Comment by Randomblock1** [comment]
3.6.0 and above break 4K device support (iPhone 6 and below) so use 3.5.6. If that fails, see if it still happens with all settings disabled. If it does, try RootFS restore. If THAT doesn’t work, well, I don’t know. That version works perfect fine for me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by res1492** [comment]
It's not a bug, I get the same error "Failed - network error", turn off your antivirus for a minute when downloading the file,
 I have to disable avast when downloading but then it works fine.
