### ISSUE TITLE
Can’t jb

### ISSUE THREAD

**Issue by ENDERZOMBI102** [pwn20wndstuff/Undecimus#1443]
**Describe the bug**
Jb with sock puppet 3, when auto-respring, stuck on load.

With sockport instead, the jb cant finish cause a “low power” screen is triggered and the device shutdown. (31% of battery)

**To Reproduce**
1. Jailbreak with sock puppet 3.0
2. here you’re stuck

1. Jailbreak with sockport 3
4. error

**Screenshots**
Can’t do screenshoot

**Device (please complete the following information):**
 - iOS Version: 12.1.3
 - iOS Device: iphone 8.4 (se)
 - unc0ver Version: 3.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**

**Comment by DJ-Haegi** [comment]
Why your are on 12.1.3???
Make RestoreFS
Go to iOS 12.4 and then Jailbreak again

**Comment by ENDERZOMBI102** [comment]
Sorry but why? I want to stand on 12.1.3

**Comment by ENDERZOMBI102** [comment]
Resolved, the fault is of a tweak, not of unc0ver... sry
