### ISSUE TITLE
offsetcache.h file not found

### ISSUE THREAD

**Issue by alekye** [pwn20wndstuff/Undecimus#1446]
**Describe the bug**
I clone the project to local, and run the Undecimus.xcodeproj with xcode, a error was occurred : 'offsetcache.h' file not found.

My iPhone is : iPhone 6s plus

**Comment by vegerot** [comment]
Same problem here

**Comment by margus-lind-ctx** [comment]
Try recursive clone.
Dupe of #939 ?

**Comment by vegerot** [comment]
Oops.  Answered it myself on another thread but forgot to post the answer here too

> Not working for me :(. Would someone be able to upload and post the file on their own?
> 
> Edit: While `git submodule update` doesn't work, recloning the repo with `git clone --recursive` does work 🤷🏽‍♀️
