### ISSUE TITLE
Facebook app crashes when scrolling

### ISSUE THREAD

**Issue by nuno10costa** [pwn20wndstuff/Undecimus#1447]
This issue has been happening for me for a several weeks now. I'm now on the latest version (3.6.1) and it keeps happening. I can scroll on the news feed for a bit, but then out of nowhere the app just crashes and i'm back on the homescreen.

iPhone X 12.4

Please find the crash log attached.

[facebook crash log.txt](https://github.com/pwn20wndstuff/Undecimus/files/3589409/facebook.crash.log.txt)

**Comment by Randomblock1** [comment]
This is a tweak issue, not a jailbreak issue. Try again with tweaks disabled, if it still crashes, then it might be a jailbreak issue.
Could also be an issue with Facebook crashing if get-task-allow is on. In which case that may or may not be Unc0ver’s problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nuno10costa** [comment]
Hi @Randomblock1 thanks for your reply.

I went to icleaner and disabled all tweaks - unfortunately the issue remains...
![unnamed](https://user-images.githubusercontent.com/48016936/64601262-89bdc480-d3b4-11e9-9f0b-b4bfd479b62d.jpg)

If I reboot my phone, the issue is gone, so I believe it should be related to unc0ver, am I right?

Do you have any ideas on how to solve this?

Thanks

**Comment by Randomblock1** [comment]
Have you tried with tweaks disabled while jailbreaking (it’s an option in unc0ver), or going into safe mode?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nuno10costa** [comment]
Just tried with tweaks disabled in unc0ver and it keeps happening - please check video in attach (I've done the re-jailbreak before, so no tweaks were running).

Note: it also happens sometimes while viewing instagram stories (these are the only 2 apps that are having the issue - reinstall/update them won't fix it).

I tried also in safe mode, and it looks like I'm unable to replicate the issue...so it all seems to work correctly in safe mode...
[RPReplay_Final1568122435.zip](https://github.com/pwn20wndstuff/Undecimus/files/3596114/RPReplay_Final1568122435.zip)
