### ISSUE TITLE
Jailbreak related apps force crash, and no signs of tweaks in setting

### ISSUE THREAD

**Issue by lancerevodrifter** [pwn20wndstuff/Undecimus#145]
After jailbreaking and using the device for a while, apps relating to jailbreak (cydia, ext3nder, filza, iCleaner, etc) would immediately crash upon selecting it and opening it, however, when rejailbreaking, the apps do start up, but after a hour even half a hour, the apps would continue to force crash. At this point, even the tweaks stops working and doesn't show up in settings, the only tweaks that has no issue is PercentageBatteryX and only the percentage shows up, when I press and hold on the percent to ask if I want to respring and click yes, nothing happens. The only option is for me to reboot my device and rejailbreak. This problem recently happened with V2.0.0 and V2.0.2 Pre Release

**Comment by soum91** [comment]
Can confirm. Basically old automatic unjailbreak has respawned. Apparently it was fixed, didn’t experienced overnight unjailbreak lately but got reinstated with v2.0.1. It has something to do with unc0ver resources 0.8 update.
@pwn20wndstuff are you aware of this? I have got screenrecording of this, if needed I can post those videos.

**Comment by siris-k** [comment]
same here

https://imgur.com/a/1mMUgGs

**Comment by Diatrus** [comment]
Can also confirm, and will add that SetRes no longer activates on jailbreak as of 2.0.2.

**Comment by soum91** [comment]
Should be fixed with the unc0ver resources 0.11 update.
@lancerevodrifter you may want to close the issue.

**Comment by Samgisaninja** [comment]
Fixed in unc0ver resources version 0.11. Install update in cydia.
