### ISSUE TITLE
Self updater

### ISSUE THREAD

**Issue by Michael-Stokoe** [pwn20wndstuff/Undecimus#1451]
**Describe the bug**
After 3.6.2 was released, I tried the in-app "Check for update".
No update could be found, even though presently I have 3.6.1.

**To Reproduce**
1. Go to unc0ver app
2. Click on settings (top right)
3. Scroll down to "check for update"
4. Click it.

**Screenshots**
![70152595_2350512961864670_399288605404561408_n](https://user-images.githubusercontent.com/2981213/64546762-2c2d6780-d323-11e9-9a69-2ce00e83039d.jpg)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone Xs
 - unc0ver Version: 3.6.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver (I don't know...)

**Logs**
If applicable, add logs or error messages here.
 > It's not.

**Comment by kornjudistic** [comment]
May be try using cydia impactor. I reinstalled v3.6.2 using impactor and got jb done in first attempt in like 22s.

**Comment by Michael-Stokoe** [comment]
Sorry, you're missing the point.

I've got no issue using impactor to install. I'm reporting this bug to pwn20wnd so that in future releases he can fix it.

**Comment by kornjudistic** [comment]
Oh my bad then.

**Comment by Randomblock1** [comment]
I think Unc0ver checks for update.txt, and since that hasn’t been updated for a while, the feature just doesn’t work. Nothing I can do about that though, other than encourage you to use [my Shortcut to update Unc0ver](https://routinehub.co/shortcut/3125) with ReProvision and turn on Pwn’s [Tweet notifications](http://twitter.com/pwn20wnd).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gabri25ele** [comment]
> 
> 
> I think Unc0ver checks for update.txt, and since that hasn’t been updated for a while, the feature just doesn’t work. Nothing I can do about that though, other than encourage you to use [my Shortcut to update Unc0ver](https://routinehub.co/shortcut/3125) with ReProvision and turn on Pwn’s [Tweet notifications](http://twitter.com/pwn20wnd).
> 
> Sent with [GitHawk](http://githawk.com)

I try this https://www.icloud.com/shortcuts/bed5d2134c1d4c9f871cc88928476e72
but it founds 3.5.5 version 🤨

**Comment by Randomblock1** [comment]
@gabri25ele 

This works. I know, because I made it and I use it. https://routinehub.co/shortcut/3125 https://routinehub.co/shortcut/3125

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DJ-Haegi** [comment]
Here is my Unc0ver Updater. The Special is, you have nothing to do and it Download only, when an Update is available.

https://www.reddit.com/r/jailbreak/comments/cx8sju/release_unc0ver_update_check/?utm_source=share&utm_medium=ios_app

V4.1.1
https://routinehub.co/download/10649

**Comment by Randomblock1** [comment]
Well, mine’s made specifically to add more than a IPA downloader. It can download from Ignition _and_ respring your device. It also lets you download **_every single jailbreak available for iOS 12._** Including Chimera, u0 normal/dark, and RootlessJB. That’s what’s special about mine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Michael-Stokoe** [comment]
I think I'll stick to official solutions only.

If pwn fixed the update button, nobody would need 3rd party tools installed.
