### ISSUE TITLE
V3.6.0 and v3.6.1 not working on iPhone 6

### ISSUE THREAD

**Issue by Buddha2400** [pwn20wndstuff/Undecimus#1452]
**Describe the bug**
This version just doesn't work on iPhone 6 if it's supposed to on iPhone 6. Then a fix is needed for people that are having these issues. 

**To Reproduce**

**Screenshots**
![IMG_0015](https://user-images.githubusercontent.com/33353171/64546708-2b7fdb80-d2f9-11e9-8a6b-0ddb5775371d.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6
 - unc0ver Version: 3.6.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/3591436/diagnostics.plist.txt)

**Comment by kornjudistic** [comment]
V3.6.2 is out and it works fine for  iphone 6..i got mine done with no problem.

**Comment by Randomblock1** [comment]
Duplicate #1445 
Also, it’s fixed in the latest version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robmartin1987** [comment]
Duplicate #1444
