### ISSUE TITLE
unc0ver Version showing as 3.6.2+1.gb9c17cb

### ISSUE THREAD

**Issue by robmartin1987** [pwn20wndstuff/Undecimus#1453]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to '...' unc0ver.dev
2. Click on '....' download v3.6.3
3. Scroll down to '....' impact to device 
4. See error open unc0ver see unc0ver Version: 3.6.2+1.gb9c17cb

**Screenshots**
![25981CE3-1218-4BE2-99CF-E019CC0C6B20](https://user-images.githubusercontent.com/36098312/64557050-a6b4b200-d338-11e9-8da7-388cd8245149.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone6
 - unc0ver Version: V3.6.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by asdfugil** [comment]
I can confirm that this can be reproduced

**Comment by triaefta** [comment]
Same ios 12.4 ipad mini 2

**Comment by res1492** [comment]
Not sure if bug or just titled that way but i can confirm this also....
Iphone SE , ios 12.4

**Comment by mikemike998** [comment]
Same ios 12.4 Iphone 7

**Comment by sleeplessrazi** [comment]
Same iOS 12.4 iPhone 7
