### ISSUE TITLE
Support for Iphone Xs Max (Jailbreak & Impactor)

### ISSUE THREAD

**Issue by thekinggoffical** [pwn20wndstuff/Undecimus#1455]
So i just got a new iphone xs max and tried to jailbreak but it didnt work. i tried multiple settings & rebooting my phone multiple times up. So i was wondering when will support be made ?

**Comment by iVosey** [comment]
Ios 12.4 xr best way i found was airplane mode and wifi on an after 1-3 tries worked

**Comment by jordanthren** [comment]
You're on 12.4 right? I have the XS Max and it usually successfully jailbreaks after 1-5 attempts

**Comment by thekinggoffical** [comment]
i tried turn on airplane mode and with the wifi . i even tried uninstalling and reinstalling . i messed with some of the settings in U0 but nothing worked .

**Comment by iVosey** [comment]
Filza
Apps Manager
Reprovision
Installed 
Amd also did the respri g logo via ssh ;)

**Comment by thekinggoffical** [comment]
i used (http://www.cydiaimpactor.com/ ) for my cydia impactor.

**Comment by thekinggoffical** [comment]
i running on 12.4.

**Comment by iVosey** [comment]
Same way i do tbh 
If installs its fine
Dont mess the settings like cydia cache or install an all that as its not there. No need reinstall ssh neither

**Comment by jordanthren** [comment]
Keep trying. Sometimes it takes more attempts

**Comment by thekinggoffical** [comment]
Yeah for the most part ive just been reinstalling and deleting the app and then jailbreaking again. Most of the times i did the installing either the app would crash or the jalibreak would be complete but rather then reboot and cydia would be installed it just closes the app.

**Comment by jordanthren** [comment]
Cydia hasn't been implemented into the jailbreak for the XS Max yet. The jailbreak is only partial for A12 devices right now. The jailbreak will complete successfully but Cydia won't be installed with it yet.

**Comment by thekinggoffical** [comment]
I figured .In the meantime im not probably gonna update  to 12.4.1

**Comment by iVosey** [comment]
Changing the apple logo with filza and just awaiting reprovision to try for its first time here .

**Comment by Born2PushLimits** [comment]
> You're on 12.4 right? I have the XS Max and it usually successfully jailbreaks after 1-5 attempts

only show jailbreak complete ,nothing happen

**Comment by jordanthren** [comment]
If you’re on an A12 device, tweak injection (including Cydia) has not been implemented into Unc0ver yet. It’s only a partial jailbreak.

**Comment by Born2PushLimits** [comment]
> If you’re on an A12 device, tweak injection (including Cydia) has not been implemented into Unc0ver yet. It’s only a partial jailbreak.

looking forward 2 the modify ...
