### ISSUE TITLE
Clock.app freeze

### ISSUE THREAD

**Issue by pqhcker** [pwn20wndstuff/Undecimus#1458]
When jailbreak enabled, the clock.app freeze, and I can't set alarms... Happens on the new version that supports iOS 12.4

**Comment by Randomblock1** [comment]
That’s caused by a tweak. My Clock app works fine while jailbroken.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cdlenfert** [comment]
May not be caused by a tweak. Is it possible it was just a conincidnec that you were in the clock app when the freeze occurred? I'm getting random freezes every 24hrs requiring a hard reboot. iPhone 6, 12.4, UC 3.6.3

**Comment by jaxon0523** [comment]
I think its caused by daemon mobiletimerd
because somtimes my battery drain a lot for that

**Comment by jaxon0523** [comment]
I found fix solution in my iphone X
When I disable [Reload Deamon] and jailbreak use by unc0ver 3.7.0 b1 
its all no problm

but I'm not understand
what differnce able and disable [Reload Deamon]
my all tweaks are working

for reference
