### ISSUE TITLE
is able  2 support iphone xs max version 12.4 to jailbreak with undecimus version 3.6.2+1??

### ISSUE THREAD

**Issue by Born2PushLimits** [pwn20wndstuff/Undecimus#1461]
after several times , still can not 2 jailbreak,only show jailbreak completed...

**Comment by AmesianX** [comment]
me too..

**Comment by Born2PushLimits** [comment]
@pwn20wndstuff how 2 fix the problem , thanks a lot

**Comment by soyolaya** [comment]
Im having the exact same Problem, tried 100 times! Diffrent Versions of Unc0ver. Restored RootFs 100 Times, airplane mode on.... bla bla bla!

**Comment by Born2PushLimits** [comment]
> Im having the exact same Problem, tried 100 times! Diffrent Versions of Unc0ver. Restored RootFs 100 Times, airplane mode on.... bla bla bla!

and the result?

**Comment by soyolaya** [comment]
No Result
