### ISSUE TITLE
Iphone 7 12.4 UC crash by no access with ldid

### ISSUE THREAD

**Issue by suerion** [pwn20wndstuff/Undecimus#1462]
**Describe the bug**
![8A680C8B-95E2-48AC-A5B2-E0345BEA22E4](https://user-images.githubusercontent.com/55131959/64596595-7d396c00-d3b4-11e9-858d-a45e9a668188.png)

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: i7
 - unc0ver Version: 3.6.2+1....

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

**Comment by suerion** [comment]
Yet i had give the failure, my iphone was jaulbroken, but the rootfs is already mounted.

UC Crashed and the Iphone restarts

**Comment by zikha** [comment]
My phone 7 (12.4) on v3.6.1 takes forever to respring after the jailbreak it took 3 minutes, it jailbroke after 3 seconds..

**Comment by zikha** [comment]
Same on v3.6.0 cause I can't jailbreak on v3.6.2 and last, respring after jailbreak takes more than 3 minutes now... normally the resprings takes 10 seconds...
