### ISSUE TITLE
Outdated compatibility in setting description 

### ISSUE THREAD

**Issue by asdfugil** [pwn20wndstuff/Undecimus#1465]
**Describe the bug**
Same as tile

**To Reproduce**
1. Go to 'Unc0ver'
2. Click on 'Settings'
3. Click on the info button 
4. Outdated compatibility info

**Screenshots**
![55BFC3A7-9172-4B72-9A03-F6EE7974DF14](https://user-images.githubusercontent.com/42699250/64607352-ee037700-d3fa-11e9-84fa-ae6ba156be19.png)
![DD4251AD-0527-4E03-9F37-07B4569B544E](https://user-images.githubusercontent.com/42699250/64607353-ee9c0d80-d3fa-11e9-8f64-e7a26f1571a4.png)
![0F511692-35AE-4987-919A-52FBCFB1E10E](https://user-images.githubusercontent.com/42699250/64607354-ee9c0d80-d3fa-11e9-9406-698ef090b265.png)
![3CB4E78B-3E2E-4E13-B200-AB7C2F93F95F](https://user-images.githubusercontent.com/42699250/64607355-ef34a400-d3fa-11e9-852b-1d27fb1ca91d.png)
![CCD97BF1-0AEB-4AEC-89AA-54F3BF8726E2](https://user-images.githubusercontent.com/42699250/64607357-ef34a400-d3fa-11e9-8d62-b24e1abc9758.png)

And more
**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device: iPhone8,2
 - unc0ver Version: 3.6.2+1.gb9c17cb

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by CARLO5ONIC** [comment]
I also made a post about this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
