### ISSUE TITLE
Crash safari vidéo play

### ISSUE THREAD

**Issue by bammargera** [pwn20wndstuff/Undecimus#1467]
**Describe the bug**
When you try to play video in some web IN 4G,the iphone x go in safe mode/or reboot

**To Reproduce**
1. Go to : in 4g and go to : https://www.dealabs.com/discussions/xiaomi-m-365-a-40-kmh-1497187
2. Click on play video
3. Try to skip 10’s 3/4 and try to skip back 10’s 3/4

**Screenshots**
I can sens you a video if it’s can help you

**Device (please complete the following information):**
 - iOS Version:  10.4
 - iOS Device: iphone X
 - unc0ver Version: 3.6.1 because higher not work (step 1 and app crash

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
N/A

**Comment by Randomblock1** [comment]
Does it still do that in safe mode? If it doesn’t, a tweak is causing it.

**Comment by bammargera** [comment]
Hi, thx for your reply.
I’ve fond the problem.
It’s settings with 4g data abroad.

I think this bug it’s solved beacause i think it’s with my phone operator

Un order bug it’s with undecimous 3.6.3/3.6.2 i cant use it (crash at 1 step)

* i can help you in the future for your devloppement

Sory i’m french guy =)
** a traduction of undecimous are cool, nop ?
