### ISSUE TITLE
LPM settings app delay

### ISSUE THREAD

**Issue by di0nisio** [pwn20wndstuff/Undecimus#1468]
**Describe the bug**
Settings app delay to open when install any tweak.

**To Reproduce**
-Put idevice in LPM
-Jailbreak with "load tweaks" and "reload system daemons" enabled
-Install any kind tweak (eg. CC on&off from poomsmart repo)
-Open Settings app and look delay
-turn off "load tweaks" and delay is gone

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 7
 - unc0ver Version: 3.6.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Randomblock1** [comment]
That’s iOS trying to conserve power, because you told it to.
It disables features and also throttles itself (I think) to save power.
Not unc0ver’s issue.
