### ISSUE TITLE
vers. 3.6.2+1. gb9c17cb wifi issue

### ISSUE THREAD

**Issue by Maniacfest** [pwn20wndstuff/Undecimus#1473]
**Describe the bug**
iPhone's wifi keep disconnecting whenever turning phone to sleep.

**To Reproduce**
1. iPhone put to sleep mode (power button)
2. after a couple of minutes wifi disconnects
3. turn iPhone on (see error)
4. manually connect Wi-Fi through settings

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 11.1.1
 - iOS Device: iPhone 5S
 - unc0ver Version: 3.6.2+1. gb9c17cb

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by nickflash01** [comment]
same issue on iphone 8

**Comment by Lovestatic** [comment]
iOS Version: 11.3.1
iOS Device: iPhone 7
unc0ver Version: 3.6.2+1. gb9c17cb


Same situation

**Comment by nickflash01** [comment]
> iOS Version: 11.3.1
> iOS Device: iPhone 7
> unc0ver Version: 3.6.2+1. gb9c17cb
> 
> Same situation

use 3.5.2 for now as i m using that on iphone 8

**Comment by Lovestatic** [comment]
> > iOS版本：11.3.1 
> > iOS设备：iPhone 7 
> > unc0ver版本：3.6.2 + 1。gb9c17cb
> > 同样的情况
> 
> 现在使用3.5.2作为我在iphone 8上使用它

I found the reason for the reboot.   hold disable updates and disable revokes  Just close it.

**Comment by Maniacfest** [comment]
i think i've found a fix for this issue. might not work for everybody.

1. Restart iDevice (Hard Reboot)
2. Re-jailbreak your iDevice

hope this fixes your issue too

**Comment by thekio1984** [comment]
just enable wifi calling lol easist fix, or just install a cydia tweak like `fiona` or `iNoSleep` for example, this imo isnt jailbreak, its ios, near enough every device i own ranging from ios 10-13 has this issue even in stock, although its more noticable ios11 & even more so for ios 12.

**Comment by Maniacfest** [comment]
okay you don't have to act like you're a professional about iOS stuff or jailbreak stuff. i was on unc0ver 3.3.3 and the wifi never disconnects and never did i have to reconnect it manually, so yeah i would say this unc0ver's version caused the issue.
