### ISSUE TITLE
vers. 3.6.2+1. gb9c17cb with file write Privilege

### ISSUE THREAD

**Issue by sailor-fly** [pwn20wndstuff/Undecimus#1480]
**Describe the bug**
iPhone6, ios12.4, to jailbreak using vers. 3.5.5, files in /var/mobile/Library/Preferences/  are access to write, however, when i use vers. 3.6.2+1. gb9c17c to jailbreak, files in /var/mobile/Library/Preferences/  are not access to write.

**Comment by Cregin** [comment]
how to fix? @sailor-fly
