### ISSUE TITLE
unc0ver 3.6.3 - locks up and freezes entire phone

### ISSUE THREAD

**Issue by EdgeXS** [pwn20wndstuff/Undecimus#1481]
**Describe the bug**
So using unc0ver 3.6.3 on an iPhone 6 (a8).  Works pretty great however randomly after using the phone exiting an app and try to select the messages app or settings app and the phone locks up (freezes) the UI is not responsive at all.  Have to do a hard reset and rejailbreak.

**To Reproduce**
there are no consistent ways to reproduce this except use the phone but there are close to 95+ people having this same issue with unc0ver.
https://www.reddit.com/r/jailbreak/comments/d4opdz/ 

**Screenshots**
No screenshots applicable 

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6 (A8)
 - unc0ver Version: 3.6.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cdlenfert** [comment]
Adding myself to the list of folks experiencing this

**Comment by EdgeXS** [comment]
This happens about 1-2 days after using the 3.6.3 jailbreak. Didn't happen with 3.5.6 release. Just the 3.5.6 release was considerably less consistent in jailbreaking.

**Comment by fioute** [comment]
Hello,
I am experiencing the exact same issue. Very well described btw.
I have an iPhone 8 running 12.4 and tried every version of unc0ver from 3.5.6 to 3.6.3.
Sincerely

**Comment by simonw2g** [comment]
Hi I added myself also to the group with this issue. 
For me also, this happens about some time after using the 3.6.3 jailbreak. 

I deinstalled some tweaks but no healing. The GUI stuck some time after use and also a respring, reboot, renewal of Jailbreak or refresh the cache with Sleep and Homebutten not works. I checked my RAM with a cydia tweak and its overloaded. Only ~20-50MB free. 

Please help in finding a solution or consider it in a new Unc0ver version. 

simonw2g
