### ISSUE TITLE
u0 open-source?

### ISSUE THREAD

**Issue by Strykeros** [pwn20wndstuff/Undecimus#1483]
**Describe the feature you'd like**
I'd like to see atleast one of the new u0 versions go open-source. You said that jaibreaking is all about choice and freedom in twitter.

**Describe alternatives you've considered**

**Additional context**
Any of 3.5.x versions open-source?

**Comment by yousef157** [comment]
@pwn20wndstuff said in Reddit that it wants it to be closed source for a while. I don't know why, but that's what I remember.
