### ISSUE TITLE
iphone7 is not support?

### ISSUE THREAD

**Issue by willerhehehe** [pwn20wndstuff/Undecimus#1488]
**Describe the bug**
unsupport

**Screenshots**
![3291568960257_ pic](https://user-images.githubusercontent.com/32084498/65304143-81366c80-dbb2-11e9-8610-1acfb1ab7d71.jpg)

**Device (please complete the following information):**
 - iOS Version: 12.3.1
 - iOS Device: iphone7
 - unc0ver Version: 3.6.0

**Comment by sever89-dev** [comment]
I think you have to update to iOS 12.4.

**Comment by nik312123** [comment]
iOS 12.3.x is not supported at all. All other iOS 12 versions are supported.

Please close this issue as this is already known and will not be fixed due to Apple's current protection on that version.
