### ISSUE TITLE
iOS 11.4b6

### ISSUE THREAD

**Issue by DottiestDuke47** [pwn20wndstuff/Undecimus#149]
Can you support iOS 11.4b6?

**Comment by clarityzzz** [comment]
no

**Comment by FivePixels** [comment]
This is a place for issues - not suggestions.

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb
