### ISSUE TITLE
Unable to restart substitute on XS Max

### ISSUE THREAD

**Issue by FocusedSG** [pwn20wndstuff/Undecimus#1493]
**Describe the bug**
I tried rejailbreaking and it shows me that on 3.7.0b1

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by musa11971** [comment]
+1
