### ISSUE TITLE
Clock.app was deleted

### ISSUE THREAD

**Issue by KibSquib48** [pwn20wndstuff/Undecimus#1494]
The clock app will not open, it just hangs on the loading screen

1. Open Clock app

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6
 - unc0ver Version: 3.7.0 Beta 1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by jaxon0523** [comment]
in the same

- iOS Version: 12.4
- iOS Device: iPhone X
- unc0ver Version: 3.7.0 Beta 1

**Comment by jaxon0523** [comment]
I found fix solution in my iphone X
When I disable [Reload Deamon] and jailbreak use by unc0ver 3.7.0 b1 
its all no problm

but I'm not understand
what differnce able and disable [Reload Deamon]
my all tweaks are working

for reference
