### ISSUE TITLE
XS MAX 12.1 No tweak injection in Safari

### ISSUE THREAD

**Issue by Akasuo** [pwn20wndstuff/Undecimus#1496]
Installed latest unc0ver on my 12.1 xs max, and there is no tweak injection in Safari. Everything is up-to-date and i got rocketbootstrap from rpetri.ch

**Comment by gitgud191** [comment]
I have the same issue. I noticed when I tried to theme it using both Eclipse and Noctis and nothing changed.
Edit: I'm on a XS Max with 12.1.2

**Comment by KillahDT** [comment]
same issue here 
3 tweaks installed:  batterynotch and batterypercentx and a safari tweak called safari plus for downloads
all of them dont work in safari

xs max ios 12.1.2

**Comment by mzxnbcv** [comment]
Same issue here on an iphone xs max 12.4
