### ISSUE TITLE
iOS 12.4 A12 IPhone XSMAX camera not working in ANY apps

### ISSUE THREAD

**Issue by SlenderFN** [pwn20wndstuff/Undecimus#1497]
The camera will work for a few seconds with the camera app then just freeze.

**Comment by maswatermelon** [comment]
I am having the same issue on my iPhone XS. At first, I thought it was just Snapchat detecting that I was jailbroken, but it was the same for the Camera app and any apps that use the camera.

**Comment by sandeepsrf** [comment]
I am having the same issue. Thank god i found this forum otherwise i had gone mad googling for it. I have the same issue . Camera app doesnot work anywhere. Fb, insta or snapchat. Toggle between modes photo/ video works but no image.

**Comment by ckrzyzak** [comment]
I thought this was just me but none of the applications that take pictures are showing anything other than a black screen from the camera

**Comment by miguelr4720** [comment]
please close this issue its already fix
Unc0ver 3.7.0~b3 

Please Close ;(
