### ISSUE TITLE
Camera app shows no image nor takes any picture/video

### ISSUE THREAD

**Issue by sandeepsrf** [pwn20wndstuff/Undecimus#1498]
**Describe the bug**
When Camera app is not running in the background and we load it for the first time, it shows black image. But when its already running in the background, it shows image for 2-3 seconds and then the image blurs out and freezes. However the selecting different modes on the camera app works but no image nor it can save any image.

**To Reproduce**
1. Jailbreak the A12 device
2. Run the camera app
3. See error

**Screenshots**
Not required

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: A12 (Iphone 11,6)
 - unc0ver Version: 3.7 beta 1

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by 2JayCee** [comment]
I also have the same problem.  iPhone XS.  unc0ver 3.7 beta 1.  

Edit: Okay now it sometimes works.  The camera displays but now freezes and won't work.

Edit 2:  The camera works sometimes.  It will show something then blur and not work.

**Comment by woofgrrrbark** [comment]
The camera works on my xR running 12.4 if no tweaks are installed

**Comment by Goldstriker208** [comment]
same here using iPhone XR on iOS 12.4

**Comment by miguelr4720** [comment]
please close this issue its already fix
Unc0ver 3.7.0~b3 

Please Close ;(
