### ISSUE TITLE
Apple's Screen recorder not recording audio

### ISSUE THREAD

**Issue by brand175** [pwn20wndstuff/Undecimus#1499]
iPhone XR on iOS 12.4.

**Comment by sandeepsrf** [comment]
U shd check wether the  microphone is disable or nor before recording starts. If u 3d press on recoding button it will popup

**Comment by brand175** [comment]
@sandeepsrf it's not the microphone, it's the game audio.

**Comment by nik312123** [comment]
As can be seen from https://support.apple.com/en-us/HT207935, "Some apps may not allow you to record audio."

This is the case for many applications.

**Comment by brand175** [comment]
@nik312123 I am recording on a compatible app.

**Comment by nik312123** [comment]
This issue does not occur when you are in a nonjailbroken state, correct?

**Comment by brand175** [comment]
@nik312123 This issue only occurs when i'm jailbroken. It works just fine when in a nonjailbroken state.

**Comment by Vestaia** [comment]
Same issue.
iPad Pro 3rd gen 11" Wifi (J317AP).
Screen recording audio works fine on iPhone X (same iOS and Unc0ver version - 12.4 & 3.7.0~b1).

Edit:
Seems to be caused by tweaks that capture audio (Mitsuha Infinity)
