### ISSUE TITLE
Add link to GitHub in Settings page

### ISSUE THREAD

**Issue by haykam821** [pwn20wndstuff/Undecimus#15]
In the Settings tab, there is a Utilities section including links to useful resources related to unc0ver:

![Utilities section](https://i.imgur.com/2sWKWGe.jpg)

This could be improved by a link to the GitHub page (“Source Code” button) or to submit a new issue (“Report a Bug”).

**Comment by pwn20wndstuff** [comment]
Good idea. Will be added soon.

**Comment by Samgisaninja** [comment]
Added in 1.1.1, will be compiled and released shortly
