### ISSUE TITLE
gps/location service is not working after jailbreak

### ISSUE THREAD

**Issue by devcline** [pwn20wndstuff/Undecimus#150]
The location services only works when is set to "always working" in settings but not all apps have this option (uncover latest version) (iphone x 11.2.1)

I tried

- resetting network settings (in jailbreak and non jailbreak mode)
- reboot
- rejailbreak
- the 3 tweaks Location Fixer (deb file), LocationFix and liblocation
- load the service from /System/Library/LaunchDaemons or /Library/LaunchDaemons
- reset location settings
- icleaner pro

The location services is working fine in non jailbreak mode

ps: i have a file com.apple.locationd.plist 2kb located in /System/Library/LaunchDaemons

What can i do else? Thanks

**Comment by Cryptiiiic** [comment]
@devcline There's probably another package that you don't even realize is a tweak. Disable tweaks in iCleaner one by one(ldrestart after each disable), if all tweaks are disabled and it still doesn't work, try rebooting then jailbreak again. If it still doesn't work, I don't know yet.

**Comment by devcline** [comment]
Any way to investigate it ? Like some kind of logs for locations ? Console commands?

**Comment by Cryptiiiic** [comment]
@devcline did you test it yet?

**Comment by Cryptiiiic** [comment]
@devcline can I close this?

**Comment by devcline** [comment]
Yes , thank you very much . !
