### ISSUE TITLE
 Spotify freezes when streaming to a Wi-Fi device 

### ISSUE THREAD

**Issue by woofgrrrbark** [pwn20wndstuff/Undecimus#1500]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to Spotify
2. Click on any song
3. Stream to a wifi device
4. See error (The app freezes and the Wi-Fi device name doesn't show up)

**Screenshots**
![1DE6541B-06AF-46D0-A71E-F4AAF4678744](https://user-images.githubusercontent.com/25355277/65396949-d40e5080-dd79-11e9-9c12-798f4f63dc15.png)
![FBAA40E4-9E6B-4715-A649-A6D6E39EB51F](https://user-images.githubusercontent.com/25355277/65396950-d40e5080-dd79-11e9-9d2b-cbb589324297.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: xR
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by dbaelon** [comment]
Yes! I have the same issue when I connect my device to a google home speaker. I am using an iPhone XR on 12.4 jailbroken using unc0ver.
