### ISSUE TITLE
Shutdown and jailbreak issues

### ISSUE THREAD

**Issue by MythicalArcher** [pwn20wndstuff/Undecimus#1501]
**Describe the bug**
Time: 8:48 Eastern time. 
1. When I first attempted to shutdown my device (IPhone XR) it would stay in a black screen. 
I performed a hard reset, phone successfully shut down.
2. When it finished booting up I attempted to re-jailbreak. The "jailbreak successful" prompt popped up, I pressed ok and the device went black and a red line appeared, then and the restarted. 
3.My second attempt ended with my phone staying in a black screen, and had to hard reset it.

**To Reproduce**
NOTE: In order begin to reproduce the issue, The IDevice must be in a jailbroken state.
1. Shutdown IDevice.
2. [1] Black screen
3. Perform Hard reset
4. Open IDevice, and open Unc0ver
5. Press jailbreak
6. End result: [2 or 3]

**Screenshots**

![IMG_0516](https://user-images.githubusercontent.com/52841681/65397431-189beb00-dd7e-11e9-8b68-6ef03f61547d.PNG)
![IMG_0517](https://user-images.githubusercontent.com/52841681/65397432-189beb00-dd7e-11e9-9921-ef1d6f4b1c11.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: IPhone XR
 - unc0ver Version: 3.7

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by palxex** [comment]
Could you explain how you did the hard reset? I entered same situation.

**Comment by MythicalArcher** [comment]
If you have an iPhone X and above: press and release volume up, press and release volume down, and press and hold the power button. Release power button when you see the apple logo

**Comment by palxex** [comment]
@MythicalArcher thanks very much.
