### ISSUE TITLE
Unable to turn off iPhone XS

### ISSUE THREAD

**Issue by 2JayCee** [pwn20wndstuff/Undecimus#1502]
**Describe the bug**
Attempting to turn off iPhone results in a black screen.  Plugging phone into charger or PC will detect the iPhone.

**To Reproduce**
1. Hold Side Button & Volume Up
2. Slide to power off

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Goldstriker208** [comment]
same here using iPhone XR on iOS 12.4

**Comment by mattrat88** [comment]
iPhone xr iOS 12.4

**Comment by mattrat88** [comment]
i honestly just want my phone to turn off ...

**Comment by 2JayCee** [comment]
Solution is to soft reset.  Press Volume Up, then Volume Down, and finally hold Side Button.
