### ISSUE TITLE
iOS 12.4 A12 iPhone XR Location problem

### ISSUE THREAD

**Issue by Dacanid** [pwn20wndstuff/Undecimus#1504]
Location problem, open the Apple map has been loading location, can not locate

**Comment by Dacanid** [comment]
In addition to the Apple map, I also opened other map apps, including google maps, they all show that the location is loading, but I have been unable to locate my address.

**Comment by nik312123** [comment]
What are your location settings for those applications under Settings -> Privacy -> Location Services?

**Comment by Dacanid** [comment]
> What are your location settings for those applications under Settings -> Privacy -> Location Services?

Allow location information during use

System settings allow these programs to get location information

**Comment by nik312123** [comment]
Hmm... And this issue does not occur when you are in an unjailbroken state, correct?

**Comment by Dacanid** [comment]
> Hmm... And this issue does not occur when you are in an unjailbroken state, correct?

Yes, I repeated the reboot several times, the jailbreak operation

I found that it can be used normally when not jailbroken.

After the jailbreak, these programs only prompt "Loading"

**Comment by nik312123** [comment]
Could you try changing it to always allow location and see if that changes anything? It probably won't help, but it's worth a try.

**Comment by Dacanid** [comment]
> Could you try changing it to always allow location and see if that changes anything? It probably won't help, but it's worth a try.

Already tried, can't improve

In the past few hours

I tried to uninstall all plugins

Reboot the device

Reinstall Google Maps

Re-Jailbreak several times

**Comment by dannyboykin** [comment]
i have the same problem. location doesn’t work on any apps when in jailbroken state but works when not jailbroken

**Comment by Dacanid** [comment]
Location issues and camera issues, may be ubiquitous bugs

**Comment by Dacanid** [comment]
12.4
iPhone XR
MT192CH/A
