### ISSUE TITLE
[HELP]I wanna get the suorce code of v.3.6.3. by switch branches or check out tags ,but I have some problem.?

### ISSUE THREAD

**Issue by PointSoBig** [pwn20wndstuff/Undecimus#1505]
I tried to  switch branches and check out tags to get suorce code of v.3.6.3,when i  run the project, I found that the version is 3.3.0,what should I do?
![IMG_0721](https://user-images.githubusercontent.com/14027556/65399804-5ab24480-ddf1-11e9-8810-e87044938db5.PNG)

**Comment by holyswordman** [comment]
uncover is closed source now

**Comment by sethfork** [comment]
Can we add a discussion label to this? It'd be great to hear more about the reasoning behind close-sourcing this project.
