### ISSUE TITLE
A12 IOS 12.4 - location, Face ID, auto fill passwords

### ISSUE THREAD

**Issue by dannyboykin** [pwn20wndstuff/Undecimus#1508]
i have a A12 device on 12.4 and face id and location and auto fill passwords do not work while in a jailbroken state but do work when not jailbroken

**Comment by lourenz101091** [comment]
same issue

**Comment by Goldstriker208** [comment]
same here using iPhone XR on iOS 12.4

**Comment by lourenz101091** [comment]
using iPhone XS Max 12.4

**Comment by Born2PushLimits** [comment]
@pwn20wndstuff  the same issue with ios 12.4, iphone xs max ,uncover version 3.7.0

**Comment by oden6222** [comment]
Yes! I have the same issue. The camera dont work at all. Just black screen. Locations doesnt work either and all my passwords are unable to be used with faceid. 
Xs max 12.4 - v3.7.0%b1

**Comment by elteekta** [comment]
Same issue with the autofill but face id still works, one fix i saw that fixes camera (so could potentially fix the face id dramas) goes as follows

1. Download the tweak”NewTerm”
2. Open it, type “su”
3 type “alpine” into the password 
4 type “ldrestart” 
Once the device has restarted give it a check, my auto fill is still broken but im pretty sure at the beginning of my jailbreak it was working

Im on a12 12.2, chances are it wont fix auto fill but let me know
