### ISSUE TITLE
Face ID, Location and Camera issues

### ISSUE THREAD

**Issue by Goldstriker208** [pwn20wndstuff/Undecimus#1509]
**Describe the bug**
Face ID:
Face ID does not work properly when installing a new app from the AppStore.  Also, in the Messages app, Memoji does not work and other third apps won't work with Face ID.  However, Face ID works when unlocking your iPhone.

Camera app:
Camera app works for a few seconds then freezes up.

Maps app:
Won't show your current location.

**To Reproduce**
Steps to reproduce the Face ID issues when installing an app:
1. Go to the AppStore
2. Click on any new app to install
3. Then it says payment not completed

**To Reproduce**
Steps to reproduce the Face ID issues when using a third-party app:
1. Go to any third-party app that uses Face ID
2. Face ID doesn't work

**To Reproduce**
Steps to reproduce the issues on the camera app:
1. Go to the Camera app
2. Camera app works for a few seconds then blurs camera then the camera freezes then it shows a black screen

**To Reproduce**
Steps to reproduce the issues on the maps app:
1. Go to the maps app
2. Maps doesn't show your current location and keeps loading

**Screenshots**
Screenshots for Face ID issues:
![IMG_3020](https://user-images.githubusercontent.com/47230190/65405305-83eeb880-dd90-11e9-8c41-1b2a8d650b44.PNG)

Screenshots for Camera app issues:
![IMG_3012](https://user-images.githubusercontent.com/47230190/65405259-6c173480-dd90-11e9-9ce1-af3d3085d845.PNG)
![IMG_3024](https://user-images.githubusercontent.com/47230190/65405289-7802f680-dd90-11e9-9e94-6550bab9a20c.PNG)

Screenshots for Location issue on apple maps:
![IMG_3025](https://user-images.githubusercontent.com/47230190/65405185-35d9b500-dd90-11e9-895b-ee278ac2dd07.jpg)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XR
 - unc0ver Version: 3.7.0 b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by mizo858** [comment]
Same issues and you cannot enter to your passwords & apps in settings and also google maps dont work

**Comment by Dacanid** [comment]
same question

**Comment by mrmcphisto** [comment]
Same issue here, iPhone XR

**Comment by wrabo** [comment]
iPhone XS Max after jailbreaking camera and faceid not working

**Comment by sandeepsrf** [comment]
Same problem here

**Comment by ghost** [comment]
iPhone XR 12.4 face id and camera its not working :(

**Comment by LuzBelitoLP** [comment]
the same problem Iphone XS 12.4 cam not working...

**Comment by iTolga** [comment]
The same for me
iPhone XS - iOS 12.4 
Unc0ver 3.7.0-b1

**Comment by eilnei** [comment]
Same here, non of them working
iPhone XS 12.4

**Comment by Born2PushLimits** [comment]
@pwn20wndstuff 
The same for me
iPhone XS max- iOS 12.4
Unc0ver 3.7.0-b1

**Comment by ericssonruffy** [comment]
Same here, iPhone XSMax on iOS 12.2 with Unc0ver 3.7.0b1
