### ISSUE TITLE
Catastrophic failure of something with 2.0.1

### ISSUE THREAD

**Issue by DarkRagnarok** [pwn20wndstuff/Undecimus#151]
Steps got stuck at 47, app stayed like that, didn’t crash for over 30 mins. Apps wouldn’t install, or update. Amazon prime had the player buttons stuck on screen and apps like Netflix and YouTube broke fully. Phone stayed like this for about a day until it crashed and gave me the Apple logo with a progress bar. Had to update to iOS 12 with my computer to fix.

**Comment by Samgisaninja** [comment]
Thanks for the report.

**Comment by DizzyDaz** [comment]
F
