### ISSUE TITLE
Password & app setting A12 xs ios 12.4

### ISSUE THREAD

**Issue by mizo858** [pwn20wndstuff/Undecimus#1510]
Can not enter to settings/passwords & accounts/website & app passwords
While jailbroken but work if the phone not jailbroken

**Comment by paradoxboy** [comment]
Same problem here

**Comment by WayneBishop1** [comment]
Same here also camera not working sometimes.

**Comment by paradoxboy** [comment]
Try to re jb for the camera it will work

**Comment by WayneBishop1** [comment]
I have quite a few times now :(
