### ISSUE TITLE
rootfs already mounted delete ota file XS-MAX 12.1.0

### ISSUE THREAD

**Issue by thu3n** [pwn20wndstuff/Undecimus#1512]
Hi!

I'm getting rootfs already mounted delete ota file. There is no OTA file existing. And the Check for update in IOS don't work, it says "unable to check for update" so i cannot try to download the update and then remove it. Any suggestions?

**Comment by h4ckua11** [comment]
First try to go into Settings and Storage and see if you can find the OTA file. 
If not try to go into Unc0ver and then into the settings panel and turn off _Disable Auto Updates_. Then click jailbreak and go into Settings and Go to the update panel. Then search for update but be careful not to update it, just download it and then go into storage and remove it. Then you should be able to go into Unc0ver and jailbreak normally.

**Comment by thu3n** [comment]
Sorry m8 it feels that you didn’t read my thread. I have already tried all mentioned. 

Before i smashed the jailbreak button it worked to search for the ios update, and after that the search for ios update displays ”unable to search for update”. I have tried to disable wifi, disable cellular, hard restart iphone, tried to go into Unc0ver and then into the settings panel and turn off Disable Auto Updates. and so on. And the ota does not display in storage to remove

**Comment by thu3n** [comment]
Because the search for the ios update worked before i smashed the jailbreak button my thoughts go to that maybe Unc0ver somehow disables the IOS update function?

**Comment by thu3n** [comment]
Ok. This is now closed

For some reason the "Update IOS" section was working again, the reason is probably cause i had airplane mode on for 1 hour, this was probably solved with airplane mode on for 5-10 minutes or less. 

Whatever, when i downloaded IOS13 (not install) i then removed the download from storage. Restarted the device within the unv0ver app(This probably doesn't mather), enabled airplane mode and smashed the jailbreak button, it crashed. Re-opened the app and smashed it again and now i have a jailbroken iphone.


**To do if rootfs already mounted delete ota file XS-MAX 12.1.0:**
1. Start airplane mode and let the phone be for like 5min or so -> Disable ariplane mode.
2. Check for iSO updates -> "Download & Install". When it has Downloaded and "Prepared Update" you will have a 10sec window to "install the iOS later" if you miss this, then you fucked..
3. If you survived 2nd stage. You will now go to "General" -> Iphone & storage" -> IOS 13(in this case) -> delete update.
4. Open Unv0ver -> Settings -> scroll down and hit the "restart" button to restart phone.
5. Open Unc0ver again and smash the "Jailbreak" button, if crash close app and re-open it and try again.

**Comment by h4ckua11** [comment]
> Ok. This is now closed
> 
> For some reason the "Update IOS" section was working again, the reason is probably cause i had airplane mode on for 1 hour, this was probably solved with airplane mode on for 5-10 minutes or less.
> 
> Whatever, when i downloaded IOS13 (not install) i then removed the download from storage. Restarted the device within the unv0ver app(This probably doesn't mather), enabled airplane mode and smashed the jailbreak button, it crashed. Re-opened the app and smashed it again and now i have a jailbroken iphone.
> 
> **To do if rootfs already mounted delete ota file XS-MAX 12.1.0:**
> 
> 1. Start airplane mode and let the phone be for like 5min or so -> Disable ariplane mode.
> 2. Check for iSO updates -> "Download & Install". When it has Downloaded and "Prepared Update" you will have a 10sec window to "install the iOS later" if you miss this, then you fucked..
> 3. If you survived 2nd stage. You will now go to "General" -> Iphone & storage" -> IOS 13(in this case) -> delete update.
> 4. Open Unv0ver -> Settings -> scroll down and hit the "restart" button to restart phone.
> 5. Open Unc0ver again and smash the "Jailbreak" button, if crash close app and re-open it and try again.

Exactly what I said just in other words.

**Comment by thu3n** [comment]
Yes yes, but my issue was that i couldn’t try ”delete ios update” method cause my phone couldn’t even find ios13 update to download cause it got a error.
