### ISSUE TITLE
Unc0ver respring after jailbreak stuck at black screen forever on A12 XS 12.4 

### ISSUE THREAD

**Issue by sooxt98** [pwn20wndstuff/Undecimus#1515]
shows either black screen or spinning indicator.

**Comment by qiushurong** [comment]
same, press + then - then hold Shutdown To Restart your iphone, try more jailbreak , It work on me. (5 times for me)

**Comment by mattrat88** [comment]
cannot even get it to shut down 
after roofs restore no spinning logo nothing just a black screen lit up a tiny bit

**Comment by mattrat88** [comment]
iPhones getting really hot too :/ i just wanna turn it off

**Comment by sooxt98** [comment]
I resolve it by force restart > restore root fs > re jailbreak, and
makesure you don't update any package in Cydia

**Comment by mattrat88** [comment]
i cannot even force a restart it just stays on a black screen

**Comment by mattrat88** [comment]
iTunes says it cannot connect to my device is there anyway i can get a log file from it ???

**Comment by sooxt98** [comment]
Looks like you break your phone? What phone are you using?

**Comment by ImVxping** [comment]
I have the same problem. I tried to shut it off using 3uTools, but it didn't worked. I'm using an iPhone XS

Edit: The battery need to be off, put it on a freezer it's gonna drain the battery pretty quickly

Edit #2: I put my phone in the freezer for about 2 hours, and I charged it, and sucessfully started

**Comment by ImVxping** [comment]
The battery need to be off, put it on a freezer it's gonna drain the battery pretty quickly

**Comment by kushrael** [comment]
i did a soft reset by pressing + then pressing - and then holding the big button on left for 15 seconds and i was ok

**Comment by kaimakes** [comment]
Just had this same issue. iPhone Xr, phone is very hot, awaiting battery drain. Second time this has happened now

**Comment by mrbonner2984** [comment]
Just happened. Respring and then black screen. Gonna hold off on using this jailbreak until they push update. Now gotta wait for battery to drain

**Comment by luchoon** [comment]
Same stays stuck black screen or spinning not even letting me restart

**Comment by dsammuzaki** [comment]
Yeah me too. After i jailbreak twice, Black screen is happen. I can’t even do anything to turn it on. How to fix it? Help

**Comment by cerebral-314** [comment]
Ok. I have a question for all of you.  Did you guys add any repos to cydia right before this happened?
