### ISSUE TITLE
Random resprings all the time, on iPhone 7 iOS 12.4

### ISSUE THREAD

**Issue by MODZ4FUN420** [pwn20wndstuff/Undecimus#1517]
Since iOS 12.4 Jailbreak has been released I updated from 12.1.2 to 12.4 on a iPhone 7, random resprings have been occurring all the time since. It happens when I double tap the home button and about to kill a app in the back ground, or shortly after I kill the app or apps. It also happens a lot when I am updating a bunch of apps in the AppStore. And crashreporter isn’t working on iOS 12.4 yet, or needs updated so iPhone 7 can use it. But I would see what’s going on with the springboard to see if it could be a tweak that I have installed but I currently don’t know another way. Just thought I would share this so possibly pwn or the unc0ver team can investigate this or contact me to try to fix this. You can also DM me in Twitter if your pwn or anyone on the unc0ver team if you want a list of what I have installed to see if it’s what I have installed or the tool. Also I have been keeping up to date on the latest unc0ver tool since version 1.0. But I am on 3.7.0 b1 currently and the issue is still happening. Other than this annoying respiring issue that happens around 10 or more times a day, I love unc0ver and am very thankful and loyal to the unc0ver team. Best Jailbreak since our last untethered public release on iOS 9.x.x by pangu. So thank you so much pwn and the unc0ver team for all the amazing work you guys have done.

**Comment by qiushurong** [comment]
same, 12.4 xs max  :  press + then - then hold Shutdown To Restart your iphone, try more jailbreak , It work on me. (5 times for me)

**Comment by mrpras** [comment]
This has been happening for me too on iPhone 7 since uncover has a rewrite (not the move to 12.4 but the rework that happened recently). It’s not common but usually once a day or so there’s a random respring. Happens usually when using certain apps, but can’t confirm that as it’s quite uncommon. Still didn’t happen before the rework (3.6.3 I think)

**Comment by MODZ4FUN420** [comment]
It happens at least 5 to 10 times a day for me now. Drives me crazy.

**Comment by 2JayCee** [comment]
I suggest using the 3.6.0 or slightly higher version for your iPhone.  I’ve found that using the latest builds make my older devices less stable.  

All iPhone models underneath iPhone X use 3.6.0

iPhone XS and up use the latest builds.

**Comment by mrpras** [comment]
Thanks for the suggestion, I was thinking to try an older build but wasn’t sure which is a good choice.

**Comment by Gamr13** [comment]
I get about 3-4 random resprings on my iPhone 7 12.4 a day.

**Comment by cerebral-314** [comment]
Crashreporter FTW!

**Comment by Gamr13** [comment]
CrashReporter and Cr4shed don’t name any culprit.

**Comment by cerebral-314** [comment]
Then it sounds like you either have a bad battery or you are one of the unlucky owners of a flakie iPhone 7 logic board.

**Comment by Gamr13** [comment]
Not at all, built the iPhone myself, works perfectly fine on stock.

**Comment by cerebral-314** [comment]
At the very least you need to show the libs that were loaded durring one of the crashes. Come on man.  we aren't psychic.

**Comment by Gamr13** [comment]
A lot of the crashes were in Snapchat due to the camera thing I mentioned, where I had NoSub installed, so that would have been one of the libs and the other was Cydia Substrate. I'll post a log if I get another crash, but as of right now, I did a RootFS and fully erased the content & settings to start from scratch.

**Comment by cerebral-314** [comment]
I can tell you from experience, taptapflip causes problems, at least untill the dev addresses the issue.

**Comment by Gamr13** [comment]
A-ha, that would certainly have added to the issue, if not been the issue. That said, I don't think that would explain the crash reboots or resprings in apps were NoSub was enabled.

**Comment by cerebral-314** [comment]
I'm currently working on a perfect A12 jailbreak setup. No resprings, no funny behaivor, no processes running in the background eating up the battery...  I'm currently up to 88 tweaks with only one weird issue.  Only sometimes if face ID doesn't unlock from my face, the time disappears but the wallpaper stays, and the screen doesn't not want to shut off at this point.  I click power button, it goes off then back on with no clock showing.  This just started this morning so I'm still trying to find the culprit.

**Comment by Gamr13** [comment]
Odd, this time around I only installed tweaks that I actually use frequently (BioProtect, YouTube Tools, Spos, Clean Home Screen, etc) so I'll see if I have any crashes or instability from here on out. I know BioProtect seems to crash every time I jailbreak (leading to safe mode) but once I respring out of safe mode it's fine. I have around 102 packages installed at the moment and most of them have a green checkmark from tweakCompatible.

**Comment by cerebral-314** [comment]
I have noticed bioprotectx as being the source of a lot of issues and compromises I had to make.  I might just drop it all together.  It might actually be the cause of my latest issue.

**Comment by Gamr13** [comment]
BioProtect XS is made for iOS 12, X is for 11, give that a try and see if you have any other issues.

**Comment by cerebral-314** [comment]
Oh yeah, my bad.  Its bioprotectxs.  Type-o.   It just seems a bit flakie depending on what options you have enabled.

**Comment by Gamr13** [comment]
I kept my settings mostly stock, all I did was select the applications I wanted to protect and that was it

**Comment by cerebral-314** [comment]
That's what I'm doing now.  Protecting cydia or anything that can undo my jailbreak.   I have smart ass children who like to joke around in less then funny ways.   Bricking my phone being high on their list.

**Comment by cyntrifical** [comment]
Same thing happening to me too on iPhone 8 iOS 12.4 ,  also I cannot enable RSD Or it just hangs on respring and then reboot the phone but I have a respring constantly I’m talking 15 to 20 times a day and most of the time it catches on the rear spring and reboot the phone and I have to re-jailbreak again

**Comment by miguelr4720** [comment]
can some one please tell me how to fix this Respring Bug
