### ISSUE TITLE
Tweaks not working

### ISSUE THREAD

**Issue by blue638** [pwn20wndstuff/Undecimus#1519]
Installed multiple tweaks but they don’t show up in settings

**Comment by khouch13** [comment]
Hi, I found a solution to solve this issue.
Just add the source in Cydia: https://rpetri.ch/repo and proceed to upgrade. After the installation is complete, the tweaks will appear in Settings after a Respring.

**Comment by BuildNat** [comment]
I’ve just tried your solution but it’s no working for me. IOS 12.4 XR A12

**Comment by BuildNat** [comment]
after installing springotmize with the dependencies applist, the problem disappeared and I was able to find the settings of the tweaks in the application iphone settings. tell me if it works for you too.

**Comment by DarthPestilane** [comment]
I can't see tweaks in settings either.
I've installed PreferenceLoader, RocketBootstrap and Applist, but still not working.
IOS 12.1 XS A12.
