### ISSUE TITLE
A12 12.4 Can't install tweak injector

### ISSUE THREAD

**Issue by Smythius** [pwn20wndstuff/Undecimus#1522]
**Describe the bug**
On jailbroken iPhone XS on 12.4 when I open cydia I have an update for a package that is dependent on tweak injector. when I try to install tweak injector it always crashes my device to a black screen once I press "restart SpringBoard" and I have to press volume up/down then power to get my device to restart. I am then back at square one. I am unable to remove the package either. each time the device crashes when I reboot I have to jailbreak again and when I open cydia I am back where I started.

**To Reproduce**
1. jailbreak device
2. open cydia
3. search for/install tweak injector
4. press "restart SpringBoard"
5. crash

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: XS
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by khouch13** [comment]
Hi, I found a solution to solve this issue.
Just add the source in Cydia: https://rpetri.ch/repo and proceed to upgrade. After the installation is complete, the tweaks will appear in Settings after a Respring.

**Comment by Smythius** [comment]
Thank you good sir. You are my hero of the day!

**Comment by amernaik** [comment]
I love that man  too
