### ISSUE TITLE
Substitute Dummy not working on iOS 12.2 A12

### ISSUE THREAD

**Issue by alexmodrono** [pwn20wndstuff/Undecimus#1523]
**Describe the bug**
I don't really know where to file this issue so thought it would be best here as it might be a problem with unc0ver.

**To Reproduce**
1. Try to install **Substitute Dummy for Unc0ver** or any tweak that has it as a dependency.
2. Restart springboard.
3. Have fun while your phone screen turns into a cool and awesome black screen.

**Screenshots**
how the heck do I screenshot a black screen /s

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iPhone Xr
 - unc0ver Version: 3.7.0b1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by miguelr4720** [comment]
Hopefully it's fix soon
