### ISSUE TITLE
camera blurred out, wont take a picture

### ISSUE THREAD

**Issue by icanc0** [pwn20wndstuff/Undecimus#1525]
**Describe the bug**
whenever I open up the camera app, it shows up for 2 or 3 seconds, and then it's blurred out, the picture won't save if I tried to take one

**To Reproduce**
1. Go to the home screen
2. Click on camera
3. See error

**Screenshots**
nope

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: ipad mini 5 (ipad11,2)
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present in the latest version of unc0ver

**Logs**
nope, it's not a crash

**Comment by icanc0** [comment]
#1497 had a similar issue, but on a different ios version

**Comment by null64** [comment]
same in ios 12.4  XR, only to re-jailbreak make camera work.

**Comment by K9TSniper** [comment]
Some retard told everyone to do ldrestart on newterm2 by logging in as root to fix the  camera bug, i did that and i am stuck in respring loop, it is stuck on buffering sign on black screen. I tried doing hard reset, nothing worked. Now i am just waiting for the battery to die. I am on iPhone XR iOS 12.4

P.S. i didn't install any tweaks.

**Comment by stillxxdani** [comment]
Same issue on XS Max running IOS 12.4
I ran unc0ver with load tweaks option off and it worked fine.

**Comment by twaikel** [comment]
Same issue on iOS 12.for iPhone XR with the latest 3.7.0b1 build. Also occasionally a perpetual respring.  The only fix that I have found so far for either one of these is to reboot for the camera hard reset for the respring and not reapply the jailbreak.

**Comment by iVosey** [comment]
restore rootfs works but then i guess it depends what u install tweak wise after that

**Comment by twaikel** [comment]
Thanks.

**Comment by ghost** [comment]
> restore rootfs works but then i guess it depends what u install tweak wise after that

Not working with out any tweak …

**Comment by icanc0** [comment]
> Now i am just waiting for the battery to die. I am on iPhone XR iOS 12.4

u can force to shut it down btw
rejailbreak sometimes solves the issue, but sometimes it just doesn't

**Comment by twaikel** [comment]
I restored rootFS, re-jailbroke with Unc0ver3.7.0 and installed my tweaks one by one, trying the camera in between installs and it appears in my case the bug belongs to bioprotect XS
