### ISSUE TITLE
Iphone xs Jailbreak power off problem

### ISSUE THREAD

**Issue by activoss** [pwn20wndstuff/Undecimus#1528]
when i am to jaibreak status with uncover 3.7.0 and i decide to power off my iphone, when i do this the screen goes black and/ BUT the side button its not working. So we going in 2 results .                                                         1  results) 50%  of tries the iphone stay to black screen ( maybe its power off) and dont open again with the side button.Only if i do a hard reset can open it.( force restart).                                                 2 results) 50% of tries the iphone opens alone after about 2 minuites without press the side bottum . This happend only in jailbreak status        BUT if the iphone it is NOT in jailbreak status , the iphone power off and power on normaly......
1. Jailbreak
2. Power off iphone
3. Black screen
4. It opens alone after 2 minuites or if its not open alone , i must hard reset( force restart) it.

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device: iphone xs
 - unc0ver Version: 3.70

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ImVxping** [comment]
I put my phone in the frezzer for 2 hours straight, the battery was completly drained, then a pluged the phone, then I was fonctionnal

**Comment by mzxnbcv** [comment]
Same here iphone xs max ios 12.4

**Comment by realHyperMatrix** [comment]
Can confirm. Same phone/ios, same problem.

**Comment by kaimakes** [comment]
Same problem, XR, iOS 12.2

**Comment by Santacruz78** [comment]
Hi 
Same for me
When a i turn off my phone for using camera
« Camera don’t working with JB »
My iphone stay black until battery off.
And i can’t use my phone xs 
iPhone xs 12.4 Unc0ver 
Thx
