### ISSUE TITLE
Unjailbreak unc0ver jailbreak

### ISSUE THREAD

**Issue by nanpuhaha** [pwn20wndstuff/Undecimus#153]
How to unjailreak unc0ver jailbreak?
There are lots of guide to unjailbreak for Electra using SemiRestore11/Rollectra, but I couldn’t find any for unc0ver.

**Comment by DizzyDaz** [comment]
You can use SemiRestore11/Rollectra on Unc0ver too!

**Comment by Samgisaninja** [comment]
^what he said
