### ISSUE TITLE
Activator not Working A12

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1530]
Activator Not Working A12 Respring After Install 12.4 Unc0ver 3.7.0 Keep Getting Stuck Safe Mode after Installing From Ryan Petrich Repo

**Reproduce**
1. After Installing Activator
2. Respring
3. Getting In Safe Mode Get Error Activator Beta Not Compatible
4. Remove Activator Respring Safe Mode is Gone 

Please Fix this Problem A12 Jailbreak

**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: v3.7.0 Beta 1 A12 Cydia Supported

**{
  "packageId": "libactivator",
  "action": "notworking",
  "userInfo": {
    "arch32": false,
    "packageId": "libactivator",
    "deviceId": "iPhone11,8",
    "url": "http://cydia.saurik.com/package/libactivator/",
    "iOSVersion": "12.4",
    "packageVersionIndexed": true,
    "packageName": "Activator",
    "category": "System",
    "repository": "rpetrich repo",
    "name": "Activator",
    "installed": "",
    "packageIndexed": true,
    "packageStatusExplaination": "This package version has been marked as Working based on feedback from users in the community. The current positive rating is 100% with 12 working reports.",
    "id": "libactivator",
    "commercial": false,
    "packageInstalled": false,
    "tweakCompatVersion": "0.1.5",
    "shortDescription": "Centralized gestures, button and shortcut management for iOS",
    "latest": "1.9.13~beta5",
    "author": "Ryan Petrich",
    "packageStatus": "Working"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJsaWJhY3RpdmF0b3IiLCJkZXZpY2VJZCI6ImlQaG9uZTExLDgiLCJ1cmwiOiJodHRwOlwvXC9jeWRpYS5zYXVyaWsuY29tXC9wYWNrYWdlXC9saWJhY3RpdmF0b3JcLyIsImlPU1ZlcnNpb24iOiIxMi40IiwicGFja2FnZVZlcnNpb25JbmRleGVkIjp0cnVlLCJwYWNrYWdlTmFtZSI6IkFjdGl2YXRvciIsImNhdGVnb3J5IjoiU3lzdGVtIiwicmVwb3NpdG9yeSI6InJwZXRyaWNoIHJlcG8iLCJuYW1lIjoiQWN0aXZhdG9yIiwiaW5zdGFsbGVkIjoiIiwicGFja2FnZUluZGV4ZWQiOnRydWUsInBhY2thZ2VTdGF0dXNFeHBsYWluYXRpb24iOiJUaGlzIHBhY2thZ2UgdmVyc2lvbiBoYXMgYmVlbiBtYXJrZWQgYXMgV29ya2luZyBiYXNlZCBvbiBmZWVkYmFjayBmcm9tIHVzZXJzIGluIHRoZSBjb21tdW5pdHkuIFRoZSBjdXJyZW50IHBvc2l0aXZlIHJhdGluZyBpcyAxMDAlIHdpdGggMTIgd29ya2luZyByZXBvcnRzLiIsImlkIjoibGliYWN0aXZhdG9yIiwiY29tbWVyY2lhbCI6ZmFsc2UsInBhY2thZ2VJbnN0YWxsZWQiOmZhbHNlLCJ0d2Vha0NvbXBhdFZlcnNpb24iOiIwLjEuNSIsInNob3J0RGVzY3JpcHRpb24iOiJDZW50cmFsaXplZCBnZXN0dXJlcywgYnV0dG9uIGFuZCBzaG9ydGN1dCBtYW5hZ2VtZW50IGZvciBpT1MiLCJsYXRlc3QiOiIxLjkuMTN+YmV0YTUiLCJhdXRob3IiOiJSeWFuIFBldHJpY2giLCJwYWNrYWdlU3RhdHVzIjoiV29ya2luZyJ9",
  "chosenStatus": "not working",
  "notes": "iPhone XS not work Safe Mode "
}

**Comment by miguelr4720** [comment]
When is this going to be fix

**Comment by icanc0** [comment]
same thing, its prob a bug

**Comment by miguelr4720** [comment]
Yes hopefully pwn20wnds or Ryan Petrich they should fix this problem because Activator Works Fine A11 the bug appear to be A12

https://twitter.com/rpetrich


iOS 12.4

Please Notify him for he could Solve this Hope He does Lol.

**Comment by icanc0** [comment]
oh i installed a lower version of activator and it works in someway

**Comment by miguelr4720** [comment]
What version did you use

**Comment by DonPabloRP** [comment]
This is **not** on the unc0ver-team’s table. The developer behind Activator is Ryan Petrich - you just wrote that...
Chimera users are experiencing this problem too so it’s clearly not a bug or case for unc0ver specifically.

**Comment by miguelr4720** [comment]
Hope Ryan Petrich fix this soon

**Comment by souporshawn** [comment]
From what it sounds like, I should give up on my search for a way to get Activator working on my XS Max..? Or, are the posts above pointing out Unc0ver is not the developer & therefore, fixing Activator “...is not on the team’s table...”?

**Comment by 2JayCee** [comment]
> This is **not** on the unc0ver-team’s table. The developer behind Activator is Ryan Petrich - you just wrote that...
> Chimera users are experiencing this problem too so it’s clearly not a bug or case for unc0ver specifically.

Exactly this above. This thread should be closed since it isn't the Jailbreaks fault whatsoever.
