### ISSUE TITLE
Camera Not Working FB Messenger Camera 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1531]
Camera Not Working On Facebook Messenger When i am Video Chatting. Camera Stays Stuck 😡 on Connecting Video on my phone.

 I am able to see and hear the Person but i can't see my self stays stuck Video Connecting 

**To Reproduce**
1. Video Connecting Stuck FB Messenger
2. AUDIO WORKS
3. Only see the person am Video Chatting with

 - iOS Version: 12 4
 - iOS Device: iPhone XS Max A12
 - unc0ver Version: 3.7.0 b1

**Comment by icanc0** [comment]
check if the camera app is black outed too, if not, then its a facebook problem

**Comment by miguelr4720** [comment]
I wasn't having the problem after i Jailbreak leet me uninstall the app and reinstall it see what happens

**Comment by icanc0** [comment]
eheheh
i meant like the camera app itself, not the facebook app

**Comment by miguelr4720** [comment]
Un-Jailbrake and Re-Jailbrake should solve the problem with the camera no working

**Comment by miguelr4720** [comment]
Restoring rootfs only

**Comment by miguelr4720** [comment]
Mines is working now

**Comment by miguelr4720** [comment]
Mines was working for one day being Jailbroken now the same problem is back again hope Unc0ver is fixing this camera bug

**Comment by miguelr4720** [comment]
Solved New VersionB3
