### ISSUE TITLE
YouTube Tools Not Working A12 12.4

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1532]
`YouTube Tools` not working on iOS 12.4 
  "packageId": "com.yourepo.jpet26.youtubetools",
  "action": "notworking",
  "userInfo": {
    "arch32": false,
    "packageId": "com.yourepo.jpet26.youtubetools",
    "deviceId": "iPad8,3",
    "url": "http://cydia.saurik.com/package/com.yourepo.jpet26.youtubetools/",
    "iOSVersion": "12.4",
    "packageVersionIndexed": true,
    "packageName": "YouTube Tools",
    "category": "Tweaks",
    "repository": "jpet26 Source - YouRepo",
    "name": "YouTube Tools",
    "installed": "2.0",
    "packageIndexed": true,
    "packageStatusExplaination": "This package version has been marked as Working based on feedback from users in the community. The current positive rating is 100% with 5 working reports.",
    "id": "com.yourepo.jpet26.youtubetools",
    "commercial": false,
    "packageInstalled": true,
    "tweakCompatVersion": "0.1.5",
    "shortDescription": "Essential toolbox for YouTube app.",
    "latest": "2.0",
    "author": "Justin Petkovic",
    "packageStatus": "Working"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20ueW91cmVwby5qcGV0MjYueW91dHViZXRvb2xzIiwiZGV2aWNlSWQiOiJpUGFkOCwzIiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnlvdXJlcG8uanBldDI2LnlvdXR1YmV0b29sc1wvIiwiaU9TVmVyc2lvbiI6IjEyLjQiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOnRydWUsInBhY2thZ2VOYW1lIjoiWW91VHViZSBUb29scyIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6ImpwZXQyNiBTb3VyY2UgLSBZb3VSZXBvIiwibmFtZSI6IllvdVR1YmUgVG9vbHMiLCJpbnN0YWxsZWQiOiIyLjAiLCJwYWNrYWdlSW5kZXhlZCI6dHJ1ZSwicGFja2FnZVN0YXR1c0V4cGxhaW5hdGlvbiI6IlRoaXMgcGFja2FnZSB2ZXJzaW9uIGhhcyBiZWVuIG1hcmtlZCBhcyBXb3JraW5nIGJhc2VkIG9uIGZlZWRiYWNrIGZyb20gdXNlcnMgaW4gdGhlIGNvbW11bml0eS4gVGhlIGN1cnJlbnQgcG9zaXRpdmUgcmF0aW5nIGlzIDEwMCUgd2l0aCA1IHdvcmtpbmcgcmVwb3J0cy4iLCJpZCI6ImNvbS55b3VyZXBvLmpwZXQyNi55b3V0dWJldG9vbHMiLCJjb21tZXJjaWFsIjpmYWxzZSwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwidHdlYWtDb21wYXRWZXJzaW9uIjoiMC4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiRXNzZW50aWFsIHRvb2xib3ggZm9yIFlvdVR1YmUgYXBwLiIsImxhdGVzdCI6IjIuMCIsImF1dGhvciI6Ikp1c3RpbiBQZXRrb3ZpYyIsInBhY2thZ2VTdGF0dXMiOiJXb3JraW5nIn0=",
  "chosenStatus": "not working",
  "notes": "Settings blank"
}

**Comment by icanc0** [comment]
hehe my preferenceloader have an error loading youtube tools, is that ur problem? 
or its just won't work?

**Comment by miguelr4720** [comment]
It just wont work it needs to be updated idk if is the preference loader causing this?

**Comment by miguelr4720** [comment]
Yes Is the Preference Loader Error it needs to be Updated To Support A12

**Comment by icanc0** [comment]
heheh idk becuz some tweaks work, but it just doesnt show up in settings
