### ISSUE TITLE
EQE Not Working A12 12.4 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1533]
A12 Is not Supported

Only iPhone 8 or Plus
Only iPhone X 

12.4 A12 and iPad Pro Not Supported

ONLY WORKS A11 Devices Running Unc0ver

**Comment by miguelr4720** [comment]
Only iPhone 7 iPhone 8 or  + or any iPads Running A11 CPU

**Comment by miguelr4720** [comment]
It will work other Than A12 it wont Work

**Comment by jhon-lito** [comment]
Thank you! I waiting for eqe 🤩

**Comment by miguelr4720** [comment]
EQE For A12 Is Now Avalible 

Notice Please Use Filza to install DONT USE CYDIA to Inatall this New Program Download EQE Beta 2 A12 Enjoy
**HOW TO INSTALL EQE ON iOS 12**
Don't use the Cydia version.

unc0ver, Electra and Chimera are supported.

0. Install Filza and Debian Packager and coreutils and RocketBootstrap (RocketBootstrap from https://rpetri.ch/repo)
1. Copy/paste this link into Safari:  https://github.com/rweichler/EQE/releases/download/a12-beta2/eqe.deb
2. Open In/Copy to Filza (DON'T USE SILEO)
3. Tap on the file, tap Install, then Respring
4. Open MTerminal (or NewTerm) and type `uicache` and press enter (if you're on Chimera or Electra, do `uicache —all` instead) 
5. If you had an old install of EQE, reboot/rejailbreak. Otherwise the app will crash on launch.

The app should appear on your homescreen.

READ <#562891468600115229> BEFORE ASKING FOR HELP

**Comment by rweichler** [comment]
@miguelr4720 Your instructions are out of date. I would appreciate it if you simply linked to the Discord, which has up to date instructions.
