### ISSUE TITLE
Face ID not working on third apps (password use)

### ISSUE THREAD

**Issue by mzxnbcv** [pwn20wndstuff/Undecimus#1538]
Face ID doesnt work on any app which uses it set a password 

**To Reproduce**

1. Go to 'any app which uses Face ID instead of password'
2. Click on 'tap to authenticate with face id'

**Screenshots**
![0B74DE45-66C2-4944-9333-8ED28BBCD7C8](https://user-images.githubusercontent.com/55734594/65575472-22b01c00-df2d-11e9-818a-f5b96156d1cd.png)

**Device:**
 - iOS Version: 12.4
 - iOS Device: 11,6 iphone xs max
 - unc0ver Version: 3.7.0 b1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by alexmodrono** [comment]
I'm facing the same problem, I cannot enter WhatsApp because of this bug.

**EDIT**: now I also tried to download an app from the App Store and it also appears to be impossible.

@pwn20wndstuff

**Comment by realHyperMatrix** [comment]
Can confirm. Wrote detailed info on this problem in another thread:  https://github.com/pwn20wndstuff/Undecimus/issues/1536#issuecomment-534937130
