### ISSUE TITLE
Safari dont get any tweak injection 

### ISSUE THREAD

**Issue by mzxnbcv** [pwn20wndstuff/Undecimus#1539]
safari browser app will always be like in no jailbreak state

**To Reproduce**
1. Go to 'safari'

**Device:**
 - iOS Version: 12.4
 - iOS Device: 11,6 iphone xs max
 - unc0ver Version: 3.7.0 b1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by realHyperMatrix** [comment]
Can confirm. Safari Plus functionality not present when safari is opened.

**Comment by richwincott** [comment]
Pwn has tweeted about this and confirmed it will be fixed in the next release
