### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by willyaako** [pwn20wndstuff/Undecimus#154]
iOS version: 11.3.1
iDevice model: iPhone 8
unc0ver version: 2.0.2

When I open "Gogoro" App 
It stucked in the launch screen and crash about 10 seconds.

If I rename or remove tweakloader.dylib
It will be okay, but other tweaks will not work.
Can fix it? Thanks ~

**Comment by Cryptiiiic** [comment]
@willyaako try disabling tweaks one by one until it doesn't crash, then you can figure out which tweak is causing this. This most likely has nothing to do with unc0ver but rather a tweak you have.

**Comment by willyaako** [comment]
@Cryptiiiic It also happened on electra when I remove all tweak, too.

**Comment by ienthach** [comment]
may be it have jailbreak detection, "STC Pay" also crash if there is one tweak is injected. 
@pwn20wndstuff  could you make jb detect bypass for this kind of app?

**Comment by Samgisaninja** [comment]
https://translate.googleusercontent.com/translate_c?depth=1&nv=1&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://hiraku.tw/2018/04/4720/&xid=17259,15700023,15700124,15700126,15700149,15700186,15700191,15700201,15700237,15700242&usg=ALkJrhhUj2qIASNFJuQZDU-sqs67jiANaQ

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb
