### ISSUE TITLE
Restore RootFS sometimes hang

### ISSUE THREAD

**Issue by palxex** [pwn20wndstuff/Undecimus#1542]
**Describe the bug**
The restore rootfs function sometimes will hang there. 

**To Reproduce**
1. Jailbreak
2. Restore rootfs
3. Repeat 1-2, after several times( for me about 5 times ) the restore rootfs( not the jailbreak ) may hang.
I'm sure the hang is happened in renaming stage, since the the last log line is 'Archiving ...'.
After that happened, I force resetted the device, and re-restore works. Seems the possibility is very low.

**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device: iPhone XR
 - unc0ver Version: 3.7.0b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
Not sure.
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
Not sure. The restore should be atomic.
 - [x] this issue is present on the latest version of unc0ver

**Comment by realHyperMatrix** [comment]
Can confirm. Same issue with iPhone XS Max on 12.4.

**Comment by abigchopstick** [comment]
It doesn't actually hang, just sometimes it takes too long, maybe an hour or so.
I am using XR 12.4, and the first time i tried this I waited 20 mins, eventually I saw a post on reddit, quit unc0ver and start over the process again, it worked in just a few minutes.

But second time it wasn't so lucky, I only waited for like 5mins, and did the same thing like first time, but every time it end up not working. Until before I go to bed at night I tried again, and it worked the next day morning when I checked. My guess is the max time it could take is like one or two hours, so the best time to restore rootFS is probably when you are going to sleep.

So all I can say is, it didn't hang, just some process takes longer, and in cases where it did go wrong, it will restart the iPhone itself or  hang at shutting down (black screen with back light).

Even shutting down sometimes isn't hanging I think, it just take much, much longer, and this is all random now, you don't know what went wrong, perhaps there are logs that can be reviewed by the developer but definitely not us.

**Comment by palxex** [comment]
Lets separate reasons.
In my knowledge, restore rootfs has two stage:
1. Archiving rootfs modifications 
2. Restore snapshot.

In this issue only stage1 is being discussed.

And in both stage, when export tfp0 not toggled, has 2 step:
1. (re)jailbreak
2. do the actual job.

In the jailbreak step, there’re racing, may takes long time, maybe fail or reboot, that’s OK, all of us knows that. But in the stage1 step2( we can identify that through log, thanks to the design), the achieving operation should be trivial task, and should costs constant time instead of random( since other bug I reported, my cydia refuse to work, so total modifications are constant). That’s why I cannot imagine the long time consuming could be normal. 
For the log, since I’ve only triggered it once, and that time whole phone was almost locked( cannot return home through bottom ), so no screen shot was taken. What I can remember is jailbreaking stage has been done(get tfp0/unsandboxing/platforming/etc), log was Archiving many place and stuck somewhere, last line not remembered but also beginning with Archiving.
