### ISSUE TITLE
 Camera not working after jailbreak iOS 12.4 A12 iPhone XS Max device

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1544]
Is anybody else having issues with the camera iPhone XS Max after jailbreaking with uncover ? My camera app stopped working after jailbreak . Help !!

https://www.reddit.com/r/unc0ver/comments/d7z7gr/camera_not_working_after_jailbreak_ios_124_a12/

I See more People are Having this Bug on the Camera While being Jailbroken

Pwn20wnd Please Fix This Problem 

ASAP PLEASE

**Comment by ColonelAnguss** [comment]
Same here. It works just fine on FaceTime calls. It’s both the front and rear camera, just shows either a fuzzy frozen frame of what I was trying to take a picture of or just a black screen.

**Comment by Proxyworm** [comment]
confirming this, XSmax 12.4

**Comment by marcowind80** [comment]
Xs max 12.4 same here, please fix it

**Comment by maxsmoothred** [comment]
Same problem here. I jail broke it again and the problem disappeared for a little while but it’s back again. :(. 12.4 Xs Max

**Comment by govegan88** [comment]
I’m having the same issue but can’t even FaceTime or use any apps that use the camera. 

XR 12.4

**Comment by maxsmoothred** [comment]
I just used a method suggested by someone else having the same issue.  Reboot your phone, take a few pictures and then rejailbreak your phone.  Now my camera works!  Good luck

**Comment by govegan88** [comment]
I just tried this and it did absolutely nothing.

**Comment by maxsmoothred** [comment]
Well, it worked last night but I’m right back where I was 😒

**Comment by Heftydose** [comment]
Same here i used ldrestart but it goes back everytime:(

**Comment by ZeRoNiX164** [comment]
Same problem with Uncover. The touch is not working while the Camera App is running.

**Comment by Dark3n3rgy** [comment]
Same problem here, camera opens and looks fine but then the screen is blurry as if the camera is out of focus. This happens every time I open the camera app

**Comment by Dark3n3rgy** [comment]
My issue was fixed immediately thanks to this video.         https://youtu.be/nwlHaKPXWxY
Quick Tutorial:
1) DL PowerSelector via Cydia
2) run ldRestart via power down menu (tap slide to power off to cycle options. 
3)After restart issue was solved
 This is only temporary and would have to be ran after every jailbreak

**Comment by maxsmoothred** [comment]
That didn’t work at all for me Dark3n3rgy 🤷‍♂️

**Comment by intramorph** [comment]
That’s only a temporary fix. DL PowerSelector 
If it even works it’s only for a while. Hopefully pwn pushes 
An update soon

**Comment by m1337v** [comment]
Same here on iPhone 8 (12.1.1 u0 3.7.0~b1). It looks like it is working but I cannot zoom and it doesn't save any images.

Edit: Ldrestart did not fix the issue, but it works in safemode. No problems on IPX (12.4 Chimera...)

**Comment by Santacruz78** [comment]
Hi
Same for me
iPhone xs 64gb 12.4 Unc0ver jb
Camera Freeze or Black and your issue ldrestart doesn’t work 
Appstore downloading no work
Weather location no work

We wait 
Thx

**Comment by evllo01** [comment]
Xs max 12.4 same here, please fix it

**Comment by dsammuzaki** [comment]
Yes this issuse is happen to me tho, please fix it soon

**Comment by Jonnyrouge** [comment]
Go into settings in the uncover app and jailbreak it with reload daemons disable. 

Fixes all issues.

**Comment by Santacruz78** [comment]
Thx jonnyrouge
But don’t work for me
Same bug
Xs 12.4 Unc0ver

**Comment by Santacruz78** [comment]
But this issue fix my bug for appstore downloading
Before i can’t download any app in appstore
But nowvit’s ok
So thx lot

**Comment by abigchopstick** [comment]
Same problem here, judging from the time pwn2wnd releases version, this could take 20-30 days, and last release time is 9/22, let's wait until 10/12th, heard that he already knew the cause...hope it finds the best cure this time and thanks to his hard work to make this all possible.

Some of the tweaks are just really good.

**Comment by leroy023** [comment]
I had this problem. I rebooted my iPhone XS Max and it ceased to be an issue.

**Comment by abigchopstick** [comment]
Did you notice that after reboot your phone is in unjailbroken state or did
you mean a simple reboot and rejailbreak take away your problem after
running unc0ver?

**Comment by Jonnyrouge** [comment]
I mean your phone needs to be in an unjailbroken state and then only check off reload daemons and then jailbreak.

This doesn’t fix everything for everyone apparently but it helps/fixes most.

-Devin Miller

On Oct 6, 2019, at 4:42 AM, abigchopstick <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you notice that after reboot your phone is in unjailbroken state or did
you mean a simple reboot and rejailbreak take away your problem after
running unc0ver?

**Comment by abigchopstick** [comment]
> I mean your phone needs to be in an unjailbroken state and then only check off reload daemons and then jailbreak. This doesn’t fix everything for everyone apparently but it helps/fixes most.
> -Devin Miller On Oct 6, 2019, at 4:42 AM, abigchopstick <notifications@github.com<mailto:notifications@github.com>> wrote: 

Nah, doesn't work for me. Apparently Pwn20wnd already has the fix, according to twitter he just wants to be more thorough, so just wait a few more days, not a big deal.

**Comment by sTuP1Dant** [comment]
same problem as my mini5 12.2
hope fixed version soon

**Comment by mrc1973** [comment]
Same for me, IPhone XR, IOS 12.1.2

Camera stops working, Touch ID for AppStore stops working, and GPS stops working.

DL powerselector fixes the camera but not the other bugs.

**Comment by Santacruz78** [comment]
What a great job
With update unc0ver 3.07 b3 all bug fix it...
I’m so happy
Wonderfull!!!!

**Comment by acidart** [comment]
.:[ FaceID & Camera Fix iPhone XR iOS 12.4 ]:.

 I had the same [blurred or black screen] camera problems with my IPhone XR iOS 12.4 until just a minute  ago.

# My Solution to Camera & FaceID XR problem:

1• I downloaded PowerSelector from Cydia and did a LDRestart and followed up with the IUCache command.
(This didn’t fix the problem though)
Luckily Unc0ver released their 3.0.7~b3 new  update simultaneously as I tried to fix this problem. 

2• Download and install the newest version of Unc0ver. 
* After updating Unc0ver I had a few problems with re-jailbreaking again and tried a couple of times and methods.

3• I had to to turn my phone [Off] & [On] to do a successfully re-jailbreak again.

4• I then did the same procedures in PowerSelecor [LDrestart] & [UICache].
• Solved •
After the UICache respring both back/front Camera included FaceID was fixed. 

—- • \O/ • —- 

*  I can’t deny or approve if the the Unc0ver 3.07 update solved this problem on its own, as I never tried the camera between re-jailbreaking it and doing the “LDrestarting/UICache” procedures.
——-

Much respect and a big thanks to all of the Unc0ver team and every jailbreak/tweak devs here.!.
