### ISSUE TITLE
Again.... TIA

### ISSUE THREAD

**Issue by royalty505** [pwn20wndstuff/Undecimus#155]
I’m not trying to bash or be in annoying person,  I have deleted the app, read downloaded, ran the utility, literally left it overnight, and it just stays in a boot loop. Where is the best source to download an official copy of unc0ver?  Is there something in the settings that need to be changed?

**Comment by Samgisaninja** [comment]
The only official source for unc0ver is our [releases page](https://github.com/pwn20wndstuff/Undecimus/releases). The only official way to sign multipath is by using Cydia Impactor with an Apple developer account 

Signing services may be used to get multipath for free, but Apple revokes these constantly and we cannot provide support. 

This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb
