### ISSUE TITLE
Cannot Rejailbreak on my iPhone 8+

### ISSUE THREAD

**Issue by NakadashiS** [pwn20wndstuff/Undecimus#1551]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
Stops jailbreak process at 19/30 and gives this.
**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'Re-Jailbreak'
4. See error at 19/30

**Screenshots**
![image](https://user-images.githubusercontent.com/55870318/65752797-64260000-e0c2-11e9-8fe1-8af01a55b488.png)

**Device (please complete the following information):**
 - iOS Version: 11.2.6
 - iOS Device: iPhone 8+
 - unc0ver Version: Undecimus v3.6.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
Archive: skipping directory: ./Library/MobileSubstrate/DynamicLibraries/
Processing ./Library/MobileSubstrate/DynamicLibraries/mmaintenanced_hook.dylib
./Library/MobileSubstrate/DynamicLibraries/mmaintenanced_hook.dylib: OK
Processing ./Library/MobileSubstrate/DynamicLibraries/mmaintenanced_hook.plist
./Library/MobileSubstrate/DynamicLibraries/mmaintenanced_hook.plist: OK
[ * ] Successfully copied over resources to RootfFS.
[ * ] Removing /var/lib/dpkg...
[ * ] Unable to repair dpkgg status file.
[ * ] Progresss; Repairing filesystem...
[ * ] Unplatformizing...
[ * ] Sandboxing...
[ * ] Downgrading host port...
[ * ] Restoring shenanigans pointer...
[ * ] Deallocating ports...
[ * ] Deallocating Memory...
[ * ] Status; Jailbroken

**Comment by aggelosy** [comment]
Try restoring RootFS and try again.

**Comment by NakadashiS** [comment]
RestoreFS gives an error. "Unable to sync/"

**Comment by nonspin** [comment]
Use any other version than v3.6.2. I'd recommend v3.6.1 or v3.6.0.

**Comment by NakadashiS** [comment]
Problem still persists on v3.6.0. Tried restoring RootFS and re-jailbreaking and same error appeared again.

**Comment by zhengling** [comment]
Before Restore RootFS, reboot the iPhone firstly

**Comment by bobzerrr** [comment]
Same problem for me, unc0ver 3.6.3 ipa crashes at the very first step.
Solution: I used my old 3.5.6 ipa.
