### ISSUE TITLE
How to use it for APP debugging?

### ISSUE THREAD

**Issue by Imzpy** [pwn20wndstuff/Undecimus#156]
I found that I can't use the command,
Debugserver *:23333,
It can't wait for lldb debugging.
Or use such a command,
Debugserver -x backboard *:22222 /Applications/Calculator.app/Calculator
, it can't let the app wait for debugging.
Can you help me?
Many thanks

**Comment by Cryptiiiic** [comment]
Try
`debugserver localhost:6666 -a PID` then try and connect via lldb on your computer. 
```lldb
platform select remote-ios
```

**Comment by Cryptiiiic** [comment]
Closing this due to the user not responding and being on a completely different jailbreak...
