### ISSUE TITLE
Massive battery drain even with all tweaks disabled

### ISSUE THREAD

**Issue by Akasuo** [pwn20wndstuff/Undecimus#1565]
Battery is draining like hell even without any tweaks enabled. All the processes in CocoaTop are not spiking up (besides the stock ones, like aggregated). I cant do anything to make the drain stop. Tried rootfs and didnt work. Please do something, is unusable. I get only 4 hours of uptime. IPS Energy is always in the top of the battery drainers. Searched reddit and everybody got the same problem.
 - iOS Version: 12.4
 - iOS Device: Xs Max
 - unc0ver Version: 3.7.0b1

 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver.

**Comment by cerebral-314** [comment]
Try switching to beta2.  its best for A12 devices.

**Comment by 2JayCee** [comment]
Check with System Info and enable System Daemons to see what is draining your battery.
