### ISSUE TITLE
Bug/Error XS Max 12.4

### ISSUE THREAD

**Issue by WayneBishop1** [pwn20wndstuff/Undecimus#1567]
**Describe the bug**

When i jailbreak it wont start substrate
Also if i have to power off my phone it wont jailbreak again until i restore rootfs so basically
i need to restore rootfs everytime i need to jailbreak :(

**Device (please complete the following information):**
 - iOS Version: 12.4 
 - iOS Device: iPhone XS Max
 - unc0ver Version:  v3.7.0%b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Comment by chorim** [comment]
Hello, I also not started substrate.

But, I found solution.

How about reset configure of your phone?

This process will be lost your iphone data. But installed app's will remaining.

Step 1) Tapped "Settings > General > Reset > Reset all settings"

Step 2) Trust your installed certificate "Settings > General > Device Management"

Step 3) Turn off the siri. "Settings > Siri"

Step 4) Run unc0ver app. And turn on Restore rootfs, Reload daemon. And etc ( disable autoupdate, disable revokes, boot nonce...)

Step 5) Tap on Jailbreak button. Your iphone will be restart of 2 times.

Step 6) After 2 times reboot, Turn off restore rootfs and reload daemons. Then, tap on jailbreak button.

Step 7) Your iphone will be reboot and jailbreaked. If not jailbreaked, Please retry to step 4.

**Comment by WayneBishop1** [comment]
Thanks but i lost my jailbreak :(
I had a bootloop from deleting the wrong files so had no choice but to update to ios 13 :(

**Comment by cerebral-314** [comment]
That's a real bummer bro.  All you had to do was hold down the power and volume up button to unload all tweaks.   Can I ask you if you had loaded any pirate repos before this happened?   Using certain pirate repos can cause the jailbreak to freak out and go into what looks like a bootloop.  This is done on purpose to stop people from pirating paid for apps. Once you remove the repo the phone boots up just fine.  The more you know right?  so sorry for you.

**Comment by WayneBishop1** [comment]
No I brought all my tweaks.
Luckily I have a iPhone 7 I can use most of them on so not wasted my money except for a couple that only work on the Xs max lol
It was a proper bootloop as I put it in dfu mode then rebooted it and it still stayed on the apple logo I also tried the connect to iTunes mode and that didn’t kick it out either so had no choice but to update to the latest version :(
