### ISSUE TITLE
Spinning wheel forever after respring

### ISSUE THREAD

**Issue by 877cms** [pwn20wndstuff/Undecimus#157]
**Issue:**
Spinning wheel forever, more dimly lit than normal and backlight is on. Have to force restart (vol+ vol- power)

**Device & versions:**
iPhone 8 (10,4) on ios 11.3.1
Unc0ver v2.0.2 (previously used Electra)
CarBridge 1.0.2

**How to replicate:**
Install a tweak which requires a respring (Platinum safari tweak) sometime causes this.
Press respring after Springboard crashes (normally while using CarBridge) virtually always causes this.

**Further info:**
This is also related to issues #110  and #142 but it seems quite different as I can replicate the issue, and is not only related to CarBridge issues.

**Comment by 877cms** [comment]
Reserved for crash log information

**Comment by Cryptiiiic** [comment]
@877cms Please remove all of your pirated tweaks, apps, and packages. I'm telling you this not because it's piracy but because those packages usually cause lots of issues such as various crashes.

**Comment by 877cms** [comment]
@Cryptiiiic thanks I will get it to crash again tomorrow when I'm in the car, then get the logs and post here asap.

Regarding pirate tweaks, I do have the xarold repo for Cydown, Movie Box, TSS Saver and Youtube Tools. I can't see them on legit sources, maybe I should look again. CarBridge is genuinely purchased by me and I do tend to purchase any good tweaks. I do have Spotify++ installed though which I sideloaded.

I take your point that these apps/tweaks could be the issue, and will try installing them for now...
Thanks

**Comment by Cryptiiiic** [comment]
@877cms Yah the pirate repo is overriding the correct repos, so I suggest removing it. TSSSaver app is from [](https://repo.nullpixel.uk/). CarBridge is from chariz.

**Comment by 877cms** [comment]
@Cryptiiiic oh right that's not good then..

Cydown - removed
Movie Box - removed
TSS Saver - reinstalled from proper nullpixel repo
Carbridge - already installed from proper Chariz repo
Youtube Tools - reinstalled from proper repo.packix.com 
Removed Xarold repo form sources

![2018-12-14 20 03 57](https://user-images.githubusercontent.com/28159761/50024811-79221e80-ffdb-11e8-96de-0564cf5a8b9d.png)

Will be a shame to lose Spotify++ if that is also a cause...

**Comment by Cryptiiiic** [comment]
@877cms I doubt a sideloaded app is the issue.

**Comment by 877cms** [comment]
@Cryptiiiic  I hope so, I will have to wait and see if the CarBridge issues continue as I normally use Spotify in the car. Below is my current list of repo's, nice and clean hopefully..

I'll update this issue immediately upon the next crash. many thanks!

![2018-12-14 20 07 44](https://user-images.githubusercontent.com/28159761/50025106-5a705780-ffdc-11e8-9a86-7886da87be18.png)

**Comment by Samgisaninja** [comment]
If you jailbreak with no tweaks installed (or with them disabled in iCleaner Pro), does it still hang?

**Comment by Cryptiiiic** [comment]
@877cms Is this issue resolved?

**Comment by 877cms** [comment]
@Cryptiiiic not had a crash since removing the dodgy repos, but only used my car today. As I will be commuting could I give it a more thorough try over the next few days before closing plz?

**Comment by soum91** [comment]
I can for sure tell that Safari Plus causes the infinite respring loop. I had this issue with Electra and figured it, later forgot about it. Then again when I had new tweak setup due switching to unc0ver, I reinstalled Safari Plus since it was out of my mind. So opened the #110 thinking of it being caused by unc0ver. Later I figured it once again when went uninstalling tweaks one by one. Never had since I removed it. 

I don’t know if you had Safari Plus installed before but if you had, certainly it was being caused by that, @877cms. If you didn’t, then maybe it’s being caused by something else.

**Comment by Cryptiiiic** [comment]
@soum91 @877cms Upgrade to unc0ver v2.1.0. Also install substrate from saurik's beta repo.

**Comment by 877cms** [comment]
Hi @soum91 never had Safari Plus installed myself.

@Cryptiiiic I will do this and report back when/if I next get a crash. Or in the next few days either way 👍🏻

**Comment by soum91** [comment]
@Cryptiiiic I don’t why my device acting weird with the substrate. The device locks it up all of a sudden. Display goes off and iPhone becomes unresponsive as if it’s turned off(though I’m not sure if it actually is), no buttons work, no charging chime. It’s the same freezing with screen turned off. Only force reboot works.  Had such 3 freeze. With 2 I forced rebooted and with last one, I left it alone to see what happens but kernel panicked. On subreddit I have seen others are encountering this. I tried to make Saurik aware of this but failed I guess. Currently resorted back to substitute. With latest unc0ver resources the substitute is really stable, had 4 days uptime.

Then something else maybe, @877cms. I really hope you don’t have to face ever again.

**Comment by 877cms** [comment]
@soum91 sounds like a real pain, maybe raise a separate issue to get some help?

@Cryptiiiic I've updated to unc0ver 2.1.0 and Sauriks substrate so will let you know how it goes over the next couple of days - thanks

**Comment by soum91** [comment]
@877cms, someone has already opened issue #145 regarding this but I don’t think it’s unc0ver relateded, instead the problem is itself with the substrate update.

**Comment by 877cms** [comment]
All seems good after a few days and no crashes, so closing issue. 

Many thanks @Cryptiiiic 👍🏻
