### ISSUE TITLE
iPad Airdrop not working after jailbreak with latest release. 

### ISSUE THREAD

**Issue by seanskii** [pwn20wndstuff/Undecimus#1570]
**Describe the bug**
I have an iPad Pro 10.5in running on iOS 12.4 and my airdrop no longer works after jailbreaking. Doesn’t show up on other devices and is unable to see devices nearby. 

**Device (please complete the following information):**
iOS Version: 12.4
iOS Device: iPad Pro 10.5 in
unc0ver Version: v3.7.0~b1

**Place an "x" between the brackets if true:**
  this is a bug others will be able to reproduce
  [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
  [x] this issue is present after a rootfs restore
  [x] this issue is present on the latest version of unc0ver

**Comment by seanskii** [comment]
Why was it closed? LOL

**Comment by Cryptiiiic** [comment]
Over 30 days old and 3.7 is outdated
