### ISSUE TITLE
Localized String not found in Passwords and Accounts 

### ISSUE THREAD

**Issue by Juestrix** [pwn20wndstuff/Undecimus#1572]
**Describe the bug**
There seems to be an issue with the top menu displaying the correct link names.
![8D0F1916-8C51-4AB8-8066-7482E3E79CE6](https://user-images.githubusercontent.com/15260073/66781411-e8bca080-ee6e-11e9-9190-050e910cd285.jpeg)
 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Passwords and Accounts'
3. Scroll down to 'n/a'
4. See on top navigation ‘localized string not found + localized string not found‘

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: 3.7.0~b2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Randomblock1** [comment]
Unc0ver latest, iPhone 6, 12.4
Can not reproduce, still works fine even with my Dark Mode tweaks in Settings

**Comment by Juestrix** [comment]
I’m going to assume this is A12 related. It does not affect functionality. Will restore RootFS and see if I can reproduce after a fresh start.

**Comment by Juestrix** [comment]
Installed unc0ver 3.7.0~b3, seems the issue is resolved in this version.
