### ISSUE TITLE
sbreload takes up 100% of all CPU power draining battery

### ISSUE THREAD

**Issue by abigchopstick** [pwn20wndstuff/Undecimus#1577]
iPhone XR 12.4 Jailbroken on 3.7.0.b3, installing tweaks I had to respring a couple times and it seems that the sbreload is stuck in memory and runs forever with 100% CPU occupancy
. 
Please check the cocoatop image attached.

So far a reboot and re-jailbreak seems to solve the problem and not sure if it will happen again.

**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device:  iPhone XR
 - unc0ver Version: 3.7.0~b3

![WechatIMG168](https://user-images.githubusercontent.com/24934554/66846266-2b33c980-efa4-11e9-839e-9fe3ce864100.jpeg)

**Comment by julien10** [comment]
I'm on the exact same configuration (iPhone Xr 12.4 jailbroken with unc0ver 3.7.0~b3), and I also have battery issues that seem to be linked to sbreload.
However, I only had one instance running, but at 100%.

I just killed the process, I'll see if this decreases the negative impact on the battery.

**Comment by cerebral-314** [comment]
If you are running an A12 device. Use unc0ver 3.7.0~b2.  It completely fixes these issues.

**Comment by Texlo-Dev** [comment]
> If you are running an A12 device. Use unc0ver 3.7.0~b2. It completely fixes these issues.

Hmm. sbreload, when using zebra package manager, still hits 100% for me. On b2.

**Comment by cerebral-314** [comment]
Then its a tweak causing this behavior.
