### ISSUE TITLE
iMessage not working on unc0ver v3.7.0~b3

### ISSUE THREAD

**Issue by Pundainayai** [pwn20wndstuff/Undecimus#1581]
**Describe the bug**
iMessage works properly on wifi, but when I use it on data it randomly stops working. Temporary fix would be to LDRestart or reboot then jailbreak

Worked fine on beta 1

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: v3.7.0~b3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Xerillic** [comment]
Same problem, currently can’t be jailbroken because I've had to reboot my phone several times to send an important message. 
Edit: several different occasions*

**Comment by cerebral-314** [comment]
I can not recreate this bug. 

    iOS Version: 12.4
    iOS Device: iPhone XS Max
    unc0ver Version: v3.7.0~b3

**Comment by Pundainayai** [comment]
Yeah because it randomly happens. Go on with your days on data, you will be able to recreate this bug

Sent from my iPhone

On Oct 17, 2019, at 10:07 AM, cerebrallolzy <notifications@github.com<mailto:notifications@github.com>> wrote:


I can not recreate this bug.

iOS Version: 12.4
iOS Device: iPhone XS Max
unc0ver Version: v3.7.0~b3

**Comment by cerebral-314** [comment]
Try using the unc0ver 3.7.0~b2.  If you have an A12 device you need to be on this version anyway.  I moved down to beta 2 and its cleared up all my issues.

**Comment by Pundainayai** [comment]
Will try

**Comment by Pundainayai** [comment]
Can’t find it

Sent from my iPhone

On Oct 18, 2019, at 3:59 AM, cerebrallolzy <notifications@github.com<mailto:notifications@github.com>> wrote:


Try using the unc0ver 3.7.0~b2. If you have an A12 device you need to be on this version anyway. I moved down to beta 2 and its cleared up all my issues.

**Comment by cerebral-314** [comment]
https://github.com/pwn20wndstuff/Undecimus/releases/tag/v3.7.0%25b3
Look near the bottom of the page.  In blue text. If you still dont see it click the arrow next to "Assets"

**Comment by Pundainayai** [comment]
Thanks

Sent from my iPhone

On Oct 18, 2019, at 10:11 AM, cerebrallolzy <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/pwn20wndstuff/Undecimus/releases/tag/v3.7.0%25b3
Look near the bottom of the page. In blue text.

**Comment by DIMEBAG79** [comment]
Does anyone no how to get back to 3.7.0 b2? I can’t find the link!

**Comment by 2JayCee** [comment]
I also just recently started having this problem. Rejb hasn't fixed this issue for me.  So far, only Facetime & iMessage have issues on b3.
