### ISSUE TITLE
sleep alarm does not ring(b3,12.4,xr)

### ISSUE THREAD

**Issue by xuqiu** [pwn20wndstuff/Undecimus#1582]
**Describe the bug**
The sleep alarm does not ring(no sound but showed on screen)
normal alarm work well
**To Reproduce**
1. set up sleep alarm
2. wait till week up time
3. alarm triggered with no sound

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device:  XR
 - unc0ver Version: 3.7.0 b3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cerebral-314** [comment]
Try using unc0ver Version: 3.7.0.b2.  Its meant for A12 devices.

**Comment by xuqiu** [comment]
It works all good now. 
not sure  it  happend first time or  I made mistake
