### ISSUE TITLE
Camera still doesn't work on Beta 3

### ISSUE THREAD

**Issue by m1337v** [pwn20wndstuff/Undecimus#1584]
**Describe the bug**
Whenever I open the camera I can sometimes see through the camera, sometimes it's just a black screen. I can't zoom and I can't take any pictures or videos except screenshots and recordings. On my iPhone X (Chimera) with exactly the same tweaks this doesn't happen. In safemode/all tweaks disabled this doesn't happen.

**To Reproduce**
1. Go to Camera (either on LS or the app)
2. Try to zoom or take a picture
3. Nothing happens

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone 8
 - unc0ver Version: 3.7.0 beta 3

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Comment by cerebral-314** [comment]
Mine works fine. Perhaps you have a conflicting tweak installed?

    iOS Version: 12.4
    iOS Device: iPhone XS Max
    unc0ver Version: 3.7.0 beta 3

**Comment by m1337v** [comment]
Could fix camera by disabling Eclipse X. Well it used to work with Eclipse enabled
