### ISSUE TITLE
Internet Accession 

### ISSUE THREAD

**Issue by MKSTAFF95** [pwn20wndstuff/Undecimus#1586]
My jailbreak apps can’t access to internet such installer 5 and Zebra within My net is good 
Also I getting  error messages that my device isn’t connected...these problem appears with some Appstore Apps but in this case I must be reboot my device to get rid the jailbreak to show selection window told me what’s I want to connects to internet (WALN & WiFi , WiFi Only Or Off ) because this window Don’t appears with jailbreak Mode ....I had to use a VPN App  to be able to install tools from Cydia but it stills shows the message Host Unreachable when trying to update the sources
My Following device info
-iOS 12.4 iPhone11,6 D331pAP T8020
Use Unc0ver 3.7.0~b3 
I hope  to read  bug and solve it ASAP

Big thanx to uncover team for hard work.

**Comment by cerebral-314** [comment]
Im not sure I entirely understand you. But.  I would try restoring rootFS and then reinstalling cydia. 
Also.  If you are on an A12 device, you need to use unc0ver 3.7.0~b2 instead of beta 3.

**Comment by MKSTAFF95** [comment]
I was tried all methods no way to solve this bug ...becauce it coursed by unc0ver code ...and need to solve by Pwn20wnd

**Comment by cerebral-314** [comment]
Did you try using 3.7.0~b2?   You have an A12.  A12 runs weird on beta 3.

**Comment by cerebral-314** [comment]
I have the same phone you do.  mine works fine with beta 2

**Comment by palxex** [comment]
Same problem. Both cydia and zebra complains no internet. b3, still have exactly same problem. XR.
EDIT: b2 tested too, same problem also exist. Plus safari cannot open.
[My issue](https://github.com/pwn20wndstuff/Undecimus/issues/1540) has screenshots.

**Comment by cerebral-314** [comment]
To be totally honest. It sounds like you have a faulty Phone.  Either the sim or the radio itself.  You seem to be the only person with this issue. Does this work without the jailbreak enabled?

**Comment by MKSTAFF95** [comment]
Yub I had to update to iOS 13.1.3 hoping go get stable version from unc0ver jailbreak ASAP.

**Comment by palxex** [comment]
Finally found the solution. 
I guess you also buy the iPhone from apple store that isolated inside Chinese mainland. That special model has a strange rule, every app have to ask user to link to internet. AND Cydia/Zebra does NOT obey this rule. That means you need to manually goto settings and allow them connects to Internet.

**Comment by nonspin** [comment]
The SIM-Lock Window (Unlock) is probably not showing  .. is it ?

**Comment by MKSTAFF95** [comment]
Oh man the apps totally don’t appers in settings to set manually....

**Comment by palxex** [comment]
@MKSTAFF95 if you can read Chinese, see https://juejin.im/post/5d5d1934f265da038f481238. 
The key is install openssh in unc0ver( not in cydia since it does not work ), then ssh into the device and 
`rm /var/preferences/com.apple.networkextension{,.necp,.uuidcache}.plist`

**Comment by MKSTAFF95** [comment]
You have been too late to publish  this comment as I have updated to the latest version... and  will be wait to a new jailbreak with coolstar he is wark professionally ... thanks for any one tried to help me ...

**Comment by cerebral-314** [comment]
The issue is that you will have the same problem even if you use an updated jailbreak.  You will still need to edit the property list in order for any jailbreak tweaks to communicate.   Blame your country bro.

**Comment by MKSTAFF95** [comment]
I will save all comments if i need it.

**Comment by palxex** [comment]
@MKSTAFF95 sorry for the late reply but I only found it several minutes ago -_-
@cerebrallolzy blame bureaucratism in the whole world:)
