### ISSUE TITLE
Facetime not Working on Unc0ver 3.7.0~b3

### ISSUE THREAD

**Issue by 2JayCee** [pwn20wndstuff/Undecimus#1587]
Facetime is unable to work properly on A12.

1. Jailbreak with Unc0ver 3.7.0~b3
2. Try Facetime

 - iOS Version: 12.4
 - iOS Device: XS
 - unc0ver Version: 3.7.0~b3

 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by cerebral-314** [comment]
You have an A12 device.  You need to be using Unc0ver 3.7.0~b2 instead of b3. try this before you do anything else.
