### ISSUE TITLE
iPhone cannot open uncover application and apps will not download or delete

### ISSUE THREAD

**Issue by DeAsianSensation** [pwn20wndstuff/Undecimus#1590]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
My iphone is a Xs and is jailbroken on a 12.4 jailbreak on the 3.7.0.b1 version of uncover. About 2 weeks ago my device ran out of battery, but when I recharged it the uncover application was not able to open and said that the certificate was revoked. I deleted the profile off my phone and thought that I could just use cydia impactor to get uncover to work that way. This was not the case because it registered that the profile was still on my phone. I tried deleting the uncover application, but the application will not go away. This is the case with all apps. I cannot delete, install, or update apps on my phone.
**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: Xs
 - unc0ver Version: 3.7.0.b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cerebral-314** [comment]
First make sure you are using the updated version of impactor. Next , you should be using unc0ver Version: 3.7.0.b2. Its the best version for A12 devices.  OK now you need to turn on impactor and click the xcode tab at the top right.  Select revoke certificate. Fill out the info you used for the profile that's giving you shit. It should go through its thing and say 1 certificate deleted or something to that effect.  Next do a hard reset on your phone. (volume up, vulome down, hold power button till you see the screen go black, then release.) At this point you should either, Not see the profile in the profiles section, or you should have the ability to delete it or the app.  Next, Load unc0ver Version: 3.7.0.b2 with impactor and you should be golden.

**Comment by DeAsianSensation** [comment]
I just tried it, but it didn’t really do anything. Impactor said that 1 certificate was revoked, so I did a hard reset. I tried to delete the uncover app by pressing the delete button, but nothing changed.

**Comment by DeAsianSensation** [comment]
I’ve also noticed that my messages have been buggy. I opened the message app and all I got was a white screen. So I have to fix this by hard resetting. It just keeps happening every so often.

**Comment by cerebral-314** [comment]
At this point.  Have you tried adding unc0ver through impactor without trying to delete the old one first?

**Comment by cerebral-314** [comment]
Lets see if just trying to add unc0ver Version: 3.7.0.b2 through impactor will work first.  The randomness almost sounds like a battery that's at its end.

**Comment by DeAsianSensation** [comment]
Just tried it and it says that there is already a certificate for it.

**Comment by cerebral-314** [comment]
Delete the old certificate or use a different apple ID for impactor.

**Comment by DeAsianSensation** [comment]
That’s the thing, I’ve already “deleted” the certificate. I went into my settings when I first found the issue and deleted the certificate, but impactor still registers it as being there.

**Comment by cerebral-314** [comment]
Use a differant apple id to sign impactor

**Comment by DeAsianSensation** [comment]
I've tried using different a different apple id, but it always says "application already installed as incompatible team"

**Comment by cerebral-314** [comment]
open settings, general, and scroll down to profiles and device management. What do you see?   a screenshot would be awesome.

**Comment by legriv26** [comment]
So. I have an issue similar but different. I have the uncover JB running v 3.0.7b1 on iPhone 10xr 12.4
Yesterday I my Uncover app stopped working. I deleted it without deleting the profile and tried to reinstall it but now it’s dessert and one open and I don’t see any profiles to delete. What can I do do I just have to restore my phone and lose my ability to jailbreak.?

**Comment by legriv26** [comment]
Sorry uncover 3.7.0 b3 is my version

**Comment by cerebral-314** [comment]
impactor is still not working.  you will need to redownload uncover from a website. once you jailbreak, use reprovision and you wont have to deal with this problem anymore.
