### ISSUE TITLE
Pokemon Go App Crashes After Beta 3 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1591]
Everytime i Open the PokemonGO app it keeps closing and Crashing and it wont Start After Jailbrake i also Try PokeGOBP to bypass Jailbrake Detection Liberty Lite and it did not work the Games Crashes Everytime when you try to open it and it wont Do Anything 

and this Issue is also Happening with other Apps please fix 

please Pwn we need Unc0ver Gold Masters to be completed all this Beta are not stable

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max and iPad Pro 
 - unc0ver Version: Unc0ver B3 
Unc0ver 3.7.0~b3 
*

**Comment by miguelr4720** [comment]
please fix i miss this game

**Comment by cerebral-314** [comment]
try using  Unc0ver 3.7.0~b2.  Its better for A12 devices.  it might fix your problem.

**Comment by miguelr4720** [comment]
it did not work? Plus this is Not The Only App There are More Apps That Are Crashing
