### ISSUE TITLE
Some Apps Are Crashing Undecimus-v3.7.0.b3

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1593]
Please Fix This Problem When Ever I Install Some Apps Every time i Open it keeps Crashing and is not Doing Anything and this is Only Happening When i Jail broken

Some Apps Are Still Crashing Lottery.com and Pokemon Go and It Happening With More Other Apps Please Fix 

and Also Shortcuts Keeps On Closing On Safari

**Device following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: Undecimus-v3.7.0.b3.ipa

**Comment by miguelr4720** [comment]
Is anyone else having this problem

**Comment by cerebral-314** [comment]
use beta 2

**Comment by miguelr4720** [comment]
try that it did not work

**Comment by miguelr4720** [comment]
and am using beta 2

**Comment by cerebral-314** [comment]
what apps specifically?

**Comment by iVosey** [comment]
new mario cart game is only one for me so far. probably jailbreak detect triggered. unsub and tweakconfigurator work on some apps 12.4 XR
