### ISSUE TITLE
Tweaks are Not Showing in Setting 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1594]
Tweaks are not Showing in Settings 

![0B47DFD9-DEBF-4EC5-9F7C-5D22FAD521FD](https://user-images.githubusercontent.com/36649261/67518290-7f107380-f672-11e9-94b7-5be078fbe2bb.png)
![4637B7C3-DA12-41EF-9499-A3D61A1731C0](https://user-images.githubusercontent.com/36649261/67518291-7f107380-f672-11e9-9d75-b9f6e1f3b9bf.png)
![60780F3D-83A6-4084-B637-100B9BDE54D5](https://user-images.githubusercontent.com/36649261/67518292-7f107380-f672-11e9-8b45-fe3115f19dfe.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: unc0ver b3

How. Can I fix this someone please help??

**Comment by miguelr4720** [comment]
Install http://rpetri.ch/repo/ 

PreferenceLoader

**Comment by cerebral-314** [comment]
use beta 2
