### ISSUE TITLE
Bluetooth will connect but sound is muffled and then dies.

### ISSUE THREAD

**Issue by dameeerajman** [pwn20wndstuff/Undecimus#1598]
**Describe the bug**
Been  jailbroken from day 1 and had no issues with bluetooth when all of a sudden my bluetooth sound started dying from my devices. I uninstalled all my tweaks and did multiple restoreFS and clean jailbreaks but it did not resolve the issue. The second I am jailbroken bluetooth issues return.
**To Reproduce**
1. Run uncover jailbreak fresh
2. Bluetooth connects and sound plays for like 2 seconds muffled and then dies.
3. need to reboot phone to allow bluetooth to connect again.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone xs max
 - unc0ver Version: latest b3

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by cerebral-314** [comment]
Load the jailbreak with "load tweaks"  unchecked in Unc0ver. see if you still have the issue.

  BTW you probably want to use beta-2 .  It seems to work better with A12 devices.

**Comment by dameeerajman** [comment]
Tried unchecking load tweaks with beta 3 and no luck.

Beta 2 doesn’t seem to want to install with Cydia impactor I am getting
errors. Is there a way to install beta 2 directly from safari?

**Comment by cerebral-314** [comment]
What errors do you get with impactor?

**Comment by dameeerajman** [comment]
Hi,

The issue from cydia impactor was being caused by me having reprovision
installed on multiple devices and being unable to revoke the certificates.
Got it to revoke just now and installed uncover b2 clean with load tweaks
unchecked but the Bluetooth issues remain.

It plays audio for a second and then just dies for some reason.

**Comment by cerebral-314** [comment]
have you tried a differant bluetooth device?   Might not be your phone at all.

**Comment by cerebral-314** [comment]
delete the old bluetooth device profile and reconnect it while the phone is jailbroken.

**Comment by dameeerajman** [comment]
That worked!!!!!!! Omg! Thanks so much!!! You guys are the best :DDDDD just
had to remove the bluetooth device and add it back. Silly me.
