### ISSUE TITLE
App shortcut 

### ISSUE THREAD

**Issue by Zombiesun00** [pwn20wndstuff/Undecimus#1599]
Hey the bug is that when you get appshorcut free version you can’t move your homescreen or even do a power off it’s really annoying and I’m trying to find a way to open Cydia and remove their tweak it’s really bad don’t get it

**Comment by cerebral-314** [comment]
Hard reset your phone.  when you open unc0ver click the little cog and make sure "load tweaks" in not checked.  Jailbreak your phone and go into cydia and uninstalled the tweak.

**Comment by Zombiesun00** [comment]
Cool thanks
