### ISSUE TITLE
Collapsed header conflicts with options below it

### ISSUE THREAD

**Issue by haykam821** [pwn20wndstuff/Undecimus#16]
If you scroll down in the Settings tab of unc0ver, the collapsed header will collide with the options below:

![Collapsed header in unc0ver](https://i.imgur.com/sJeIWzL.jpg)

In contrast, the collapsed header covers the setting panes below it with a translucent cover:

![Collapsed header in Settings](https://i.imgur.com/s4HgdCj.jpg)

**Comment by pwn20wndstuff** [comment]
Will be fixed soon.

**Comment by Samgisaninja** [comment]
Fixed in 2.0.2

**Comment by haykam821** [comment]
Confirmed that this has been fixed in 2.0.2:

![Collapsed header in unc0ver 2.0.2](https://user-images.githubusercontent.com/24855774/49752262-d3d71580-fc7d-11e8-9678-41cdc458cd9f.jpg)
