### ISSUE TITLE
Uncover got revoked, Reinstalled but "Not Verified"

### ISSUE THREAD

**Issue by Yoshi24517** [pwn20wndstuff/Undecimus#1603]
**Describe the bug**
So my unc0ver got revoked, its been 7 days. Okay. What ever. I go to sideload it again via Impactor (the latest version), and go to trust it again, and it get trusted, but it says Not Verified. I just literally redownloaded it.

**To Reproduce**
1. Just redownload uncover on your phone.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.4
 - iOS Device: iPhone XR
 - unc0ver Version: 3.7.0 b3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce (maybe)
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cerebral-314** [comment]
hehe.  Don't freak out.  just go into settings , general, profiles and device management. open the profile and click trust.

**Comment by Yoshi24517** [comment]
I know. I trust it, and it still says "Not Verified."

**Comment by gummykage** [comment]
You do need an active internet connection to verify it.

**Comment by ghost** [comment]
Your certificate got revoked. Just wait for another signing service to update your certificate and install that. You have to rely on signing services or 3uTools to install unc0ver as Cydia Impactor is currently not working. This is not a problem with unc0ver. Also if your using a Mac, you can use XCode to install unc0ver using your Apple ID

**Comment by quilenle** [comment]
We are waiting for Saurik to fix this.
