### ISSUE TITLE
Substrate randomly decides to stop working ?

### ISSUE THREAD

**Issue by RexSonic** [pwn20wndstuff/Undecimus#1606]
Sometimes substrate will randomly stop working complete with all your tweaks and opening unc0ver app and clicking re-jailbreak will put you in a respring loop so you have to reboot in order to start substrate

**Comment by RexSonic** [comment]
here are bunch of crash reports
[crashreports.zip](https://github.com/pwn20wndstuff/Undecimus/files/3802003/crashreports.zip)

**Comment by delon5** [comment]
happens to me aswell iphone x iOS 12.2 latest unc0ver. Can’t get past 3-9 days uptime before this happens. Otherwise very stable.

**Comment by cerebral-314** [comment]
a list of tweaks you are using would be much easier to work with.

**Comment by ghost** [comment]
me too. 
My tweaks keep working very well for a few hours, before this status。
Then I have to reboot it.

**Comment by fuguangxin** [comment]
I have the same problem,usually available within one or two days
