### ISSUE TITLE
Can't install Undecimus with error code 81

### ISSUE THREAD

**Issue by haer0248** [pwn20wndstuff/Undecimus#1609]
**Device:**
 - iOS Version: 12.0.1
 - iOS Device: iPhone6s plus
 - unc0ver Version: x

Cydia impactor:
![image](https://user-images.githubusercontent.com/25150003/68375940-b149c700-0182-11ea-8a02-ed3a1b5bdc1e.png)

How to install ;( ?

**Comment by cerebral-314** [comment]
Try a different error code...

**Comment by cerebral-314** [comment]
:D  hehe. J/K.  There is a problem with impactor and reprovision. Its on apple's side.  They are looking for a fix at the moment.

**Comment by InternetMogul** [comment]
yes, having same line 81 issue here. Thank you for all your hard work developer!

**Comment by cerebral-314** [comment]
reprovision is working now. so im assuming getting unc0ver from a website might work now.  impactor is a no go for the moment.
