### ISSUE TITLE
iPhone 8, iOS 12.4, u0 3.7.0, random resprings/reboots/can’t enable RSD

### ISSUE THREAD

**Issue by cyntrifical** [pwn20wndstuff/Undecimus#1610]
**Describe the bug**
Basically everytime I jailbreak, I have to disable RSD or it resprings forever until it reboots. After jailbreaking sometimes upon clicking home button from lockscreen as soon as it transitions from LS to SB it goes black and reboots. Then just the immense amount of random resprings which typically always lead to a reboot. Not sure if it started with version 3.7.0 but it’s gradually gotten worse to the point my jailbreak is nearly unusable. No crash logs are being produced either. May have some analytics logs though. 

**To Reproduce**
1. Use iPhone 8, on iOS 12.4 with u0 3.7.0

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 8, 64gB
 - unc0ver Version: 3.7.0

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce (seems there’s similar issues on 12.4?)
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cerebral-314** [comment]
It sounds like you recently added some new repos yes?

**Comment by cyntrifical** [comment]
I mean i delete and add repos here and there why is there a particular reason?

**Comment by cerebral-314** [comment]
Some pirate repos can trigger certain, paid for, apps to exhibit this type of behavior. re jailbreak with all tweaks disabled.  go in and delete any such repos.  See if this fixes the issues.  If it does.  there are ways around using pirate repos.

**Comment by cerebral-314** [comment]
A list of tweaks would help. the tweak Flame can give you the list.
