### ISSUE TITLE
iPod Touch 6G iOS 12.4 big battery drain issue

### ISSUE THREAD

**Issue by Alan-Python** [pwn20wndstuff/Undecimus#1611]
When I add the install the Cydia tweaks it drops from 100% to 96% from 4 percent loss there’s is a big battery drain here on out from A12 devices

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cerebral-314** [comment]
Install cocoatop 2.0.2.  I can't show you the repo to get it, but you can simply google it to find out.

It's a tweak that is basicly just like task manager on a PC.  This will show what is running and taking up CPU usage.    Come back and report what is running at %100 constantly.

**Comment by Alan-Python** [comment]
Ok. I report back to you
