### ISSUE TITLE
Screenshots stop working after a while for no reason

### ISSUE THREAD

**Issue by Shaq234** [pwn20wndstuff/Undecimus#1613]
**Describe the bug**
The screenshot works correctly after jailbreaking but as time passes by it stops working, when I click on Power + Home it doesn’t take the screenshot anymore, and I have to respring the device to get it working again.

**To Reproduce**
I don’t do anything special on my phone, just stops working after a while.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6s
 - unc0ver Version: Always happened to me since first unc0ver public beta and now is happening at 3.7.0 b3.

**Place an "x" between the brackets if true:**
 - [ x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x ] this issue is present after a rootfs restore
 - [ x ] this issue is present on the latest version of unc0ver

**Comment by cerebral-314** [comment]
show a list of the tweaks you are currently using please.

**Comment by cerebral-314** [comment]
use the tweak "Flame"  to get this list.

**Comment by Shaq234** [comment]
7-zip (POSIX): 16.02-1
AnimationsBeFastPlus: 2.0
AppList: 1.5.15~beta1
Apps Managed: 1.5.0-12
AppStore++: 0.9.7
AppSync Unified: 64.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional: 1:0-2
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
AskBeforeCalling Too 12: 1.0.0~beta18-7
Assuan: 2.5.1-1
AwesomePageDots: 1.1.2
BackupAZ 3 (iOS 10 - 12): 1.6.1
Base Structure: 1-5
Baylor: 1.2
Berkeley DB: 6.2.32-1
BetterCCXI: 1.6.0
BigBoss Icon Set: 1.0
blankpass: 0.0.1-1+debug
Bourne-Again SHell: 5.0.3-2
BrickFix: 1.0.1
bzip2: 1.0.6-1
CA Certs: 0.0.2
CallDismiss12: 1.0.0~beta6
Cappd: 1.0.3
CCBrightnessExtended: 1.0
CCModules Pro: 1.0.2
CCSupport: 1.2.2
Cephei: 1.13.1-2
Cercube for YouTube: 5.1.1
ColorBadges: 1.4.1
ColorBanners 2: 1.2.4
CopiedBanner12: 0.0.2
CopyLog: 1.2.5
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cuboid: 2.0.1
Cuttlefish: 1.2
Cydia Installer: 1.1.32~b22
Cydia Substrate: 0.9.7033
Cydia Translations: 1.1.32~b1
CyDown: 7.0.1
DarkKeys: 1.1.2
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DiskProbe: 0.7.3b
DismissProgress: 1.0.4
DoubleCut: 0.5
Dragspring: 1.2.1
EasyBrightness: 1.1.2
EasySwitcherX: 0.0.7
Essential: 0-1
ExactTime: 1.6
ExactTimeMessages: 1.0
ExactTimePhone: 1.0-1+debug
FastForwardTime: 2.0.2
file: 5.35-2
Filza File Manager: 3.7.0-18
Find Utilities: 4.6.0-2
Flame: 1.3
FloatingDockPlus: 1.3.4.1
Fortune: 1.4.4
FoxFort Tools: 1.0.7
Gawk: 4.2.1-1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
GoodWiFi: 0.0~beta5
grep: 3.1-1
gzip: 1.9-1
iCleaner Pro: 7.7.5
iOS Firmware: 12.4
iPadStatusBar: 1.1.6
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b26
KSBA: 1.3.5-1
LetMeBlock: 0.0.7.1
libcolorpicker: 1.6.4
libCSColorPicker: 1.0.3
libCSPreferences: 1.2.0
Liberty Lite: 0.2.10
libfoxfortutils64: 1.0.9
libidn2: 6.1.2-1
libnotifications: 0.2-3
libpackageinfo (cokepokes): 1.1.0.1-3
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libswift (stable): 5.0
libswift4: 4.2.1-2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
Locale Profiles in UTF-8: 1.0-1
LowBatteryBanner [Public]: 1.0.2
LowPowerCharging: 0.0.2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MathTeacher: 1.1.1
MenushkaPrefs: 1.2.2
MobileSubstrate Dummy Package: 0.9.7033+dummy
Nanobanners: 0.1.2
NCGrabberInfo: 1.0
nControl: 1.2.2-19
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NoCallBlur: 1.0.1
NoLargeTitles: 1.0-1
OhMyFlash: 1.0.0
OneNotify: 1.2.2
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PhoenixOS Theme: 1.1.1
PieCrust: 1.0.5-1
PortraitXI: 1.0.5
PowerGuard: 2.0.3
PowerSelector (iOS 11 & 12): 1.2.1
PreferenceLoader: 2.2.4~beta1
PrefixUI: 1.2.6
Profile Directory: 0-1
readline: 8.0-1
RealCC: 1.0.2
ReProvision: 0.5~experimental3
RespringCacheFix: 0.2
RocketBootstrap: 1.0.7~beta3
Rose: 2.2.1
Safari Plus: 1.7.7-2
sed: 4.5-1
SelectionPlus: 1.0.6.4
shell-cmds: 118-8
Shunrai Theme: 1.3
Signing Certificate: 0.0.1
SleepToggle: 1.0.3
SleepyTime: 0.0.2
SlideToShowNotification: 1.0.0
SmallSiri: 1.2.2
SmoothCursor: 1.1.3
SnowBoard Dock Extension: 1.0.5~Beta1
SnowBoard Fonts Extension: 1.0.4~Beta1
SnowBoard Icon Effects Extension: 1.0.8~Beta1
SnowBoard Icon Masks Extension: 1.0.7~Beta1
SnowBoard Labels Extension: 1.0.0~Beta1
SnowBoard Page Dots Extension: 1.0.1~Beta1
SnowBoard Preset Extension: 1.0.14~Beta1
SnowBoard Procedural Wallpapers Extension: 1.0.1~Beta1
SnowBoard Respring Extension: 1.0.1~Beta1
SnowBoard Settings Icons Extension: 1.0.15~Beta1
SnowBoard StatusBar Extension: 1.0.2~Beta1
SnowBoard: 1.2.52~Beta1
Soda Repo Icons: 1.2
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.10
SwitchShades: 1.0
System Memory Reset Fix: 2.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TapTapFlip: 1.5
TechSupport Framework (cokepokes): 1.5.0.1-2
ToneManager: 0.6.2-368
Translomatic: 1.2.10
Trust Cache Injector: 0.4~b5
trustDevAlert: 0.2
TSS Saver: 1.2.0
TweakReviewsDB: 0.4.2
UIKit Tools: 1.1.15-2
Ultrasound: 1.2.9
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
Viola: 1.9
Watusi 2 for WhatsApp: 1.2.17
WatusiTools: 2.1.8
WiFiScanner: 0.0.6
XZ Utils: 5.2.4-4
YTStatus: 1.2.0
Z Shell: 5.7.1-3
Zebra (BETA): 1.0~beta26-4
zip: 2.32-1

**Comment by cerebral-314** [comment]
I would download the tweak called crashrepoter. when you have an issue pop up.  check this app.
Im going to guess its calldismiss12 causing your issue.

**Comment by Shaq234** [comment]
This bug is not registered by crashreporter since nothing is really crashing, it just stops doing a function. But I will uninstall CallDismiss12 to see if something changes.

**Comment by Shaq234** [comment]
Looks like it was caused by CallDismiss12, thank you!
