### ISSUE TITLE
Restore RootFS does not work on 12.4 iPhone 6 Plus - Trying to migrate to checkra1n

### ISSUE THREAD

**Issue by drewfissh** [pwn20wndstuff/Undecimus#1614]
**Describe the bug**
Unc0ver does not allow my iPhone to Restore RootFS, it gets stuck at 2/30.
**To Reproduce**
1. Jailbreak
2. Enable restore RootFS in unc0ver settings
3. Tap Restore RootFS
4. unc0ver crashes

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by quilenle** [comment]
Did you turn off other features (only Restore RootFS enabled)?

**Comment by quilenle** [comment]
If you want to use checkra1n, you can follow these steps:
1. Install NewTerm2
2. Open NewTerm2
3. Type `su` then press Return
4. Type the password is `alpine` (ALPINE in lower case)
5. Type `touch /.mount_rw` then press Return
6. Then you can switch to checkra1n by using the checkra1n to jailbreak your phone
