### ISSUE TITLE
Apps chash sometime when i try to open

### ISSUE THREAD

**Issue by franciscel** [pwn20wndstuff/Undecimus#1615]
![IMG_2317](https://user-images.githubusercontent.com/41459127/68885908-6f71d100-06ec-11ea-8cd8-e4bfa257fc95.PNG)
![IMG_2319](https://user-images.githubusercontent.com/41459127/68885909-6f71d100-06ec-11ea-8266-8e2b3fc59957.PNG)
![IMG_2320](https://user-images.githubusercontent.com/41459127/68885910-6f71d100-06ec-11ea-91e2-2d470ee06737.PNG)

**Describe the bug**
Sometimes, when i take my phone and try to open any app, it crash, send me to "Safe mode" when try to open an app crash again, The tweak Cr4shed say "springboard" but no shows culprit, this happens sometimes in a day.

The same problem happen with "Electra"

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone X
 - unc0ver Version: 3.7.0. B3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cerebral-314** [comment]
show a list of installed tweaks.  you can get this from a tweak called Flame.

**Comment by franciscel** [comment]
List of Tweaks

![IMG_2372](https://user-images.githubusercontent.com/41459127/69063710-58d0c000-09f3-11ea-9a61-a7458d2c1de9.PNG)
![IMG_2373](https://user-images.githubusercontent.com/41459127/69063711-59695680-09f3-11ea-8f91-1d1c58eee7ef.PNG)
![IMG_2374](https://user-images.githubusercontent.com/41459127/69063712-59695680-09f3-11ea-8521-4a6cdefd4da9.PNG)
![IMG_2375](https://user-images.githubusercontent.com/41459127/69063713-59695680-09f3-11ea-9232-d214c27f8d38.PNG)
![IMG_2376](https://user-images.githubusercontent.com/41459127/69063714-59695680-09f3-11ea-80ae-9b6947db0e4d.PNG)

**Comment by cerebral-314** [comment]
You definitely have a tweak compatibility issue. If I had to make a fast guess. I would say activator is your main suspect. You just need to start going through each one, uninstalling, running for awhile to see if you get the same problems, then going to the next tweak.  rinse and repeat, until you find the offending tweaks. 
I now have 122 tweaks and counting, and my phone runs butter smooth all day all night.

**Comment by franciscel** [comment]
> You definitely have a tweak compatibility issue. If I had to make a fast guess. I would say activator is your main suspect. You just need to start going through each one, uninstalling, running for awhile to see if you get the same problems, then going to the next tweak. rinse and repeat, until you find the offending tweaks.
> I now have 122 tweaks and counting, and my phone runs butter smooth all day all night.

It is tedious to uninstall one by one, but I uninstalled the one you recommended, I think that was the problem. I am testing, thanks
