### ISSUE TITLE
How to jailbreak after impactor’s bug

### ISSUE THREAD

**Issue by c3z4r4rthur** [pwn20wndstuff/Undecimus#1616]
I don’t know how to install Unc0ver without Impactor, which one isn’t working so far.

**Comment by quilenle** [comment]
Try using third-party that signed app such as Ignition, AppValley, ...
[If the app can't install now, be patient and try again later.]
After that, you can use ReProvision for re-signing your own u0 via your Apple ID

**Comment by c3z4r4rthur** [comment]
I tried several times with ignition but now it worked. Thank you.
