### ISSUE TITLE
Why i can't enter the app ?

### ISSUE THREAD

**Issue by ShYmaNo16Hz** [pwn20wndstuff/Undecimus#1617]
I turned my iphone off yesterday now i have the reinstall the jailbreak.
I reinstalled the app with Ignition
After installing, i tried to enter the app but its look like that: ![proof](https://user-images.githubusercontent.com/32879510/69051595-71e66a80-0a0d-11ea-8283-35561305e00e.jpg) and i can't enter in the app.

I tried to install it with cydia impactor, but i got an error about xcode 7.3
Device: iphone 5s 12.2

**Comment by ybekirov** [comment]
Having the same issue, any update? @pwn20wndstuff

**Comment by zgudge** [comment]
The app has been revoked, this means apple has denied the app from installing. It should be back up in 24 hours. Or you can sign it yourself if you have access to a laptop with cydia impactor and an internet connection.

**Comment by ff4goods4life** [comment]
you cant sign it yourself anymore using impactor because apple updated something on the backend so until cydia impactor gets an update, i wouldn't hold my breathe since saurik has been mia, there is no way to rejailbreak unless u try checkmate

**Comment by zgudge** [comment]
> you cant sign it yourself anymore using impactor because apple updated something on the backend so until cydia impactor gets an update, i wouldn't hold my breathe since saurik has been mia, there is no way to rejailbreak unless u try checkmate

I've just tried, Xcode error. Hang tight, there will be an update soon :)

**Comment by ShYmaNo16Hz** [comment]
> update

what checkm8 / checkra1n actually do?

**Comment by zgudge** [comment]
UNC0VER IS NOW SIGNED ON IGNITION

**Comment by ff4goods4life** [comment]
Link?

**Comment by zgudge** [comment]
> Link?

app.ignition.fun type unc0ver on search and trust the profile. You've used uncover before right?

**Comment by sebastiensimon** [comment]
doesnt work

**Comment by sebastiensimon** [comment]
This one work beautiful for me https://cydia-app.com/unc0ver/ just use the 3utool and it work

**Comment by zgudge** [comment]
> This one work beautiful for me https://cydia-app.com/unc0ver/ just use the 3utool and it work

Yes, with a computer. You can use uncover on ignition to do it straight from your phone. rather than plugging your phone into your pc every time

**Comment by sebastiensimon** [comment]
The one with ignition doesnt work for me for some reason i dont know why.

**Comment by zgudge** [comment]
> The one with ignition doesnt work for me for some reason i dont know why.

I'd reset your cache, it must've still stored the old version. Try again, it should work now.
