### ISSUE TITLE
Safari Wont Give Me Options 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1619]
everytime i open safari is not giving me any options please help me fix 

 - iOS Version: iOS 12.4 
 - iOS Device: iPhone XS Max
 - unc0ver Version: b3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
![3CD1193B-8D78-4B19-AD36-EA1793C184DE](https://user-images.githubusercontent.com/36649261/69304328-36ef5d00-0bee-11ea-82e0-27597474314d.png)

**Comment by miguelr4720** [comment]
everytime is doing this sometime when am Jailbroken

**Comment by cerebral-314** [comment]
disable any dark mode settings for safari. see if that works.
