### ISSUE TITLE
Issues with 3rd party Keyboards

### ISSUE THREAD

**Issue by VeZReVouLiS** [pwn20wndstuff/Undecimus#1620]
**Describe the bug**
In the past ~5-6 versions (or more, i don't remember correctly) of unc0ver i had issues with 3rd party keyboards as Swiftkey/Google Keyboard.

At first i thought that has something to do with the keyboards and the iOS versions because it didn't happen all the time.

I decided to open an issue, because i was without JB for almost a week due to problem with Cydia Impactor and jailbreaks.fun and both of the keyboards worked **_without any_** problem.

The problem is that when i'm in any app (fb, twitter, messages, browser etc) and i press anywhere in order to write/reply etc sometimes i having similar behavior like the first image of issue #783 

Meaning that keyboard trying to open but it crush and apple keyboard opens instead.
Sometimes though freezes for some seconds and opens.

From keyboard settings i tried numerous combinations/settings like :
1. Tried to have only one keyboard activated
2. Tried to have two keyboards (except apple's keyboard) in different position
3. Tried to use only apple keyboard.

Even with 1 or 2, when the keyboard crushes apple's keyboard opens even if i don't have it activated.

PS1. I will try to make a video but as i said, isn't happening all the time but sometimes...
PS2. I understand that in case-sensitive forms like passwords, apple's keyboard will be opened.
PS3. Maybe is not related with this but when i having this issue, all the browsers i have (chrome, safari, opera and firefox) opens and hangs immediately.
PS4. If i use only Apple's keyboard, the issue doesn't appear at all.
PS5. This issue appeared first when i was at iOS 11 (i'm not remember the exact version, sorry) 

**Device :**
 - iOS Version: 12.4
 - iOS Device: iPhone 7 Plus
 - unc0ver Version: 3.7.0-b3

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce (_**hopefully**_)
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

Thanks and sorry for the long post...
Dimitris,

**Comment by cerebral-314** [comment]
Use a tweak called Flame to get a list of tweaks you have installed. Also, have you updated your gboard?

get that list of tweaks and post it please.

**Comment by shayshtern** [comment]
@VeZReVouLiS Did u fix this? I have this issue now with Unc0ver 4 iPhone XS Max iOS 13.3
