### ISSUE TITLE
Error with Undecimus-v3.7.0.b1

### ISSUE THREAD

**Issue by ammarutd9** [pwn20wndstuff/Undecimus#1624]
File: Provision.cpp;line:81;what

ios/listDevices=3018
Please update to Xcode 7.3 or later to continue developing with your Apple ID.

**Comment by rickyguccio** [comment]
i have the same problem

**Comment by cerebral-314** [comment]
Guys, you need to do some catching up in the Apps signing scene.  You need to download unc0ver from a website now.  Not through impactor. Also don't use beta 1.   Use 2 or 3 depending on your device.

**Comment by Cezararthur** [comment]
What site can I use? Tweakbox and appvalley aren’t working.

**Comment by alexmaten** [comment]
The only way I found to install succesfully unc0ver at this moment is through '3uTools', in the JB tab, select 'iosXX jailbreak' and it will install unc0ver in your iDevice easily.
