### ISSUE TITLE
Filza asking to “open with..” (not showing Cydia as an option) & default option chosen

### ISSUE THREAD

**Issue by Swaghacker7** [pwn20wndstuff/Undecimus#1627]
**Describe the bug**
When opening a deb file sometimes Filza will ask to “open with..” and not show Cydia as an option, what should be expected to happen is the deb Install gui should pop up but that isn’t happening, only the open with menu is coming up with default chosen as the option in the file preferences.

**To Reproduce**
1. Tap on any deb file
2. Menu for open with.. pops up instead of deb installer

**Screenshots**

![A4E8C781-5D06-4A01-8B99-2B7B5E3F2408](https://user-images.githubusercontent.com/54298662/69917605-aad30600-1435-11ea-878b-24b3982868c1.jpeg)
Here I am trying to install the installer beta and I’m expecting an install window to show up but it always shows this menu even on “default” chosen as the open with option

**Device (please complete the following information):**
 - iOS Version: iOS 12.4.0
 - iOS Device: IPhone XR
 - unc0ver Version: 3.7.0~b2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ENDERZOMBI102** [comment]
If its an ipa is normal, cydia can’t install ipas, use reprovision or filza itself for that
