### ISSUE TITLE
Why the unc0ver icon is grayed out

### ISSUE THREAD

**Issue by yefeiyu** [pwn20wndstuff/Undecimus#1632]
From unc0ver.dev, Failed to install.
Other installation media prompt "revoke".

**Comment by kfur** [comment]
@yefeiyu just don't delete revoked app and follow this instructions [https://www.youtube.com/watch?v=Pk1roueWr6Q](https://www.youtube.com/watch?v=Pk1roueWr6Q)

**Comment by 1060182419** [comment]
苹果6S越狱12.4.1在线越狱什么时候出来
