### ISSUE TITLE
Unc0ver crashes when trying to enter the app

### ISSUE THREAD

**Issue by JTCGaming** [pwn20wndstuff/Undecimus#1635]
**Describe the bug**
I recently installed the newest version 3.8.0 b1 and once I try to enter the application, it crashes usually in .5-2 seconds. 

My iPhone is jailbroken but my iPhone recently restarted so I am trying to re jailbreak it. However I can’t seem to enter the app to do so. 

**To Reproduce**
Enter the application. 

**Screenshots**
N/a

**Device (please complete the following information):**
 - iOS Version: 11.4.1
 - iOS Device: iPhone 6
 - unc0ver Version: 3.8.0 b1

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
am having the same problem too sometimes when am using the my iPhone normally it respirings out of no where please fix this bug i check the tweaks and i dont see any incompatible tweak install and my iPhone Respring Sometimes plz fix???

**Comment by JTCGaming** [comment]
A little info, I can’t even use my damn tweets. I’m in the unjailbroken state currently. Back on version 3.7.0 b3 it worked just fine, was perfectly stable and no problems on the phone. Just simply can’t access the app. It’s on the screen and everything so it’s not a uicache issue. 

Glad I’m not alone however. I was hoping it wasn’t a me only thing. Lol.

**Comment by icaros7** [comment]
I have same proble too. Now I can't open unc0ver on 12.4 xs max. I hope its working well, when I downgrade to 3.7.0. However, I can't install old version without reprovision...

Wow...It so happy? I'm not alone too!! XD

**Comment by JTCGaming** [comment]
> I have same proble too. Now I can't open unc0ver on 12.4 xs max. I hope its working well, when I downgrade to 3.7.0. However, I can't install old version without reprovision...
> 
> Wow...It so happy? I'm not alone too!! XD

Yeah bro. I get my version from AppValley because Cydia impactor doesn’t work anymore because of a bug. AppValley is going through a revoke apocalypse and they can’t seem to find new certificates and now once it finally workes, another wall appears. Like how much longer do I got to wait to jailbreak my phone again?!

**Comment by ABurnglv** [comment]
For me work next things.
1. Turn on airplane and off wi-fi (If you connected)
2. Open Unc0ver app
3. Wait for make sure that app doesn't close
4. Turn on Airplane mode (You can make Jailbreak with airplane, but I have only reboots and resprings with it)
5. Make jailbreak :)

**Comment by icaros7** [comment]
Update

It working perfectly on 3.7.0b3...without any problems.

If you want find 3.7.0b3 sideload site who have same this issue,
I found 1 site still alive with 3.7.0b3

But I don't know 'Can I reply this url on github?!'
So I tell you search keyword. IT'S ALL YOUR OWN RISK :\

1. Search 'unc0ver 3.7.0b3 revoked' via Google
2. One of result, has a 'RED REVOKED BUTTON ON TOP' and display unc0ver, cimera, sileo demo...etc...
3. Just tap get button(next the unc0ver icon)
4. Yay. Enjoy your PrisonBreak😘

**Comment by cutieshy** [comment]
> Update
> 
> It working perfectly on 3.7.0b3...without any problems.
> 
> If you want find 3.7.0b3 sideload site who have same this issue,
> I found 1 site still alive with 3.7.0b3
> 
> But I don't know 'Can I reply this url on github?!'
> So I tell you search keyword. IT'S ALL YOUR OWN RISK :\
> 
> 1. Search 'unc0ver 3.7.0b3 revoked' via Google
> 2. One of result, has a 'RED REVOKED BUTTON ON TOP' and display unc0ver, cimera, sileo demo...etc...
> 3. Just tap get button(next the unc0ver icon)
> 4. Yay. Enjoy your PrisonBreak😘

I don't trust this and don't understand it



> For me work next things.
> 
> 1. Turn on airplane and off wi-fi (If you connected)
> 2. Open Unc0ver app
> 3. Wait for make sure that app doesn't close
> 4. Turn on Airplane mode (You can make Jailbreak with airplane, but I have only reboots and resprings with it)
> 5. Make jailbreak :)

this straight up does nothing.

I'm in the same boat on 12.4/A12 and nothing seems to be working, I'm currently jailbroken but I can't get the latest IPA to install and start up properly.

**Comment by res1492** [comment]
Not a bug, use 3utools to add uncover back to your iPhone, delete old uncover app first, load 3utools, goto Flash&JB tab then jailbreak section and pick your OS version, make sure you have antivirus turned off, let it do its thing, trust the app on your phone just like normal open unc0ver and JB Away, your done....this will only installs the latest version of unc0ver, nothing else is effected
