### ISSUE TITLE
iPhone Respring For No Reason 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1636]
**RESPRING BUG**

Am having the same problem too sometimes when am using the my iPhone normally it respirings out of no where please fix this bug i check the tweaks and i dont see any incompatible tweak install and my iPhone Respring Sometimes plz fix???
**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: b4

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
i been having This Respring Bug Since I First Jailbrake with Uncover B3 and my iPhone Respring For no Reason this issue is getting me Pissed Off how can i fix this Problem

**Comment by miguelr4720** [comment]
the Issue Occurs Sometimes when i Normally Use my phone and i updated Uncover b4 and am still having this problem

**Comment by miguelr4720** [comment]
any fix for this please

**Comment by Duckloveshack** [comment]
OK, I understand it is BETA 4, but can you send the full version number, please?

**Comment by miguelr4720** [comment]
Am using 3.7.0 B3 iOS 12.4 and am getting tired of this problem and it never fixes or unC0ver does nothing to fix this
