### ISSUE TITLE
Cydia Substrate disables itself

### ISSUE THREAD

**Issue by smolsarahios** [pwn20wndstuff/Undecimus#1637]
Unc0ver is an awesome jailbreak, however after a long uptime Cydia Substrate disables itself and rejailbreaking doesn’t work (“failed to start Cydia Substrate”). Is there any hope for a fix? Could you possibly enable Substitute for older devices? I know it’s deprecated but I’d (as well as others) would definitely be interested.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by quilenle** [comment]
Reference: https://github.com/pwn20wndstuff/Undecimus/issues/1575
You need to reboot your device to stock and jailbreak again.

**Comment by rctfan929** [comment]
No need to reboot.
If you are currently jailbroken do the following:

1. Open preferred package manager
2. Find Substrate
3. Tap reinstall
4. Close package manager
5. Open unc0ver
6. Rejailbreak
