### ISSUE TITLE
Touch ID Issue

### ISSUE THREAD

**Issue by MaZaaF** [pwn20wndstuff/Undecimus#1639]
**Describe the bug**

Im having issue with Touch ID, I can't download apps or get in app purchase using Touch ID, I need to enter my password everytime I try to download apps, even if I have iTunes & App Store enable in Touch ID settings.

**To Reproduce**
1. Try to download any apps in App Store

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone 6S
 - unc0ver Version: 3.8.0~b1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**

**Comment by quilenle** [comment]
Did you try the 3.7.0~b4?
