### ISSUE TITLE
Ios13

### ISSUE THREAD

**Issue by Dscar702** [pwn20wndstuff/Undecimus#1642]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by orznick14** [comment]
There isn't a released TPF0 for iOS13 yet, hold your horses.

**Comment by andre104623** [comment]
Admin close this issue because there isn’t any unc0ver not supporting iOS 13 isn’t a fucking bug it’s you begging for a iOS 13 jailbreak
