### ISSUE TITLE
Where's the complete, up-to-date source code?

### ISSUE THREAD

**Issue by ansarirayyan** [pwn20wndstuff/Undecimus#1644]
Am I doing something wrong? I can't find where the current, completed code is. The master, dev, and 2.1 branches seem to be ancient and the source code posted on the releases page is incomplete. 

Having the source code handy would be really useful, especially since saurik's Cydia Impactor no longer works. Having the source code would enable us to run the source code on our iOS device via Xcode and successfully jailbreak it. The source code in the master branch is seemingly old as, when run, says my iPod 6G is unsupported while I had it jailbroken before using an *.IPA from the releases page. The source code links are missing all that symlink stuff (like the contents of the patchfinder64 directory, and a lot others).

I hope my explanation makes sense.

**Comment by andre104623** [comment]
Yes not the place. Google, close the thread 
Iosninja

**Comment by ansarirayyan** [comment]
I tried searching it up but still couldn't find. Also the issue with iOSNinja is that it sometimes isn't signed.

**Comment by andre104623** [comment]
Omg google is your friend that is the how it’s is apple revokes the apps over time sometimes 1 day sometimes a week. Cydia impactor doesn’t work anymore till someone fixes it you can become an apple developer for 100 a year and sign your own stuff

**Comment by andre104623** [comment]
And wait hold on you have an iPod??!!! Omg use Checkm8 which you should also google
