### ISSUE TITLE
Iphone Xr ios 12.2 unable to get debs for packages to repair

### ISSUE THREAD

**Issue by vicogh** [pwn20wndstuff/Undecimus#1655]
I try to jailbreak my IDevice  for first time and I get the error 

**To Reproduce**
 I tap on jailbreak after finish the process the Xr reboot automatically, I check that cydia was not installed, so I re-jailbreak but in the 18/31 process I have the next error "unable to get debs for packages to repair" and then the Unc0ver app close  byitself

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.2
 - iOS Device:  iPhone XR
 - unc0ver Version: 3.8.0%b1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by andre104623** [comment]
Download version 3.7.0b7 instead I’m pretty sure that’s the version that supports your version iOS. Unc0ver 3.8.0b1 is only for a12 devices running 12.4.1 XS XS max XR but XR is broken so that’s why it won’t work
