### ISSUE TITLE
Outlook App Doesn’t Work no More? Outlook App is Dead :(Do Not Update Version 4.21.0 iOS 12.4

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1658]
Everytime i Open the App While Jailbroken the apps keeps crashing. And when I restart the phone and I open the app am not able to login

![31E9AA3D-817D-43AE-9543-359BEF04A7E4](https://user-images.githubusercontent.com/36649261/73067601-24f09b80-3e77-11ea-9229-35e813341b38.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: 12.4
 - unc0ver Version: 3.8.0 b1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by andre104623** [comment]
Why are you in a call while your signing in

**Comment by andre104623** [comment]
Oh and your supposed to use unc0ver 3.7.0 not 3.8.0 that version is only for a12 devices running 12.4.1

**Comment by miguelr4720** [comment]
Am On The Phone With My Mother But if anyone else having this problem and have you forgot the ReProvision is Dead how am Suppose to get Uncover 3.7.0?

**Comment by miguelr4720** [comment]
IS YOUR Outlook WORKING ???

**Comment by miguelr4720** [comment]
HOW DO YOU FIX THIS PROBLEM PLEASE HELP :( THATS WHAT AM ASKING? PLEASE I BEEN TRYING ALL NIGHT TO GET MY OUTLOOK WORKING AGAIN STILL NO LUCK :(

**Comment by miguelr4720** [comment]
> Oh and your supposed to use unc0ver 3.7.0 not 3.8.0 that version is only for a12 devices running 12.4.1

Is There any Fix for This Problem

**Comment by andre104623** [comment]
Yes uninstall 3.8.0 and then install 3.7.0

**Comment by andre104623** [comment]
You can use iso ninja

**Comment by andre104623** [comment]
iOS ninja

**Comment by andre104623** [comment]
Download the purple one 
![2A3D8BE1-0A83-46F9-8B67-563F2E3C7D47](https://user-images.githubusercontent.com/58851323/73069652-41430700-3e7c-11ea-9362-2130f9362eec.png)

**Comment by andre104623** [comment]
Cydia impactor is working again

**Comment by miguelr4720** [comment]
Ok I Install Uncover 3.7.0 iOS Ninja but the problem Outlook crashing still persist

**Comment by andre104623** [comment]
Ok well I’m going blind here not having any phone that can run unc0ver at the moment hmmm try uninstalling outlook or better yet sign in while your not jailbroken

**Comment by andre104623** [comment]
Some apps have jailbreak detectors and will error out when in a jailbroken state

**Comment by miguelr4720** [comment]
> Ok well I’m going blind here not having any phone that can run unc0ver at the moment hmmm try uninstalling outlook or better yet sign in while your not jailbroken

I Try Sign in while not jailbroken i get the cannot add account error 

when i am jailbroken the Outlook app just crash doesn't work

**Comment by andre104623** [comment]
That could be a problem with outlook try uninstalling and reinstalling

**Comment by miguelr4720** [comment]
> That could be a problem with outlook try uninstalling and reinstalling

I Try That I Uninstall it Reinstall it from the app store did a network reset and still the same bug

**Comment by andre104623** [comment]
If all that fails then I would not use outlook and use Apple mail and sync your outlook account with that

**Comment by miguelr4720** [comment]
Yes Apple Mail Works Fine Right now :)

**Comment by miguelr4720** [comment]
idk looks like Apple Might Patch it :( fuck apples lol

**Comment by andre104623** [comment]
Cydia might have an outlook patch I’ll look I have to turn on my iMac and Checkm8 my SE

**Comment by miguelr4720** [comment]
Hope their be a fix for this in the FUTURE :( This Apple thing is Making me pissed off

**Comment by andre104623** [comment]
Apple mail works fine when I’m jailbroken

**Comment by andre104623** [comment]
![D967278C-66D8-40FF-AF2D-1E64C3CAF06A](https://user-images.githubusercontent.com/58851323/73070469-659fe300-3e7e-11ea-8c7f-90ada319932f.jpeg)

**Comment by miguelr4720** [comment]
> Apple mail works fine when I’m jailbroken

Same Here Apple Mail Still Works is Just and Outlook App Issue Patch by Tim Cock :( Sucks

**Comment by andre104623** [comment]
Yeah I checked Cydia nothing there for outlook but there is jailbreak hiding apps on there that make is look like your phone isn’t jailbroken and lets you run the apps that blacklist jailbroken iPhones

**Comment by miguelr4720** [comment]
Whats the Name of The Tweak

**Comment by miguelr4720** [comment]
Just found and article on reddit and it looks like am not the only one having this problem 

https://www.reddit.com/r/jailbreak/comments/esp5fy/tip_do_not_update_microsoft_outlook_mail_in_the/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by miguelr4720** [comment]
https://www.reddit.com/r/jailbreak/comments/esp5fy/tip_do_not_update_microsoft_outlook_mail_in_the/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by miguelr4720** [comment]
AppStore++ doesn’t work so I can’t Downgrade

**Comment by miguelr4720** [comment]
Is there anyway I could downgrade Outlook? :(

**Comment by miguelr4720** [comment]
I really wish someone could fix it

**Comment by miguelr4720** [comment]
This is cuz of Version 4.21.0 it broke it last night 


APPLE IS RIDICULOUS

**Comment by miguelr4720** [comment]
I think this would be the last time I update apps in the AppStore

**Comment by miguelr4720** [comment]
use AppStore++ for A12 Use AppStore++ 0.9.5

Use iFile to Install Don’t Use Cydia 


https://www.ios-repo-updates.com/repository/cokepokes/package/com.cokepokes.appstoreplusplus/

HOLD DOWN Open In the AppStore on the app and Downgrade

**Comment by amydevs** [comment]
@andre104623 Wait, is cydia impactor working again??  👀👀

**Comment by miguelr4720** [comment]
I doubt To see Cydia Impactor Working Again 

APPLE HAS FUCK EVERYTHING

**Comment by JTCGaming** [comment]
If Cydia impactor doesn’t work, is there anything else I could use instead?

**Comment by miguelr4720** [comment]
Well Outlook has been block from Microsoft server anyone On Jailbroken Device will be block from using the App

**Comment by res1492** [comment]
> If Cydia impactor doesn’t work, is there anything else I could use instead?

Install appcake using safari by going their website www.iphonecake.com/app click install Appcake then follow instructions, trust the app then download Unc0ver from github using safari when it has downloaded tell it to open in appcake, it will open the app then  just install unc0ver from there, stay in the appcake app until it has finished (it has to extract unc0ver, resign it then install to your phone) after its done unc0ver will open fine.

**Comment by MaltronCraft** [comment]
> Am On The Phone With My Mother But if anyone else having this problem and have you forgot the ReProvision is Dead how am Suppose to get Uncover 3.7.0?

Someone fixed ReProvision, I’ll reply with the repo

**Comment by adamturbo** [comment]
Found an article about a new Jailbreak detection app called FlyJB. I tried it and it works on the latest Outlook version.

![25478C6D-A3A9-46A3-A122-9518EFD53774](https://user-images.githubusercontent.com/61048726/77218017-ee2abf00-6b61-11ea-8ab9-6d402098a254.jpeg)


https://piunikaweb.com/2020/03/12/want-to-bypass-jailbreak-detection-flyjb-makes-it-possible/
