### ISSUE TITLE
Tweaks in icleaner pro ‘Cydia Substrate Addons' are missing

### ISSUE THREAD

**Issue by waterun** [pwn20wndstuff/Undecimus#166]
I'm on 2.1.0 prerelease version, and install the new cydia substrate of saurik 0.9.7000. I could not find tweaks in icleaner pro 'Cydia Substrate Addons'. And when I quit the icleaner pro, the settings  won't be saved, such as 'language selection'. 
I had rejailbreaked for servral times,  the problem remains.

Another problem,  I turn off the preference of 'Load Daemons' when I rejailbreak, The OpenSSH would not work, so the phone could't be logon from remote ssh.

**Comment by Cryptiiiic** [comment]
@waterun they show up fine for me. Post your diagnostics exported from the unc0ver app.

**Comment by Samgisaninja** [comment]
This is not a code-level issue with unc0ver and is therefore closed. 

Technical support for your tweak setup will be provided on https://reddit.com/r/jailbreak
