### ISSUE TITLE
Springboard Crashes For No Reason Respring iOS 12.4

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1661]
when am using the Phone like Normal Running Unc0ver Jailbrake 12.4 iPhone XS Max and opening Application or Browsing the Phone The Springboard Crashes out of no Where and then it goes to the Respring by it self it’s there a way to fix this and stop my phone from being respiring by it self this is very annoying and I haven’t install any new Tweaks only but RocketBootstrap and PrefrenceLoader and I remove all tweaks and everyday my phone respiring by its own 1 time per day I keep having this respiring Problem please help me fix this  

**To Reproduce**
1. Any where on the Phone it Occurs 1 Time Perday
4.No Errors on Crash-reported 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: 12.4
 - unc0ver Version: 3.7.0 b3

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X
![44736600-F494-413F-9E97-1999D0C61900](https://user-images.githubusercontent.com/36649261/73570736-e80a4300-443a-11ea-8829-61805433670f.png)
] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

No Error Message

**Comment by miguelr4720** [comment]
Is there a way to fix this I don’t have no Tweak install and my phone respiring for no reason please help to fix this

**Comment by miguelr4720** [comment]
I hate seeing my phone respiring on it own for no reason

**Comment by miguelr4720** [comment]
can someone please help me this

**Comment by onisimus** [comment]
I updated to 13.3 for this reason. Kept putting my device in bootloop.

**Comment by miguelr4720** [comment]
same problem here
