### ISSUE TITLE
"unable to get debs for packages to repair" 

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1669]
I jailbroke and received the error "unable to get debs for packages to repair" at 18/30 then I press ok then it goes to home screen. If I try to re-jailbreak without rebooting, it goes to 1/30.

**Comment by CookieCoder15** [comment]
having the same problem here

**Comment by xMilesManx** [comment]
Same problem here as well. I tried to restore rootFS and try again but the issue persisted through multiple tries. 11 pro max.

Seems as though quite a bit of people on reddit also have this issue.

EDIT: Pwn says this is an issue with AltStore. The working alternatives are to use a signing service or to self sign until altstore is fixed.

**Comment by Moudoux** [comment]
Same issue here as well

**Comment by DaddyBoard** [comment]
Same issue!! Thank god its not only me...
@pwn20wndstuff heres some screenshots
![EDD2947B-68A4-40FE-9982-E121D7773F06](https://user-images.githubusercontent.com/48053193/74597036-00d84280-5050-11ea-99b0-e617641177c0.png)
![B204704F-2BF4-4157-987E-AC5A441348D7](https://user-images.githubusercontent.com/48053193/74597039-046bc980-5050-11ea-928d-6222703aaca1.png)

![5BA18C29-094C-49DA-A21A-CD157643DBA2](https://user-images.githubusercontent.com/48053193/74597037-02a20600-5050-11ea-9b45-bdfde9ff5d3e.png)

![5EC1C56B-ACAB-4906-91F8-AFF6BDF77D86](https://user-images.githubusercontent.com/48053193/74597032-fa49cb00-504f-11ea-88ba-254bedc979d4.png)
![BE5B7611-3937-4DA1-BE7A-3008046284F1](https://user-images.githubusercontent.com/48053193/74597033-ff0e7f00-504f-11ea-9036-0247b675d878.png)

**Comment by cooperbow88** [comment]
iPhone XR on iOS 13.3. Same issue.

**Comment by ghost** [comment]
@CookieCoder15 @xMilesManx @Moudoux @DaddyBoard Pwn tweeted out on twitter saying the solution was to go and self sign due to an issue with AltStore.
![zFKp3fu](https://user-images.githubusercontent.com/30735343/74597070-66570f80-500d-11ea-9310-540deda69cd6.png)

**Comment by mlgxyves** [comment]
iPhone 11 same Issue.
After reinstalling the App nothing works anymore.
![IMG_1061](https://user-images.githubusercontent.com/61098650/74597077-f66e7680-5058-11ea-8cbd-278250763fb5.PNG)
![IMG_1063](https://user-images.githubusercontent.com/61098650/74597078-f8d0d080-5058-11ea-9f5a-4fd2fd1073df.PNG)

**Comment by ghost** [comment]
@mlgxyves Try self-signing using something other than AltStore and try again.

**Comment by BS1997** [comment]
I had same problem.
After trying with IOSninja, it's done.

**Comment by ez0x** [comment]
iPhone 11 Pro Max. Same issue :(

**Comment by ez0x** [comment]
@BS1997 thank you it works for me after i used IOSninja

**Comment by ghost** [comment]
Ios ninja keeps crashing help @pwn20wndstuff

**Comment by sheharyarak** [comment]
Same thing here. It says jailbroken after i hit okay but there is no cydia.

![86391953_129480835043506_2999791015646199808_n](https://user-images.githubusercontent.com/31715063/74598849-eee5a800-502d-11ea-9a64-3cc13c1c1ade.jpg)

![86481982_331548287762286_999448527685812224_n](https://user-images.githubusercontent.com/31715063/74598835-c198fa00-502d-11ea-82bb-17b80d50be08.jpg)

**Comment by MrBlock5633** [comment]
> Ios ninja keeps crashing help @pwn20wndstuff

this happens to me as well, i click it and it just crashes:(

**Comment by SHYAZEN** [comment]
Me too

**Comment by pedrosoori** [comment]
I downloaded the ipa from altstore, ignition and iosninja and I have the same error all the time. I have the unable to resolve lzma to a deb error and the "unable to get debs for packages to repair"

**Comment by tazzmaniadevilz** [comment]
> @mlgxyves Try self-signing using something other than AltStore and try again.

I did do that but nothing changed

**Comment by andre104623** [comment]
All this has been fixed with unc0ver 4.2.1 I’m running 13.3 iPhone XR myself have no problems so far with this update
