### ISSUE TITLE
Doesn't have saurik repo [Unc0ver 2.0.2]

### ISSUE THREAD

**Issue by GNAHK** [pwn20wndstuff/Undecimus#167]
i don't know how to fix this issue. 
Does it happen bc of my device??? 
Please help me

**Comment by Ultra03** [comment]
Did you try adding it?

**Comment by Ultra03** [comment]
Are you talking about the Substrate beta repo or the Telesphoreo repo?

**Comment by GNAHK** [comment]
The telesphoreo

Vào Th 4, 19 thg 12, 2018 lúc 21:56 Ultra03 <notifications@github.com> đã
viết:

**Comment by Cryptiiiic** [comment]
@GNAHK why would it even have that repo. That repo is for iOS versions that don't enforce 64bit arch. iOS 10 and below. sbingner compiled and uploaded all those packages to his apt repo which is included in unc0ver. His apt repo is the new telsporeo.

**Comment by GNAHK** [comment]
Bc i need Cydia substrate to do st on iOSGods.com and MobileSubstrateDummyPackage can't solve this
