### ISSUE TITLE
4.0 jailbreak stopped working on iPhone 11 Pro after a couple reboots

### ISSUE THREAD

**Issue by Jarred-Sumner** [pwn20wndstuff/Undecimus#1670]
After jailbreaking successfully (screenshot at bottom), I installed some stuff from Cydia, rebooted, and now my phone is no longer jailbroken.

I am running iOS 13.3 (not 13.3.1). I don't think I did anything that would cause it to un-jailbreak. When I say "un-jailbreak", I mean the following:
- Unc0ver's app no longer shows "Re-jailbreak" in the button
- Cydia crashes on opening

Choicy & other apps reported "failed to load preferences bundle" in the Settings app. That's why I tried rebooting twice.

If I were to guess why: maybe the 13.3.1 update downloaded while jailbroken (automatic updates are off, it is not installed)? I'm not really sure how to verify this, but maybe a patch should be released that disables OTA entirely?

![image](https://user-images.githubusercontent.com/709451/74597163-0f523a00-500f-11ea-87c8-5eda96e284b3.png)

----

I am able to re-jailbreak once again after rebooting though.

**Comment by mrwulff** [comment]
Just so you know, this is a semi-tethered jailbreak, meaning it is supposed to do exactly what it is doing.  Once you reboot, it goes away
