### ISSUE TITLE
2bugs in JP4.0 ios13.3

### ISSUE THREAD

**Issue by Nero69s** [pwn20wndstuff/Undecimus#1671]
After Jp the iPhone 11pro max 13.3 you can’t download from AppStore. It’s stopped when the app in installing stage. Another bug is you can’t take screen video record when you press the recorded button and keep counting 3 2 1 And after that nothing happened.

**Comment by TimmyOVO** [comment]
Can not download apps from AppStore,screen video record works fine

**Comment by Nero69s** [comment]
No I can’t recording any thing. But if I turn off the JP I can download from AppStore and recording again.

**Comment by vschembari** [comment]
Can confirm. While jailbroken, apps download and "install" but icon is grayed out and cannot be opened. Screen recording and screen mirroring are broken. Carplay also is not working but is likely related to the previous issue. 
XS Max 13.3
