### ISSUE TITLE
4.0 AppStore downloads never finish

### ISSUE THREAD

**Issue by Movinggun** [pwn20wndstuff/Undecimus#1672]
If you are currently jailbroken the appstore will never finish installing applications, they will download then fail at the very end and not install. A temporary fix is to install apps when not jailbroken.

**Comment by hmoghani** [comment]
same here
iPhone 11
iOS 13.3

**Comment by Vladimirchevelle** [comment]
Same here iOS 13.3
iPhone 11 Pro Max

**Comment by rockqj** [comment]
Same here.
iPhone XR
iOS 13.3

**Comment by keroassad98** [comment]
Same here, iPhone XS iOS 13.3

**Comment by 7Iff5** [comment]
Same here. Apps never installs, got the message (in AppStore) that the app isn’t available at the moment.
Does not work even in Safe Mode, had to reboot the iPhone to install any Apps from the AppStore.
iPhone XS Max iOS 13.3

**Comment by lt-fancy** [comment]
Same here, iPhone XS Max iOS 13.3

**Comment by TimmyOVO** [comment]
Same here, iPhone XS iOS 13.3, stuck on installing then icon goes to gray
