### ISSUE TITLE
“There was an error loading the preference bundle for *tweak name*”

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1673]
PreferenceLoader isn’t loading the preferences for the tweaks

**To Reproduce**
1. Install a tweak with a preference page in settings
2. Go find it in settings
3. You will see the error (hopefully)
**Screenshots**

**Device (please complete the following information):**
 - iOS Version: iPadOS 13.3
 - iOS Device: iPad mini 5 (WiFi) iPad 11,1
 - unc0ver Version: 4.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by FalcoO0n** [comment]
Any fix
