### ISSUE TITLE
SMS and iMessage Notifications

### ISSUE THREAD

**Issue by crook47** [pwn20wndstuff/Undecimus#1674]
**Describe the bug**
While jail broken The notifications for a text message do not appear at all

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: XS Max
 - unc0ver Version: 4.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by hmoghani** [comment]
same for me. no notification. 
iPhone 11
iOS 13.3

**Comment by jloysch** [comment]
Same here. iPhone XR 13.3

**Comment by keroassad98** [comment]
Same here, iPhone XS iOS 13.3

**Comment by Grapplerone** [comment]
Same issue on IPhone 11 IOS 13.3

**Comment by drybonesification** [comment]
Experiencing same bug, iPhone xs max (11,6) ios 13.3 did notice other sounds and notifications work fine (ie incoming call)

**Comment by hmoghani** [comment]
mine got fixed somehow. I rejailbroke the phone, reinstalled cydia and cleared the cache with unc0ver. Updated all the packages. and notification is working now. Not sure if I got lucky or the rejailbreaking fixed it. I'll update once I restart and rejailbreak and if it doesn't work again.

**Comment by jloysch** [comment]
> mine got fixed somehow. I rejailbroke the phone, reinstalled cydia and cleared the cache with unc0ver. Updated all the packages. and notification is working now. Not sure if I got lucky or the rejailbreaking fixed it. I'll update once I restart and rejailbreak and if it doesn't work again.

Any updates?

**Comment by Grapplerone** [comment]
The temp fix I used is to initiate an ldrestart in terminal on the iPhone. It also fixed:

Carplay Mirroring
Screen Mirroring
Screen recorder

And my airdrop started working but I’m not sure if that’s what did it yet.

iPhone 11 IOS 13.3
