### ISSUE TITLE
Substitute-loader corrupt // FIXED in 4.0.3

### ISSUE THREAD

**Issue by stohle** [pwn20wndstuff/Undecimus#1678]
**Describe the bug**
Jailbreak is successful but substitute fails.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device:  11,6 (XS Max)
 - unc0ver Version:  4.0

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
2020-02-16 03:24:24.660 Undecimus[230:4536] [*] Corrupted
"usr/lib/substitute-loader.dylib"
2020-02-16 03:24:24.660 Undecimus[230:4536] [*] Need to repair
"com.ex.substitute".

**Comment by amydevs** [comment]
Substitute was also breaking for me on 12.4 with u0 4.0
