### ISSUE TITLE
Error in preference bundle - no tweaks working - latest 4.0 - pro max  

### ISSUE THREAD

**Issue by Vladimirchevelle** [pwn20wndstuff/Undecimus#1679]
**Describe the bug**
Installed tweaks and nothing is working.  Shows in settings but says an error loading preference bundle.

**To Reproduce**
Install any package from cydia and it will display the error under settings 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 11 Pro Max 
 - unc0ver Version: 4.0

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
nothing is loading on cydia 12.4 Unc0ver 4.0.0

**Comment by stohle** [comment]
![Image](https://i.imgur.com/ibor3dy.jpg)

I get this when trying to install anything
XS Max 12.4 u0 4.0

Looks like Substitute is completely broken for 12.4

**Comment by andre104623** [comment]
Unc0ver 4.0 doesn’t work for 12.4

**Comment by andre104623** [comment]
You were supposed to be on 13.3 on iPhone 11/iPhone XS period

**Comment by stohle** [comment]
![Image](https://i.imgur.com/CyeQJsg.jpg)

You really think pwn would say its supported when its not supported?

**Comment by Vladimirchevelle** [comment]
I’m on 13.3 iPhone 11 Pro Max, substitute is broken no matter how many times you jailbreak it has the same error for all tweaks zeppelin tetherme etc. jail broke it fine, I installed app sync unified to get around the no apps installing from App Store bug, still not getting notifications for iMessages, Cydia works for me, was blank at first but downloaded the packages after a few mins, things install like filza app cake work fine, but zero tweaks. Anybody have a work around till a fix is completed ?

**Comment by stohle** [comment]
@Vladimirchevelle Im looking into substitute as we speak. pwn did one hella job rewriting this for u0 4.0.
