### ISSUE TITLE
Cydia clear

### ISSUE THREAD

**Issue by cris028284** [pwn20wndstuff/Undecimus#1681]
After a successful jailbreak, device resprings( for a unsuslly long time based on other unc0ver jb) when finished, Cydia is in my home screen but when opened it just shows a clear screen before crashing - others seem to be having the same issue. Have tried restoring rootfs. 
Pressing reinstall cydia just freezes device and reboots. 

Issue seems to be after testing: after the device resprings. The device also reboots w the Apple logo 

Thus, you were jail broken but by having the phone reboot, you’re not in a jail broken state. 
No idea about a fix tho 

**Screenshots**
![7E640001-2EB5-4573-9CD9-A96D1CBF88C6](https://user-images.githubusercontent.com/61101850/74598761-74288700-5045-11ea-9cf3-12abe6600fff.png)

**Device (please complete the following information):**
 - iOS Version: iOS 13.2.3
 - iOS Device: iPhone 11
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
am having the same problem here

**Comment by miguelr4720** [comment]
how can it be fixed

**Comment by hamtramgram** [comment]
same exact issue here...

**Comment by shiv213** [comment]
Same here!

**Comment by andre104623** [comment]
What’s your guys iOS versions

**Comment by cris028284** [comment]
13.2.3

**Comment by andre104623** [comment]
You guys can go into unc0ver settings uncheck everything and check off reinstall Cydia then click jailbreak

**Comment by andre104623** [comment]
> 13.2.3

I know yours

**Comment by cris028284** [comment]
Reinstalling cydia causes our phones to freeze then reboot

**Comment by andre104623** [comment]
I could be your iOS version pwn said people with 13, 13.1, 13.2, and 13.3 will have the least problems pwn probably needs to update the jailbreak

**Comment by hamtramgram** [comment]
13.2 on XS Max for me

**Comment by shiv213** [comment]
13.1 on iPhone XR here

**Comment by shiv213** [comment]
Can confirm issue still exists on v4.0.1 - iOS 13.1 on iPhone XR

**Comment by hamtramgram** [comment]
Same issue in version 4.0.1 

The last answer of pwn gave me some hope for a better release soon...

![3264A7A3-92C5-4784-A043-E7C315895201](https://user-images.githubusercontent.com/38755729/74625992-804c3b80-514e-11ea-9993-daaa467e0c60.jpeg)

**Comment by hamtramgram** [comment]
version 4.0.2 resolved my issue ! Thanks 😊

**Comment by shiv213** [comment]
Still facing the same issue after numerous tries on iPhone XR iOS 13.1 v4.0.2 although it takes more tries to even get a successful jailbreak, most often facing #1696

**Comment by cris028284** [comment]
4.0.2 has resolved my issue.
