### ISSUE TITLE
Unc0ver app wont start

### ISSUE THREAD

**Issue by Shaq234** [pwn20wndstuff/Undecimus#1682]
When installing the app and verifying the certificate, when tapping on the app it just closes automatically. 

 - iOS Version: 13.3
 - iOS Device: iPhone 8 Plus
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by c1oneman** [comment]
not an unc0ver issue

**Comment by Shaq234** [comment]
> not an unc0ver issue

Where is the problem?

**Comment by c1oneman** [comment]
The 3rd party signing services (Toyota) are getting revoked from what I am seeing

**Comment by Shaq234** [comment]
It was TOYOTA certificate, I installed via AltStore and it opens
