### ISSUE TITLE
Games/apps crash after 1 or 2 minutes

### ISSUE THREAD

**Issue by keroassad98** [pwn20wndstuff/Undecimus#1683]
**Describe the bug**
Games/apps crash after using for a minute or 2, for example, call of duty

**To Reproduce**
1. Open call of duty
2. Play for a minute or 2
3. App crashes

Device:
 - iOS Version: 13.3
 - iOS Device: iPhone XS
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by sryisme** [comment]
Same device,iOS version,unc0ver version
Same situation.
Even I try unc0ver 4.0.1 and 4.0.2
Even in safe mode
I got same result.

**Comment by jayzee06** [comment]
Same issue here, the apps crash when opening or after 2 minutes. Same device and same iOS version
