### ISSUE TITLE
Unc0ver 4.0.0 12.4 Cydia Repos Sources Wont Load

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1684]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to Cydia
2. Click on Cydia
3. Scroll down to Source
4. See error No Errors and Nothing Happens in 12.4  Unc0ver 4.0.0 please fix

**Screenshots**
![CAACD716-5612-4508-A4C8-B501B246B6CA](https://user-images.githubusercontent.com/36649261/74599614-f7040e80-5052-11ea-80d5-5cadc073ee4c.png)
![DE239019-693D-4732-8024-3CF4AF09A589](https://user-images.githubusercontent.com/36649261/74599625-113dec80-5053-11ea-945f-adf53d7dbfc3.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
some one please help me with this and i cant find where to downgrade UnCover B1 Version

**Comment by amydevs** [comment]
I have the same issue, also installing essential updates spits out error code (255) (sorry, don't have a log, I didn't take time to screenshot it b4 downgrading). Also yes, the issue still occurs, after rootfs restore.

**Comment by miguelr4720** [comment]
hope they fix this it soon :)

**Comment by amydevs** [comment]
just tested again with 4.0.1, still broken
