### ISSUE TITLE
iphone does not rejailbreak after reboot

### ISSUE THREAD

**Issue by Magicalrudedude** [pwn20wndstuff/Undecimus#1687]
after you install tweaks and go back to the unjailbroken state and try to jailbreak again it gets stuck at the springboard loading icon and never boots.

**Device information:**
 - iOS Version: iOS 13.3
 - iOS Device: iPhone XR
 - unc0ver Version:  4.0.0

 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by idseventeen** [comment]
me too, iphone8p/ios12.0.1

**Comment by nooneyy** [comment]
same,
iphone 12,3 on 13.3

**Comment by vovtokare** [comment]
iPhone XR iOS 13.1.2
