### ISSUE TITLE
13.3 Jailbrake Apps Wont Install Being Jailbroken 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1688]
**Describe the bug**
Apps Wont Install from AppStore on The NEW Unc0ver Jailbrake 13.3 

**To Reproduce**
1. Go to AppStore
2. Click on Install Facebook or Any Apps
3. Go to Home Screen app Wont Install 
4. App wont Install Being Jailbroken i

**Screenshots**

![FB98F9E1-E1A1-4D7F-AED3-ECBBBE7884C4](https://user-images.githubusercontent.com/36649261/74600727-84e7f580-5063-11ea-8db7-cc05c1a6dbab.jpeg)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: 13.3 iPhone 11 Pro Max
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by O5MOR** [comment]
I hve the same problem bro, iphone XS, try reboot, install apps & re jailbreak... works for me, waiting for an official solution 👍🏼

**Comment by andre104623** [comment]
I don’t have any problems

**Comment by gabe-lucas** [comment]
As a temporary solution, install a working version of "AppSync".
Please see: [Pwn20wnd's tweet](https://twitter.com/Pwn20wnd/status/1229041582613000193).

**Comment by O5MOR** [comment]
> As a temporary solution, install a working version of "AppSync".
> Please see: [Pwn20wnd's tweet](https://twitter.com/Pwn20wnd/status/1229041582613000193).

Ty bro... work fr me... ”Appsync Unified v70.0”

**Comment by miguelr4720** [comment]
thanks

**Comment by miguelr4720** [comment]
fixed 4.0.1 Unc0ver 13.3
