### ISSUE TITLE
Failed to extract bootstrap and failed to inject library

### ISSUE THREAD

**Issue by rvsandre** [pwn20wndstuff/Undecimus#169]
iPhone 7, iOS 11.3.1, unc0ver 2.1.0

**Comment by rvsandre** [comment]
![Image](https://i.imgur.com/0MKf3VW.jpg)
![Image](https://i.imgur.com/loy1uvk.jpg)

**Comment by FivePixels** [comment]
#152

**Comment by wakeupk2** [comment]
Did u get fixed bro ?

**Comment by Cryptiiiic** [comment]
Duplicate of #152 as previously stated by FivePixels. Closing.
