### ISSUE TITLE
Uncover is no longer an open source project?

### ISSUE THREAD

**Issue by joeddoe** [pwn20wndstuff/Undecimus#1691]
Latest code on Github is more than 6 months old, but releases are still being made, code bundled with the release is old and had nothing from the latest release (I presume it's the same source code that an be found in the `master` branch I'm just lazy to check checksums). After building the app from source (or just reading sources) you can see it contains nothing about latest kernel, oob_timestamp or offsets. Additionally zipped source code is annoying to work with as it has no git history and you can't easily init submodules. 

Seeing this and activity on Github I can only conclude that Uncover is no longer open source and this is alarming to me, I have no interest in Uncover except for the code (which is awesome, thanks for the hard work) and not being able to read everything that will potentially run on my phone is terrifying.

Could you provide up to date source code that contains whole codebase to build `4.0.0` or can you update `README.md` so that people know they wont be getting working source code and that how it will be done (as that's how it was for the last 6 months)? 
In case no source code will not be provided please consider removing attached source code on the release page as it's  misleading and it provides false info about source code availability. 

Also please do not provide same response as in this issue https://github.com/pwn20wndstuff/Undecimus/issues/1644, I have no interest in prebuilt ipa or something like that, that's not what I'm interested in, before you could read all of the source code once the new version was released, why is this no longer the case?

**Comment by FocusedSG** [comment]
It was closed source months ago.

**Comment by joeddoe** [comment]
I did not know that, so much for the `This project is completely open source and it will be kept like it in the future` 😢 it's a real shame, they collect information from the community to be able to build the jailbreak and then they do not wanna share it back, hopefully @pwn20wndstuff and rest of the team will change their minds!

**Comment by NewGithubber35** [comment]
So much for all the trash talking about Coolstar’s Chimera being closed source. I use on my compatible Devices as it seems to cc’d much more stable. Going to switch to Checkra1n when i get the chance. Tired of the reboots and resprings... rushed project full of bugs. Soringtomize 5 has helped a lot to keep my tweak count down drastically improving stability. I don’t know why they have to rush it, just do the damn thing right. Quality over quantity

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by The-SamminAter** [comment]
@joeddoe do you know if they are even monitoring the issues then? They seem to use this only for releases. And if not, if there is a issues section that they do monitor?
