### ISSUE TITLE
Device crashes during respring process after jailbreaking

### ISSUE THREAD

**Issue by TrickShotMLG02** [pwn20wndstuff/Undecimus#1694]
**Describe the bug**
Unc0ver app just installed and clicked the jailbreak button. After finishing the jailbreak process I
pressed he respring button, the device is showing the normal "respring animation screen". After a few minutes the device crashes and reboots normally. Cydia is on the homescreen, but i can't open it, because the device doesn't respring.

**To Reproduce**
1. Go to 'unc0ver app'
2. Click on 'jailbreak'
3. Click on 'respring'
4. wait

**Screenshots**
![2020-02-16 14 03 20](https://user-images.githubusercontent.com/43967908/74605129-471bb900-50c5-11ea-9428-04ef29da18cb.png)
![2020-02-16 14 03 27](https://user-images.githubusercontent.com/43967908/74605130-48e57c80-50c5-11ea-9cd9-d8c62227bbc6.png)
![2020-02-16 14 30](https://user-images.githubusercontent.com/43967908/74605610-f064ae00-50c9-11ea-9f04-c24abfc994b9.png)

**Device (please complete the following information):**
 - iOS Version: 13.2.2
 - iOS Device: iPhone XR
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/4209769/diagnostics.txt)

**Comment by BlackJack8** [comment]
Same here on iPhone 12,5. (11 Pro Max)
Also happens with everything turned off except Load Tweaks, Load Daemons and Auto respring.

Turning these off will cause an instant reboot.

Tried Re-Downloading, Airplane Mode, Clearing Diagnostic Data and turning every setting off.

**Comment by TrickShotMLG02** [comment]
I tried the same things with the same result

**Comment by dablackmage** [comment]
Same situation on my iPhone XR 13.2

**Comment by TrickShotMLG02** [comment]
I have the same Problem with Unc0ver 4.0.1
The Respring isn't working correctly
(iPhone 11,8 XR)

**Comment by BlackJack8** [comment]
You can close the issue, as it has been resolved

**Comment by TrickShotMLG02** [comment]
How did you fix that?

**Comment by dablackmage** [comment]
Please reopen. This has not been addressed.

**Comment by BlackJack8** [comment]
The new unc0ver 4.0.2 update fixed the respring issue for devices under 13.3.
Tested on 2 devices:
iOS 13.2.3 iPhone 11 Pro Max
iOS 13.0 iPhone XS

**Comment by TrickShotMLG02** [comment]
How did you install the new version?

**Comment by BlackJack8** [comment]
With Altstore on Windows.
There are some good tutorials on Youtube.
When you've installed it, leave iCloud, iTunes and Altserver running (open with administrator privileges!) and connect your phone to the computer.
Now go to unc0ver.dev, download and save the ipa. Then you have the option to open it in Altserver, just click on that and you're done.

**Comment by dablackmage** [comment]
I am now on verison on 4.0.3 and on iPhone XR 13.2 beta and it still freezes on respring. so @BlackJack8 i wouldn’t say that it’s completely fixed.

**Comment by BlackJack8** [comment]
Try disabling "set get-task-allow", "Reload Daemons" and "disable revokes".

**Comment by TrickShotMLG02** [comment]
Still not working

**Comment by TrickShotMLG02** [comment]
Anybody has got a fix for that on iphone xr ios 13.2.2
