### ISSUE TITLE
deinitializing the Jailbreak freezes the device

### ISSUE THREAD

**Issue by PwnedC99** [pwn20wndstuff/Undecimus#1696]
**Describe the bug**
If you Jailbreak your device on step 30/30 where the deinitializing takes place the device freezes for estimated 3/4 seconds. I dont know if this is common so I'll leave this here.

**To Reproduce**
1. Go to Unc0ver
2. Click on Jailbreak
3. Wait until 30/30

**Device (please complete the following information):**
 - iOS Version: iOS 13.3
 - iOS Device: iPhone11,6 (XS MAX)
 - unc0ver Version: Latest 4.0.0

**Place an "x" between the brackets if true:**
 - [ X ] this is a bug others MIGHT be able to reproduce
 - [ X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ X ] this issue is present after a rootfs restore
 - [ X ] this issue is present on the latest version of unc0ver

**Comment by ogjuggy** [comment]
I have these 2 issues.

-IOS Version: 13.1.3
-IOS Device: iPhone 11
-unc0ver Version: 4.0.0

When jailbreaking, either it will show
"30/30 Deinitializing Jailbreak"
or
"30/30 Jailbreak Complete"
which will then freeze my phone or put it in a temporary bootloop.

**Comment by andre104623** [comment]
Could be your version of iOS

**Comment by andre104623** [comment]
Pwn did say 13 13.1 13.2 and 13.3 would have the least problems at first

**Comment by xxjoshmxx** [comment]
Did u sign it or use iOS ninja or similar signing software

**Comment by ogjuggy** [comment]
I signed with newest version of altstore.

**Comment by andre104623** [comment]
I use iOS ninja it’s better and AltStore doesn’t work with iPhone 11 max and 11 it’s on Reddit

**Comment by andre104623** [comment]
It’s the reason for most of the problems

**Comment by ogjuggy** [comment]
ok thanks i will try it

**Comment by ogjuggy** [comment]
> It’s the reason for most of the problems

the problem still occurs with iosninja.

**Comment by gabe-lucas** [comment]
This issue shows many of the symptoms of #1698. It could be the same root cause.

**Comment by shiv213** [comment]
iPhone XR on iOS 13.1 having same issue, on both v4.0.0 and v4.0.1 signed by both altstore and iosninja

**Comment by andrewfree** [comment]
Having this issue with iphone X on ios12 now.
