### ISSUE TITLE
iPhone XR "Assertion Failure" v4.0 iOS 12.4.1

### ISSUE THREAD

**Issue by mangledbottles** [pwn20wndstuff/Undecimus#1697]
**Describe the bug**
I have previously tried to jailbreak my iPhone XR iOS 12.4.1 when the previous supporting jailbreak became available, however, it never worked.
The same is happening now, I am getting an "Assertion Failure" now in step 1/30.

**To Reproduce**
Run the jailbreak and it occurs immediately

**Screenshots**
![IMG_0562](https://user-images.githubusercontent.com/22305511/74606089-72060d00-50c5-11ea-9b85-d97aeff24997.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.4.1
 - iOS Device: iPhone XR
 - unc0ver Version: v4.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by andre104623** [comment]
Sorry buddy you were supposed to update to 13.3 MAX firmware and stay there 12.4.1 never worked and will not work now

**Comment by andre104623** [comment]
Don’t think you updating now will do anything ether 13.3.1 is not jailbreakible

**Comment by andre104623** [comment]
12.4.1 12.4.2 12.4.3 and 12.4.4 are dead firmwares

**Comment by andre104623** [comment]
I also have the XR and was waiting on 12.4.1 and when unc0ver finally came guess what it didn’t work with the XR only XS and XS MAX
