### ISSUE TITLE
Unable to rejailbreak/Restore rootfs

### ISSUE THREAD

**Issue by CheeseSteakk** [pwn20wndstuff/Undecimus#1700]
After my iphone 11 pro max rebooted into non jailbreak state, i was unable to rejailbreak/restore rootfs. The app crashes and reboots at step 1.

**Comment by CheeseSteakk** [comment]
Im using altdeploy to sign the app

**Comment by andre104623** [comment]
Did you delete the 13.3.1 update from your phone?

**Comment by CheeseSteakk** [comment]
yes i did

**Comment by andre104623** [comment]
Use iosninja it’s the only one I got to work Reliably

**Comment by andre104623** [comment]
Ok there is 2 update files did you delete both

**Comment by CheeseSteakk** [comment]
iosninja dont work for me, cant even open the app, the certificate has been revoked for me

**Comment by CheeseSteakk** [comment]
yes

**Comment by andre104623** [comment]
Ok take screenshots of the settings of unc0ver

**Comment by CheeseSteakk** [comment]
![IMG_4F0086F060E1-1](https://user-images.githubusercontent.com/61115863/74607010-072df380-5110-11ea-88c2-dc14a531fd7d.jpeg)

**Comment by CheeseSteakk** [comment]
thats all that ive enabled

**Comment by andre104623** [comment]
![A2776AAC-01FF-4FC0-88A5-B4230C1F0AAC](https://user-images.githubusercontent.com/58851323/74607058-64d82680-50a3-11ea-9c8b-6945c8f101c8.png)
![1D36CA98-1CEC-4726-B0E2-60B971D8A30D](https://user-images.githubusercontent.com/58851323/74607060-686bad80-50a3-11ea-9ae7-e34276ef8eaa.png)
Do this

**Comment by andre104623** [comment]
It seems iPhone 11s are having more problems than most

**Comment by CheeseSteakk** [comment]
yup, tried the same setting before wanting to restore rootfs. I jailbroke another xs max and rebooted and it jailbroke it again just fine.

**Comment by andre104623** [comment]
Good

**Comment by andre104623** [comment]
So your ok now

**Comment by CheeseSteakk** [comment]
but the one that i wanted to re jailbreak is my personal 11 pro max, the xs max belongs to my bro

**Comment by andre104623** [comment]
Oh my bad

**Comment by CheeseSteakk** [comment]
i think they have to release an update for the 11 series of phones.

**Comment by andre104623** [comment]
If your trying to restore rootfs you need to turn off everything and only have that option checked off

**Comment by andre104623** [comment]
Also try reinstalling Cydia

**Comment by CheeseSteakk** [comment]
i tried for the rootfs by disabling everything. i also tried to enable the same setting given by u with the addition of reinstalling cydia.

**Comment by andre104623** [comment]
Pwn needs to fix the 11 and 11 pro also seems none one can see battery stats in settings

**Comment by CheeseSteakk** [comment]
finally able to rejailbreak after reinstalling all settings. Phew

**Comment by CheeseSteakk** [comment]
resetting i mean

**Comment by andre104623** [comment]
Good glad I could help

**Comment by fernandodiaz22** [comment]
> finally able to rejailbreak after reinstalling all settings. Phew

how did you solve the problem? im stuck at step 19/31
