### ISSUE TITLE
No Battery Usage Info

### ISSUE THREAD

**Issue by Chocolateismybaby** [pwn20wndstuff/Undecimus#1702]
I can't view my battery usage information in settings.

**To Reproduce**
Go to Settings 
Tap Battery
It won't load any information 

**Screenshots**
![287F6667-5EB2-4BFD-89E9-9A29C7CC8903](https://user-images.githubusercontent.com/59924070/74606968-8524d700-50dd-11ea-86e1-2412975fbe0e.png)
 

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 11
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [idk] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

**Comment by andre104623** [comment]
Same here iPhone XR 13.3

**Comment by andre104623** [comment]
The jailbreak just came out I’m sure it will be fixed

**Comment by PwnedC99** [comment]
Can confirm, iPhone11,6 13.3

**Comment by hmoghani** [comment]
Same here, iPhone12,1 - iOS 13.3

**Comment by CloneVince** [comment]
Fixed with 4.0.1

**Comment by miguelr4720** [comment]
fixed Closed the case Please thanks

**Comment by Grapplerone** [comment]
Fixed for me in 4.01

iPhone 11 IOS 13

**Comment by lt-fancy** [comment]
fixed in 4.0.1
iPhone xs max(China) 13.3

**Comment by miguelr4720** [comment]
now please closed the issue  4.0.1 Fixed
