### ISSUE TITLE
iPhone 11 Pro Max (12,5) IOS 13.3 (UNCOVER 4.0)

### ISSUE THREAD

**Issue by Moddingmad** [pwn20wndstuff/Undecimus#1703]
I have tried all possible methods of installing the iPa. But the jailbreak process fails at the same point during the JB process with every method. 

I managed to grab a still image from a video of where the process crashes. 
Many users I have contact with on Discord report the same issue. on A13 devices 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/4210406/diagnostics.zip)
![IMG_0374](https://user-images.githubusercontent.com/38045982/74609504-7db3fc80-50e2-11ea-84d4-4df487867eac.JPG)

**Comment by stohle** [comment]
go to settings, scroll down and click "share diagnostics data" choose "copy" and paste it here as a comment

**Comment by JeffResc** [comment]
I am experiencing the same issue on 4.0.1 (iPhone 11 Pro Max, 13.3). [[View Diagnostic Log](https://pastebin.com/DEJ8JeiN)/[View Screenshot](https://imgur.com/a/WykuWro)].

**Comment by Nodewarrior** [comment]
Yay!!!!! I got it working guys iPhone pro max 13.3 
![EA786D54-A49E-4575-93B4-A413DE7F75E1](https://user-images.githubusercontent.com/5001440/74779910-12923380-5264-11ea-96f1-148c8039aaec.png)

Please try this! 
1. Reset all the settings that’s the only way! 
2. And make sure you switch on, off and on the tpfo 
3. Click on jail break it works! Atlast whew

**Comment by JeffResc** [comment]
@Nodewarrior Clearing the settings in Unc0ver or iOS settings? If iOS settings, which specific button? Thank you!

**Comment by Nodewarrior** [comment]
> @Nodewarrior Clearing the settings in Unc0ver or iOS settings? If iOS settings, which specific button? Thank you!

Oops sorry i didnt mention. Reset all the Ios settings, meaning General->Reset-> Reset all settings.

**Comment by rootshll** [comment]
O
