### ISSUE TITLE
No Success iPhone 11 Pro Max 13.3

### ISSUE THREAD

**Issue by ianrod30** [pwn20wndstuff/Undecimus#1705]
**Describe the bug**
4.0.1 still has not fixed any issues with jailbreaking my device, 0% success rate. Reboots instantly after tapping jailbreak.

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone12,5
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/suTqiqb3

**Comment by JDLHiguera** [comment]
Also happening to me. Here are the logs: 
https://pastebin.com/fiDdnMjP

**Comment by JeffResc** [comment]
Same issue here. [[View Diagnostic Log](https://pastebin.com/DEJ8JeiN)/[View Screenshot](https://imgur.com/a/WykuWro)].

**Comment by ScenicJaguar101** [comment]
Same here
