### ISSUE TITLE
I still don't get iMessage notifications.

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1707]
**Describe the bug**
Hey, so I still don't get iMessage notifications.

**To Reproduce**
1. Get someone to message you.
2. The notification won't show up.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.0.1 

**Place an "x" between the brackets if true:**
 - [(Not sure)] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [(I haven't tried)] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by CloneVince** [comment]
Still same with XS Max 13.3 (Unc0ver 4.0.1)
Ldrestart fix the problem when needed.

**Comment by miguelr4720** [comment]
please fix this problem

**Comment by Cameron12533439** [comment]
Im having the same issue on XS Max 13.3

**Comment by miguelr4720** [comment]
am having the same problem too

**Comment by miguelr4720** [comment]
please fix this :(

**Comment by miguelr4720** [comment]
this is crazy lol

**Comment by Grapplerone** [comment]
I still have this issue, only way to fix is ldrestart in terminal.

iPhone 11 IOS 13

**Comment by keroassad98** [comment]
Installed the tweak “power selector” and fixed it by doing an Ldredtart, temporary fix I guess

**Comment by heyitsblink** [comment]
*Crying face* me too.. even after I installed 4.0.1 through AppCake.

**Comment by keroassad98** [comment]
> _Crying face_ me too.. even after I installed 4.0.1 through AppCake.

Try to do the trick with power selector, my notifications are working fine now

**Comment by Cameron12533439** [comment]
I’ve tried ldrestart but it still doesn’t work. Idk I’ll keep trying it

**Comment by keroassad98** [comment]
> I’ve tried ldrestart but it still doesn’t work. Idk I’ll keep trying it

It took me a bit to get everything to work. I forced rebooted (volume up, down, power button) restored Root, re-jailbroke, then used icleaner and cleaned everything related to jailbreak and Cydia, then used power selector and installed apsync unified (which also fixed the App Store big) and then notifications started working again. Hopefully Pwn will fix it soon

**Comment by lt-fancy** [comment]
Hey guys, check this out:
[https://www.reddit.com/r/jailbreak/comments/f4k1on/discussion_unc0ver_400_jailbreak_bugs_and_issues/](url)
I've fixed SMS and iMessage bug

**Comment by heyitsblink** [comment]
The PowerSelector fixed it for me (ldrestart, I believe). 

Anyone having issues with iMessage not showing image thumbnails?

**Comment by miguelr4720** [comment]
please fix :(
