### ISSUE TITLE
unc0ver 4.0.1 respring loop

### ISSUE THREAD

**Issue by D4N2xIL** [pwn20wndstuff/Undecimus#1708]
**Describe the bug**
Upon completion of jailbreaking the device goes into respring loop

**To Reproduce**
1. Go to unc0ver 4.0.1
2. Click on “Jailbreak”
3. Wait until it successfully completes

**Screenshots**
None

**Device (please complete the following information):**
 - iOS Version: 13.2.3
 - iOS Device: iPhone XS 64GB
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
None

**Comment by Hauteknits** [comment]
Wdym by respring loop? Did you disable auto-respring and if so, do you get to step 30/30?

**Comment by pascalchristian** [comment]
I think same here https://github.com/pwn20wndstuff/Undecimus/issues/1704
