### ISSUE TITLE
Apple Smart Battery Case will not charge phone when jailbroken

### ISSUE THREAD

**Issue by pdxtechmike** [pwn20wndstuff/Undecimus#1711]
**Describe the bug**
I thought something was off when I went to take my phone with it’s smart battery case off the charger. My phone was at 4% battery and the charging case was at 100% battery after 12 hours of charging. I then plugged it back in and it still refused to charge the phone. I unplugged it and removed the battery case and both charge independently just fine. When inserting the phone back into the case it notifies that it’s charging and then immediately stops charging the phone. I have RootfS restored and have no tweaks installed. I experienced this same problem on 12.4 with unc0ver and was told by someone to enable “USB accessories” under “allow while phone is locked” in passcode settings but this “fix” has no affect this time.

**To Reproduce**
1. Jailbreak w/ unc0ver and plug in the smart battery case with phone inside of it (will not charge)
2. Plug each device in independently to verify charging is working at all (works)
3. Take device out of case and re Insert to see charging notification which goes away immediately
4. Charging while phone is in its case not jailbroken it charges normally.

**Screenshots**
NA

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS Max
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
same here please fix

**Comment by dinol1187** [comment]
Same issue!!

**Comment by VIXIVIXIV** [comment]
Possibly related: accessories like HDMI and VGA adapters also do not work when jailbroken; ldrestart does not fix this. Charging normally does work.

**Comment by dinol1187** [comment]
Found a fix for this.. after you jailbreak your phone. Remove case from phone and then put the case back on.

Hope this helps

**Comment by ouzmno** [comment]
> Found a fix for this.. after you jailbreak your phone. Remove case from phone and then put the case back on.
> 
> Hope this helps

This way is just working. Thanks.

**Comment by DB008899** [comment]
This is still not fixed and for me the workaround doesn’t work as my smart battery case doesn’t charge my phone

**Comment by ouzmno** [comment]
> This is still not fixed and for me the workaround doesn’t work as my smart battery case doesn’t charge my phone

I believe you should pull out your iphone from the case before rejailbreaking and after finishing the jailbreak, you can insert and use your case as normal.
