### ISSUE TITLE
Facetime/Facetime Audio Fails Immediately While Phone Calls Work Fine

### ISSUE THREAD

**Issue by gitgud191** [pwn20wndstuff/Undecimus#1713]
Facetime and FT Audio both fail immediately on both ends if one or more of those involved is on Unc0ver 4.0.0 or 4.0.1

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: XS Max
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by miguelr4720** [comment]
same here

**Comment by KelwinP** [comment]
Long time connecting
