### ISSUE TITLE
Unc0ver 4.0.1 iOS 13.3 Asking Apple ID Passwords Bug

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1714]
Sometimes in my Home Screen i get box asking me to enter my Apple ID Password this issue happens Randomly 

**To Reproduce**
1. Go to Home Screen
2. Click on Settings 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 11 Pro Max
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by nanawalke** [comment]
hello friend

My unc0ver app work

100% work

Unc0ver App Open > Seeting > Export TFP0



Thanks...

**Comment by miguelr4720** [comment]
i did the bug got fixed for now hopefully it dont happen again
