### ISSUE TITLE
Cydia crashing after jailbreak (also Cydia has the old icon for some reason)

### ISSUE THREAD

**Issue by tempasta** [pwn20wndstuff/Undecimus#1717]
Device (please complete the following information):

iOS Version: 13.1.3
iOS Device: iPhone XR
unc0ver Version: 4.0.1
Place an "x" between the brackets if true:

[ x ] this is a bug others will be able to reproduce
[ x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
[ x ] this issue is present after a rootfs restore
[ x ] this issue is present on the latest version of unc0ver

Even re-jailbreaking or changing the settings doesnt work.

**Comment by tempasta** [comment]
This bug is still is on 4.0.2

**Comment by andre104623** [comment]
It’s because of your iOS version

**Comment by andre104623** [comment]
Pwn is working on the odd firmwares that’s why everyone said including me update to 13.3 and stay there

**Comment by tempasta** [comment]
Well ICrackUrIDevice always tells us to be low as possible.
