### ISSUE TITLE
4.0.1 for 6s cydo returned an error code (255)

### ISSUE THREAD

**Issue by xuefer** [pwn20wndstuff/Undecimus#1718]
When installing tweak it fail with: cydo returned an error code (255)

Jailbreak stuck on respring if Reload daemon enabled

Since my 3.8.0b1 was outdated i jailbreak using 4.0.1 with daemon reload disabled and then rejailbreak using 3.0.8b1 successfully

iPhone 6s 12.4

**Comment by stohle** [comment]
Why are you not using checkra1n to jailbreak?

**Comment by xuefer** [comment]
> Why are you not using checkra1n to jailbreak?

i own no mac. checkra1n do not support windows/linux before, but it do support linux now, thanks god, will try
