### ISSUE TITLE
Uncover crashes and reboots Iphone 11 upon clicking Jailbreak

### ISSUE THREAD

**Issue by EggyEgo** [pwn20wndstuff/Undecimus#1719]
Every time I click Jailbreak in Uncover the process stops at 1, and the phone proceeds to reboot. This happened after I had clicked the re-jailbreak button while still in a jailbroken state. No matter how many times I reboot, restart, or try to Restore Root it won’t work and the phone continues to reboot. I left a few screenshots of the diagnostics at the bottom to see if anyone knows what is going on with it:,))

![3C40AEED-7168-4C99-AD82-52BE81AD6E86](https://user-images.githubusercontent.com/61152053/74661208-1f782f80-515d-11ea-8c2b-2573c0693f98.png)

This is another issue which I don’t know what it correlates to exactly, but if anyone wants to take a look go ahead:,)
![7CF66BCE-59F4-4E0D-B840-E3D9CF442986](https://user-images.githubusercontent.com/61152053/74661229-28690100-515d-11ea-95f2-b1f40b349060.png)

 - iOS Version: 13.3
 - iOS Device: Iphone 11
 - unc0ver Version: 4.0.1

**Comment by lukej1129** [comment]
im on xr 13.3 and the same thing happens

**Comment by lukej1129** [comment]
ok well soft resetting worked for me :).

**Comment by lukej1129** [comment]
ok I just waited 30 seconds after my phone was turned on, then jailbroke and it worked.

**Comment by EggyEgo** [comment]
> ok I just waited 30 seconds after my phone was turned on, then jailbroke and it worked.

It still resets on my end after a few tries

**Comment by spanishcop** [comment]
I'm having same issue..... I'm on 13.3 with iPhone 11 pro.  Click the jailbreak button and phone just reboots/restarts and there are no changes that I can see to iphone nor is cydia installed.

**Comment by computersteve** [comment]
Happening to me on latest Uncover with iPhone 11 Pro D421AP on 13.0 build 17A577
