### ISSUE TITLE
./substrate does not work on 2.1.0 12/17 and later

### ISSUE THREAD

**Issue by gnawh** [pwn20wndstuff/Undecimus#172]
Ran jailbreak without tweaks loaded (X, 11.4 b3). 
Typically, running substrate starts tweaks no problem after respring.

/etc/rc.d/substrate does not work on versions newer than 2.1.0 on 12/16. 

12/17 and 12/19 versions both do not load tweaks after running the command. 

Ran as root, su, tried killall -9 SpringBoard, backboardd, ldrestart, etc. 

If possible, could you add this command as a button on Unc0ver? That way we don't have to run it through a terminal client (either Shelly or ssh).

**Comment by jakeajames** [comment]
There was an issue with hsp4 breaking until a few commits ago (and thus substrate + jailbreakd would be broken as well). Are you running the latest commit?

**Comment by gnawh** [comment]
Not the latest commit, just the latest pre-release.

**Comment by jakeajames** [comment]
Try the latest commit

Il giorno mercoledì 26 dicembre 2018, gnawh <notifications@github.com> ha
scritto:

**Comment by pwn20wndstuff** [comment]
You need to delete /var/tmp/.substrate_disable_loader before loading it.
