### ISSUE TITLE
Third party keyboards not working

### ISSUE THREAD

**Issue by danaholic86** [pwn20wndstuff/Undecimus#1720]
**Describe the bug**
Third party keyboards do not work after jailbreak

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: XS Max
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by shayshtern** [comment]
Here also the same issue!

**Comment by shayshtern** [comment]
RootFS doesn’t help.
