### ISSUE TITLE
Tweaks not loading or installing on iOS 12.4

### ISSUE THREAD

**Issue by ccdffddfddfdsfedeee** [pwn20wndstuff/Undecimus#1722]
**Describe the bug** (A clear and concise description of what the bug is and what you expected to happen)
Tweaks do not load after jailbreaking and packages do not install

**To Reproduce**
1. Open unc0ver
2. Click on jailbreak
3. Click OK to respring
4. Tweaks did not load

**Screenshots** (If applicable, add screenshots to help explain your problem)
https://i.imgur.com/4QWyJ6W.jpg
https://i.imgur.com/ajM8rFm.png

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPad 6
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs** (If applicable, add logs or error messages here)
https://pastebin.com/H8cTmstE

**Comment by gokaybalci** [comment]
Exact same problem. Did you try enabling Restore RootFS?
RootFS method did not solve it for me, but for some people it worked.

**Comment by miguelr4720** [comment]
same problem here

**Comment by miguelr4720** [comment]
THIS ARTICLE HAS BEEN MOVED 

https://github.com/pwn20wndstuff/Undecimus/issues/1709
