### ISSUE TITLE
Unsupported Jailbreak 13.3 beta 4

### ISSUE THREAD

**Issue by lyses** [pwn20wndstuff/Undecimus#1723]
My device is XS Max 64GB and I am currently running ios 13.3 beta 4. Yesterday I downloaded unc0ver jailbreak 4.0.0 and later also 4.0.1 but when I try to run the app, the status says "Unsupported". Could you please fix it? A screen shot is attached.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version:  13.3 beta 4
 - iOS Device: XS Max 64GB
 - unc0ver Version:  4.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error 
![C0556D7E-FEF6-4436-BECE-D11C892D0703](https://user-images.githubusercontent.com/52870279/74669105-c7661b00-51a6-11ea-8093-8ac3e773d2f1.png)
messages here.

**Comment by stohle** [comment]
13.3 beta 4 is indeed unsupported

**Comment by lyses** [comment]
May I please know why? It is certainly a firmware version between ios 13.0 and 13.3, so why would it be unsupported?

**Comment by Beastandcool** [comment]
Youe were told to update to 13.3 weren't you. This could have been avoided if you listened

**Comment by lyses** [comment]
If you say so ... In my opinion it wasn't made clear enough that beta versions wouldn't be supported. The announcement mentioned "devices A12-13 @ios 13.0-13.3". Anyway if this is the case, are you at least planning to adjust the jailbreak to some of the betas in the near future?
