### ISSUE TITLE
BUG - UNSUPPORTED

### ISSUE THREAD

**Issue by jorevi25** [pwn20wndstuff/Undecimus#1724]
iOS  13.3
Iphone 6S
alt server

I cannot install  unc0ver 4.0.1
Said    UNSUPPORTED"

![IMG_0021](https://user-images.githubusercontent.com/54463833/74674008-6c203280-517e-11ea-82ed-6ebde03c7287.PNG)

**Comment by ccdffddfddfdsfedeee** [comment]
iOS 13 is not yet supported for A11 and under. Use checkra1n

**Comment by alikhan112** [comment]
When they goons fix this

**Comment by ZakDumasia** [comment]
No one knows how long but this has happened to me before and it didn’t  take very long to fix just wait a month and it surely will be fixed
