### ISSUE TITLE
No sms/iMessage notification

### ISSUE THREAD

**Issue by 7Iff5** [pwn20wndstuff/Undecimus#1725]
With Unc0ver 4.0.0 and 4.0.1
I do not have any notifications when I receive an iMessage or sms, even I got no ringtone played !
So I don’t know when receiving sms/imessage. My Apple Watch do ring when receiving not the iPhone.
I tried in Jailbroken state : Does not Work
Safe Mode : Does not Work
Rebooted in non-jailbroken state : Works

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS Max
 - unc0ver version : 4.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
https://www.dropbox.com/s/orpantizvbn2zea/Fichier%2017-02-20%2019%2043%2015.txt?dl=0

https://www.dropbox.com/s/gqohqfmi7b19i45/Fichier%2017-02-20%2019%2044%2040.txt?dl=0

Edit : I comfirm, ldrestart solves the problem. Waiting to see if it occurs again and need to ldrestart one more time

**Comment by miguelr4720** [comment]
THIS ARTICLE HAS BEEN MOVED


https://github.com/pwn20wndstuff/Undecimus/issues/1707
