### ISSUE TITLE
IPhone XR 13.2 - Multiple Issues

### ISSUE THREAD

**Issue by ScriptKlddie** [pwn20wndstuff/Undecimus#1728]
**Describe the bug**
Issue 1: Freeze on all tasks completed. 30/30. Phone is unresponsive. After some time, reboots.

Issue 2: Jailbreak runs smoothly. Spring board restarts. Runs for a very long time and then phone reboots

Issue 3: When trying to reinstall cydia, device will freeze on step 25 (Reinstalling cydia). It will then eventually reboot.

Issue 4: Device freezes on step 21 (Extracting bootstrap). Eventually reboots.

**To Reproduce**
Go to unc0ver and press jailbreak. All issues listed can happen. However, issue 3 can be replicated by performing the jailbreak process with the option reinstall cydia turned on. The reason for this is issue 2. The jailbreak process completes successfully in issue 2 yet after a while in the spring board, the phone reboots, essentially removing the jailbreak. Which is why one would want to reinstall cydia.

**Screenshots**
NOT AVAILABLE

**Device (please complete the following information):**
 - iOS Version: 13.2
 - iOS Device: Iphone XR
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Unavailable

**Comment by ScriptKlddie** [comment]
Re-upload of a previously closed issue since the recent update of unc0ver 4.0.2 had not fixed any of these issues.

**Comment by dablackmage** [comment]
Same. iPhone XR 3.2. Same issues on 4.0.2

**Comment by Silvre** [comment]
Also tagging along and saying it doesn't work for me as well, XR @ 13.2.  I've tried all the tips that people have suggested but to no avail.  It seems to crash upon respring if jailbreak was successful, negating the jailbreak entirely.

**Comment by pascalchristian** [comment]
Issue 1 is same here https://github.com/pwn20wndstuff/Undecimus/issues/1704
Multiple reports not just on XR but on other A12 devices <13.3

**Comment by Tempris** [comment]
> Issue 1 is same here #1704
> Multiple reports not just on XR but on other A12 devices <13.3

Same here with XR 13.2 on latest v4.0.3 update. Still freezing at reinstalling cydia and at 30/30 until after 5-10 mins it restarts and isn’t jail broken. I’ve tried everything I’ve found to try without attempting something that would break it.
