### ISSUE TITLE
AutoFill Passwords with 3rd Party Apps is broken

### ISSUE THREAD

**Issue by ianrod30** [pwn20wndstuff/Undecimus#1729]
**Describe the bug**
Using Autofill with Password with a third-party app, not iCloud Keychain refuses to launch. Whether it's tapping "Passwords" above the KeyBoard or using an App's built-in AutoFill button.

**To Reproduce**
1. Go to Any App with autoFill Password Compatibility, I used Twitter for example
2. Click on "Passwords" or Dedicated password manager button.
3. Refuses to launch password manager
**Screenshots**
Heres a video: https://streamable.com/6yzyc

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone12,5
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Laiteux** [comment]
I am experiencing the exact same issue, can I please know have this been closed?
