### ISSUE TITLE
Freeze and reboot 

### ISSUE THREAD

**Issue by nosbourg** [pwn20wndstuff/Undecimus#173]
Hi bro must comment with you that a few minutes ago i did rootfs, did semirestore rollectra to turn iphone factory default rejailbreak without install any tweak, installed substrate and with Phone charging when i open cydia while refresh repos iphone freeze and reboot it happens to me 2 times with the same symptons exactly the same, m37 user told me yesterday the same while charging.thanks in advance

**Comment by nosbourg** [comment]
Im on 6s plus 11.3.1 unc0ver last version from this GitHub

**Comment by coenkcore** [comment]
@nosbourg try using v 2.0.2, i have used for 7 days v 2.0.2 on 6s 11.2.6 no random reboot or freezing
In v 2.1.0 it's not ready for production the label is pre-release

**Comment by xxHoBoZxx** [comment]
@nosbourg, I was having the same issue with cydia with the new substrate and v 2.1.0. I installed NoSub /w paypal and set cydia in the options. My freezing stopped once I did that. Don't know if it will help you or not, but it helped me.

**Comment by xxHoBoZxx** [comment]
@nosbourg, I was having the same issue with cydia with the new substrate and v 2.1.0. I installed NoSub /w paypal and set cydia in the options. My freezing stopped once I did that. Don't know if it will help you or not, but it helped me. I am on a 6s 11.2.6, btw...

**Comment by xxHoBoZxx** [comment]
I renamed the vsd daemon and it solved my cydia freezes. I was having the exact same problem with cydia freezing and rebooting when refreshing sources. Once I remaned the vsd daemon, it stopped.

**Comment by iM4CH3T3** [comment]
Thx will do that now ...
Got freezes already 5-6 times in 2 days ...

**Comment by xxHoBoZxx** [comment]
you have to reboot and re-jailbreak afterwards. I just renamed it to videosupscriptionsd.bak in /usr/libexec

**Comment by iM4CH3T3** [comment]
Yes I did thx

**Comment by iM4CH3T3** [comment]
It’s fixed for me... since I renamed vsd the freezing while refreshing sources has stopped.

**Comment by s8ad8in** [comment]
> @nosbourg try using v 2.0.2, i have used for 7 days v 2.0.2 on 6s 11.2.6 no random reboot or freezing
> In v 2.1.0 it's not ready for production the label is pre-release

Hey lucky man, that's great for somebody who is trying things become fix again, sometimes feel sad in choosing known/unknown options, however, I am such a fan of breaking tools but unfortunately there was no luck, I wonder if your options, where the right fit setup in the Settings button which one to check on/off for having the usability like yours.

Let me write what I can see now happening:
![img_3524](https://user-images.githubusercontent.com/22406627/50669628-85086b80-0ff0-11e9-970a-0c0ddaf640e0.PNG)
![img_3523](https://user-images.githubusercontent.com/22406627/50669635-8c2f7980-0ff0-11e9-8723-c4a1458a5d2d.PNG)
![img_3522](https://user-images.githubusercontent.com/22406627/50669641-8fc30080-0ff0-11e9-999f-37d042ca45e3.PNG)
@pwn20wndstuff @iM4CH3T3

**Comment by nosbourg** [comment]
Thx for your help guys havent got any freeze reboot since update to las unc0ver and substrate👌👍

**Comment by Cryptiiiic** [comment]
@nosbourg So I can close this issue?
