### ISSUE TITLE
v4.0.2 release installs v4.0.1

### ISSUE THREAD

**Issue by SavageAUS** [pwn20wndstuff/Undecimus#1734]
Downloaded v4.0.2 from github and tried to install with AppCake but as seen in appcake the version is wrong. 
![7E1DCE08-2361-4103-8990-6F78E689A624](https://user-images.githubusercontent.com/17326832/74694904-e82f7e80-5241-11ea-94eb-8789e40ddbfa.png)

**Comment by SavageAUS** [comment]
![42D8B089-EEFA-4373-85E0-21A677FD7D6D](https://user-images.githubusercontent.com/17326832/74695070-8a4f6680-5242-11ea-867a-34d742d36623.png)

**Comment by ccdffddfddfdsfedeee** [comment]
![](https://i.imgur.com/W4pXqX9.jpg)

**Comment by tempasta** [comment]
pwn20wnd just forgot to edit it to v4.0.2. Dont worry you're still on v4.0.2 not v4.0.1
