### ISSUE TITLE
iMessage thumbnail images not loading

### ISSUE THREAD

**Issue by samdh90** [pwn20wndstuff/Undecimus#1735]
**Describe the bug**
I noticed that thumbnail images in iMessage are not loading while in JB mode. None of them are loading but when tapped, they load. If I reboot and don’t kick the JB on, the thumbs load as normal. This bug is present in both WiFi and cellular networks. 

**To Reproduce**
1. Go to iMessage
2. View past messages with images
3. Notice they do not load at all. 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by samdh90** [comment]
Here is a good screenshot if the issue. 
![0C330D8F-628D-4E86-8B32-D5B8FECE18DC](https://user-images.githubusercontent.com/61171359/74696588-dcde4380-51ac-11ea-931e-4a092b08536e.jpeg)

**Comment by ROK5TAR** [comment]
I get the same thing. I notice it happens when I use the share button and not when I send pic within iMessage bar. iPhone 11 Pro on 13.3 jailbroken with 4.0.2

**Comment by hferran1** [comment]
Same issue here, iPhone 11  on iOS 13.3 with unc0ver 4.0.2

**Comment by neta540** [comment]
Same issue, iOS 13.3, unc0ver 4.0.2, XS Max

**Comment by inline6power** [comment]
Same issue on uncover 4.0.3 and xs Max
