### ISSUE TITLE
Error crash game

### ISSUE THREAD

**Issue by HDteen** [pwn20wndstuff/Undecimus#1736]
**Describe the bug**

**Device (please complete the following information):**
 - iOS Version:  13.3
 - iOS Device: iPhone XS MAX
 - unc0ver Version: 4.0.0 , 4.0.1, 4.0.2

** Open the game PUBG mobile, Call of Duty Mobile, Arena of Valor, ... about 1 minute to 2 minutes to crash

**Not receiving notifications from message / imessage ..

**Comment by sryisme** [comment]
I got the same status too.
Open the game Contra:Return about 1-2 minutes then crash.
Could somebody give me some solutions？

iOS Version: 13.3
iOS Device: iPhone XS 
unc0ver Version: 4.0.0 , 4.0.1, 4.0.2

**Comment by orakanggo** [comment]
same with me.. I played Arena of valor and got crash after 1 minute

iOS Version: 13.3
iOS Device: iPhone Xr
unc0ver Version: 4.0.0 , 4.0.1, 4.0.2

**Comment by keroassad98** [comment]
Had the same issue, I downloaded the tweak “liberty lite beta” and turned on the settings for all those apps and games that crash, after that all works fine

**Comment by HDteen** [comment]
I tried running version 4.0.3 but I still get the game crash error and didn't notice the message

**Comment by orakanggo** [comment]
already use liberty lite beta and enable setting for arena of valor but still crash

> Had the same issue, I downloaded the tweak “liberty lite beta” and turned on the settings for all those apps and games that crash, after that all works fine
