### ISSUE TITLE
imessage/sms notifications will not appear

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1737]
**Describe the bug**
iMessage will not get notification banners or lockscreen notifications, only badges, which means you dont know when you get a message, not very good.

I've tried respringing, restarting, rejailbreaking, reinstalling unC0ver, Hard shutting my phone, uninstalling and reinstalling so many different tweaks for trial error, nothing seems to work.

my friend had the same issue, he said he fixed it though by rejailbreaking from a soft shutdown, but I tried that

**To Reproduce**
just message someone

**Screenshots**
all you see is a badge, no banner or anything, not even hidden.

DND is not on
all notification settings were checked
everything inside iOS was checked

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device:  iPhone 11 Pro Max
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [? ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by JawadNozari** [comment]
Same problem on iOS 13.3,
Unc0ver v4.0.2
iPhone xs

**Comment by Zer0Degree** [comment]
Hi, 
Same here 
ios 13.3
unc0ver 4.0.2 (same on 4.0.1)
iphone 11 pro
thanks

**Comment by SynnyGR** [comment]
Same issue here, iPhone 11 Pro Max on iOS 13.3 with unc0ver 4.0.2

**Comment by hferran1** [comment]
Same issue here, iPhone 11  on iOS 13.3 with unc0ver 4.0.2

**Comment by Zer0Degree** [comment]
Just wanna notify that the iCleaner + ldrestart method solve the problem

**Comment by Stedy13** [comment]
> Just wanna notify that the iCleaner + ldrestart method solve the problem

Anyone know how to do this process?

**Comment by LAYL0W** [comment]
I have this problem also & no notifications on apple watch also.

**Comment by ghost** [comment]
> 
> 
> Just wanna notify that the iCleaner + ldrestart method solve the problem

THIS WORKS.
Download iCleaner and run it
and also download powerselector to LDRestart (soft restart without losing jailbreak)
works like a charm

**Comment by VIXIVIXIV** [comment]
Have the same problem, ldrestart via NewTerm2 fixes it.

**Comment by Terror-Gene** [comment]
Same issue, if I reboot my notifications come back. Jailbreak & they're gone! they still come to my watch though. same fix as before.
iOS 13.3
iPhone XS Max
unc0ver v4.1.1
