### ISSUE TITLE
4.0.2 Crash on launch

### ISSUE THREAD

**Issue by arayray** [pwn20wndstuff/Undecimus#1738]
**Describe the bug**
The uncover app crashes as soon as it is launched on my device. I tried using a signing service to update the app and then used AltServer to reinstall to confirm. Both methods cause a crash and the only way to fix it was to downgrade back to 4.0.1 which works completely fine.

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: Iphone 11 Max Pro
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by kutoIOS** [comment]
Không có phiên bản 13.3.1 giành cho A12  đúng không?

**Comment by javi71** [comment]
Describe the bug
The uncover app crashes as soon as it is launched on my device. 


iOS Version: 13.3
iOS Device: Iphone Xs max
unc0ver Version: 4.0.2

  this issue is present on the latest version of unc0ver

**Comment by zzzuzu3** [comment]
Describe the bug
The uncover app crashes as soon as it is launched on my device.

iOS Version: 13.2.3
iOS Device: Iphone Xs
unc0ver Version: 4.0.2

this issue is present on the latest version of unc0ver

**Comment by 946021** [comment]
Describe the bug
The uncover app crashes as soon as it is launched on my device.

iOS Version: 13.3
iOS Device: Iphone 11 Pro
unc0ver Version: 4.0.2

this issue is present on the latest version of unc0ver
