### ISSUE TITLE
 iPhone 11 Pro Max 13.3.1 Unsupported

### ISSUE THREAD

**Issue by its-arun** [pwn20wndstuff/Undecimus#1739]
**Describe the bug**
4.0.2 shows unsupported even though it is mentioned with the update that 13.3 is supported.

**To Reproduce**
1. Launch unc0ver on iPhone 11 Pro Max 

**Screenshots**
[Screenshot](https://imgur.com/a/Zkdqh5c)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone12,5
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[Diagnostics Data](https://pastebin.com/pv8m34sh)

**Comment by Beastandcool** [comment]
Can you go to your settings->general->about and screenshot your iOS version. The app is saying that your on iOS 13.3.1

**Comment by ccdffddfddfdsfedeee** [comment]
13.3.1 is not supported
