### ISSUE TITLE
Wrong version comparison logic

### ISSUE THREAD

**Issue by PoomSmart** [pwn20wndstuff/Undecimus#174]
https://github.com/pwn20wndstuff/Undecimus/blob/4bb377378b6c02f790aa8931138d6b1bcb17b775/Undecimus/source/SettingsTableViewController.m#L446

It is better to use `[Update compare:[NSString stringWithFormat:@"%@\n", [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"]] options:NSNumericSearch] == NSOrderedAscending` instead of checking the equality.

**Comment by Samgisaninja** [comment]
oops my b
