### ISSUE TITLE
iPhone XR 13.0 Cydia crashes after jailbreak and won’t open.

### ISSUE THREAD

**Issue by Darkelm67** [pwn20wndstuff/Undecimus#1740]
**Describe the bug**
I ran 4.0.1 on my XR iOS 13.0 and ran great all the way till I go to open cydia and it crashes. Cydia refuses to open no mater what I try. My wife has the same phone on 13.0 and it does the exact same thing.

**To Reproduce**

**Screenshots**
N/A
**Device (please complete the following information):**
 - iOS Version: 13.0
 - iOS Device: iphone11,8/iPhone XR 
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
N/A

**Comment by tempasta** [comment]
Im also having this bug on iPhone XR 13.1.3

**Comment by Hauteknits** [comment]
https://twitter.com/pwn20wnd/status/1230595794429890560?s=21
https://twitter.com/razmashat/status/1230959939885109253?s=21

This is a known issue and will likely be resolved in the next couple days.
