### ISSUE TITLE
App Store updates and refreshes fail to appear. 

### ISSUE THREAD

**Issue by Grapplerone** [pwn20wndstuff/Undecimus#1741]
Updates in the App Store do not show up. Doing a refresh has the same result.

Go to the App Store, no updates. Do a refresh of your apps, no updates.

 - iOS Version 13.3
 - iOS Device: Iphone 11
 - unc0ver Version: 4.06

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by DarkZone-World** [comment]
Same for me on iOS 13.3 A12 (iPhone XS). Restore RootFS didn't help without jailbreak. :( I really hope that can be fixed!

**Comment by SavageAUS** [comment]
Same issue here.
unc0ver version 4.0.2
iPhone XR 13.3

**Comment by yahyaalharbi** [comment]
@

**Comment by zenminimalist** [comment]
Same here, with two devices, running different iOS, but same unc0ver version 4.0.2.

unc0ver version 4.0.2
iPhone 11 13.3
and
iPad Pro 2018, iOS 13.2.2 
unc0ver version 4.0.2

**Comment by Grapplerone** [comment]
After the Unc0ver 4.03 update try doing a CLEAN with ICleaner Pro. That solved this issue for me.

**Comment by zenminimalist** [comment]
@Grapplerone Can you clarify what a "CLEAN" with ICleaner Pro includes? Cydia Sources etc. or just a cache cleaning session?

**Comment by zenminimalist** [comment]
@Grapplerone Boom! It worked! All updates just popped up! Great work!!

**Comment by DarkZone-World** [comment]
> @Grapplerone Boom! It worked! All updates just popped up! Great work!!

Does AppStore shows a Badges on the Icon for Updates?

**Comment by Grapplerone** [comment]
> > @Grapplerone Boom! It worked! All updates just popped up! Great work!!
> 
> Does AppStore shows a Badges on the Icon for Updates?

Hmmm, I haven’t checked that since I have the homescreen icon badge turned off for aesthetics.

**Comment by zenminimalist** [comment]
> > @Grapplerone Boom! It worked! All updates just popped up! Great work!!
> 
> Does AppStore shows a Badges on the Icon for Updates?

Works for me : )

**Comment by Haunter** [comment]
Go to the App Store, no updates. Do a refresh of your apps, no updates.

iOS Version 13.3
iOS Device: Ipad 11 pro wifi only
unc0ver Version: 4.03
Place an "x" between the brackets if true:

[ x] this is a bug others will be able to reproduce
[x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
[ Haven't tried] this issue is present after a rootfs restore
[ x] this issue is present on the latest version of unc0ver

Present even when unjailbroken. Have already tried the icleaner pro work around

**Comment by Game2Freak** [comment]
I’m still having issues with no updates showing in the AppStore on unc0ver 4.0.3 using an A12 device. Tried the iCleaner fix others have mentioned but does not work. Have to reboot update apps then Re-jailbreak.

**Comment by inline6power** [comment]
Same issue here. Won’t show or refresh to show updates yet if I click on a individual app it will show that app itself needs an update.

**Comment by zenminimalist** [comment]
It seems that this issue has come up again for me. Worked before...I've tried to reinstall Uncover, do a iCleaner round, but no joy....Very strange...

**Comment by Grapplerone** [comment]
> It seems that this issue has come up again for me. Worked before...I've tried to reinstall Uncover, do a iCleaner round, but no joy....Very strange...

A bug in AppStore++ release 0.9.8-6 is causing the SAME issue. It is being looked at be its developer.

**Comment by zenminimalist** [comment]
@Grapplerone OK, uninstalled it and solved the issue. Thanks for the heads up!

**Comment by Grapplerone** [comment]
This issue was resolved in 4.0.3, it doesn’t seem to have reoccurred and now we are at 4.2.1. 

AppStore++ ver 0.9.8-6 thru 0.9.8-8 has been the main issue causing this since the update 4.0.3 Unc0ver update. AppStore++ was updated to 0.9.8-9 to correct this.

I consider this bug fixed.
