### ISSUE TITLE
Not all rights (Operation not permitted)

### ISSUE THREAD

**Issue by XXXDem0nXXX** [pwn20wndstuff/Undecimus#1742]
When I try to open a directory or a file with a super user, I get the error "Operation not permitted" which proves us the lack of full root rights
Steps to reproduce:
1. Go to terminal
2. Enter the "su", then your password
3. After login, enter the "file /var/mobile/Library/Shortcuts"
4. See error "Operation not permitted"

**Screenshots**
![fyCEk-WHKrE](https://user-images.githubusercontent.com/54532467/74759376-5e9fa100-5281-11ea-9367-1de4afe05e1e.jpg)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: Iphone XS Max
 - unc0ver Version: 4.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Cregin** [comment]
how to fix? @XXXDem0nXXX
