### ISSUE TITLE
cydia/cydo error 255

### ISSUE THREAD

**Issue by DatMemeKid** [pwn20wndstuff/Undecimus#1745]
I get the error that annoys me to no end.
![660FF734-04F3-46F8-AE2F-F468047FD02A](https://user-images.githubusercontent.com/61212450/74785640-5d19ad00-5270-11ea-8a39-234ad0904d90.png)
I tried to restore root fs and clear cydia cache. I searched up solutions of google and yt but they are outdated

**Comment by DatMemeKid** [comment]
Hmm yes I also have this problem. I need a fix

**Comment by retX0** [comment]
Same.

**Comment by pascalchristian** [comment]
Is this on iOS 12? Try using unc0ver 3.8.0. v4 broke compatibility
