### ISSUE TITLE
Apple Watch goes into the recovery mode automatically

### ISSUE THREAD

**Issue by cidmex** [pwn20wndstuff/Undecimus#1748]
**Describe the bug**
Apple Watch will go into the recovery mode and show the restore progress bar when I use unc0ver. It doesn't happen everytime and seems to have no side effects on watch itself but you have to wait for the progress bar to finish. I also notice that this problem happens sometimes even if you just open the unc0ver app and don't click the jailbreak button.

**To Reproduce**
1. Open unc0ver app (and click the jailbreak button)
2. Apple Watch goes into the recovery mode automatically

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS Max
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by LAYL0W** [comment]
I dont get any notifications from my watch tho. I did that app unisync & ldrestart. I got imsg & apple store to work. But watch still no die with notifies. Also i cant set wallpaper. Reboots to unjailbroken state.

**Comment by NunoMF** [comment]
Turn off Bluetooth before you start the jailbreak process.

**Comment by miguelr4720** [comment]
YES
