### ISSUE TITLE
Version 4.0.2 says 4.0.1

### ISSUE THREAD

**Issue by asdfugil** [pwn20wndstuff/Undecimus#1749]
**Describe the bug**
Same as title

**To Reproduce**
1.Download and Install 4.0.2
2.Open unc0ver 
3.unc0ver version:4.0.1 at the bottom

**Screenshots**
 
![D1987FF1-562A-4AE6-8986-2E3CB2C9B19E](https://user-images.githubusercontent.com/42699250/74806521-22bc1880-5321-11ea-9179-98089884a3cb.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPad Pro 9.7 (J127AP)
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ccdffddfddfdsfedeee** [comment]
See https://github.com/pwn20wndstuff/Undecimus/issues/1734#issuecomment-587236559

**Comment by jloysch** [comment]
Please close this, this has been addressed as a mis-tag.
