### ISSUE TITLE
Restore RootFS not working on iPad8,7 J321AP / unc0ver 4.0.2

### ISSUE THREAD

**Issue by TheChatty** [pwn20wndstuff/Undecimus#1752]
**Describe the bug**
After jailbreaking successfully it's not possible to remove the jailbreak.

**To Reproduce**
1. Enable "Restore RootFS"
2. Click "Restore RootFS"
3. unc0ver prints a few lines and exits

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPad8,7
 - unc0ver Version: 4.0.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by stohle** [comment]
Please post the log file here

**Comment by TheChatty** [comment]
When I rerun unc0ver I noticed this time it was complaining about being unable to end a background task. So I just rebooted and then it worked. Sorry for disturbing.
