### ISSUE TITLE
Whatsapp send media failed 13.1.3

### ISSUE THREAD

**Issue by KH12** [pwn20wndstuff/Undecimus#1754]
i cann't send any media by whatsapp its failed on iPhone 11 13.1.3 

i didn't know what's problem and i can't fix it pls help me

**Comment by the1ulike** [comment]
This is the same issue here:
https://github.com/pwn20wndstuff/Undecimus/issues/1744

**Comment by fhs750** [comment]
same problem here

**Comment by davinder121** [comment]
Same issue on iPhone pro max 13.0

**Comment by Cryptiiiic** [comment]
Duplicated of #1744
