### ISSUE TITLE
Error on Load Tweak above Undecimius 3.8.0

### ISSUE THREAD

**Issue by Dowz95** [pwn20wndstuff/Undecimus#1755]
**Tweaks don't load but iPhone is jailbroken **
I notice when I use an Undecimius version above the 3.8.0 release, my device (iPhone X 10,6 iOS 12.4) don't load tweaks but work with root acces, the proof is that I can open Cydia. I think Cydia Substrate or something else can't be load. It's for what all my tweaks don't appear anymore.
If i use Undecimius 3.7.0 (all Beta works) or 3.8.0 all my tweaks loads and i can enjoy my jailbreak ! 
I want to share this bug for that everyone has the knowledge and developper can maybe fix this 👍 

**iPhone X**
 - iOS Version: 12.4
 - iOS Device: 10,6
 - unc0ver Version: 3.7.0 ~ b3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
No Logs

**Comment by ccdffddfddfdsfedeee** [comment]
This is a known bug, downgrade to 3.8.0-b1
