### ISSUE TITLE
Error message push message & game crash

### ISSUE THREAD

**Issue by HDteen** [pwn20wndstuff/Undecimus#1756]
** Error description **
When I perform jaibreak version 4.1.1 I still get the following error:
* Not receiving message / imessage notifications
* In the game: PUBG mobile, Call of Duty mobile, Arena of Valor, ... about 1 minute game crash

** Device :
- iOS version: IOS 13.3
- iOS device: iP XS Max
- Unopened version: 4.0.0, 4.0.1, 4.0.2, 4.0.3,4.1.1

**Comment by KH12** [comment]
i fix it crash games you can contact me on twitter @cydia20

**Comment by KH12** [comment]
ok i will write steps , its work with all apps and games i will test with pubg mobile 

1-install this tweaks ( apps manager and choicy and shadow)

2-open settings app  and go to shadow then Applications and Enable ex pubg mobile

3-choicy >applications>ex pubg mobile and Enable custom tweak and then Enable only shadow (Whitelist)

3-open apps manager then pubg mobile then click Wipe 

4-last step respring your device and then open your games and use it

Source shadow

https://ios.jjolano.me/

Source Apps Manager 

http://tigisoftware.com/cydia/

Source Choicy

https://opa334.github.io/

Hope this tutorial fix your problem

**Comment by cidmex** [comment]
It is the jailbreak detection built in game, not the jailbreak itself, that causes some games to crash.

**Comment by HDteen** [comment]
So now all I need to do is delete the game, do the jaibreak and download it again, right?

**Comment by lt-fancy** [comment]
> ok i will write steps , its work with all apps and games i will test with pubg mobile
> 
> 1-install this tweaks ( apps manager and choicy and shadow)
> 
> 2-open settings app and go to shadow then Applications and Enable ex pubg mobile
> 
> 3-choicy >applications>ex pubg mobile and Enable custom tweak and then Enable only shadow (Whitelist)
> 
> 3-open apps manager then pubg mobile then click Wipe
> 
> 4-last step respring your device and then open your games and use it
> 
> Source shadow
> 
> https://ios.jjolano.me/
> 
> Source Apps Manager
> 
> http://tigisoftware.com/cydia/
> 
> Source Choicy
> 
> https://opa334.github.io/
> 
> Hope this tutorial fix your problem

It works for me, iPhone XS Max, iOS 13.3, now I can open PUBG without any problems

**Comment by KH12** [comment]
Ok Welcome 👍
