### ISSUE TITLE
Cydia Crashing, IPhone XR 13.1.1

### ISSUE THREAD

**Issue by Fatta0** [pwn20wndstuff/Undecimus#1757]
**Describe the bug**
Cydia Will Crash and Close out.

**To Reproduce**
1. Go on Unc0ver app and press Jailbreak,
2.after snapshot is saved, jailbreak again.
3. When the Jailbreak is completed the Device will respring then reboot
4. Cydia will be seen but will crash when attempted to Open

**Screenshots**
None

**Device (please complete the following information):**
 - iOS Version: 13.1.1
 - iOS Device: IPhone XR 
 - unc0ver Version: 4.0.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
None.

**Comment by theLaxerz** [comment]
I am having this issue as well on an iPad

**Comment by theLaxerz** [comment]
I have even Restored RootFS

**Comment by theLaxerz** [comment]
We are going to need SnapBack updated

**Comment by theLaxerz** [comment]
This is also after - Reinstalling Cydia which is the only way to make it run but then upon the sources refreshing it will crash.

**Comment by Fatta0** [comment]
> This is also after - Reinstalling Cydia which is the only way to make it run but then

**Comment by theLaxerz** [comment]
Definitely no reason to close the issue it Fails still after the reinstall.

**Comment by Fatta0** [comment]
> Definitely no reason to close the issue it Fails still after the reinstall.

Yeah I accidentally closed it.

**Comment by steve-1211** [comment]
same here, 
cydia does't open even after jailbreaking using unc0ver 4.0.3 
only whatsapp2 works eveything else not working

**Comment by tempasta** [comment]
Same im having this bug on iPhone XR 13.1.3.

**Comment by Hauteknits** [comment]
https://twitter.com/pwn20wnd/status/1230595794429890560?s=21
https://twitter.com/razmashat/status/1230959939885109253?s=21

This is a known issue and will likely be resolved in the next couple days.
