### ISSUE TITLE
Adapters/accessories don't work after jailbreak

### ISSUE THREAD

**Issue by VIXIVIXIV** [pwn20wndstuff/Undecimus#1760]
**Describe the bug**
Connected video output adapters (observed with both HDMI and VGA) don't work.

**To Reproduce**
1. Connect adapter
2. Connect video cable
3. No output

Note that if the phone is locked and accessories are disabled while locked, a notification will show up to ask that you unlock the phone to use accessories, but the accessory doesn't actually work after unlocking

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS
 - unc0ver Version: 4.0.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by VIXIVIXIV** [comment]
Have not tested yet with all tweaks disabled or after a RootFS restore.

**Comment by CptKev** [comment]
There’s a fix for this, download DaemonDisabler from level3tjg’s repo. 

Search for “com.Apple.MobileAccessoryUpdater.plist” 

Disable and re-enable it, should work properly.
