### ISSUE TITLE
iPhone10,6 iOS13.3 Unsupported on v4.0.3

### ISSUE THREAD

**Issue by nanpuhaha** [pwn20wndstuff/Undecimus#1761]
**Describe the bug**
iPhone10,6 unsupported on iOS 13.3 with unc0ver 4.0.3.

**To Reproduce**
1. Launch Unc0ver v4.0.3 on iPhone10,6.
2. See error

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone10,6
 - unc0ver Version: 4.0.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

[*] unc0ver Version: 4.0.3
[*] Machine Name: iPhone10,6
[*] Model Name: D221AP
[*] Kernel Version: Darwin Kernel Version 19.2.0: Mon Nov  4 17:47:00 PST 2019; root:xnu-6153.60.66~39/RELEASE_ARM64_T8015
[*] Kernel Page Size: 0x4000
[*] System Version: iOS 13.3 (Stable) (Build: 17C54)
[*] Bundled Resources Version: 1.0~b26
[*] Status: Unsupported
[*] Progress: Unsupported

**Comment by ZakDumasia** [comment]
I would just wait a month or 2 to see if unc0ver’s team has figured out what the problem is

**Comment by tempasta** [comment]
Currently only A12-A13 devices are supported. Use [checkra1n](https://checkra.in)  instead.

**Comment by braszek-dev** [comment]
According to the changelog, since v4.2.0 A8-A11 devices running iOS 13.0-13.3 are fully supported.
I have the same problem - using the newest release v4.3.1 on iPhoneX (10.6, D221AP) the jailbreak is unsupported.

**Comment by braszek-dev** [comment]
@Cryptiiiic any comments ?
