### ISSUE TITLE
unc0ver not blocking updates 

### ISSUE THREAD

**Issue by Kai0KenX20** [pwn20wndstuff/Undecimus#1763]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

unc0ver no longer blocks updates properly 

**To Reproduce**
1. Go to settings
2. Click on General/SoftwateUpdates

**Device (please complete the following information):**
 - iOS Version: 13.3 (17C54)
 - iOS Device: MT372LL/A 11,8 Xr 
 - unc0ver Version: latest 4.0.1/2

**Place an "x" between the brackets if true:**
 - [ X] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Kai0KenX20** [comment]
Sorry but pressed on time at the moment will add logs etc later

**Comment by dinol1187** [comment]
Install tweak. Mcpatch (this tweak will allow you to install tvOS 13 beta profile)

Once installed go to betaprofiles.com and install tvOS beta profile. Once installed you can uninstall Mcpatch 

Your updates should now be blocked hope this helps

**Comment by NewGithubber35** [comment]
>Install tweak. Mcpatch (this tweak will allow you to install tvOS 13 beta profile) ...

@dinol1187 mcpatch doesn’t even come up in iOS-repo-updates.com as existing. Do you have the repo link? Thanks ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dinol1187** [comment]
@NewGithubber35 

Repo: http://xsf1re.github.io/repo/
