### ISSUE TITLE
"unable to get debs for packages to repair"

### ISSUE THREAD

**Issue by pedrosoori** [pwn20wndstuff/Undecimus#1766]
**Describe the bug**
This is a bit long story. I had realized that my battery ran out very fast with the jailbreak and I realized that it was on the backboardd and I saw on the internet that the best option was to restore the device (iPhone XR 13.3) and I found the Succession application. I did all the steps well and when you start doing the restoration, an error comes up with the only option to exit the application, but while the restoration was still running. I did not realize that the process was going on and press to exit the application. This caused errors and did not open any jailbreak or tweak applications, so enter unc0ver and activate the Restore RootFS option to eliminate the jailbreak. When I tried to jailbreak again to return to the original state I got the error of "Unable to get debs for packages to repair." No matter where I install unc0ver and whatever version I always get the same error.

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone Xr
 - unc0ver Version: I tried 4.0.0/4.0.1/4.0.2/4.0.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Unable to resolve lzma to a debs
Unable to get debs for packages to repair.

**Comment by xchemical** [comment]
I just try unc0ver version 4.1 and 4.1.1 and the problem is still there. It was working fine but was trying to get a tweak to work and restore rootfs and after that I have the same problem.

**Comment by ghost** [comment]
This issue is caused by an outdated version of AltServer for Windows, just update it.

**Comment by xchemical** [comment]
Thanx nyuszika7h it is working after I updated altserver and I'm running 4.2
