### ISSUE TITLE
/usr/libexec/cydia/cydo returned an error code (255)

### ISSUE THREAD

**Issue by m7jalta** [pwn20wndstuff/Undecimus#1767]
Hello everyone !
Yesterday I got an error in Cydia!
I am using uncover jailbreak 4.0.3 on iOS 12.4 , i wanted to restore the network settings on iOS settings, the device restarted then I lost the jailbreak and all the tweaks when I click on Cydia and when I install any tweak it’s gave me /usr/libexec/cydia/cydo returned an error code (255) with red ,
So I restored rootfs an  re uinstall Cydia but it’s not working same problem /usr/libexec/cydia/cydo returned an error code (255)
I restored the root fs and I downgrade the uncover version but not working!
I tried chimera and it works with no problem ! Then I installed filza and I removed chimera and I installed uncover to modify Cydia permission but I couldn’t install the jailbreak without using rootfs and the rootfs removed filza ! 
Please is there any solution to fix this problem!

**Comment by stohle** [comment]
Before I can help you with this, I need to know which device you are on.

**Comment by m7jalta** [comment]
iPad 5

> Before I can help you with this, I need to know which device you are on.

iPad 5e génération

**Comment by ccdffddfddfdsfedeee** [comment]
This is a known bug, downgrade to 3.8.0-b1

**Comment by idseventeen** [comment]
I had the same problem on 8p/12.0.1

**Comment by stohle** [comment]
Like @ccdffddfddfdsfedeee use Unc0ver 3.8.0b1.

Delete the Unc0ver you have now and use 3.8.0b1 to do Restore RootFS. (If it hangs for more than 10 minutes, exit Unc0ver. Do a hard reset. Look for Cydia. If its still there, do a Restore RootFS again. Cydia should now be gone when you reboot you iPad)

**Put your iPad in flight mode**
1. Close ALL running apps
2. In Unc0ver settings, turn on the following: 
- Reinstall Cydia
- Reset Cydia cache
- Auto respring

**Comment by m7jalta** [comment]
Hi everyone ! 
I did all the steps nothing works for me !
The solution is to use rootfs using last version of uncover then delete the app! Then install chimera , Sileo works perfect with no bug for the moment!

**Comment by LogDotNG** [comment]
All you need to do to fix this issue is to download Unc0ver v3.8.0 and re-jailbreak your device.

i made a tutorial on how to fix this problem, just incase you're finding it hard to fix or you don't know where/how to download and install the Unc0ver 3.8.0 IPA file, my tutorial will guide you https://log.ng/2020/02/25/fix-cydia-ios-11-4-1-12-4-fix-sub-process-usr-libexec-cydia-cydo-returned-an-error-code-255/
