### ISSUE TITLE
Image thumbnails, gifs not loading in mixed phone group messages (iPhone/Android users in same group message)

### ISSUE THREAD

**Issue by xSlickRick23x** [pwn20wndstuff/Undecimus#1768]
**Describe the bug**
Image thumbnails and gifs do not load when in a group text message with users having both iPhone and android phones. Images appear normally when in a group text message with all iPhones. I have already done the ldrestart fix in terminal, as well as toggled “low quality images” in messages settings as recommended on r/jailbreak.

**To Reproduce**
1. Open group message with users with both iPhone and android phones
2. Have other users send you images/gifs
3. Blank files show up
4. Have to tap files to open images/gifs

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.0.3

**Place an "x" between the brackets if true:**
 - [ X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by myinterlude** [comment]
![IMG_0001](https://user-images.githubusercontent.com/61329830/75063506-ec55d900-5499-11ea-8a96-85c238b3ddfc.jpg)

iOS 13.3, iPhone XS Max, Uncover 4.0.0/ .1/ .3 (tried each as clean install nothing else loaded on phone)

issue present on latest version, present with out any tweaks(just clean, just jailbroken, all Cydia defaults updated), tried restore rootfs and then jailbreak again same issue
