### ISSUE TITLE
Please Add Support Upcoming Unc0ver 4.0.4  Unc0ver 4.0.3 Cydia won't load Tweaks 12.4

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1776]
**Describe the bug**
Jailbrake Unc0ver 4.0.3 iPhone XS Max 12.4 

Open Cydia tweaks won't load : (

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone XS Max

 - unc0ver Version: Unc0ver 4.0.3

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
the bug always happens 12.4 but haven’t seen the respiring bug on 13.3 yet i keep getting random respiring on 12.4 :( too

**Comment by andre104623** [comment]
You got to use unc0ver 3.7.0

**Comment by andre104623** [comment]
That’s for 12.4

**Comment by andre104623** [comment]
4.0.0 to 4.0.3 is only only for a12 a13 13.0 13.1 13.2 and 13.3 Strictly those firmware’s

**Comment by andre104623** [comment]
If you tried to jailbreak with 4.0 you must restore rootfs with 4.0 then install 3.7.0 unc0ver

**Comment by andre104623** [comment]
I wish pwn would make every jailbreak a different name like it always like before this updating old jailbreak names is confusing newcomers like crazy like this release is nuts

**Comment by miguelr4720** [comment]
wish one B1 or B2 or B3

**Comment by mark-antonchikov** [comment]
I have IOS 12.4. Re-jailbreak with Unc0ver 4.0.3 was successful, but tweaks won't load too. Install Unc0ver 3.8.0 and made re-jailbreak without restoring rootfs. All tweaks load well.
