### ISSUE TITLE
Can’t find “iOS update”

### ISSUE THREAD

**Issue by JARBRW** [pwn20wndstuff/Undecimus#1777]
I can’t find the “iOS update” in my iPhone Storage

**Comment by Beastandcool** [comment]
be more descriptive... There were instructions on how to make a post, follow them next time. What iOS/unc0ver version are you on, could it be a tweak removing it?

**Comment by miguelr4720** [comment]
THIS IS RIDICULOUS CLOSED THIS CASE

**Comment by miguelr4720** [comment]
PLEASE CLOSED NOT URGENT UPDATE ARE NOT SUPPOSED TO WORK BEING JAILBROKEN 
JUST FOR PRECAUTION THE iOS Wont get Updated and LOSE JAILBRAKE

**Comment by miguelr4720** [comment]
CLOSED THIS CASE LOL NOT A BUG
