### ISSUE TITLE
Phone gets black screen/freeze overnight

### ISSUE THREAD

**Issue by DannySchaukens** [pwn20wndstuff/Undecimus#1779]
Hello,
Discription: 
- Iphone 11 pro max 13.3
- Unc0ver 4.0.3
- No problems when i use my phone.
- Battery good & system very smooth
- Tweaks: Animationsbefastplus, appaze 2, audiorecorder xs, autoscroll, autounlock, badgebar, banner sounds 13, barmoji, bazzi2, boxy, callbar XS, chargeanimations, cloacky, colorbanners, darkkeys, dleasy, exacttime, floatingdock, grupi, kalm, killx pro, magma evo, malipo, nevve, powermodule, preferenceorganisizer, pullover pro, realkeys, safariplus, shortlook, sleepytime, snapper2, snowboard, springtomize 5, switcherstyle, taptapflip, voicechanger XS, whoops

**When i sleep and wake up the last 4 days my phone has a black screen and I need to reboot en re-jailbreak without problems.**
I tested with and without charging...
Somebody has an idea or can give me some tips to solve the problem?
Does it have something to do with the ota update or sync something from apple?
Thx a lot & grtz from belgium ;-)

**Comment by Beastandcool** [comment]
try disabling all tweaks before going to sleep and see if the same thing happens.
