### ISSUE TITLE
YT++ for YouTube By UnlimApps

### ISSUE THREAD

**Issue by dannydav709** [pwn20wndstuff/Undecimus#1780]
The YouTube ++ tweak has worked perfectly with uncover version 4.0.2, and the update to 4.0.3 causes it to not work. A downgrade back to 4.0.2 causes the tweak to work gain. This may be an infliction on a dependency of uasharedtools which Yt++ depends on. Please fix if possible. Thanks!!
YT++ for YouTube By UnlimApps

**Comment by miguelr4720** [comment]
no and NOT unc0over issue you need to contact the developer UnlimApps

NOT A BUG FROM UNC0VER
