### ISSUE TITLE
Can’t install any third party apps 

### ISSUE THREAD

**Issue by acapstick** [pwn20wndstuff/Undecimus#1782]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

I’m trying to download uncover and other third party app stores but they either don’t download or crash as soon as I press on them. I have downloaded the same files from ignition, app cake etc onto my iPad and they’re working perfectly.  I had uncover working great but my phone rebooted and I could no longer install any third party app. This happened a few days ago so I reset my phone to factory settings and restored from iCloud backup. I have just rebooted now and can once again not install any third party app but rebooting/restoring/wiping does not make a difference 

**To Reproduce**
1. Go to any third party App Store
2. Click on download
3. App either doesn’t download or crashes 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR 
 - unc0ver Version: all

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Beastandcool** [comment]
what unc0ver version is "all". If you're on the latest then its probably a bug hes working on. You could also try installing appsync

**Comment by acapstick** [comment]
Ive tried installing uncover 3.8.0 and 4.0.0 both either crash when trying to open or don’t install. Installing the same files on my iPad and other phone work perfectly! Not jailbroken currently so only have access to stock iOS
