### ISSUE TITLE
My device version is ios13.3   Blue button on unc0ver v4.0.2 and says "Unsupported",

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1783]

**Comment by Beastandcool** [comment]
You've provided no description and expect people to help? Follow instructions...
I'm guessing your using an older device, Unc0ver is only for A12/A13 devices and doesn't support any other devices at the moment. But eventually there will be an update

**Comment by f0rmat1k** [comment]
I have the same issue on ipad 6. I suppose @zxq2233 has something like that. So, we have to wait update. Probably uncover website should have more explicit supported device list.

**Comment by ghost** [comment]
@Beastandcool @f0rmat1k latest version now supports A8-A11 devices!
