### ISSUE TITLE
Lightning to HDMI cord not working after jailbreak

### ISSUE THREAD

**Issue by JarheadNoj** [pwn20wndstuff/Undecimus#1790]
Lightning to HDMI A/V cable not working after Unc0ver jailbreak for iPhone Xs max ios 13.3

**Comment by ishsed** [comment]
Having the same problem

**Comment by Tylerbb812** [comment]
Same here

**Comment by thealgorithmc64** [comment]
Same issue here as well with the apple lightning to hdmi cable.  Usually when plugging it in, it should show a blue highlight with a cable logo on the top left corner (as it does when non jailbroken).
Works on checkra1in but not unc0ver.     However this affects the apple lightning to hdmi cable only it seems.

I have tried a third party one and that works. there is a setting in OTA options via pressing the hole via pin to enable game mode. (Works very well on iPhone X (13.3), but very choppy on iPhone 11 pro (13.1.2)

**Comment by edro68** [comment]
I have the same issue with my iPhone 11 Pro Max , any suggestions? Thanks

**Comment by ishsed** [comment]
Update 4.3.0 might fix it. #unc0ver v4.3.0 will be a major update with over 30 fixes and changes!
