### ISSUE TITLE
Uncover 4.0.0 - 4.0.3 broken on iOS 12.4

### ISSUE THREAD

**Issue by MaltronCraft** [pwn20wndstuff/Undecimus#1792]
**Describe the bug**
After jailbreaking iOS 12.4 it won’t  load tweaks properly, most don’t even activate. This happens on 4.0.0 - 4.0.3 (latest version of unc0ver at time of bug report)

**To Reproduce**
1. Open Unc0ver
2. Tap jailbreak
3. Wait for respring
4. Most tweaks won’t work properly or don’t work at all.

**Device (please complete the following information):**
 - iOS Version:  12.4
 - iOS Device:  iPhone 6 & iPad Mini 3
 - unc0ver Version: 4.0.0 - 4.0.3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

@pwn20wndstuff

**Comment by ChristiMark** [comment]
To me says when trying to install something in cydia: /usr/libexec/cydia/cydo returned an error (255). I think we have to wait for an dpkg fix.

**Comment by Puschkin-Vodka** [comment]
> 
> 
> To me says when trying to install something in cydia: /usr/libexec/cydia/cydo returned an error (255). I think we have to wait for an dpkg fix.

Unc0ver 4 isn't compatible or is very buggy on iOS 12..
You need v.3.80 (iosninja / iphonecake )
Then Restore RootFS, and finally Jailbreak your device.
Done..

**Comment by ChristiMark** [comment]
It was fixed.

**Comment by Puschkin-Vodka** [comment]
Oh ok.. Changelog from v.4.10: -Fix compatibility issues with iOS 11.0-12.4 and 13.0-13.2.3 
..good to know!
