### ISSUE TITLE
Telling me my device is unsupported.

### ISSUE THREAD

**Issue by PhildoDxldo** [pwn20wndstuff/Undecimus#1793]
![36FF4CFD-6FBE-4AAD-91FE-BA98582B2D25](https://user-images.githubusercontent.com/56623456/75201182-c9dfec00-5735-11ea-8cc8-4108fba6a8fc.png)

**Comment by DanielJasonRobinson** [comment]
Same issue

**Comment by mau5atron** [comment]
@PhildoDxldo @iphonesilver Only stable builds of iOS are supported. You are running a beta version. Please close your ticket.

**Comment by andre104623** [comment]
No beta firmwares this is like the 5th time I said this on here please close thread there is nothing you can do maybe checkm8

**Comment by DanielJasonRobinson** [comment]
I'm running beta and was able to get it to jailbreak last night. Surprisingly.

**Comment by moondark864** [comment]
Thats version 4.1.1. Download the latest version
