### ISSUE TITLE
iPhone XR Notification bug

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [pwn20wndstuff/Undecimus#1794]
Not getting notifications while Jailbroken

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iphone xr
 - unc0ver Version: 4.1.1

Not good at this sorry for a lack of info

**Comment by andre104623** [comment]
Also can confirm notifications not working

**Comment by andre104623** [comment]
Notifications workaround not working ether

**Comment by andre104623** [comment]
Update to 4.2.1 it’s fixed close thread
