### ISSUE TITLE
A10 7 Plus jailbroken with unc0ver 4.2.0 any installed tweak throws me into safe mode

### ISSUE THREAD

**Issue by marleyqp** [pwn20wndstuff/Undecimus#1804]
I was previously jailbroken with checkra1n but I restored RootFS and all of my tweaks/apps went away. Now when I'm jailbroken with unc0ver, any tweak I install throws me into Exit (safe) mode. What can I do?
Running iOS 13.3 on an iPhone 7 Plus on unc0ver v4.2.0
previously jailbroken with checkra1n version beta 0.9.8

**Comment by mau5atron** [comment]
@marleyqp Why would you remove your previous jailbreak? Releases 4.0 - 4.3 were targeted for A12-A13 devices. If I were you I would stick with checkra1n.

**Comment by marleyqp** [comment]
I don’t always have access to my computer. It’s nice having a semi-untethered jailbreak.
