### ISSUE TITLE
Unsupported (17C5046a) iPhone 11 Pro Max

### ISSUE THREAD

**Issue by kredse** [pwn20wndstuff/Undecimus#1806]
Getting the unsupported message.
![CBBE812D-1D92-42EB-82C1-0630AFA8B07E](https://user-images.githubusercontent.com/48418356/75352376-83d27780-585e-11ea-8e04-4f80e83b5b61.png)

**Comment by mau5atron** [comment]
@khojames You're supposed to be on iOS 13.0 - 13.3. No beta versions are are supported. Please close the ticket.

**Comment by andre104623** [comment]
And never will support beta firmwares
