### ISSUE TITLE
[NOBUG] Thank you for your awesome work!

### ISSUE THREAD

**Issue by MikeeI** [pwn20wndstuff/Undecimus#1807]
I think you get way too less "thank yous" for your work. 

I'm just so grateful to use it and profit from your dedication.

Just a thank you. 😊

![image](https://user-images.githubusercontent.com/13944905/75363877-0c7f0100-58bb-11ea-84d4-250eddc09bc0.png)

**Comment by The-SamminAter** [comment]
I’m sure that the devs would appreciate the thanks, I suggest you @ them on either twitter or reddit. The devs have completely abandoned this repo, except for adding new releases when they are available.
