### ISSUE TITLE
unable to start substitute

### ISSUE THREAD

**Issue by b24l** [pwn20wndstuff/Undecimus#1808]
i start to jailbreak and my phone either restarts or i get this error 
![unc0vererror](https://user-images.githubusercontent.com/43045042/75379265-02fe9480-58cd-11ea-924f-4e55054e449d.jpg)

 - iOS Version: 13.3
 - iOS Device: iphone 8(10,4)
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
shown in screenshot

**Comment by miguelr4720** [comment]
having the same problem to iPhone 11 Pro Max 13.3

**Comment by miguelr4720** [comment]
happens when i try to re-jailbrake

**Comment by b24l** [comment]
> happens when i try to re-jailbrake

yeah forgot to put re jailbreak in the original post my phone died i installed the new version of unc0ver and this error started to appear

**Comment by miguelr4720** [comment]
Is happening to everyone who tries Re-Jailbrake Defenetly Unc0ver issue

**Comment by The-SamminAter** [comment]
If possible, maybe try rootfs-big? I am not experiencing the problem, and unc0ver doesn’t let you re-install substitute, so I don’t have any suggestions other than that.
