### ISSUE TITLE
Siri breaks through bluetooth car cmds (happens on Checkra1n as well)

### ISSUE THREAD

**Issue by yaboijay2029** [pwn20wndstuff/Undecimus#1810]
**Describe the bug**
If you connect your phone to bluetooth in car and you the steering wheel control to activate siri, it flashes very so sudden and siri cancels. 

I've also posted this on the checkra1n github as well. https://github.com/checkra1n/BugTracker/issues/491

**To Reproduce**
1. Use car command via steering wheel to activate siri

**Screenshots**
no screenshot

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 7+
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [ X] this is a bug others will be able to reproduce
 - [ X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by The-SamminAter** [comment]
Do you have CarBridge installed? It doesn’t work properly with iOS 13 jailbreaks I believe.

**Comment by yaboijay2029** [comment]
Nope. No tweaks installed other than small siri. It was happening before that tweak was updated too.

**Comment by vinnie12341234** [comment]
I have this same problem!

**Comment by vinnie12341234** [comment]
@Cryptiiiic was this issue resolved?

**Comment by yaboijay2029** [comment]
@vinnie12341234 no telling when this could be fixed
