### ISSUE TITLE
iPhone Apps freeze up every once in a while.

### ISSUE THREAD

**Issue by thecolbster91** [pwn20wndstuff/Undecimus#1812]
What’s up? My iPhone XS Max iOS 13.3 on Unc0ver 4.0.2 occasionally the apps will freeze and will be unusable, but I’m able to go back to the springboard and slide down the control center, spotlight, and today view. In order for the apps to work again, I would have to respring, I have the power module tweak in the control center to do that. I end up having to do this about every 30 minutes. What is going on?? Appreciate any help.

**Comment by The-SamminAter** [comment]
I had the same problem with unc0ver 4.0.2. Upgrading to the latest unc0ver seems to fix this issue. Also, in the future, please fill out the bug template.
