### ISSUE TITLE
 iPhone Keeps Changing Name in Setting General About Name Back to the Name iPhone on Unc0ver 4.2.0 iOS 13.3

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1814]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Respring iPhone keeps changing the Name on the Back to iPhone
2. Go to Setting and About 
3. Click on Name there is where the Name Keeps Changing Back to iPhone 
4. Scroll Up Change the Name Again of My iPhone to My Name then Re-Jailbrake Name Changes Back to iPhone again Please Help with this

**Screenshots**
![088A1510-887D-47B3-B2A8-760C0A81D0D4](https://user-images.githubusercontent.com/36649261/75511563-9498ff80-59bc-11ea-9974-a7481a67c67d.jpeg)

**Device (please complete the following information):**

 - iOS Version: 13.3
 - iOS Device: iPhone 11 Pro Max 
 - unc0ver Version: 4.2.0

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
everytime i using the uncover jailbrake the name of my iPhone Keeps Changing Back to iPhone

**Comment by miguelr4720** [comment]
Why does the name of my device keep changing
Can some one please tell me why the name on my device keeps changing.  I change it to a specific name, a few days later I find that its back to 'iPhone".  This is extremely annoying. This happens on all my iOS devices.  


 
How can I get the name of device to stay the same once I have changed it.

**Comment by suprstarrd** [comment]
@miguelr4720 What tweaks do you have enabled? Take a picture and send it to me here.

If you have no tweaks, try restoring RootFS then trying this again. Please note that restoring RootFS removes all tweaks you've installed.
