### ISSUE TITLE
Reboots galore.

### ISSUE THREAD

**Issue by lokimudhearth** [pwn20wndstuff/Undecimus#1815]
**Describe the bug**
When opening a browser while listening to an audio (phone calls, Spotify, etc), the phone reboots. 

**To Reproduce**
1. Listen to Spotify, Music, Phone call, etc.
2. Open Chrome or Spotify.
3. Phone reboots.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 6s
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x]this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ghost** [comment]
I’m having this exact issue too on my iPhone 6S!

**Comment by Suphax** [comment]
This is also happening on my iPhone SE, iOS 13.3, unc0ver 4.2.1. 

Kernel panics as I open an app sometimes, on any app while on phone/YouTube/music. 

Still happens with all tweaks disabled.

**Comment by Hamlock-Maneuver** [comment]
Try this test.  Open Cydia and navagate to any app description.  now switch to another app.  Don't kill cydia. Just switch to some other app.   Now switch back to cydia.  Did it completely reload Cydia?  Or did it take you back to the app description?

**Comment by lokimudhearth** [comment]
I just switched back to checkra1n. Much more stable. If this gets fixed, I’ll switch back over.
