### ISSUE TITLE
Dont Work in my iPad 6,12

### ISSUE THREAD

**Issue by Italogc** [pwn20wndstuff/Undecimus#1818]
In my device iPad 6,12 (A1822) the jailbreak proccess stuck in error and my device reboot to apple boot logo, and never complete the jailbreak proccess! Please fix it!

**Comment by mau5atron** [comment]
@Italogc Please add information in proper format when opening a ticket. There's not enough information to help you (example: screenshots, version of iOS, etc.)

**Comment by suprstarrd** [comment]
^^^
