### ISSUE TITLE
Freezes unjailbreaks and restarts

### ISSUE THREAD

**Issue by ihaveproblems** [pwn20wndstuff/Undecimus#1819]
So after a couple of hours after jail breaking, it will freeze restart and unjailbreak so I have to rejailbreak, Its super annoying

**Screenshots**
      ...0 screenshots

 - iOS Version: 13.2.3
 - iOS Device: iPad (6 generation WiFi)
 - unc0ver Version: 4.2.1

 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

**Logs**
 No logs

**Comment by ihaveproblems** [comment]
Please fix

**Comment by ihaveproblems** [comment]
Well yes is is present after a rootfs restore with unc0ver but just after that I jailbreaked with unc0ver again
Before that I still had that issue

**Comment by Nicklasfox** [comment]
Do you by any chance have cozyBadges installed? I had it and removed it and now it works flawless ish.

**Comment by ihaveproblems** [comment]
I do

**Comment by ihaveproblems** [comment]
Imma remove it and try it, for now I can’t because I use appcake method to jailbreak and I don’t have my computer with me to do the AltStore method, and on the appcake method it restarted and unjailbreaked and appcake is revoked. Oof!

**Comment by Hamlock-Maneuver** [comment]
Learn about the app reprovision. And yes anytime you have problems like you have been having.  It's almost always caused by a tweak that was added afterwards.

**Comment by suprstarrd** [comment]
I actually had the problem before, most of the time an update to unc0ver does the trick for me. Whatever works for you, though, I guess
