### ISSUE TITLE
I have error 0 bro I can’t able to use cydia 

### ISSUE THREAD

**Issue by wakeupk2** [pwn20wndstuff/Undecimus#182]
Sub-process/usr/libexec/cydia/cydo recived a segmentation fault

**Comment by FivePixels** [comment]
This isn't a problem with unc0ver itself, rather an issue with your version of Cydia. You can resolve this in the #unc0ver channel on the r/Jailbreak Discord.

**Comment by wakeupk2** [comment]
How to reinstall cydia bro ?

**Comment by wakeupk2** [comment]
Or how to update cydia ?

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb
