### ISSUE TITLE
AFC2/ifunbox jailed state

### ISSUE THREAD

**Issue by nickxab** [pwn20wndstuff/Undecimus#1822]
**Describe the bug**
I have an iPhone 7 on iOS 13.3 jailbroken with unc0ver v4.2.1.
Installed AFC 2 v1.1.
The ifunbox detects the device as in Jailed mode.

![pic1](https://user-images.githubusercontent.com/7717789/75616421-3ce3cb00-5b59-11ea-8fca-71d2dfce106a.png)

**Device:**
 - iOS Version: 13.3
 - iOS Device: iPhone 7
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by stohle** [comment]
What's the bug here?

**Comment by nickxab** [comment]
You can't acces the raw file system (root) with USB.
Maybe there is a conflict with AFC2 and unc0ver.

**Comment by ex0ky** [comment]
People have the same problem on checkra1n too so it probably has nothing to do with u0 itself.
Also it only seems to affect ifunbox as other file managers do work for me.

**Comment by kynants** [comment]
Install Apple File Conduit 2 on your device and it should fix the problem:

https://cydia.saurik.com/package/com.saurik.afc2d/
