### ISSUE TITLE
iPhone 6s iOS 12.4.1 unc0ver says unsupported

### ISSUE THREAD

**Issue by eden1199** [pwn20wndstuff/Undecimus#1823]
![9E272814-FB4B-444C-AF18-25578243DCA8](https://user-images.githubusercontent.com/61640169/75618051-2f105480-5b1d-11ea-9a6b-bb89324808b6.png)

Downloaded uncover but says unsupported :(

**Comment by eden1199** [comment]
![1262E228-DA16-4E26-8A2B-B3F2C849628B](https://user-images.githubusercontent.com/61640169/75618060-4bac8c80-5b1d-11ea-8555-4f65cf82044e.png)
.

**Comment by jjbb528** [comment]
``

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lokisyn** [comment]
Same here 6s iOS 13.1 any answers yet?

**Comment by suprstarrd** [comment]
The 6s uses A9, and sadly there have not been much updates for early chips anymore besides A12 and A13 on iOS 13.0-13.3.

@eden1199 You can use unc0ver 3.8.0. If you can't install it let me know and I can try to help you.
@lokisyn You unfortunately cannot use your 6s with unc0ver until Pwn resolves the issues regarding the recent updates.

**Comment by Hamlock-Maneuver** [comment]
Use checkra1n.

**Comment by suprstarrd** [comment]
Ah, well yeah that's true. If they don't have a computer though they can't really do much

**Comment by luizgununes** [comment]
Same problem here with iPad Mini 2 on iOS 12.4, any ideas?
