### ISSUE TITLE
After connecting Bluetooth headphones in a jailbreak state it restarts and unjailbreaks

### ISSUE THREAD

**Issue by ihaveproblems** [pwn20wndstuff/Undecimus#1824]
**Describe the bug**
    When I connect my Bluetooth headphones after a jb it freezes restarts and unjailbreaks so I have to re jb

**To Reproduce**
1. Don’t connect Bluetooth headphones 
2. And connect them when you are in a non jb state
3. Connect them before jail breaking

**Screenshots**
If applicable

**Device:**
 - iOS Version: iOS 13.2.3
 - iOS Device: iPad 6 gen WiFi
 - unc0ver Version: v4.2.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable

**Comment by ihaveproblems** [comment]
And yes this was after a rootfs restore but the bug happened before that

**Comment by ihaveproblems** [comment]
It will also do that without connecting Bluetooth

**Comment by suprstarrd** [comment]
If it happens after a RootFS restore, check the box. I seem to be unable to have the issue you're describing.

Pwn is focusing on A12-A13 iOS 13 support, so 4.2.1 might not do the trick for you. Try downgrading to unc0ver 3.8.0 and try this again. Let me know how it does.

**Comment by Hamlock-Maneuver** [comment]
You have a bad tweak installed.  Most likely the airport tweak or something like that yes?  Just uninstall each tweak one by one until you find the offending tweak.

**Comment by ihaveproblems** [comment]
I’ll send a picture of my tweaks I have installed

**Comment by ihaveproblems** [comment]
![ED690553-2876-425F-AAE0-B033BE7F4781](https://user-images.githubusercontent.com/61595455/76168893-875cdd00-6141-11ea-9d72-a68d3d1de64d.png)

**Comment by ihaveproblems** [comment]
![7A02EDF4-6E9F-4B3A-A129-6E8CACB7678C](https://user-images.githubusercontent.com/61595455/76168903-99d71680-6141-11ea-80a1-a43723646006.png)

**Comment by ihaveproblems** [comment]
> If it happens after a RootFS restore, check the box. I seem to be unable to have the issue you're describing.
> 
> Pwn is focusing on A12-A13 iOS 13 support, so 4.2.1 might not do the trick for you. Try downgrading to unc0ver 3.8.0 and try this again. Let me know how it does.

3.8.0 doesn’t support my device

**Comment by ihaveproblems** [comment]
I removed cozy badges and it hasent done it in awhile 

I’ll give it a day and I’ll update y’all

**Comment by ihaveproblems** [comment]
Also I have AltStore install and ReProvision and there is no option to copy to AltStore any fix

**Comment by ihaveproblems** [comment]
And there is no option to copy to app cake either and I don’t have filza installed

**Comment by ihaveproblems** [comment]
I removed all tweaks and sources and added the good tweaks/sources and upgraded to unc0ver v4.3.1 and it’s fixed
