### ISSUE TITLE
Ios 13.3 beta unsupported

### ISSUE THREAD

**Issue by ios13-3beta** [pwn20wndstuff/Undecimus#1825]
![48429540-893A-452A-A700-99DB067B2CB5](https://user-images.githubusercontent.com/61723246/75742356-f87c3a80-5cd2-11ea-8213-66e7978e8fe2.png)

Is it not compatible or its just a bug?

**Comment by mau5atron** [comment]
@ios13-3beta Beta versions of iOS are not supported. Please close your ticket.
