### ISSUE TITLE
"Unsupported" Iphone 6s+ running 13.2.3 (Unc0ver 4.2.1)

### ISSUE THREAD

**Issue by parinzee** [pwn20wndstuff/Undecimus#1826]
**Describe the bug**
Uncover is saying "Unsupported" while iphone 6s+(running ios 13.2.3) has an A9 chip which is compatable with Unc0ver 4.2.1

**To Reproduce**
1. Install Alt Store on iphone 6s+
2. Sideload Undecimus.ipa through it
3. Enter Unc0ver App

**Screenshots**
![image](https://user-images.githubusercontent.com/30139280/75790221-73118c80-5d9d-11ea-9255-222184df80b1.png)

**Device (please complete the following information):**
 - iOS Version: 13.2.3
 - iOS Device: Iphone 6S+
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by lokisyn** [comment]
6s iOS 13.1 same issue any ideas?

**Comment by Hamlock-Maneuver** [comment]
Try using checkra1n.

**Comment by lokisyn** [comment]
I do use checkra1n lol but I can’t lug my hackintosh everywhere ....Unc0ver was good for me cause I’ll be out n about and some of my tweaks will jam .....icleaner as an example will just freeze up after being jail broke for a few days idk why

**Comment by Hamlock-Maneuver** [comment]
Try this.  Download an app from cydia called cocoatop.  You will need version 2.2 which can be found on certain repos that I can't post here. Just google it and you should be fine.  Anyway this program acts just like windows task manager. You should be able to see whats going on with your jailbroken phone.   Let us know what you find out.

**Comment by lokisyn** [comment]
Thanks yo I’ll try it to see what’s going on

**Comment by azooz12312312312** [comment]
![7AD4FD1C-1A60-44A1-A8AB-10F0AE5AC2E4](https://user-images.githubusercontent.com/61816553/76393043-c9756100-6383-11ea-9da6-f144e72479a7.png)

**Comment by azooz12312312312** [comment]
``

- 

- [ ] 

> @

>

**Comment by azooz12312312312** [comment]
😩😭😎👌😒😍😂😂☺️😔😔💁😍😍
