### ISSUE TITLE
iPhone X warming up on 13.3

### ISSUE THREAD

**Issue by jasons-open-repo** [pwn20wndstuff/Undecimus#1829]
My iPhone X GSM 64GB South Korea model is warming up when jailbroken with tweaks loaded and unloaded.

**Comment by suprstarrd** [comment]
This may not be a jailbreak issue. Does this happen outside of your jailbreak?

**Comment by Hamlock-Maneuver** [comment]
Install an app from cydia called cocoatop. You will need to find version 2.2. I can't post the repo on here, but this is very easy to google and find.  This app is basically task manager for IOS.  You will be able to see what is taking up so much cpu usage and causing it to heat up.

**Comment by suprstarrd** [comment]
https://d0m0.github.io/
