### ISSUE TITLE
Substrate breaks my ability to download third party apps from signing services

### ISSUE THREAD

**Issue by Amaan423** [pwn20wndstuff/Undecimus#183]
I had to downgrade back to substitute in order to be able to download third party apps again but when I had substrate it would not let me download anything from a signing services and I tried multiple different ones.

**Comment by Samgisaninja** [comment]
Turn off "disable app revokes" and try again.

If not, this means that the signing services were revoked and they need a new certificate.

This is not a code-level issue with unc0ver and is therefore closed.
