### ISSUE TITLE
IPHONE REBOOTS IN NON JAILBREAK MODE

### ISSUE THREAD

**Issue by mudi47** [pwn20wndstuff/Undecimus#1830]
my iphone 8 on ios 13.3 restarts (HARD RESTART) automatically every two days
Im on unc0ver  V4.2.1.

**Comment by xieao100** [comment]
Me too, hard restarts directly after opening multiple applications。7plus

**Comment by Hamlock-Maneuver** [comment]
If it is rebooting in a non-jailbroken state.  Why would you come and post here?   That sounds like a hardware problem.

**Comment by suprstarrd** [comment]
To clarify, this only started happening after unc0ver was installed, correct? When did you get your iPhone?

If this happened after unc0ver was installed, restore RootFS, then let me know how it goes.

**Comment by Hamlock-Maneuver** [comment]
It's most likely a bad tweak installed.  One by one start to uninstall each tweak and give it some time after each uninstall to see if it stops the restarts.  Restoring your rootfs is a bit harsh and premature at this time.

**Comment by suprstarrd** [comment]
It's happening even outside of jailbreak mode... why would a tweak do that if nothing is loaded in the first place?

**Comment by suprstarrd** [comment]
But yeah it is a bit harsh I'll say that. If after uninstalling all the tweaks it's still occurring, let us know
