### ISSUE TITLE
Unc0ver

### ISSUE THREAD

**Issue by lkfete** [pwn20wndstuff/Undecimus#1831]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by azooz12312312312** [comment]
> **Describe the feature you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
