### ISSUE TITLE
Under cimus error

### ISSUE THREAD

**Issue by JacketPotatoYT** [pwn20wndstuff/Undecimus#1834]
K

**Comment by Hamlock-Maneuver** [comment]
Dude.  what are you doing?

**Comment by JacketPotatoYT** [comment]
Oops I accidentally made one without the info check out the other one I posted sry

**Comment by suprstarrd** [comment]
You should probably close this. Click the "Close" button below (not "Close & comment", unless you're going to comment before you close!), then this will get out of the way and the main issue will be in the Open tab.

In the meantime, keep responses at #1835
