### ISSUE TITLE
Dominos Pizza App Wont Let You Order Jailbroken 

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1836]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to Dominos
2. Click on create a new Order
3. Scroll down to enter your card Information
4. See error We are Sorry we are Unable to Prosseses your order please contact the Store

i try Shadow Tweak Still Dominos App Detects The Phone Jailbroken

**Screenshots**

![C1087FE6-4863-4931-ACA3-4033403D38C1](https://user-images.githubusercontent.com/36649261/76134396-ec062380-5feb-11ea-9c44-210f9f0f9e08.png)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iOS 13.3
 - unc0ver Version: Unc0ver 4.2.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
try on none jailbroken iOS 13.3.1 and i the order was place successfully

**Comment by Hamlock-Maneuver** [comment]
Update the pizzahut app.  Mine works just fine jailbroken.

**Comment by miguelr4720** [comment]
problem is not pizza hut is the dominos app when you try to checkout for and order

**Comment by Hamlock-Maneuver** [comment]
Then it's your credit card.  Don't downvote people just because you don't like what you hear.  You want a reason to downvote me?  STOP BEING POOR...

**Comment by miguelr4720** [comment]
i am pretty sure is not my card i did it on my friends phone he is not jailbroken and he is running the latest version 13.3.1 and my card worked fine on his phone

**Comment by miguelr4720** [comment]
and i used the same account on his phone and it worked i also try a different account still the same error persists if you are Jailbroken Dominos must have a jailbrake detector :(

**Comment by miguelr4720** [comment]
am surprised they force you to update in the app i also try downgrading from using AppStore++ and it required the latest version of Dominos i get when i try to use older version

**Comment by Hamlock-Maneuver** [comment]
version 7.1.0 yes?  It works just fine.

**Comment by Hamlock-Maneuver** [comment]
You probably have pirate tweaks loaded.  Uninstall the offending tweak and try again.

**Comment by miguelr4720** [comment]
> You probably have pirate tweaks loaded. Uninstall the offending tweak and try again.

what pirate tweak i checked i did not see none

**Comment by Hamlock-Maneuver** [comment]
What do you mean "what pirate tweaks".  I don't have your phone in front of me.  No way for me to check your phone.  You will need to check yourself.

**Comment by miguelr4720** [comment]
well am dode at this point i also try Shadow and still the error persist hopefully it gets fixed wish i doubt it

**Comment by miguelr4720** [comment]
using the website directly shortcut home screen works fine for me

**Comment by Hamlock-Maneuver** [comment]
I'm trying to tell you.  There is nothing to fix except on your end.  The app works fine.   Maybe because you have appstore++ installed.  Maybe thats the problem?

**Comment by miguelr4720** [comment]
Wish is not AppStore++ and i try with the latest version still the problem persist try a different account on the Device and the error continues

**Comment by Hamlock-Maneuver** [comment]
Down vote me all you want.  You acting like a child is not going to fix your problem.  And remember.  Its your problem.  not ours.  Have a good day.

**Comment by miguelr4720** [comment]
> Down vote me all you want. You acting like a child is not going to fix your problem. And remember. Its your problem. not ours. Have a good day.

so fix it please idk why am having this problem am not the only person having problems with jailbrake angry for no reason

**Comment by Hamlock-Maneuver** [comment]
I told you why you have that problem.  You refuse to accept it.  Nothing more can be done if you will not listen.  Move along please.

**Comment by miguelr4720** [comment]
like i said using safari works fine for me so idk why the App is doing this bro

**Comment by miguelr4720** [comment]
ill just keep using browser shortcut thats it and where Unc0ver 4.3.0 wish never released this is crazy lol

**Comment by jbmagination** [comment]
@miguelr4720 It's not about if they can fix it. They are literally unable to do it. It's their job, or another dev's job. Definitely not Pwn's.

**Comment by suprstarrd** [comment]
@miguelr4720 It's not about if they can fix it, they can't really do it. Domino's either needs to remove the jailbreak detection (which I doubt they will, otherwise people could fake a purchase and order the pizza for free), or Shadow/any other bypass needs to fix their tweak to work with the app.

**Comment by thpryrchn** [comment]
That is probably a jailbrake detection issue, and nothing to do with UnC0ver... Try Liberty Lite beta, and see if that fixes it.
