### ISSUE TITLE
VPN doesn't work in jalbreak mode

### ISSUE THREAD

**Issue by Supersqualo** [pwn20wndstuff/Undecimus#1837]
**Describe the bug**
Personal VPN (IPsec) doesn't work when jailbreak is on!
When i reboot it work correctly.
I tried in safemode and doesn't connect equally to the vpn!
I tried to jailbreak with unc0ver keeping the VPN connection active but after the restart of the springboard the VPN connection is deactivated and no longer reconnects

**Device (please complete the following information):**
 - iOS Version: 13.2.3
 - iOS Device: iPhone 11 Pro
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Comment by suprstarrd** [comment]
This is likely a part of the app. Try using a tweak such as Shadow to circumvent jailbreak detection on the app, then let me know how it does.

If it fails then it is likely an unc0ver issue.

**Comment by Hamlock-Maneuver** [comment]
Go into the jailbroken state and then recreate the VPN connection. See if that fixes it.

**Comment by Supersqualo** [comment]
> This is likely a part of the app. Try using a tweak such as Shadow to circumvent jailbreak detection on the app, then let me know how it does.
> 
> If it fails then it is likely an unc0ver issue.

I tried to add https://ios.jjolano.me/ without results(Is there any problem)! but I doubt it can be resolved!

> Go into the jailbroken state and then recreate the VPN connection. See if that fixes it.

I've already tried it. I also tried to create a new vpn account without results
I also tried on another iphone 11 pro jb with ios 13.2

**Comment by Hamlock-Maneuver** [comment]
Ok then that sounds like a problem with unc0ver. This might be fixed in the next 4.3.0 version.

**Comment by suprstarrd** [comment]
^

**Comment by Supersqualo** [comment]
unc0ver 4.3.1 has solved the problem. Thanks a lot
