### ISSUE TITLE
One-time-passwords not filling automatically

### ISSUE THREAD

**Issue by vpww** [pwn20wndstuff/Undecimus#1838]
More info here https://reddit.com/r/jailbreak/comments/fbt470/help_issue_with_otp_verification_codes_as_sms/

In non jb mode this works normally: button with password fills the form
Not working in jb mode even with all tweaks disabled
Otp passwords are used in banking apps, or in apps with authentication by mobile phone via sms
Can be checked in tinder for example

**Comment by suprstarrd** [comment]
This is likely part of the app, however it may not be. We'll see.

In the meantime you could try using a jailbreak detection bypass tweak such as Shadow, and use it on the app. See if it works, then let me know how it does.

**Comment by vpww** [comment]
> This is likely part of the app, however it may not be. We'll see.
> 
> In the meantime you could try using a jailbreak detection bypass tweak such as Shadow, and use it on the app. See if it works, then let me know how it does.

Tried shadow, liberty lite, choicy - no result in several app
The only thing that helps in jb mode for some short period of time - idrestart

**Comment by suprstarrd** [comment]
4.3.1 came out recently, try upgrading

**Comment by vpww** [comment]
> 4.3.1 came out recently, try upgrading

Still experience same problem on the latest u0
