### ISSUE TITLE
Unable to call, open apps through push notification, or open apps through notification center widgets [iPhone SE, iOS 11.3.1]

### ISSUE THREAD

**Issue by kerabyte** [pwn20wndstuff/Undecimus#184]
Lumped these all into one issue, as they all seem to be related.

## Calling

**Problem:** Clicking on contact in the Phone app or phone button in contact page in iMessage should start a call; touch is registered but call does not start

**Workaround:** Asking Siri to call someone works, no noticeable problems in call

## Push notifications

**Problem:** Clicking on push notification should open the app in context; touch does not seem to be registered and app does not open

**Workaround:** None found so far

## Notification center widgets

**Problem:** Clicking on notification center widget should open the widget's parent app; touch is registered, widget is stuck being darkened (as if being held down), app does not open

**Workaround:** None found so far

**Comment by Fenyx95** [comment]
It seems you have the tweak opener, if yes delete it, it need to be update to work with substrate

**Comment by jakeajames** [comment]
Before opening an issue please verify it's not a problem of your tweaks.

**Comment by kerabyte** [comment]
@Fenyx95 Thank you, that fixed it!
@jakeajames Sorry, I'll keep that in mind for later issues.
