### ISSUE TITLE
Whole phone won’t turn off or open anything

### ISSUE THREAD

**Issue by miggse** [pwn20wndstuff/Undecimus#1842]
Went to re jailbreak my 11 pro max ios13.3 using the new 4.3.1 and now nothing works on my phone every app I open it closes its self instantly and I can’t turn my phone off at all even using the long presses

**Comment by Hamlock-Maneuver** [comment]
You need to do this procedure fast for it to work.  Quickly press volume up, volume down and then hold the lock button until you see the screen go black.  wait another second or two then release the lock button.  You should see the apple logo shortly.

**Comment by ning0626** [comment]
substitute是不是最新的，如果是降级一下就好了，我的也这样

**Comment by ning0626** [comment]
Substitute  这个插件如果是最新的，降级就好了

**Comment by Cryptiiiic** [comment]
@ning0626 Are you telling people to downgrade substitute?
substitute 你是在叫人降级吗
