### ISSUE TITLE
ldid post-install script failed exit(2) when installing ldid(2:2.1.1+elucubratus2)

### ISSUE THREAD

**Issue by johnny115** [pwn20wndstuff/Undecimus#1843]
**Describe the bug**
rootfs first and the open the 4.3.1 and done cydia to upgrade by itself 
only this app "link identity editor" will turn out a error

form  2.1.1+elucubratus to 2.1.2+24497ae-1 @ apt.bingner.com
and then will get a error in red 

![image](https://user-images.githubusercontent.com/20432296/76182509-13353e80-6200-11ea-816b-ce42a44a3525.png)

install ldid error come out then all cydia app would not install by then

when the iphone restart the run unc0ver and go to 21step will pop out repair the system failed
see the log is ldid error too 

I need to rootfs to clear the error and then no update the ldid
what wrong with this ldid?

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: 6sp
 - unc0ver Version:3.8~4.3.1

**Comment by Cryptiiiic** [comment]
@johnny115 please post unc0ver diagnostics. Also post /tmp/cydia.log

**Comment by Cryptiiiic** [comment]
No response
