### ISSUE TITLE
Phone calls

### ISSUE THREAD

**Issue by Randy-420** [pwn20wndstuff/Undecimus#1846]
**Describe the bug**

When I make / receive phone calls (in a jailbroken state or in safe mode) I can’t hear the other person and they can’t hear me unc0ver 4.3.1

**To Reproduce**
Make or receive a phone call?

**Screenshots**
None

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: xs max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ¿x?] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore (once rejailbroken only)
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

No logs produced as there’s no crash.

**Comment by Hamlock-Maneuver** [comment]
Do you have any sort of call tweaks installed? Callrecorder, callbar, ect...?

**Comment by Randy-420** [comment]
Answeringmachine xs

Calleridtoggle

**Comment by Hamlock-Maneuver** [comment]
Uninstalled each one and then test.

**Comment by Randy-420** [comment]
Since I jailbroke using “reload daemons” I haven’t had an issue -
