### ISSUE TITLE
Device randomly reboots few hours after jailbreaking. 

### ISSUE THREAD

**Issue by Wanqed** [pwn20wndstuff/Undecimus#1847]
**Describe the bug**
I jailbreak the device, works flawlessly when jailbreaking, no errors, nothing like that. Few hours later my device just randomly reboots doesn’t matter what I’m doing or if anything is even running, device could be locked and not touched and it’d do it randomly.

**To Reproduce**
No way to reproduce, just happens randomly.

**Screenshots**
N/A

**Device (please complete the following information):**
 - iOS Version: 13.2.3
 - iOS Device: iPhone 7
 - unc0ver Version: 4.3.1 (happened in previous also)

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
Ok.  Just to let you know before we continue.  That particular iphone has been known to have weird problems like this.  A Lot of times its a bad battery, But most of the time its a bad part of the logic board.  I myself have experienced this exact same issue with my iphone 7.  It progressively got worse until one day it just never turned back on.  I replaced the battery, and still nothing. Louis Rossman touches base on this issue in detail. He is a youtuber who fixes Apple products.

Anyway.  Now that you have heard the news you were really wanting to hear.  Lets get started.
Try a couple of tweaks called cocoatop version 2.2 and crashreporter 1.17 . cocoatop is just like task manager, but for IOS.  You can easily see if something is not running right.  Check those out and let us know.

**Comment by Colmix141** [comment]
Exact same issue here iPad pro 9.7 MLMQ2LL/A iOS 13.3, I’m experiencing this issue since 4.1.1

**Comment by Hamlock-Maneuver** [comment]
Download a tweak from cydia called batterylife 1.7.0.  This should show you how many times you have actually charged your devices.  Please come back here with the results.

**Comment by Colmix141** [comment]
![AEA479BA-1695-461E-92DE-7F10FE84DE51](https://user-images.githubusercontent.com/62006855/76302013-87adc300-627c-11ea-83e2-3c3364f848e0.png)
Hello, thank you for your response, here is the screenshot from the tweak you recommended.

**Comment by Wanqed** [comment]
[BatteryLife](https://user-images.githubusercontent.com/46340191/76306170-ca7f9300-629c-11ea-9699-b5bba42618e5.png)
Here’s my screenshot, the only crashes I see that are reported in CrashReporter are from apps I’ve opened once the crash happens. Which Snapchat has been only one for while bc that’s what I’m mainly on. But there’s also a suggestd daemon crash log also which popped up after a random reboot. Should I post both the Snapchat and Suggestd crash logs?

**Comment by Wanqed** [comment]
Here’s these 2 if they explain further about my issue. Both have crash logs after the reboot happened earlier today (separate crash logs different time)

[Suggestd Crash logs](https://easyupload.io/dxv3cp) 

[Snapchat crash logs](https://easyupload.io/tk10jx)

**Comment by Mikasa-san** [comment]
if you have rocketbootstrap make sure its on version 1.0.7b3
if no add this repo: rpetri.ch/repo/

**Comment by Wanqed** [comment]
I have rocketbootstrap and it’s on that version. I’ll try uninstalling it to see if that’s the problem.

**Comment by Hamlock-Maneuver** [comment]
Ok.  from the looks of it.  You simply need a new battery.  This should fix the random reboots.   When you get up to 600 cycles, that's when weird stuff can start to happen.

**Comment by Hamlock-Maneuver** [comment]
Its not that the battery is dying all the way.  Whats happening is the phone/ipad will call for a specific amount of power for whatever reason.  If the available mA's are not there. The phone will kill some other process to make up for the power loss, and sometimes it hits a process that is needed for operation to continue.  Thus a restart happens.

**Comment by Wanqed** [comment]
But I also have a iPhone 6s with 2k charge cycles and 50% battery capacity and my uptime on unc0ver with it is 20 days no random reboots (older unc0ver version) on it though.

**Comment by Hamlock-Maneuver** [comment]
https://www.igeeksblog.com/how-to-check-if-iphone-battery-need-to-replace/

**Comment by Wanqed** [comment]
I give up at this point lmao there’s no possible fix for this unless it’s addressed through the system. My battery capacity on this phone 87% which shouldn’t need serviced, below 80% is when it needs serviced.

**Comment by Hamlock-Maneuver** [comment]
Dude. What is there to figure out?  I guarantee it's your battery.  You have gone over your max charge limit by more then double.  In other words you have charged your phone 739 times OVER it's limit.
Just so you don't get confused as to what I'm telling you to do...  REPLACE YOUR BATTERY.

**Comment by mrzaptolab** [comment]
I have the same issues, iPhone 7 iOS 13.3 / Unc0ver 4.3.1 (battery with 45 cycles, 100% health, so for me the battery is not the fault).
The random reboots / resprings usually happen when I open certain apps like Snappchat.. My phone had a random restart while I was in a call.. which is very annoying. I tried rejailbreaking and after using the phone without any tweaks the freezing s rebooting problem appeared again.. i am currently running stock until the problem gets fixed

**Comment by Hamlock-Maneuver** [comment]
What you might have is a known issue with iphone 7s.  Louis Rossman a youtuber explains this better then I can.  
To help see if this is the problem.  Try running Antutu benchmark or geekbench.   This is what triggered this behavior on my iphone 7. It would randomly restart until finally I got a boot loop.    I went to update and restore, and it finally just died completely.

**Comment by Wanqed** [comment]
@Hamlock-Maneuver i used Antutu Benchmark and it went through 100% no restart. So Im sure it’s not battery issue. Idk what’s causing it because I’ve jailbroke with tweaks off and still reboot. I’ll have to try with daemons off, but I’ve restored rootfs also twice and rejailbroke and still happens, I’ve even reinstalled Cydia, reload icon cache, all that. No luck :(

**Comment by Wanqed** [comment]
Just jailbroke with load daemons off and load tweaks off, still rebooted randomly. Doesn’t require anything to trigger it, never shows up in crash logs, nothing. I’ve tried crashreporter, I’ve tried the diagnostic logs in Unc0ver (not sure why I’m not sure if that’s the problem.) but yeah. Guess I’ll just stay in stock OS until a fix is implemented :/

**Comment by Hamlock-Maneuver** [comment]
Wanqed.  Ive explained how you can fix your problem.  You refuse to listen.   You say it happens with or with out the jailbreak.  You say you cant see anything is the crash log.  And why would you?   There is nothing else to be said about your issue Wanqed.  I understand you don't want to believe it.  But in this situation.  Substituting your own reality just isn't going to be enough. There is nothing left to offer you.  I'm sorry.

**Comment by Wanqed** [comment]
Ok but I’ve ran antutu benchmark like you asked, and there was no restart. Which means it’s not the battery. Because as you explained “if you run antutu benchmark it will restart your device” but it didn’t.

**Comment by Hamlock-Maneuver** [comment]
You said it does this with or without jailbreak.  You have 1300+ cycles on your phone.  Take it to ANY shop including apple and they will tell you the exact same thing.

**Comment by andre104623** [comment]
1300 cycles is crazy it’s unbelievable it works off the charger I had a issue with the battery in my se and using Electra on iOS 11.1 it would just respiring back to stock by itself new battery still works now on 13.3 with checkra1n

**Comment by Colmix141** [comment]
Is not the battery, restored RootFS last week and deleted unc0ver, no reboots since then, on Friday installed checkra1n to jailbreak my iPad and is running as usual without any reboot.

**Comment by Hamlock-Maneuver** [comment]
Uninstall any sort of jailbreak detection bypass tweaks.  liberty lite, a-bypass, ect...

**Comment by Cryptiiiic** [comment]
@Wanqed please post unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
@Wanqed also panic-full, reset-counter, and panic-base crash logs

**Comment by Wanqed** [comment]
@Cryptiiiic 
Unc0ver diag -https://easyupload.io/ukjpgg

Panic-base - https://easyupload.io/xyliep

Panic-full - https://easyupload.io/hv43hm

Reset-counter - https://easyupload.io/abevpc

(For some reason couldn’t add text to links it wasn’t working, so I apologize in advance)

**Comment by Cryptiiiic** [comment]
**Unfortunately, to reduce issue spam/clutter, help is not provided for those who have pirate packages or repos.** I can in fact help you after you remove all your piracy. After removing all of it, please say if you still experience reboots. Closing this for now. I will reopen if you still have this issue after removing piracy. @Wanqed

**Comment by Wanqed** [comment]
@Cryptiiiic Removed all piracy you henced at and had a reboot about 20 mins after, and when I turn load tweaks off and load daemons off it’s the same, I’ve restored rootfs also and didn’t install any tweaks to see if it would reboot and it still did.

**Comment by Cryptiiiic** [comment]
@Wanqed then it's an unc0ver bug

**Comment by Wanqed** [comment]
@Cryptiiiic I’m gonna wait for another reboot to send unc0ver diagnostics i cleared them to get rid of piracy tweaks in the log, I’m gonna post fresh one when it happens again. Unless you need all the logs again? Panic-full and all that?
