### ISSUE TITLE
Certain AppStore apps won’t open after being re-installed

### ISSUE THREAD

**Issue by CallumEddisford** [pwn20wndstuff/Undecimus#1848]
**General information**
Unc0ver version: 4.3.1
iOS version: 12.4
Device: XS Max
Sideloaded through AltStore
Not running many tweaks so can class this as a pretty much clean Jailbreak.

**Notes**
- Only happens with certain apps
- Can be worked around

**Issue/Steps to re-produce**
Deleting an AppStore app and re-installing the app in jailbroken state causes app not to launch. If you reboot the device and launch the app (it will launch fine non-jailbroken) then jailbreak and open the app, it will work fine from then onwards.

**Known issue apps**
- Facebook
- Facebook Messenger

I haven’t really tried going through and deleting all my apps to test this, one app was fine to do this but I did notice this issue with these apps. I deleted the above apps several times each with the same result. My crash report tool doesn’t catch anything either so unfortunately I have no logs. Im happy to share a screen cap.

**Comment by Hamlock-Maneuver** [comment]
Did you try hard restarting your phone, rejailbreaking and just trying again?   Sometimes weird shit happens and you need to restart.
Try a couple tweaks called cocoatop 2.2 and crashreporter 1.17.2

**Comment by CallumEddisford** [comment]
Yup tried rebooting but the apps still crash when deleted and re-installed whilst jailbroken. The issue itself is for the reason of having to reboot the device in order open the app. 

I’m using Cr4shed and cocoatop, nothing out of the ordinary.

**Comment by Hamlock-Maneuver** [comment]
Ok so I noticed you were on 12.4.   Try using unc0ver 4.0.3. see if that fixes it.

**Comment by Hamlock-Maneuver** [comment]
The new unc0vers are mainly geared towards ios 13.  Not so much for ios 12.  Not yet anyway.

**Comment by CallumEddisford** [comment]
To be honest I prefer unc0ver 4.3.x as other than this one small issue I find myself having a lot less random crashing and random resprings like I experience with 4.0.3. 
I can happily try 4.0.3 to see if the same issue is persistent in older versions but I know those problems will come back which in this case is worse off for me (for now). 

The below screenshot is what happens when I open an app following these steps

Starting in stock iOS. 
1. Install Facebook Messenger and log in
2. Jailbreak
3. Open messenger (will open fine)
4. Delete messenger + re-install from App Store
5. Open messenger again
6. App crashes/hangs for 15 secs

Here is the screenshot from cocoa-top showing messenger a few seconds after opening it - stays at 100 cpu for about 15 seconds (consistently) then closes itself off.  
![66D5EBA9-6E42-47BE-BFF1-54598C1EA0F4](https://user-images.githubusercontent.com/7395118/76338204-46ef9180-62f0-11ea-9b2f-18e67f51ca58.png)

I’m not personally looking for a solution/fix to this issue as like I say it can be worked around but I guess it’s still a bug somewhere?

**Comment by Hamlock-Maneuver** [comment]
I would just try 4.0.3 to see if it's better.  You obviously know what you are doing.  So what can it hurt?

**Comment by Cryptiiiic** [comment]
@CallumEddisford please post your unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
@CallumEddisford Also see if crash logs show in in the stock iOS crash logs tab.

**Comment by Cryptiiiic** [comment]
No response
