### ISSUE TITLE
Random Reboot on unc0ver 4.3.1

### ISSUE THREAD

**Issue by mehmetakifsimsek** [pwn20wndstuff/Undecimus#1849]
**Describe the bug**
After 12 hours device rebooted randomly. (Restored via Succession 1.4.12 with unc0ver 4.3.1) and every tweak activated that all compatible with my ios version.

**Crash Log**
  - Here is the log file: https://www.icloud.com/iclouddrive/0olk9C_8OmItHuouA3AMOqhMQ#stacks%2Blocationd-2020-03-10-120626

**Device:**
 - iOS Version:  13.3
 - iOS Device:  iPhone 9,4
 - unc0ver Version: 4.3.1
 - Signed via ReProvision

 - [X] this issue is present on the latest version of unc0ver

**Comment by stohle** [comment]
Why are you using unc0ver 3.7.1?

**Comment by mehmetakifsimsek** [comment]
> Why are you using unc0ver 3.7.1?

Oh, It's my bad. I realized when e-mail notificate came. Its 4.3.1 actually.

**Comment by stohle** [comment]
You can find crash logs in Settings > Privacy > Analytics > Analytics Data.
Post it here if there's one there

also remeber to change the unc0ver version here too "**(Restored via Succession 1.4.12 with unc0ver 3.7.1)**"

**Comment by xieao100** [comment]
My 7 plus is also at the same time in the boot  open multiple app will restart

**Comment by miguelr4720** [comment]
use ccleaner and disable all tweaks
![32AD39D5-A196-4A81-87C5-AE6B5D07B967](https://user-images.githubusercontent.com/36649261/76472650-91464080-63cc-11ea-9824-f7c13c2456d6.png)
![D5B16D97-3BE4-4207-93BC-3912955ADDDA](https://user-images.githubusercontent.com/36649261/76472651-91ded700-63cc-11ea-91dd-0aff054bac4b.png)

**Comment by Cryptiiiic** [comment]
@mehmetakifsimsek please post unc0ver diagnostics.

**Comment by klepp0906** [comment]
I’m getting the same issue on my iPad on 13.3 using 4.3.1 

It’s the first time it’s been jail broken and only using about 5 tweaks.  Same tweaks on the iPhone and it doesn’t seem to happen. 

What info can I provide you guys to help?

**Comment by Tgod1991** [comment]
Im having a random reboot issue also iPhone 6s. iOS 13.1.2. unc0ver version 4.3.1. When it happens sometimes I can’t open unc0ver app it just crashes upon opening

**Comment by Cryptiiiic** [comment]
#1890

**Comment by imsonova** [comment]
Im having the same issue with unc0ver 4.3.1. When i re-jailbreak my phone, the next day (even the later that day sometimes) my phone will just restart. I never had this issue with checkra1n and im using the exact same tweaks as i was when i was on the checkra1n jailbreak. Here’s the link to the panic log for the random reboots [My panic log](https://www.sendspace.com/file/nhp671)
