### ISSUE TITLE
6s, 2.0.2, can’t turn passcode&autolock on

### ISSUE THREAD

**Issue by Ragdo11cat** [pwn20wndstuff/Undecimus#185]
Iphone6s, 11.2.6, unc0ver 2.0.2
After jailbreak, I can’t turn my passcode back on and also auto lock get sucked at “never”

Every single time I try to turn it on is just not working

PlZ help

**Comment by jakeajames** [comment]
Please explain better and with a more proper english.

**Comment by Ragdo11cat** [comment]
the passcode can’t turn on, not working.
And auto lock cant change from “never” to other option...
Can someone help me (crying
Wanna try semi restore11 but it not working at iOS 11.2.6

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb
