### ISSUE TITLE
Somehow you guys still haven’t fixed this...

### ISSUE THREAD

**Issue by lokimudhearth** [pwn20wndstuff/Undecimus#1850]
**Describe the bug**
This issue has been present in the last 2 versions. If you are listening to ANY audio (Spotify, music, a fucking phone call) and you are doing ANYTHING else (scrolling Facebook, opening chrome, sending a text) it will reboot and you lose jailbreak. This is NOT caused by a tweak, it is present with NO tweaks installed.

**To Reproduce**
1. Listen to ANY audio
2. Open ANY other app
3. Wait a bit, switch apps a few times
4. Forced reboot

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 6s
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ x ] this is a bug others will be able to reproduce
 - [ x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
Download a tweak called Batterylife 1.7.0.   Post a screenshot of the results here please.   I think you have a battery that's about to die.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver I’ve seen you comment this on a few different posts, and I’m sure you got at least one right, but this is a brand new phone. My battery is fine.

**Comment by Hamlock-Maneuver** [comment]
Ok bro.  But your phone was created over 5 years ago.  Batteries do not last forever. Even if you don't use them.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver what the hell are you talking about? This phone is a few months old. The battery is in perfect condition.

**Comment by Hamlock-Maneuver** [comment]
Its an iphone 6s

**Comment by Hamlock-Maneuver** [comment]
No point in starting an argument.  If you don't want to check your battery.  Then simply don't.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver and? Bro are you a maintainer? Do you contribute to this jailbreak? Then you know dick. 

My battery is fine. Go troll somewhere else.

**Comment by Hamlock-Maneuver** [comment]
I have an iphone 6 and 2 ipad 4's that this same thing has happened to.  I replaced their batteries, and they all work just fine.  But you are right.  I should just go troll some other people with the correct answers.  You have a great day.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver dude, go away. My battery is fine. And I don’t need some obscure, “likely working” tweak that has access to my battery serial to tell me that. 

When you first commented, you were “sure” my battery was about to fail. As I said, it’s brand new. This is not a battery problem. Full stop. Have a nice night.

**Comment by Hamlock-Maneuver** [comment]
So you just purchased the phone "brand new" yes?

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver you don’t listen to well do you?

Go.
Away.

**Comment by Hamlock-Maneuver** [comment]
Neither do you apparently.  Unless you found some iphone factory that makes your phone right there when you purchase it.  Your phone is over 5 years old.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver im well aware that my iPhone is no longer being manufactured. But THE BATTERY IS FINE.

KINDLY, FUCK OFF.

**Comment by Hamlock-Maneuver** [comment]
Unless you changed out the battery.  No it is not fine.  Lithium ion batteries do not last forever.   If they sit in a box for any length of time, and lose their charge.  The battery will start a degradation process.
For a battery to last its longest.  It actually needs to be at %50. Sitting in a box at a store for over 5 years...  Its going to degrade bro.  Anyway.  I'm done trying to help you.  Do some research bro.  Yes it's your battery.

**Comment by Hamlock-Maneuver** [comment]
And if you do not want help here.  Then close your ticket. No point in wasting our time.

**Comment by lokimudhearth** [comment]
Go the fuck away dude. You’re not attached to this project. You’re not helping in anyway. I’ll tell you once more before I report you. 

My battery is fucking fine.

Go the fuck away.

Stop commenting.

I don’t want your “help”.

Fuck.
Off.

**Comment by Hamlock-Maneuver** [comment]
Hey.  Stop being abusive or you will get reported yourself.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver then stop fucking commenting like I’ve asked you to many times. You don’t know what the fuck you’re talking about. Stop commenting.

**Comment by Hamlock-Maneuver** [comment]
https://help.github.com/en/github/site-policy/github-community-guidelines

Last time I'm going to ask you.

**Comment by lokimudhearth** [comment]
@Hamlock-Maneuver and this will be the last time I ask you. Go the fuck away.

**Comment by Hamlock-Maneuver** [comment]
It doesn't seem like anyone is willing to help you.   I'm still here if you would like to download Batterylife and post that screenshot.

**Comment by lokimudhearth** [comment]
Dude. I’m not downloading some malware infested tweak. I really thought I made myself clear. Go away.

**Comment by lokimudhearth** [comment]
![6E3EE8E0-036D-45EF-A8E1-7C61B9CF90C7](https://user-images.githubusercontent.com/61324357/76591039-1a3ca500-64bd-11ea-83f2-386aa8cfd902.png)

Here, just to shut you up. 

As I said THREE DAYS AGO, my battery is FINE.

So what’s the plan now? You need a screenshot of anything else that would have fuck all to do with why a piece of software isn’t working?

**Comment by Hamlock-Maneuver** [comment]
Hey bro.  Calm down.  You seem full of hate and should probably relax before you have a stroke. It doesn't invalidate anything I have told you.  You still have a 5+ year old battery.   Here try this.  Maybe the rest of the world can convince you.  I surely can not. 
https://www.igeeksblog.com/how-to-check-if-iphone-battery-need-to-replace/

**Comment by Hamlock-Maneuver** [comment]
I'm sure they are wrong as well.

**Comment by lokimudhearth** [comment]
Jesus Christ you’re an idiot. I just showed you where my battery is fine and you persist. I’m blocking you, reporting you and closing this thread. For fucks sake, people like you are what gives the jailbreak community a bad name.
