### ISSUE TITLE
Safari frozen

### ISSUE THREAD

**Issue by stohle** [pwn20wndstuff/Undecimus#1851]
Safari is frozen.
After using u0 4.3.1 safari freeze whenever the keyboard is going to show up. 
No tweaks or anything affecting keyboard is installed.
Bug introduced in 4.3.1

Does anyone else have this?

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: XS Max Global
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [dont know ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by Hamlock-Maneuver** [comment]
Try using 4.0.3    You are on ios 12.  4.3.1 is mainly for ios 13.

**Comment by Hamlock-Maneuver** [comment]
Also you might want to list the tweaks you are using anyway.

**Comment by stohle** [comment]
> Try using 4.0.3 You are on ios 12. 4.3.1 is mainly for ios 13.

It's not that i cant fix the problem. I'm just reporting that there might be a new bug introduced for A12 on 12.4 in the latest u0

**Comment by Cryptiiiic** [comment]
@stohle please post your unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
No response
