### ISSUE TITLE
7plus A10 equipment always restart

### ISSUE THREAD

**Issue by xieao100** [pwn20wndstuff/Undecimus#1854]
**Describe the bug**
Mobile phone boot after a period of time, at the same time open multiple app phone will restart，Points to open more than 10 app at the same time, and then switch back and forth, during must restart。System log can't see the root cause, this bug has been exist, the reason I guess is out of memory，Checkra1n would not have this problem, hope can be repaired。

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iphone 7plus
 - unc0ver Version: 4.3.1

**Comment by Hamlock-Maneuver** [comment]
Try cocoatop version 2.2.  You should be able to see whats using all your memory.

**Comment by Hamlock-Maneuver** [comment]
Crash reporter 1.17.2   Use this as well.

**Comment by xieao100** [comment]
> Crash reporter 1.17.2 Use this as well.

Hi brother memory restart is in a flash, logs, and view the process cannot be captured

**Comment by Hamlock-Maneuver** [comment]
What did cocoatop tell you?

**Comment by xieao100** [comment]
> What did cocoatop tell you?

in cocoatop It's normal，But there is shut down

**Comment by Hamlock-Maneuver** [comment]
Ok in cocoatop.  set the columns to show by cpu usage.  Is there any process using %100?  How many processes are running?

**Comment by xieao100** [comment]
Are normal, no occupy 100% of the process

**Comment by Hamlock-Maneuver** [comment]
Ok. at this point the only thing I can say is to see what tweaks you are using.

**Comment by xieao100** [comment]
> Ok. at this point the only thing I can say is to see what tweaks you are using.

Brother, you are the author of the unCover？I found out the reason of the restart because too much open program, run out of memory。Have to solve？

**Comment by Cryptiiiic** [comment]
@xieao100 no he's not the author at all. please post your unc0ver diagnostics.

**Comment by xieao100** [comment]
Hello, I have switched the checkra1n tool, and now it runs stably for a week without restarting, no bugs. I extracted the logs from unCover for nearly a week, I don't know if I can tell the reason for the restart, thank you

**Comment by xieao100** [comment]
> @xieao100 no he's not the author at all. p
[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/4397019/diagnostics.plist.zip)
lease post your unc0ver diagnostics.
