### ISSUE TITLE
Lpm must force restart will not turn on 

### ISSUE THREAD

**Issue by stuie1** [pwn20wndstuff/Undecimus#1857]
**Describe the bug**
If I put lpm on either a tweak that turns it on or just simple no tweak enabled lpm I leave it on charge randomly maybe 30 mins later or listen to music the lock screen will not turn on but music is playing its low power mode it only happens with low power mode if I don’t use a tweak or enable lpm my jailbreak works after a jailbreak it’s done this for awhile but it takes about me 1 min after jailbreak to respring 

**To Reproduce**
1. Go to 'settings'
2. Click on 'enable lpm'
3. Scroll down to 'lock screen’
4. See error!!!

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 11
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
Have you had this restore from a previously jailbroken phone?  I would attempt a rootfs restore with a cydia cache reset.

**Comment by stuie1** [comment]
Ugh I don’t want to because I have things downloaded I would not get back sources not working anymore gosh can I just use SnapBack to orig fs and still have my snapbacks saved after I do a orig fs reset in SnapBack???? 

Stuart Bailey Jr

**Comment by stuie1** [comment]
I just don’t wanna have to install everything again I get that all my sources will be in cydia still but ugh ughhhhh try and like put a update that will fix my lpm that would just make me so happy I just dont wanna have to redownload everything I never done ssh before if u could help me drag drop my SnapBack file into my Mac computer so I don’t have to do all the work of downloading u would just make my life 100% easier and I would learn how to ssh!?!!!! Or if u know of a website with great instructions to ssh and where SnapBack files are that would be so nice of u! You are awesome!!!!!!!!!!!

Stuart Bailey Jr

**Comment by Hamlock-Maneuver** [comment]
Use a tweak called Flame.  It will allow you to see what tweaks you have and their sources. The point in doing this is to rebuild your system to what you had, 1 piece at a time so you can see where the problem occurred.

**Comment by Hamlock-Maneuver** [comment]
If you just copy then reload what you have.  You are not fixing anything.

**Comment by stuie1** [comment]
Flame when I install it does not have a Preference bundle it’s in the settings but it doesn’t come up with all the settings

Stuart Bailey Jr

**Comment by stuie1** [comment]
O tru I mean I just watched a video on how to save battery life I pretty much did everything low power mode does basically I don’t half the shit I have running I just wanna know why some tweak work and some don’t like I used to have auto lie in my iPhone x it worked but on this iPhone 11 I guess it doesn’t work unless rejailbreaking will kick start it...

Stuart Bailey Jr

**Comment by stuie1** [comment]
Idk what it is but I can get vpn to work unless it a certain vpn vpn unlimited I can’t use any other vpn

Stuart Bailey Jr

**Comment by stuie1** [comment]
One last question do u know why it’s like 16gs to make a ICloud back up 

Stuart Bailey Jr

**Comment by Hamlock-Maneuver** [comment]
hey bro.   flame does work.  in cydia, click installed tab.  you will see a folder near the top.  that's flame.  Your also able to load batch repos in the sources section.  you just don't get the preferences in settings.

**Comment by Hamlock-Maneuver** [comment]
If you really wanted to mess with flame's settings.  you could always just use filza and find the Property list file for flame (plist)

**Comment by stuie1** [comment]
O really damnnn 

Stuart Bailey Jr

**Comment by Cryptiiiic** [comment]
@stuie1 please post unc0ver diagnostics.

**Comment by stuie1** [comment]
I think I have the same problem my lpm does not work if I keep it on like on a charger or randomly will not turn on

Stuart Bailey Jr

**Comment by Cryptiiiic** [comment]
@stuie1 please post unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
No response
