### ISSUE TITLE
Uncover 4.3.1 Still a Failure iPhone 11 Pro Max

### ISSUE THREAD

**Issue by miguelr4720** [pwn20wndstuff/Undecimus#1861]
**Describe the bug**
Unc0ver Still Having Issues Please fix

**To Reproduce**
1. Go to Unc0ver App 4.3.1
2. View The Log 
3. Scroll down to log Unc0ver App
4. See error Cant End Background Task 0xb

**Screenshots**
![87010A1E-7D7B-4819-9316-F3611A984A83](https://user-images.githubusercontent.com/36649261/76460631-ba5ad700-63b4-11ea-8de2-1251c321ac9f.png)

**Device (please complete the following information):**
 - iOS Version: iOS 13.3
 - iOS Device: iPhone 11 Pro Max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by miguelr4720** [comment]
when is this issue going to be fixed is getting me frustrated

**Comment by Yone-beep** [comment]
Itt

**Comment by Cryptiiiic** [comment]
@miguelr4720 its an iOS UI error, just ignore it, it doesn't effect unc0ver at all.
