### ISSUE TITLE
Powerloghelperd still crashing on 4.3.1

### ISSUE THREAD

**Issue by windowsvista6009** [pwn20wndstuff/Undecimus#1862]
**Describe the bug**
Powerloghelperd is continuously crashing in the background. Used the choicy method but it did not work. Also tried with all tweaks disabled and it still crashes. All tweaks enabled also didn't make a difference. PowerloghelperdFIX did not help either. Did resprings/ldrestarts/reboots 100x before and after each attempt to fix. The problem also seems to be present in unjailbroken mode as the battery settings do not load even then. The problem started on 4.1.1 I believe and updating to 4.2.1 fixed it the one time. However it went right back to crashing. Downgraded to 4.1.1 but that didn't fix it. 
**To Reproduce**
1. Go to 'settings'
2. Click on 'battery'
3. Scroll down to 'info'
4. See error- powerloghelperd crashing in cocoatop.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: XS MAX
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [? ] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment]
@windowsvista6009 please post your unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
No response
