### ISSUE TITLE
While I’m in a jb state I connect my Bluetooth headphones, it restarts and puts me in a non jb state.

### ISSUE THREAD

**Issue by ihaveproblems** [pwn20wndstuff/Undecimus#1863]
After a couple hrs of being jail broken It crashes and unjailbreaks when I connect my Bluetooth headphones

**To Reproduce**
1. Don’t set headphones in pair mode
2. Only clime the connect button once
3. Don’t connect them via settings

**Screenshots**
If applicable

**Device (please complete the following information):**
 - iOS Version: iOS 13.2.3
 - iOS Device: iPad 6
 - unc0ver Version: v4.3.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://easyupload.io/fdjoyp

**Comment by Cryptiiiic** [comment]
@ihaveproblems please post you unc0ver diagnostics.

**Comment by ihaveproblems** [comment]
How do I do that?

**Comment by Cryptiiiic** [comment]
@ihaveproblems unc0ver app -> settings page -> scroll down -> share diagnostics.

**Comment by ihaveproblems** [comment]
How do I copy it over I’m on iOS btw

**Comment by ihaveproblems** [comment]
Got it. https://easyupload.io/fdjoyp

**Comment by ihaveproblems** [comment]
@Cryptiiiic Got it https://easyupload.io/fdjoyp

**Comment by Cryptiiiic** [comment]
**Unfortunately, to reduce issue spam/clutter, help is not provided for those who have pirate packages or repos.** I can in fact help you after you remove all your piracy. After removing all of it, please say if you still experience this bluetooth reboot. Closing this for now. I will reopen if you still have this issue after removing piracy.
