### ISSUE TITLE
I have a ipad pro 3th gen, ios 12.4.1, do you have any advice?

### ISSUE THREAD

**Issue by rootgo** [pwn20wndstuff/Undecimus#1864]
I have a ipad pro 3th gen
ios 12.4.1
I wanna jailbreak
Should I stay at ios 12.4.1 and wait for new version of unc0ver 
or update to ios 13.3.1 ??
Do you have any advice?
plz help me

**Comment by Hamlock-Maneuver** [comment]
Try unc0ver 4.0.3

**Comment by rootgo** [comment]
not working with unc0ver 4.0.3

**Comment by Hamlock-Maneuver** [comment]
12.4.1 support for A12 iPhones (iPads not supported at this time)

**Comment by rootgo** [comment]
> 12.4.1 support for A12 iPhones (iPads not supported at this time)

Will unc0ver support A12x with iOS 12.4.1 in the future ？

**Comment by lokimudhearth** [comment]
@rootgo there is always Checkra1n. 

And I wouldn’t trust anything @Hamlock-Maneuver says.

**Comment by Hamlock-Maneuver** [comment]
Yeah? checkrain doesn't work for A12x devices...

**Comment by Hamlock-Maneuver** [comment]
And you can listen to who ever you like.

**Comment by rootgo** [comment]
> @rootgo there is always Checkra1n.
> 
> And I wouldn’t trust anything @Hamlock-Maneuver says.
sadly,checkra1n  is not support A12x

**Comment by rootgo** [comment]
> Yeah? checkrain doesn't work for A12x devices...

you are right

**Comment by lokimudhearth** [comment]
@rootgo sorry, I misread your device. I would probably just update to 13.3.1, as pwn may have something in the pipeline.

**Comment by rootgo** [comment]
> @rootgo sorry, I misread your device. I would probably just update to 13.3.1, as pwn may have something in the pipeline.

thx for your advice

**Comment by kwetawi** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/1864#issue-579767783

**Comment by kwetawi** [comment]
d
