### ISSUE TITLE
can't jailbrek on my iphone se beacuse the Error: Unable to get debs for packages to repair

### ISSUE THREAD

**Issue by shihaoyan2018** [pwn20wndstuff/Undecimus#1866]
can't jailbrek on my iphone se beacuse the Error: Unable to get debs for packages to repair.
when i use the app jailbrek in step 18,it will break and have an error:
Error: Unable to get debs for packages to repair.
Undecimus version 4.3.1
ios version 13.2
ios device iphone se

**Comment by dinol1187** [comment]
Update your altserver on your computer and reinstall uncover. This is not an uncover issue

**Comment by shihaoyan2018** [comment]
Thank you，I jailbrek on my iphone sucessfully.
