### ISSUE TITLE
iPhone XS Max goes into safe mode when screen goes to sleep.

### ISSUE THREAD

**Issue by thecolbster91** [pwn20wndstuff/Undecimus#1867]
**Describe the bug**
Every time my device locks or goes to sleep for a while, and I unlock it, it wakes up to safe mode. It just started this yesterday. I tried uninstalling tweaks but that did not help. I don’t know what is causing it. Could it be a bug, or a bad repo or what?

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS Max
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
List your tweaks

**Comment by 2JayCee** [comment]
Disable all tweaks with iCleaner Pro. If that doesn't resolve your issue then it is a Jailbreak issue. Restore RootFS to fix your issue.

**Comment by Cryptiiiic** [comment]
closing this, you opened another issue #1893 which makes this issue irrelevant at this current time, will open once new issue is resolved.
