### ISSUE TITLE
Not working on iOS 12.4.4 on iPhone 6

### ISSUE THREAD

**Issue by shaikharfan7** [pwn20wndstuff/Undecimus#1868]
iPhone 6 iOS 12.4.4 currently unsupported.

**Comment by Hamlock-Maneuver** [comment]
use checkrain

**Comment by shaikharfan7** [comment]
> use checkrain

Unable to get into DFU because home botton is broken :/

**Comment by Hamlock-Maneuver** [comment]
There is a way to do it through command line.

**Comment by shaikharfan7** [comment]
Could you please let me know? I was not able to find it. I can only manage to put in recovery mode through command line.

**Comment by Hamlock-Maneuver** [comment]
there was an older program we were using to pull the noonce for A12 devices.  During the process it would throw the phone into dfu mode through command prompt.  For the life of me I just can't remember the name of the program.  There was also an older version used way back during the green poison jailbreak.

**Comment by shaikharfan7** [comment]
Thank you, will try to check it out.

**Comment by Cryptiiiic** [comment]
closing, conversation turned into not related to unc0ver.
