### ISSUE TITLE
Not working on iOS 12.4.5 on iPhone 6

### ISSUE THREAD

**Issue by Bellaposa** [pwn20wndstuff/Undecimus#1869]
Not working on iOS 12.4.5 on iPhone 6

**Comment by Hamlock-Maneuver** [comment]
Use checkrain

**Comment by 2JayCee** [comment]
Yeah, I have no idea why you're using unc0ver. Please use Checkra1n. This isn't even a bug.

**Comment by Bellaposa** [comment]
Staje calm pesccmman!

**Comment by Bellaposa** [comment]
Yes! Thanks!
