### ISSUE TITLE
Can't jailbreak, delete OTA issue.

### ISSUE THREAD

**Issue by FloncDev** [pwn20wndstuff/Undecimus#1870]
**Describe the bug**
Can't jailbreak. Keeps on saying "RootFS already mounted, delete OTA file from settings - Storage if present and reboot." I have checked my phone storage and there is no update present. When I click on software update I get an error and cant see the newest update so I can't install then uninstall.

**To Reproduce**
1. Download Jailbreak
2. Press Jailbreak
3. See the error message.

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Can't see logs, when I click show logs it crashes.

**Comment by Hamlock-Maneuver** [comment]
reboot and turn on unc0ver.  click the cog and ONLY change the switch "Disable updates". click jailbreak or whatever it may say.  Go through the process and see if you can see and even delete the IOS update.

**Comment by Cryptiiiic** [comment]
@DevFlock343 please follow the steps in this tweet: [https://twitter.com/Jakeashacks/status/1103747007745835011](https://twitter.com/Jakeashacks/status/1103747007745835011). This issue is most likely caused by iOS itself.
