### ISSUE TITLE
CPU jump to 400% , too much battery drain + the solution ( iPhone 11 Pro Max 13.3)

### ISSUE THREAD

**Issue by BL4CKR4Y** [pwn20wndstuff/Undecimus#1871]
Lately noticed that my battery drains too much , when i checked the processes i saw that the CPU usage was always around 300 to 400% checked and found that it was caused by Accountsd, Securityd and Cloudd, tried eveything even disabled all the Tweaks but with no luck , signed out of icloud and the CPU came back to normal but when i signed in again the CPU jumped back to high usage, the only solution was “LDrestart” after using it everything went back to normal, so it means that its caused by ur new userspace reboot technique, hope u fix it soon
![8F94C74A-BDDD-45D3-9D55-B88659B82C87](https://user-images.githubusercontent.com/36887162/76834795-d50ecf00-683e-11ea-9725-8a44ac56b467.png)

**Comment by 2JayCee** [comment]
Have you considered Restore RootFS as an option to remedy your issue?

**Comment by BL4CKR4Y** [comment]
As i said when u LDrestart after the jailbreak it fixes it until u reboot and rejailbreak

**Comment by Hamlock-Maneuver** [comment]
What version of unc0ver are you on?

**Comment by BL4CKR4Y** [comment]
4.3.1 , now even LDrestart doesnt help ,i even restored rootFS
![6FDD539A-345D-4366-995F-B1CDD0A9553C](https://user-images.githubusercontent.com/36887162/77065647-c23cfb80-69f2-11ea-8d2e-64b7f3436503.png)

**Comment by Hamlock-Maneuver** [comment]
list your tweaks
You can use Flame to get the list.

**Comment by Cryptiiiic** [comment]
@blackray88 make sure you are using unc0ver v4.3.1. Please post your unc0ver diagnostics.

**Comment by Hamlock-Maneuver** [comment]
He has already stated that he is using 4.3.1
You need to list your tweaks before we can go from here.

**Comment by Cryptiiiic** [comment]
@Hamlock-Maneuver this reply is redundant. I said everything that needs to be done.

**Comment by Cryptiiiic** [comment]
No response
