### ISSUE TITLE
IPHONE XS FACEID AND 3D TOUCH BUG

### ISSUE THREAD

**Issue by caccavo** [pwn20wndstuff/Undecimus#1872]
Goodmorning, im sorry to disturb you, but i want to tell you there is a buh on faceid on iphone xs ios 12.4. The iphone sometimes puts in unlocked state and remains unlocked till i respring. Same happenss on 3d touch in notification center to respond to someone or just to open that. This kind of freeze its like for a minute then the iphone remains like nothing was happened. If respring, it backs working. Hope you will fix this, thanks for your working and for reading this!

**Comment by Hamlock-Maneuver** [comment]
You may want to use an older version of unc0ver.  Try 4.0.3 and see if this still happens.  If you are unclear how to do this easily, just say so and I will try to explain.

**Comment by caccavo** [comment]
Even the old unc0v3r version does to me the same bug, i couldn’t not text you before because i were busy at work. These problems shows up after the update 3.7.0.b3 wich this version was stable for me. Hope you may find a way to fix it, thanks for reply! ill wait for anorher response! Ps. The new version 4.3.1 has less battery drain and fast in everything, my only problem are these 2 things, for the rest, everything is fine!

**Comment by Cryptiiiic** [comment]
@caccavo please post unc0ver diagnostics.

**Comment by Hamlock-Maneuver** [comment]
You should have better luck with unc0ver 3.8.0 or 4.0.3.   4.2.1 and up are mainly for ios 13

**Comment by caccavo** [comment]
This one?

**Comment by caccavo** [comment]
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/4398982/diagnostics.zip)
This one? I’ve been forced to put into a zip cause the file couldnt been attached alone and filza doesnt allow me to copy and paste his contenent

**Comment by Cryptiiiic** [comment]
**Unfortunately, to reduce issue spam/clutter, help is not provided for those who have pirate packages or repos.** I can in fact help you after you remove all your piracy. After removing all of it, please say if you still experience this Face ID/Touch ID bug. Closing this for now. I will reopen if you still have this issue after removing piracy.
