### ISSUE TITLE
iPhone Xs Max iOS 13.3 with Unc0ver4.3.1 BUG

### ISSUE THREAD

**Issue by JAMJAMJ-A-M** [pwn20wndstuff/Undecimus#1874]
I encountered a problem, when I was running some applications, I couldn't select photos, it would crash.  I disabled all tweak using icleaner pro and it didn't solve the problem.
It's not the album application that crashes, but the photos selected in other applications will crash, such as Microsoft Translator and papago.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by JAMJAMJ-A-M** [comment]
![7199849B-DCEA-46C6-853D-766004ADE818](https://user-images.githubusercontent.com/21018730/76974374-13ee7300-696c-11ea-9e5b-6a734028e919.gif)

**Comment by Hamlock-Maneuver** [comment]
Ok, first try this.  When you want to bypass your tweaks.  Don't use another tweak to do it.  You already have all the tools you need to do it correctly.  Open inc0ver and click the little gear. At the top of the list you will see "Load Tweaks" and "Load Daemons".  Uncheck both of them.  Click done, then power off your phone, Or do a hard restart. Open unc0ver and click the jailbreak. See if you still have the issue. Come back and report results.

**Comment by JAMJAMJ-A-M** [comment]
To be honest, I have tried many methods, but nothing has changed, I even restored the rootfs twice. But I finally found the cause. After I changed the libcolorpicker-nepeta library to libcolorpicker, the problem didn't seem to reproduce.

**Comment by JAMJAMJ-A-M** [comment]
Thank you for your development work.

**Comment by Cryptiiiic** [comment]
@z306334796 please post unc0ver diagnostics.

**Comment by Hamlock-Maneuver** [comment]
He has already fixed the problem. 

 "After I changed the libcolorpicker-nepeta library to libcolorpicker, the problem didn't seem to reproduce."

**Comment by Cryptiiiic** [comment]
@Hamlock-Maneuver I don't remember asking for you opinion. 
![asked](https://user-images.githubusercontent.com/27748705/77810014-8ab3fc00-704f-11ea-8f09-1d0a72642886.gif)

**Comment by TherealNicholas** [comment]
lol
