### ISSUE TITLE
iPhone XS Max 13.3 text message alerts not working.

### ISSUE THREAD

**Issue by thecolbster91** [pwn20wndstuff/Undecimus#1875]
**Describe the bug**
When I get a SMS message or iMessage, my iPhone will not ring or make a sound. In order for me to see it, I have to go into my messages and read it manually. Is there a bad tweak?

Here are all my tweaks

A-Font: 1.7.1
AppList: 1.5.15~beta1
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Axon: 1.0
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
BioProtect XS (iOS 12/13): 4.4-2
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCSupport: 1.2.2
CleanHomeScreen: 1.0.4
ClearDock12: 1.0.0
ColorBanners 3: 1.0.1
ColorBoard: 0.0.4
ColorFlow 5 (iOS 13): 1.0.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b24
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
debugserver-10: 10.0.0~svn-20191106+dcaf932-1
debugserver: 10-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DubDub: 1.6
file: 5.35-2
Find Utilities: 4.6.0-2
Flame: 1.3
FloatingDockPlus13: 1.1.6
Frame: 2.0.0-beta2
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HomePlus Beta: 0.4.9-beta
HS.Ryu_006 Fluid Widget: 1.0.8
iOS Firmware: 13.3
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b27
jbctl: 0.2.3-1
Jellyfish: 1.3.3
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libclang-cpp10: 10.0.0~svn-20191106+dcaf932-1
libcolorpicker: 1.6.7
libidn2: 6.1.2-1
libllvm10: 10.0.0~svn-20191106+dcaf932-1
libplist: 2.0.0-2
libSparkAppList: 1.0.7
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NewCam: 0.0.1
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PianoPass: 2.0.0
PreferenceLoader: 2.2.4
PrefixUI: 1.2.6
Profile Directory: 0-1
Prysm: 1.4.1
readline: 8.0-1
Rocket for Instagram: 3.6.11
RocketBootstrap: 1.0.7~beta3
rsync: 3.1.3-2
sed: 4.5-1
shell-cmds: 118-8
SnowBoard: 1.2.87~Beta2
Springtomize 5: 5.0.9
Substitute Support Package: 0.1~b3
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.7
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TetherMe for iOS 8+: 2.0
Trust Cache Injector: 0.4~b5
Twisted: 1.1
UIKit Tools: 1.1.15-2
Whoops: 1.1.0
Xen HTML: 1.1.4~release
XenInfo: 2.2.9
XZ Utils: 5.2.4-4
Yumru: 1.1
Zebra: 1.0.7

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS Max
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
Have you tried 4.3.1?

**Comment by thecolbster91** [comment]
@Hamlock-Maneuver  Yes I've downloaded 4.3.1 but 4.3.1 will not work for my phone. It won't let me jailbreak my device.
