### ISSUE TITLE
Unresponsive Device on 4.3.1 (iPhone XS MAX 12.4)

### ISSUE THREAD

**Issue by danny137** [pwn20wndstuff/Undecimus#1876]
Upon updating from 4.2.1 to 4.3.1, my entire device would lock up and physical buttons would be unresponsive. Plugging it in to my Macbook would release it and I could then try and recreate the error which I did successfully.

After typing a few letters on the keyboard, trying to copy, cut, or paste, or open an app, that was not a system app, the issue would occur. System apps seemed to be slower than usual but not unresponsive.

Downgrading to 4.2.1 fixed the issue.

**Comment by Hamlock-Maneuver** [comment]
You may want to go down as far as 4.0.3.
 4.2.1-4.3.1 are mostly meant for IOS 13.

**Comment by Cryptiiiic** [comment]
@danny137 please post your unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
No response
