### ISSUE TITLE
Can’t use Cydia after Substrate 7010 update

### ISSUE THREAD

**Issue by BIOHazard877** [pwn20wndstuff/Undecimus#188]
iPhone X iOS 11.3.1 unc0ver 2.1.0

I updated to Substrate 7010 earlier today and got in a respring loop while only having 1 tweak (and two apps —Reprovision and Filza) installed. I rebooted and stayed in stock state until a few moments ago when I rejailbroke with Substrate disabled (volume up) and attempted to update to Substrate 7011 when I’m now getting errors such as 

If I try to update Substrate I get:
“Sub-process /usr/libexec/cydia/cydo returned an error code (255)” 

If I try to remove Substrate (or any tweak) I get:

“Sub-process dpkg —set-selections returned an error code (255).
Couldn’t record the approved state changes as dpkg selection states”

Help please? Thanks. 

FIXED: by disabling "Reload system daemons", rejailbreaking and then updating to 7011.

**Comment by iM4CH3T3** [comment]
Update to 0.9.7011
