### ISSUE TITLE
13.3 11 pro max message app malfunction 

### ISSUE THREAD

**Issue by arttyyy** [pwn20wndstuff/Undecimus#1880]
I’m having problems with my messaging app.
Before it was not getting notified and now it works with the NewTerm command.

having issues with pictures not previewing which isn’t that bad  and now past couple days when I send messages it gives me a send error and have to send it 2-3 times before it sends. 

Anyone else having this issue??

Please help quite annoyin.

**Comment by Hamlock-Maneuver** [comment]
What unc0ver version do you have?

**Comment by arttyyy** [comment]
> What unc0ver version do you have?

Currently 4.3.1

**Comment by kevinjohncutler** [comment]
Same here on 13.3 iPad Pro.

**Comment by Hamlock-Maneuver** [comment]
try an older version.   4.0.3

**Comment by Cryptiiiic** [comment]
@arttyyy please post your unc0ver diagnostics.

@Hamlock-Maneuver it's a general bad practice to recommend using an older version of a product as a solution. I don't suggest you do it.

**Comment by Hamlock-Maneuver** [comment]
I do recommend what works for people.  Nothing more.

**Comment by Cryptiiiic** [comment]
No Response
