### ISSUE TITLE
iPhone 7 13.3.1 Unc0ver Unsupported using Zjailbreak

### ISSUE THREAD

**Issue by 420hackS** [pwn20wndstuff/Undecimus#1892]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
I do not have computer access so I’m trying to use Unc0ver to jailbreak my iPhone 7 on 13.3.1. I downloaded it using Zjailbreak which has been highly recommended to me. Just wondering how everyone has been so successful with this method and my app still says unsupported even after I uninstall and reinstall. I will add the fact that this device has never been Jailbroken. Not sure if that makes a difference. Thanks for any help.
**To Reproduce**

**Screenshots**
![BDE280BF-E770-4508-A481-9D0FCF2F96C0](https://user-images.githubusercontent.com/62512574/77254015-4b8b4280-6c2c-11ea-91d0-d40b1960067a.png)

**Device (please complete the following information):**
 - iOS Version: 13.3.1
 - iOS Device: iPhone 7
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X}this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
You need to use checkrain.

**Comment by neso92** [comment]
Your issue is that you are running 13.3.1
Current unc0ver only supports up to 13.3

**Comment by Cryptiiiic** [comment]
@420hackS as of unc0ver v4.3.1, which is the latest version of unc0ver, it does not yet support later than 13.3. **13.3.1 to 13.4 are NOT supported at all.** There is a chance 13.3.1 will be support soon so **DO NOT update to 13.4** if you want to use unc0ver in the near future. For now you can use checkra1n if you are really that desperate to need to jailbreak. Additionally, ZJailbreak is a fake jailbreak site, don't use it.
