### ISSUE TITLE
iPhone XS Max 13.3 Unc0ver 4.3.1 will not re-jailbreak my device, freezes at Apple Logo.

### ISSUE THREAD

**Issue by thecolbster91** [pwn20wndstuff/Undecimus#1893]
**Describe the bug**
I have another issue. My iPhone XS Max will not jailbreak with 4.3.1. It will only jailbreak with 4.2.1. When I try to jailbreak with 4.3.1, it always goes to the Apple logo and it will stay there until I force reset it. Why is that??

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XS Max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by thecolbster91** [comment]
I have another issue. My iPhone XS Max will not jailbreak with 4.3.1. It will only jailbreak with 4.2.1. When I try to jailbreak with 4.3.1, it always goes to the Apple logo and it will stay there until I force reset it. Why is that??

**Comment by Hamlock-Maneuver** [comment]
Did this happen after installing tweaks?

**Comment by Hamlock-Maneuver** [comment]
Try this. Go back to 4.3.1.  When you open unc0ver click the gear and disable "load tweaks" and "Load daemons".  now click jailbreak and see if it works.

**Comment by thecolbster91** [comment]
Yes it did. It un-jailbroke last night and it came back to stock.

**Comment by Hamlock-Maneuver** [comment]
It jailbreaks with tweaks and daemons disabled?

**Comment by Cryptiiiic** [comment]
@thecolbster91 I see you checked the rootfs box.
![image](https://user-images.githubusercontent.com/27748705/77740008-c3ac8c00-6fcf-11ea-9ec2-3e83b6ad54c3.png)
Is it actually still present after rootfs restore or did you check this box by mistake?

**Comment by thecolbster91** [comment]
@Cryptiiiic Yea it works after a restore. So I must have accidentally checked it.

@Hamlock-Maneuver and No I have to always restart my jailbreak from scratch whenever my phone resets itself.

**Comment by Cryptiiiic** [comment]
Bad tweak not unc0ver's fault.
