### ISSUE TITLE
Random reboots

### ISSUE THREAD

**Issue by moondark864** [pwn20wndstuff/Undecimus#1897]
Even on Unc0ver version 4.3.1 which was suppose to fix random reboots. I still get random reboots after 3 hours.

 - iOS Version: 13.3
 - iOS Device: IPad 7
 - unc0ver Version: 4.3.1

 - [] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

**Comment by JesseB0rn** [comment]
Same here, random reboots. On iPhone SE here tho.

**Comment by Hamlock-Maneuver** [comment]
Another person with the same issue said he was using jailbreak bypass tweaks.  Once he disabled those, his phone ran fine with no problems.

**Comment by Cryptiiiic** [comment]
@moondark864 @JesseB0rn please post your unc0ver diagnostics.

**Comment by JesseB0rn** [comment]
For me it happens either on the Lockscreen, when entering safari or when entering into snapchat from a notification. I have cleaned the diagnostics and now I'm waiting for a crash.

**Comment by moondark864** [comment]
I stopped getting reboots after removing liberty lite tweak.

**Comment by moondark864** [comment]
I thought I fixed it but I didn’t. It also happens to me when entering safari.

**Comment by Cryptiiiic** [comment]
@moondark864 please post your unc0ver diagnostics.

**Comment by moondark864** [comment]
(https://github.com/pwn20wndstuff/Undecimus/files/4396511/diagnostics.1.txt)

**Comment by Cryptiiiic** [comment]
Remove the following packages due to piracy:

> Anti-Revoke 2
> Kiiimo Repo Icons
> LocalIAPStore
> HYI Repo Icons
> CyDown
> SCloudlife

and  remove these for incompatibility:
> PullToRespring
> Sileo Compatibility Layer
> Appcd Medium

remove these repos:
> cydia.iphonecake.com
> cydia.kiiimo.org
> repo.hackyouriphone.org

@moondark864 Report back if you still have random reboots after removing the packages I said.

**Comment by Un4givenPG** [comment]
Sadly I have to report the same issue while not using pirate repos.
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/4397155/diagnostics.txt)

**Comment by leandroprz** [comment]
I'm also experiencing random reboots on a 6S, iOS 13.3.
I just had a reboot when taking a picture with the stock Camera app.

[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/4397896/diagnostics.txt)

**Comment by Cryptiiiic** [comment]
@Un4givenPG That diagnostic is useless to me. Please make sure you are in a jailbroken state before pressing share.

**Comment by Cryptiiiic** [comment]
@leandroprz Try disabling tweaks 1 by 1 using choicy. If all tweaks are disabled and you still panic then its most likely unc0ver's fault. But for now its unknown if this is the case.

**Comment by moondark864** [comment]
I got it again even when I disabled tweaks.

**Comment by Cryptiiiic** [comment]
@moondark864 did you in fact **uninstall** the packages and repos I states?

**Comment by moondark864** [comment]
No I just disabled tweaks in the unc0ver app than rejailbroken. I will uninstall the tweaks that you said.

**Comment by dinol1187** [comment]
I have also noticed random reboots on my IPhone XR 13.3

**Comment by Cryptiiiic** [comment]
@dinol1187 can you please not make a comment without posting usable data? please post your diagnostics like everyone else. How can I even help with "XY phone random reboots on Z iOS"?

**Comment by Cryptiiiic** [comment]
@moondark864 @JesseB0rn @Un4givenPG @dinol1187 please post all panic-base, reset-counter, and panic-full crash logs.

**Comment by moondark864** [comment]
[panic-full-2020-03-27-160258.955.txt](https://github.com/pwn20wndstuff/Undecimus/files/4398091/panic-full-2020-03-27-160258.955.txt)
[ResetCounter-2020-03-27-160257.txt](https://github.com/pwn20wndstuff/Undecimus/files/4398093/ResetCounter-2020-03-27-160257.txt)
I don’t have panic base

**Comment by Cryptiiiic** [comment]
Duplicate of #1847

**Comment by Un4givenPG** [comment]
So I had so many, that I had to zip them.
[panic.zip](https://github.com/pwn20wndstuff/Undecimus/files/4398121/panic.zip)

**Comment by Cryptiiiic** [comment]
Duplicate of #1890

**Comment by Un4givenPG** [comment]
Idk, if it helps but while browsing the crash logs I found out that every time I experience a random reboot a “jetsam event” log is created. I’m uploading the most recent here, because there are to many to upload them all.
https://drive.google.com/file/d/1GFYJDALySltv9myr9PcSYRz_EE-tgnv2/view?usp=drivesdk

**Comment by Cryptiiiic** [comment]
Closing due to duplicate, all info has been received.
