### ISSUE TITLE
Camera app resprings my device whenever it gets opened  iphone xs max ios 13.3 uc 4.3.1

### ISSUE THREAD

**Issue by qwertypoiuy1234** [pwn20wndstuff/Undecimus#1898]
**Describe the bug**
Whenever I open the camera app it resprings my device. I tried to disable all tweaks but nothing worked 

**To Reproduce**
Steps to reproduce the behavior 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iphone xs max 
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
please list your tweaks.  You can get a list from using the tweak Flame. When installed, go to the "installed" tab in cydia.  You will see a folder at the top left. That's flame.

**Comment by Cryptiiiic** [comment]
@qwertypoiuy1234 please share unc0ver diagnostics. Also install crashreporter from [https://revulate.dev/](https://revulate.dev/) repo and share your SpringBoard and backboardd crashlogs.

**Comment by Cryptiiiic** [comment]
No Response
