### ISSUE TITLE
iPhone X 11.3.1 can't jailbreak

### ISSUE THREAD

**Issue by TheAndreGomes** [pwn20wndstuff/Undecimus#190]
Im using the latest beta version of unc0ver and when the iPhone gets to the 37/38 then it freezes on a loop and come to normal (no jailbreak)

**Comment by BiasShadow** [comment]
Im using the version that was just released and its not really jailbreaking. Says jailbroken, but I never went into a post JB success respring. And Cydia keeps crashing

**Comment by Cryptiiiic** [comment]
@TheAndreGomes Make sure you are using 2.1.0 latest release. Also post your diagnostics, without it we can't help you. @BiasShadow Same for you, use latest and post diagnostics.

**Comment by TheAndreGomes** [comment]
@Cryptiiiic Sorry for not answering, busy week. Thank you for your response, unfortunately i've tried Rollectra and the iPhone didn't surpass the quick start screen. Updated to ios 12 😔
