### ISSUE TITLE
"Unable to verify newly mounted RootFS" on unc0ver v4.3.1 iPhone 11 Pro

### ISSUE THREAD

**Issue by bigfrog** [pwn20wndstuff/Undecimus#1904]
I've been trying to jailbrake this device with 13.3 but the first time I tried never saved the snapshot but says that an over the air update to be deleted but I don't have any update pending or downloaded in iPhone storage.. when keep trying then it start doing the process but give me the error that says Unable to verify newly mounted RootFS and others that I will posted pics so maybe someone can help me fix and be able to complete the process... after error if I click Preview it show jailbroken but nothing works....

![72304FB7-64A3-4BF6-BE70-E6AE5B4428EB_1_105_c](https://user-images.githubusercontent.com/166387/77832316-89e0a000-710b-11ea-8c44-05a2c398b123.jpeg)

**Comment by Cryptiiiic** [comment]
@bigfrog please post unc0ver diagnostics.

**Comment by bigfrog** [comment]
On Mar 28, 2020, at 7:40 PM, Liam(Cryptic) <notifications@github.com<mailto:notifications@github.com>> wrote:



@bigfrog<https://github.com/bigfrog> please post unc0ver diagnostics.

**Comment by bigfrog** [comment]
I send it to you via email because when I get the report it comes out to be a .plist and when trying to post it here it does not allow me says the file type not supported...

**Comment by bigfrog** [comment]
diagnostics.plist

**Comment by Cryptiiiic** [comment]
@bigfrog rename it to txt

**Comment by rcelus** [comment]
I would try restoring the iPhone through settings...
1) back up 
2) restore 
3) rejailbreak 
4) install all your tweaks
5) restore from back up... hope this helps!

**Comment by bigfrog** [comment]
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/4400010/diagnostics.txt)

**Comment by Hamlock-Maneuver** [comment]
Have you tried using the "restore rootfs" in uncover?

**Comment by Hamlock-Maneuver** [comment]
That should reset it and allow you to take another system snapshot.

**Comment by bigfrog** [comment]
every time I try to restore rootFS it crash , like right now I did it and crashed the iPhone /reboot

**Comment by Cryptiiiic** [comment]
I've seen this issue before, purgeUpdates is missing. Can you delete unc0ver app data from iPhone Storage or just delete unc0ver and install it back? @bigfrog

**Comment by bigfrog** [comment]
let me try

**Comment by bigfrog** [comment]
![IMG_1975](https://user-images.githubusercontent.com/166387/77863578-714ab580-71f1-11ea-8731-2514aacc265f.png)

![IMG_1976](https://user-images.githubusercontent.com/166387/77863588-7d367780-71f1-11ea-9891-6263f3e0a196.png)

**Comment by bigfrog** [comment]
that's what I get after

**Comment by Hamlock-Maneuver** [comment]
delete uncover and try redownloading a fresh version of 4.2.1. try rootfs restore once more.

**Comment by Hamlock-Maneuver** [comment]
If the rootfs restore works.  Jailbreak with version 4.3.1.

**Comment by Hamlock-Maneuver** [comment]
Regardless of what you do.  Redownload fresh copies of unc0ver.

**Comment by bigfrog** [comment]
let me try that now... thanks

**Comment by bigfrog** [comment]
now this

**Comment by bigfrog** [comment]
![IMG_1977](https://user-images.githubusercontent.com/166387/77864312-d0122e00-71f5-11ea-9cbc-7ad14d759469.png)

**Comment by bigfrog** [comment]
and then when I reboot is the same as before .. this is driving me crazy....

**Comment by Hamlock-Maneuver** [comment]
are you on a ios beta?

**Comment by bigfrog** [comment]
no is IOS 13.3 iPhone 11 Pro

**Comment by Hamlock-Maneuver** [comment]
Just to be sure.  You dont have an OTA update in file storage pending do you?

**Comment by bigfrog** [comment]
the funny this is that if I click the view log after the error it says jailbroken with some details but no respring

**Comment by bigfrog** [comment]
no I looked everywhere in settings iPhone/storage and nothing there

**Comment by bigfrog** [comment]
![IMG_8C55D9FD4914-1](https://user-images.githubusercontent.com/166387/77864558-45cac980-71f7-11ea-9d82-25bac93bf2f2.jpeg)

**Comment by bigfrog** [comment]
look this is what it says after errors

**Comment by bigfrog** [comment]
never has passed over 10 out of 29

**Comment by Hamlock-Maneuver** [comment]
That is definitely weird.

**Comment by Hamlock-Maneuver** [comment]
Ok can you open the gear in unc0ver and show us what you have selected?

**Comment by bigfrog** [comment]
my last thing will be  , reset it to factory on setting with out updating to 13.4 and try again because the rootFS is not working and I really don't know what to do.. I wrote to @pwn20wnd but you know he never answer ..

**Comment by bigfrog** [comment]
![IMG_1978](https://user-images.githubusercontent.com/166387/77864925-888da100-71f9-11ea-950c-c6259bed4831.png)
![IMG_1979](https://user-images.githubusercontent.com/166387/77864938-96432680-71f9-11ea-88f4-ab5939c1aee8.png)

**Comment by Hamlock-Maneuver** [comment]
Ok not sure if it matters.  But you don't have an ECID

**Comment by bigfrog** [comment]
The ECID I don't think is the problem because on my iPhone XS which is jailbroken it doesn't show either... don't know why

**Comment by Hamlock-Maneuver** [comment]
When you plug your phone into itunes and keep clicking the serial number and it changes to ecid.  Is it blank?

**Comment by bigfrog** [comment]
is not empty it shows the numbers

**Comment by Hamlock-Maneuver** [comment]
ok just making sure as this would be a hardware error.

**Comment by bigfrog** [comment]
I just going to wait for the next unc0ver update and see if I can do the whole process because right now I don't see other way.. I really appreciate all your help I will leave the issue open and see maybe someone with the same problem shows up...thanks again

**Comment by Cryptiiiic** [comment]
@bigfrog is this your first time jailbreaking this device or was it jailbroken before and you just rootfs restored?

**Comment by Cryptiiiic** [comment]
[#1675-586730609](https://github.com/pwn20wndstuff/Undecimus/issues/1675#issuecomment-586730609) Interesting

**Comment by thpryrchn** [comment]
I had the same problem on my iPhone 11. It stemed from me just activating the phone when I first got it to see what software version was on it, then restoring my backup without doing a reset all content and settings from my old phone. There was a partial update downloaded.

You need to backup your phone on your computer, then you need to reset and erase all settings. If you are like me, and the erase all settings and content doesn't do anything, I found that I had to buy https://www.imyfone.com/ios-data-erase/iphone-wont-erase-all-content-and-settings-solved/ to wipe it, then after I activated it, I erased all content and settings, then I installed unc0ver, and had to turn off "Disable Updates". After that, the phone restarted, and started downloading an update. Once the update finished downloading, I was able to remove it in the Settings-> General->iPhone Storage. Once that was removed, I was then able to jailbrake successfully with unc0ver. Then I restored rootfs, then did erase all settings and content. then restored my phone, and then installed uncover, and it worked again!

**Comment by bigfrog** [comment]
> [#1675-586730609](https://github.com/pwn20wndstuff/Undecimus/issues/1675#issuecomment-586730609) Interesting

It is the first time, thats why is so weird that doesn’t work...like I said before, when I run the unc0ver it started the process never show the snapshot but says something about over the update, I looked for the update is not there on settings, then the process always stops at 10% with different errors like the ones I showed you guys, don’t know what else to do...

**Comment by thpryrchn** [comment]
@bigfrog Try doing what I did, you most likely have a partial download of a software update, that isn't showing up in the General->iPhone Storage, like mine didn't.. I had the same problem and I fixed it by doing above.
If you can erase all settings and content without having to purchase a program, then you are in better shape than I was :)

**Comment by bigfrog** [comment]
> @bigfrog Try doing what I did, you most likely have a partial download of a software update, that isn't showing up in the General->iPhone Storage, like mine didn't.. I had the same problem and I fixed it by doing above.
> 
> If you can erase all settings and content without having to purchase a program, then you are in better shape than I was :)

I’m at work now but definitely I will follow your guide when I get home.. thanks for your time and help...👍

**Comment by bigfrog** [comment]
> @bigfrog Try doing what I did, you most likely have a partial download of a software update, that isn't showing up in the General->iPhone Storage, like mine didn't.. I had the same problem and I fixed it by doing above.
> If you can erase all settings and content without having to purchase a program, then you are in better shape than I was :)

Im confused, when you say to buy imyfone what  or which will be the option in that program to use ? I see Erase All Data-Erase Deleted files or what I don't know which one to choose .. and also after that it will left the iPhone on 13.3 ?
please let me know what is that you did... thanks

**Comment by bigfrog** [comment]
finally ..... What happened is that an update was somewhere on the iPhone .. what I did was I run unc0ver with the disable update off , restarted the iPhone then start the software update on setting on the iPhone after the 13.4 update downloaded complete and the phone was preparing the update I turn the iPhone off then when restart the update was present in settings and I was able to deleted it then able to jailbrake.. thank you guys for all your help....

**Comment by lildebz** [comment]
I am literally having the exact same problem. I’m going to try what you did

**Comment by thpryrchn** [comment]
I’m glad I was able to help :)

I wish that unc0ver had an option in it to remove any OTA updates it sees, as sometimes it won’t show that there is one downloaded if it is a partial download, and it is hard to get it removed. 
I’m just glad I figured it out, or I would be  Jealous Of my wife, as I was able to jailbreak her iPhone, then ran into this crap on mine.

**Comment by Cryptiiiic** [comment]
[https://twitter.com/Jakeashacks/status/1103747007745835011](https://twitter.com/Jakeashacks/status/1103747007745835011) @bigfrog @thpryrchn @lildebz

**Comment by bigfrog** [comment]
> I am literally having the exact same problem. I’m going to try what you did

just make sure that after the 13.4 is completely downloaded and the phone says is preparing software , make a quick re-start the iPhone -volume up and power to turn it off then you will look for the download on settings - iPhone storage and delete it then run onc0ver... good lucks...

**Comment by SofaK8ng** [comment]
TYSM!! I was stuck in that loop for a whole month 😂

**Comment by thpryrchn** [comment]
Even those the issue was resolved, the feature of having unc0ver be able to remove OTA updates would help!!!

**Comment by Cryptiiiic** [comment]
That literally exists, purgeUpdates is just broken on some devices. Pwn is fixing it. @thpryrchn
