### ISSUE TITLE
Can’t jailbreak iPhone XR(ios 13.3.1) showing unsupported 

### ISSUE THREAD

**Issue by a7raj** [pwn20wndstuff/Undecimus#1908]
![783431AA-3C70-4243-A4E2-237E3D4252EF](https://user-images.githubusercontent.com/37625203/77932312-2dc67900-72cf-11ea-9eb6-b27fdc8832dc.png)

**Comment by Hamlock-Maneuver** [comment]
13.3.1 on XR is currently not supported.

**Comment by a7raj** [comment]
> 13.3.1 on XR is currently not supported.

owh. thanks
