### ISSUE TITLE
Mobilesubstrate or Substitute?

### ISSUE THREAD

**Issue by ouraigua-zz** [pwn20wndstuff/Undecimus#1909]
One of my tweaks which relies on mobilesubstrate works fine in most devices jailbroken using unc0ver, but noticed in others it fails. It turns out that in these devices unc0ver is using **susbstitute** instead of **mobilesubstrate**.

I'm wondering how come some when jailbreaking some devices use mobilesubstrate while others susbstitute. Is there a raison for this?

Many thanks for your help with this matter.
Regards

**Comment by Cryptiiiic** [comment]
@ouraigua mobilesubstrate only supports iOS 11 on unc0ver. Susbstitute is used for iOS 12 and later.
