### ISSUE TITLE
11.1.2 iPad Air - No tweaks with Substrate

### ISSUE THREAD

**Issue by 0000vt** [pwn20wndstuff/Undecimus#192]

**Comment by 0000vt** [comment]
On my iPad air, running 11.1.2, no tweaks are working when upgrading to (the latest) Substrate. The first substrate update for unc0ver was also not working for me, so I switched back to Substitute.
Substitute is working fine regarding tweaks, however, I'm some freezes once in a while. Therefore, I'd like to upgrade to Substrate.
I tried a rootfs restore, tried rebooting and rejailbreaking.

**Comment by 0000vt** [comment]
After futurerestoring the iPad to 11.3.1, the problems were resolved. So, for anyone having the same problems, try upgrading to 11.3.1.
Otherwise, I would like to ask the developers to look into substrate compatibility issues on 11.1.2.

**Comment by Cryptiiiic** [comment]
Seems resolved.
