### ISSUE TITLE
Face ID breaks with UO 4.3.1.

### ISSUE THREAD

**Issue by sumssa** [pwn20wndstuff/Undecimus#1920]
Only solution was cleaning the lense and clipping pff and on the cable of camera unit.  All went fine with Facw ID. But with rejaillbreaking the device. Addiotionally selfie Portrait mode is broken. And its reproducebal. Seems affecting many people. 

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13..3
 - iOS Device: X
 - unc0ver Version: 4.3.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment]
@sumssa does this happen when you are stock, not jailbroken.

**Comment by Cryptiiiic** [comment]
No response
