### ISSUE TITLE
Can't Use Share Menu (While Jailbroken or not)

### ISSUE THREAD

**Issue by m3rtngs** [pwn20wndstuff/Undecimus#1924]
**Describe the bug**
So, my device ended up rebooting and I had to resign it using Altstore. So I press the share button on the unc0ver.ipa and instead of showing me the share menu, my screen becomes extremely laggy and doesn't show me any options.

**To Reproduce**
1. Go to Safari downloads
2. Click on unc0ver.ipa
3. Click on share button
4. No share options visible.

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Comment by Hamlock-Maneuver** [comment]
It's unfortunate that you burned your bridge between us.  Such an easy one to fix too.

**Comment by m3rtngs** [comment]
Fixed!
