### ISSUE TITLE
Unsupported on iPhone 5S also machine name detected as iPhone 6, 1

### ISSUE THREAD

**Issue by aysien** [pwn20wndstuff/Undecimus#1925]
**Describe the bug**
Unsupported on iPhone 5S also machine name detected as iPhone 6, 1

**To Reproduce**

**Screenshots**
![IMG-1975](https://user-images.githubusercontent.com/31809167/78617065-167c2280-78b1-11ea-9fd8-07c3a8be21c0.JPG)

**Device (please complete the following information):**
 - iOS Version: 12.4.6
 - iOS Device: iPhone 5s
 - unc0ver Version: 4.3.1
 - Machine Name:: iPhone6, 1

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Hamlock-Maneuver** [comment]
Use checkrain

**Comment by Hamlock-Maneuver** [comment]
You seem to have forgotten who I am cryptic.  You will find out.

**Comment by Hamlock-Maneuver** [comment]
I'll slap you first so you know who it is when it happens.

**Comment by DanTheMann15** [comment]
unc0ver currently doesn't work on iOS 12.4.1 through 12.4.6.

support for some (or all) of these firmwares "might" be added later, but don't hold your breath.

if you need a jailbreak on these firmwares, use [checkra1n](https://checkra.in/)
(assuming you have a device older than t8020 and that you have access to a mac or a linux machine)
