### ISSUE TITLE
Cydia crashes when I open it

### ISSUE THREAD

**Issue by tobybyb** [pwn20wndstuff/Undecimus#193]
all the tweaks work fine but i cant open cydia

i’ve tried the “reinstall cydia“button but it still crashes. i am on the dummy version of substrate and both unc0ver 2.02and 2.1 have the issue 

it is really werid

**Comment by eeesliao** [comment]
Delete the following folders:

1- var/mobile/library/cydia/metadata.cb0

2- var/mobile/library/caches/com.saurik.Cydia (Whole folder)

now you can open cydia again

**Comment by Cryptiiiic** [comment]
@tobybyb Is there a cydia crashlog? also post unc0ver diagnostics.

**Comment by frankmaresca** [comment]
> Delete the following folders:
> 
> 1- var/mobile/library/cydia/metadata.cb0
> 
> 2- var/mobile/library/caches/com.saurik.Cydia (Whole folder)
> 
> now you can open cydia again

So ive been jailbroken for months now with no cydia issues what so ever on my ipad pro 12.1.1 using uncover jailbreak and this morning when i tried to open cydia it would start to load but always crash...i tried everything reccomended and nothing worked until i read this post..i made an account just to personally thank you for posting this solution...it was killing me that i couldnt figure out how to fix my problem especially when i havent installed any new tweaks in over a month....thanks eeesliao!!
