### ISSUE TITLE
icloud keychain is abnormal

### ISSUE THREAD

**Issue by dihaohappy** [pwn20wndstuff/Undecimus#1930]
**Describe the bug**
The newly added account password of the icloud keychain function will be lost after the jailbreak environment is lost. IPXPROMAX IOS 13.3. Another problem is that after restarting springboard, icloud's auto-fill function will display abnormally, specifically the password above the keyboard will disappear, leaving only a key button on the right.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iphone pro max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
Since there is no abnormality caused by the device, I do not know how to get the log

**Comment by Cryptiiiic** [comment]
@dihaohappy post unc0ver diagnostics and post screenshots/videos

**Comment by dihaohappy** [comment]
I can't send list file types. What's your email address?

**Comment by Cryptiiiic** [comment]
@dihaohappy just rehost it or rename it to .txt

**Comment by dihaohappy** [comment]
I uploaded the log file to Google Web Drive, please download and view it. I have made a screenshot. And with a concise and easy-to-understand explanation. I hope you understand my English


unc0ver log link: https://drive.google.com/file/d/1JO89r8egFxOYsKNyxMhO9Scddo_wA3kc/view?usp=drivesdk

![05BD5F55-64FA-4EA1-8E6B-AC5C1E8C15DF](https://user-images.githubusercontent.com/62019352/79046200-0a41ed80-7c42-11ea-9508-506a1ba949cd.jpeg)
![7608EEEE-75A7-4B28-ABCA-65D863165A67](https://user-images.githubusercontent.com/62019352/79046202-0ca44780-7c42-11ea-9335-b3e136cabdef.jpeg)

**Comment by Cryptiiiic** [comment]
@dihaohappy does it happen when not jailbroken or only when you jailbreak

**Comment by dihaohappy** [comment]
He only appeared in the jailbreak environment

**Comment by Cryptiiiic** [comment]
@dihaohappy try userspace reboot

`launchctl reboot userspace`

**Comment by dihaohappy** [comment]
I know that it can be restarted to solve the problem. But every time you install the plug-in or update the plug-in, you need to restart springboard in cydia. Need to perform additional ldrestart

**Comment by Cryptiiiic** [comment]
**Unfortunately, to reduce issue spam/clutter, help is not provided for those who have pirate packages or repos.** I can in fact help you after you remove all your piracy. After removing all of it, please say if you still experience this icloud keychain issue. Closing this for now. I will reopen if you still have this issue after removing all piracy and piracy repos.
