### ISSUE TITLE
Stuck on apple logo after jailbreaking

### ISSUE THREAD

**Issue by Brobbo41** [pwn20wndstuff/Undecimus#1931]
**Describe the bug**
Just recently with unc0ver, after I jailbreak, the apple logo stays for 5 minutes, then I get rebooted to the lockscreen un-jailbroken. This hasn't happened before. I have reset Cydia cache but that doesn't help/

**To Reproduce**
1. Press jailbreak button in Unc0ver
2. Click OK on the popup once jailbroken in Unc0ver
3. Stuck on apple logo for 5 minutes
4. Finally at lock-screen but in an un-jailbroken state

**Screenshots**
![image](https://user-images.githubusercontent.com/61969096/79065618-61000380-7ce4-11ea-88a3-8569a8d99a9d.png)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: 10,1 iPhone 8
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Comment by Cryptiiiic** [comment]
@BaileyRob41 You have a bad tweak post unc0ver diagnostics. This is not an issue with unc0ver itself.

**Comment by Brobbo41** [comment]
> @BaileyRob41 You have a bad tweak post unc0ver diagnostics. This is not an issue with unc0ver itself.

Ohhhh ok, I'l uninstall the tad tweak. Thanks!
