### ISSUE TITLE
Unable to jailbreak on jailed state with disabled OTA daemon

### ISSUE THREAD

**Issue by Paul-2-4** [pwn20wndstuff/Undecimus#1932]
**Describe the bug**
I restored FS and made a backup on iCloud, but didn't enable the OTA daemon again beforehand.
Restored firmware 13.3 on iPhone SE, then used iCloud backup to set it up. The OTA daemon is still disabled at this point.
When trying to jailbreak now, it says:

"Error
RootFS already mounted, delete OTA file from Settings - Storage if present and reboot."

I have no such file. Going into Settings - Software Update crashes the Settings app, since the OTA daemon is disabled.
Nice way to block unwated updates in jailed state, but I suspect this whole thing being the culprint to not being able to jailbreak.

Please look into this. I'm paying on Patreon since you announced the jailbreak.

**Screenshots**
![image0](https://user-images.githubusercontent.com/54375569/79071239-f4ccd200-7cda-11ea-9603-b09475e86123.png)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone SE
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
Unc0ver crashes when trying to see the log after the supplied screenshot.

**Comment by Cryptiiiic** [comment]
@Paul-2-4 [https://twitter.com/Jakeashacks/status/1103747007745835011](https://twitter.com/Jakeashacks/status/1103747007745835011)

**Comment by Cryptiiiic** [comment]
No response

**Comment by Paul-2-4** [comment]
> @Paul-2-4 https://twitter.com/Jakeashacks/status/1103747007745835011

This is not the issue I am having.
I cannot jailbreak. I cannot download or delete any OTA updates, since the OTA daemon is disabled. I have no option to enable the OTA daemon.

**Comment by Cryptiiiic** [comment]
@Paul-2-4 rootfs should wipe it completely and since you say to already did that idk why it won't work.
