### ISSUE TITLE
FaceTime Calls Not Connecting/Unable to Accept

### ISSUE THREAD

**Issue by harshsingh7** [pwn20wndstuff/Undecimus#1934]
I’ve heard that many people are facing this yet no one seems to have added it to this list. Sometimes you aren’t able to Pickup any FaceTime calls or if you make one, it won’t connect.

**To Reproduce**
1. After jailbreaking, just  try making a FaceTime call. (Should he successful)
2. Make a call tasting upper SIM, like no VOIP Carling, regular call. 
3. Now try making a FaceTime call, it won’t connect, or if you receive, it will fail to connect.

**Device :**
 - iOS Version:  13.3  (17C54)
 - iOS Device: iPhone XS Max  (iPhone 11,6)
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Comment by Cryptiiiic** [comment]
@harshsingh7 please post unc0ver diagnostics.

**Comment by harshsingh7** [comment]
How do I do that?

**Comment by Cryptiiiic** [comment]
@harshsingh7 unc0ver > Settings Tab > Share Diagnostics.

**Comment by harshsingh7** [comment]
Had to include a zip file, couldn’t upload the plist by itself. Sorry for the inconvenience. [diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/4483180/diagnostics.zip)

**Comment by Cryptiiiic** [comment]
**Unfortunately, to reduce issue spam/clutter, help is not provided for those who have pirate packages or repos.** I can in fact help you after you remove all your piracy. After removing all of it, please say if you still experience this facetime issue. Closing this for now. I will reopen if you still have this issue after removing all piracy and piracy repos.
