### ISSUE TITLE
Bluetooth crashes springboard when not connected to WiFi

### ISSUE THREAD

**Issue by dev-luisraul** [pwn20wndstuff/Undecimus#1935]
This issue occurs now when in both the jailbroken AND unjailbroken state. Running Unc0ver v4.3.1 on iPhone X GSM iOS 13.3. 
UPDATE: I’ve realized the issue only occurs when connected to my AirPods Pro. I’ve tried resetting network settings, deleting and reconnecting my AirPods, and disabling all dylibs

**Comment by abodyn** [comment]
- [**@**`_]()

**Comment by abodyn** [comment]
> This issue occurs now when in both the jailbroken AND unjailbroken state. Running Unc0ver v4.3.1 on iPhone X GSM iOS 13.3. 
> 
> UPDATE: I’ve realized the issue only occurs when connected to my AirPods Pro. I’ve tried resetting network settings, deleting and reconnecting my AirPods, and disabling all dylibs
