### ISSUE TITLE
Connecting to AirPods Pro crashes SpringBoard. (Unc0ver 4.3.1 - iPhone X GSM iOS 13.3)

### ISSUE THREAD

**Issue by dev-luisraul** [pwn20wndstuff/Undecimus#1936]
Every time my device connects to my AirPods Pro, my device crashes. The big issue here is that it happens in both the jailbroken AND unjailbroken state. I can’t use my headphones at all anymore. I’ve tried resetting network settings, deleting and reconnecting my AirPods, and disabling all dylibs.. no luck

**Comment by Cryptiiiic** [comment]
If it happens in a non jailbroken state, how exactly is this unc0ver's fault?
