### ISSUE TITLE
VPN’s causing extreme slow internet

### ISSUE THREAD

**Issue by SupremoSG** [pwn20wndstuff/Undecimus#1938]
I had this issue for about 1-2 months now, but I never found the root cause of it, I tried to contact uncover devs but they said it wasn’t an uncover problem. It is a uncover problem, I had no tweaks installed and same problem. I’m jailbroken with an iPhone XR 13.3, the VPN that caused the problem was an adblocker. 

Edit: I forgot to mention but my data worked fine after I disabled the adblocker, but still, it’s a really annoying problem

**Comment by Cryptiiiic** [comment]
@SupremoSG does it happen in non-jailbroken mode(stock). Does it happen with the tweaks switch turned off? Does it happen after userspace reboot? Please post unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
@SupremoSG bump.

**Comment by Cryptiiiic** [comment]
No response.
