### ISSUE TITLE
A respring when charging the phone i wanna jailbreak.

### ISSUE THREAD

**Issue by Primiman** [pwn20wndstuff/Undecimus#1939]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
So, this has happened to me multiple time, i these are the only reasons i can see why it happens, Both my SE on 12.1.1 and both the latest unc0ver and on 3.8.0-b1, and the 6S on 12.4 on both of those un0ver versions, basically, while i'v been jailbroken, which lasted for a day only, i jailbroke while the phone was plugged into the charger on the 6S and it failed and now it resprings for like forever. left it for 15 minutes and it still keeps going, and it seems like the only way is to restore root fs, this happened to me also when i connect the 6S to my charger while it resprings after i've presed "jailbreak" in the unc0ver app, not sure what else i'd base my theory or if it's even a bug, but this has happened multiple times and i could probably replicate it, but i'm not sure how i'd get footage to show it, this has happened to me a couple of times in the last month.
So to sum it up, it resprings forever whenever i plug the phone in to charge while pressing "jailbreak" while both in airplane mode and not, to try different scenarios, and also to plug the phone to charge while it resprings, note this usually happens when i've been jailbroken and have a few tweaks, the first jailbreak after restoring always works the first time, if not, a reboot usually works to me. While after this issue has appeared, other times i try to jailbreak, it goes from my set respring logo which is unc0ver repsring logo to the default small loading logo, tried rejailbreaking with different stuff enabled, waiting a night or something to see if it would be any difference, but to no luck, and i can only see one way out, is to restore root fs. Sometimes my 6S immediately just reboots, sometimes after it resprings, and it switches from my custom unc0ver respring logo to the default one, it reboots, instead of keep respringing forever. This last this has happened to me like 3 times today when i tried to jailbreak.
As a side issue, not a big one, but when i press jailbreak sometimes, it just stays at 1/29 or 31 without moving. 
For unc0ver to jailbreak successfully without any problems it was, to not charge the phone while jailbreaking, and to put airplane mode on and disable bluetooth and wifi, because that's what i've been doing just so to make sure, i'm not doing it wrong.
**To Reproduce**
**Screenshots**
Can't screenshot the respring.
**Device (please complete the following information):**
 - iOS Version: 12.1.1 & 12.4
 - iOS Device: SE & 6S
 - unc0ver Version: 3.8.0-b1 & 4.3.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
Don't know if respringing has a log.

**Comment by Cryptiiiic** [comment]
@Primiman I'm not gonna spend time reading this. Please tldr and post your unc0ver diagnostics.

**Comment by Primiman** [comment]
@Cryptiiiic I'm new to posting stuff on here, so I'm not sure i know where you meant, but long story short.
I get this issue of either it resrpinging for forever, or respringing for a while, while swtiching repsring logo to my custom one and the default then reboot or just turns the screen black, and i thought it might be a bug, that if you connect your phone for it to charge, while it's either respringing or before you press "jailbreak" this issue happens and i'll have to restore root fs because countless of tries to jailbreak fails. 
Hope you or someone understand this. I might've explained it better in the inital bug report or post, incase you're not sure.

**Comment by Cryptiiiic** [comment]
@Primiman please post your unc0ver diagnostics file

**Comment by Primiman** [comment]
@Cryptiiiic Not sure what you mean, didn't know i could take anything from the unc0ver... app? Or not sure what you mean. Where can i find this "unc0ver diagnostic file" unless you mean the log, which would look generic now i'd imagine if that's what you meant?

**Comment by Cryptiiiic** [comment]
@Primiman unc0ver app > Settings tab > share diagnostics

**Comment by Primiman** [comment]
@Cryptiiiic Ah okay got it, does it matter if i've restored root fs and now it's working to jailbreak, until i recreate the issue again? And also do i post it in here as a comment or reply as a full text or should i try like graph or something? Or i can share it through google drive that i maanged to upload to and share a link to it? Also since i restored, the problem ain't there, until it returns, may i come back later, if this problem ever occur again and i'll post the diagnostic data on google drive and i'll share it, Last time it took me a little over a day for this to happen. If that's ok?

**Comment by Cryptiiiic** [comment]
@Primiman Yes reopen the issue if it occurs again. But send diagnostics after it occurs again.

**Comment by Primiman** [comment]
https://drive.google.com/open?id=1nVetpP-xS3Wcn0J_sCr3_C0_oLTXSJ7x
