### ISSUE TITLE
Crash immediatly after opening when rebooting device

### ISSUE THREAD

**Issue by jedai47** [pwn20wndstuff/Undecimus#1940]
The app crashes immediatly after opening when rebooting device even if it is signed with my apple id via reprovision.

**To Reproduce**
1. Install uncover via altdeploy using ur apple id
2. Jailbreak
3. Do your stuff
4. One day reboot 

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: Iphone 7
 - unc0ver Version: Latest

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by LiuliLiuqi-zz** [comment]
You can either install ReProvision from cydia, or install AltServer on your computer and AltStore on your iDevice to automatically re-sign your ipa and to avoid this. 
    If you still want to use AltDeploy, you need to re-sign your ipa at least every 7 days, or your certificate will be revoked and your ipa installed by altdeploy will crash like what you said.
