### ISSUE TITLE
Today View Widgets Crash

### ISSUE THREAD

**Issue by Greigh** [pwn20wndstuff/Undecimus#1941]
**Describe the bug**
Some Widgets in the Today View do not work under a stock jailbreak. Specifically, I can point out that Shortcuts crashes when you are using a shortcut that doesn't need to open the Shortcuts app in a jailed stock state. 

**To Reproduce**
1. Add Shortcuts to your Widget Today view. 
2. Try to run a Shortcut that doesn't require opening the Shortcuts app (Here's one: https://www.icloud.com/shortcuts/e62356a68d784678b189f512e5a5d3d1)
3. Shortcuts widget either just doesn't work or gives you and "Unable to Load" error. 

**Screenshots**
![IMG_1289](https://user-images.githubusercontent.com/57759540/79811541-1b76b280-8344-11ea-9ee1-1d5ec2f9b667.PNG)

**Device (please complete the following information):**
 - iOS Version: 13.3.
 - iOS Device: XS Max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Unfortunately, neither Cr4shed or CrashReporter are producing any kind of crash logs.

**Comment by Cryptiiiic** [comment]
@Greigh please post your unc0ver diagnostics file. Are you sure the widget actually works.

**Comment by Greigh** [comment]
Hmm you're right. It doesn't even work in stock mode. It must be an iOS 13.3 bug. Sorry about the trouble.
