### ISSUE TITLE
Unsupported for 12.4.6 (A7) 

### ISSUE THREAD

**Issue by adamtheapiguy** [pwn20wndstuff/Undecimus#1942]
I have iPhone 7 but I get "Unsupported". Is there any prerequisite documented some where for every release?

![IMG_0001](https://user-images.githubusercontent.com/11493202/79844303-d82d4a00-83fe-11ea-8918-de9fa8f8e35e.PNG)
![IMG_0002](https://user-images.githubusercontent.com/11493202/79844321-dcf1fe00-83fe-11ea-9a61-5a7c7a4f420b.PNG)

**Comment by Cryptiiiic** [comment]
Duplicate of #1923 and #1925

**Comment by Cryptiiiic** [comment]
Duplicate of #1923

**Comment by Cryptiiiic** [comment]
and #1925

**Comment by Cryptiiiic** [comment]
Duplicate of #1925
