### ISSUE TITLE
iPhone 11 iOS 13.3 call bug 

### ISSUE THREAD

**Issue by stuie1** [pwn20wndstuff/Undecimus#1944]
**Describe the bug**
Well idk what’s causing this problem but randomly if I wanna make a phone call or someone calls me I can’t make a call I can sms use the internet but not make a phone call 

**To Reproduce**
Idk what causes this problem I can’t figure that out but I’ll keep a eye out for this issue as what I can do I don’t think it’s any of my tweak but I’ll keep a look out
But if I turn off my iPhone rejAilbreak this call bug goes away I can make a phone call so u know even in safe mode I can’t make a phone call I think it’s a bug of some kind but ugh thank u so much hope I can see a update soon be awesome can’t wait love to see more!!!

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 11
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment]
@stuie1 Please post your unc0ver diagnostics.

**Comment by stuie1** [comment]
Got it 

Stuart Bailey Jr

**Comment by qasem99881** [comment]
> **Describe the bug**
> 
> Well idk what’s causing this problem but randomly if I wanna make a phone call or someone calls me I can’t make a call I can sms use the internet but not make a phone call 
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> Idk what causes this problem I can’t figure that out but I’ll keep a eye out for this issue as what I can do I don’t think it’s any of my tweak but I’ll keep a look out
> 
> But if I turn off my iPhone rejAilbreak this call bug goes away I can make a phone call so u know even in safe mode I can’t make a phone call I think it’s a bug of some kind but ugh thank u so much hope I can see a update soon be awesome can’t wait love to see more!!!
> 
> 
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> 
> 
> **Device (please complete the following information):**
> 
>  - iOS Version: 13.3
> 
>  - iOS Device: iPhone 11
> 
>  - unc0ver Version: 4.3.1
> 
> 
> 
> **Place an "x" between the brackets if true:**
> 
>  - [ ] this is a bug others will be able to reproduce
> 
>  - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
> 
>  - [ ] this issue is present after a rootfs restore
> 
>  - [x] this issue is present on the latest version of unc0ver
> 
> 
> 
> **Logs**
> 
> If applicable, add logs or error messages here.
> 
>

**Comment by stuie1** [comment]
I fixed it

Stuart Bailey Jr
