### ISSUE TITLE
Screen Mirroring not working

### ISSUE THREAD

**Issue by LegendArmour** [pwn20wndstuff/Undecimus#1945]
Iphone 11 Pro Max IOS 13.3
Unc0ver Ver. 4.3.1
Unable to use any kind of screen sharing app and native built in screen mirroring will not work on any device.

**Comment by Cryptiiiic** [comment]
@LegendArmour Please use the issue template. Please post your unc0ver diagnostics.

**Comment by Cryptiiiic** [comment]
No response.
