### ISSUE TITLE
127.0.0.1:22

### ISSUE THREAD

**Issue by ardi66** [pwn20wndstuff/Undecimus#1946]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment]
For localhost ssh install localssh on packix repo. @ardi66

**Comment by ardi66** [comment]
Kontol

Pada tanggal Sen, 27 Apr 2020 13.51, Liam(Cryptic) <notifications@github.com>
menulis:
