### ISSUE TITLE
Unc0ver crashes when launched

### ISSUE THREAD

**Issue by brennvika** [pwn20wndstuff/Undecimus#1947]
**Describe the bug**
When i try to open the unc0ver app it crashes

**To Reproduce**
1. Open the app
2. Watch it close

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: Iphone xs max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by m3rtngs** [comment]
What method did you use to install unc0ver onto your device?
