### ISSUE TITLE
after restore rootfs

### ISSUE THREAD

**Issue by unnamegeek** [pwn20wndstuff/Undecimus#1949]
can i do 'wipe all data and settings',i know there would be a loop once jailbroken for doing that, but how about the 'restore rootfs', is it still the same, or i can actually wipe my phone after restore roofs？

**Comment by Cryptiiiic** [comment]
You can erase all content and settings once your device rootfs restore. You should never erase all when jailbroken or have a jb rootfs but not in a jb state. @unnamegeek
