### ISSUE TITLE
Whatsapp unable to backup in uncover Jailbreak

### ISSUE THREAD

**Issue by romanadam91** [pwn20wndstuff/Undecimus#1950]
**Describe the bug**
**Whatsapp is unable to backup data to iCloud after the jailbreak(stuck and didn't move past the screenshot shared).** Had watusi 2 installed, removed it to check if it had something to do with the issue, didn't work. Tried Liberty Lite, TweakRestrictor didn't work. Deleted WhatsApp and reinstalled didn't work too. Someone please look into this and help.

**Screenshots**
![IMG_4584](https://user-images.githubusercontent.com/64604081/80746769-09fd8980-8b40-11ea-8628-8d3ec514fbcd.PNG)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone X
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Cryptiiiic** [comment]
Move #1744 because it's general whatsapp issues thread.

**Comment by romanadam91** [comment]
I installed JBPwn Whatsapp from Cydia and reinstall Whatsapp. It seems like its fixed. Thanks for the support though.

**Comment by wicky05** [comment]
how to read whatsapp messages in iPhone anonymously. ???

i want to Cydia or any other jailbreaker iphone app, using app library or repository i'll want to make my own app which fetch data &  send anonymous/ secrete to my web api.
