### ISSUE TITLE
[METHOD FOR SOLVING] Whatsapp Media Issue for all device

### ISSUE THREAD

**Issue by injpentesting** [pwn20wndstuff/Undecimus#1956]
Salve, dato che il mio inglese non è dei migliori posto questo articolo in italiano cosicché possiate tradurlo al meglio.

Visto che Unc0ver teams non rilascia al momento ulteriori aggiornamenti per la risoluzione di questo problema ho escogitato un metodo funzionante al 100% per tutti i device correlati a questo bug del jailbreak.

Seguite questi step passo per passo e non avrete alcun problema. Per qualsiasi chiarimento commentate questo post.

Il mio device è il seguente:

- iPhone XR
- iOS 13.1.3
- Unc0ver 4.3.1 (ultima rilasciata ad oggi)

**I passaggi da seguire in ordine sono:**

1. - Rimanere Whatsapp originale installato
2. - Rimuovere tutti i tweak inerenti a whatsapp (**jbpn Whatsapp, Whatsapp++, Watusi 2, etc**)
3. - Installare **Filza o altri File Manager**
4. - Installate **Adblock ++** (rejail.ru repo)
4. - Installare **Appcake**
5. - Pulizia cache con il tweak **iCleaner**
6. - **Disattivare A-Bypass per whatsapp** o altri tweak con questa funzione
7. - Andare con Filza nella seguente cartella: 

> /var/mobile/Containers/Shared/AppGroup/WhatsApp 

(potrebbero esserci più cartelle whatsapp, dovete trovare la cartella che contiene il file ChatStorage.sqlite)
8. - Copiare i seguenti file e cartelle nella pasteboard: **ChatStorage.sqlite; ChatStorage.sqlite-wal; Sticker.sqlite; Sticker.sqlite-wal; Message; stickers** (non preoccupatevi se non c'è la cartella stickers)
9. - Creare una cartella in: 

> /var/mobile/ (es. Whatsapp Backup)

10. - Incollare i file precedentemente copiati nella cartella creata
11. - **Disinstallate Whatsapp**
12. - Scaricare da Appcake "**Watusi for WhatsApp**"
13. - Installatelo
14. - Una volta installato, avviatelo e accettate i termini
15. - Aprite Filza
16. - Copiate i file precedentemente incollati (**/var/mobile/Whatsapp Backup**)
17. - Trovate la seguente cartella: 

> /var/mobile/Containers/Data/Application/WhatsApp/Documents/group.net.whatsapp.WhatsApp.shared/

 (se ci sono più cartelle Whatsapp, ordinatele per data)
18. - Incollate i file precedentemente copiati e sovrascriveteli
19. - A questo punto tornate nell'applicazione scaricata da Appcake e continuate la verifica (preferibilmente con chiamata e non messaggio)
20. - Procedete con la configurazione

Ed ecco il gioco è fatto!!! Ora siete in grado di inviare foto e video senza alcun problema!

Come ho detto in precedenza il metodo dovrebbe funzionare per tutti i devices e inoltre avrete anche watusi installato su whatsapp.

Per chiarimenti, informazioni o consigli commentate. Condividete questo post grazie :)

Credits: @emacapo94 @reddit

**Comment by waseem7** [comment]
English version?

**Comment by waseem7** [comment]
It’s a workaround and basically u will not use the original WhatsApp from appstore but a tweaked one after u backup and restore ur files to it. 


Still waiting for actual fix!

**Comment by car20001** [comment]
So what happens when they fix it and we wanna get our messages and stuff back to the original WhatsApp from the AppStore? Do we follow the same exact steps? Or do we do those steps in reverse?

**Comment by car20001** [comment]
One more thing...even though this fixes the issue of not being able to send videos. calls from WhatsApp don’t go through/ can’t receive calls. And push notification don’t go through with the app either.

**Comment by kzaoaai** [comment]
Fixed videos for me, but push notifications and calls stopped working. At this point I think the latter is more important.
