### ISSUE TITLE
App doesn't download from appstore in non-jailbroken state.

### ISSUE THREAD

**Issue by abidshahriar** [pwn20wndstuff/Undecimus#1957]
**Describe the bug**
I have this weird issue. Can’t download any apps in non jailbroken state.The download circle in the appstore just circles forever. 
I think the tweak appstore++ messed up something..however, removing it won’t fix the issue.
(deleted the plist file for the said tweak also , manually)
Or
Maybe this version of uncoverhad to do something with it..

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone11,6
 - unc0ver Version: 4.3.1

 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

hoping a fix. 
TIA

**Comment by Cryptiiiic** [comment]
@abidshahriar does it happen after reboot before jailbreaking? Post unc0ver diagnostics.

**Comment by eglacias** [comment]
No need to use App Store. Jailbreak your phone with checkrain using checkn1x usb Linux boot stick and install Cydia from it of course.  Now from cydia install filza and  The second to last version of reprovision by installing the latest, and then downgrading to that second to last version.   Now download uncover on your phone and browse to it in Filza and long press open with reprovision to install and sign!
 This is exactly what I do, in order to have on device jailbreak on that version  for when ever my phone has to reboot and I am not near a computer. IE I prefer to run checkrain but still, this allows uncover to run perfectly fine.

Unfortunately my newest device is on iOS 12.4.1 which uncover doesn’t support strangely enough!

**Comment by eglacias** [comment]
Oops  I thought you were talking about on device install of uncover!

Doing a restore rootFS, or switching jailbreaks and then doing a restore rootFS I would think may solve your actual problem?

**Comment by abidshahriar** [comment]
> @abidshahriar does it happen after reboot before jailbreaking? Post unc0ver diagnostics.

Yes. I restarted the device in non jailbroken state , the issue still persisted.

**Comment by abidshahriar** [comment]
> Oops  I thought you were talking about on device install of uncover!
> 
> 
> 
> Doing a restore rootFS, or switching jailbreaks and then doing a restore rootFS I would think may solve your actual problem?


Yeah that’s the last option. but i want to be certain about what exactly causing this issue.

**Comment by eglacias** [comment]
I have had the App Store do that under all kinds of circumstances that have nothing to do with the jailbreak or not. The most obvious is that your Internet connection it isn’t good, or that you have cellular data turn it off like I do, and Wi-Fi is actually not communicating data regardless of bars

 Even with a data connection I am pretty sure I have seen the App Store “crash“ in exactly this manner, where I cannot get it to actually download data. I would try more than one reboot without the jailbreak, and of course verify a data connection before even opening the App Store, And make sure you have cellular data turned on specifically for the App Store of course.

**Comment by cuucondiep** [comment]
Iphone 11 IOS 13.3.1 when have Jailbreak?
Please tell me. Thanks

**Comment by Cryptiiiic** [comment]
@abidshahriar if it persists even when not in a jailbroken state then this isn't unc0ver's fault. This is an internet issue, corrupt preference file, or corrupt cache issue.

**Comment by lewis0917** [comment]
I get this problem randomly and have to reboot.
