### ISSUE TITLE
Jailbreak error

### ISSUE THREAD

**Issue by JAMJAMJ-A-M** [pwn20wndstuff/Undecimus#1959]
This error message will always appear in the startup program, and the jailbreak environment has become unstable since this prompt.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by JAMJAMJ-A-M** [comment]
![E1DDF6D9-9F42-442C-891B-4F34D9E0AFD6](https://user-images.githubusercontent.com/21018730/81500308-04543080-9304-11ea-8c5b-3d7c69812399.jpeg)
![Uploading B629E823-007F-4B38-B759-49A7C78A31EE.jpeg…]()

**Comment by Cryptiiiic** [comment]
This has nothing to do with anything, please just ignore the error. It is not the cause of your issues at all.
