### ISSUE TITLE
Unsupported on iPhone 8 iOS 13.5

### ISSUE THREAD

**Issue by Escartem** [pwn20wndstuff/Undecimus#1964]
**Describe the bug**
Uncover 4.3.1 is unsupported on iPhone 8 with iOS 13.5.

**Screenshots**
![83E87303-AC43-4B91-81DC-7526F3D7B92A](https://user-images.githubusercontent.com/43405304/82736246-855def80-9d28-11ea-86ca-d2ad7b30c4e1.png)

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPhone 8
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Johnnygam3r** [comment]
Unc0ver 5.0.0 is not released yet, causing your “unsupported” bug. 4.3.1 does not support 13.5.

**Comment by Escartem** [comment]
Ok thanks
