### ISSUE TITLE
Dark Mode description is the same as 'Load Tweaks'

### ISSUE THREAD

**Issue by ajsacco** [pwn20wndstuff/Undecimus#1965]
**Describe the bug**
The description of the 'Dark Mode' option is the same as the description of 'Load Tweaks'

**To Reproduce**
1. Open Unc0ver
2. Click the settings icon
3. Hit the 'i' next to 'Dark Mode'

**Screenshots**
[https://imgur.com/RrPnQDs](url)

**Device:**
 - iOS Version: 13.5
 - iOS Device: iPhone 8
 - unc0ver Version: 5.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Not applicable

**Comment by HPaulson** [comment]
Definitely is occurring on v5. Not a big deal, just a copy/paste string they didn’t change. +1

**Comment by ajsacco** [comment]
Looks like it's fixed in 5.0.1.
