### ISSUE TITLE
unc0ver v5.0.0 An error occurred while ensuring resources of our application

### ISSUE THREAD

**Issue by nwilliams17** [pwn20wndstuff/Undecimus#1967]
![590E35E0-FD4E-4B34-BB77-E4D9C61C76F8](https://user-images.githubusercontent.com/25935889/82741814-fa223100-9d0a-11ea-9e1c-2c4c16d98010.png)

iPhone XS Max
iOS 13.4.1
Methods that failed: nullximpacter, AltDeploy, iOS App Signer + Xcode

Update: Only working method that I’ve tried so far is the AltStore method. 
Just for good measure, I deleted unc0ver from my phone and rebooted. Updated Altserver on my mac to the latest version, installed altstore on my iphone, and then opened unc0ver.dev through my phone and clicked 'open with altstore' and the jailbreak worked this time. So the issue is the install method, not the jailbreak.

**Comment by Johnnygam3r** [comment]
DRM is broken, try altstore. Sadly for me, it doesn’t work

**Comment by gh0st17** [comment]
Same issue. iPhone 7 iOS 13.5.
UPD: AltStore method worked.

**Comment by acsway878787** [comment]
I've tried Altserver Patcher, but it didn't work either. Seems that installing unc0ver via Altstore is the only way to pass the check. Hope Altserver Patcher method works too because I don't want to install one more IPA for jailbreaking, the less is the better.

**Comment by ThatStella7922** [comment]
I think this *only* works over AltStore. I keep getting this error when using the Buildstore signing service and the official github from unc0ver.dev.

**Comment by claui** [comment]
## Fix 1 (if you use some sort of external signing service)

If you use some tool or service to sign unc0ver:

- Inspect `unc0ver.app` manually after signing. (If the tool or service gives you only an .ipa file, unzip that first to get `unc0ver.app`.)
- Make sure **no unnecessary extra files** have been placed into the `unc0ver.app` directory that weren’t there when you downloaded the `.ipa` from the website originally. Compare the (unzipped) original `.ipa` if you’re not sure. Allowed files are a) the provisioning profile, and b) a `_CodeSignature` subdirectory. Other than that, no extra files should be present that weren’t there before signing.
- In particular, **delete from `unc0ver.app` any leftover plist file that contains entitlements.** (Leave alone `Info.plist` though.)
- Upload `unc0ver.app` to your device.

## Fix 2 (requires macOS, Xcode and an Apple Developer account)

Also, here’s a reliable method to sign and install unc0ver using just Xcode and an Apple Developer account:

- Unpack the `.ipa` file
- Sign in to the Apple Developer website.
- Create an app ID using a bundle ID wildcard such as `science.xnu.*`. (Don’t use `science.xnu.undecimus` as Apple is going to reject that.)
- Create a provisioning profile for your device and app ID.
- Download the provisioning profile from Apple, place it inside the `unc0ver.app` directory and rename it to `embedded.mobileprovision`.
- Create a minimal entitlements plist, e. g. `/tmp/Entitlements.plist`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>YOURTEAMID.science.xnu.undecimus</string>
</dict>
</plist>
```

- Ensure the Team ID in `Entitlements.plist` matches your own Team ID (aka *App ID Prefix*). Also, ensure everything after the first dot matches your bundle ID wildcard.
- Look up the name of your signing certificate exactly as it appears in `Keychain Access.app`
  (e. g. `iPhone Distribution: Your Name (YOURTEAMID)`)
- Open `Terminal.app` and `cd` to the `unc0ver.app` directory.
- Sign the app by running the following command line:

```bash
/usr/bin/codesign -f -s 'iPhone Distribution: Your Name (YOURTEAMID)' --entitlements /tmp/Entitlements.plist .
```

- Double-check no extra files have been added to the `unc0ver.app` directory apart from `embedded.mobileprovision`.
- Connect your phone.
- Open Xcode and go to *Window* » *Devices and Simulators*.
- Using the Finder, navigate to `unc0ver.app` and drag it onto Xcode’s device window.

Works reliably for me with unc0ver 5.0.0, 5.0.1, and 5.2.0.

**Comment by Jack06WS** [comment]
I've also got this issue and using AltStore and Cydia Impactor with a developer account does not fix it.
