### ISSUE TITLE
SettingPage stretched on iPhone 11

### ISSUE THREAD

**Issue by Niclas1337** [pwn20wndstuff/Undecimus#1969]
**Describe the bug**
Open Settings of unc0ver -> settings are stretched

**To Reproduce**
settings -> x

**Screenshots**
see next post

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPhone 11
 - unc0ver Version: 5.0

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by Niclas1337** [comment]
![24052020_004614_521](https://user-images.githubusercontent.com/34512773/82741933-0aacc880-9d58-11ea-8411-b5a397b73725.png)

**Comment by rlatm** [comment]
The 6.x version of unc0ver has now been released at http://unc0ver.dev/ so you may want to see if that resolves any issue you saw? Thanks.

**Comment by Niclas1337** [comment]
It does
