### ISSUE TITLE
ios 12.4.7 iphone 5s not supported

### ISSUE THREAD

**Issue by FDeghy** [pwn20wndstuff/Undecimus#1970]
hello
iOS 12.4.7 iPhone 52
your site say "unc0ver supports iOS 11.0 through to iOS 13.5 (Excluding 12.3-12.3.2 and 12.4.2-12.4.5)" 
=
12.4.7 supported
but
not supported

**Comment by triaefta** [comment]
same problem iPad mini 2 iOS 12.4.7

**Comment by zxsleebu** [comment]
same problem iphone 6 12.4.7

**Comment by champcm** [comment]
same problem on  iPad Air 1 (4,1)

**Comment by Assfugil** [comment]
iOS 12.4.2 - iOS 12.4.7 currently not supported on 4k devices

**Comment by zxsleebu** [comment]
Lol no. pwn20wnd said it will be supported on every iOS starting from 11.0 to 13.5 and on every device, so we won't close it

**Comment by yarkovalexey** [comment]
same problem iphone 6 12.4.4

**Comment by KatyushaScarlet** [comment]
Same problem on iPhone6Plus with 12.4.7

**Comment by rbits0** [comment]
Same problem on iPhone 6 Plus on iOS 12.4.7

**Comment by DanTheMann15** [comment]
on 4K devices, iOS 12.3-12.3.1 and 12.4.1-12.4.7 aren't supported.

i think the reason for this is that compatibility with these firmwares are not high on the priority list.
the team might get to it eventually, but don't hold your breath.

if all else fails, use [checkra1n](https://checkra.in).

**Comment by Ben569483** [comment]
It's because it is the new of the old so just close this issue. There will be support soon

**Comment by FDeghy** [comment]
> It's because it is the new of the old so just close this issue. There will be support soon

what time to support 12.4.7
