### ISSUE TITLE
Cydia crashing

### ISSUE THREAD

**Issue by error474** [pwn20wndstuff/Undecimus#1979]
**Describe the bug**
Cydia appears to crash on some iPads when a tweak is clicked.

**To Reproduce**
1. Go to Cydia
2. Click on any tweak
3. Cydia immediately crashes

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPad8, 1 (iPad Pro 11 inch)
 - unc0ver Version: 5.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[text.txt](https://github.com/pwn20wndstuff/Undecimus/files/4673435/text.txt)

**Comment by JayTWill** [comment]
Can confirm this is also present on an XR 13.5

**Comment by cl0vrfi3ld** [comment]
Can you install another package manager, or is cydia totally bricked?

**Comment by CrCrate** [comment]
You can if you go thru a link directly opening the package in cydia, but its really annoying.

**Comment by error474** [comment]
@1MaddieX @CrCrate I’ve found a small workaround for me, I don’t know if it works for others with the same issue. SwipeForMore luckily works for me and using this is the only way for me to install other packages. I’ve installed CrashReporter but it doesn’t pick it up.

**Comment by c0nfleis** [comment]
> @1MaddieX @CrCrate I’ve found a small workaround for me, I don’t know if it works for others with the same issue. SwipeForMore luckily works for me and using this is the only way for me to install other packages. I’ve installed CrashReporter but it doesn’t pick it up.

This unfortunate didn’t work. Can’t install SwipeForMore due to it crashing :/

**Comment by CrCrate** [comment]
> > @1MaddieX @CrCrate I’ve found a small workaround for me, I don’t know if it works for others with the same issue. SwipeForMore luckily works for me and using this is the only way for me to install other packages. I’ve installed CrashReporter but it doesn’t pick it up.
> 
> This unfortunate didn’t work. Can’t install SwipeForMore due to it crashing :/

Open this http://cydia.saurik.com/package/com.tigisoftware.filza/ link and click open in cydia, you shou be able to install filza. Then get swipeformore deb file here http://apt.thebigboss.org/repofiles/cydia/debs2.0/swipeformore_1.1.7.deb and install with filza

**Comment by Oscillate18** [comment]
Hi,

I found a solution on Reddit that worked for me which involves resetting the settings from
Settings> General > Reset > Reset All Settings

This fully solved the issue for me however it does involve wiping your settings so have a backup!

You won't lose any data just settings like Wi-Fi etc. Do not chose 'Erase All Content and Settings' else this will wipe your data as well.

**Comment by Vykori** [comment]
@Oscillate18 thanks for the clues, the conflicting setting (in my case) was full keyboard access (settings > accessability > keyboards > full keyboard access > enable/disable toggle)

Could you spread that info in the reddit thread you learned that trick from?

**Comment by Axel29** [comment]
> @Oscillate18 thanks for the clues, the conflicting setting (in my case) was full keyboard access (settings > accessability > keyboards > full keyboard access > enable/disable toggle)
> 
> Could you spread that info in the reddit thread you learned that trick from?

**It worked for me too!**

I got really scared! I was jailbroken on iOS 12.0.1 with Chimera (iPhone XS 11,2) and finally decided to try that upgrade to 13.5 with unc0ver. So I made a clean restore of my iPhone "from scratch" without using iCloud backup to have an entirely clean iPhone, but when I got these crashes I started to panic :p 

So.... What I mean to say is: THANK YOU!

**Comment by CrCrate** [comment]
Please post all following questions to #1991, I won’t be checking this thread anymore.

**Comment by cxen** [comment]
> 
> 
> @Oscillate18 thanks for the clues, the conflicting setting (in my case) was full keyboard access (settings > accessability > keyboards > full keyboard access > enable/disable toggle)
> 
> Could you spread that info in the reddit thread you learned that trick from?

This has worked for me! Thanks for saving me from resetting all settings!
