### ISSUE TITLE
Unc0ver fails

### ISSUE THREAD

**Issue by ujaveri** [pwn20wndstuff/Undecimus#1988]
![5BD71763-A2FC-416C-8BE4-7F452200967C](https://user-images.githubusercontent.com/55907135/82749388-657b0a00-9dc2-11ea-856a-051c4a346cf4.png)

iPhone X 
13.5

![558E607D-215C-4E31-B867-CB816C35D53F](https://user-images.githubusercontent.com/55907135/82749399-70ce3580-9dc2-11ea-8397-db9f3df9a5d4.png)

**Comment by slassh1337** [comment]
iPhone 11 Pro
IOS 13.5
![FD05573D-DEDD-48AE-86C2-641913E8FF53](https://user-images.githubusercontent.com/65848321/82749672-1e354f00-9dab-11ea-8d26-44c5de3cd420.png)

**Comment by sa1rf** [comment]
Yeh I get the same problem on iPhone SE 1st gen

**Comment by FurkanYks** [comment]
İpad 6-7 th generation error:

Verified "./usr/lib/substitute-inserter.dylib"
[+] Verified "./usr/libexec/substitute-reload"
[+] Verified "./usr/libexec/substituted"
[+] Verified "./usr/share/entitlements/inject.xml"
[+] Verified "./usr/share/substitute/signcert.p12"
[*] No errors in verifying checksums
[*] Stage (23): Resolving dependencies
[*] Resource Pkgs: "(
    firmware,
    grep,
    "ncurses5-libs",
    "coreutils-bin",
    "profile.d",
    coreutils,
    ncurses,
    readline,
    sed,
    bash,
    bzip2,
    diffutils,
    file,
    findutils,
    gzip,
    libplist,
    "ca-certificates",
    "libssl1.0",
    ldid,
    lzma,
    xz,
    tar,
    dpkg,
    "science.xnu.substituted",
    launchctl,
    "com.ex.substitute"
)".
[+] Resolved dependencies
[*] Stage (24): Verifying resources
[*] Need to repair "grep".
[*] Need to repair "ncurses5-libs".
[*] Need to repair "coreutils-bin".
[*] Need to repair "profile.d".
[*] Need to repair "ncurses".
[*] Need to repair "readline".
[*] Need to repair "coreutils".
[*] Need to repair "sed".
[*] Need to repair "bash".
[*] Need to repair "diffutils".
[*] Need to repair "bzip2".
[*] Need to repair "file".
[*] Need to repair "findutils".
[*] Need to repair "gzip".
[*] Need to repair "libplist".
[*] Need to repair "ca-certificates".
[*] Need to repair "libssl1.0".
[*] Need to repair "ldid".
[*] Need to repair "lzma".
[*] Need to repair "xz".
[*] Need to repair "tar".
[*] Need to repair "dpkg".
#[*] Need to repair "launchctl".
[*] Need to repair "com.ex.substitute".
[+] Verified resources
[*] Stage (25): Extracting resources
[*] (Re-)Extracting "(
    grep,
    "ncurses5-libs",
    "coreutils-bin",
    "profile.d",
    ncurses,
    readline,
    coreutils,
    sed,
    bash,
    diffutils,
    bzip2,
    file,
    findutils,
    gzip,
    libplist,
    "ca-certificates",
    "libssl1.0",
    ldid,
    lzma,
    xz,
    tar,
    dpkg,
    launchctl,
    "com.ex.substitute"
)".
Unable to resolve ldid to a deb
[-] Unable to get debs for packages to repair.

**Comment by onetr1ck** [comment]
> İpad 6-7 th generation error:
> 
> Verified "./usr/lib/substitute-inserter.dylib"
> [+] Verified "./usr/libexec/substitute-reload"
> [+] Verified "./usr/libexec/substituted"
> [+] Verified "./usr/share/entitlements/inject.xml"
> [+] Verified "./usr/share/substitute/signcert.p12"
> [_] No errors in verifying checksums [_] Stage (23): Resolving dependencies
> [_] Resource Pkgs: "( firmware, grep, "ncurses5-libs", "coreutils-bin", "profile.d", coreutils, ncurses, readline, sed, bash, bzip2, diffutils, file, findutils, gzip, libplist, "ca-certificates", "libssl1.0", ldid, lzma, xz, tar, dpkg, "science.xnu.substituted", launchctl, "com.ex.substitute" )". [+] Resolved dependencies [_] Stage (24): Verifying resources
> [_] Need to repair "grep". [_] Need to repair "ncurses5-libs".
> [_] Need to repair "coreutils-bin". [_] Need to repair "profile.d".
> [_] Need to repair "ncurses". [_] Need to repair "readline".
> [_] Need to repair "coreutils". [_] Need to repair "sed".
> [_] Need to repair "bash". [_] Need to repair "diffutils".
> [_] Need to repair "bzip2". [_] Need to repair "file".
> [_] Need to repair "findutils". [_] Need to repair "gzip".
> [_] Need to repair "libplist". [_] Need to repair "ca-certificates".
> [_] Need to repair "libssl1.0". [_] Need to repair "ldid".
> [_] Need to repair "lzma". [_] Need to repair "xz".
> [_] Need to repair "tar". [_] Need to repair "dpkg".
> #[_] Need to repair "launchctl". [_] Need to repair "com.ex.substitute".
> [+] Verified resources
> [_] Stage (25): Extracting resources [_] (Re-)Extracting "(
> grep,
> "ncurses5-libs",
> "coreutils-bin",
> "profile.d",
> ncurses,
> readline,
> coreutils,
> sed,
> bash,
> diffutils,
> bzip2,
> file,
> findutils,
> gzip,
> libplist,
> "ca-certificates",
> "libssl1.0",
> ldid,
> lzma,
> xz,
> tar,
> dpkg,
> launchctl,
> "com.ex.substitute"
> )".
> Unable to resolve ldid to a deb
> [-] Unable to get debs for packages to repair.

Same on iPhone XS MAX on iOS 13.5

**Comment by Zelakor** [comment]
I have the same problem as the first picture where it says the “build has been tampered with”  iPhone X, iOS 13.5, unc0ver 5.0.0 and 5.0.1

**Comment by jirijanata** [comment]
Please use unmodified version of AltStore and at first install AltStore on your device and then install unc0ver throught AltStore. Then it will work :)

**Comment by ujaveri** [comment]
Rickpactor signed so it’s UN modified and still errors on iPhone X v13.5 

![D6257C41-9C11-48D8-8DAA-29997D3A366A](https://user-images.githubusercontent.com/55907135/82811439-350e9b00-9eaa-11ea-8996-b41cee171ba8.png)

**Comment by jirijanata** [comment]
Can you please install unc0ver via AltServer - https://altstore.io/

It's very easy, just install AltServer and then install on your phone unc0ver. It takes maximally 15 minutes.

**Comment by ujaveri** [comment]
It doesn’t install on my laptop.  Tried everything.  Anyway got it working via signing service. Thanks for your help. 
Ticket close.

![7BDAFF6B-89BD-4D16-B91F-2F3EE9EC5FCA](https://user-images.githubusercontent.com/55907135/82823447-04862b80-9ec1-11ea-838c-db7dbb9cf5e4.jpeg)

**Comment by sa1rf** [comment]
I get this error on my pc saying ‘failed to verify code signature of
/private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.37zwBg/extracted/AltStore.app
: 0xe8008015 ( A valid provisioning file for this executable was not found)
