### ISSUE TITLE
iPhone 6 11.3.1 

### ISSUE THREAD

**Issue by mnemonicgr** [pwn20wndstuff/Undecimus#199]
Happy new year !!! 
So the last days with all the updates being made...I made a full restore of my device and waited for the uncover v2.1.0 to be public and for sauric to fix the issue!!! After all these was ok I jailbreaked and till now I didn’t notice anything wrong ...everything is working fine and smoothly.the tweaks I have install are:activator,AudioRecorder,bioprotect x,callbarx,marina,PowerSelector,preferenceorganizer2,snapper2 snowboard ...

**Comment by atifchy** [comment]
Nice. Close this issue.
