### ISSUE TITLE
İpad 6 Jailbreak Error Help

### ISSUE THREAD

**Issue by FurkanYks** [pwn20wndstuff/Undecimus#1990]
An error occurred while extracting an archive error! Logs:

Verified "./usr/lib/substitute-inserter.dylib"
[+] Verified "./usr/libexec/substitute-reload"
[+] Verified "./usr/libexec/substituted"
[+] Verified "./usr/share/entitlements/inject.xml"
[+] Verified "./usr/share/substitute/signcert.p12"
[*] No errors in verifying checksums
[*] Stage (23): Resolving dependencies
[*] Resource Pkgs: "(
    firmware,
    grep,
    "ncurses5-libs",
    "coreutils-bin",
    "profile.d",
    coreutils,
    ncurses,
    readline,
    sed,
    bash,
    bzip2,
    diffutils,
    file,
    findutils,
    gzip,
    libplist,
    "ca-certificates",
    "libssl1.0",
    ldid,
    lzma,
    xz,
    tar,
    dpkg,
    "science.xnu.substituted",
    launchctl,
    "com.ex.substitute"
)".
[+] Resolved dependencies
[*] Stage (24): Verifying resources
[*] Need to repair "grep".
[*] Need to repair "ncurses5-libs".
[*] Need to repair "coreutils-bin".
[*] Need to repair "profile.d".
[*] Need to repair "ncurses".
[*] Need to repair "readline".
[*] Need to repair "coreutils".
[*] Need to repair "sed".
[*] Need to repair "bash".
[*] Need to repair "diffutils".
[*] Need to repair "bzip2".
[*] Need to repair "file".
[*] Need to repair "findutils".
[*] Need to repair "gzip".
[*] Need to repair "libplist".
[*] Need to repair "ca-certificates".
[*] Need to repair "libssl1.0".
[*] Need to repair "ldid".
[*] Need to repair "lzma".
[*] Need to repair "xz".
[*] Need to repair "tar".
[*] Need to repair "dpkg".
[*] Need to repair "launchctl".
[*] Need to repair "com.ex.substitute".
[+] Verified resources
[*] Stage (25): Extracting resources
[*] (Re-)Extracting "(
    grep,
    "ncurses5-libs",
    "coreutils-bin",
    "profile.d",
    ncurses,
    readline,
    coreutils,
    sed,
    bash,
    diffutils,
    bzip2,
    file,
    findutils,
    gzip,
    libplist,
    "ca-certificates",
    "libssl1.0",
    ldid,
    lzma,
    xz,
    tar,
    dpkg,
    launchctl,
    "com.ex.substitute"
)".
Unable to resolve ldid to a deb
[-] Unable to get debs for packages to repair.

**Comment by SarKaa** [comment]
Yes same here on iPhone 7 Plus iOS 13.4.1

**Comment by SarKaa** [comment]
I dug into this a bit more
Try enabling the (re)install cydia option and try again, I haven't tried this myself, but it should work

**Comment by FurkanYks** [comment]
> I dug into this a bit more
> Try enabling the (re)install cydia option and try again, I haven't tried this myself, but it should work
İm tryed not working
