### ISSUE TITLE
Jailbreak Complete but having Error after rebel case pop up

### ISSUE THREAD

**Issue by carlolong** [pwn20wndstuff/Undecimus#1994]
![C00D8FB9-6529-43EC-8D42-076B77FF3BD1](https://user-images.githubusercontent.com/65861334/82757689-b9164380-9e14-11ea-8012-147d94677574.jpeg)

**Describe the bug**

The phenoma happens after the rebel case pop up. The bug will pop “Jailbreak Complete: An Error occured while extracting an archive

**To Reproduce**
1. Just press jailbreak and wait on the popup
 - iOS Version: 13.5
 - iOS Device: i6s
 - unc0ver Version: 5.0.0

 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by icanc0** [comment]
same problem here with 6s plus on ios 13.5
restore rootfs wont do anything

**Comment by Cardesh38** [comment]
Solution: Download unc0ver over AltStore. This helped me.

**Comment by carlolong** [comment]
Thanks Cardesh38🤗
