### ISSUE TITLE
Cydia crashing everytime a package is viewed.

### ISSUE THREAD

**Issue by DuploMinh** [pwn20wndstuff/Undecimus#1996]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

This may or may not be related to Unc0ver but I cannot find an issue page for Cydia. 
Cydia will crash everytime I enter a page for a package. 

**To Reproduce**
1. Go to Cydia
2. Find a Package
3. Click on the package page
4. Cydia will crash

**Screenshots**
Just Cydia crashing

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: Xs Max
 - unc0ver Version: 5.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Oscillate18** [comment]
Hi,

I found a solution on Reddit that worked for me which involves resetting the settings from
Settings> General > Reset > Reset All Settings

This fully solved the issue for me however it does involve wiping your settings so have a backup!

You won't lose any data just settings like Wi-Fi etc. Do not chose 'Erase All Content and Settings' else this will wipe your data as well.

**Comment by CrCrate** [comment]
See thread #1991

**Comment by DuploMinh** [comment]
Solved! @Oscillate18 ‘s solution worked.
