### ISSUE TITLE
When I re-jailbreak sometimes, 17/31 purging software updates gets stuck and does not continue

### ISSUE THREAD

**Issue by jailbreaker17** [pwn20wndstuff/Undecimus#1999]
**Describe the bug**
When rejailbreaking, step 17/31 purging software updates is stuck. Even after a few minutes of waiting it does not continue. When I kill the unc0ver app and then try to reopen the app it crashes. Only way to fix it is do a force restart.

**To Reproduce**
There is no specific time it can be reproduced.

**Screenshots**
![image](https://user-images.githubusercontent.com/65879720/82772600-37ed9980-9e72-11ea-9ee4-1120ab9be33a.png)

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: 11 pro max
 - unc0ver Version: 5.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by jirijanata** [comment]
Have you tried to backup and restore your iPhone via iTunes?

**Comment by jailbreaker17** [comment]
> Have you tried to backup and restore your iPhone via iTunes?

Not yet because i have a 200gb backup. I don’t have a means of backing up my data. This happened for the first time in using the v5.0.0 version

**Comment by jirijanata** [comment]
How you updated to iOS 13.5? OTA or iTunes?

**Comment by jailbreaker17** [comment]
I updated via iTunes.     
  

  
  
>

**Comment by jirijanata** [comment]
Okay - there should be no updates, but you can try it - go to Settings -> General -> iPhone Storage and you can try to delete OTA updates, but there should be none.

Have you enough free space on your iPhone (1-10GB)? Was your iPhone Jailbroken before?

If you have SSD, than Backup and Restore should be done in 45-60 Minutes. Just make sure, that you have access to your Bank Application etc. They usually needs to be reactivated after Backup&Restore. I think, that in next few days there will be few more new builds, so you can wait a little bit, but for now is restore is the quickest method.

**Comment by jailbreaker17** [comment]
Thanks for the help.   I'll try it out.   
  
  
  

  
  
  

  
  
>
