### ISSUE TITLE
Landscape orientation Support for iPad

### ISSUE THREAD

**Issue by th3sn3k** [pwn20wndstuff/Undecimus#2002]
**Describe the feature you'd like**
iPad Support for the unc0ver app.
Landscape support for the app it’s anoying rotating the iPad every time you need to jailbreak

**Comment by jirijanata** [comment]
It's already in version 5.0.1

**Comment by th3sn3k** [comment]
> It's already in version 5.0.1

Doesn't work for me on iPad Air 3

**Comment by jirijanata** [comment]
What ist not working for you? Unc0ver or Landscape mode?

**Comment by th3sn3k** [comment]
> What ist not working for you? Unc0ver or Landscape mode?

Landscape mode that’s why I submitted this under enhancement

**Comment by th3sn3k** [comment]
Closing this issue since unc0ver 5.2 fixes this
