### ISSUE TITLE
Tweak Injection into apps fails after an app crashes

### ISSUE THREAD

**Issue by delon5** [pwn20wndstuff/Undecimus#2016]
**Describe the bug**
If an app crashes and you open it no tweaks are injected into it. You have to close the app from the switcher and open it again for tweaks to be injected.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: X
 - unc0ver Version: 5.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by SarKaa** [comment]
Try ldrestarting, because this happens with my activator, every noe and then, it says substrate is disabled, and only gets fixed when I ldrestart

**Comment by delon5** [comment]
found out that this is a feature when substitute replaced substrate in unc0ver
