### ISSUE TITLE
[Bug] Unable to search iOS updates after restoring RootFS

### ISSUE THREAD

**Issue by noeXzTi** [pwn20wndstuff/Undecimus#2038]
**Describe the bug**
After jailbreaking my device and then restoring RootFS with “Disable Auto Updates” option unselected, I am unable to search for iOS updates (it displays the “An error occurred while checking for a software update” error).

**To Reproduce**
1. Open unc0ver
2. Jailbreak your device
3. Open unc0ver again
4. Select the “Restore RootFS” option with everything else unselected.
5. Restore RootFS.
6. After unc0ver has finished, go to Settings > General > Software updates to try to search an update, and you will face that you cannot find for updates.

**Screenshots**
None.

**Device (please complete the following information):**
 - iOS Version: iOS 13.5 (Stable, 17F75)
 - iOS Device: iPhone 8 (iPhone10,4)
 - unc0ver Version: 5.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
None.

**Comment by tdreams2** [comment]
Re-Jailbreak

Toggle disable software updates ON ( It's a bug) ON = OFF actually

You should see check for updates it works
Restore FS

**Comment by noeXzTi** [comment]
Hey @tdreams2,

Yeah it seems to be working that way. Thanks!

This bug should be fixed, as it may cause confusion.

**Comment by sameermogallur** [comment]
Still isn't working for me. Any other ways to update?

**Comment by tdreams2** [comment]
> Still isn't working for me. Any other ways to update?
@smog25
1 - Make sure you have the latest Unc0ver release 5.3.1 
2 - Jailbreak 
3 - Toggle disable software updates ON
4 - Jailbreak again
5 - Toggle disable software updates OFF
6 - Jailbreak one more time
7 - Test if you can see IOS updates before you RootFS
8 - If updates are available check RootFS. If not try to toggle disable software updates ON
9 - Jailbreak

**Comment by Hamlock-maneuverr** [comment]
Everything tdreams2 said is correct except for the version.  You need to use 5.3.1

**Comment by tdreams2** [comment]
> Everything tdreams2 said is correct except for the version. You need to use 5.3.1

@Hamlock-maneuverr 
You are right!. I thought this repository is maintained.
Do you know where are the latest releases hosted other than the Unc0ver website?

**Comment by Hamlock-maneuverr** [comment]
Sorry,  I don't think that's public information.  Only unc0ver.dev
