### ISSUE TITLE
afc2 (Apple File Conduit 2) not working 

### ISSUE THREAD

**Issue by m37h-aga1n** [pwn20wndstuff/Undecimus#204]
Apple File Conduit "2" (arm64/KPPLess) broken on last few updates of uncover and substrate. Many people doesn't have this issue but just a few. Root dir(raw file system/var) cannot be accessed on PC and MAC over usb with ifunbox or imazing tool.(these tools read phone as jailed,but it shouldn't because of this afc2 tweak). Tried all sort of things before posting this issue. iphone X 114b3 using final unc0ver 2.1.0. and 
latest substrate -7020. re-instaling afc2,uninstalling it, cleaning with icleaner pro, installing it again, removing ifunbox from pc and installing it again,removing all sites blocked in host file. In the end i used rootFS option in uncover and it didn't even work on substitude before i updated to substrate again. So it is till not working. I always jailbreak my device with "reload system daemons" switch on in u0.All was working great on substrate -7000 but now when i downgrade substrate it doesn't. Tried all cables and usb ports too.Any info about this would be greatly appreciated,thank you.
p.s. contacted respective developers of the tweak about the issue as well.
EDIT: downgrading substrate and/or unc0ver doesn't help.

**Comment by coenkcore** [comment]
i have same issue with AFC2 with unc0ver v.2.1.0, root folder cannot be display using iExplorer on MAC, on unc0ver v.2.0.2 AFC2 is working properly.
iP6S iOS 11.2.6

**Comment by m37h-aga1n** [comment]
@coenkcore well it was working at some point on 210 u0 for me i just don't remember which pre-release from which day,gonna test with 202 later today...

**Comment by 61Halim** [comment]
Same here, any fix for AFC 2

**Comment by me246813579** [comment]
Update Link Identity Editor to the latest version
