### ISSUE TITLE
App Switcher : Non Responsive/Lagging

### ISSUE THREAD

**Issue by romanadam91** [pwn20wndstuff/Undecimus#2041]
**Describe the bug**
The app switcher lags and freeze and also takes time to close the apps. The app switcher works pretty fine if I restart the device and don't re-jailbreak the device but still comes up if I re-jailbreak. I can make the video and share if required. Please look into this. Thanks you so much for the support.

**To Reproduce**
1. Install unc0ver 5.0.1
2. Once done, open multiple apps
3. Try to switch between apps from app switcher or try to close
4. The screens will lag or freeze and won't close the apps either on time

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPhone X
 - unc0ver Version: 5.0.1

**Place an "x" between the brackets if true:**
(Didn't check the blank ones)
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by noeXzTi** [comment]
Try to boot to Safe Mode and then test again. If it doesn’t lag, then uninstall your tweaks.
