### ISSUE TITLE
Jailbreak still detected after restoring RootFS

### ISSUE THREAD

**Issue by mrbonkerz** [pwn20wndstuff/Undecimus#2042]
**Describe the bug**
Citibank SG still detects devices is jailbroken even after restoring RootFS.

**To Reproduce**
1. Open unc0ver
2. Select the “Restore RootFS” option with everything else unselected.
3. Restore RootFS.
4. Launch Citibank SG
**Screenshots**
none

**Device (please complete the following information):**
 - iOS Version: iOS 13.5
 - iOS Device: iPhone X
 - unc0ver Version: 5.0.1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
none

**Comment by gummykage** [comment]
Did you reinstall the app after restore Rootfs? Apps usually leave a hidden setting to remember jailbreak was detected.

**Comment by mrbonkerz** [comment]
> Did you reinstall the app after restore Rootfs? Apps usually leave a hidden setting to remember jailbreak was detected.

I tried reinstalling and resetting all settings. the app still detects.

**Comment by mrbonkerz** [comment]
got it fixed by running icleaner

**Comment by Jib128** [comment]
@mrbonkerz how exactly did you run icleaner if you restored rootfs? Did you jailbreak again, use icleaner, then restore rootfs?

**Comment by mrbonkerz** [comment]
> @mrbonkerz how exactly did you run icleaner if you restored rootfs? Did you jailbreak again, use icleaner, then restore rootfs?

Yes, run icleaner in jailbroken state then restore rootfs.
