### ISSUE TITLE
iPhone XS Booting Issues using v5.0.1

### ISSUE THREAD

**Issue by tvieira20** [pwn20wndstuff/Undecimus#2051]
**Describe the bug**
iPhone XS sometimes can't boot after jailbreaking using latest unc0ver (5.0.1). The issue was gone after I downgraded to v5.0.0. I tried to reinstalled Cydia - same issue (after restoring rootfs iPhone couldn't boot properly - it was taking around 2 minutes to boot), Formated my iPhone and then I jailbreaked it with a clean copy os iOS 13.5 - same issue. There's something going on here that is now present in the latest unc0ver that wasn't in the inicial release

**To Reproduce**

1) Jailbreak using unc0ver v5.0.1
2) Black screen --> there's my issue

It only boots normally after a Hard Reset. It also boots if the "Load Tweaks" option is disabled - keep in mind that I formatted my iPhone and got a clean install and the issue was still there (leading me to think that it isn't a tweak problem)

**Screenshots**
---

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPhone XS
 - unc0ver Version: 5.0.1 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
---

**Comment by ryanspencer0** [comment]
If you think a tweak caused this issue you're probably right, even if you restore rootfs it doesnt delete everything that was installed via cydia sileo or whatever you used to install. The only way to do that would be to completely restore your iphone using a backup or just fresh.
If thats not what you wanted you could always search through filza looking through jailbreak files and manually delete old tweak files that could be potentially corrupting your jailbreak.
Restorerootfs is useful but it doesnt always work in relation to a corrupted jailbreak. I had same issue and i gave up searching for such files restoring (by nature) removes basically everything and gives you fresh ios files

**Comment by burakk1hunna** [comment]
yeah im having the exact same issue on my iphone 11. everytime this happens i just restorerootfs and download all my tweaks again and it happens everyday. plz find a fix

**Comment by tvieira20** [comment]
> yeah im having the exact same issue on my iphone 11. everytime this happens i just restorerootfs and download all my tweaks again and it happens everyday. plz find a fix

Try to download [unc0ver v5.0.0 IPA](https://github.com/pwn20wndstuff/Undecimus/releases/download/v5.0.0/unc0ver-v5.0.0.ipa) and install it using AltStore. For now it fixed the issue

**Comment by reemhq** [comment]
Unsubscribe
