### ISSUE TITLE
cynject not supported on iOS 12

### ISSUE THREAD

**Issue by liuxuan30** [pwn20wndstuff/Undecimus#206]
Hi there,

Just want to ask, will dumpdecrypted.dylib work on unc0ver (maybe not now, but is it possible in future)?

And, I'm also interested in why dumpdecrypted.dylib stopped working. Can someone explain what's the difference between old JB and the new one? Thanks in advance

**Comment by Cryptiiiic** [comment]
Use [bfdecrypt](https://github.com/BishopFox/bfdecrypt/raw/master/bfdecrypt.dylib) + substrate's cynject.

**Comment by liuxuan30** [comment]
@Cryptiiiic can they work with 'load tweak' enabled mode?

**Comment by Cryptiiiic** [comment]
@liuxuan30 I haven't tried it yet but pwn told me to use it. You were able to use inject_criticald and inject_library with tweaks enabled and cynject is part of substrate(made by saurik) so wouldn't it be better to try it instead of asking.

**Comment by liuxuan30** [comment]
@Cryptiiiic  the truth is I don't know how to get started.. though I know how to code, but I don't have the knowledge how to put what you said together :(
wanted to learn, but I don't find any doc or guide on this topic.

**Comment by liuxuan30** [comment]
@Cryptiiiic but you have to disable load tweaks right? Do you know why? 

I'm kind of want to write a daemon process to execute the shell cmds to dump the apps, but disabling tweaks would kill my daemon.

previously I can use dumpdecrypted.dylib and my daemon at the same time.

**Comment by Cryptiiiic** [comment]
@liuxuan30 no you don't at all. Why would you have to disable them. Saurik makes his injector properly unlike coolstar and his inject_criticald.

**Comment by liuxuan30** [comment]
wow that's fantastic. Thanks! closing.

**Comment by useignition** [comment]
I understand this is closed now however when trying to inject into an app the app crashes.

**Comment by flockoffiles** [comment]
Tried to use cynject on iOS12 (with unc0ver). The app crashes:
```
cyinject 871 /usr/lib/bfdecrypt.dylib 

_krncall(mach_vm_read_overwrite) =10000003
```

**Comment by victor1342** [comment]
> 
> 
> Tried to use cynject on iOS12 (with unc0ver). The app exits with an error:
> 
> ```
> cyinject 871 /usr/lib/bfdecrypt.dylib 
> 
> _krncall(mach_vm_read_overwrite) =10000003
> ```

I get exactly the same thing.

**Comment by liuxuan30** [comment]
reopen - @Cryptiiiic can you help?

**Comment by useignition** [comment]
Any updates? @pwn20wndstuff

**Comment by jakeajames** [comment]
Cycript works fine after the latest update for me. Make sure to install cycript from Elecubratus.

**Comment by Cryptiiiic** [comment]
Closing, use substitute-inject on substitute. Bingner updated cynject for substrate.
