### ISSUE TITLE
iPhone overheating and apps freezing/closing

### ISSUE THREAD

**Issue by Casinopolis** [pwn20wndstuff/Undecimus#2085]
After upgrading to iOS 13.5 and performing unc0ver jailbreak, my iPhone overheats and many apps keep crashing/freezing/closing.

I have changed my battery in a Apple Store (official) and its life is 100%. The battery isn't the problem. If I turn off the phone (in order to "stop" the jailbreak), this issue doesn't exist. If I turn off all the tweaks via iCleaner, the problem keeps happening.

Any help, please? 

 - iOS Version: 13.5
 - iOS Device: iPhone 7
 - unc0ver Version: 5.2

**Comment by ghost** [comment]
I can't hit fail

**Comment by ghost** [comment]
> After upgrading to iOS 13.5 and performing unc0ver jailbreak, my iPhone overheats and many apps keep crashing/freezing/closing.
> 
> 
> 
> I have changed my battery in a Apple Store (official) and its life is 100%. The battery isn't the problem. If I turn off the phone (in order to "stop" the jailbreak), this issue doesn't exist. If I turn off all the tweaks via iCleaner, the problem keeps happening.
> 
> 
> 
> Any help, please? 
> 
> 
> 
>  - iOS Version: 13.5
> 
>  - iOS Device: iPhone 7
> 
>  - unc0ver Version: 5.2
> 
> 
> 
> 
> 
>

**Comment by Casinopolis** [comment]
It somehow stopped overheating.
