### ISSUE TITLE
Throw up a warning on LPM.

### ISSUE THREAD

**Issue by chxseh** [pwn20wndstuff/Undecimus#2086]
**Describe the feature you'd like**
You can notify a user that has LPM on to disable it (as afaik, you can't jailbreak with it enabled)

**Additional context**
Here's a blog post about it: https://useyourloaf.com/blog/detecting-low-power-mode/

```
// Swift
if NSProcessInfo.processInfo().lowPowerModeEnabled {
  // stop battery intensive actions
}

// Objective-C
if ([[NSProcessInfo processInfo] isLowPowerModeEnabled]) {
  // stop battery intensive actions
}
```

**Comment by Hamlock-maneuverr** [comment]
my XS max jailbreaks just fine with LPM enabled.

**Comment by chxseh** [comment]
Weird. Must’ve taken me 10 attempts with Airplane Mode on + No siri.
