### ISSUE TITLE
OYO app not working

### ISSUE THREAD

**Issue by romanadam91** [pwn20wndstuff/Undecimus#2098]
**Describe the bug**
OYO app (Hotel Booking app) not working in Unc0ver jailbreak. I tried liberty, tweak manager, tweak restricter, and finally unsub which worked in the first few seconds and then detected jailbreak again. Please help me to get this fixed or if anyone can get the detection code fixed or any tweak to get it worked. Thanks in advance.

**To Reproduce**
1. Install OYO app
2. Open it 
3. Jailbreak detected

**Screenshots**
(https://user-images.githubusercontent.com/64604081/88150622-40b6dd80-cc1f-11ea-89da-79e9cae60517.jpg)

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPhoneX
 - unc0ver Version: 5.2.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Comment by Hamlock-maneuverr** [comment]
Thats not an unc0ver thing.  Thats a jailbreak detection thing.  Some apps just can't be bypassed.
