### ISSUE TITLE
[BUG] Missing /var/log/dpkg causes Cydia installs to fail cydo error 2

### ISSUE THREAD

**Issue by badger200** [pwn20wndstuff/Undecimus#2099]
This bug has existed forever. The workaround is you need to manually recreate /var/log/dpkg. Your /tmp/cydia.log last 20 lines should reveal this also.

I suspect iOS purges most/all of /var/log during very low disk space conditions, which occur to me on a daily basis as my 256GB iPad Pro 9.7’ is always full.

**Comment by jianmingyong** [comment]
Damn, I remember mine was so broken that I thought my update screwed up and I had to restore rootfs and rejailbreak again to fix it.

**Comment by badger200** [comment]
@jianmingyong The default unc0ver sbinger “Elucubratus” repo (whatever tf that means) pushed an update about 4 months ago, to the apt or dpkg packages (I forget which) that fixed this issue by moving the path used to something other than /var/log/dpkg/
