### ISSUE TITLE
Multipath entitlement should not be checked in embedded.mobileprovision

### ISSUE THREAD

**Issue by n3d1117** [pwn20wndstuff/Undecimus#21]
I'm referring to [this line](https://github.com/pwn20wndstuff/Undecimus/blob/1683c0728520b1db8188a3c2128fedc4794842d3/Undecimus/SettingsTableViewController.m#L268).

Some signing services distribute the .ipa without an embedded mobileprovision, so the check fails, but the actual app binary is correctly signed with multipath entitlement.

The entitlement should instead be checked directly at runtime (maybe [this project](https://github.com/matsmattsson/apple-runtime-entitlements) can help?) in order to avoid this issue.

**Comment by J0113** [comment]
I thought Unc0ver did not do drama (unlike a well know jailbreak...). But than why are you guys blocking AppDB (and some other signing software)? It is easy fixable, appDB has done nothing wrong, their system is just not build like Unc0ver expects to.
