### ISSUE TITLE
[Solved] Freezing Latest v2.1.0-2 , solution posted in comments 

### ISSUE THREAD

**Issue by ios11iphone6s** [pwn20wndstuff/Undecimus#212]
First Release of v2.1.0 is successfully installed no Problems,

The Latest Release of v2.1.0 is Freeze at 1/40 and suddenly Respring done. Tweaks working but all apps freezing including unc0ver.

Freezing in every application and every jailbreak tries.

iPhone 6S. iOS 11.3.1

I tried Tweakbox MP, jailbreaks.fun EL , both are freezing.

**Comment by ZerOneX** [comment]
exactly... the 2.1.0-1 was perfect for me also

the 2.1.0-2 does not work

**Comment by ios11iphone6s** [comment]
> exactly... the 2.1.0-1 was perfect for me also
> 
> the 2.1.0-2 does not work

After Jailbroken_Respring done, Keep airplane mode TURN ON.
Don't open any application, Wait for 2mins.
Then, 
open CYDIA and uninstall every Tweak after you installed/updated saurik's Substrate. (or) Uninstall every Tweak that you doubt that causing trouble.

Done., clean with iCleanerPro 

Everything is fine now, I removed begoneCIA Tweak. :)

**Comment by ZerOneX** [comment]
realized that my problem is different than yours... posted a video yday... very very strange... it does not go into a jailbroken state
