### ISSUE TITLE
Jailbreak fails with pspawn error Bad executable or Tweaks not Loading after Installing Substrate (all versions)

### ISSUE THREAD

**Issue by Wanqed** [pwn20wndstuff/Undecimus#214]
The issue started off on Unc0ver 2.0.2 I installed Substrate 9.7.000 and Tweaks didn’t load so I said “I’ll just wait for updates” I downloaded Unc0ver 2.1.0 because In patches it said it fixed said problem, and also waited to install Substrate for a little but I installed all versions up to 9.7.020 and still no Tweaks are being loaded, I’ve Restored RootFS multiple times and downloaded Substrate as first thing after all necessary updates and then installed a tweak to see if it’d work but still no luck.

**Comment by 0000vt** [comment]
What iOS version are you on?

**Comment by Wanqed** [comment]
@0000vt iOS 11.3 , iPhone 6S

**Comment by atifchy** [comment]
@wanqed install substrate from saurik’s repo, remove electra repos, restart and rejailbreak. If it doesn’t work then use restore rootfs option from unc0ver setting.

**Comment by Wanqed** [comment]
@atifchy so far I have Restored RootFS atleast 12 times because after I upgrade to Substrate after restoring RootFS it doesn’t let me install or downgrade or uninstall anything error (255) says something with /libexec/cydia/cydo

**Comment by 0000vt** [comment]
You could try a futurerestore to the same ios version, or 11.3.1. I also had a lot of trouble with substrate on 11.1.2, but it was fixed after an upgrade to 11.3.1

**Comment by Wanqed** [comment]
@0000vt I currently have no access to WiFi nor a computer as of right now because of my internet provider messing everything up with the bills. I looked at my cydia today and I realized I have BOTH Substrate and Substitute installed after my Restore RootFS last night and I’m confused? But everything works fine? But it also tells me to upgrade Substrate in notifiers..

**Comment by Wanqed** [comment]
Now everytime I upgrade to Substrate (Any Version) and try to install or downgrade Substrate itself I get “Sub-process “/usr/libexec/cydia/cydo has returned an error code (255)” @Saurik @Pwn20wnd I have no idea what’s happening

**Comment by BiasShadow** [comment]
I occasionally get the same error. I usually try Re-jailbreaking and the sub process error goes away. If you have Substitute installed, you should be seeing the Dummy version of Substrate. Now according to your issue, it seems rejailbrekaing doesnt help, correct?  If thats the case, so I can understand the issue a little better and the options at hand, just answer the following regardless if its been asked above.

Have you attempted to install updates with tweaks disabled in Unc0ver?

Have you attempted to refresh sources (probably yes)? If so, have you attempted to re-add any of the sources?

Are you attempting to upgrade all packages at once? With other packages? One by one?

Does this happen to all packages or only certain packages?

Any other methods you have tried?

Any other details you can provide would help a lot.

**Comment by vitalik2187836** [comment]
> Now everytime I upgrade to Substrate (Any Version) and try to install or downgrade Substrate itself I get “Sub-process “/usr/libexec/cydia/cydo has returned an error code (255)” @saurik @pwn20wndstuff I have no idea what’s happening

I have exectly the same situation. I have iPhone 6s on IOS 11.3 and nothing works with substrate 0.9.7 and up but everything work just fine with substrate dummy and substitute. I also have 255 error with new substrate.

**Comment by Wanqed** [comment]
I decided to leave Substrate alone up until now, I decided to upgrade it once again. No change at all, it’s still the same. Once I respring, restart device rejailbreak device not one tweak loads. None of them decide to load.

**Comment by vitalik2187836** [comment]
Did the same right now - same result.

**Comment by ItzColdOutside** [comment]
> I decided to leave Substrate alone up until now, I decided to upgrade it once again. No change at all, it’s still the same. Once I respring, restart device rejailbreak device not one tweak loads. None of them decide to load.

Any resolution yet? Recently jailbroken (X on 11.3.1) and get the 255 error code. Can't upgrade existing or install new tweaks.

**Comment by Cryptiiiic** [comment]
@Wanqed @BiasShadow @vitalik2187836 @ItzColdOutside Use 3.0.0. b12 then post unc0ver diagnostics.

**Comment by vitalik2187836** [comment]
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2829717/diagnostics.zip)
hope this helps

**Comment by Wanqed** [comment]
@cryptiiiic I just used b13 and I am getting bootstrap error. I’ve used every version from 2.2.2 up to 3.0.0b13 and I always get bootstrap error

Diagnostics - https://pastebin.com/1FDmC2FA

**Comment by vitalik2187836** [comment]
Wanqed, same.

**Comment by vitalik2187836** [comment]
@Cryptiiiic I have done this many times. If I try to update substrate to 0.9.7 from 0.9.6 dummy on uncover 2.1.4 and down my tweaks will stop working. But I can't install uncover version 2.2.0 and up at all! It gives an error about substrate.deb or dpkg.deb, depends on the try of installing jailbreak. On the first try it gives me an error about substrate.deb (after that I can't open any apps (system and appstore too) until reboot), on the second try (after reboot) and later on it gives me an error about dpkg.deb (and I can open apps (not jailbreak ones)). 
But if I restore rootfs and install 2.1.4 version everything works fine.

**Comment by sbingner** [comment]
If you're having this error please try with the attached ipa inside a zip (don't ask - github wouldn't take it otherwise) - this is caused by your volume up button being stuck or something similar.  Saurik will probably provide a proper fix later but this should work around it for now.

[Undecimus.zip](https://github.com/pwn20wndstuff/Undecimus/files/2831325/Undecimus.zip)

**Comment by vitalik2187836** [comment]
I haven't tried it yet but you are right, my volume up button isn't working! I'll try it later, thank you

**Comment by vitalik2187836** [comment]
@sbingner it works! I had some error in uncover about substrate while installing this version but then I tried to launch cydia and it opened. I installed some tweaks and they work now. Finally! Thank you very much guys you are awesome.

**Comment by Cryptiiiic** [comment]
@Wanqed can you try the ipa up there and post diagnostics.

**Comment by Wanqed** [comment]
@cryptiiiic yes I’ve had that ipa signed for about a week now, I was talking with Sam over discord about the issue. It works fine now thank you guys :)

**Comment by sbingner** [comment]
Keeping this open until we have a substrate update that fixes it.

**Comment by vitalik2187836** [comment]
Hello. Can you please update this fix to beta 39. I have updated my iPhone to iOS 12.1.1 and now have this problem again.
