### ISSUE TITLE
Can't install it through Xcode because it requires MultiPath?

### ISSUE THREAD

**Issue by me246813579** [pwn20wndstuff/Undecimus#215]
Hello,

I have modified Main.storyboard in Xcode, and would like to try it out on my device. However, I do not have a developer account, and so it won't let me sign it because of a MultiPath requirement. Is there any way to use Xcode to install it without having a developer account?

**Comment by Samgisaninja** [comment]
so then disable the multipath entitlement in xcode? or use make?
