### ISSUE TITLE
Unalble to Log Into or Access iTunes Store, App Store, or Apple Music.

### ISSUE THREAD

**Issue by Starwarsfan2099** [pwn20wndstuff/Undecimus#2211]
**Bug**
Several people recently, including myself have been experiencing an issue where Unc0ver is the only common denominator. As of this week, several iOS versions appear to be unable to connect to Apple ID or iTunes services. This has happened to many on several iOS versions, including myself, when any tweaks have not been installed or uninstalled in weeks. Initially, Apple Music failed to play songs, failing simply with the error "cancelled". AppStore would also fail to update or install apps with no error reported. I attempted to sign out of iCloud, as well as iTunes and AppStore and sign back in. iCloud successfully can be logged into. However, going to `iCloud` > `iTunes and AppStore` and attempting to login fails. The correct information is provided, the sheet stating `Signing into iTunes and AppStore` appears, the sheet then disappears, nothing happens, and the cell still reads `Off`. Signing in via the `iTunes and AppStore` further down in the preferences (Not under iCloud) results in no information sheet, and no error, only still saying `Sign In`. Attempting to sign in via the AppStore yields the error `Could Not Sign In`. Attempting to update/install apps results in a Apple ID password prompt, and then no error. The app does not install, the loading wheel simply goes away. Attempting to login via the iTunes app yields no error. All the sign in methods mentioned here will still display if the wrong password has been entered, therefore the error is occurring after authentication. All errors persist across hard reboots. All errors persist whether jailbroken or unjailbroken. All errors persist with `Load Tweaks` enabled or disabled. All errors persist with `Reload Daemons` enabled or disabled. All error persist with tweak injection into all LaunchDaemons disabled via Choicy. All errors persist after hard reboot - Unjailbroken - Network Settings Reset - and connected only over LTE. 

I have not tested yet, but another user claims that performing a RootFS restore than `Erase all Content and Settings` fixes the issue, however, after jailbreaking with Unc0ver again, the issue reappears. [Source](https://www.reddit.com/r/jailbreak/comments/kwwoye/help_cannot_login_to_app_store_jailbreak_issue/gjsj7k6?utm_source=share&utm_medium=web2x&context=3) The issue was also reported by a user in the Jailbreak Discord yesterday who had Unc0ver, performed only a RootFS restore, and the issue did in fact still persist.

Reddit threads about the issue:

https://www.reddit.com/r/jailbreak/comments/kwwoye/help_cannot_login_to_app_store_jailbreak_issue/
https://www.reddit.com/r/jailbreak/comments/kz1pc6/help_could_not_sign_in_to_appstore_cant_download/

**To Reproduce**
1. Jailbreak with latest Unc0ver on iOS 11.3.1.
2. Sign out of Apple ID services when they fail in Apple Music and the AppStore.

**Device:**
 - iOS Version: 11.31
 - iOS Device: iPhone 7 Plus GSM
 - unc0ver Version: 5.2.0 (Also tested, version 4.3.1)

**Place an "x" between the brackets if true:**
 - [ X] this is a bug others will be able to reproduce
 - [X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [  ] this issue is present after a rootfs restore 
 - [ X] this issue is present on the latest version of unc0ver

**Logs**
AppStore error: `Could not sign in`.
iTunes error: `Unable to connect to iTunes store`. (Has been reported)
Settings App error: No error is printed at all.

Output of `launchctl list | grep itunes`:

```
406 -9 com.apple.itunnesstored
17438 -44 com.apple.itunescloudd
```

as well as 

```
18558 -9 com.apple.itunnesstored
18720 -9 com.apple.itunescloudd
```

Reloading both of the LaunchDaemons has no effect, although the status/exit code becomes 0. 

Some more logs with errors from `accountsd` while attempting to sign in:

```
Jan 18 10:43:56 AJs-iPhone trustd(libnetwork.dylib)[113] <Error>: nw_connection_get_connected_socket 144 Connection has no connected handler
Jan 18 10:43:56 AJs-iPhone trustd(CFNetwork)[113] <Error>: TCP Conn 0x10535e210 Failed : error 0:61 [61]
Jan 18 10:43:56 AJs-iPhone trustd(libnetwork.dylib)[113] <Notice>: 0.011s [144.1 A5A08D78-B44A-45E3-A2B0-EC5EB6F334AA 127.0.0.1:49943-><private> socket-flow] flow:failed_connect Error Domain=kNWErrorDomainPOSIX Code=61 "Connection refused" UserInfo={NSDescription=Connection refused}
Jan 18 10:43:56 AJs-iPhone trustd[113] <Notice>: Open failed: Error Domain=com.apple.utilities.sqlite3 Code=14 "finalize: 0x105747590: [14]2 unable to open database file" UserInfo={NSDescription=finalize: 0x105747590: [14]2 unable to open database file, NSUnderlyingError=0x10536def0 {Error Domain=com.apple.utilities.sqlite3 Code=14 "step: [14]2 unable to open database file" UserInfo={NSDescription=step: [14]2 unable to open database file}}}
Jan 18 10:43:56 AJs-iPhone trustd[113] <Notice>: opened block failed: Error Domain=com.apple.utilities.sqlite3 Code=14 "finalize: 0x105747590: [14]2 unable to open database file" UserInfo={NSDescription=finalize: 0x105747590: [14]2 unable to open database file, NSUnderlyingError=0x10536def0 {Error Domain=com.apple.utilities.sqlite3 Code=14 "step: [14]2 unable to open database file" UserInfo={NSDescription=step: [14]2 unable to open database file}}}
Jan 18 10:43:56 AJs-iPhone trustd[113] <Notice>: _SecOCSPCacheAddResponse failed: Error Domain=com.apple.utilities.sqlite3 Code=14 "finalize: 0x105747590: [14]2 unable to open database file" UserInfo={NSDescription=finalize: 0x105747590: [14]2 unable to open database file, NSUnderlyingError=0x10536def0 {Error Domain=com.apple.utilities.sqlite3 Code=14 "step: [14]2 unable to open database file" UserInfo={NSDescription=step: [14]2 unable to open database file}}}
Jan 18 10:43:56 AJs-iPhone accountsd(CFNetwork)[90] <Error>: Task <5F581416-F8F4-4426-8424-7C3CAEF44EA0>.<2> HTTP load failed (error code: -999 [1:89])
Jan 18 10:43:56 AJs-iPhone accountsd(CFNetwork)[90] <Error>: Task <5F581416-F8F4-4426-8424-7C3CAEF44EA0>.<2> finished with error - code: -999
Jan 18 10:43:56 AJs-iPhone accountsd(iTunesAccountsAuthenticationPlugin)[90] <Error>: iTunesAccountsAuthenticationPlugin: [45A4261A] Unable to set cookies because we have no auth response.
Jan 18 10:43:56 AJs-iPhone accountsd(iTunesAccountsAuthenticationPlugin)[90] <Error>: iTunesAccountsAuthenticationPlugin: [45A4261A] Failed to authenticate the account. error = <private>
Jan 18 10:43:56 AJs-iPhone accountsd(iTunesAccountsAuthenticationPlugin)[90] <Error>: iTunesAccountsVerifyCredentialsResponse: [45A4261A] Authentication failed, but we aren't allowed to run it again.
Jan 18 10:43:57 AJs-iPhone assistantd[24] <Error>: -[ADCommandCenter(Metrics) _metrics_sendMetricsToServerUntilLimit:requiresUnlimitedPower:requiresActiveSession:purgesOversizedStorage:completion:] Skipped sending metrics to server because the session is not active.
```

I can provide other logs, output, and errors if need be. 

Thank you.

**Comment by jordammit** [comment]
Also having this exact same issue. It happens when not in jailbroken state as well. Everything else iCloud seems to work, just cannot sign into App Store and Apple Music. Login always fails. Everything works on my iPhone 6 Plus with yalu102, so I'm supposing it has something to do with unc0ver, granted that restoring RootFS seems to be the fix a couple of people have found successful, and like you mentioned, once you jailbreak with unc0ver again the connection seems to fail.

**Comment by Starwarsfan2099** [comment]
Solution has been found. Disable "Block Revokes" in the Unc0ver settings. Apple changed stuff on their end and this option was causing the device to be unable to connect to Apple's servers for the AppStore and Apple Music.
