### ISSUE TITLE
Fingerprint in AppStore not showing up

### ISSUE THREAD

**Issue by swaggyP36000** [pwn20wndstuff/Undecimus#222]
I have no tweaks installed, and I just ran rootFS and am currently jailbroken without installing any tweaks, but no matter what I do, I keep having to type my iCloud password instead of being able to use my fingerprint like I have set it up. While you try to fix, I’m gonna try a few different things and see if I can find a temporary solution. Thanks for your help in advance!

Oh, and I’m currently on iOS 11.2.1 using unc0ver v2.1.0

**Comment by Cryptiiiic** [comment]
@swaggyP36000 post diagnostics

**Comment by Cryptiiiic** [comment]
@swaggyP36000 in unc0ver, in the settings tab, there's a share diagnostics button.

**Comment by swaggyP36000** [comment]
[Diagnostics (inside).zip](https://github.com/pwn20wndstuff/Undecimus/files/2751367/Diagnostics.inside.zip)

Here are the diagnostics. This is the best way I could think of sharing the file

**Comment by Cryptiiiic** [comment]
@swaggyP36000 you have so much piracy. Pirated packages tend to be corrupt and break your device/jailbreak. Also you do have many tweaks, what do you mean "without installing any tweaks". Also when you rootfs restore, you have to re-add your fingerprints. I doubt this has to do with unc0ver.

**Comment by swaggyP36000** [comment]
Oops, I installed a bunch of tweaks after I posted this...

Technically I only pirated a few of those tweaks. I just use the repositories I do because I forget where to find certain tweaks. No point in arguing that here.

Thanks @Cryptiiiic
