### ISSUE TITLE
Xcode does not works pac device ios 14.3 JB

### ISSUE THREAD

**Issue by Andre85to** [pwn20wndstuff/Undecimus#2227]
**Describe the bug**
Xcode does not deploy anymore after JB.

Xcode: 12.4 
Ios: 14.3
Iphone 11

When the phone is not JB Xcode work perfectly.
When the phone is JB you get the error:
Errors were encountered while preparing your device for development. Please check the Devices and Simulators Window.
or:
Could not start debugserver on "dev name" when trying to launch "app name".

if you reboot the phone ( so no JB) everything work fine

**Comment by wstclzy2010** [comment]
Same problem

**Comment by burakCokyildirim** [comment]
+1

**Comment by burakCokyildirim** [comment]
![image](https://user-images.githubusercontent.com/25784705/111757322-434ffc80-88ac-11eb-9281-c4fe596295ee.png)

> Details
> Failed to start remote service "com.apple.debugserver" on device.
> Domain: com.apple.dtdevicekit
> Code: 811
> Recovery Suggestion: Please check your connection to your device.
> User Info: {
>     DVTRadarComponentKey = 261622;
> }
> 
> The service is invalid.
> Domain: com.apple.dt.MobileDeviceErrorDomain
> Code: -402653150
> User Info: {
>     DVTRadarComponentKey = 261622;
>     MobileDeviceErrorCode = "(0xE8000022)";
>     "com.apple.dtdevicekit.stacktrace" = (
> 	0   DTDeviceKitBase                     0x000000012c236c8f DTDKCreateNSErrorFromAMDErrorCode + 220
> 	1   DTDeviceKitBase                     0x000000012c2465a4 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 613
> 	2   DTDeviceKitBase                     0x000000012c245c70 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
> 	3   DTDeviceKitBase                     0x000000012c238def __DTDKExecuteInSession_block_invoke_2 + 35
> 	4   DTDeviceKitBase                     0x000000012c2384c9 __DTDKExecuteWithConnection_block_invoke_2 + 218
> 	5   DTDeviceKitBase                     0x000000012c2383c6 __DTDKExecuteWithConnection_block_invoke + 106
> 	6   libdispatch.dylib                   0x00007fff202c37c7 _dispatch_client_callout + 8
> 	7   libdispatch.dylib                   0x00007fff202d0605 _dispatch_lane_barrier_sync_invoke_and_complete + 60
> 	8   DVTFoundation                       0x000000010f646cc3 DVTDispatchBarrierSync + 208
> 	9   DVTFoundation                       0x000000010f61dd76 -[DVTDispatchLock performLockedBlock:] + 60
> 	10  DTDeviceKitBase                     0x000000012c2382c7 DTDKExecuteWithConnection + 226
> 	11  DTDeviceKitBase                     0x000000012c238c93 DTDKExecuteInSession + 239
> 	12  DTDeviceKitBase                     0x000000012c245ac2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 131
> 	13  DVTFoundation                       0x000000010f64417e __DVT_CALLING_CLIENT_BLOCK__ + 7
> 	14  DVTFoundation                       0x000000010f645da0 __DVTDispatchAsync_block_invoke + 1191
> 	15  libdispatch.dylib                   0x00007fff202c25dd _dispatch_call_block_and_release + 12
> 	16  libdispatch.dylib                   0x00007fff202c37c7 _dispatch_client_callout + 8
> 	17  libdispatch.dylib                   0x00007fff202c95fe _dispatch_lane_serial_drain + 606
> 	18  libdispatch.dylib                   0x00007fff202ca0fe _dispatch_lane_invoke + 426
> 	19  libdispatch.dylib                   0x00007fff202d3c5d _dispatch_workloop_worker_thread + 819
> 	20  libsystem_pthread.dylib             0x00007fff2046b499 _pthread_wqthread + 314
> 	21  libsystem_pthread.dylib             0x00007fff2046a467 start_wqthread + 15
> );
> }
> 
> 
> 
> System Information
> 
> macOS Version 11.2.1 (Build 20D74)
> Xcode 12.4 (17801) (Build 12D4e)
> Timestamp: 2021-03-19T12:11:37+03:00

If I restart the phone everything is fine

**Comment by wstclzy2010** [comment]
> +1

Just update u0 to 6.1.1 and rejailbreak,it has already solved.

**Comment by burakCokyildirim** [comment]
ok, thank you

**Comment by Andre85to** [comment]
fixed on 6.1.1 as mention by @wstclzy2010
