### ISSUE TITLE
Device doesn't respond to touches

### ISSUE THREAD

**Issue by MrDiamond64** [pwn20wndstuff/Undecimus#2229]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

After jailbreaking, the device no longer responds to touches

**To Reproduce**
1. Jailbreak with unc0ver (any version 6.0.0+)
2. Respring
3. Try to tap on any part of the screen

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 14,2
 - iOS Device: iPhone 8
 - unc0ver Version: 6.1.2

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
https://controlc.com/ac1d44e8

**Comment by MrDiamond64** [comment]
Still doesn't work with 6.1.0

**Comment by MrDiamond64** [comment]
Doesn't work in 6.1.1

**Comment by balenv** [comment]
i have the same problem on a iPhone 7 on iOS 14.1

**Comment by MrDiamond64** [comment]
Still doesn't work with 6.1.2

**Comment by MrDiamond64** [comment]
UPDATE: Looks like this issue is caused by using low quality screen replacements.
