### ISSUE TITLE
"Failed to find shenanigans offset" v2.1.1 iPad 5th 11.3.1

### ISSUE THREAD

**Issue by longhtran91** [pwn20wndstuff/Undecimus#224]
I have been having problem with v2.1.1 and v2.1.0. The version v2.0.2 and below work fine for me.
![img_0004](https://user-images.githubusercontent.com/1468210/51092867-1e0e5380-1762-11e9-930e-9102f5dac47f.PNG)
[diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2753766/diagnostics.plist.txt)

**Comment by RZMiRaN** [comment]
Same issue, iPhone 6+ iOS 11.3 MP
Diagnostics file: https://drive.google.com/file/d/1jycUGgUlsO-tfYXW-UV4I50IrEnJwMgC/view?usp=drivesdk

**Comment by eeesliao** [comment]
Same issue 
#220 
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2754702/diagnostics.txt)

**Comment by eeesliao** [comment]
need 2.0.2 Signing Service

**Comment by Mr-zhaohy** [comment]
same issue, please fix. thx

**Comment by tipsback** [comment]
On 2.1.0 it crashed at 8 or 14 without an error.  2.1.1 yields the above error.  I did come from Electra, but had no issues with 2.0.2 when switching.  The restore root options was used when switching.   Followed the same steps on my 7+ and was successful.  2.0.2 EL works on the first or second try, but 2.1.0 nor 2.1.1 will JB even using the EL or MP.

**Comment by maggiejack** [comment]
same here 826
