### ISSUE TITLE
Can’t install uncover/ isp blocks me from website

### ISSUE THREAD

**Issue by PartyPooper3756** [pwn20wndstuff/Undecimus#2272]
I need to install uncover to restore rootos but I can’t install it again since my isp blocked the website

**Comment by githubcensorshipisreal** [comment]
You are most likely being blocked by the DNS your router/device is using. simply change it to one not being filtered. Try google's 8.8.8.8

**Comment by PartyPooper3756** [comment]
Thank youuu so much
