### ISSUE TITLE
Cydia not updating sources on 956b7ba

### ISSUE THREAD

**Issue by resistor4u** [pwn20wndstuff/Undecimus#229]
Iphone 6s on 11.3.1 with Cydia64 1.1.32~b10. I'm on Undecimus dev branch commit 956b7ba. I did a restore rootfs and reinstall Cydia.

Once opening Cydia, it doesn't seem to complete pulling the sources lists - I've got just an endless red spinner. I'm not even sure Cydia is connecting to anything. (I SSH-ed to the phone, and tried to run `apt` and `apt-get`, but it no-worky because `dyld: Library not loaded: /usr/lib/libapt-pkg.5.0.dylib`.)

Cydia should pull the sources. Am I missing something?

Also, it doesn't appear that saurik's repo was unblocked - or, at least it wasn't added to the sources list in Cydia.app. `/private/etc/apt/sources.list.d` has `cydia.list` but it's a symlink to `/var/mobile/Library/Caches/com.saurik.Cydia/sources.list` which doesn't exist.

**Comment by sbingner** [comment]
Something screwed up your base system.  You can manually download and install the libapt-pkg5.0 deb, if that doesn’t work you could make it try to rebootstrap by removing /.installed_unc0ver and rejailbreaking or restore rootfs.  This isn’t look like a problem with the jailbreak though.  Cydia does use its own internal libapt so it probably should work without that.  I can’t think of any good reason that the Cache wouldn’t have been created by Cydia.  You don’t need to do reinstall cydia if you did restore rootfs as that already includes it.

**Comment by resistor4u** [comment]
putting libapt-pkg5.0 on the phone via sftp works for the CLI, but both re-jailbreaking and restoring rootfs after `rm /.installed_unc0ver` did not fix the Cydia issue. Curious - `dpkg -l` shows these packages installed but unpacked.
```
iU  apt-key                                  1.4.8-3      iphoneos-arm repository encryption key management tool
iU  apt1.4                                   1.4.8-3      iphoneos-arm the advanced packaging tool from Debian
iU  cydia                                    1.1.32~b12   iphoneos-arm graphical iPhone front-end for APT
iU  cydia-lproj                              1.1.32~b1    iphoneos-arm languages and translations for Cydia
iU  essential                                0-1          iphoneos-arm contains nothing, represents everything
iU  libapt                                   1.4.8-6      iphoneos-arm the advanced packaging library from Debian
```
@sbingner would a `dpkg-reconfigure --force` solve this? This still doesn't explain why they weren't done automatically.

**Comment by sbingner** [comment]
There was a bug in my bootstrap.  If you update and try again it should be good.

**Comment by resistor4u** [comment]
bingo dingo
