### ISSUE TITLE
Can’t install apps on latest v2.1.1

### ISSUE THREAD

**Issue by camerontheobald** [pwn20wndstuff/Undecimus#231]
I can’t download any from App Store or ignition tweak box anything so I went and Cydia imapacted unc0ver then disabled everything I still can’t install anything

**Comment by Cryptiiiic** [comment]
@camerontheobald can you share diagnostics in unc0ver (have to be jailbroken first.)

**Comment by camerontheobald** [comment]
I have emailed you the diagnostics but when I’m jailbroken it work and then when I restart(non jailbroken) my phone I can’t install anything I’m not sure if it’s a tweak or the jailbreak itself I just don’t know

**Comment by Cryptiiiic** [comment]
@camerontheobald who did you email, I didn't get an email. Just send the diagnostics while jailbroken.

**Comment by camerontheobald** [comment]
i emailed it to the to the email i got apparently that didn't so how do i share them to you? how do i send you them

**Comment by camerontheobald** [comment]
I did but I have since deleted it and the problem is still present

**Comment by Cryptiiiic** [comment]
@camerontheobald try removing appsynce

**Comment by camerontheobald** [comment]
That didn’t work either
