### ISSUE TITLE
Videosubscriptiond and other Daemons Crashing 

### ISSUE THREAD

**Issue by RunkzCFW** [pwn20wndstuff/Undecimus#233]
It’s causing random Resprings and reboots

**Comment by eeesliao** [comment]
just use the tweak called ByeVSD please google it

**Comment by atifchy** [comment]
Use ByeVSD or Cappd. Cappd is more effective.

**Comment by atifchy** [comment]
https://www.reddit.com/r/jailbreak/comments/aftigx/release_cappd_safely_disable_some_daemons_for_a/
