### ISSUE TITLE
v2.2.0~b2 causing respring loop

### ISSUE THREAD

**Issue by rctfan929** [pwn20wndstuff/Undecimus#236]
v2.0.0~b2 is causing a respring loop.
iPhone 6s 11.3.1

**Comment by mramirez23** [comment]
Yup, I’m getting the same thing. 

iPhone X
iOS 11.3.1

**Comment by yazanalharbi** [comment]
Same thing tried 2.0.0-b2 Caused a respring loop 

IPhone X 
IOS 11.3.1

**Comment by MannerRev** [comment]
Also getting a respring loop on  2.2.0~b2

iPhone 8
iOS 11.3.1

**Comment by m37h-aga1n** [comment]
iPhX 114b3 here,i don't think this is any kind of a loop,just stuck on bootlogo,i excluded noctisXI by deleting it and i don't have stackXI so it must be even more to it,all fine on u0 213 but same thing happened to me on u0 212/211,what is worse, it can be a combo of two or more tweaks which aren't supposed to work on substrate (tweaks made to work on substitude).

**Comment by KMamedoff** [comment]
I have this problem too with v2.2.0~b1 and b2 on my iPhone 7 iOS 11.3.1.

**Comment by Danielperalta07** [comment]
Same problem here, unc0ver v2.2.0~b2 iPhone 6S iOS 11.3.1.
Stuck on respring, already uninstalled anemone, noctisxi and stackxi; since jailbreaking without loading tweaks works fine.

**Comment by atifchy** [comment]
Remove pirate tweaks
Remove limneos tweaks
Remove bolder

**Comment by KMamedoff** [comment]
> Remove pirate tweaks
> Remove limneos tweaks
> Remove bolder

Don’t have any pirated tweaks. Never installed Bolder. Only have Audio Recorder but not going to uninstall that as I am using it every day.

**Comment by pwn20wndstuff** [comment]
This is related to Cydia Substrate tweak incompatibility and it just appeared since v2.2.0 started installing Cydia Substrate

**Comment by m37h-aga1n** [comment]
@pwn20wndstuff so to fix this we need to uninstall substrate incopatible tweaks? i got a long list of tweaks,hard to know for every tweak which is and which is not compatible with substrate,thank you

**Comment by mramirez23** [comment]
How do we distinguish Substrate compatibile tweaks from tweaks that are not?

**Comment by KMamedoff** [comment]
> This is related to Cydia Substrate tweak incompatibility and it just appeared since v2.2.0 started installing Cydia Substrate

I am using Substrate since the first update with unc0ver and I didn’t have this problem before the latest beta.

**Comment by rctfan929** [comment]
@KMamedoff Same

**Comment by Danielperalta07** [comment]
Aparentaly it was iCleaner. After restoring I tried to install it again, and got a dependency error, it was trying to install "APT Transitional". Ivano should look at it soon...

**Comment by KMamedoff** [comment]
> Aparentaly it was iCleaner. After restoring I tried to install it again, and got a dependency error, it was trying to install "APT Transitional". Ivano should look at it soon...

I don't have iCleaner installed and only have those:

- APT (apt-key): 1.4.8-3
- APT 0.7 Transitional (lib): 1:0
- APT 1.4 Strict (libapt-pkg): 1.4.8-4
- APT Strict (lib): 1.4.8-6

**Comment by rctfan929** [comment]
@KMamedoff I think ccsupport is the issue.

**Comment by rctfan929** [comment]
Sent email to developer.

**Comment by Chasewhip8** [comment]
It is not ccsupport as I am running it perfectly fine.

**Comment by mattesorta** [comment]
i don’t have CCSupport, CallBar X only and iCleaner (of the tweak that you mention before), i tried to jailbreak without any of these and it keep giving me boot loop

**Comment by KMamedoff** [comment]
Do you have Watusi?

**Comment by mattesorta** [comment]
this is the list of tweaks! Hope you find a fix!

Il giorno mar 22 gen 2019 alle 12:07 Kenan <notifications@github.com> ha
scritto:

**Comment by mattesorta** [comment]
no i don’t have Watusi

Il giorno mar 22 gen 2019 alle 12:13 Matteo Pastina <matteopas.999@gmail.com>
ha scritto:

**Comment by mattesorta** [comment]
no i don’t have Watusi, sorry but is the first time i’m using GitHub

**Comment by mattesorta** [comment]
could someone DM me so i send you a screenshot of tweaks preferences??

**Comment by mattesorta** [comment]
ok fix, they were: CallBar X, SmartVolumeControl2 and Switches, CallBar X for sure, also Bolders i can confirm it

**Comment by mramirez23** [comment]
@mattesorta

Too bad I don’t have any of these installed. 

CallBar X, SmartVolumeControl2, Switches, and Bolders.

**Comment by Akkavkaz** [comment]
Delete CCModules.

**Comment by KMamedoff** [comment]
Yeap. It is CCModules.
