### ISSUE TITLE
lockdown.cpp:84

### ISSUE THREAD

**Issue by lecoleco** [pwn20wndstuff/Undecimus#237]
Hi,

I get this error on installation.

Error.
file: lockdown.cpp; line 84; what: LOCKDOWN_E_INVALID_SERVICE.

Iphone 7 PLUS

How fix this? Thank you

**Comment by pwn20wndstuff** [comment]
This is related to Cydia Impactor. Make sure that you have its latest version.

**Comment by lecoleco** [comment]
Hi,

Yes the last version of cydia impactor. impactor_0.9.51.dmg

thanks

**Comment by bosscode21** [comment]
I have this problem, too. Could someone please help. 

Thanks
