### ISSUE TITLE
V2.20~b2 rootfs failing

### ISSUE THREAD

**Issue by NebulaMods** [pwn20wndstuff/Undecimus#238]
Issue with restoring rootfs, I have no OTA updates pending. I am also able to jailbreak fine, just want a clean start.

iPhone 7
iOS 11.1.1

![image0](https://user-images.githubusercontent.com/26749185/51484252-6389dc80-1d71-11e9-9629-0c5f67a689c5.png)

Let me know if there is anything else you may need.

**Comment by pwn20wndstuff** [comment]
I know what causes this and I am almost done with the fix.

**Comment by pwn20wndstuff** [comment]
@NebulaMods Can you compile and test the latest developer branch with this change https://github.com/pwn20wndstuff/Undecimus/commit/81672d87d8c08c779e83215a375447948fb377aa?

**Comment by pwn20wndstuff** [comment]
Oh wait, this is a different error... This should have been fixed in v2.2.0~b4!

**Comment by NebulaMods** [comment]
Okay, once it is released I will try it.

**Comment by NebulaMods** [comment]
@pwn20wndstuff I just tried using restore rootfs with the lastest version V2.20~b7 and recieved this error.
![image0 1](https://user-images.githubusercontent.com/26749185/51565655-eb064700-1e68-11e9-95fd-2ef01b1cf8ab.png)

**Comment by NebulaMods** [comment]
This is now fixed and everything seems to working fine.
