### ISSUE TITLE
Unc0ver 2.2.0 b2 DPI Issues

### ISSUE THREAD

**Issue by gnawh** [pwn20wndstuff/Undecimus#241]
Graphical glitches persist after changing DPI of iPX 11.4 b3.

Usually change 1 pixel to fix graphical glitches. System Info will no longer apply new DPI.

Upscale or other DPI changing tweaks successful change resolution, however, they do not remove graphical glitch.

**Comment by Cryptiiiic** [comment]
@gnawh does this still occur on unc0ver 3.0.0 b12

**Comment by gnawh** [comment]
Yes, system info does not save/apply resolution.
