### ISSUE TITLE
Substrate loader crash 

### ISSUE THREAD

**Issue by yazanalharbi** [pwn20wndstuff/Undecimus#243]
Crashed after I tried 2.2.0 b4, failed because of bootloop, went back to 2.1.3 launched cydia and my device completely froze and then rebooted, crash reporter blames substrate loader, do you need me to send you crash logs ? (Also Trust Cashe Injector showed up after trying 2.2.0 b2 and failing) it’s under an unknown source, what should I do with it ?

**Comment by Cryptiiiic** [comment]
@yazanalharbi use unc0ver 3.0.0 b12, post diagnostics and see if it still happens.

**Comment by king4q** [comment]
@Cryptiiiic Saurik is supposed to be working on a fix for this issue. As mentioned by Saurik himself in #165. Please close this issue.
