### ISSUE TITLE
Backboardd spikes 

### ISSUE THREAD

**Issue by yazanalharbi** [pwn20wndstuff/Undecimus#246]
I noticed right after v2.2.0~b5 was successful on CocoaTop backboardd is always 11-15% without me touching anything, it was usually 2-3% always
(Also takes up 5% battery life in settings,is that normal?)

**Comment by spockers** [comment]
I'm getting 0.5-3.4% with occasional spikes to 4% or so. After a minute or two it stays below 1% for the most part.

**Comment by yazanalharbi** [comment]
That should be normal

**Comment by spockers** [comment]
That's on 2.2.0b5, forgot to mention.

**Comment by atifchy** [comment]
Tweak issue

**Comment by yazanalharbi** [comment]
And how would I know what tweak causes backboardd to spike ?

**Comment by spockers** [comment]
Disable half of them with icleaner Pro. You'll then know which half the culprit is in. Rinse and repeat. ;)

**Comment by mattesorta** [comment]
EQE doesn’t work properly, maybe is it
