### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by viiejo** [pwn20wndstuff/Undecimus#25]
Errno: 3 
Test: MACH_PORT_VALID(task_port)
Filename: ViewController.m
Line:215
Function: inject_libary

I get this error when i click jailbreak and it gets around 37/48

**Comment by Cryptiiiic** [comment]
@viiejo please provide us with more information. What iOS are you on and does this happen every time you jaibreak?

**Comment by Cryptiiiic** [comment]
Closing this due to no response after 2 days.
