### ISSUE TITLE
Touch id not working after upgrade to last v2.2.0~b8 (iphone 6s)

### ISSUE THREAD

**Issue by frobali** [pwn20wndstuff/Undecimus#255]
Don´t remember which previous version got installed.
After reboot didn´t work too, downgraded to 1.1.4 and didn´t worked, make upgrade to 2.2 and a RootFS Restore, still not working.

IOS 6.1.2

As i referred, immediately after upgrade, touch id stopped worked.

Any help pls.

Rgds and tks

**Comment by frobali** [comment]
forget to comment... after reboot don´t work too, downgraded to 1.1.4  and didn´t  worked, make upgrade to 2.2 and a RootFS Restore, still not working.

**Comment by atifchy** [comment]
Rollectra full restore might help

**Comment by frobali** [comment]
Can´t do it with Rollectra (IOS>=11.3), mine is 11.1.2
