### ISSUE TITLE
Idea: Built-in jailbreak delay

### ISSUE THREAD

**Issue by JohnLockeNJ** [pwn20wndstuff/Undecimus#257]
It seems that most people have success after waiting, say 5 min, between opening unc0ver and hitting the jailbreak button.  Could you have an option like a “Jailbreak in 5 min” button that when pressed would wait 5 min and then jailbreak?

**Comment by pwn20wndstuff** [comment]
I am slightly against the idea of forcing the user to wait... Will consider anyway.

**Comment by ios11iphone6s** [comment]
or like as Electra, 
Can add cooldown timer feature.

**Comment by king4q** [comment]
Or possibly make it able to be turned on & off via a toggle?

**Comment by k9education** [comment]
Perhaps just add a confirmation dialog that pops up if it has been less than X minutes.  eg "It is recommended you wait X before jailbreaking. Do you want to proceed without waiting?"

**Comment by Samgisaninja** [comment]
I added this during the initial unc0ver beta test (pre public release) and it was reverted, so I seriously doubt it will be approved now
