### ISSUE TITLE
Add the ability to save blobs

### ISSUE THREAD

**Issue by Shengheer** [pwn20wndstuff/Undecimus#260]
Hello guys, thanks for your awesome work and for improving the jailbreak everyday.

I’m requesting if you could add an option to save blobs through Unc0ver JB tool, it will be easier for us to save them and also I’m wondering if you can also add the ability to read blobs to get the nonce and set it automatically to the Boot Nonce field, because every time Unc0ver sign revokes we need to re-type the nonce again.

**Comment by king4q** [comment]
@pwn20wndstuff want to give your opinion? & if not close this?

**Comment by king4q** [comment]
This just needs to be closed. @ Cryptiiiic please close this issue.

**Comment by Cryptiiiic** [comment]
@Shengheer @GeoSn0w Another idea would be to use TSSSaver API. Closing this, reopen if you need to,
