### ISSUE TITLE
Failed to extract Substrate from deb

### ISSUE THREAD

**Issue by tm4dev** [pwn20wndstuff/Undecimus#261]
@Cryptiiiic Hi, sorry, I dont wanna spam but after rootfs restoring, I can not re-jailbreak (not sure which version but b6 or b8 was worked before).
I tried restoring multiple times but still stuck at "Failed to extract Substrate from deb".
Tried "erase all content and settings" + rootfs restoring (b13), thanks.

[diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2800215/diagnostics.plist.txt)

![err](https://user-images.githubusercontent.com/40720093/51803315-49c32a80-2286-11e9-8757-f46049a7f956.jpg)

![22](https://user-images.githubusercontent.com/40720093/51803454-fb169000-2287-11e9-8140-3dff299c4cd0.jpg)

**Comment by pwn20wndstuff** [comment]
Your app installation is corrupted. You should use the latest Pre-Release with the latest Cydia Impactor and reinstall it.

**Comment by tm4dev** [comment]
> Your app installation is corrupted. You should use the latest Pre-Release with the latest Cydia Impactor and reinstall it.

hmm, not sure but I downloaded latest pre-release again, the checksums are same, and I'm using Cydia Impactor v0.9.51
Could you provide the latest pre-release's checksum info to check if it corrupted?
here is mine, thanks for your reply
![2019-01-27 23_54_21-checksum information](https://user-images.githubusercontent.com/40720093/51804109-1afd8200-228f-11e9-93d5-3563394a5d59.png)

**Comment by tm4dev** [comment]
I reinstalled and now it stucks at Failed to extract bootstrap xD
![b66795779302490112_n](https://user-images.githubusercontent.com/40720093/51804491-3fa82880-2294-11e9-8552-f351d1b03ffa.jpg)

**Comment by tm4dev** [comment]
Worked in v2.2.0 b14 and v3 b1 :D thanks!
