### ISSUE TITLE
[Request] provide option "Restore default settings"

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#269]

**Comment by FivePixels** [comment]
Would have loved to PR this! This was an idea I had immediately after submitting my previous one, but the lead developer seems to be more concerned with updating the jailbreak process rather than the UI (even though it's what makes the application not only professional but easier to use and more accessible for users) :/

**Comment by GamingSlimeYT** [comment]
+1 I would really love this idea. It's really simple to create. Just have a button to press and the app force closes and when you reopen the app, it will have all the default settings like when you first downloaded the first time.

**Comment by pwn20wndstuff** [comment]
@FivePixels You are still welcome to PR and I will merge it... I didn’t like your last PR at all and didn’t have time to fix it. That was all.

**Comment by FivePixels** [comment]
@pwn20wndstuff 

> You are still welcome to PR and I will merge it...

I think I've heard that before.

> I didn’t like your last PR at all and didn’t have time to fix it.

If you didn't like the fact that I credited PRs for not only myself, but other contributors (such as Ge0snow and anyone else who has PR'd!) then sure, remove it. If I were really in it to have my name on a credits page, I would have replaced DennisBednarz name, like SamG thought should be done in the first place. But I don't care about credit that much in the first place.

What _fame_ do you think I was expecting by performing a pull request?
Learn how to use open source software. Then I'd love to contribute.

Oh yeah, before I forget - about this: 
> He couldn't do anything properly
> He just renamed functions and made them worse
> I doubt he is a programmer
> I will never merge that

So a pretty crazy thing - I've got a GitHub account! With repositories. Maybe you should look into something and stop being lazy and care about the work you're putting out. If people are willing to contribute to your project you should be professional about the things you are putting out. I understand that you aren't at the point in life where you understand how to handle fame or publicity properly but when someone dedicates time and effort into a project, maybe you could treat them with respect? I'm open for PR denial. What I'm not open for is being told, oh yeah - it'll be merged, for 5 weeks, and then finding out that it never had intentions of being merged.

Hope you took time to read this. Be an adult and understand your actions before they get ahead of you.
