### ISSUE TITLE
Device reboots when powering off.

### ISSUE THREAD

**Issue by MattieThurlow96** [pwn20wndstuff/Undecimus#272]
This issue was fixed in an earlier update, but now, it has been reintroduced.

I’ve noticed this since updating to u0 2.2.0~b13. All other versions seem to be fine.

**Comment by pwn20wndstuff** [comment]
Can anyone confirm if this exists? If so, I probably know why.

**Comment by pwn20wndstuff** [comment]
I am unable to reproduce this... Perhaps, was the unc0ver app still running in the background before you attempted to shutdown?
