### ISSUE TITLE
Feature Request: Re-enable tweaks without rejailbreaking.

### ISSUE THREAD

**Issue by gnawh** [pwn20wndstuff/Undecimus#274]
A lot of substrate/substitute respring loops/issues are mitigated by jailbreaking without tweaks and then running substrate afterwards (including CCSupport). This is helpful when troubleshooting and then testing without having to rejailbreak.

**Comment by wishy-96** [comment]
i would love that too, with alot of tweaks evenually you encounter alot of issues and when troubleshooting its just a nightmare with so many reboots and fails, this feature would be a lifesaver

**Comment by sbingner** [comment]
Just delete /var/tmp/.substrate_disable_loader and run ldrestart and it will do it.  Can’t really do that from unc0ver because it’s sandboxed until it jailbreaks (even after the jailbreak)
