### ISSUE TITLE
Feature Request : User Interface that follows Apple's Design Guidelines

### ISSUE THREAD

**Issue by FivePixels** [pwn20wndstuff/Undecimus#275]
Since I can't do it right (pwn's exact words), I'd like to see a user interface that follows design guidelines and makes sense so the user isn't confused and can understand what each preference means. If you're giving the option to the user they should be aware of what it does.

**Comment by me246813579** [comment]
@FivePixels could you make some sort of mockup for me?

**Comment by FivePixels** [comment]
Oh no, I already completed a pull request, but rather than inform me that it wasn't being implemented at any point I was told it will be implemented _soon_. 

https://github.com/pwn20wndstuff/Undecimus/pull/170

Although this pull says Merged, it was reverted immediately after.
