### ISSUE TITLE
Wifi Passwords List is broken with v2.2.0 Pre-Release

### ISSUE THREAD

**Issue by KMamedoff** [pwn20wndstuff/Undecimus#276]
![photo-2019-01-28-00-52-49](https://user-images.githubusercontent.com/5307981/51928298-0ea03300-240f-11e9-929b-0923fb20cfb8.jpg)

**Comment by yazanalharbi** [comment]
Yup same issue uncover 2.2.0 ~b14 
iPhone X 
iOS 11.3.1

**Comment by ryu16** [comment]
Can you read /private/var/preferences/SystemConfiguration/com.apple.wifi.plist ? It’s wifi settings. Is it broken or lost permissions or something else?

**Comment by ryu16** [comment]
I got it. Mine is “WiFi Passwords 11.0-1”, not your “WiFi Passwords List”. Mine is installed last october when I switched from electra to unc0ver 1.0, and It’s still working fine with unc0ver 2.2. It seems “WiFi Passwords” has been removed from Bigboss, I don’t know why, so you can’t install it from cydia now. Is it legal that I upload “WiFi Passwords” deb created by redeb for you?
If you need your “WiFi Passwords List” fixed, you should contact that tweak’s dev, not here. :)

**Comment by KMamedoff** [comment]
I contacted with the dev. Waiting for a reply.

WiFi Passwords is not removed from BigBoss. I installed it and it has the same problem.

![img_2067](https://user-images.githubusercontent.com/5307981/51980707-47d9b100-24aa-11e9-8618-514617c02c61.PNG)

**Comment by ryu16** [comment]
I’be just realized that cydia won’t list tweak on the repo if one already has a newer version.
Bigboss’s version is 3.0.1 and mine is 11.0-1. I’ve forgotten from which repo I’ve installed. I now downgraded WiFi Passwords to 3.0.1 then it doesn’t work like you. I installed 11.0-1 again then it works.

**Comment by KMamedoff** [comment]
I installed GoodWiFi. It gets the job done.

**Comment by king4q** [comment]
Request for this issue to be closed. @Cryptiiiic
