### ISSUE TITLE
Keep getting Failed to Extract Bootstrap

### ISSUE THREAD

**Issue by rctfan929** [pwn20wndstuff/Undecimus#277]
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2809690/diagnostics.zip)

I keep getting fail to extract bootstrap error while try 2.2.0~b14.
iPhone 6s ios 11.3.1

**Comment by Yoruiop** [comment]
same problem check my issue: [https://github.com/pwn20wndstuff/Undecimus/issues/248](url)

**Comment by troy236** [comment]
same issue. previously on electra, tried 3.0.0b1/2.2.0 and 2.1.3
after rejailbreaking on electra i see a new package installed and the error unc0ver was getting. i cant install any package as it keeps retrying the same package its stuck on. idk how to clear the dpkg cache to stop it trying to install a package that isnt going to install. i checked the unc0ver diagnostics and see the same error in this image.
![img_0370](https://user-images.githubusercontent.com/31560656/52005712-40be9d00-24c2-11e9-8f4f-0c9dc2434a6c.PNG)

**Comment by coenkcore** [comment]
Issue has been fixed on u0 latest release version 2.2.2
Try again using new version of u0 app
