### ISSUE TITLE
iPhone X - 11.4.1 fails to jailbreak 100% of the time

### ISSUE THREAD

**Issue by Rov3r** [pwn20wndstuff/Undecimus#282]
20+ tries, and all have failed. Only have seen one person jailbroken on an X and that was on 11.4.

I also have an iPhone 7 Plus on 11.4.1 and it has failed every time as well.

Let me know if you need any info from me: [My Twitter](https://twitter.com/Rov3rRepo)

**Comment by 0xLouie** [comment]
+1

**Comment by Madrox24** [comment]
+1

**Comment by CaptainChickenzz** [comment]
+1

**Comment by GamingSlimeYT** [comment]
+1
