### ISSUE TITLE
Testers

### ISSUE THREAD

**Issue by thehappydinoa** [pwn20wndstuff/Undecimus#284]
Hi,

I know you are quite busy and I wanted to thank you for quickly pushing a 11.4.1 jailbreak. I would love to assist with A7/A8 testing (iPhone 6 specifically), if there is anything I can do please let me know: [@thehappydinoa](https://twitter.com/thehappydinoa) or [thehappydinoa@gmail.com](mailto:thehappydinoa@gmail.com)

Thanks again,
thehappydinoa

**Comment by test13371997** [comment]
Adding on, I can test with a 5s

**Comment by king4q** [comment]
If there is help needed Pwn20wnd will say so. @Cryptiiic Please close this issue.
