### ISSUE TITLE
Update screenshots to show v3.0.0

### ISSUE THREAD

**Issue by haykam821** [pwn20wndstuff/Undecimus#286]
[The screenshots](https://github.com/pwn20wndstuff/Undecimus/blob/v3.0.0%25b4/README.md#screenshots) have not been updated since ce0f82c. They should be updated to show support for 11.4.

**Comment by T4shf33n** [comment]
Screenshot has been updated in a recent pull request. Now it only needs to merge

**Comment by haykam821** [comment]
Pull request #340? Those screenshots aren't very good.

**Comment by T4shf33n** [comment]
@haykam821 I will look into it tomorrow

**Comment by T4shf33n** [comment]
Does those really matter? And I don’t use a sim card
