### ISSUE TITLE
Voucher_Swap failing

### ISSUE THREAD

**Issue by LucifersCircle** [pwn20wndstuff/Undecimus#287]
I'm currently using my own developer certificate for Multi_Path but I wanted to post the issues I had when trying VS. 

iOS: 11.3.1
Device: iPhone 7+
Unc0ver version: 3.0.0~b4

Issue: Phone reboots either at, or immediately after "stashed voucher pointer in thread." I have not gotten past this in over 20 attempts, nor has it crashed before this point. Here is a screen shot from unc0ver before it crashes, I hope this can help in some way.

https://imgur.com/a/qnfSNRh

**Comment by sportusrcu** [comment]
Totally broken here too. Using ip7 + 11.3.1, it starts then just reboot.
Unc0ver v3.0.0 b5

**Comment by danielbald** [comment]
Still crashing in v3.0.0~6 i7+ 11.4.1

**Comment by iiTzTune** [comment]
Also getting this issue on iPhone 8 Plus 11.4

**Comment by How-Bout-No** [comment]
Using @danielbald method from #283 on the latest version 3.0.0~b8 worked fine

1. Airplane mode
2. Clear memory
3. Open unc0ver and press button (all settings default)
4. After the crash/reboot and instantly after unlocking, open unc0ver and press the button
5. It worked and went through the motions of initial install

**Comment by fejkmin** [comment]
I have the same crash on iPad pro 2 12,9  v3.0.0~b9 iOS 11.2.1
Tried many times now and what How-Bout-No suggested doesnt help me.
Just reboots at "stashed voucher pointer in thread."

**Comment by king4q** [comment]
Everyone needs to update their Unc0ver version to 3.0.0 Beta 13 as if fixes this issue. @Cryptiiiic please close this issue.
