### ISSUE TITLE
iPad mini 2 on 11.4.1 not supported

### ISSUE THREAD

**Issue by CodeyMoore** [pwn20wndstuff/Undecimus#288]
I went to try and jailbreak my iPad mini 2 on 11.4.1 but it says its not supported

iOS: 11.4.1
Device: iPad Mini 2 (Retina)
Unc0ver version: 3.0.0~b4

**Comment by c0ldra1n** [comment]
Possibly because voucher_swap is not compatible with mini 2. Try electra which has v1ntex, or wait until unc0ver is updated.

**Comment by king4q** [comment]
voucher_swap doesn’t support 4K devices at this time. @Cryptiiiic please close this issue.
