### ISSUE TITLE
ALARM CLOCK BUG

### ISSUE THREAD

**Issue by Marinamoina** [pwn20wndstuff/Undecimus#292]
An ALARM CLOCK BUG is causing my iPhone 8, 11.3.1, unc0ver 2.1.3 in a complete freeze. The alarm is on and I cannot stop it. Touch and hard buttons do not work. Only a hard reset can help.
Can u please have a look at this?
No clock tweaks installed by the way.

**Comment by Marinamoina** [comment]
The issue happens randomly. Especially after a night in the morning.

**Comment by gnawh** [comment]
stackxi

**Comment by Marinamoina** [comment]
I don’t use StackXI.

**Comment by king4q** [comment]
This issue is a duplicated of the closed issue #289. @Cryptiiiic please close this issue.

**Comment by Cryptiiiic** [comment]
@king4q 289 came after this issue, it was a duplicate of this.

**Comment by Marinamoina** [comment]
It seems duplicated because the was a written mistake „Cock“ instead of „Clock“. So I closed it my self. Couldn’t delete it edit.
Please reaktivate this issue. Today morning I had a freeze again, no sound just vibration. Left the phone until Safe Mode came.

**Comment by king4q** [comment]
@Marinamoina please update to Unc0ver 3.0.0 Beta 15 which is the latest at the time of typing this. & if the problem persists please post your diagnostics log.
