### ISSUE TITLE
Unc0ver 3.0.0b7 Failed to Extract Bootstrap still

### ISSUE THREAD

**Issue by Wanqed** [pwn20wndstuff/Undecimus#296]
Test: installDeb(dpkg_deb.UTF8String, true) still getting the same error with the beta 7 I’ve restored RootFS I’ve completely restored my whole device also.

**Comment by Wanqed** [comment]
iPhone 6s, 11.3

**Comment by lipealv3s** [comment]
I got a 6s on 11.3.1 running well on both 2.2.3 and 3.0.0 b7.
In the beginning I was having trouble with a tweak “Copic 2” that after jailbreak run put my device in spinning whell and rebooted.

**Comment by sbingner** [comment]
Duplicate of #290
