### ISSUE TITLE
Unable to jb with new versions

### ISSUE THREAD

**Issue by corleone132** [pwn20wndstuff/Undecimus#299]
After I updated the uncover jb v2.2.2 and v2.2.3 on my iPhone 7 Plus 11.3.1, 3 things happened. First, I have to try and try and try to get into jailbroken state. Always reboots right after a hit jailbreak button. If I manage to pass the first step, jailbreak throws my phone into the safe mode and I cannot pass that. Someone told me to delete bolders, and I did that. After deleting bolders, if I can pass the first step, after 34, jailbreak sends my phone into the respring loop and I have to force reboot the phone. Never had an issue before with the unc0ver

**Comment by dicksonboy** [comment]
same

**Comment by 510shah** [comment]
I have the same problem, cannot jailbreak on any version. Also when I disable tweaks from the unc0ver it works. But jailbreak stops working or gets stuck on respring loop as soon as I turn on tweaks.

**Comment by coenkcore** [comment]
Check your tweak, delete all tweak first and rejailbreak and try installing tweak again one by one and make sure tweak are compatible.


Tested by me on u0 2.2.2 / 2.2.3  on iP6S iOS11.2.6

**Comment by 510shah** [comment]
After 3 hours found out Bioprotect XI, Audio Recorder 2  and CallBar XI are creating problems.

**Comment by dicksonboy** [comment]
For me I just found out ‘SneakCam’ disable it then all good

**Comment by coenkcore** [comment]
@510shah i have installed bioprotectX voicechangerX from limneos and no problem while respring, you must installed and buy lisence from limneos do not use pirate tweak. 
One more careful with CCmodules on u0 2.2.2 and above that causes respring loop

**Comment by sportusrcu** [comment]
Agree with post above, CallbarX perfectly working

**Comment by wishy-96** [comment]
> 
> 
> After I updated the uncover jb v2.2.2 and v2.2.3 on my iPhone 7 Plus 11.3.1, 3 things happened. First, I have to try and try and try to get into jailbroken state. Always reboots right after a hit jailbreak button. If I manage to pass the first step, jailbreak throws my phone into the safe mode and I cannot pass that. Someone told me to delete bolders, and I did that. After deleting bolders, if I can pass the first step, after 34, jailbreak sends my phone into the respring loop and I have to force reboot the phone. Never had an issue before with the unc0ver

dude i was able to fix this issue on #304 where i listed all the tweaks that caused what you were experiancing
hope this helps

**Comment by king4q** [comment]
Everyone please make sure you are on the latest Beta of Unc0ver if you have a A9 or iPhone 6S or newer & you can use Voucher swap, & it’ll fix the respring & bootstrap errors. And as for the safe mode it’s your tweaks you need to figure out what tweaks are causing you to be put into safe mode. On #304 there is a list of incompatible tweaks. The developers of their tweaks need to update them to work with Sauriks Substrate. It is NOT Unc0vers fault. I repeat it is NOT Unc0vers fault.

**Comment by king4q** [comment]
Request for this to be closed @Cryptiiiic
