### ISSUE TITLE
Kernel Panics

### ISSUE THREAD

**Issue by Ziph0n** [pwn20wndstuff/Undecimus#3]
Device: iPad Air 2
iOS version: iOS 11.3.1
I jailbroke it with Electra before, I didn't use Rollectra

I tried to jailbreak it 3 times, got a kernel panic at 1/48 each time (logs below). Is it something you can fix? Is it because I didn't use Rollectra?

If I can do something on my side to help troubleshoot this, just ask.

https://pastebin.com/8i6x6sts
https://pastebin.com/jve9kv15
https://pastebin.com/kT2TRHQi

**Comment by Cryptiiiic** [comment]
For some reason after the snapshot gets reset, Siri is running and is actively communicating on mptcp even after reboot. To fix this, simply turn siri on, then turn it back off. Then either reboot or clear ram.
@Ziph0n @KMamedoff

**Comment by KMamedoff** [comment]
Did not make it better. It still takes me 8-10 tries to jailbreak with multipath.

**Comment by pwn20wndstuff** [comment]
That seems to be an issue with MPTCP. I’ll be taking a look at it.
