### ISSUE TITLE
Jailbreakd is still being injected to TrustCache

### ISSUE THREAD

**Issue by lokiuox** [pwn20wndstuff/Undecimus#300]
Uncover (latest version) is still injecting old binaries, including jailbreakd, into the TrustCache from leftover files from previous versions, in particular, `/usr/share/undecimus/injectme.plist`.

Evidence: **(Look at the log, not the error)**
![9w10ph4mywd21_](https://user-images.githubusercontent.com/25590129/52137358-a2aa0e80-264a-11e9-9942-c75daf1ec0ad.png)

Although said file is not present anymore in the newest versions, it is never removed from previous versions  and Uncover still reads that file and inject listed binaries into the TrustCache.
Here's the code that does that:
https://github.com/pwn20wndstuff/Undecimus/blob/ce3e5035a7a8d38458787d33a0d4b8fe72e9a3b6/Undecimus/source/JailbreakViewController.m#L1220-L1222

Contents of the file from older versions:
![photo5956551055057727032](https://user-images.githubusercontent.com/25590129/52136948-9d988f80-2649-11e9-972a-056c591cd54e.jpg)

**Suggestion:** Remove the file in initial setup or/and change aforementioned lines from JailbreakViewController.m to not read from it anymore when injecting TrustCache.

UPDATE: Apparently manually deleting the file causes a respring loop (I'm not sure, can't test this)

**Comment by jd486** [comment]
Not working on iPhone 7 ios 11.3.1 tried many time and was stuck on respiring loop

**Comment by lokiuox** [comment]
Probably there's something else to do, let's wait for a proper fix from pwn

**Comment by vadim-shavkunov** [comment]
Failed to inject trust cache, I can't activate jailbreak

**Comment by lokiuox** [comment]
Apparently deleting the file causes a respring loop (haven't tried myself though). Best option for now is to Restore RootFS and jailbreak with latest version.

**Comment by king4q** [comment]
Everyone needs to update their Unc0ver version to 3.0.0 Beta 13 & it will fix this issue. @Cryptiiiic please close this issue.

**Comment by lokiuox** [comment]
I think the fix should be to remove the line that sources the file or change it to /usr/share/jailbreak/injectme.plist as that file is actually present in the newer version, but I'm not sure about that since I don't know enough about the code of Uncover

**Comment by Cryptiiiic** [comment]
@lokiuox please post your diagnostics.

**Comment by sbingner** [comment]
Fixed in v3.0.0~b14
