### ISSUE TITLE
Iphone 7+ not working

### ISSUE THREAD

**Issue by duspada** [pwn20wndstuff/Undecimus#305]
Hello.
I have the 11.4 version, Iphone 7+

It just restart the phone, but nothing happens...

Sometimes go through 13/38, but it mostly stops on eh 1/38....

Does it work on that version? Maybe is its memory? 256gb....

Thanks again

**Comment by wishy-96** [comment]
it has to be ios 11.4 b3
your version probably not compatible

**Comment by How-Bout-No** [comment]
Are you using the 3.0.0 betas?

**Comment by duspada** [comment]
Yes, i think so... im using the latest!!!
V3.0.0~b8

**Comment by How-Bout-No** [comment]
@duspada try this method, worked well for me:

1. Airplane mode
2. Clear memory
3. Open unc0ver and press button (all settings default)
4. After the crash/reboot and instantly after unlocking, open unc0ver and press the button
5. It worked and went through the motions of initial install

**Comment by duspada** [comment]
@How-Bout-No this way stops here!! but at least goes a little more...
https://imgur.com/a/31tiTqp

**Comment by king4q** [comment]
@duspada this is fixed in Unc0ver 3.0.0 beta 13 the latest currently is beta 15. Cryptiiiic please close this issue.
