### ISSUE TITLE
Cryptiiiic Closed so many open issues and a pull request

### ISSUE THREAD

**Issue by kjwamlex** [pwn20wndstuff/Undecimus#306]
I mean, seriously. 
I worked on UI part with pwn in PR and you can’t just close it; also I looked into issues tab and so many of them got closed; wtf is going on Cryptiiiic?

**Comment by Cryptiiiic** [comment]
chillout it was conflicting.

**Comment by kjwamlex** [comment]
> chillout it was conflicting.

Hey dude.

Pwn and I were aware of the conflicts and pwn was going to take care of it. Can you please bring it back?

**Comment by Samgisaninja** [comment]
We will not be changing the unc0ver UI. Sorry about that.
