### ISSUE TITLE
 recovery mode

### ISSUE THREAD

**Issue by calvin2000001** [pwn20wndstuff/Undecimus#308]
Hello sir,
Thanks for all you do!
I was wondering if you could help.
After trying to install uncover onto my iphone 6s with Electra just deleted from the home screen ( I can't remember which version of uncover it was), My phone was boot-looped then I was able to get it into recovery mode to restore to ios 12 loosing my jailbreak and ios11 install.
Now, although I am on ios 12.0.1, I wanted to update to 12.1.1 because of the bugs on the 0.1, but now my phone goes into recovery mode before the update and then the apple logo comes on and it just sits there and itunes never goes through the whole update. I also can't restore. So just wondering if there is anything to fix whats going on. Not sure what was changed but something. Thanks!!!

**Comment by king4q** [comment]
We cannot fix this. @Cryptiiiic please close this issue.

**Comment by sbingner** [comment]
You should enter DFU mode and restore 12.1.1 before it is un-signed.  Strange that you can't get into recovery mode though.  Make sure you have shsh saved as well.  You may also want to check your USB cable etc.  If none of that helps you may want to talk to somebody on the r/jb discord or something similar for more ideas.
