### ISSUE TITLE
Unable to rename snapshot

### ISSUE THREAD

**Issue by ELiTEiiiSkillz** [pwn20wndstuff/Undecimus#309]
https://www.reddit.com/r/jailbreak/comments/amjrf6/help_unc0ver_errno_17/

**Comment by king4q** [comment]
@Cryptiiiic I cannot assist in this. As I do not know the internal code of Unc0ver well enough.

**Comment by Cryptiiiic** [comment]
@ELiTEiiiSkillz post your diagnostics.

**Comment by sbingner** [comment]
What? according to what you posted, you are on 11.1.2 with a snapshot mounted.  That is not supposed to happen.  Did you rename your orig-fs snapshot to the system snapshot with snappy or something similar?

**Comment by sbingner** [comment]
Please try the ipa in the attached Undecimus.zip and post diagnostics.  I don't expect it to work but it might tell us something that makes more sense. It will log what snapshots actually exist on the remounted rootfs.
[Undecimus.zip](https://github.com/pwn20wndstuff/Undecimus/files/2831431/Undecimus.zip)

**Comment by king4q** [comment]
@ELiTEiiiSkillz please use the Undecimus.zip that sbinger has provided. Thank you.

**Comment by sbingner** [comment]
Actually use the latest beta release - it has the additional logging added

**Comment by king4q** [comment]
So, @GeoSn0w posted on Twitter he had the same issue. He was forced to restore to the latest update. But this does need to be fixed, as it’s messed up 2 devices now that I know of. @pwn20wndstuff @sbingner @Cryptiiiic

**Comment by cr7hmood** [comment]
me too guys i eanna know what should i do my ios is 12.1.2 and i can not fix this i tryed every thing in this world
