### ISSUE TITLE
YouTube freeze on app startup

### ISSUE THREAD

**Issue by How-Bout-No** [pwn20wndstuff/Undecimus#310]
The YouTube app constantly freezes on startup, nothing in crashreporter and no tweaks that have anything to do with YouTube are installed. Trying again with the Load Tweaks option off still had youtube, and only youtube, freeze.

iPhone 6s
iOS 11.0.3
unc0ver 2.1.3

**Comment by king4q** [comment]
Update to Unc0ver 3.0.0 Beta 13 & make sure you have YouTube updated also check in non jailbroken mode that YouTube opens.

**Comment by king4q** [comment]
@How-Bout-No

**Comment by How-Bout-No** [comment]
YouTube worked fine not jailbroken, but anyways getting unc0ver to beta 13 fixed the issue, no freezes. Thanks, @king4q

**Comment by king4q** [comment]
> YouTube worked fine not jailbroken, but anyways getting unc0ver to beta 13 fixed the issue, no freezes. Thanks, @king4q

No problem! Just so you know the latest version as of now is Unc0ver 3.0.0 Beta 15.
