### ISSUE TITLE
substrate stuck on safe mode. 

### ISSUE THREAD

**Issue by YARIEL** [pwn20wndstuff/Undecimus#312]
Ios 11.4.1 Can't get out of substrate safe mode even if I remove all my tweaks. And removing substrate leads to error (2)

**Comment by king4q** [comment]
Use Rec0ver in the Unc0ver app settings & make sure you are on Unc0ver 3.0.0 Beta 13 If all of that is done & you rejailbreak & your still stuck in substrate safe mode reply here please. @YARIEL

**Comment by king4q** [comment]
This isn’t a issue with Unc0ver. @Cryptiiiic I can’t handle this as I don’t know what to do.

**Comment by Cryptiiiic** [comment]
@YARIEL post diagnostics.
