### ISSUE TITLE
iPad Pro 7,4 Works first try (or so) then refuses to work until I reinstall the ipa

### ISSUE THREAD

**Issue by d0lb33** [pwn20wndstuff/Undecimus#318]
iPad Pro 7,4 is refusing to rejailbreak after successfully doing it once, unless I uninstall uncover and reinstall it. 12.1. This is also happening with GeoFilza, and RootlessJB

**Comment by Cryptiiiic** [comment]
placebo

**Comment by d0lb33** [comment]
Definitely not a placebo. Doesn’t work at all before reinstalling, works the second I reinstall. I can provide video proof.
