### ISSUE TITLE
Detailed option descriptions

### ISSUE THREAD

**Issue by haykam821** [pwn20wndstuff/Undecimus#32]
There should be descriptions of each option or the most important ones (like "Restore RootFS") below in small text, like how Apple does it in sub-menus in Settings.

**Comment by nullpixel** [comment]
that whole settings page is a mess, needs redesigning and actually implemented well before this can be implemented.

**Comment by nullpixel** [comment]
please don’t do that and instead take inspiration from the settings app. Group relevant settings by section and add extra pages if you have to.

**Comment by Samgisaninja** [comment]
@nullpixel @haykam 

*sighs* fiiiiine

**Comment by Samgisaninja** [comment]
I forgot about this... I’ll make it once we merge `substrate` into `master` as I don’t want to create further fragmentation
