### ISSUE TITLE
High CPU usage after unc0ver 3.0

### ISSUE THREAD

**Issue by wishy-96** [pwn20wndstuff/Undecimus#323]
![a25a87c6-866e-4f2a-b20e-2faf7b845a84](https://user-images.githubusercontent.com/15282798/52310655-336b4c00-29b5-11e9-8541-6a0d9567d45f.png)
![e352c2ec-0e28-437b-b3c5-d700761d7896](https://user-images.githubusercontent.com/15282798/52310656-3403e280-29b5-11e9-9803-ff0945eb568f.jpeg)

**Comment by wishy-96** [comment]
first one is with all tweaks disabled and the second one is with all tweaks enabled
as you can see both shows high CPU usage

**Comment by king4q** [comment]
@Cryptiiiic I’ll let you handle this as I don’t know the rules for this.

**Comment by wishy-96** [comment]
so you close issues without a single tip? or at least how to fix this or tell me where i can find the help i need since your too busy

**Comment by Cryptiiiic** [comment]
@wishy-96 it's not unc0ver related. Also the cpu usage looks normal to me.
