### ISSUE TITLE
Question: should is rename videosubscriptionsd to .bak ?

### ISSUE THREAD

**Issue by wishy-96** [pwn20wndstuff/Undecimus#324]
so alot of people on reddit says that you can fix respring and freezing by renaming videosubscriptionsd to videosubscriptiond.bak
should i do it and what are the drawbacks if i do

**Comment by king4q** [comment]
@Cryptiiiic this doesn’t relate to Unc0ver.

**Comment by wishy-96** [comment]
its related the the jailbreak topic so if you know something about this please share
i do wanna ruin my device because of a mistake ive made wthout consulting the experts and thats why i posted it here

**Comment by king4q** [comment]
No you shouldn’t rename any files @wishy-96 update your Unc0ver & your issue will be resolved.

**Comment by wishy-96** [comment]
well mine is on b17 and unluckely for me it still freezes from time to time like daily, usually while using spotify or refreshing cydia
what is videosubscriptionsd anyway?

**Comment by Cryptiiiic** [comment]
nothing to do with unc0ver, ask someplace else.
