### ISSUE TITLE
v3.0.0%b17- iPhone 6 on iOS 11.4.1 does NOT work, unsupported?

### ISSUE THREAD

**Issue by 0M3G0** [pwn20wndstuff/Undecimus#325]
I tried Electra before giving this one a shot, I believe Electra crashes since it doesn't finish and reboots my device unexpectedly. Gave this one a try and nope... says unsupported?

**Comment by WezXBL** [comment]
After installing the v3.0 b17.ipa use the apps utility area to restart springboard then click jailbreak again & it should work. I had same problem, restarting springboard seemed to make it jb.

**Comment by king4q** [comment]
@0M3G0 only iPhone 6S & newer are supported for IOS 11.4 & newer currently. @Cryptiiiic please close this issue.

**Comment by 0M3G0** [comment]
@WezXBL unfortunately it doesn’t work..

Well I guess I’m going back to Android..

Thanks anyways

**Comment by Cryptiiiic** [comment]
@0M3G0 4k device support is coming soon.
