### ISSUE TITLE
Block Revoke - Standalone Button - iOS 12 support?

### ISSUE THREAD

**Issue by dallaslittle** [pwn20wndstuff/Undecimus#329]
I'm sorry if this is the wrong place to put this, but I thought it would be a great idea. A standalone block revoke button would be incredibly useful, and perhaps even get some sideloaders over to the jailbreak community, seeing the ease in it. iOS 12 support would also be nice (if technically possible), along with the reboot toggle you've recently adapted for iOS 12. 

Side note - I believe someone is already using your method in an IPA for iOS 12, so perhaps you could just grab the code from them since it's your method anyways. Just an idea

**Comment by Cryptiiiic** [comment]
@dallaslittle revoke block needs remount because etc is on rootfs.
