### ISSUE TITLE
Unable to sideload RC7 - Error 4100 Cydia Impactor

### ISSUE THREAD

**Issue by mehtaman** [pwn20wndstuff/Undecimus#33]
Cant get RC7 to install with impactor...
Could be me doing something wrong but the others installed fine.

**Comment by mehtaman** [comment]
Also had Electra
Used Rolectra + Full RootFS to wipe device

**Comment by Samgisaninja** [comment]
You may need to “register your account” with the free development program. I’ve never seen this error before. 

However, this is an issue between you and Apple or you and impactor or Apple and Impactor. Not something that we’re really able to assist with.

**Comment by mhassen724** [comment]
i have same here

**Comment by mhassen724** [comment]
any update please in your case?
