### ISSUE TITLE
Issue when switching from Electra 1.0.3 with the unsplitted Cydia bundle to unc0ver 2.2.6

### ISSUE THREAD

**Issue by JQ555888** [pwn20wndstuff/Undecimus#330]
I used to be on Electra and seeing unc0ver is a much much more advanced tool I decided to switch. I had been well aware of the fact that starting from unc0ver 2.1 a RootFS restore is not needed, so I was expecting a smooth switch from Electra.

Thing is, this didn’t happen. I deleted Electra, rebooted my iPhone, downloaded and sideloaded unc0ver 2.2.6. Thinking it wouldn’t be of an issue, I didn’t turn on the RootFS Restore option and proceeded with the jailbreak. Then an error poped up saying “failed to extract bootstrap”. Notice this is unc0ver 2.2.6 not the older versions. After that thinking the issue might be temporary and could be resolved by rejailbreaking again, I rebooted my device and went straight into “Jailbreak”. This time it says something resembling “Cydia is not correctly installed” and failed. Upon opening Cydia afterwards I discovered Cydia is functioning just fine but weird thing is thag unc0ver seems to be fixated on the fact that Cydia is not working. Even when I toggled on the Reinstall Cydia option in unc0ver Settings tab and rejailbreak the exact same error saying there’s a faulty Cydia popped up. Ended up having to toggle on the Restore RootFS option and things started to work.

However, if this is a rare issue I would have let go of it. I’ve got a couple of devices willing to switch to unc0ver but it seems this issue persists. Please do notice that the Cydia that I have on my devices is not the one which CS later splitted. Instead of having both Cydia (GUI Only) and Cydia Compatibility Package, I only have the Cydia Compatibility Package (the original version before CS pushed that sketchy splitted Cydia package to make it work with Sileo). I wonder whether this could be the cause. I posted this issue on r/Jailbreak a while ago but the stupid mods there didn’t seem to understand there’s a difference between the splitted and unsplitted Cydia and removed my post just hours later telling me this is a duplicated question (fuck them).

Hopefully this issue can be fixed and much love to the developers <3

**Comment by king4q** [comment]
@JQ555888 update your Unc0ver version to 3.0.0 Beta 19. It should fix your issue. @Cryptiiiic please close this issue.

**Comment by JQ555888** [comment]
Thanks for the instant reply. Will try ;)

**Comment by king4q** [comment]
Your very welcome. @JQ555888 let me know how it goes!

**Comment by JQ555888** [comment]
Tried the latest unc0ver v3.0.0 b21 on another device with the exact same old Electra v1.0.3 set up and it's still having the old "Failed to extract bootstap" issue. This time I noted down the whole popup. @king4q 

Error (Fatal) Errno:9
Test: InstallDeb(dpkg_deb.UTF8String, true)
Filename: JailbreakViewController.m
Line: 1563
Function: Jailbreak
Description: Failed to extract bootstrap.

Any idea?

**Comment by JQ555888** [comment]
Never mind. 
After that I rebooted the phone because unc0ver was unresponsive to touches and then rejailbroke. The issue seems to be gone. This time the new Cydia with substrate is installed and Electra is gone. Don't know why it failed on first try though. Thanks to the developers. Issue marking closed now.
