### ISSUE TITLE
Unc0ver 3.0.0 videosubscriptionsd keeps crashing and rebooting phone

### ISSUE THREAD

**Issue by AccelShiftx** [pwn20wndstuff/Undecimus#333]
![s__25206791](https://user-images.githubusercontent.com/41006159/52444204-a8c84f80-2b62-11e9-9f49-74d0cabe37a5.jpg)
![s__25206790](https://user-images.githubusercontent.com/41006159/52444205-a960e600-2b62-11e9-841b-2a66bef4fee2.jpg)

**Comment by Un4givenPG** [comment]
This doesn’t belong here, remember tweaks break the substrate not substrate tweaks, if it doesn’t work for you just uninstall the tweak or futurerestore to a version where it works. 👍🏻

**Comment by king4q** [comment]
@Cryptiiiic

**Comment by atifchy** [comment]
Install cappd

**Comment by AccelShiftx** [comment]
Well i didn't have crashes on lower versions of Unc0ver with the same tweaks installed, problems started to show up when switching to newer versions. That’s why i posted this here.

**Comment by Cryptiiiic** [comment]
@AccelShiftx not unc0ver related, use cappd like @atifchy suggested. Closing this.
