### ISSUE TITLE
Cannot restore root successfully or jailbreak

### ISSUE THREAD

**Issue by abraham8p** [pwn20wndstuff/Undecimus#336]
Error : https://imgur.com/a/qn4AaHT

Diagnostics.plist : https://pastebin.com/VvnNpc5d

So a little background before looking into diagnostics I tried switching from electra to unc0ver awhile back when it wasn’t supported on iphone 7+ now haven’t been able to jailbreak ever since tried both electra/unc0ver and no luck the only thing I could open is filzaescaped I havent been jailbroken since the release of unc0ver rc1 dont know if this is fixable just want to know if it might get fixed in the future or am I doomed and should update? I’ve also had other issues that did get fixed with updates of unc0ver but this is my latest error that I cant get passed.

**Comment by Cryptiiiic** [comment]
@abraham8p please shared the full diagnostics.plist

**Comment by abraham8p** [comment]
https://mega.nz/#!FcIFCI5A!4s1pugoPVrTKfVUoeRZKtGwKbmXVMy04cjIBAtGJgBU

**Comment by king4q** [comment]
Yeah you’re on 11.2.1, you don’t need a RootFS Restore I don’t even know why you would have one to begin with. @abraham8p

**Comment by abraham8p** [comment]
@king4u I believe RootFs Restore 11.2-11.2.6 support was added on RC7 The reason I want to restore it is because something got corrupted when I tried to switch from electra to unc0ver on RC1 when it wasn’t supported at the time basically I f*cked up but it was different errors those errors were fixed on updates of unc0ver I also have the storage bug where It just says calculating system storage the unc0ver wont go trough with restore root off or on or disabled updates on n off but no luck also have tried to go back to electra but no luck with that either tried to restore to a icloud backup but no luck with that when I try to jailbreak without the restore feature on I get a bootstrap error https://imgur.com/a/klTfcwQ

**Comment by king4q** [comment]
@abraham8p use the latest beta of Unc0ver without RootFS & it should fix your issue.

**Comment by abraham8p** [comment]
@king4q not trying to like be rude or anything but like I said on the last comment it wont go trough with the restore RootFS feature on/off so no it wont fix my issue

**Comment by king4q** [comment]
Yes but if you’re not on the latest version I won’t help you & it just causes more time out of my day that’s wasted to tell you to update the ipa & it ends of fixing the problem. A lot of issues are just due to not updating the IPA. So update it & I’ll reply again. @abraham8p

**Comment by abraham8p** [comment]
@king4q wat I am using the latest id prefer if someone else helped you clearly dont get my error.

**Comment by jayb1239** [comment]
@abraham8p have you tried Rollectra instead?
