### ISSUE TITLE
Boot nonce

### ISSUE THREAD

**Issue by mad2909** [pwn20wndstuff/Undecimus#337]
Boot nonce not set automatically on ip8+
Uncover 3.0.0 b20

**Comment by king4q** [comment]
@Cryptiiiic

**Comment by Cryptiiiic** [comment]
@mad2909 post diagnostics file.

**Comment by mad2909** [comment]
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2848440/diagnostics.zip)

**Comment by Cryptiiiic** [comment]
@mad2909 what's the issue? the bootnonce is set to 0x1111111111111111 automatically.
