### ISSUE TITLE
Restore RootFS 

### ISSUE THREAD

**Issue by CoolPersonMaam** [pwn20wndstuff/Undecimus#338]
I did a restore RootFS on A8 device 11.4.1 but after doing it Cydia is still there so I reenabled restore RootFS but then once I did it somehow it started jail breaking please help

**Comment by CoolPersonMaam** [comment]
Also, btw here’s the download link https://www.dropbox.com/s/pdieedjagyvnkth/diagnostics-7.plist?dl=0 to my diagnostics and lastly what I mean is that after Restore RootFSing I have a snapshot after I try to do it again it says now creating system Snapchat and then it restarted BUT CYDIA IS STILL HERE!! Have a nice reading this btw and ya I’m kind of pancing also since I launched this application multiple times the diagnostics are going to be filled with a mess

**Comment by atifchy** [comment]
Cydia being there isn’t an issue. After restoring successfully, jailbreak again.

**Comment by king4q** [comment]
Cydia and all apps will still show up dont worry about it. just restore rootfs and then jailbreak. itll be fine.

**Comment by CoolPersonMaam** [comment]
No doesn’t restore RootFS Restore the root filesystem and isn’t Cydia part of it sorry for my issue very unclear but I’m asking why after doing restore RootFS Cydia is still there

**Comment by Cryptiiiic** [comment]
@CoolPersonMaam that's just the icon, it is actually gone.
