### ISSUE TITLE
Looks like problem’s on Substrate - fakesigned apps crash on unc0ver even with AppSync installed

### ISSUE THREAD

**Issue by HSANNU** [pwn20wndstuff/Undecimus#339]
So i’ve got a bunch of apps (like the ++ ones but not piracy) fakesigned and then installed on my device when I was on Electra. They were signed using “ldid -S [executable]” method and worked perfectly before I switched.

After I switched to unc0ver and despite having AppSync Unified from Karen’s repo installed, those apps start crashing upon opening, like only for one second I can see the launch screen. Apps that are signed using Enterprise certificates or signed by my personal iOS development certificates would work just fine under jailbreak even if the certificate has been revoked or even expired. Not sure what’s wrong with those fake signed ones installed using Filza though. I tried to “ldid -S” them again using saurik’s Link Identity Editor but the issue persists.

Insights anyone?

**Comment by HSANNU** [comment]
Tried Karen’s “appinst” command to install that fakesigend app again, and still it crashed. Weird thing is that, if I sideload the app using Impactor it would work. Also if I compile the app from source in Xcode and build it that way it would work as well. It’s simply that fakesigned apps won’t work even if I have AppSync there.

**Comment by atifchy** [comment]
Fake signed apps works perfectly in jailbroken state.

**Comment by HSANNU** [comment]
So I tested whether it’s AppSync causing the issue again by downloading GoodNight.ipa from a signing service, removing its entitlements file and signing it with ldid and voila it works, so first of all we can exempt AppSync from being the culprit for now.

**Comment by HSANNU** [comment]
HOWEVER, I did some further investigation and saw this line under the description of the new Substrate “0.9.7013 fixes an issue where some applications would crash when hooked by Substrate” and “0.9.7020 adds MSHookMemory”. 

What I’m suspecting is that this new version of substrate somehow broke support for particular apps again and leads to what’s happening now, for the reason that this exact same set up used to be working fine on Electra. Aside from AppSync Unified, the other tweaks I was using on this test device were Filza from Tigi’s repo, HomeGesture, BatteryLife and their dependencies. While all those tweaks were notoriously issue free, the only thing that comes up to my mind was what changes that unc0ver has made that render these apps unusable, and therefore Substrate since AppSync wasn’t causing this.

**Comment by HSANNU** [comment]
Basically what’s going on here with my fakesigned ipas (using ldid -S):
Install using Filza - Successfully installed - crash upon opening
Install using Impactor/Reprovision - Successfully installed - working fine

**Comment by HSANNU** [comment]
So now the question comes down to “how can I downgrade Substrate to its dummy version to see whether its causing this”.

In Substrate’s descriptions page I found that I should press Volume Up while jailbreaking to get into non-Substrate mode but every time I do this, it results in “Failed to extract bootstrap” with an errno:9.
Otherwise if I simply try to remove Substrate in Cydia and install Substitute, it would say “subprocess cydo report error (2)” and it never actually get installed. If I disable tweaks and daemons in unc0ver’s Settings page and reboot, rejailbreak, Substrate is still loaded and leads to the same error “cydo reported error (2)”.

This is u0 v3 b21 that I’m using. So HOW (TF) CAN I DOWNGRADE SUBSTRATE TO ITS DUMMY VERSION NOW?

**Comment by HSANNU** [comment]
Think maybe I should @sbingner @pwn20wndstuff

**Comment by sbingner** [comment]
You need to sign with proper entitlements.  If it worked on electra that’s not good.  Just because something worked on electra doesn’t mean it should work.

**Comment by HSANNU** [comment]
@sbingner Sorry I used the wrong word (this is not my mother tongue so plz forgive for that). Actually I did use entitlements while signing.

The whole command was “ldid -Spath/to/entitlements [executable]”, and the entitlements file I was using that had been working on Electra was from Karen’s website explaining what entitlemenrs should be used. (Here: https://developer.angelxwind.net/iOS/Xcode/asu_pid.entitlements) I meant the mobile provision file that was removed. With “ldid -e [exec]” I can see it seems fine.

Could you please elaborate what entitlements I should have been using? I also found that if I use entitlements generated by Impactor (with my personal team identifier in it) it appears to be working. But the question is, how can I sign it to make it work permanently instead of 7 or 365 days?
