### ISSUE TITLE
Offsets Finder

### ISSUE THREAD

**Issue by unixblue** [pwn20wndstuff/Undecimus#342]
Hi, I have a problem with offsets.
So I’m trying to get offsets of ios 12.1.1 and offsetfinder64 tells me this: 
```
libc++abi.dylib: terminating with uncaught exception of type tihmstar::exception: std::exception
Abort trap: 6
```
So is not possibile to retrieve the offsets of the current version.
I tried to investigate on in and i noticed in the ios 12 the kernelcache structure has changed.
So how can I get the offsets of ios12 kernelcache ?

**Comment by Cryptiiiic** [comment]
@unixcerberus post the full log

**Comment by unixcerberus** [comment]
```
./liboffsetfinder64 kernelcache
lzss comp detected, uncompressing : success ...
libc++abi.dylib: terminating with uncaught exception of type tihmstar::exception: std::exception
Abort trap: 6
```

**Comment by Cryptiiiic** [comment]
@unixblue it doesn't support iOS 12 yet I don't think, also v1ntex is 11.x only. offsetfinder is for v1ntex so this is pointless.
