### ISSUE TITLE
Better looking log window

### ISSUE THREAD

**Issue by preminemm** [pwn20wndstuff/Undecimus#343]
Make the logging window aesthetically pleasing pls (e.g. a transparent babcround + black text)

**Comment by T4shf33n** [comment]
That’s a good idea .

**Comment by king4q** [comment]
Make a pull request with the code changes if you can’t do that then I wouldn’t request it. @Cryptiiic please close this issue. Sorry about all the tags. @preminemm

**Comment by preminemm** [comment]
Pwn said he’s nyt against implementing user requests amd to just create an issue. It wasn’t just an idea. No need to be salty. @king4q

**Comment by king4q** [comment]
No I was just saying that it makes it a crap ton easier on the Developers such as Pwn20wnd. So that’s why I said it.

**Comment by preminemm** [comment]
@king4q Whatever you say, chief

**Comment by CoolPersonMaam** [comment]
I mean this is meant to show verbose mode and it is meant for diagnostics so you can se what it’s generating while you jailbreak you could turn it off in the settings if you want to
