### ISSUE TITLE
Failed to extract bootstrap on unc0ver v3.0.0 b21

### ISSUE THREAD

**Issue by JQ555888** [pwn20wndstuff/Undecimus#344]
What the popup says:
Error (Fatal)
Errno: 9
Test: installDeb (dpkg_deb.UTF8String, true)
Filename: JailbreakViewController.m
Line: 1563
Function: jailbreak
Description: Failed to extract bootstrap.

Here are the screenshots of the error:
![img_0268](https://user-images.githubusercontent.com/47416213/52529660-f0043b00-2d30-11e9-8a3c-19f0de055880.PNG)
![img_0269](https://user-images.githubusercontent.com/47416213/52529662-f397c200-2d30-11e9-99ab-ccbe593ac724.PNG)

This post has been created as requested here:
https://github.com/pwn20wndstuff/Undecimus/issues/327#issuecomment-462056825

Worth to mention this error is 100% reproducible if trying to boot into no substrate mode.

The diagnostics files are here:
[diagnostics (right after the freezing caused by the error).plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2848521/diagnostics.right.after.the.freezing.caused.by.the.error.plist.zip)
Because the app freezes after it shows the error message, I was unable to use the "share diagnostics" function, so instead I took some screenshots of the log window
![img_0270](https://user-images.githubusercontent.com/47416213/52529676-512c0e80-2d31-11e9-81fe-030c90d7aed2.PNG)
![img_0271](https://user-images.githubusercontent.com/47416213/52529677-51c4a500-2d31-11e9-9109-e6ef07e19d51.PNG)
![img_0272](https://user-images.githubusercontent.com/47416213/52529678-51c4a500-2d31-11e9-8421-eb625249f08b.PNG)

This is the diagnostics file after a successful jailbreak:
[diagnostics (after a successful jailbreak).plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2848522/diagnostics.after.a.successful.jailbreak.plist.zip)

This issue can also be found on my iPhone 7 (iPhone9,1) using voucher_swap.

@Cryptiiiic @sbingner

**Comment by king4q** [comment]
Don’t hold volume up. Just turn tweaks off. It’s substrates fault it happens when using volume up to go into safe mode aka no substrate mode. @JQ555888 so just turn tweaks off. & you’ll be fine

**Comment by king4q** [comment]
Also, @Cryptiiiic this is a duplicate of my previous issue. Just so you know as then the one you specifically DMed me & said you marked as a duplicate I don’t remember the # for it & i’m tired & on vacation right now.

**Comment by JQ555888** [comment]
Gotcha @king4q thanks so much!!! This issue also appeared while I was trying to switch from Electra to unc0ver during the first try using b21. After a reboot it all worked great until I was trying to uninstall Substrate because Elimneos' tweak sent me straight into a respring loop.

And also #334 and #327 are probably the ones duplicated. :)

**Comment by king4q** [comment]
Yeah I have one I opened as well that’s a duplicate lol. Anyways if that fixed it then let me know. But just turn tweaks off if you need to. Otherwise there’s no reason to turn them off. Anyways let me know how it goes and if it’s good please close the issue. Saves other people time. @ JQ555888

**Comment by JQ555888** [comment]
Yes it all went well. I was just suggesting a method to reproduce the exact same error that struck me when I was switching from Electra.
Actually I opened this one because @Cryptiiiic asked me to open another one in this comment here (https://github.com/pwn20wndstuff/Undecimus/issues/327#issuecomment-462093887) because he had closed both of the duplicated issues (maybe to merge into one idk?), but if this is still a duplicate I'll close it rn.

**Comment by JQ555888** [comment]
@king4q oh, and is there a method to get the old substrate now without booting into safe mode? On reddit someone said Limneos' tweaks are not compatible with the latest substrate so I wonder if using the old one can fix this. 

English is not my first language and sorry if I sound very strange. I really appreciate the efforts developing this jailbreak and it's real faster than Electra in terms of time spent respringing, reloading daemons, etc.
