### ISSUE TITLE
iphone keep rebooting i can't open it

### ISSUE THREAD

**Issue by dontraceme** [pwn20wndstuff/Undecimus#345]
I am using v3.0.0 b21. It told me click to reboot, then my iphone keeps rebooting. can't open my phone. even itunes can't detect it. have to dfu upgrade

**Comment by dontraceme** [comment]
iphone 6, ios11.3. Is there any way to save my iphone?

**Comment by ctalbot2004** [comment]
it’s a bootloop, my iphone 7 did this as well

**Comment by king4q** [comment]
@sbinger @pwn20wndstuff @Cryptiiiic huge massive bug. Also@ctalbot2004 12.1.1Beta 3 IS STILL BEING SIGNED & CAN JAILBREAK SOON!! @dontraceme!!! Read above!!! 12.1.1 Beta 3 is still signed you can still have a chance at a jailbreak soon!!

**Comment by ctalbot2004** [comment]
@king4q already did that and now i’m on iOS 12.1.1 beta 3 jailbroken with unc0ver.

**Comment by king4q** [comment]
Good. Save blobs as well. I have a 6S & a iPod 6 I’ve saved a ridiculously overkill amount of blobs... around 100K per device lol

**Comment by IOSMR4twenty** [comment]
Guessing this was because you didn’t remove the already installed IOS update from your iPhone storage in settings?

**Comment by phooooon** [comment]
@IOSMR4twenty Yes I did that accidentally.whatcani do now?? Restore from iCloud?
