### ISSUE TITLE
[Solved] v3.0.0~b26 "RootFS(rec0ver)" solved all the problems.

### ISSUE THREAD

**Issue by ios11iphone6s** [pwn20wndstuff/Undecimus#346]
iPhone 6S, iOS 1131

1- Initially **v3.0.0~b21(vs)** worked perfectly., After 1day i restarted my iPhone. Then iPhone restarting everytime on last step of Jailbreak process. Tried 7times on **v3.0.0~b21(VS)** 

2- Tried with **v2.2.6(EL)** , same restarts over &over after last step of jailbreak process**(38/38)** 

3- Tried with **v2.2.2(EL)** no improvements.

**Comment by Cryptiiiic** [comment]
@ios11iphone6s turn off tweaks

**Comment by ios11iphone6s** [comment]
> @ios11iphone6s turn off tweaks

1. Installed v2.2.6( EL)
2. Turn OFF Tweaks
3. restarting at 1/38 every time , still 3times now

**Comment by atifchy** [comment]
Don’t v1/vn on 6s.   use vs instead.

**Comment by ios11iphone6s** [comment]
@Cryptiiiic 
1. Installed Latest v3.0.0~b22(VS) , [Airplane=ON,RAM=clear,Restarted]
2. "LoadTweaks = OFF" , i see "jailbroken status" on "Jailbreak button" & it disappear in seconds then restarts everytime. (tried 2times for now)

@atifchy 
1.Sorry i used VS, typing mistake.

**Comment by Cryptiiiic** [comment]
@ios11iphone6s keep trying and post diagnostics.

**Comment by ios11iphone6s** [comment]
@Cryptiiiic @pwn20wndstuff 
1. Installed **v2.2.6(EL)** , Restarts at (34/38)(38/38) every time, [Tweaks OFF]

2. Tried nearly 12 times with (increase memory limit,TweaksOFF) , no use.

3. Don't know why it is not jailbreaking, I had no problem before **v3.0.0~b20(VS)** . 

Here is the Diagnostics file , Please look at it, i have noticed Jailbroken status(Diagnostics) on38/38 but device restarting 


[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2849672/diagnostics.plist.zip)

**Comment by ios11iphone6s** [comment]
i done "Restore RootFS(rec0ver)" on unc0ver v3.0.0~b26

it's fabulous , Thanks
