### ISSUE TITLE
[Request] Dark Theme

### ISSUE THREAD

**Issue by VeZReVouLiS** [pwn20wndstuff/Undecimus#347]
Hello,

I understand that this is something that can not be done right now as there are more important things to do, but it would be great if there was a dark theme sometime in the feature...

Thanks

**Comment by ios11iphone6s** [comment]
@VeZReVouLiS 
Jailbreak.ipa doesn't meant for themes

Use NoctisXI,Eclipse etc Tweaks (or) Request Tweak developers to make them.

**Comment by VeZReVouLiS** [comment]
@ios11iphone6s 

I don't know what you mean exactly, but i just recommended for the JB tool to have a dark theme beside of the default (white) by its own.

I don't know if the NoctisXI or Eclipse can do this...
I haven't tried them on Unc0ver.

Thanks for your answer though.

**Comment by preminemm** [comment]
Eclipse X does this very nicely

**Comment by Diatrus** [comment]
It’s kind of idiotic to recommend Eclipse for this purpose because you’re going to be using the jailbreak app when you aren’t jailbroken...

**Comment by preminemm** [comment]
Half light half dark mode 😂

**Comment by Samgisaninja** [comment]
I sorta wanted to do a complete redesign of the UI for iOS 12... this might be done at some point but it's not anywhere close to the top of my priority list.

**Comment by CoolPersonMaam** [comment]
Turn on smart invert colors XD then it will work and you got dark mode

**Comment by me246813579** [comment]
@Samgisaninja I tried doing my own redesign, but when I run it on my device, nothing is changed! what do I need to do?
