### ISSUE TITLE
Language Change

### ISSUE THREAD

**Issue by VeZReVouLiS** [pwn20wndstuff/Undecimus#348]
Hello,

Is there any way that you can support translations of the app in other languages?

Thanks

**Comment by ios11iphone6s** [comment]
@VeZReVouLiS 
Translations are not at ready for now, may or may not in future.
it's not necessary, Please raise a issue if you have anything with latest unc0ver.ipa

else 
Please add [Request] [Question] [Help] tags on Title.

**Comment by Cryptiiiic** [comment]
@ios11iphone6s this isn't reddit...

**Comment by Cryptiiiic** [comment]
@VeZReVouLiS It might happen but it isn't the focus right now.
