### ISSUE TITLE
Bootloop on beta v22 on iPhone 7, 12.1

### ISSUE THREAD

**Issue by ctalbot2004** [pwn20wndstuff/Undecimus#349]
Said that something had been renamed and it was going to reboot then went into a reboot loop.

**Comment by pwn20wndstuff** [comment]
This should have happened because you had a downloaded OTA update before trying it. The good news is that iOS 12.1.1~b3 (Which unc0ver can jailbreak) is still being signed by Apple and you should restore to it right now. Get your IPSW from https://twitter.com/Pwn20wnd/status/1093191940831567872.

**Comment by ctalbot2004** [comment]
I restored to iOS 12.1.1 beta 3 last and tried unc0ver again and it worked! Thanks.

**Comment by BaranGorcin** [comment]
I had the bootloop to but when i restore my device in storage i cant see OTA file how can i delete it? @pwn20wndstuff
