### ISSUE TITLE
b26 is not working on i7+ 12.1.2

### ISSUE THREAD

**Issue by xabbasoo** [pwn20wndstuff/Undecimus#354]
I tried to jailbreak with b25 without any luck
I only got snapshot renamed and my 7+ rebooted
after that, I tried to jailbreak without any success for countless of times.

Now I've tried b26 and still won't pass (2/38).
![2019_02_11_img_4338-min](https://user-images.githubusercontent.com/40974474/52551472-bf360b80-2ded-11e9-9a58-e27e86ee73be.JPG)

If it helps, my 7+ was jailbroken with yalu on iOS 10.1.1
did full restore using itunes to ios 12.0 -after bootloop on iOS 10.1.1-
and second restore using itunes also to iOS 12.1.2

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2850171/diagnostics.zip)

**Comment by IOSMR4twenty** [comment]
Enable Airplane mode before jailbreaking worked fine for me. I was getting stuck on 2 and kept rebooting...

**Comment by xabbasoo** [comment]
@IOSMR4twenty As you can see in the picture Airplane mode is already enabled before. I disabled Siri also.

**Comment by xabbasoo** [comment]
v3.0.0~b27 has fixied the issue.
