### ISSUE TITLE
Inject &  Libsnappy missing

### ISSUE THREAD

**Issue by userlandkernel** [pwn20wndstuff/Undecimus#355]
I'm trying to compile the project so I can add stuff but inject.h, inject.m and lib snappy are missing

**Comment by userlandkernel** [comment]
They're submodules, sorry I did not pay attention.

**Comment by me246813579** [comment]
How can I compile it?

**Comment by userlandkernel** [comment]
simply do this:


 git submodule init && git submodule update

to fix any compilation issues.

**Comment by mac-user669** [comment]
Sorry for the late reply, but thanks!

**Comment by wstclzy2010** [comment]
> simply do this:
> 
> git submodule init && git submodule update
> 
> to fix any compilation issues.

I got an error when I try to compile it, please help
`bunzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bunzip2: No such file or directory
	Input file = apt.modmyi.com_dists_stable_main_binary-iphoneos-arm_Packages.bz2, output file = apt.modmyi.com_dists_stable_main_binary-iphoneos-arm_Packages

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

bunzip2: Deleting output file apt.modmyi.com_dists_stable_main_binary-iphoneos-arm_Packages, if it exists.
Command PhaseScriptExecution failed with a nonzero exit code`
