### ISSUE TITLE
Cannot find patchfinder64.c, Will not build.

### ISSUE THREAD

**Issue by me246813579** [pwn20wndstuff/Undecimus#359]
I have tried compiling the V1ntex branch, and the master, and they all say the same thing:

`error: Build input file cannot be found: '/Users/me246813579/Desktop/Xcode/Undecimus/patchfinder64/patchfinder64.c'`

I am not sure how I can solve this, do I need to download [this](https://github.com/xerub/macho/blob/master/patchfinder64.c) and place it where it needs to be? 

Does this happen to everyone, or is it only me?

**Comment by Cryptiiiic** [comment]
@me246813579 
`git clone --recursive https://github.com/pwn20wndstuff/Undecimus.git`
