### ISSUE TITLE
Fatal erore on 5s ios11.4.1

### ISSUE THREAD

**Issue by mafi73** [pwn20wndstuff/Undecimus#361]
Hi,i have iphone 5S ios11.4.1; last beta(27) still give fatal error on step 27- line1620
Error num2
Fail ro extract boot startup
What i must do?

**Comment by Cryptiiiic** [comment]
@mafi73 post a screenshot and also post diagnostics file.

**Comment by mafi73** [comment]
@Cryptiiiic 

![photo_2019-02-13_10-31-07](https://user-images.githubusercontent.com/47586779/52693173-3947cb00-2f7b-11e9-93ce-ba4ca697cb55.jpg)

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2859208/diagnostics.zip)

**Comment by Cryptiiiic** [comment]
@mafi73 you need to rootfs restore since you updated to iOS 12 instead of restoring. Your iOS 8 jailbreak files are still there lol... Just turn on the rootfs restore switch.

**Comment by mafi73** [comment]
@cryptiiic thank you so much
But my storage like apps and cameraroll will be destroyed whit rootfs??

**Comment by coenkcore** [comment]
@mafi73 no, your user data like apps, photos is still there and unaffected.

**Comment by Cryptiiiic** [comment]
@mafi73 "root". This is the system fs. Contains no user data at all.

**Comment by mafi73** [comment]
@Cryptiiiic @coenkcore 
its done
iam jailberak my iphone sucssesfully thank U so much...

**Comment by Cryptiiiic** [comment]
@mafi73 yw.

**Comment by mafi73** [comment]
@Cryptiiiic hi agane
after every restart , my jailbreak gone.. and i must jailbreak my iphone agane;; is this normal?

**Comment by coenkcore** [comment]
@mafi73 It is normal.
After restart you must rejailbreak your device again.

**Comment by mafi73** [comment]
@coenkcore tnx
and other thing: honestly iam jailbreaked my idevuice for 1 resion: that is my "oters" storage on my iphone is almost 15GIGABAYE
thats a lot
iam searching for any twik that can manage this storage on my device
iam trying normal metod like cleaning telegram & instagram cach and remove imessage,voice memos &...
stiil oters are 15gig
becuse i have jailbroket my iphon 2year ago on ios 8.4 and thas file are still ther i tink
and plus i use i cleare pro twik,.,,,its workless only clean 300mb
please help me
