### ISSUE TITLE
Error jalibreak 11.4.1

### ISSUE THREAD

**Issue by adurza2** [pwn20wndstuff/Undecimus#362]

**Comment by adurza2** [comment]
Al instalar jalibreak desde uncover o Electra se me sale de la aplicación.

**Comment by adurza2** [comment]
Me pone un mensaje que pone “no tiene offsets para el iPad “

**Comment by adurza2** [comment]
Y se sale de la aplicacion

**Comment by adurza2** [comment]
![8cba3735-b4ab-4474-9189-d225a80e1a7d](https://user-images.githubusercontent.com/47613059/52748698-7d70b500-2fe7-11e9-9e58-e493f8faae6e.png)

**Comment by T4shf33n** [comment]
Try the the primary solutions.. like RetoreFS or rollectra 

Translation- Prueba las soluciones primarias...

I think it’s something with the patch finder. Try the latest version 

Prueba la última versión. @adurza2

**Comment by adurza2** [comment]
No funciona. Que pude pasar?

**Comment by king4q** [comment]
English only on issues please. @adurza2

**Comment by Samgisaninja** [comment]
It looks like you are using a beta release of iOS, please download [the IPSW for your version](
http://updates-http.cdn-apple.com/2018/iosseed/091-93792-20180702-30D8AFDC-7AE7-11E8-85EA-5422DA3C085A/iPadPro_9.7_11.4.1_15G5077a_Restore.ipsw) and extract the `kernelcache.release.ipad6b`. Rename it to `kernel` and place the file in unc0ver's iTunes File Sharing

pacere que usted está usando una beta versión de iOS... por favor, obtene [IPSW para su versión](
http://updates-http.cdn-apple.com/2018/iosseed/091-93792-20180702-30D8AFDC-7AE7-11E8-85EA-5422DA3C085A/iPadPro_9.7_11.4.1_15G5077a_Restore.ipsw). Extrae `kernelcache.release.ipad6b` y renombra a `kernel`. Ponga el expediente en unc0ver's iTunes File Sharing.

@king4q hehe, I took Spanish 3, 2 years ago, and I have google translate, hopefully that kinda made sense...

**Comment by adurza2** [comment]
Y como hago eso? Me podías ayudar?

**Comment by joanbono** [comment]
Hola @adurza2 .

(English version below)

Intentare ayudarte. Vamos a ver:

1. Descarga el IPSW del enlace de arriba o desde aqui: [ENLACE AL IPSW](http://updates-http.cdn-apple.com/2018/iosseed/091-93792-20180702-30D8AFDC-7AE7-11E8-85EA-5422DA3C085A/iPadPro_9.7_11.4.1_15G5077a_Restore.ipsw)
2. Extrae la imagen. Busca `kernelcache.release.ipad6n`. Para extraer, puedes usar [esta herramienta](https://github.com/blacktop/ipsw). Renombra el fichero a `kernel`. Te recomiendo que hagas una copia del archivo y renombres la copia.
3. Conecta el iPad a iTunes, selecciona la aplicacion unc0ver y arrastra el fichero anterior. Aqui apple explica como hacerlo: [Usa iTunes para compartir archivos entre tu ordenador y el iPhone, iPad o iPod touch](https://support.apple.com/es-es/HT201301).

Por ultimo, igual que Samgisaninja ha usado el traductor para escribir en castellano, deberias hacer lo mismo para escribir en ingles, ya que en GitHub hay usuarios de todo el mundo, y todos merecen saber la solucion, no solo los que hablemos castellano.


##########################
