### ISSUE TITLE
iPhone 7 on 11.4 boot loop

### ISSUE THREAD

**Issue by norperz** [pwn20wndstuff/Undecimus#364]
After attempting to jailbreak, asks for a restart and continues to run in a boot.

(on latest version)

**Comment by CreeDanWood** [comment]
same issue with me

**Comment by MegaminxCode** [comment]
@norperz @ CreeDanWood
Note that the jailbreak won’t work first try it may take multiple attempts.
Make sure you’re using the latest beta as the current public release doesn’t support iOS 11.4+

If the problem still occurs please give more detail. Post screenshots and share/post the diagnostics at the bottom of the settings page under restart in the unc0ver app.

**Comment by snowball7241** [comment]
@norperz just want to clarify. The definition of a bootloop is that your phone never boots up. Are you referring to this, or does the jailbreak just never succeed?

**Comment by CoolPersonMaam** [comment]
When creating a system snapshot it can take a while especially for older device just wait for it to finish restarting and then click jailbreak. If your saying it’s a bootloop that means it’s stuck on reboot and you will have to restore

**Comment by Cryptiiiic** [comment]
@norperz ^^^
