### ISSUE TITLE
Bootloop ios 12.1.1 after RootFS Restore b28

### ISSUE THREAD

**Issue by f0xhaulin** [pwn20wndstuff/Undecimus#366]

**Comment by xabbasoo** [comment]
RootFS Restore only supports iOS 11.0-11.4.1 :) !

**Comment by coenkcore** [comment]
Xabbasoo rootFS restore support all ios from 11 to 12.1.2.
I have try rootfs restore u0 3.0.0~b27 on ios 12.1.1 beta 3 it's not problem and work perfectly

**Comment by f0xhaulin** [comment]
Same here @coenkcore, prepared for FR, successfully went from 12.1.1b3-12.1.1. Something happened, I used uncover and it renamed the snapshot then reboot straight into boot loop.

**Comment by king4q** [comment]
@pwn20wndstuff @Cryptiiiic

**Comment by CoolPersonMaam** [comment]
i think you have ota updates installed..

**Comment by Samgisaninja** [comment]
Folks, make sure that there is no OTA update downloaded. We've since improved the checker for this, in the meantime, restore to 12.1.1b3 while it's still signed.
