### ISSUE TITLE
https://github.com/pwn20wndstuff/Undecimus/issues/165#issuecomment-456793026

### ISSUE THREAD

**Issue by sultttan** [pwn20wndstuff/Undecimus#368]
https://github.com/pwn20wndstuff/Undecimus/issues/165#issuecomment-456793026

**Comment by nevsm** [comment]
16.02.2019, 07:18, "sultttan" <notifications@github.com>:Closed #368.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
