### ISSUE TITLE
Boot loop op iOS 11.4.1 using 3.0.0 beta unc0ver

### ISSUE THREAD

**Issue by phooooon** [pwn20wndstuff/Undecimus#369]
Did not delete previous update. Now phone in unusable state. Any help appreciated

**Comment by king4q** [comment]
@sbinger

**Comment by king4q** [comment]
@phooooon restore to 12.1.1 Beta 3 it’s up to you to find out how.

**Comment by ZaWarud0** [comment]
What device do you have?
If you can, you can upgrade to 12.1.1b3 and downgrade back, or just wait, as u0 is coming out soon for 12.x.x

**Comment by MiladShojaei** [comment]
Me too - I have iPhone SE 11.4.1 with the last version of unc0ver v3.0.0 Pre-Release --- stuck at Boot Loop

thx unc0ver

**Comment by MegaminxCode** [comment]
@MiladShojaei whats seems to be the problem? Post screenshots and the diagnostics under restart in the unc0ver app.
I have an iPhone SE on 11.4.1 and It worked just fine. Make sure airplane mode isnt enabled.

**Comment by MiladShojaei** [comment]
@MegaminxCode 
it stuck at boot loop for good and I have to go 12.1.1 beta 3 /// so no way to try again and send diagnostics. thx

**Comment by king4q** [comment]
Turn off tweaks jailbreak & remove Substitute. I tried telling @Pwn20wndstuff this was a issue.

**Comment by king4q** [comment]
@Cryptiiiic please get Pwn to look into this & for substitute to be removed automatically if it’s installed.

**Comment by MiladShojaei** [comment]
> Turn off tweaks, jailbreak without tweaks on & remove Substitute. I tried telling @pwn20wndstuff this was a issue.

thx - but what can I do when it stuck at Boot Loop bro. I can't do anything except seeing Apple logo forever

**Comment by king4q** [comment]
@MiladShojaei so it won’t boot even in normal mode? Even after a hard reset? If so then dm me on Twitter I don’t want to spam this issue & everyone else here. @king4q1 is my twitter handle.

**Comment by CoolPersonMaam** [comment]
See if you can get WiFi on the device or open a connection so you can restore via iTunes

**Comment by MiladShojaei** [comment]
> See if you can get WiFi on the device or open a connection so you can restore via iCloud/find my Iphone so you don’t be lose firmware

good idea but I can't access anything / THX

**Comment by Samgisaninja** [comment]
Sorry folks, **PLEASE** check if there's an OTA update downloaded.

You can continue discussion but I'm closing this issue because it's not something that we can fix

**Comment by phooooon** [comment]
. I restored to ios 12 version that i can still jb. Cheers
