### ISSUE TITLE
Where can I find the ipa files of older releases, specifically v3.00b26?

### ISSUE THREAD

**Issue by Ap3xPrime** [pwn20wndstuff/Undecimus#370]
I was getting a "failed to extract bootstrap" error message and upon searching the issue on google, I found out that the problem can be solved by re-jailbreaking from the last release which worked for the user, which was v3.00 b26 in my case. However, I have searched everywhere and am unable to find the ipa file for the aforementioned release. If someone has it and can upload it on some cloud service or knows of a site which has all the releases on it, please let me know.

**Comment by FaZeBase** [comment]
Yeah sure

https://github.com/pwn20wndstuff/Undecimus/releases/tag/v3.0.0%25b26

**Comment by king4q** [comment]
This isn’t related to a issue within Unc0ver. @Cryptiiiic please close this issue.

**Comment by Ap3xPrime** [comment]
@king4q If that’s how you want to proceed, just assume that I didn’t ask for the ipa file and that I’m just a random guy who’s getting the “failed to extract bootstrap” error. Does that make this issue relevant to unc0ver? Will you help me out now?

**Comment by king4q** [comment]
Nope because this issue has been fixed & you’ve also used Electra which is part of the reason you’re getting this error or holding the volume up button while running the tool which breaks Unc0ver.

**Comment by king4q** [comment]
I sadly can not find any sort of IPA. If maybe @pwn20wndstuff has a IPA then he could give it to you or maybe @Cryptiiiic has it then he could maybe as well otherwise I cannot help. I’m sorry.

**Comment by Ap3xPrime** [comment]
@king4q Thank you for at least trying to help me out by searching for the ipa. I apologize if I failed to explain my issue properly, which is why I'll try again. Unc0ver is the only tool I used to jailbreak my phone. I never used Electra and don't intend to as well. Moreover, I have not been holding down any volume keys like you stated so that is most probably not the cause of my problem. All I did was jailbreak using b26, then install a faulty tweak which made my phone restart. Then I updated unc0ver to b28 and tried jailbreaking but it gave me the error which I previously mentioned.

**Comment by king4q** [comment]
Okay so then turn off “Load Tweaks” in the settings page & try that. If it does not work let me know.

**Comment by Ap3xPrime** [comment]
It didn’t.

**Comment by blanxd** [comment]
I've got a few iterations downloaded, b26 happens to be one of them :) https://happy.planet.ee/Undecimus-v3.0.0-b26_20190210-1453UTC.ipa
I'll remove the link some time after 2019-02-17 20:00:00 UTC.

**Comment by Ap3xPrime** [comment]
@blanxd You're a real lifesaver bro. Thanks a lot!

**Comment by Ap3xPrime** [comment]
Ok so rejailbreaking with b26 didn’t work out for me. I experienced the same error again. Therefore, I decided to play with the options a bit and after toggling on the restore rootFS, reset cydia cache, and reinstall cydia options, I was able to jailbreak successfully. However I had to start from scratch and reinstall all tweaks. Hope this helps anyone else out there with the same problem.

**Comment by king4q** [comment]
@Ap3xPrime I wanted you to update to beta 27 I think it’s the latest beta at the time of writing this. But I guess it’s fixed. If you have the same problem again please dm me on Twitter @king4q1

**Comment by Ap3xPrime** [comment]
@king4q The latest beta is b28 and I tried it before writing this issue but it didn’t work. Since my problem is solved now, I thank you for the concern you took to help me out. I will most definitely contact you if I encounter the same problem again.

**Comment by king4q** [comment]
Thank you. @Ap3xPrime
