### ISSUE TITLE
Does Not Work with IPad Mini 2 IOS 12.0 (4K)

### ISSUE THREAD

**Issue by Monn111** [pwn20wndstuff/Undecimus#371]

**Comment by king4q** [comment]
It does not support the iPad Mini 2nd Generation at this moment. Only the iPad Air 2 & iPad Mini 4th Generation are supported on IOS 12.0-12.1.2. @Cryptiiiic please close this issue

**Comment by Samgisaninja** [comment]
this device is not supported. That's intentional, not an issue.
