### ISSUE TITLE
all bank apps crash on ios 11.1.1 iphone x by using unc0ver 2.2.6 

### ISSUE THREAD

**Issue by neoneotw** [pwn20wndstuff/Undecimus#374]

**Comment by MegaminxCode** [comment]
Sorry man that’s called jailbreak detection. It’s a way of apps stopping jailbreak users from messing with them. At the moment I don’t think there’s anyway of bypassing it. @neoneotw
@Cryptiiiic Please close this issue

**Comment by king4q** [comment]
You can use tsprotector but i’m not sure if it’s compatibility with 11.1.1.

**Comment by Samgisaninja** [comment]
This is jailbreak detection, there's nothing we can do about this.

**Comment by neoneotw** [comment]
> This is jailbreak detection, there's nothing we can do about this.

that would be strange to me , last month I used version 1.1.x JB everything went fine with tweak Liberty lite which can anti jb detection.
