### ISSUE TITLE
lockdown.cpp:84

### ISSUE THREAD

**Issue by lecoleco** [pwn20wndstuff/Undecimus#377]
Hi,

I get this error on installation.

Error.
file: lockdown.cpp; line 84; what: LOCKDOWN_E_INVALID_SERVICE.

Iphone 7 PLUS

Cydia Impactor version is 0.9.51

How fix this? Thank you

**Comment by EliteAppleHacks** [comment]
https://www.reddit.com/r/jailbreak/comments/7wa84v/tutorial_how_to_fix_lockdowncpp57_cydia_impactor/

**Comment by CoolPersonMaam** [comment]
this is a problem with impactor that guy already posted a link but you can also use a signing service like ignition im not going to link it however

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all eta/wen/halp/etc to https://reddit.com/r/jailbreak or https://discord.gg/jb

**Comment by CLEVEROYANG** [comment]
hey bro,have u solved ur problem right now? i also meet it , and i didnt know how to deal with it either....

**Comment by poopyhed444** [comment]
why are you replying to an issue 2 years later ? you got some dedication tho, you can try to use altstore or something instead of cydia impactor.

**Comment by EliteAppleHacks** [comment]
Hes on internet explorer lol
