### ISSUE TITLE
ln: resources.deb: No such file or directory when compiling xcode project

### ISSUE THREAD

**Issue by EliteAppleHacks** [pwn20wndstuff/Undecimus#379]
Im trying to add a different resource deb version

Full code: 

> ~/Library/Developer/Xcode/DerivedData/Undecimus-agefbofakrzfyfazpokpadgnyllx/Build/Products/Debug-iphoneos/Undecimus.app/apt ~/Downloads/Undecimus-master
dpkg-scanpackages: info: Wrote 62 entries to output Packages file.
ln: resources.deb: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by CoolPersonMaam** [comment]
you don thave to compile it there is an ipa btw or you can pull request it and add the file you want

**Comment by EliteAppleHacks** [comment]
>you don thave to compile it there is an ipa btw or you can pull request it and add the file you want

@CoolPersonMaam well im trying to just replace the resources deb. Shouldnt i be able to without having to request them to make an ipa?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by newtoncircus06** [comment]
If you guys need for a extra A12 Xmax for initital testing or so, ive got 12.1.1 i can use xcode and and mailing from Japan. We people dont talk that much:) Just to let you know im more than welcome to use as test machine.

**Comment by Samgisaninja** [comment]
you need to pull submodules to compile unc0ver.

If you don't know how to do this, you probably shouldn't be trying to, please use the ipas over on [releases](https://github.com/pwn20wndstuff/undecimus/releases)
