### ISSUE TITLE
Can’t jailbreak with Reload System Daemons turned on

### ISSUE THREAD

**Issue by rctfan929** [pwn20wndstuff/Undecimus#381]
My issue is what the title says. It’s weird because this has not been an issue for many versions. Also, I’ve been using 3.0.0~b28 since it came out and never had to turn it off before.

iPhone 6s iOS 11.3.1
uncover version 3.0.0~b28

**Comment by Cryptiiiic** [comment]
Closing this(sorry) because there is an issue with more details. #495
