### ISSUE TITLE
Freeze in the morning, clock alarm issue, respring after 2 minutes

### ISSUE THREAD

**Issue by Marinamoina** [pwn20wndstuff/Undecimus#383]
iPhone 8, 11.3.1, unc0ver 2.2.6
Every morning after alarm clock starts, my lock screen and alarm display freeze and after 2 minutes it resprings and the safe mode mode is active. Sometimes LS freezes by just waking the display up, without alarm.
It happens with and without lock screen tweak like LockplusPro.

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all technical support questions to https://reddit.com/r/jailbreak or https://discord.gg/jb
