### ISSUE TITLE
iPad Pro 10.5 iOS 12 bootloop

### ISSUE THREAD

**Issue by jayb1239** [pwn20wndstuff/Undecimus#384]
Device boot looped after running beta 29. Will restore and try again, just thought I would post so that others were aware.

**Comment by Samgisaninja** [comment]
Folks, if you don't delete the downloaded OTA update, you will bootloop

**Comment by jayb1239** [comment]
@Samgisaninja There was no OTA on that particular iPad, plus updates were also blocked with an earlier version of Unc0ver. All sorted now anyway, the post was just to make you guys aware as the jailbreak had only just been released.
