### ISSUE TITLE
Failed to extract bootstrap unc0ver b29

### ISSUE THREAD

**Issue by CasparW** [pwn20wndstuff/Undecimus#385]
Failed to extract bootstrap 11-12.1.2 unc0ver b29

**Comment by DaneMacFadden** [comment]
I'm also having this issue. Gets to step 27 then gives me that notification.

**Comment by FU5E** [comment]
Same here. Any solution for this?

**Comment by DaneMacFadden** [comment]
I still haven’t figured it out but sometimes my phone restarts and doesn’t install Cydia, sometimes it just gets stuck on step 27. I’m on an iPhone 6s, iOS 12.1.1 beta 3

**Comment by Samgisaninja** [comment]
Does this still happen on the latest beta?

**Comment by dnogwat** [comment]
i have this problem with b40 on iphone 6
