### ISSUE TITLE
iOS 12 issues - reported by people

### ISSUE THREAD

**Issue by jakeajames** [pwn20wndstuff/Undecimus#388]
Nothing I experienced but many people are reporting:

- ldrestart causes a respring loop & then panic
- bootloops
- stuck on step 27 (airplane mode fixes it apparently?)
- ^ that's it for now

Just wanted to make a centralized place for discussing those issues

**Comment by FuadPoroshtica** [comment]
for step 27 try again and for me the 3rd time it worked

**Comment by pwn20wndstuff** [comment]
- Seems to happen when the device is hot
- Happens due to downloads OTA file and I already warned people about that
- No clue but it seems like restating fixes it

**Comment by jakeajames** [comment]
>Happens due to downloads OTA file and I already warned people about that

According to them, they had no updates downloaded @pwn20wndstuff

**Comment by pwn20wndstuff** [comment]
According to who?

**Comment by IObviouslyDontExist** [comment]
I don't have any OTA update stored on my device. It was blocked by your b28 to atleast SSH and FILZA into my phone via root.

**Comment by IObviouslyDontExist** [comment]
Is there a proper way to explain this directly to you, I have images on my twitter handle: here: https://twitter.com/TempAccountNull/status/1099077402762928129

**Comment by IObviouslyDontExist** [comment]
Is there a proper way to explain this directly to you, I have images on my twitter handle: here: https://twitter.com/TempAccountNull/status/1099071405021376516

**Comment by jakeajames** [comment]
@pwn20wndstuff everyone in /r/jailbreak said so

**Comment by jayb1239** [comment]
iPad Pro 10.5 12.0 no OTA, no prior jailbreak attempts with other tools, bootloop. Got as far as system snapshot renaming and never came back after that. Awaiting download of ipsw to restore however its taking a while as I'm on 4G at the minute, will try again when done if the beta signing window hasn't closed by the time this download eventually finishes! 7+ ran without issue though.

**Comment by FuadPoroshtica** [comment]
device shut down after enabling tweaks

**Comment by Nerfclasher** [comment]
Wifi is disabled when it works

**Comment by campbellcole** [comment]
> Wifi is disabled when it works

this same thing happens to me. wifi switch is greyed out in CC and settings, but rebooting phone re-enables it without issues.

**Comment by EricWagnerJr** [comment]
> > Wifi is disabled when it works
> 
> this same thing happens to me. wifi switch is greyed out in CC and settings, but rebooting phone re-enables it without issues.

Could you specify? Does wifi work after reboot after you jailbreak or is it in an unjailbroken state? I am having the issue where wifi will not allow me to enable it.

**Comment by vmpowercli** [comment]
Enable restore rootfs in the setting and re-run the jailbreak. It worked for me

**Comment by campbellcole** [comment]
I fixed it by disabling reload system daemons but i'm not sure if there's a better way to fix it

**Comment by coenkcore** [comment]
@jakeajames @pwn20wndstuff maybe airplane mode fix stuck on step 27, i have try for 5 times on ios 12.1.1 ip6s with airplane mode on and device succcessfully jailbroken.

**Comment by jakeajames** [comment]
@pwn20wndstuff it also appears that people who got bootlooped had OTA updates completely broken, they didn't have one downloaded, but going to software update settings throwed them an error like "cannot request" or something.

**Comment by jayb1239** [comment]
@jakeajames my updates were disabled via Unc0ver using one of the initial releases.
