### ISSUE TITLE
A7 and A8 Support planned? 

### ISSUE THREAD

**Issue by kevinishawesome** [pwn20wndstuff/Undecimus#389]
Just want to know if A7 and A8 support is in the plan?

**Comment by jakeajames** [comment]
How about reading pwn's tweets? Is it hard?

**Comment by JQ555888** [comment]
Yes they confirm they are working on supporting them. Please close this issue.

**Comment by kevinishawesome** [comment]
I didn’t see any tweet regarding A7 A8 till 3 hours ago... @jakeajames. Just because you’re a respected member of the jail break community, doesn’t mean you have the to be an asshole.. 

Thank you @JQ555888.

**Comment by jakeajames** [comment]
@kevinishawesome you saw it or not, that doesn't matter; you are *required* to do research before bothering devs with issue reports

**Comment by iM4CH3T3** [comment]
@kevinishawesome
Jakes means that github isn’t twitter.
And making an issue isn’t the same as making a post.
U only make issues if u have issues with the Jailbreak and if the issues doesn’t exist yet. If such an issue exist than comment to that issue.

**Comment by kevinishawesome** [comment]
I have mentioned before that I haven't seen it, I look it, I didn't find it, so made an issue just to confirm, then he tweeted a few hours later that a support is coming, so I closed the issue... That's all there is -------- Original Message --------Subject: Re: [pwn20wndstuff/Undecimus] A7 and A8 Support planned?  (#389)From: Jake James To: pwn20wndstuff/Undecimus CC: Kevin ,Mention @kevinishawesome you saw it or not, that doesn't matter; you are required to do research before bothering devs with issue reports

**Comment by kevinishawesome** [comment]
I know what he meant, you have to read my response again... I said I didn't find a tweet regarding A7 A8.. Pwn tweeted few hours later after I open this issue, so then I closed the issue.. Anyway its pointless to go on arguing about this, unless you have a lot of time.. -------- Original Message --------Subject: Re: [pwn20wndstuff/Undecimus] A7 and A8 Support planned?  (#389)From: iM4CH3T3 To: pwn20wndstuff/Undecimus CC: Kevin ,Mention @kevinishawesome

Jakes means that github isn’t twitter.

And making an issue isn’t the same as making a post.

U only make issues if u have issues with the Jailbreak and if the issues doesn’t exist yet. If such an issue exist than comment to that issue.
