### ISSUE TITLE
Cant select "MP" In Settings

### ISSUE THREAD

**Issue by FawkiDied** [pwn20wndstuff/Undecimus#39]
I downloaded RC7 fron the github updated the cydia impactor, Put it on my iphone 7 running 11.3.1  I was able to select MP the first time and the phone restarted half way through it (didnt jailbreak) then I was unable to select MP again.

**Comment by Samgisaninja** [comment]
“This isn’t a bug, it’s a feature”

You need to have an Apple developer certificate to use multipath. You can purchase one for $99 USD/year from https://developer.apple.com 

If the app detects that you don’t have a dev cert, it won’t let you use MP because it would never work.
