### ISSUE TITLE
Iphone X on 12.1.12 now bootlooping

### ISSUE THREAD

**Issue by JamieTheBiff** [pwn20wndstuff/Undecimus#391]
was a fresh restore. double checked to make sure no ota's were present on my device but sadly now its bootlooping for about 20 minutes now. Is there a fix to this or am i gonna have to lie to an apple store that it wasnt me xD

edit: mistype in title 12.1.2 was what my phone is on

**Comment by lancerevodrifter** [comment]
turn off "restart system daemons" in settings and try again

**Comment by JamieTheBiff** [comment]
Thats kinda hard when i cannot get my phone to turn on anymore. like i said bootloop e.g Apple shows for a couple seconds then repeats

**Comment by andrew123456789111** [comment]
Yes. The same issue happened to me. I am very upset as if i cant fix this then i have to go to a unjailbreakable version.

**Comment by lancerevodrifter** [comment]
if your phone isn't responding when you pressed jailbreak and all you get is a black screen, just press and hold up and down volume and then press and hold the power button until you get the apple logo back and get to the unjailbroken state when it restarts and the disable "reload system daemons"

**Comment by andrew123456789111** [comment]
Yes.

**Comment by JamieTheBiff** [comment]
basically yeah, i got to "bootstrap has been successfully extracted restarting device now." and bam bootloop

**Comment by JamieTheBiff** [comment]
Guess this is what happens when a commiunity pushes a dev too far. they release unfinished stuff

**Comment by andrew123456789111** [comment]
Yup i Agree. Now im stuck with a useless phone

**Comment by andrew123456789111** [comment]
kinda sucks

**Comment by JamieTheBiff** [comment]
yup

**Comment by JamieTheBiff** [comment]
well, ive decided to go ahead and load 12.1.11b~3 as it is still signed and my phone is fine. sadly hadnt backed up the data and cloned it to my new phone yet. (i did have it backed up but my pc had ssd failure) so at least it didnt brick it

**Comment by Aternias** [comment]
I had the boot loop problem to, go into DHU mode by holding the volume down and power button until the iTunes power cable icon comes up, your gonna have to restore your phone or upgrade to 12.1.4 :/ sorry

**Comment by Anatharias** [comment]
With blobs saved, you can just update your system partition to the system your iphone was previously on
I successfully updated my bootlooping iPhone X 12.1.1 to iOS 12.1.1 just using the -u argument in futurestore. [I left a quick tutorial about that on Reddit](https://www.reddit.com/r/jailbreak/comments/atrfq9/tutorial_futurerestore_your_bootlooping_iphone/)

On another hand, after updating the phone, I was able to get back, just like that never happened, and I recovered the diagnostics file, maybe Devs can find useful information in there:
[Diagnostics.plist](https://pastebin.com/kSPQy9m3)

Btw, thanks for having injected the 0x1111111111111111 nonce in NVRam before proceeding with rebooting the device. lifesaver!
