### ISSUE TITLE
iPhone 7+ running iOS 12.0 Bootlooped after installing Jailbreak.

### ISSUE THREAD

**Issue by andrew123456789111** [pwn20wndstuff/Undecimus#392]
Hi. My iphone 7+ has been bringing up the apple logo then shutting itself off. The phone seems to be bootlooped. I would like to know how i could fix this without reverting. I cannot get to the home screen to turn off any settings. i had no OTA's installed. Thanks.

**Comment by JamieTheBiff** [comment]
same happened too my spare X. was a fresh restore no ota's in site. now bootlooping on 12.1.2

**Comment by Aternias** [comment]
Happened to me too on my iPhone 7, had to completely restore my phone :(
