### ISSUE TITLE
failed to rename system snapshot iOS 12.X

### ISSUE THREAD

**Issue by heretofarmpp** [pwn20wndstuff/Undecimus#394]
https://imgur.com/a/hqvPzZb

**Comment by emro916** [comment]
go to settings and check you dont have the ios update installed

**Comment by emro916** [comment]
u can youtube it

**Comment by heretofarmpp** [comment]
you mean in storage? i have deleted it before jailbreaking

**Comment by JamieTheBiff** [comment]
jb is bugged, it bootlooped my phone that had nothing but ios 12.1.2 on it
