### ISSUE TITLE
Unc0ver app force crashes after jailbreaking

### ISSUE THREAD

**Issue by lancerevodrifter** [pwn20wndstuff/Undecimus#395]
After disabling "reload system daemons" and jailbreaking afterwards, I can't get Unc0ver to open at all and crashes upon opening, I tried using a signing program to reinstall, but the app would still crash upon opening.

**Comment by Samgisaninja** [comment]
What version, what device?

**Comment by Cryptiiiic** [comment]
No information given so closing.
