### ISSUE TITLE
Forced DFU mode iphone 8 plus ios 12

### ISSUE THREAD

**Issue by Trgrit** [pwn20wndstuff/Undecimus#397]
I was meet with an error and told to delete the tvos beta profile then restarted and reattempted to jailbreak it said it would restart the phone then it threw me into DFU mode

**Comment by iamn0tdev** [comment]
I jailbreak my i8+ without any issue (TVOS previously installed).

**Comment by Samgisaninja** [comment]
you will never be told to *delete* the tvOS beta profile, (and in fact, you should install it), force reboot the device, make sure there are no downloaded OTA updates, and try again.
