### ISSUE TITLE
iPhone 7 12.1.2 "Restart to create renamed device" Bootloop (forced to restore my phone :/)

### ISSUE THREAD

**Issue by Aternias** [pwn20wndstuff/Undecimus#400]
I deleted all OTA's and restarted my phone before embarking in this jailbreak, it made it to 2 and then a message popped up telling me the device would restart and rename itself, now it starts, shows the apple logo, the screen goes black for 5 seconds whilst showing a random white line on screen, then the whole phone turns off, repeat. It will do this infinitely and I am forced to activate DFU mode, and now my only option is to recover (which makes me feel stupid because I deleted my last backup -_-)

BEWARE!!

**Comment by kei-sidorov** [comment]
Same for me, 7+ 12.1.2

**Comment by BaranGorcin** [comment]
you can downgrade to ios 12.1.1 beta 3 it is still signed :)

**Comment by Samgisaninja** [comment]
Folks, please delete OTA updates before trying to do *anything* with this jailbreak.
