### ISSUE TITLE
Cydia crashes when opening - iPhone 6s Plus 12.1.1

### ISSUE THREAD

**Issue by M1ghtyBoy** [pwn20wndstuff/Undecimus#401]
Open Cydia and the app crashes straight away. Any help? IOS 12.1.1 iPhone 6s Plus

**Comment by M1ghtyBoy** [comment]
Reinstalled cydia only and it works now

**Comment by ankurspadale** [comment]
same issue here.

cydia works if u only choose 're-install cydia' in uncover.

but not tweaks working or showing in setting even if it shows installed correctly in cydia.
