### ISSUE TITLE
unable to rename system snapshot (Errno: 17) - iphone7+ 12.1

### ISSUE THREAD

**Issue by 100tomer** [pwn20wndstuff/Undecimus#402]
while the jeailbreak process there is an error 17 that says "Unable to rename system snapshot"
filename: "JailbreakViewController.m
Line 1181

**Comment by 100tomer** [comment]
Still happening in b30

**Comment by jeydm** [comment]
Same issue with iPhone X on 12.1

**Comment by Samgisaninja** [comment]
Duplicate of #394
