### ISSUE TITLE
ldrestart is unstable on iOS 12.X

### ISSUE THREAD

**Issue by 0xEmma** [pwn20wndstuff/Undecimus#403]
Was working, now gets to 27/28ish cant tell a pop up comes up saying its completed. then it crashes shows the respring logo for 2ish minutes then reboots

**Comment by IObviouslyDontExist** [comment]
** The Problem **
- This is a result of ldrrestart.

** The solution **
- Until a fix is made, turn off "restart system deamons" in uncover and re-jailbreak.

**Comment by VanishingTacos** [comment]
@IObviouslyDontExist 

turning off  "restart system deamons" puts me in safemode.

**Comment by VanishingTacos** [comment]
Removed Unc0ver, installed it again, turned off “reload system daemons” and now it works. 🤷‍♂️

**Comment by MatthewDSamms** [comment]
still not fixed on B32

**Comment by tsxmichael** [comment]
Turn off reload system and enable reinstall cydia and reset cydia cache and jailbreak again 💪🏽👍🏽

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andrewbestman** [comment]
B49 cannot jailbreak with reload system daemons turned off
