### ISSUE TITLE
com.apple.MobileSMS Crash buggy on b29 but semi works | Completely crashes on b41

### ISSUE THREAD

**Issue by TempAccountNull** [pwn20wndstuff/Undecimus#404]
### Jailbreaking with any of the following beta versions results in the following.
- b29 & b42*
- b30 - b41

The main problem: The breaking CSSymbolicatorRef's in dynamic libraries

### An Example of Symbolic linkage just crashing is below
- https://github.com/pwn20wndstuff/Undecimus/issues/604
- https://github.com/pwn20wndstuff/Undecimus/issues/404

FAULT: com.apple.MobileSMS
**Opening message app and sending the following crashes the app entirely**
- Using the microphone to send a voice text
- Typing long messages with using emoji's
- Having night mode activate and deactivate.

**Steps to reproduce this problem**
1. Step one: Open imessage
2. Step two: Go to an imessage contact (**will not work with a text or a user who has turned off imessages**)
3. Step three: click the microphone icon and try recording a voice message.

**Video of the crashes happening**
b30 footage
1. https://twitter.com/i/status/1099198301273051136
2. https://cdn.discordapp.com/attachments/500765231891611649/548758903622598686/Nick_boi_-_Video_of_the_microphone_crash_on_b30.mp4

b31 footage
- https://www.youtube.com/watch?v=8r6Snk8WyNY&feature=youtu.be

### Does this persist in stock iOS?
**No, This does not result after rebooting the device and not being jailbroken.**

**BUG NOTES**
Note: This crash can be halted by selecting another individual in your imessage contacts and holding the microphone button, and once un-held the application results in a crash.

**Miscellaneous Notes.**
- Using b29 or b42 (with Mach_swap) allows the use of the microphone by holding, but sends whatever is recorded when application crashes. 
- This is breaking anything using symbolic linkage.
- However using b30 through the recent b41 release completely crashes upon clicking or holding. This issue is still present.

**Root Causes**
- Error Formulating Crash Report: Failed to create CSSymbolicatorRef

### The Problem and why this is potentially happening
- It means that it can't link to a dynamic library. The most likely reason for this is that the offending executable was compiled against an incompatible SDK

### Crash Logs Zipped
- [substrated.wakeups_resource-2019-02-22-203654.ips.zip](https://github.com/pwn20wndstuff/Undecimus/files/2896570/substrated.wakeups_resource-2019-02-22-203654.ips.zip)
- [MobileSMS-2019-02-22-234854.zip](https://github.com/pwn20wndstuff/Undecimus/files/2896561/MobileSMS-2019-02-22-234854.zip)
[mediaserverd-2019-02-14-105706.zip](https://github.com/pwn20wndstuff/Undecimus/files/2896577/mediaserverd-2019-02-14-105706.zip)
- Full crash log list since first jailbroken on b29  to now b30
[MobileSMS b29 logs & b30 logs.zip](https://github.com/pwn20wndstuff/Undecimus/files/2896579/MobileSMS.b29.logs.b30.logs.zip)

### Crash Logs Images

- **Substrated**

![4vidc7wl jpg large](https://user-images.githubusercontent.com/11286901/53279548-09b16500-36d7-11e9-949d-300c0bf1e599.jpg)
![ktsbryn- jpg large](https://user-images.githubusercontent.com/11286901/53279551-0a49fb80-36d7-11e9-9067-4b92423ffac9.jpg)
![ppqqjpxe jpg large](https://user-images.githubusercontent.com/11286901/53279553-0a49fb80-36d7-11e9-9cb8-6ba400b644c1.jpg)

- **Mobile SMS**

![lt2p0icd jpg large](https://user-images.githubusercontent.com/11286901/53279552-0a49fb80-36d7-11e9-98f7-ab626ffda2c5.jpg)
![8055vwyt jpg large](https://user-images.githubusercontent.com/11286901/53279549-09b16500-36d7-11e9-9d24-98864ae2dd9b.jpg)

- **MediaServerd**

![ih9czko5 jpg large](https://user-images.githubusercontent.com/11286901/53279550-0a49fb80-36d7-11e9-8a1d-3a7036e65ca7.jpg)

**Comment by epkienen** [comment]
Nice find.. thought my phone was perfect with this JB, but I am having this issue as well.. Welp at least I don't use the MIC that much when sending message...  iPhone X 12.1.1

**Comment by IObviouslyDontExist** [comment]
10:13 - Push issue to top

**Comment by IObviouslyDontExist** [comment]
> Nice find.. thought my phone was perfect with this JB, but I am having this issue as well.. Welp at least I don't use the MIC that much when sending message... iPhone X 12.1.1

This issue results due to launchd. This also breaks any function using symbolic links because it simply cannot dynamically link to them.

**Comment by IObviouslyDontExist** [comment]
Push issue above.

**Comment by IObviouslyDontExist** [comment]
Push issue again, still present in b34

**Comment by TempAccountNull** [comment]
Issue pushed due to: b37 still having this issue.

**Comment by TempAccountNull** [comment]
Issue pushed due to: b38 still having this issue.

**Comment by TempAccountNull** [comment]
Push Issue still present in b39!

**Comment by TempAccountNull** [comment]
Issue is semi-present in b42 (with a workaround before crashing)

**Comment by ladiciuus** [comment]
Issue is present in B43.

**Comment by 2600box** [comment]
FWIW, this bug is not present on an iPhone XS with 12.1 and b46 (no substrate)
