### ISSUE TITLE
iPhone X - long respring and then reboot

### ISSUE THREAD

**Issue by 32two64** [pwn20wndstuff/Undecimus#406]
iPhone X
iOS 12.0.1

I installed filza, resprung and everything was normal. I then had to reboot my device, and i went to rejailbreak. Rejailbroke, clicked of, unc0ver closes. It then resprings but it stays on the loading circle for about 2-3 minutes and then reboots, unjailbroken. I also noticed this on rootlessjb.

**Comment by VanishingTacos** [comment]
I am getting the issue as well. Can not rejailbreak.

**Comment by KeyFlyz** [comment]
iPhone 8+ IOS 12.0.1 Same issue I just couldn’t get the jailbreak to enable after respring it would reboot to apple logo finally enabled airplane mode and it will do fine after second attempt but with airplane mode off it won’t jailbreak at all.

**Comment by L1cardo** [comment]
* turn off "restart system deamons" in uncover and re-jailbreak.

**Comment by VanishingTacos** [comment]
@L1cardo  that puts me in safe mode

**Comment by VanishingTacos** [comment]
Removed Unc0ver, installed it again, turned off “reload system daemons” and now it works. 🤷‍♂️
