### ISSUE TITLE
iPhone SE 12.1 Errno 0 "Failed to Extract Bootstrap" B29 - B30

### ISSUE THREAD

**Issue by SimpleCloudz** [pwn20wndstuff/Undecimus#408]
So recently I've been trying to use unc0ver as my jailbreak tool. This would not work. It constantly gives me an Errno 0, which displays as "Failed to Extract Bootstrap". This problem occurs with B29 to B30 even after switching some things off and on like load tweaks. In this case, B28 would create a jailbreak directory? I have no clue what that means but all I know is that it isn't installing Cydia or any JB.

**Comment by IMMILDEW** [comment]
Did you try going to unc0ver>Settings>Restore RootFS (rec0ver) and toggling it before jailbreaking??

**Comment by SimpleCloudz** [comment]
Thanks, my jailbreak is now running on iOS 12.1 with unc0ver while using that RootFS toggle.
