### ISSUE TITLE
Cydia sources refresh causing freeze and device restart

### ISSUE THREAD

**Issue by Chasewhip8** [pwn20wndstuff/Undecimus#409]
IOS 12.1.2 IPhone X

While refreshing sources in Cydia, the device completely locks up and reboots into an unjailbroken state.

**Comment by zirdum** [comment]
I have the same issue. On iPhone X 12.1.2. Installed jailbreak around 3:30PM. Issue occurred around 8:50PM. Opened Cydia (as I've done many times today). Sources were refreshing (but taking longer than usual). Took about 2-3 minutes before screen went completely black. Swiping nor buttons did anything. Waited about another 2-3 minutes and phone rebooted normally.

**Comment by Chasewhip8** [comment]
@pwn20wndstuff @sbingner Alos seen this issue discussed on discord a few times.

**Comment by HuChundong** [comment]
confirmed，iphone x，12.1.1 with b30

**Comment by Skilles** [comment]
Same thing on 12.1.2 iPhone X with b36

**Comment by Samgisaninja** [comment]
This seems to be very rare, but I have personally experienced this before.

**Comment by Cryptiiiic** [comment]
@Chasewhip8 @Samgisaninja I experienced this twice and I'm even on iOS 11.3.1(iPhone 6s). This has also happened in the Settings app so it seems like it is substrate related.

**Comment by tigerban** [comment]
iOS 12.1.1 iPhone X, phone freezes then reboots, this happens random times when opening Cydia and sources refresh, or when adding or removing a source. This happened with every release, even now on the last beta happens too. With or without tweaks. 

Everytime with this Crash log:

Date: 2019-03-01 10:38:00 +0000
Bundle id: com.apple.springboard
Exception type: NSUnknownKeyException
Reason: [<SBDashBoardView 0x143ada320> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _proudLockIconView.
Parent symbol: Foundation - 0x00000001d0e44440 <redacted> + 268

**Comment by rdc74656** [comment]
This happened to me today, iPhone 7+ 11.3.1 unc0ver 3.0.0 b39

**Comment by CoolPersonMaam** [comment]
Try enabling Increase Memory Limit(Beta) it does cause battery drain but some folks on Reddit says it helps

This has happen to me once but just force restart

**Comment by tigerban** [comment]
It happened also with increase memory limit. Now since b40 I didn't experience anymore freezes of this type. I'll continue testing and will post back if it happens again.

**Comment by Chasewhip8** [comment]
This is not the place for this argument
