### ISSUE TITLE
Storage Calculation Broken

### ISSUE THREAD

**Issue by ThinkDifferentunc0ver** [pwn20wndstuff/Undecimus#41]
Many devices tested,breaks storage calculation.Needs fix.Apps stop installing.Issue similar to Joseph Shentons breaking storage.

**Comment by Cryptiiiic** [comment]
@ThinkDifferentunc0ver make sure you are on the latest RC7

**Comment by Samgisaninja** [comment]
@Cryptiiiic not yet fixed

**Comment by SeMoOo** [comment]
@Cryptiiiic @Samgisaninja @ThinkDifferentunc0ver I fixed the problem on my device by restoring rootfs then jailbreaking with rc7 while disabling both update and app revoke options.

**Comment by ThinkDifferentunc0ver** [comment]
do the above

**Comment by marceloflix** [comment]
I’m having the same issue, i’m going to try @SeMoOo “fix” when i have no space left just to see how much of a problem this is and let’s hope there’s a way to fix this in a future version of this amazing jailbreak with the update and revoke options enabled!.
