### ISSUE TITLE
Cydia no network

### ISSUE THREAD

**Issue by L1cardo** [pwn20wndstuff/Undecimus#410]
Thank you very much for releasing the iOS 12 JB
But after my JB , there is Cydia , but no network permission for cydia.
I don't know if this is something to do with Chinese version iPhone 
please fix it

**Comment by clarityzzz** [comment]
yes, it is, the fix is somewhat burried on issues & google

**Comment by JQ555888** [comment]
This is a dulplicate of Issue #136. Solution’s there. Please close this issue.

**Comment by L1cardo** [comment]
@JQ555888  that is just a solution, not the really fix.

**Comment by JQ555888** [comment]
@L1cardo But that doesn’t justify making another post talking about the EXACT SAME THING. If you want to investigate into the issue & provide/ask for a viable fix, comment in the other post instead of making a new issue which confuses people. There’s already an existing pending fix in the other post. @pwn20wndstuff Someone close this issue please.

**Comment by L1cardo** [comment]
ok 
sorry to bother you

**Comment by JQ555888** [comment]
OK so i understand what you want is a temporary fix. 

The exact same words from the other opened issue,

> A workaround is to delete some Network Extensions files or using a VPN to bypass

> go to /Library/Preferences/, remove com.apple.network*.plist, reboot your device

> SSH into the device first and then “rm -rf /var/preferences/com.apple.networkextension.cache.plist”

Try one of the three methods provided and you’ll be good to go.

**Comment by clarityzzz** [comment]
@L1cardo you're not bothering mate, don't worry.
Did you try fix number 2?Does it properly work now? If so, a pull can be made to solve this if it doesn't have any negative impact on other stuff.

**Comment by Zanendra** [comment]
how do I ssh as cydia doesnt open to enable the ssh on iphone . Please help we are in trouble

**Comment by JQ555888** [comment]
@Zanendra Please read #136 to its entirety. I am well aware of the fact that OpenSSH is not bundled by default in the latest version of unc0ver as of 26 Feb. However, in that post we did suggest the use of a VPN service for temporarily bypassing that error, and then from there you can install OpenSSH or dropbear for secure shell, or whatever that’s needed to delete the preference files, say, Filza for example.

**Comment by JQ555888** [comment]
@Zanendra VPNs might not available in the Chinese AppStore, meaning that you’ll have to register an Apple ID for the US store, or anything that’s not mainland China. However, this VPN is not meant to bypass the firewall, so setting up one locally on device should do. No need to violate the regulations or anything.

**Comment by L1cardo** [comment]
> @L1cardo you're not bothering mate, don't worry.
> Did you try fix number 2?Does it properly work now? If so, a pull can be made to solve this if it doesn't have any negative impact on other stuff.

the fix solution works well
go to /Library/Preferences/, remove com.apple.network*.plist, reboot your device

**Comment by JQ555888** [comment]
@L1cardo Thanks for the feedback. C’est parfait :)
