### ISSUE TITLE
iPhone X lost jailbreak after successful jb

### ISSUE THREAD

**Issue by gt2416** [pwn20wndstuff/Undecimus#411]
I used uncover to jailbreak my iPhone X running iOS 12.1.2. It took about 5 tries and then cydia finally showed up. 
It did not open however and crashed immediately.  After selecting reset cydia cache and trying 3 more times it worked. 
I installed a few tweaks which worked only sometimes, so I decided to reboot. After the reboot, none of my tweaks showed up and cydia would not open. 
I tried more than 5 times to re jailbreak but after a reboot no tweaks show up and cydia doesnt open :/

**Comment by dippersauce** [comment]
It is my understanding that unc0vered is a semi-tethered jailbreak. It will require the device to be re-jail broke if hard rebooted.

**Comment by gt2416** [comment]
I did not realize it was semi-tethered jb, thanks ! 
You can close this now.
