### ISSUE TITLE
Getting "Unsupported" on iPhone 6 on 12.1.1 beta 3

### ISSUE THREAD

**Issue by dlr4life** [pwn20wndstuff/Undecimus#412]
Greetings, 

Thanks for your work on this repository, and others related to jailbreaking. **I have received the "Unsupported" message shortly after seeing the newer updates to this jailbreak on my very old daily-use iPhone 6 with 12.1.1 beta 3 installed. Is there a way to submit .plist file data other than the "Share Diagnostics Data" button within Settings?** I hope to upgrade soon, to be more adept with ARKit, but I am still interviewing for iOS Developer positions.

Thanks for reading!
An Engineering Developer
Darryl Reed

**Comment by Ultra03** [comment]
This is because A8 isn't supported yet, only A8X - A11 at the moment.

**Comment by dlr4life** [comment]
Ahh! Understood. Thanks!

**Comment by JQ555888** [comment]
Yep. They said on Twitter the current version doesn’t support A7 & A8 devices and they’ll be working on supporting them in the next update. So mmaybe we can close the issue for now. :)

**Comment by snowball7241** [comment]
@Cryptiiiic please close

**Comment by dlr4life** [comment]
Closing! Apologies. Was handling a coding challenge and missed this.
