### ISSUE TITLE
Cydia not starting

### ISSUE THREAD

**Issue by Kyledude252** [pwn20wndstuff/Undecimus#413]
Cydia is installed, but won't start. Reinstall Cydia, Reset Cydia Cache, and multiple restarts haven't worked.

**Comment by dippersauce** [comment]
I’m getting this bug as well. In the unc0ver app no matter how many times I redo the jailbreak it never shows “Re-Jailbreak” on the button. I suspect the jailbreak is not succeeding. I’m on a 2018 iPad, MR7J2LL/A.

**Comment by Kyledude252** [comment]
I wasn't even aware it was supposed to say "Re-Jailbreak", mine still says "Jailbreak" like yours. When I do the jailbreak, the steps get to 38/38 and for an ever so split second a large dialog box shows saying jailbreak successful so it seems like it should have worked?

**Comment by dippersauce** [comment]
> I wasn't even aware it was supposed to say "Re-Jailbreak", mine still says "Jailbreak" like yours. When I do the jailbreak, the steps get to 38/38 and for an ever so split second a large dialog box shows saying jailbreak successful so it seems like it should have worked?

I see the same behavior as well. On an iPone 7 plus and X, I see a “Re-Jailbreak” option if I reopen the app after jailbreaking. Here’s a link to my unc0ver diagnostics, compare it to yours and see if you notice anything. 

https://filebin.ca/4Xyb67PJJ98Y/diagnostics.plist

You’ll see towards the end it states the jailbreak was successful, so the issue may be something small.

**Comment by dippersauce** [comment]
I was able to resolve this issue on my device by surprise surprise, following the instructions. Ensuring Siri was disabled and Airplane mode resulted in successful jailbreak. I’ve attached am image of the “Re-Jailbreak” button I mentioned earlier. Double check your settings and let me know if anything is improved!  
https://imgur.com/a/k8cyx81

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all technical support questions to https://reddit.com/r/jailbreak or https://discord.gg/jb
