### ISSUE TITLE
Unc0ver Crashing

### ISSUE THREAD

**Issue by theWindowsGuy** [pwn20wndstuff/Undecimus#414]
I wont even let me open the application when I sign it to my device, Just closes when I try to open it.

**Comment by dippersauce** [comment]
Have you trusted the profile in Settings? Confirmed device compatibility? Using any prior jailbreaks?

**Comment by theWindowsGuy** [comment]
It's not even allowing me to JB because it just crashes before I can hit Jailbreak.

**Comment by IMMILDEW** [comment]
Have you trusted the profile in Settings>General>Profiles_and_Device_Managment??

**Comment by danhvuong** [comment]
I have the same problem when i tap on the icon it crashes

I have trusted in device management
I don't have OTA updates pending
and also installed os tv profile.
please help me!

Iphone X 12.1.1

**Comment by theWindowsGuy** [comment]
> 
> 
> I have the same problem when i tap on the icon it crashes
> 
> I have trusted in device management
> I don't have OTA updates pending
> and also installed os tv profile.
> please help me!
> 
> Iphone X 12.1.1

**Comment by theWindowsGuy** [comment]
A12 is not supported (Iphone X)

Also Cydia impactor was not updated was my problem it was on 0.9.44 latest was 0.9.51

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all technical support questions to https://reddit.com/r/jailbreak or https://discord.gg/jb
