### ISSUE TITLE
Failed to extract bootstrap

### ISSUE THREAD

**Issue by LainIwakuraBuddy** [pwn20wndstuff/Undecimus#415]
Goes to 27 then fails
Tried RestoreFS

**Comment by bstillitano** [comment]
Same here on iPhone X 12.1

**Comment by strangeliu** [comment]
![image 2019-02-23 13 51 48](https://user-images.githubusercontent.com/5244588/53283454-9e709d00-3781-11e9-8fc0-2b30a747babf.jpg)

Same here on iPhone X 12.1.2

**Comment by DaneMacFadden** [comment]
This was happening to me on iOS 12.1.1 beta 3, I reinstalled iOS 12.1.1b3 and then restored my backup and then tried again and Cydia was able to install.

**Comment by Samgisaninja** [comment]
If someone can tap "View Log", then copy and past the log into this issue, that would be helpful
