### ISSUE TITLE
(Informative) Unc0ver for iOS 12 is still beta. (Not an Issue)

### ISSUE THREAD

**Issue by Wanqed** [pwn20wndstuff/Undecimus#419]
It’s hencing to use at owns risk, read an issue of someone blaming people for pushing developers to release something unfinished, and was upset about a bootloop. Of course there are going to be problems with a new jailbreak on a new software version, it’s in beta for people who have test devices to report any bugs and help make the jailbreak as stable as possible. It is still a beta, there will still be issues. Not everything is perfect. The developers are kind and very fast responding and will help with issues in any way possible if provided the correct information and diagnostics logs, don’t freak out and blame it on everyone else. It is recommended to stay away from jailbreak betas (at least by me) and wait for a stable release of that version. I’ve been using unc0ver for the past 4-5 months and I am enjoying it, I have had problems yes but I haven’t blamed my problems on anyone else. And yes I was helped with my issues and I was happily redirected to a fix.

**Comment by Samgisaninja** [comment]
This is not a code-level issue and is therefore closed.

Please submit all technical support questions to https://reddit.com/r/jailbreak or https://discord.gg/jb
