### ISSUE TITLE
Crashes while jailbreaking

### ISSUE THREAD

**Issue by Marcel8x8** [pwn20wndstuff/Undecimus#421]
Its the 15. time i clicked on the jailbreakbutton but it always crashes between package 27 and 36. And then a restart last about 5 to 7 minutes.

Iphone X / A11 / v.12.1.2 / unc0ver b30

**Comment by coenkcore** [comment]
- try turn on airplane mode
- turn off siri
- run rootfs restore
- then try to jailbreak again

**Comment by Marcel8x8** [comment]
After i posted this my phone rebooted again and the little shutdown wheel stopped. Now its stuck there since 40min. what to do? :(
Wait for the battery is not good was barely full.

**Comment by coenkcore** [comment]
@Marcel8x8 try to force restart your device
make sure before jailbreak you have delete OTA file from setting - general - iphone storage then restart your device again.
then switch on airplane mode, turn off siri, run rootFS (switch on restore rootFS-recover from unc0ver setting) after success restore rootFS device will go restart.
then keep airplane mode on and siri off, clear all apps from apps switcher and wait for 1-2 minutes with keep unc0ver apps open and hit jailbreak.

hope you luck.

**Comment by Marcel8x8** [comment]
yes sure thanks but i can't restart my device now its just stuck.

**Comment by Marcel8x8** [comment]
ok thanks man i just did my hard restart wrong i pressed all buttons together. 
I had to click and leave up button the same with down button and then press and hold the power button. now it restarted without a problem.
