### ISSUE TITLE
ldid can't sign libraries

### ISSUE THREAD

**Issue by Archangel004** [pwn20wndstuff/Undecimus#423]
unc0ver b30 iOS 12.1.1, iPad 6th gen Wifi

Installing Python (which worked on iOS 11) causes "ldid unable to sign library" error while running DPKG (via cydia or using deb, 2 different debs even)

Error while using dpkg : 
```
ldid.cpp(693): _assert(): false
ldid.cpp(705): _assert(): Swap(mach_header_->filetype) == MH_EXECUTE || Swap(mach_header_->filetype) == MH_DYLIB || Swap(mach_header_->filetype) == MH_BUNDLE
dpkg: error processing archive python-v2.7.6-proteas-2015-11-30.deb (--install):
 ldid failed to sign libraries
```

**Comment by jakeajames** [comment]
Looks like it found an invalid library

**Comment by Archangel004** [comment]
Invalid how? Unsure because as I said, same library works on iOS 11 and iOS 10

**Comment by jakeajames** [comment]
Invalid as in invalid dude. Not a library but a corrupted file.

**Comment by Archangel004** [comment]
It's happening across multiple sources of Python. Same deb installs on 10.2.1 with no issue (and works)

**Comment by HSANNU** [comment]
Came here to confirm MacApollo’s version of Python works just fine on iOS 11 Electra (the one from his github repo just to make things clear).

**Comment by Archangel004** [comment]
Yeah, it was updated yesterday to work with the jailbreak.

**Comment by MCApollo** [comment]
DPKG/ldid was missing some files- .so (shared objects)- and incorrectly trying to sign some files- .o (object),  .dSYM (file says companion file).  Updates to dpkg should fix that.

The bigger issue is having to play nice with Coretrust (correct me if I’m wrong), not corrupted libraries.
