### ISSUE TITLE
Cannot install in iphone 6

### ISSUE THREAD

**Issue by anurag345** [pwn20wndstuff/Undecimus#426]
How to install it in iphone 6 ios 12 (A8) 
please help

**Comment by Dziqus** [comment]
It does not support iPhone 6 yet

**Comment by james-still** [comment]
_"A lot of people seem to be concerned about A7/A8 and A12 support on Unc0ver. Do not worry, nobody forgot about you, Pwn20wnd is working on adding both A7, A8 and A12 support in subsequent updates. Please wait patiently. It may take a few days and it's normal, but it will come."_ ~ **GeoSn0w**

**Comment by snowball7241** [comment]
@Cryptiiiic please close
