### ISSUE TITLE
Device stuck into respring. Cant reboot. Buttons donot working. 

### ISSUE THREAD

**Issue by Marcel8x8** [pwn20wndstuff/Undecimus#429]
Hey guys,
my phone is stuck in the respring mode. I tried to Jailbreak but then it failed between package 27 and 36.
Now my little respringtire (or wheel) whatever stopped turning and i can't reboot with my buttons. 
Any possible way to get out there? 
Thanks a lot.

**Comment by StijnSimons** [comment]
You sure you uninstalled the update OTA?

**Comment by Marcel8x8** [comment]
yes i am!
But just did the hard restart front now it works.

**Comment by Marcel8x8** [comment]
That problem caused after installing the Tweak : CleanHomeScreen

**Comment by KushTheDoosh** [comment]
Marcel please help me. I installed clean home screen and now I have the same issue...what do i do?
