### ISSUE TITLE
Bugs in cydia

### ISSUE THREAD

**Issue by ThinkDifferentunc0ver** [pwn20wndstuff/Undecimus#43]
1) While the installation screen is showing tapping on status bar takes it to top thus breaking the large-small tile on top.
2) DPKG locked issues(add inbuilt command for fix)
3) hash mismatch for cydia.lists
4) Uicache not working

**Comment by Samgisaninja** [comment]
1. Might be fixed, in the meantime, don’t tap the status bar?
2. DPKG_locked means that another process is using dpkg and therefore has “locked” it. If you can’t find which process this is, reboot or use ldrestart
3. Hash sum mismatch means that the maintainer of whatever repo it’s saying has the issue needs to update their Packages.bz2 to match their deb files. Please contact them instead
4. uicache is disabled except when needed intentionally as a performance enhancement. If cydia doesn’t automatically run uicache when it’s need it, run it yourself.

**Comment by Samgisaninja** [comment]
1. is also an intended feature, when you reach the top of any page, the title is supposed to change to be the iOS 11 style title
