### ISSUE TITLE
Issue with an iphone 6 on ios 11.4.1

### ISSUE THREAD

**Issue by vivanadal** [pwn20wndstuff/Undecimus#431]
Hi, first of all, thanks for all of the work ! since yesterday whey i try to jailbreak my iphone 6 on ios 11.4.1, it crashes alternatively at 16/38 or 36/38 , i tried it with release 29 & 31. same result.

And it said that it should work 

02/07/2019 - v3.0.0~b20 was released for public testing with the following changes:

iOS 11.1 - 11.4.1 support for A7/A7X/A8 devices with v1ntex by @tihmstar

Any suggestions ?

**Comment by Cryptiiiic** [comment]
No diagnostics or log given, so closing.
