### ISSUE TITLE
Cydia gets stuck on device on restore rootFS 

### ISSUE THREAD

**Issue by ben0wnz98** [pwn20wndstuff/Undecimus#432]
on both my ipad and iphone when restoring rootFS cydia icon gets stuck on the device without any way of removing it

**Comment by mikemike998** [comment]
Same issues people are having when they unjailbreak they can't remove cydia .

**Comment by tsxmichael** [comment]
Try GeoFilza ipa and in application see if u see cydia and delete that carpet 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikemike998** [comment]
> Try GeoFilza ipa and in application see if u see cydia and delete that carpet
> 
> Sent with [GitHawk](http://githawk.com)

Will that remove cydia from the device ?

**Comment by tsxmichael** [comment]
>> Try GeoFilza ipa and in application see if u see cydia and delete that carpet ...

@mikemike998 yes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
Just install GeoFilza and in the first page used the search typing cydia and delete any cydia document!! Won’t affect your phone cause you delete the jailbreak already 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ben0wnz98** [comment]
I found that the app was deleted but uicache wasnt done i rejailbroke deleted the app used terminal to run uicache then restore rootFS and it was removed

**Comment by mikemike998** [comment]
I can't remove cydia from my phone .

**Comment by Cryptiiiic** [comment]
You have to reset Cydia cache, closing.

**Comment by mikemike998** [comment]
I did .

**Comment by mikemike998** [comment]
Still don't delete .

**Comment by mikemike998** [comment]
I have fixed it by watching this video https://www.youtube.com/watch?v=lsFGzCvM4dY .
