### ISSUE TITLE
Version b31 failing to JB iPhone-6 on 11.4.1

### ISSUE THREAD

**Issue by DavidNC1978** [pwn20wndstuff/Undecimus#433]
The new version b31 isn't jailbreaking my iPhone-6 on 11.4.1, for some reason it shows running thru all 38 processes every time without issue, it even downloaded the Kernel Cache form Apple.  But each time it runs thru the 38 processes it just simply reboots my phone into stock mode.  I've had to re-sideload version b28 again to get my JB back working.  Not sure if there is any log files I can send you.  I am MetrolinaAlerts on twitter I helped you test on my iPhone-6 11.4.1 right before you released the JB for A8 support...  Thank you.  Not sure if anyone else is having this same issue...

**Comment by archfan** [comment]
I have the same issue on my iPad Pro with iOS 12.1.1

**Comment by yaf3i** [comment]
what is the success rate for iPhone 6 11.4.1 with b28 ?

**Comment by Cryptiiiic** [comment]
No diagnostics given or logs, so closing.

**Comment by DavidNC1978** [comment]
With version b28 I was usually having to do it multiple times. Usually by #6 or #7 it would finally JB.  For some reason Unc0ver kept rebooting my phone randomly at night when my power cord was connected and a few days ago it sent me into a bootloop where my phone wouldn’t even restore.  I has to get an iPhone-6S and i downloaded the new version b38 & it has greatly improved success rate!
