### ISSUE TITLE
iPhone 6s Cydia Doesn't Open And Update Problem

### ISSUE THREAD

**Issue by ShutNSmoq** [pwn20wndstuff/Undecimus#434]
I tried to reinstall and cleared cache but after a phone restart I can't open it and after the jailbreak there is a software update called ios 12.1.4 and it says update requested and it is still like that please help me

**Comment by NickyPan** [comment]
same problem here...
iphone6s with version b31

**Comment by jakeajames** [comment]
Enable the jailbreak dude

**Comment by NickyPan** [comment]
ok, I solved my problem. Actually, I should click jailbreak again after cydia was installed first time.
Thanks for the tip. @jakeajames

**Comment by ShutNSmoq** [comment]
When i shutdown and open my device my cydia stops working

**Comment by jakeajames** [comment]
@ShutNSmoq it's normal. You have to jailbreak again after you shutdown/reboot

**Comment by Cryptiiiic** [comment]
Learn common sense please, closing.
