### ISSUE TITLE
Jailbreak impossible!

### ISSUE THREAD

**Issue by Marcel8x8** [pwn20wndstuff/Undecimus#435]
I still jailbreaked it hours ago BUT i made a reboot. 
Then... Cydia was installed and its still on my Phone but unc0ver can't extract Cydia when its on the Phone. So can't jailbreak anymore. Ant i can't get any Lydia eraser. 

Please Help.

**Comment by jakeajames** [comment]
Use "rootfs restore" in settings

**Comment by coenkcore** [comment]
@Marcel8x8 restart your device and turn on rootFS Restore (recover) then push jailbreak button, wait for process to complete and device will be restart.
after device restarted run u0 app again and wait for 1-2 minutes then push jailbreak button again.

**Comment by Cryptiiiic** [comment]
No information give, so closing.
