### ISSUE TITLE
Unsupported on iphone XR ios 12.1.1

### ISSUE THREAD

**Issue by danyz124** [pwn20wndstuff/Undecimus#436]
i have an iphone XR on ios 12.1.1 and i go to the app and it says unsupported for some reason

**Comment by StijnSimons** [comment]
The jailbreak is only for devices from A8-A11. Your device has an A12 chip.

**Comment by danyz124** [comment]
> The jailbreak is only for devices from A8-A11. Your device has an A12 chip.

but doesnt the iphone XS have an A12 chip in it and i saw it work on that phone

**Comment by jakeajames** [comment]
>but doesnt the iphone XS have an A12 chip in it and i saw it work on that phone

YES! That's exactly why it isn't supported! DEAR!

**Comment by danyz124** [comment]
> > but doesnt the iphone XS have an A12 chip in it and i saw it work on that phone
> 
> YES! That's exactly why it isn't supported! DEAR!

well if they both have the same chip how come it works on one phone and not the other

**Comment by coenkcore** [comment]
for now just support on iOS 12.0 - 12.1.2 for **A8X-A11 devices**
please read notes on release 3.0.0~b29

**Comment by HSANNU** [comment]
“Omg I think I just discovered a new way to bother developers for A12 support” /s

**Comment by tsxmichael** [comment]
Oh boy 🤦🏽‍♂️ do people forgot to read on those times!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by snowball7241** [comment]
@Cryptiiiic please close
