### ISSUE TITLE
Sandbox issue?

### ISSUE THREAD

**Issue by ca13ra1** [pwn20wndstuff/Undecimus#437]
Just testing some of my tweaks and noticed my tweak Selectmoji isn’t being injected into 3rd party apps just the stock apps. Unsure if this has been resolved or not? I had this issue before when Electra was released but was eventually fixed. I’ve double checked my code, headers, and no changes were made. My tweak is working fine on iOS 11 jailbroken with unc0ver.

**Comment by jakeajames** [comment]
Where does your tweaks install its files?

**Comment by ca13ra1** [comment]
It’s the same location I used in the unc0ver jailbreak for iOS 11. Library/MobileSubstrate etc 
https://m.imgur.com/a/19l56tv

**Comment by ca13ra1** [comment]
Turns out it’s HBPreferences causing the issue. Since it’s not working in sandboxed processes in iOS 12
