### ISSUE TITLE
cydia sub-process dpkg error code(2) couldn't record the approved state changes as dpkg selection states 

### ISSUE THREAD

**Issue by ben0wnz98** [pwn20wndstuff/Undecimus#438]
can install tweaks fine but when try to uninstall get this error:
cydia sub-process dpkg error code(2) 
couldn't record the approved state changes as dpkg selection states 

and when restore rootFS doesnt fix the issue at all and tweaks remain

**Comment by Cryptiiiic** [comment]
Try resetting Cydia cache. No usable information given, so closing.
