### ISSUE TITLE
Cydia, iPhone settings and other apps opening delay

### ISSUE THREAD

**Issue by adityameena26** [pwn20wndstuff/Undecimus#442]
It takes 6-8 seconds to opening cydia first time after reboot/respring. Same is with settings menu and other apps as well.

**Comment by ahmedgharibmorsy** [comment]
hi i want make cydia

**Comment by vitalik2187836** [comment]
The same goes for iPad pro 12.9 2nd gen ios 12.1. Can send diagnostics, if needed.

**Comment by Cryptiiiic** [comment]
No information given, so closing.

**Comment by vitalik2187836** [comment]
Well, you didnt ask for any type of information. This problem still persists with latest uncover release. With or without tweaks. I can record a video if needed but there were already some on reddit. What else i can do to help you fix this problem?
