### ISSUE TITLE
iPad7,5 iOS 12.0.1 -- 3.0.0b33

### ISSUE THREAD

**Issue by joanbono** [pwn20wndstuff/Undecimus#443]
Hi guys, 

Thanks for the amazing job you did with unc0ver.

Just one thing. I'm using iPad7,5 (iPad 2018) with iOS 12.0.1
+ ✅  **unc0ver 3.0.0b30** works fine.
+ :x: **unc0ver 3.0.0b31** is not working.
+ :x: **unc0ver 3.0.0b32** is not working.
+ :x: **unc0ver 3.0.0b33** is not working.

I'm back on 3.0.0b30. If you need testing or something, let me know, I'd like to help here.

Thanks

**Comment by TheNoim** [comment]
I experienced the same with iPad 7,4.
Here my diagnostic data
https://gist.github.com/TheNoim/d3c36e00a8a2ce666d3ae6bdd6fd4149

**Comment by joanbono** [comment]
EDIT:

Still not working using b33 enabling RootFS
