### ISSUE TITLE
Cydia is completely not working.

### ISSUE THREAD

**Issue by muradnaji** [pwn20wndstuff/Undecimus#444]
Cydia is always on bootloop. Tried reinstalling unc0ver and re-jailbreak and when it on the loading screen it takes 2 minute and crashes. Cydia crashes every time I open it. I'm on 12.1.2. Plz help.

**Comment by W4rW1nG** [comment]
same problem here. cydia is not working after rebooting the device.
tried unc0ver jailbreak again. still not working at all.

**Comment by arcreigh** [comment]
Restore RootFS, reboot your phone and then re-attempt the jailbreak.

**Comment by muradnaji** [comment]
Thx arcreigh, ill try that when I get home.

**Comment by shahbazgithub87** [comment]
This worked for me

**Comment by muradnaji** [comment]
I have attempted this twice, both failed. Is there another way?

**Comment by shahbazgithub87** [comment]
Yes there is .... i managed somehow.... ill write as far as remember
1. recover from rootfs option (unjailbreak kind off).... had to do this 2,3 times.
2. Once unjailbroken... jailbreaked again... again this took a number of attempts
3. now once jailbroken again... no repos were working (became blank, without packages) including big boss.
4. removed all repose.... cleaned cydia with icleaner
5. Now voila!! all sources started workinf

**Comment by muradnaji** [comment]
Thank you. I tried this however the same issue is happening. Cydia keeps crashing on boot. Any other option?

**Comment by shahbazgithub87** [comment]
dont know man...i too am a noob

**Comment by ankurspadale** [comment]
same issue here.

cydia works if u only choose 're-install cydia' in uncover.

but not tweaks working or showing in setting even if it shows installed correctly in cydia.

**Comment by muradnaji** [comment]
Thank you for all comment but I have figured it out thanks to support by shahbazgithub87. Follow his procedure listed above ensuring that the Rootfs option is in the correct state every time. I did this 9 time until successfully opening Cydia without crashing. Thank you shahbazgithub87! 😁
