### ISSUE TITLE
iPhone 8,1 iOS 12.1.1 with v3.0.0~b32 get respring loop

### ISSUE THREAD

**Issue by baobaoit** [pwn20wndstuff/Undecimus#445]
Like the title, I have turn off the option `Reload System Daemons` for v3.0.0~b32 to work. 
Thanks!

**Comment by tsxmichael** [comment]
Enable reinstall cydia and reset cydia cache too and try to jailbreak again! 👌🏽👍🏽

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by baobaoit** [comment]
I have to use b31 and it was fixed! Thanks!!!
