### ISSUE TITLE
iPhone 8 WIFI problems iOS 12.1

### ISSUE THREAD

**Issue by t6nak** [pwn20wndstuff/Undecimus#447]
After updating from b29 to b32, WIFI won't work while jailbroken

**Comment by truebydefault** [comment]
This happens to my iPhone 7 GSM and I just toggle WiFi off and on from the settings app then wait for it to connect. That seems to fix it. 

Sometimes it will say my password is wrong as well and that problem goes away after a reboot.

**Comment by t6nak** [comment]
Unfortunately the WIFI button is grayed out, so I can't toggle it from settings or from cc

**Comment by Chasewhip8** [comment]
@t6nak I can also confirm this issue. @pwn20wndstuff @sbingner

**Comment by Chasewhip8** [comment]
A full device restart and re-jailbreak seem to have fixed the issue as of now.

**Comment by elektromouse** [comment]
i have same problem 
ipad mini 4, ios 12.0.1
reboot and re-jailbreak doesn't help 
no twiks except appsync

**Comment by t6nak** [comment]
Which version of unc0ver are you using?

b29 and b30 doesn’t have that issue for me,
I got my wifi working on b32 with airplane mode on, reload daemons(off, wifi works always)(on, works sometimes, a lot of respring loops).
Haven’t tested the newer versions, b30 is running smoothly for me.
