### ISSUE TITLE
iPhone X, iOS 12.1.1b3 - 3.0.0-b32 puts my phone in a respring loop

### ISSUE THREAD

**Issue by KillswitchOne** [pwn20wndstuff/Undecimus#448]
To make unc0ver work I have to turn off "Reload System Daemons", when it is enabled it says the jailbreak is successful, then it resprings for a couple minutes and suddenly reboots and I have to start all over.

**Comment by icymichael** [comment]
Do the same again but this time enable reinstall cydia and reset cydia cache and jailbreak! 👌🏽👍🏽

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KillswitchOne** [comment]
@icymichael Thanks for responding! Will I lose my tweaks when doing that?

**Comment by tsxmichael** [comment]
I don’t think 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KillswitchOne** [comment]
@tsxmichael Okay, thanks but it unfortunately doesn't work for me.

**Comment by tsxmichael** [comment]
🤦🏽‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
Try again! If not them go back to the beta you have before 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KillswitchOne** [comment]
Downgrading to v3.0.0-b31 does the trick for me. Now it works with "Reload System Daemons" enabled.

**Comment by tsxmichael** [comment]
Perfect 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by StijnSimons** [comment]
I have the same thing on my iPhone 6S, it worked before on B31 but it doesn’t with the latest one. Guess i’m gonna downgrade

**Comment by KillswitchOne** [comment]
@StijnSimons Yeah b29-b31 worked for me too, but b32 screwed it up. Seems like downgrading is the only option for now :)

**Comment by StijnSimons** [comment]
I tried downgrading back to b31 but it still doesn’t work.
Enabled settings:
- Load Tweaks
- Load Daemons
- Dump APTicket
- Disable Auto Updates
- Disable App Revokes
- Reload System Daemons

**Comment by KillswitchOne** [comment]
@StijnSimons b31 works for me with the same settings as you with one exception, "Overwrite Boot Nonce" is also enabled in my settings.

**Comment by StijnSimons** [comment]
Forgot that setting^

**Comment by tsxmichael** [comment]
Using the beta32 you have to repeat the way I explained 2 to 3 times and will work perfect 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KillswitchOne** [comment]
@tsxmichael well honestly if the update thats supposed to fix respring loops is the first update that causes respeing loops for me, i might as sell stay at b31 until its fixed

**Comment by StijnSimons** [comment]
Apparantly, it was a problem with a tweak i installed. I disabled 'Load tweaks' and uninstalled it.

**Comment by tsxmichael** [comment]
Yes but you have already cydia install and the best way to do is reinstall cydia to take effect!! I been helping alot people in Twitter and its been working perfectly! But if the beta 31 works for you then why the risk right! 😌 if you see when you do that method in the first try will stop by 16 of 38 then the second one will stop by 27/38 then should work perfectly! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KillswitchOne** [comment]
@StijnSimons would you mind telling me what tweak it was? Happy you fixed it!

**Comment by KillswitchOne** [comment]
@tsxmichael very good that you’re helping the community out! i appreciate your input on this issue too, but i think ill stick to b31 for now.

**Comment by StijnSimons** [comment]
@KillswitchOne The tweak was called AutoTouch or something like that. Problem might occur in other tweaks aswell.

**Comment by HSANNU** [comment]
Pwn has removed b32 as it’s considered broken so stick with b31 for now.
