### ISSUE TITLE
Temp respring loop

### ISSUE THREAD

**Issue by 5Blue** [pwn20wndstuff/Undecimus#452]
When I got the new version of uncover b32 after clicking jailbreak and getting the success message it put phone into respring loop until you power it off and on

**Comment by 6papi** [comment]
same thing happen to me .cydia kept crashing after I tried installing a tweak and uninstalling a tweak so I rebooted and blah blah blah , I downloaded the updated 32 version and got stuck on a temporary respring loop after I tried jailbreaking again, luckily it got out of it.

**Comment by 6papi** [comment]
btw I was on beta29 when the Lydia crashing started happening
