### ISSUE TITLE
PHOTOS AND SAFARI FORCE CLOSE

### ISSUE THREAD

**Issue by v3rBaLcRiMiNaL** [pwn20wndstuff/Undecimus#455]
Whenever you click the little share icon (box with the arrow in it) in photos or safari like if you wanna share or save something the app will force close

**Comment by jlippold** [comment]
To piggy back off this: https://reddit.com/r/jailbreak/comments/au4lf5/question_cannot_share_or_edit_photos_after/

It’s probbaly a related issue?

**Comment by jlippold** [comment]
@Cryptiiiic is this fixed in the latest build?
