### ISSUE TITLE
unc0ver crash after reboot

### ISSUE THREAD

**Issue by luosuonan** [pwn20wndstuff/Undecimus#456]
2/38，no offsets for iphone

**Comment by johnweisz2112** [comment]
Do you get this error?

[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported

**Comment by luosuonan** [comment]
system/library/watchdog/thermalmonitor.bundle 
i use tweak change the file，then crash

**Comment by atfunderscoreyt** [comment]
Yah, I got that error. Know how to fix it?

**Comment by luosuonan** [comment]
still crash
