### ISSUE TITLE
Strange Cydia/Substrate issue - iPhone X 12.1.1

### ISSUE THREAD

**Issue by ankurspadale** [pwn20wndstuff/Undecimus#464]
after first successful jailbreak, cydia crashes as I open it.
then in uncover setting, select only reinstall cydia and jailbreak then cydia works and tweaks install successfully, for test I try BetterCC.
But now tweaks are not showing in setting app or not working but showing installed in cydia.

What could be wrong here?

**Comment by ankurspadale** [comment]
Here is my uncover diagnostics data:

[diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2897582/diagnostics.plist.txt)

**Comment by K1llah03z** [comment]
Did you install preferenceloader?

**Comment by bevzyy** [comment]
I’ve got the same issue! This is so annoying! Can someone please find a fix? I reinstalled cydia and re jailbroke, didn’t fix it. Re installed in preferenceloader as well, yet no.

**Comment by Cryptiiiic** [comment]
@ankurspadale bettercc is pirated, this is most likely causing the issue, remove the pirated version, then remove your 3 pirate repos, then post back results. Closing this due to not related to unc0ver.
