### ISSUE TITLE
Problems download apps AppStore 

### ISSUE THREAD

**Issue by sharklatan** [pwn20wndstuff/Undecimus#467]
I have  problems for download apps on AppStore in Jailbreak mode
But no Jailbreak mode download/update apps normal

**Comment by Slayer741** [comment]
Yeah, same here on 2 devices, also, sometimes it just works and other times its broken.  very weird thing indeed

**Comment by xuefer** [comment]
12.1.1beta3
unc0ver 3.0.0~b45

verification pop up asking password, after which telling me it will send verification code to my phone, but there's no verification code input dialog on the phone (it will verify using alipay.com on not-jailbroken device)

**Comment by xuefer** [comment]
looks like "opener tweak" issue
