### ISSUE TITLE
After Turned off back on jailbreak has gone and can't jailbreak again

### ISSUE THREAD

**Issue by ByKrCl** [pwn20wndstuff/Undecimus#468]
I successfully jailbroke my IPhone SE  witb Unc0ver 3 beta 30. I installed tweaks. When I was going to sleep, I turned off my device. When turned back to on, all of installed tweaks were not working. Tried to open cydia crashed. I opened Unc0ver, but it says Jailbreak, not Re-Jailbreak, and I clicked Jailbreak. it completely finishes process the special thanks(I couldn't see) message pops up, device starts to respring, then it reboots. When system booted again no tweaks, and jailbreak. IOS 12.1.2

**Comment by ByKrCl** [comment]
Here my diagnostics 
[attachment 1.plist.tar.gz](https://github.com/pwn20wndstuff/Undecimus/files/2897622/attachment.1.plist.tar.gz)

**Comment by ByKrCl** [comment]
Ok, I read pther issues and I jailbreak with reset cydia cache, reinstall cydia, and not loading tweaks. it's Jailbroken, but how to load tweaks, without getting crush and reboot after successful jailbreaking?

**Comment by CoolPersonMaam** [comment]
I have experienced this glitch too on my iPhone 6 when it runs uicache it restarts. However upgrading unc0ver to the latest version fixed my issue
