### ISSUE TITLE
Safe mode on every sms 

### ISSUE THREAD

**Issue by Vanquished79** [pwn20wndstuff/Undecimus#470]
So since updating to b31 and now 32, every time I get an SMS or IMessage the phone goes into safe mode, it happens as soon as the sms or iMessage is received (not opened) just received, I’ve looked at all the tweaks and I don’t have any messages related 

iOS 12.1.1 iPhone 8+

**Comment by T4shf33n** [comment]
Try updating to b~33? Or back to b~31?

**Comment by Vanquished79** [comment]
It was happening on B31, so updated to B33 and it still happens, not sure what’s causing it.

I’m going to remove all tweaks one by one to see if it’s a tweak causing it but I have no tweaks that are message app related

**Comment by Vanquished79** [comment]
So I gave up removing each tweak one by one and then having a sms and imessage sent to me to see if it would crash and just re-jailbroke and reinstalled cydia now it doesnt crash when receiving a message so it must have been one of the tweaks installed. 


This can be closed!
