### ISSUE TITLE
Unsupported iOS 12.1.1 beta 3 iPhone XS?

### ISSUE THREAD

**Issue by Eddie821** [pwn20wndstuff/Undecimus#472]
I keep on getting this error message 
-canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
When using the in app jailbreaker.
Pls help

**Comment by sportusrcu** [comment]
LoL a12 currently not supported.

**Comment by HSANNU** [comment]
XS has the A12 chip which is going to be supported in the future but not yet

**Comment by snowball7241** [comment]
@Cryptiiiic please close
