### ISSUE TITLE
Ios 12.1.4 Update Requested Stuck After Jailbreak

### ISSUE THREAD

**Issue by ShutNSmoq** [pwn20wndstuff/Undecimus#473]
After jailbreak there is a update requested thing on updates and it is stuck and when i close and open my phone my cydia crashes and cannot be opened can anyone help me please !

**Comment by MichailiK** [comment]
Did you consider enabling **Reinstall Cydia** and try to Jailbreak?

<img src="https://user-images.githubusercontent.com/39029839/53348757-f5aa7500-391b-11e9-8156-1209d6b08594.png" alt="Loading..." width=300></img>

**Comment by riyadian1** [comment]
ios 12.1.4 :O :P :D
