### ISSUE TITLE
Cydia won’t launch

### ISSUE THREAD

**Issue by nazomeita** [pwn20wndstuff/Undecimus#475]
Cydia will not open and just shows a white screen and then crashes

**Comment by cre3p3rman** [comment]
Have you tried jailbreaking again, and then opening cydia?

**Comment by snowball7241** [comment]
Try the reinstall cydia option.

**Comment by nazomeita** [comment]
> Try the reinstall cydia option.

I did try that but nothing worked :/

**Comment by nazomeita** [comment]
> Have you tried jailbreaking again, and then opening cydia?

I will definitely try that thanks for the recommendation :)
