### ISSUE TITLE
Errno: 2 Failed to copy over Resources to RootFS after trying to replace deb of Resources to earlier version

### ISSUE THREAD

**Issue by EliteAppleHacks** [pwn20wndstuff/Undecimus#477]
Latest Resources crash a tweak i like on my iPhone X on 11.3.1. I replaced Resources with a deb on bingners repo. Downloaded latest Uncover, changed ipa to zip, extracted, opened /apt/ and replaced deb with the one included with the jailbreak. Also in / i replaced Resources.deb to the one i want to test and renamed accordingly to Resources.deb. Went back to the whole root folder (Payload), compressed, changed zip to ipa, then sideloaded with impactor. Running uncover now gets to this point. Any insight or how to downgrade the deb will help. Thanks devs
![Screenshot](https://user-images.githubusercontent.com/13251160/53297587-45325900-37d5-11e9-89ec-093f83e632d5.PNG)

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2897770/diagnostics.zip)

**Comment by HSANNU** [comment]
Just extract resources.deb and see what’s changed in the latest version. There’s really not much stuff going on in that file. So there’s a modified launchctl, the debugserver exectuable and it’s entitlements file. Figure out which one is bothering you and replace that file in the debian package and repackage it. You don’t have to install the ipa again; simply replace the original resources.deb in unc0ver’s application folder.

**Comment by EliteAppleHacks** [comment]
>Just extract resources.deb and see what’s changed in the latest version. There’s really not much stuff going on in that file. So there’s a modified launchctl, the debugserver exectuable and it’s entitlements file. Figure out which one is bothering you and replace that file in the debian package and repackage it. You don’t have to install the ipa again; simply replace the original resources.deb in unc0ver’s application folder.

@HSANNU can you expand a bit more? So leave the deb inside apt alone? And what do you mean by extract? Like change to zip and replace the files inside of it to an earlier version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
