### ISSUE TITLE
How to Install iPA files on iOS 11.3.1 Ipad Air 2 cellular JB with unc0ver2.2.2

### ISSUE THREAD

**Issue by magicfabrice** [pwn20wndstuff/Undecimus#478]
Hello,
I'm on IOS 11.3.1 on an Ipad Air 2 cellular
I've jailbreak it with unc0ver2.2.2
I've installed "AppSync Unifed" v31.1 from Karen's Repo

When I use AppCake, I've tried to install "Infuse pro 5"
So it has been installed but when I try to launch the application; it opens and close , it does not work.

Is there a limitation with unc0ver jailbreak ?

Regards

**Comment by HSANNU** [comment]
Piracy related. But that aside, try to sign the app with Impactor. If it’s still crashing, then the ipa is most likely broken.

**Comment by magicfabrice** [comment]
not better.
I would like to test the principle with another application, to understand.
For IOS 11.3.1 I need a 64 bits application ?  
any idea where I could find a test ipa ?
Regards

**Comment by Cryptiiiic** [comment]
Closing, piracy isn't supported...
