### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by szymonkrygier** [pwn20wndstuff/Undecimus#479]
iOS 12.1.2, iPhone9,1
unc0ver 3.0.0~b32

1. When re-jailbreaking (only!), even without tweaks installed, sometimes I get stuck on springboard loading screen. If it gets jailbroken, respring is working fine.

2. Even without tweaks, sometimes iPhone gets very hot. Rebooting and re-jailbreaking helps.

3. Sometimes iPhone reboots after jailbreaking, forcing people to jailbreak again. (maybe kernel panic?)

4. Sometimes it enters safe mode after jailbreaking for the first time.

**Comment by VanishingTacos** [comment]
Use b31, turn off "Reload system Daemons", reboot and try again.

A fix for this issue should be coming soon.

**Comment by szymonkrygier** [comment]
Thanks for your reply!
Turning off "Reload system Daemons" fixed some problems. I also noticed that jailbreaking without tweaks enabled, then entering cydia and restarting springboard by installing/reinstalling any tweak (that needs respring) and then re-jailbreaking with tweaks enabled partially fixes this issue.

I'm still curious why my iPhone gets very hot randomly sometimes, but trying to figure it out what causes this problem.

Also kernel panic needs to be fixed (sometimes still happens to me after jailbreaking after a reboot)

**Comment by Guilhermes755** [comment]
you fixed the issue of hot phone? my iphone 6s its almost all the time hot now i don't know what to do i'm using the unc0ver b35

**Comment by szymonkrygier** [comment]
May be caused by a tweak. Some people say it's caused by FloatyDock tweak. 
Try downloading some kind of process viewer and check which tweak may be the issue.
