### ISSUE TITLE
Safe mode resprings

### ISSUE THREAD

**Issue by Sahmoee** [pwn20wndstuff/Undecimus#480]
Not sure what’s causing it having about 6 per hour depending on how much I use my device. Sometimes it happens unpon opening an app or loading story or Snapchat or insta or by installing a tweak

iPhone 6s 12.1 uncover v3 beta 31.

32 doesn’t work at all for me

**Comment by VanishingTacos** [comment]
You need to be using b31, b32 got pulled for causing issues.
