### ISSUE TITLE
b30 & b31 nothing but respring loop then reboot..(wasted 25mins)

### ISSUE THREAD

**Issue by thekio1984** [pwn20wndstuff/Undecimus#483]
as title ios 12.1 SE, jailbreaking goes as normal, then once jailbroken, respringing then reboots..constantly, as in jailbreaks but dont even load lockscreen...everythings fine on b29, which is fantastic & actually works for me, as i expect...uptime is sooo long, i almost forgot what a loop or random reboot was..until now lol reimpacted b29, jailbroke, resprung for like 2seconds, lockscreen appears.. ill stay on this beta for now xD

**Comment by pbr0ck3r** [comment]
Try disabling the `Restart System Deamon`

**Comment by thekio1984** [comment]
Tyvm 👍
