### ISSUE TITLE
iPhone 6 NOT SUPPORTED??

### ISSUE THREAD

**Issue by jailbreakdaddy** [pwn20wndstuff/Undecimus#487]
on a ice 365 titled iOS jailbreak final release and tutorial for iOS 12-12.1.2
and added support for iPhone 5s and 6
my problem is that when running on iPhone 6 plus
show an error not supported
i am confused and looking for help
and also just was to alert the developers
of this issue

**Comment by DJCHICKEN4** [comment]
@jailbreakdaddy pwn20wnd is currently working on A7 and A8 support right now so iPhone 5s and 6 are not currently supported.

**Comment by snowball7241** [comment]
@Cryptiiiic please close

**Comment by NickJustWill** [comment]
isn't pwn20wnd working on A7 - A8 devices before A12?

**Comment by DJCHICKEN4** [comment]
@NickJustWill Yep

**Comment by philzyk** [comment]
Guys don't forget about "oldschools" with A7 and A8 devices.
Please!

**Comment by DJCHICKEN4** [comment]
@SidMostWanted The new b37 update added partial 4k support this update allows for setting the boot nonce and disabling auto updates on 4k devices. More information can be found in the release changelog.

**Comment by philzyk** [comment]
Closed? It's not working
I see no Cydia icon

**Comment by DJCHICKEN4** [comment]
@philzyk There isn't any issue there isn't supposed to cydia it's a partial-jailbreak (this means there is no cydia) for 4k devices.

**Comment by Cryptiiiic** [comment]
FFS, do I have to lock this? Ugh.
