### ISSUE TITLE
Infinite respring loop using beta 33

### ISSUE THREAD

**Issue by ASILVAPT** [pwn20wndstuff/Undecimus#488]
Hi,

I was jailbreak my iPad Air 2 (iOS 12.1.2) with beta 31, and all works good. Now I update for the beta 33 (Restart the iPad, and install the beta 33 and click jailbreak) I get a success and iPad stucks in infinite respring loop.

Any help?

Regards.

**Comment by reversed95** [comment]
_(Note: If you still experience this issue, you should use the RootFS Restore feature and re-attempt the jailbreak again before filing a new issue)_
Did you try this already? Make a backup of your tweaklist with Flame before this.

**Comment by ASILVAPT** [comment]
Tried and still infinite respring.

**Comment by rrajk0** [comment]
Highly recomendet Airplane mode ON !

**Comment by ASILVAPT** [comment]
I have airplane mode on!

**Comment by rrajk0** [comment]
Ah,I can‘t help u too much .. I still waiting for an A12 unc0ver update

**Comment by ProfessorRadish** [comment]
I’ve also restored RootFS and still get a respring and reboot on the latest beta 33 on iPhone X 12.1.2.

**Comment by reversed95** [comment]
Yeah I just tried it on iPhone X and iPad Pro 10.5 inch, both still have the respringing problem after RootFS restore. Disabling reload system daemons fixes the problem.

**Comment by lowgigs** [comment]
iPhone X 12.1.1 RootFS restore performed and it's still having respring issue as well.

**Comment by VanishingTacos** [comment]
iPhone 6s Plus and I am getting the respring loop. I tried to restore the rootfs but it got stuck running 28/39 after the restore. I downgraded to b31 for the time being.

**Comment by EmberVulpix** [comment]
I am using Undecimus-v3.0.0-b33.ipa on an iPhone X on iOS 12.1. I have never used a previous version of the jailbreak, only b33. I also get infinite respring unless Reload System Daemons.

**Comment by Tezzlicious** [comment]
iPad Mini 4 Cellular 12.1.1: Jailbreak went fine on b29. After b33 was released I did a reboot and update to b33. It started looping in respring mode and eventually rebooting. Went back to b29 and the issue remained. Tried it ~5 times on b29 and then turned off reloading system daemons. The respring loop disappeared. Updated again to b33. Without reloading system daemons instant success.

**Comment by briancrink** [comment]
Reload System Daemons enabled is still problematic on b33

**Comment by EmberVulpix** [comment]
Pressing "OK" on the "Jailbreak Completed with Status" alert with "Reload System Daemons" turned on allowed it to work properly for me.
