### ISSUE TITLE
Touch ID doesn’t work!!

### ISSUE THREAD

**Issue by snuk0** [pwn20wndstuff/Undecimus#491]
After jailbreak b33 Touch ID doesnt catch finger, only passcode works
iPhone 8+ 10,5 , iOS 12.1

**Comment by T4shf33n** [comment]
This should be related to futurerstore . Did you use it?

**Comment by snuk0** [comment]
No, I didnt use it

**Comment by clarityzzz** [comment]
@snuk0 Share diags please, a friend of mine reported this bug to me today too.
If you have blobs you can restore back to 12.1 later.

**Comment by snuk0** [comment]
@clarityzzz https://drive.google.com/file/d/1xI1mjw97F0Gv-XEvxRrDYQYjR5yk7fxH/view?usp=drivesdk
unfortunately I dont have saved blobs for 12.1 :(

**Comment by clarityzzz** [comment]
@snuk0 you can downgrade to 12.1.1 b3 if a jailbreak is really important to you.
If you have any 12.x blobs below 12.1.3, they're all usable for future-restoring.
I'll be taking a look into your logs.

**Comment by snuk0** [comment]
I used only previous unc0ver beta versions

**Comment by clarityzzz** [comment]
I don't believe it's related to root-fs since looking at your logs, it didn't get restored.

**Comment by snuk0** [comment]
Fixed:
I rebooted my device(then Touch ID start working again) and jailbreaked again with enabled option „Restore RootFS (rec0ver)” and now its all good.

**Comment by clarityzzz** [comment]
That's great to hear!
