### ISSUE TITLE
Restore RootFS still doesn't solve respring issue

### ISSUE THREAD

**Issue by Popcorncandy09** [pwn20wndstuff/Undecimus#492]
As the title says 👎

**Comment by meanskunk** [comment]
iPhone x 12.1.2 b32-b33 Respring issue tried restore rootfs still don't work had to go back to b31

**Comment by tsxmichael** [comment]
Update to beta 36 and disable reload system deamons and active reinstall cydia 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
Will be waiting to see if that help

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
