### ISSUE TITLE
Beta 33 Report (iPhone 7+ and 6S)

### ISSUE THREAD

**Issue by KyleWTF** [pwn20wndstuff/Undecimus#493]
Device 1: iPhone 7+, iOS 12.0
Turning 'Reload System Daemons' on causes the device to respring and eventually shutdown, same as previous betas.
Turning the switch off causes the device to boot up fine.

Device 2: iPhone 6S, 12.1.1 Beta 3
Turning 'Reload System Daemons' on causes the device to respring and eventually shutdown, same as previous betas.
Turning the switch off causes the device to boot up fine.

I have tried restoring rootfs for both.
Seems like the issue is still there.
I haven't noticed any freezing issues that seem to be around yet.

**Comment by bdan629** [comment]
Respring loop still happening for me.  iPad Pro 12.9 inch WiFi 12.1.1.  Also tried performing the restore rootfs and it didn’t help.  Only way to get it to succeed is to turn off reload system daemons...
