### ISSUE TITLE
iPhone 10,6 12.1.1 still respiring loops on beta 33 when reload system daemons is on, even after using the RootFS Restore feature

### ISSUE THREAD

**Issue by notmicrodev** [pwn20wndstuff/Undecimus#494]

**Comment by astrosfan1996** [comment]
Same thing happens to me with both my iPhone 8, 12.1.2, and my iPad Pro 10.5in, 12.1.1b3. The iPhone was originally jailbroken on b30, updated to b31 and running with reload system daemons turned off. I updated it to b33 and couldn't get it to work with reload system daemons on.

I restored my iPad to 12.1.1b3 yesterday and did not jailbreak it until today with b33, so it was a fresh system. Still didn't work with reload system daemons on.

The suggestion by this Twitter user works on both devices, though.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/Pwn20wnd?ref_src=twsrc%5Etfw">@Pwn20wnd</a> respring loop fix. Find a solution turn off reload daemons then jailbreak when is finish jailbreak. turn on reload daemons then re-jailbreak you device. it worked for my iphone 6s ios 12.1.1</p>&mdash; mehmet (@Mehmetpwned) <a href="https://twitter.com/Mehmetpwned/status/1099736328827219972?ref_src=twsrc%5Etfw">February 24, 2019</a></blockquote>

**Comment by astrosfan1996** [comment]
Here are my logs
[log_file_iPhone.txt](https://github.com/pwn20wndstuff/Undecimus/files/2898256/log_file_iPhone.txt)
[log_file_iPad.txt](https://github.com/pwn20wndstuff/Undecimus/files/2898257/log_file_iPad.txt)
