### ISSUE TITLE
Respring loop 

### ISSUE THREAD

**Issue by cipry0200** [pwn20wndstuff/Undecimus#497]
I've fresh Restored (futurerestore) my iPhone X (iPhone 10.6 d221ap) and i stil got respring loop followed by a restart. 
iOS 12.1.1 / Unc0ver b33

**Comment by KushTheDoosh** [comment]
Me too

**Comment by briancrink** [comment]
same, no apparent difference between the prior revoked b32/33 and this current b33.

**Comment by briancrink** [comment]
disable the daemon toggle for now on b33

**Comment by cipry0200** [comment]
> disable the daemon toggle for now on b33

I know about that opt, But I, discovered another temporary fix... PRESS "OK" right after you get jailbroken window...(You have to be fast, very fast. Once you see it press ok)  It worked every single time. tride for 10x -

**Comment by NickJustWill** [comment]
I disabled "Reload System Daemons" and it hasn't given me any issues so far... just like my ios 11.3.1 device.

**Comment by Sahahh** [comment]
I'm having the same problem with last beta, even after a RootFS restore

**Comment by lancerevodrifter** [comment]
Im also on the same train as Sahahh, did a RootFS restore and constantly puts my phone in a respring than reboot loop

**Comment by cipry0200** [comment]
> I disabled "Reload System Daemons" and it hasn't given me any issues so far... just like my ios 11.3.1 device.
