### ISSUE TITLE
i can't use dumpdecrypted ，tips killed:9

### ISSUE THREAD

**Issue by CCbird** [pwn20wndstuff/Undecimus#498]
i use my account to signed, and the kernel Log is : only launchd is allowed to spawn untrusted binaries

**Comment by TheNoim** [comment]
So far I understand it, you need to have a valid ent on the binary and you need to inject its trust
```bash
cd /private/var/mobile/Documents # save place to work in
ldid -e `which bash` > ent.xml # Get the ent from bash and save it
ldid -Sent.xml `which dumpdecrypted` # sign dumpdecrypted with the ent. "-Sent.xml" is the correct usage
inject `which dumpdecrypted` # inject into trust cache
```

But not really sure if this is correct. At least this is the way how I archive this.

**Comment by CCbird** [comment]
> So far I understand it, you need to have a valid ent on the binary and you need to inject its trust
> 
> ```shell
> cd /private/var/mobile/Documents # save place to work in
> ldid -e `which bash` > ent.xml # Get the ent from bash and save it
> ldid -Sent.xml `which dumpdecrypted` # sign dumpdecrypted with the ent. "-Sent.xml" is the correct usage
> inject `which dumpdecrypted` # inject into trust cache
> ```
> 
> But not really sure if this is correct. At least this is the way how I archive this.

how did i delete the trust cache,i use your method but still can't,the kernel tip same as before

**Comment by Cryptiiiic** [comment]
@CCbird on iOS 12 things need to be signed using a cert. I recommend bfdecrypt instead.

**Comment by Cryptiiiic** [comment]
Refer to #206 for all dumping and injecting related issues.
