### ISSUE TITLE
Is it normal to have electra folder in root?

### ISSUE THREAD

**Issue by KMamedoff** [pwn20wndstuff/Undecimus#5]
I wiped my device completely with electra and used this JB on stock iOS.

![klthsha - imgur](https://user-images.githubusercontent.com/5307981/46911128-c6dec400-cf63-11e8-92fa-3689a6559bb3.jpg)

**Comment by pwn20wndstuff** [comment]
The folder is being created to preserve the compatibility with the packages which were designed for Electra.
