### ISSUE TITLE
Respring Loop b33

### ISSUE THREAD

**Issue by sukarodo** [pwn20wndstuff/Undecimus#503]
iPhone X (10,3) iOS 12.1.1 (16C50)

Respring Loops (and eventually reboots) on b33 of unc0ver, even after rec0ver. Needs to disable "Reload System Daemons toggle".

**Comment by lancerevodrifter** [comment]
Even after restoring RootFS, i still get the same respring/reboot loop as I would with b32

**Comment by lancerevodrifter** [comment]
Even after a RootFS restore, I still get the same respring/reboot loop as I would with b32

**Comment by Oxycodon-IV** [comment]
Got the same thing:

Respring loop that eventually reboots on b33 even after rec0ver on BOTH ipX iOS12.1.1 & iPad Air 2 iOS12.1.1.

Had to still disable "Reload System Daemons Toggle"

Also, Respring is ALOT longer then on b31

**Comment by a-b-cd** [comment]
update to b33 and Restore RootFS and Rejailbreak, this work for me

**Comment by lancerevodrifter** [comment]
I came from b32 to b33 and did a RootFS restore on b33, still no change.

**Comment by a-b-cd** [comment]
so, Click on jailbreak and if you see in console waiting 1/2 double tap on home button close unc0v3r oper cydia install Newterm 2 and open Newterm and tap uicache && killall -9 SpringBoard if this work please answer here for other people

**Comment by a-b-cd** [comment]
-tap +write

**Comment by a-b-cd** [comment]
so, Click on jailbreak and if you see in console waiting 1/2, double click on home button close unc0ver, open cydia install Newterm 2 and open Newterm and write uicache && killall -9 SpringBoard 
if this work please answer here for other people :)
