### ISSUE TITLE
Not working on iPhone 6 

### ISSUE THREAD

**Issue by Krobix** [pwn20wndstuff/Undecimus#504]
I used Cydia impactor to get the ipa working on my iphone 6. I have ios version 12.0.1 and A8 CPU. When I go to install, the button says "unsupported". I will supply diagnostics in a bit.

**Comment by jaredkaragen** [comment]
I have an iphone 6 running 12.1, same issue;  shows up as "Unsupported".
diagnostics Plist file link for my phone can be found here: https://mega.nz/#!1LQBWApb!Tj5fo4Y2Z7KzfNOp1pZkxjZh2DJDmBA5rm9y8DoN3jU

**Comment by Vanquished79** [comment]
As of right now only A8X-A11 are supported.  but they are working on support for the others

**Comment by rGInfini** [comment]
Does anyone have any clue when support for A8 processors will be implemented?
