### ISSUE TITLE
[help]Iphone 7 ios 12.1.2 unc0ver dont work

### ISSUE THREAD

**Issue by tsxmichael** [pwn20wndstuff/Undecimus#505]
I try to help a friend that have this issue! The image link below! Why this happen
https://pbs.twimg.com/media/D0MUoh8XcAAb0lR.jpg

**Comment by clarityzzz** [comment]
I'll send a pull request solving success rates soon this soon.

**Comment by tsxmichael** [comment]
>I'll send a pull request solving success rates soon this soon.

@clarityzzz solved! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
>I'll send a pull request solving success rates soon this soon.

@clarityzzz thanks i figure plus I was reading and find out i was right! :) restore to ios 12.1.1 beta!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clarityzzz** [comment]
@tsxmichael that's not a way to solve an issue, rather a shortcut.
And I believe the problem here is it gets stuck on stashing the voucher, not on the service not available.

**Comment by tsxmichael** [comment]
So how its solved?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
>@tsxmichael that's not a way to solve an issue, rather a shortcut. ...

@clarityzzz ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clarityzzz** [comment]
@tsxmichael the day 12.1.1 b3 gets unsigned, we can no longer suggest that as a fix ( which it is not).
Downgrading from an official build to a beta is all but ideal. Wouldn't recommend it.

**Comment by batboy710** [comment]
@clarityzzz 
[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2898334/diagnostics.plist.zip)

**Comment by tsxmichael** [comment]
>@tsxmichael the day 12.1.1 b3 gets unsigned, we can no longer suggest that as a fix ( which it is not). ...

@clarityzzz ok but that a way for now instead to lose the opportunity of!! Ones you on jailbreak with a nonce update and shsh you can go up just like alot people do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clarityzzz** [comment]
@batboy710 Thanks! I'll take a look.

**Comment by tsxmichael** [comment]
>@clarityzzz  ...

@batboy710 what is that for? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
That is a diagnostic for ios 11

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
What that have to be with that problem 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clarityzzz** [comment]
@tsxmichael It's log to help fix another issue with the iPhone 7.
About your problem, I can't do anything without your friend sharing diagnostics to help diagnose the issue.

**Comment by tsxmichael** [comment]
>@tsxmichael It's log to help fix another issue with the iPhone 7. ...

@clarityzzz its alright problem solved! Its working perfectly now with the restore! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by batboy710** [comment]
@tsxmichael how did u fix it? Did u downgrade to 12.1.1 b3 ?

**Comment by tsxmichael** [comment]
>@tsxmichael how did u fix it? Did u downgrade to 12.1.1 b3 ? 

@batboy710 yes! I been helping couple people! And 3 of them have the same issue before! So the best recommendation in my opinion is get the beta 3 ios 12.1.1 still signed! And if you dont wanna lose any data instead restore just updated holding shift update and select the ipsw of the beta! Get the unc0ver 33 ones you jailbreak and cydia runing! The next time you jailbreak again make sure you disable reload system deamons!! You wont have any problem! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clarityzzz** [comment]
@tsxmichael if anyone else appears to have that problem BEFORE telling them to downgrade, please also ask them for diagnostics. We need to know whether this is caused by OTA or not!

**Comment by tsxmichael** [comment]
>@tsxmichael if anyone else appears to have that problem BEFORE telling them to downgrade, please also ask them for diagnostics. We need to know whether this is caused by OTA or not!

@clarityzzz i will make sure next time i can get you that for sure! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
>@tsxmichael if anyone else appears to have that problem BEFORE telling them to downgrade, please also ask them for diagnostics. We need to know whether this is caused by OTA or not!

@clarityzzz i have another guy that contact me yesterday night with the same problem but he dont have much experience with and take for ever to respond! I will teamviewer with him but no sire if he have computer for or anything he haven’t responded yet! But i will let you know if i get the diagnostic 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
