### ISSUE TITLE
Cydia won’t Open

### ISSUE THREAD

**Issue by ZachJazzy** [pwn20wndstuff/Undecimus#506]
Whenever o try and open it shows a clear screen with just my background then crashes. I’ve tried jailbreaking again and reloading cydia and nothing works. Please help.

**Comment by ZachJazzy** [comment]
It also gets stuck on 27/38 and has never gotten past it, even in airplane mode.

**Comment by clubby789** [comment]
Are you sure it's actually being jailbroken if it's getting to 27/38? Maybe it just keeps failing. What version are you on?
