### ISSUE TITLE
App Crash because jailbreak detect

### ISSUE THREAD

**Issue by sebk95** [pwn20wndstuff/Undecimus#507]
Some Apps from app store (Skygo, TimVision or Banks app) crash when open it. Detect jailbreak is possible iussue. Please insert jailbreak detection feature .
VIDEO CRASH:
[https://youtu.be/BNLMyKksAz8](https://youtu.be/BNLMyKksAz8)

**Comment by clubby789** [comment]
Use NoSub or LibertyLite
Also this isn't really an unc0ver issue

**Comment by sebk95** [comment]
NoSub or LibertyLite not work for this app.... the app work only if I start rec0ver

**Comment by sebk95** [comment]
edit: with liberty lite my bank apps work but skygo crash

**Comment by sebk95** [comment]
[https://youtu.be/BNLMyKksAz8](url)  this video is my iphone crash

**Comment by clubby789** [comment]
Looks like better JB detection, idk what you can do really

**Comment by stegerpa** [comment]
I'm having the same problem with my two banking apps... Its a real pain that even with a jailbreak i cant disable these apps detection mechanisms

**Comment by Mas9311** [comment]
This is neither an issue nor a bug related to unc0ver. Unc0ver is meant for loading the jailbreak into the kernel. Once you’re jailbroken, it is no longer related to unc0ver.

I’m guessing you’re using a system-wide tweak (like bloard). Use safe mode when you **need** to use the app.

Feel free to post this in https://www.reddit.com/r/jailbreak/ as a [Request] post with the specific app name(s).

Again, this is not an issue, so **please close this, @sebk95**
