### ISSUE TITLE
Message app crash 8+ 12.1.2

### ISSUE THREAD

**Issue by ChidoNguyen** [pwn20wndstuff/Undecimus#513]
When attempting to record a voice message to send the app will crash a second into holding down the microphone button in the text box

**Comment by aRamadi** [comment]
I have the same problem as well, I had it on all versions released b29-b33. It even happens if you use unc0ver with load tweaks turned off, in safe mode and even after trying to restore rootfs.

Here's a video I recorded of it happening: https://streamable.com/98a4w

**Comment by mosaleh77** [comment]
same happen with me iphone 6s+ ios 12.1.2 it crashes as soon as i tap on Audio Messages in IMessage app i have tried full restore to make sure its not my phone it only happen once i activate the jailbreak i made sure note to install any tweak before i test it BUT it still Crashes

**Comment by aRamadi** [comment]
I don’t know if this will help, but here’s my crash log:

{"blame":[],"app_name":"MobileSMS","timestamp":"2019-02-24 23:36:16.39 -0500","app_version":"5.0","slice_uuid":"2655e3be-3dea-314b-937a-400016231cf8","adam_id":0,"build_version":"1.0","bundleID":"com.apple.MobileSMS","share_with_app_devs":false,"is_first_party":true,"bug_type":"109","os_version":"iPhone OS 12.1.2 (16C104)","incident_id":"0627B33C-3E32-4C55-85D3-4EB99AFDDCD5","name":"MobileSMS","symbolicated":true}
Incident Identifier: 0627B33C-3E32-4C55-85D3-4EB99AFDDCD5
CrashReporter Key:   20e9d48923a68f7434fc67dc86b3d0b5ee6c4c9b
Hardware Model:      iPhone9,4
Process:             MobileSMS [4137]
Path:                /Applications/MobileSMS.app/MobileSMS
Identifier:          com.apple.MobileSMS
Version:             1.0 (5.0)
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.apple.MobileSMS [572]


Date/Time:           2019-02-24 23:36:16.3811 -0500
Launch Time:         2019-02-24 23:36:08.3708 -0500
OS Version:          iPhone OS 12.1.2 (16C104)
Baseband Version:    3.02.01
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [4137]
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x00000001044d1db8
    x4: 0x0000000000000000   x5: 0x0000000000000038   x6: 0x0000000000000000   x7: 0x000000000000003f
    x8: 0x0000000000000000   x9: 0x39b8f3ecc7850082  x10: 0x0100000100000000  x11: 0x0200000010000db8
   x12: 0x0000000000000000  x13: 0x00000010006861aa  x14: 0x0200000110000db8  x15: 0x0000000000000000
   x16: 0x00000001aa50404c  x17: 0x0200000110000db8  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000020  x21: 0x0000000105987968  x22: 0x0000000200000003  x23: 0x0000000000000000
   x24: 0x00000001d811ef0d  x25: 0x0000000000000002  x26: 0x0000000282e4da40  x27: 0x0000000280265360
   x28: 0x000000016bfdb0e0   fp: 0x000000016bfda4d0   lr: 0x00000001aa504060
    sp: 0x000000016bfda4c0   pc: 0x00000001aa4fd5f8 cpsr: 0x60000000

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef

EOF




Binary Images (dpkg):

Binary Images (App Store):

Binary Images (Other):

**Comment by wesmosis** [comment]
Same here, even after disabling all tweaks by iCleaner.

**Comment by muk546** [comment]
Same issue: iPhone 7 12.1.1 when jailbroken and I tap the mic messages app crashes.

**Comment by JHaz3y** [comment]
Issue still exists in b40 iPhone 7+ iOS 12.1.
iMessage crashes when doing a voice message

**Comment by ChipSkylark37** [comment]
Same issue as well on multiple devices. I would provide crash logs however they are the same information as presented above.

**Comment by DonnT90** [comment]
Is there a fix for this yet? Audio messages are a big part of my everyday texting.

**Comment by smailpouri** [comment]
Hi, same issue on iPhone 7 ios 12.1.2. unc0ver 3.0.1

**Comment by JHaz3y** [comment]
https://level3tjg.github.io
Add this repo.
This dev has a fix for voicemsg crash

**Comment by smailpouri** [comment]
> https://level3tjg.github.io
> Add this repo.
> This dev has a fix for voicemsg crash

Thank you @JHaz3y !!! this worked VoiceMsgFix which is apparently available on a few repos
