### ISSUE TITLE
Tweaks Not Working Properly

### ISSUE THREAD

**Issue by iMaxed0ut** [pwn20wndstuff/Undecimus#517]
I have finally managed to get a working jailbreak and working Cyida (albeit I have no idea how...just lots of trying again). However, when I go to install tweaks that are known and proven to work such as Flame 1.3 and NoBetaAlert, they don't seem to work nor seem to even be installed. I can't find them in the menu's and my Beta Alert is till popping up. Anyone have any suggestions?

**Comment by clubby789** [comment]
Have you tried turning off Reload System Daemons?

**Comment by iMaxed0ut** [comment]
>Have you tried turning off Reload System Daemons?

@clubby789 yup

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clubby789** [comment]
I think you're meant to also use Restore RootFS, not sure

**Comment by iMaxed0ut** [comment]
>I think you're meant to also use Restore RootFS, not sure

@clubby789 I’m just an idiot...major facepalm...I had load tweaks off for some reason. I checked it and rejailbroke. We’re all good! Closing as issue was resolved. Issue not caused by software but from user error.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment]
>I think you're meant to also use Restore RootFS, not sure

@clubby789 restore rootfs is for delete the jailbreak! Is that what you wnt to happen?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clubby789** [comment]
> @clubby789 restore rootfs is for delete the jailbreak! Is that what you wnt to happen?
It's what pwn recommended for fixing the issue.

**Comment by tsxmichael** [comment]
>> @clubby789 restore rootfs is for delete the jailbreak! Is that what you wnt to happen? ...

@clubby789 well that the method to delete the jailbreak and have the icon only of cydia but you wont have jailbreak! Thats for if you wnt to delete the jailbreak you just have to enable this option and all the tweaks and jailbreak will be delete!! What he recommends is to disable reload system deamons! And I recommend if its still no working to enable reinstall cydia plus disable reload system deamons and its been working for all the issues of all the people i been helping!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clubby789** [comment]
Yes, but he suggests Restore RootFS if that doesn't work
