### ISSUE TITLE
Iphone X 10,3 - Ios 12.1.1 - Never successful on beta 33 (Reboots after respiring) , even RootFS restore was used

### ISSUE THREAD

**Issue by zenzehar** [pwn20wndstuff/Undecimus#520]
After I have the message of jailbreak completed and respiring loading icon come up, it stays there for a while and then nothing happen bu reboot and the jailbreak is always unsuccessful (even tried RootFS restore). This wasn't the case with beta 32.

**Comment by chrislinke** [comment]
Possible Workaround: 
Have you tried disabling "Reload System Daemons" in the unc0ver settings, and then re-jailbreaking?  
Fixed this issue for me - supposedly you're meant to re-enable after jailbreaking (IDK why - someone more technical could probably answer this for you).

**Comment by zenzehar** [comment]
> Possible Workaround:
> Have you tried disabling "Reload System Daemons" in the unc0ver settings, and then re-jailbreaking?
> Fixed this issue for me - supposedly you're meant to re-enable after jailbreaking (IDK why - someone more technical could probably answer this for you).

When I do so it works but system tweakes don't work, like Real CC for example

**Comment by MichailiK** [comment]
[Beta 34](https://github.com/pwn20wndstuff/Undecimus/releases) recently got released. Already tried Jailbreaking with this version?

**Comment by zenzehar** [comment]
> [Beta 34](https://github.com/pwn20wndstuff/Undecimus/releases) recently got released. Already tried Jailbreaking with this version?

Unfortunately, Still insisting in beta 34

**Comment by L8toH8** [comment]
I had to reinstall Cydia after rootFS restore. B34
