### ISSUE TITLE
Enhancement Request: CYDIA - Change default web address to https:// when adding Repo's

### ISSUE THREAD

**Issue by chrislinke** [pwn20wndstuff/Undecimus#521]
Cydia request: It'd be great to change the default 'add source' field to "https://" rather than "http://" - most repos these days are https.  Not sure if it's for you to change, or if it's a Saurik IP thing.
Very very minor, but would save 10 seconds every time we add a new repo.

**Comment by JQ555888** [comment]
I believe it has already been confirmed that https will not be necessary as there have been proper file integreation checks implemented in Cydia already. Also not everyone has the ability to purchase an SSL certificate (let’s not count in Let’s Encrypt for now, which is clearly an exception), especially for private repo owners. Maybe someone else can clarify this further?

**Comment by chrislinke** [comment]
Not trying to force the use of https, just wanting it to be the default address that pops up when adding a new repo.  Most of my repos are https, and failing to add the ‘s’ meant I couldn’t add them.  
This is a usability-driven enhancement request, not security-based.

**Comment by Cryptiiiic** [comment]
@chrislinke I have a tweak to do this, If I get time, I'll get my repo up and running again this weekend.

**Comment by chrislinke** [comment]
Brilliant! Would you mind pasting a repo link here once up and running? Love your work

**Comment by Cryptiiiic** [comment]
@chrislinke Remind me this weekend on twitter [@Cryptiiiic](https://twitter.com/cryptiiiic) or via discord Cryptic#6293.

**Comment by Cryptiiiic** [comment]
@chrislinke https://cryptiiiic.com/repo/

**Comment by chrislinke** [comment]
Thanks heaps mate! Running beautifully
