### ISSUE TITLE
phone keeps restarting itself

### ISSUE THREAD

**Issue by gigajew** [pwn20wndstuff/Undecimus#524]
phone keeps restarting itself after doing jailbreak, what can i do to fix it?

**Comment by tsxmichael** [comment]
Check any incompatible tweak! Probably you install some tweak that make your phone to do that! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MichailiK** [comment]
@gigajew Did you try disabling **Reload System Daemons** in unc0ver's settings?

<img src="https://user-images.githubusercontent.com/39029839/53347427-57b5ab00-3919-11e9-8a25-0dc5f7c3dc32.png" alt="Loading..." width=300></img>

**Comment by SidMostWanted** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/518#issuecomment-467717903

**Comment by SidMostWanted** [comment]
They this step by step; https://github.com/pwn20wndstuff/Undecimus/issues/518#issuecomment-467717903
