### ISSUE TITLE
stuck on 27/38 after deleting b29 and switching to b33

### ISSUE THREAD

**Issue by apexslay** [pwn20wndstuff/Undecimus#525]
I am on iphone x 12.1.1 b3 and already tried restore rootFS multiple times and toggled off reload system daemons.

**Comment by EliteAppleHacks** [comment]
Launch it with just rootFS and have it go through the process. See if that helps

**Comment by apexslay** [comment]
Ok so I got it working. However, i went down to b31 instead. I also ran into issued there such as my wifi becoming greyed out (can’t toggle it on or off) so i just kept jailbreaking and rebooting my phone until i was able to use my tweaks and with the wifi fixed. Quick question: what are the ideal settings to have toggled on in uncover?
