### ISSUE TITLE
Does is support iPhone 5s iOS 12.0 ?

### ISSUE THREAD

**Issue by josh7** [pwn20wndstuff/Undecimus#526]
iPhone 5s iOS 12.0

**Comment by jayb1239** [comment]
iPhone 5s uses the A7 processor so as yet is unsupported by Unc0ver however support is planned.

**Comment by josh7** [comment]
> iPhone 5s uses the A7 processor so as yet is unsupported by Unc0ver however support is planned.

Amazing work! Waiting for it.
