### ISSUE TITLE
Resprings when opening camera from lockscreen

### ISSUE THREAD

**Issue by rorcores** [pwn20wndstuff/Undecimus#527]
If I raise to wake and then tap the camera button on the bottom right of the screen (locked or unlocked) and take a photo straight away it will respring most times I do this.

Running beta 21 on iPhone x ios 12.1.2

Update: Wanted to add, thanks so much for your hard work on this, aside from this 1 issue the JB has been flawless for me.

**Comment by rorcores** [comment]
This appears to have been resolved on b34. Thank you

**Comment by nik312123** [comment]
Could you close the issue and reopen it only if the issue reappears?

**Comment by rorcores** [comment]
Yes, closing now, thank you.
