### ISSUE TITLE
iPhone sometimes freezes when rearranging icons in jailbroken state

### ISSUE THREAD

**Issue by pmjm** [pwn20wndstuff/Undecimus#529]
This happens intermittently when I'm moving an app icon a great distance, like from the last page (I have around 10 pages of apps) to the first. Once it gets to the first page, the system locks up and I have to do a forced-restart of the phone and rejailbreak.

At this point I'm only rearranging icons while in a jailed state to get around this issue.

No tweaks installed so this is definitely an Undecimus issue.

iPhone X on 12.1.1 b3.

**Comment by mikevillarroel** [comment]
My device resprings if i try to move an icon while jailbroken
