### ISSUE TITLE
Cannot make any call

### ISSUE THREAD

**Issue by novusgbg** [pwn20wndstuff/Undecimus#534]
Hey, whenever I make a call the animation goes through(the grey thingy) but the call doesn’t happen, I can receive calls but I cannot make any call
Here’s a list of my tweaks
Boxy3
DLEasy
IGOLED
LocallAppstore
Noctis12
Utubed
PullToRespring
WADarkMode
Any help would be appreciated
I’m on iPhone X iOS 12.1.2

**Comment by coenkcore** [comment]
try to restart your device, and jailbreak again with load tweaks off, then try again to make a call
if success to make a call you can try to delete your tweak or you can try to restore rootFS.

**Comment by riyadian1** [comment]
> try to restart your device, and jailbreak again with load tweaks off, then try again to make a call
> if success to make a call you can try to delete your tweak or you can try to restore rootFS.

i has the same issue , just hard rebot your device and rejailbreak again ,,,, on iphone 7 12.1.2

**Comment by novusgbg** [comment]
Solved, thank you @coenkcore 
@AppleNati0n For me, it didn't work with just rebooting, i had restore rootFS.
