### ISSUE TITLE
iOS Update Popup on jailbreak state

### ISSUE THREAD

**Issue by c3sco** [pwn20wndstuff/Undecimus#535]
I've installed b33 yesterday evening.
tvOS profile installed, jailbreak applied.
After 2 hours a popup saying that iOS 12.1.4 is available appeared.
If i open "Software Update" in settings an error appears.
Can i jailbreak safely or do i risk a bootloop?

**Comment by MichailiK** [comment]
Go to `Settings -> General -> iDevice Storage` and see if you can find `iOS 12.1.4` on the list. Delete it if you do and restart your iDevice. If you don't, you can safely Jailbreak.

**Comment by c3sco** [comment]
I checked and there isn't. But shouldn't unc0ver and tvOS profile block update requests?

**Comment by MichailiK** [comment]
Yea, it should. Strange... It should be safe for you to Jailbreak nonetheless.
