### ISSUE TITLE
iPhone 7+ iOS 12.1 Jailbreak lost post restart

### ISSUE THREAD

**Issue by Adityan27** [pwn20wndstuff/Undecimus#536]
Jailbreak worked flawlessly and installed a bunch of tweaks. Decided to restart my phone which resulted in losing the JB with the Cydia app still present but it wouldn't open.
I selected Reinstall Cydia & Clear Cydia Cache in the UncOver app, tried the jailbreak again, it worked and even got all the tweaks back.
Second time my phone restarted beacuse of a tweak which failed to install, now I am unable to redo the above process even after multiple tries.

**Comment by c3sco** [comment]
It's a semi-tethered jailbreak so after reboot you should just open unc0ver and press "Jailbreak".
After respring it should work.

**Comment by Adityan27** [comment]
Alright, wasn't aware of that.
Appreciate your revert.

Does the JB expire after 7 days? I heard that on some video.

**Comment by riyadian1** [comment]
> Alright, wasn't aware of that.
> Appreciate your revert.
> 
> Does the JB expire after 7 days? I heard that on some video.

yes if you have a signing service then you have 365 days ,

**Comment by Adityan27** [comment]
> > Alright, wasn't aware of that.
> > Appreciate your revert.
> > Does the JB expire after 7 days? I heard that on some video.
> 
> yes if you have a signing service then you have 365 days ,

How do I know if I have a signing service or not? If I don't, how do I get the service?
My apologies if the queries are too amaterish.

**Comment by c3sco** [comment]
From unc0ver settings you can see expiry time.
If you used a signing service the days should be more than 7

**Comment by riyadian1** [comment]
> > > Alright, wasn't aware of that.
> > > Appreciate your revert.
> > > Does the JB expire after 7 days? I heard that on some video.
> > 
> > 
> > yes if you have a signing service then you have 365 days ,
> 
> How do I know if I have a signing service or not? If I don't, how do I get the service?
> My apologies if the queries are too amaterish.

check this out https://ipastore.me/ signing service for one year

**Comment by c3sco** [comment]
Maybe not allowed (or maybe yes, we aren't on reddit), but http://ignition.fun host signed jailbreak apps for free

**Comment by Adityan27** [comment]
I have 282 days till expiry. I'm not sure how I got that though.

Thank you all for helping out.

**Comment by c3sco** [comment]
> I have 282 days till expiry. I'm not sure how I got that though.
> 
> Thank you all for helping out.

You installed it from a signing service.
You should close the issue if you problem has been resolved.
