### ISSUE TITLE
Beta 34 still causes respring loop with reload daemons

### ISSUE THREAD

**Issue by Emoinm** [pwn20wndstuff/Undecimus#537]
I was still sent into a respring loop when using beta 34. I haven’t had the chance to rootfs restore to test it yet, but I thought it would be helpful to post an issue with my diagnostics data for now. I’ll update the issue when I get more time to test to see if it works. For now though, here’s my diagnostics data 
https://drive.google.com/file/d/1Nxap0KsnaTXsZ_-a88X3XOP8xOak0Irl/view?usp=drivesdk

(github wouldn’t let me attach the file so here’s a google drive download)

**Comment by coenkcore** [comment]
try to run rootFS restore, after finished try to jailbreak again.

**Comment by riyadian1** [comment]
> I was still sent into a respring loop when using beta 34. I haven’t had the chance to rootfs restore to test it yet, but I thought it would be helpful to post an issue with my diagnostics data for now. I’ll update the issue when I get more time to test to see if it works. For now though, here’s my diagnostics data
> https://drive.google.com/file/d/1Nxap0KsnaTXsZ_-a88X3XOP8xOak0Irl/view?usp=drivesdk
> 
> (github wouldn’t let me attach the file so here’s a google drive download)

did you run jailbreak on aeroplane Mode?

**Comment by Emoinm** [comment]
RootFS restore did work, glad to know that works.

**Comment by Emoinm** [comment]
After having to reboot my phone, the respring loop with reload daemons has come back. It had worked after that initial RootFS restore earlier today, however now, after installing tweaks, it sends me into a respring loop. Disabling all tweaks in iCleaner does not solve this issue, so I don’t think it is a tweak issue.

**Comment by hmoghani** [comment]
I'm on 12.1.2. I did a clean Restore yesterday. Installed the latest b34 build. Everything worked fine.  after installing Tetherme, the respring worked fine, but the re-jailbreak didn't work with reload system daemon enabled. So:

Clean Install (No tweak):
Respring works
Re-jailbreak works (with daemon reload)

With Tetherme:
Respring works (right after installation)
Rejailbreak Fails  - daemon reload enabled (Respring loop and then restart)
Rejailbreak works - daemon reload disabled (tetherme itself didn't work after this)

Removing tetherme, fixed the rejailbreak with reload daemon enabled issue.

**Comment by Emoinm** [comment]
I don’t have tetherme enabled, but maybe that means some tweaks are breaking it? I was able to get it working on a fresh rootfs and today I was able to jb using iCleaner to disable all tweaks.
