### ISSUE TITLE
Undecimus-v3.0.0-b34 Even after restore rootfs, reset cydia cache, reinstall cydia on iPhone 10,6 stuck on spinning icon

### ISSUE THREAD

**Issue by JSeredick** [pwn20wndstuff/Undecimus#538]
Undecimus-v3.0.0-b34.ipa
iPhone 10,6
Lost jailbreak from phone shutting off
Was having this issue before, updated to the new ipa this actually fixed it
Lost jailbreak again during a cydia install
This version of uncover no longer will fix my issue, just stuck on spinning icon.
Note: worked the first time but hasn't worked since.

**Comment by JSeredick** [comment]
The jailbreak does work successfully each time. It is only during the respring process it is stuck

**Comment by riyadian1** [comment]
> Undecimus-v3.0.0-b34.ipa
> iPhone 10,6
> Lost jailbreak from phone shutting off
> Was having this issue before, updated to the new ipa this actually fixed it
> Lost jailbreak again during a cydia install
> This version of uncover no longer will fix my issue, just stuck on spinning icon.
> Note: worked the first time but hasn't worked since.

did you run jailbreak in aeroplane mode??

**Comment by JSeredick** [comment]
> > Undecimus-v3.0.0-b34.ipa
> > iPhone 10,6
> > Lost jailbreak from phone shutting off
> > Was having this issue before, updated to the new ipa this actually fixed it
> > Lost jailbreak again during a cydia install
> > This version of uncover no longer will fix my issue, just stuck on spinning icon.
> > Note: worked the first time but hasn't worked since.
> 
> did you run jailbreak in aeroplane mode??

I will give it a try now thanks

**Comment by devcline** [comment]
try several times. it must work

**Comment by JSeredick** [comment]
I was on airplane mode with WiFi still enabled before.. seemed to have actually worked this time after attempting all the above with the reset cydia cache reinstall cydia and restore rootfs. However still an annoying issue. If every time I finally get my tweaks set up and lose them all due to having to reinstall cydia and restore rootfs pretty annoyiong

**Comment by MichailiK** [comment]
@JSeredick Did you try disabling "Reload System Daemons" in unc0ver's settings?

**Comment by riyadian1** [comment]
> I was on airplane mode with WiFi still enabled before.. seemed to have actually worked this time after attempting all the above with the reset cydia cache reinstall cydia and restore rootfs. However still an annoying issue. If every time I finally get my tweaks set up and lose them all due to having to reinstall cydia and restore rootfs pretty annoyiong

i lost my all tweaks 5 times , every time i update the unc0ver app , lost all the data and tweaks , but no problem thats a public beta :) Happy Jailbreaking

**Comment by riyadian1** [comment]
https://twitter.com/iM4CH3T3/status/1100024843452452865 

People don’t forget!!!
Enable airplane mode when Jailbreaking

**Comment by JSeredick** [comment]
> @JSeredick Did you try disabling "Reload System Daemons" in unc0ver's settings?

I had not attempted that no, and yes unfortunately yes as a beta this all is expected to lose tweaks, but possibly an issue to highlight so people during the full release aren't losing their tweaks

**Comment by MichailiK** [comment]
> 
> 
> > @JSeredick Did you try disabling "Reload System Daemons" in unc0ver's settings?
> 
> I had not attempted that no, and yes unfortunately yes as a beta this all is expected to lose tweaks, but possibly an issue to highlight so people during the full release aren't losing their tweaks

Give it a try. So far, I've never got the respring-loop ever since I turned it off. https://twitter.com/Pwn20wnd/status/1099781612575682562

**Comment by JSeredick** [comment]
Fix for me: restore root fs, reinstall cydia, reset cydia cache, on latest Undecimus-v3.0.0-b34.ipa, when rejailbreaking use airplane mode without WiFi enabled.

**Comment by riyadian1** [comment]
> Fix for me: restore root fs, reinstall cydia, reset cydia cache, on latest Undecimus-v3.0.0-b34.ipa, when rejailbreaking use airplane mode without WiFi enabled.

good happy jailbreaking :D
