### ISSUE TITLE
Reload System Daemons issue still occurs in beta 34/35

### ISSUE THREAD

**Issue by AvinashDevina** [pwn20wndstuff/Undecimus#540]
Hello, i am using iPhone 6S IOS 12.1.1 with unc0ver beta 34/35 installed with cydia impactor, with latest beta i restored my rootFS and jailbreaked with Reload System Daemons turned on, it was successful at that time, after some time i have restarted my phone and again i tried to jailbreak with Reload System Daemons turned on, this time it is take me to respring loop , i have restarted my phone again and disabled Reload System Daemons this time jailbreak is successful. I was on airplane mode while doing entire process. Please investigate. Thanks

**Comment by meanskunk** [comment]
I got b34 working by manually turning off mobile data/Bluetooth/Wi-Fi  

after jailbreak re-enable them this works for me iPhone X 12.1.2

Also you might want to download cydia tweak - ReProvision - to re-sign your apps save using computer every time
