### ISSUE TITLE
Undecimus b34 still enters respring loop. Reload System Daemons broken. Avoid.

### ISSUE THREAD

**Issue by briancrink** [pwn20wndstuff/Undecimus#541]
Edit: disabling Reload System Daemons returns 'Error (Fatal) Erno: 9 ... Description: Failed to Initialize patchfinder64'

**Comment by v3rBaLcRiMiNaL** [comment]
Mine iPhone X is still going into a restring loop too... I'm not getting this patchfinder64 error though.

**Comment by nickpl456** [comment]
Also running into this problem on an iPhone SE 128gb running iOS 12.1. iOS 12.1 installed by iTunes, not OTA. un0ver b34 is the first sideloaded app/jailbreak installed onto this phone. iPhone successfully jailbreaks with Reload System Daemons turned off, and once the phone is jailbroken I can rejailbreak it with Reload System Daemons turned on.
