### ISSUE TITLE
respring Loop with v3.0.0~b34

### ISSUE THREAD

**Issue by 56aluminium** [pwn20wndstuff/Undecimus#544]
respring loop with latest unc0ver version
I have included the diagnostics report from unc0ver 
I don't know if it helps or not 
Thank you for your Work <3
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2901725/diagnostics.txt)

**Comment by sadanro100** [comment]
same thing here, even after using the RootFS Restore feature

**Comment by IZNEK** [comment]
Same thing here, I maybe have a solution to bypass the respring loop waiting a new update. 
First jailbreak with Load Tweaks toggle OFF
While being jailbroken without Load Tweaks Re-Jailbreak with Load Tweaks.
This worked for me.
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2902861/diagnostics.txt)

**Comment by tsxmichael** [comment]
Just disable reload system deamons! That is guys and jailbreak again with airplane mode on

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lberrezoug** [comment]
> Just disable reload system deamons! That’s it guys and jailbreak again with airplane mode on
> 
> Sent with [GitHawk](http://githawk.com)

HI tsxmichael,
Yes, it works great when I disable reload system, however to help the team I also attach the diagnostic report.
thank you

**Comment by sadanro100** [comment]
Indeed, I confirm it works. Pardon my ignorance, what difference does it make to disable this toggle?

**Comment by mtuan293** [comment]
That toggle executes "ldrestart". If you want, download Mterminal from Cydia, then open it up and type `ldrestart` and you should be stuck in the respring loop

**Comment by sadanro100** [comment]
I see, but my point is, what does "ldrestart" do? Is it important? What do I miss if I disable it?

**Comment by meanskunk** [comment]
Just turn off 
WiFi/Bluetooth/mobile data 
this works for me after jailbreak  
turn them back on  

Airplane Mode did not work for me but this did

**Comment by mtuan293** [comment]
> I see, but my point is, what does "ldrestart" do? Is it important? What do I miss if I disable it?

pwn20wnd replied here
https://www.reddit.com/r/jailbreak/comments/a22azu/question_what_is_reload_system_daemons_in_unc0ver/

**Comment by sadanro100** [comment]
@mtuan293 thank you! Is it correct to assume that disabling it makes no difference since tweaks restart what they need when they're installed?

**Comment by mtuan293** [comment]
> Tweaks already restart what they need to on installation. Yet they can’t do it when rejailbreaking, so we just restart everything to make sure that everything will work ok.
Did you read past this line?

**Comment by mtuan293** [comment]
> Tweaks already restart what they need to on installation. Yet they can’t do it when rejailbreaking, so we just restart everything to make sure that everything will work ok.

Did you read past this line?

**Comment by sadanro100** [comment]
Yes did, it didn't make sense then, it does now. Thanks
