### ISSUE TITLE
Can't remove cydia after unjailbreaking 

### ISSUE THREAD

**Issue by mikemike998** [pwn20wndstuff/Undecimus#548]
Can't remove cydia after unjailbreaking .

**Comment by mai0li** [comment]
Have you tried using 'Restore RootFS' option?

**Comment by mikemike998** [comment]
> Have you tried using 'Restore RootFS' option? Yes I still can't delete the icon .

**Comment by Mas9311** [comment]
Why you want to delete Cydia is beyond me...

You cannot squiggle-delete 1 any tweak that makes an icon on the Springboard, 2 unc0ver, or 3 Cydia.
Tweaks: You need to turn on the option to restore rootfs (in unc0ver) to remove any tweaks that are one the springboard.
unc0ver: To delete uncover, go to Settings > General > device management > your email > delete app.
Cydia: This app isn’t actually *on* your device at this point. You’ll need to back up your device, preform an erase all content and settings, then restore your phone from the backup. 

Again, why you would want to do this is beyond me. Very stressful if something goes wrong, and you’ll be up all night googling the error codes. Good luck!

**Comment by mikemike998** [comment]
> Why you want to delete Cydia is beyond me...
> 
> You cannot squiggle-delete 1 any tweak that makes an icon on the Springboard, 2 unc0ver, or 3 Cydia.
> Tweaks: You need to turn on the option to restore rootfs (in unc0ver) to remove any tweaks that are one the springboard.
> unc0ver: To delete uncover, go to Settings > General > device management > your email > delete app.
> Cydia: This app isn’t actually _on_ your device at this point. You’ll need to back up your device, preform an erase all content and settings, then restore your phone from the backup.
> 
> Again, why you would want to do this is beyond me. Very stressful if something goes wrong, and you’ll be up all night googling the error codes. Good luck!

When will cydia be on your device ?

**Comment by mikemike998** [comment]
So I have to do a reset to get cydia off my phone ?

**Comment by mikemike998** [comment]
I have fixed it by watching this video https://www.youtube.com/watch?v=lsFGzCvM4dY .

**Comment by mikemike998** [comment]
But there should be a feature added in cydia or in unc0ver for people who don't have laptops or computers when they unjailbreak cydia will be deleted !
