### ISSUE TITLE
iPad mini 2 on ios 12.1.1 b3 'Unsupported' on Unc0ver 3.0.0~b29

### ISSUE THREAD

**Issue by ProBlauw** [pwn20wndstuff/Undecimus#549]
Hello, my iPad mini 2 on iOS 12.1.1 beta 3 is unsupported. Why is this on different sites it says my model is supported. Could this be because I have jailbroken my device before on a different firmware? 
Please help me! 

Thank you.

**Comment by shijiav** [comment]
This one is not supported yet, right now b34 still acquired A8X and above, ipad mini2 is A7.

**Comment by ProBlauw** [comment]
> This one is not supported yet, right now b34 still acquired A8X and above, ipad mini2 is A7.

so I can't jailbreak right now?

**Comment by shijiav** [comment]
yes, but will get supported very soon, should be today.

**Comment by ProBlauw** [comment]
Ok, thank you very much!

**Comment by ProBlauw** [comment]
So... is there an exact date when my model is getting support?

Thank you

**Comment by objp4th** [comment]
@ProBlauw: Being in the same boat as you I recommend waiting for an updated release that supports the iPad mini 2. Asking for an ETA can be considered rude, please show respect to the unc0ver developers by being patient. Thank you!

**Comment by ProBlauw** [comment]
> @ProBlauw: Being in the same boat as you I recommend waiting for an updated release that supports the iPad mini 2. Asking for an ETA can be considered rude, please show respect to the unc0ver developers by being patient. Thank you!

Yeah I will, and I am very thank full to the developers of unc0ver! They are just hero's!

**Comment by ProBlauw** [comment]
Thanks team unc0ver! I have been able to jailbreak my device! only thing is... Cydia doesn't show up..
Maybe I did something wrong, any help?

**Comment by yangia** [comment]
> Thanks team unc0ver! I have been able to jailbreak my device! only thing is... Cydia doesn't show up..
> Maybe I did something wrong, any help?

![image](https://user-images.githubusercontent.com/34333375/53538133-608bc400-3b47-11e9-81be-7d05a94415fc.png)

**Comment by ProBlauw** [comment]
> > Thanks team unc0ver! I have been able to jailbreak my device! only thing is... Cydia doesn't show up..
> > Maybe I did something wrong, any help?
> 
> ![image](https://user-images.githubusercontent.com/34333375/53538133-608bc400-3b47-11e9-81be-7d05a94415fc.png)

Thanks I'll wait.
