### ISSUE TITLE
Error Fatal Error Number: 17 for Unc0ver Jailbreak for ios 12 - 12.1.2

### ISSUE THREAD

**Issue by Ac1dSn0w** [pwn20wndstuff/Undecimus#551]
This error occurs with Unc0ver with FSRoot restore

https://imgur.com/a/5VWo8QJ

Done with:
1. Airplane Mode
2: Deleted OTA file in iPhone Storage

Image URL Explains condition

**Comment by TheChatty** [comment]
See #707 for solution.
