### ISSUE TITLE
Stuck on 27 / 38

### ISSUE THREAD

**Issue by rorcores** [pwn20wndstuff/Undecimus#555]
Stuck on 27/38 on version b34 after moving from b29 to b34

**Comment by tsxmichael** [comment]
Do some research please! 🤦🏽‍♂️read! They are couple post already of how to fix that!! Just disable reload system deamons on setting in unc0ver and activate airplane mode then press jailbreak! That’s it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rorcores** [comment]
I did research. In airplane mode with system daemon reloads switched off and it still becomes stuck on 27/38. Have tried several times. No good. No other apps open either. Need to force a reboot each time it happens.

**Comment by rorcores** [comment]
Resolved by doing the following:

Restored rootFS and cydia.
Then let it restart, then put plane mode on and re-jailbroke 3 times with system daemons disabled, on the 3rd time it went all the way and worked. Thanks guys.

**Comment by tsxmichael** [comment]
>Resolved by doing the following: ...

@rorcores see that doing research you will find a answer! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
