### ISSUE TITLE
ipad air2，unc0ver 3.0.0~b34，line 1680， failed to extract bootstrap

### ISSUE THREAD

**Issue by isaac850904** [pwn20wndstuff/Undecimus#556]
ps: find my phone turned off , airplane on, , RootFS Restore every time. 
Tried many many times...
Hate the Ios beta push.
Can you help me?
Thanks.
![qq 20190226103714](https://user-images.githubusercontent.com/26065253/53383784-b9c2ee80-39b3-11e9-8fb9-33c56276efeb.png)

**Comment by AveHawkEyE** [comment]
Please use Beta 31 
https://github.com/pwn20wndstuff/Undecimus/releases/download/v3.0.0%25b34/Undecimus-v3.0.0-b31.ipa

it will be good!

**Comment by sonhl0105** [comment]
First, you should restore rootfs. After enable airplan mode and jailbreak again. Good luck.

**Comment by devcline** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/530

**Comment by isaac850904** [comment]
> @isaac850904 [try this again,](https://yalujailbreak.net/error-fatal-unc0ver-ios-12/) its seems to be different error from the main problem, but i have ipad air 2 #530 @AveHawkEyE tested 31 too, @sonhl0105 also done this

You're right. Maybe we need to wait several weeks until uncOver is more stable.
