### ISSUE TITLE
beta reports

### ISSUE THREAD

**Issue by sharklatan** [pwn20wndstuff/Undecimus#557]
I'm currently seeing what some users keep in B29 because they report that it works better than the new versions.

Most users do not know how to report errors, much less are they testing the updates they are doing. Are you aware of it?

I think this is affecting us all since I know that sometimes some corrections are thrown waiting for reports to know if the correction works or to undo the change because it did not work 
I think that this could leave us a tool without sufficient evidence, for the attempt of some users to continue to stay in old betas without even trying the new versions.

should prompt users to report errors

**Comment by Yochannan** [comment]
I am working with about 25 iPhones/ipt's on 12.1.1b3 and do not know where or how to share concerns, findings or successes.

**Comment by Yochannan** [comment]
I also found b29 to be pretty good, and went back to it a couple of times on 6s's

the SE's seem to play better than 6s's... don't ask me why but they do.

**Comment by Yochannan** [comment]
I'm looking forward to the 5S, IPT and THE 6 to be supported. :-)
