### ISSUE TITLE
iPad mini 4 on iOS 12.1.1 b3 (16C5050a), 'STATUS: Unsupported' on Unc0ver 3.0.0~b29 and b34

### ISSUE THREAD

**Issue by objp4th** [pwn20wndstuff/Undecimus#560]
Hello!
Just upgraded a iPad Mini 4 (iPad4,4) from 10.2 to 12.1.1 b3 and installed unc0ver b34 (then also b29) which both yield:

[*] STATUS: Unsupported

Happy to help if I can provide information.

Thanks for the great work! 👍

**Comment by objp4th** [comment]
Maybe an duplicate of issue 549 (same issue but different hardware, iPad mini 2).

**Comment by objp4th** [comment]
Mistakenly interpreted iPad4,4 as iPad Mini 4. So this is dup of #549

**Comment by ProBlauw** [comment]
Same problem #549 but other model, but that is because my chipset ain't supported yet; A7. Maybe A8 isn't supported yet either.

**Comment by objp4th** [comment]
I've corrected the title to reduce the confusion.

**Comment by ProBlauw** [comment]
Hello! I was able to jailbreak my device with the latest build (3.0.0~b37) but in my case Cydia din't show up. Do you have the same problem? 

Kind regard
