### ISSUE TITLE
app crash on start

### ISSUE THREAD

**Issue by mohsenmehrvarz** [pwn20wndstuff/Undecimus#562]
unc0ver Version: 3.0.0~b33 & 3.0.0~b34
iPhone X, 10.6
after jailbreak some of Applications crashes on startup. I had no issue on b31 and installed b31 and jailbreak with that version.

**Comment by nuno10costa** [comment]
Same here.
unc0ver 3.0.0~b34
iPhone X 10.6 12.1.2
Some apps crashes on startup, causing the device to respring. I notice it more on the camera app and safari (I don't have tweaks installed for any of those apps).
