### ISSUE TITLE
iphone 6

### ISSUE THREAD

**Issue by alimuhdi00** [pwn20wndstuff/Undecimus#563]
please release for iphone 6 ios 12.1

**Comment by Mas9311** [comment]
He is in the process of releasing a beta if not public version of unc0ver. His Twitter explains his exact progression.

Please check his Twitter for more updates: https://mobile.twitter.com/pwn20wnd?lang=en

This is not an issue nor a bug meant to be posted to GitHub. The subreddit you are looking to post this to is: https://www.reddit.com/r/JelBrek/

**Comment by alimuhdi00** [comment]
iphone 6 stuck in 21/28

**Comment by zyan910** [comment]
Close this issue, A7 and A8 support will come soon
