### ISSUE TITLE
Jailbreak for A12 devices?

### ISSUE THREAD

**Issue by FocusedSG** [pwn20wndstuff/Undecimus#564]
When will it be coming out?

**Comment by d3vCr0w** [comment]
"A12(X) support will be worked on after the public release of full 4K support."

**Comment by FocusedSG** [comment]
@d3vCr0w yea, any estimation?

**Comment by Mas9311** [comment]
There will be a beta released for A12 devices once 4K is released as a public (non-beta) version.

Check his Twitter every so often for more updates: https://mobile.twitter.com/pwn20wnd?lang=en

This is NOT an issue nor a bug on GitHub. Go to this subreddit to ask your questions: https://www.reddit.com/r/JelBrek/

**Comment by FocusedSG** [comment]
@Mas9311 thanks for the detailed reply.

**Comment by T4shf33n** [comment]
Wow ETA FOLKS are creating issues to ask. LOL don’t cross limits

**Comment by tsxmichael** [comment]
>Wow ETA FOLKS are creating issues to ask. LOL don’t cross limits

@T4shf33n they dont read! They came and created a new post when they are like 100s post asking the same over and over and they dont research🤦🏽‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d3vCr0w** [comment]
@tsxmichael indeed, can anyone else close these open "issues"?

**Comment by tsxmichael** [comment]
>@tsxmichael indeed, can anyone else close these open "issues"?

@d3vCr0w the only one that can do that is who post it or Pwn20wnd i think

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chrisg00029** [comment]
Close this! As it's not an issue

**Comment by tsxmichael** [comment]
And that will be annoying for Pwn20wnd! That its just better leave him alone and let him work and do his things!😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d3vCr0w** [comment]
@tsxmichael I agree. @FocusedSG can you close this? This isn't an issue

**Comment by zyan910** [comment]
Close this issue, it’s not an issue with unc0ver
