### ISSUE TITLE
LoopBoot

### ISSUE THREAD

**Issue by Avi3ator** [pwn20wndstuff/Undecimus#565]
I was on ios 12, tried to jailbreak, got loopboot had to reset to 12.1.4 :/

**Comment by Ezb2661** [comment]
https://twitter.com/NepetaDev/status/1100133503784701953

Save Blobs with https://tsssaver.1conan.com/

If you get another boot loop and a nonce setter utility drops you can restore with blobs back to the beta ios (which is supported by unc0ver)

**Comment by Avi3ator** [comment]
> https://twitter.com/NepetaDev/status/1100133503784701953
> 
> Save Blobs with https://tsssaver.1conan.com/
> 
> If you get another boot loop and a nonce setter utility drops you can restore with blobs back to the beta ios (which is supported by unc0ver)

i guess its to late now when i already restored it to 12.1.4?

**Comment by iamn0tdev** [comment]
@Avi3ator you can downgrade to 12.1.1 beta 3 with iTunes. If you have saved 12.1.1 or 12.1.2 blobs you can restore back to official firmware with futurerestore.
