### ISSUE TITLE
iPhone 6s, 12.1.2, using b31

### ISSUE THREAD

**Issue by myronious** [pwn20wndstuff/Undecimus#567]
apple's stock Notes app crashes. 

app icons compact on the screen sometimes, covering the icon labels and being generally annoying.  Not sure what triggers it, since I have no icon-arranging tweaks installed.

**Comment by StrugglingDoge** [comment]
I’d assume that this is a tweak conflict. This could be caused by an outdated tweak that may modify the springboard in any way. I haven't personally ran into these issues on both of my devices and notes app works fine.
