### ISSUE TITLE
iPhone X's still seem to respring loop with system daemons on?

### ISSUE THREAD

**Issue by Popcorncandy09** [pwn20wndstuff/Undecimus#570]
Some people are having success but mostly seems to be us IPH X users?...

**Comment by v3rBaLcRiMiNaL** [comment]
Yea I'm still having issues as well. Everything is fine if I turn off Reload System Daemons. When it's on it doesn't work at all. iPhone X, iOS 12.1.1.

**Comment by GucciGazm** [comment]
Also having same issue. iPhone X 12.1.1 just used restore root fs and on the final reboot it reached the Uicache and got stuck in a loop no tweaks installed

**Comment by kurtbain250** [comment]
Same here, iPhone X 12.1.2 unc0ver 3.0.0b36 respring loop with ldrestart (reload system daemon) on, turn off and everything is gold. Very stable. Also running ldrestart once jailbroken causes the same results. Last rootfs restore i did was with the last unc0ver beta34, did not correct the issue. 
Take your time pwn, no rush.

**Comment by GucciGazm** [comment]
Yes I agree no rush just trying to help

**Comment by DaddyBoard** [comment]
Still happening to me... i some how managed to get it to work ONCE after a restoreFS but now can't get back into it with RSD enabled... works for loads of others so must be only IPX affected?

**Comment by theLeroy** [comment]
I also have problems with Iphone X 12.1.2. Its not working at all. -> #595

**Comment by zyan910** [comment]
It’s a known issue, close this.

**Comment by Popcorncandy09** [comment]
Why close it if it's not been resolved?

**Comment by zyan910** [comment]
Because its a known issue, pwn is working on it and other have already opened issues
