### ISSUE TITLE
Failed to initialize patchfinder64 (Errno 1)

### ISSUE THREAD

**Issue by dstlny** [pwn20wndstuff/Undecimus#574]
Test: original_kernel_cache != NULL
Filename: JailbreakViewController.m 
Line: 855

IOS 12.1.1b3 - iPhone SE.

b34 works just fine, same with all the other betas before this.

Regardless of options that are enabled in Unc0ver, the same error occurs - with the app force-closing afterwards. Even Restore RootFS doesn't work. Tested in airplane mode and not in, doesn't make a difference - always the same error at the same line with the same test.

**Comment by dstlny** [comment]
Diagnostics are here: https://ufile.io/jxt3q

**Comment by hicmeister** [comment]
Similar for me: iPhone 10,6 iOS 12.1.2 b34 okay. b36 the following error alert:

Error (Fatal)
Errno: 1
Test: original_kernel_cache != NULL
Filename: JailbreakViewController.m
Line: 855
Function: jailbreak
Description: failed to initialize patchfinder64.

Regards,
hicmeister

**Comment by clarityzzz** [comment]
Diagnostics are empty.

**Comment by dstlny** [comment]
@clarityzzz
Fresh upload:
https://ufile.io/d0yf3

**Comment by cr419** [comment]
Same issue here, anything above b34 results in the patchfinder64 error. 
Given I’m on iPX 11.4b3 I’m guessing it’s a beta thing.

**Comment by viniciusnrc** [comment]
Same error on 6s 12.1.1  anything above beta 34 doesn't work. Once I was able to make beta 38 work but had to reboot and never worked again. Tried beta 39 today and nothing

**Comment by hicmeister** [comment]
Had my device crash yesterday - unknown why, only noticed when my theme missing and dock showing. Had no issue with rejailbreaking with b38.

**Comment by me246813579** [comment]
B41 doesn't work with my 5s, but it works with my iPad Air and iPod touch 6. On the 5s it fails to initialize patchfinder64
