### ISSUE TITLE
IPHONE X HOMEBAR FAIL? 

### ISSUE THREAD

**Issue by jayzandhuis** [pwn20wndstuff/Undecimus#576]
![acbbca04-4c7e-42d5-994a-c066eaa6c6cb](https://user-images.githubusercontent.com/48037191/53457064-26300300-3a31-11e9-8f28-132595489d4b.png)
![4c659020-44b5-4ece-91a5-951be087a9ae](https://user-images.githubusercontent.com/48037191/53457065-26300300-3a31-11e9-8ab9-0096c150af23.png)

As u can see the home bar/ display size in screen fails after the jailbreak? How do i fix this?

**Comment by gotrandom** [comment]
HideBarX is something I’ve always used because I’m paranoid about it causing burn-in anyway and I highly recommend it. (From SparkDev’s Repo)

**Comment by jayzandhuis** [comment]
Yeah iknow that one but that does not fix the problem, i mean the display moved badly as u can see in the following screenshot, look al the way at the bottom and than u can see the difference between jailbroken and non-jailbroken
![8992a015-8dab-4b09-8a97-3a0320356e6d](https://user-images.githubusercontent.com/48037191/53478588-75008b80-3a77-11e9-9f46-89a7ced04bb6.png)
