### ISSUE TITLE
Line 926: Failed to escape sandbox.

### ISSUE THREAD

**Issue by nn9dev** [pwn20wndstuff/Undecimus#578]
using beta 36, have tried a number of times. rebooted, yet still get this error.
stops about here:
``[*] Escaping Sandbox...
[*] error reading kernel @0x56007a2064207178
[*] myProcAddr = 0x0000000000000000
[*] 
__assert(9:ISADDR(myProcAddr))@JailbreakViewController.m:926[jailbreak]``

@jakeajames do you think you could offer insight, since if i recall correctly you did sandbox patches?

**Comment by nn9dev** [comment]
okay, i added some debug lines of my own and it's solved??? added this at line 924 and 925
`LOG("myPid= " ADDR, myPid);
LOG("AAA= " ADDR, get_proc_struct_for_pid(myPid));`

**Comment by nn9dev** [comment]
have not closed because i would still like insight into why this randomly happened and then stopped. @jakeajames ?

**Comment by CoolPersonMaam** [comment]
Restart and click jailbreak again

**Comment by Regaily** [comment]
Hi, I am getting this error even after using beta 43, I have iphone X 64 GB, and using IOS 12.1.1 beta 3

**Comment by DrissiReda** [comment]
I have a similar issue, on my X on 12.1.2(16C104) : 
Errno: 9
```Test: ISADDR(myProcAddr)
Filename: JailbreakViewController.m
Line:884
Function: jailbreak
Description,: Failed to escape sandbox.```

I've tried many betas like @Regaily and still none of them worked.
