### ISSUE TITLE
Nobetaalert is always installed

### ISSUE THREAD

**Issue by wz1129** [pwn20wndstuff/Undecimus#579]
Please set a switch to turn off its installation.I have an idea, if the length of the version number is greater than 6 digits, it will not be installed.

**Comment by wz1129** [comment]
There is also a bug. If the Disable Auto Update is not enabled, there will be a red mark in the settings.

**Comment by zyan910** [comment]
It’s installed to get rid of the beta popup, what’s the issue?

**Comment by wz1129** [comment]
Because I am the official version！

**Comment by king4q** [comment]
@Samgisaninja

**Comment by wz1129** [comment]
@sbingner Please fix it

**Comment by Samgisaninja** [comment]
Yeah, I’ll make this later.
