### ISSUE TITLE
Jailbroken but no Cydia

### ISSUE THREAD

**Issue by boombos** [pwn20wndstuff/Undecimus#58]
I'll try to be as detailed as possible.

ios 11.3.1 iPhone 7 Plus RC8

1) Had phone jailbroken on Electra before
2) Downloaded unc0ver and hit Jailbreak
3) success on the first try
4) after phone was jailbroken with unc0ver, cydia still showed all the sources and tweak list i had from electra jailbreak.
5) this included electra's default repos
6) tweaks from electra were showing in cydia but none of them were actually working etc.
7) this means? i had the old cydia from electra even after jailbroken with unc0ver
8) hence i used roll electra to do a full restore of my device
9) all my data gone like photos etc(i knew this) but..
10) cydia and some jailbreak apps that i had installed with electra were still present even after roll electra
11) for eg cocoa top, i cleaner, wifi kill, filza, 
12) what the hell, downloaded unc0ver again and hit jailbreak after all this
13) again succesfully jailbroken but now my Cydia is gone
14) checked the discord and they gave me a cydia repo url to add in safari and i could not do so
15) means cydia is definetely gone
16) so this is my situation

**Comment by Cryptiiiic** [comment]
#56

**Comment by Samgisaninja** [comment]
Closing because duplicate, please "Watch" issue 56 if you'd like to receive notifications
