### ISSUE TITLE
Cannot touch Messages notification

### ISSUE THREAD

**Issue by julesfr6** [pwn20wndstuff/Undecimus#580]
When someone sends me a message (iMessage or text) and the Messages notification pops up, I cannot touch it to go to the messages app. I have to manually go to the app. Every other notification works though. I uninstalled all tweaks and have the default jailbreak and it still happens.

**Comment by julesfr6** [comment]
Also does the same thing on the lockscreen or if I pull down to the notification center and try to touch it there.

**Comment by gotrandom** [comment]
Are you guys using ApolloOpener or libOpener? That was preventing me from tapping message notifications. Removing these fixed the issue.

**Comment by julesfr6** [comment]
Nope, not using either of those.

Le mar. 26 févr. 2019 à 23:11, gotrandom <notifications@github.com> a
écrit :
