### ISSUE TITLE
Failed to extract bootstrap on fully restored iOS 12.1.1b3 iPhone 6s+ with unc0ver v3.0.0~b36 

### ISSUE THREAD

**Issue by vietbach22** [pwn20wndstuff/Undecimus#582]
Previously I was on clean iOS 12.1.1, turned on Airplane Mode, tried all beta versions of unc0ver but always got the same `Errno: 2 - Failed to extract bootstrap` so I restored it to 12.1.1b3 and tried to jailbreak but still got the same error. Log files are attached, hope those help.
[log_file_1.txt](https://github.com/pwn20wndstuff/Undecimus/files/2908523/log_file_1.txt)
[log_file_2.txt](https://github.com/pwn20wndstuff/Undecimus/files/2908524/log_file_2.txt)

**Comment by devcline** [comment]
try with enable 'Restore RootFS(rec0ver)' and let me know if it works.

**Comment by bstillitano** [comment]
@devcline that worked. Here’s what I did. 

Following steps were done after closing all background apps and enabling aeroplane made. 

1. Reinstall unc0ver
2. Enable Restore RootFS
3. Run Jailbreak 
4. Allow Restart
5. Run Jailbreak (Receive message about snapshot being saved)
6. Allow Restart
7. Run jailbreak (Received message about bootstrap being extracted successfully)
8. Allow restart
9. Run jailbreak
10. Allow respring (didn’t press anything, it just resprings)
11. Cydia now installed.

**Comment by kalifans** [comment]
unc0ver v3.0.0~b34 & unc0ver v3.0.0~b36
iOS 12.0.1 Unable to mount system snapshot
[https://i.imgur.com/3fB8fxQ.png](url)

**Comment by dnogwat** [comment]
doesnt work with restore RootFS
