### ISSUE TITLE
can't use cycript

### ISSUE THREAD

**Issue by timelessg** [pwn20wndstuff/Undecimus#584]
when i use cycript -p xxx, it's showing

```
 [1314] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary
```
all of the application are throw this error when i use cycript

I think that it about patch kernel, and my phone is iphone se,os is 12.1

Best wishes

**Comment by flockoffiles** [comment]
Same here (when trying to inject bfdecrypt.dylib)

```
cynject 871 /usr/lib/bfdecrypt.dylib
```

```
[883] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
```

**Comment by mgfjxxiexiaolong** [comment]
Yes, same problem.
```
[9595] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary
```

**Comment by Jackiedk100** [comment]
Same here... injecting with bfdecrypt.dylib..

```
cynject 5161 /usr/lib/bfdecrypt.dylib
[5162] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
```

**Comment by VladislavVesely** [comment]
Yes, same problem.

[9595] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary

**Comment by xunbu7** [comment]
[9671] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary

**Comment by ngn999** [comment]
same problem here, 
just happened when attatching to  some app, while attatching to others, it works.

**Comment by mcn2004** [comment]
Same problem... I think that is a problem with the codesign and we need tu bypass the AMFI, because i have a similar problem with memctl

**Comment by Mr007jd** [comment]
**Same Problem here:**
iso 12.1.1 and uncover jailbreak .
Version:0.9.520-X12

**Error****:**
[826] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary

**Comment by bigdogs** [comment]
Same Problem : 
~ root# cycript -p Snapchat
[7327] DarwinInjector.cpp[246]: _krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary


Sad... :(

**Comment by 0OOooOO0** [comment]
Not the same problem on iOS 11.0.1 unc0ver 3.2.1 when I run cycript, I got `Killed: 9`.

**Comment by pwn20wndstuff** [comment]
The DarwinInjector.cpp/Inject.cpp failures are entirely related to Saurik’s Substrate and a change that was made in iOS 12 that breaks them. I have no control over this

**Comment by mxdhqm** [comment]
same problem on iOS 12.2, I tried the lasted version and still can't use it.

```
[2283] task_for_pid(0)
[2283] _assert(MSSetKernelPort())[DarwinKernel.cpp:233]
````

**Comment by Yongle-Fu** [comment]
iOS 11, got 
Killed: 9

after add ent, got
dyld: Library not loaded: /usr/lib/libcycript.dylib
  Referenced from: /usr/bin/cycript
  Reason: no suitable image found.  Did find:
	/usr/lib/libcycript.dylib: code signing blocked mmap() of '/usr/lib/libcycript.dylib'
	/usr/lib/libcycript.dylib: code signing blocked mmap() of '/usr/lib/libcycript.dylib'

**Comment by yejunyou** [comment]
The same 
5s iOS12.2 
_krncall(mach_vm_read_overwrite) =10000003
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary

But it works at 5s iOS9.2.1

**Comment by lolicon** [comment]
iOS 12.4 
iPhone SE

Suzume:~ root# cycript -p 2725
[2758] _krncall(task_for_pid) =5
[2758] MachObject.cpp[106]: _krncall(task_info) =10000003
[2758] DarwinInjector.cpp[73]: _assert(MSGetTaskInfo(info, task))[DarwinInjector.cpp:73]
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary

**Comment by Rosle23** [comment]
iOS 10.3.3
iPhone 5s

root# ps -ax | grep testapp
4981 ttys002    0:00.00 grep testapp
Sectest-iPhone:~ root# cycript -p 4981
sh: /usr/bin/cynject: No such file or directory
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary

**Comment by kevinpiac** [comment]
Same there iOS 11.2

```
^[[A[3223] _krncall(task_for_pid) =5
[3223] MachObject.cpp[106]: _krncall(task_info) =10000003
[3223] DarwinInjector.cpp[73]: _assert(MSGetTaskInfo(info, task))[DarwinInjector.cpp:73]
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary```

**Comment by Yongle-Fu** [comment]
fixed  use cyrun

**Comment by Mr007jd** [comment]
This may help -> fixed

https://gist.github.com/laprasdrum/667213ab364ef2536a30f3bdb79c77bb
