### ISSUE TITLE
jailbreak detection bypass

### ISSUE THREAD

**Issue by mohammadabumoosa** [pwn20wndstuff/Undecimus#586]
all banking apps and games are disabled because of detecting jailbreak
i used all jailbreak detection bypass but it falls and reboot help ?

**Comment by mohammadabumoosa** [comment]
also tried all flex3 scripts not working and still crash

**Comment by T4shf33n** [comment]
Try safemode when needed

**Comment by Mas9311** [comment]
This is neither an issue or a bug with unc0ver. I’m guessing you’re using a system-wide tweak (like bloard).

Feel free to post this in https://www.reddit.com/r/jailbreak/ as a [Request] post with the specific app name(s).

Please close this issue, @mohammadabumoosa.

**Comment by Phukit** [comment]
use libertylite works great

**Comment by coenkcore** [comment]
Use libertylite bro.
