### ISSUE TITLE
iPhone X still can't Jailbreak with Reload System Daemons

### ISSUE THREAD

**Issue by DaddyBoard** [pwn20wndstuff/Undecimus#587]
I some how managed to get it to work ONCE after a restoreFS but now can't get back into it with RSD enabled... works for loads of others so must be only IPX affected?

Also random resprings every 3-4 minutes during the one time I could enable RSD, but with it turned off, jailbreaks first time every time and no random resprings?

@pwn20wndstuff  please can we work on fixing this? Half my tweaks are not working correctly and need constant resprings

**Comment by theLeroy** [comment]
I also have problems with iphone x Jb. Its not working -> #595

**Comment by DaddyBoard** [comment]
@pwn20wndstuff 
Please, help us iPhone X users?
