### ISSUE TITLE
I'm jailbroken but there is no Cydia and no ssh

### ISSUE THREAD

**Issue by trista71** [pwn20wndstuff/Undecimus#59]
i'm at a loss what to do. I see some other people are having the same issue as me so i'm not alone. Hopefully there's a fix? Please advice

**Comment by KMamedoff** [comment]
toggle on "Refresh Icon Cache" in unc0ver settings.

**Comment by Cryptiiiic** [comment]
#56

**Comment by pycak1** [comment]
Same here uicache not helping either

**Comment by Samgisaninja** [comment]
Closing because duplicate, please "Watch" issue 56 if you'd like to receive notifications
