### ISSUE TITLE
iPhone random resprings

### ISSUE THREAD

**Issue by nuno10costa** [pwn20wndstuff/Undecimus#590]
Is anyone facing ramdon reprings when trying to open apps like camera, messages, etc? It doesn't happen everytime, but it happens quite several times during a day.
I have an iPhone X on 12.1.2 JB with unc0ver b36.
Is there any app that tells us what may be causing the issue? If it's a tweak or maybe something related to unc0ver itself?
CrashReported is not getting satisfying results....

**Comment by Drhellboy22** [comment]
Am having the same problem

**Comment by DaddyBoard** [comment]
> Is anyone facing ramdon reprings when trying to open apps like camera, messages, etc? It doesn't happen everytime, but it happens quite several times during a day.
> I have an iPhone X on 12.1.2 JB with unc0ver b36.
> Is there any app that tells us what may be causing the issue? If it's a tweak or maybe something related to unc0ver itself?
> CrashReported is not getting satisfying results....

Few questions.

1. Have you got Reload System Daemons enabled?
2. Does it also happen when clicking notifications on the lockscreen (sometimes anywhere)?

**Comment by nuno10costa** [comment]
1. Yes, I have reload system daemons enabled. 

2. No, only when opening the app itself.

**Comment by DaddyBoard** [comment]
> 1. Yes, I have reload system daemons enabled.
> 2. No, only when opening the app itself.

1. That's really strange.... I've Restored RootFS twice now, on b29 and b34 and I cannot get it to Jailbreak with Reload System Daemons at all! How tf have you managed?

2. Hmm, mine crashing even just swiping up to unlock. just seems to crash a hell of a lot, but could be tweaks... crash reporter doesnt show anything to me.

**Comment by nuno10costa** [comment]
Why aren't you on b36?
What I usually do to make it work is to jailbreak first with system demons off (this usually takes 2 attemps until it's successfuly jailbroken). Once it's done, I change the option to on, and hit jailbreak again.

Yes, crash reporter doesn't show anything useful.

Can anybody help?

**Comment by nuno10costa** [comment]
I'm going to downgrade to an older version of unc0ver. I don't think I had this issue in the first versions...

**Comment by nuno10costa** [comment]
It happened in b30 also... I deleted everyting and jailbreaked from scratch (no tweaks). Just installed a few, and so far so good...

**Comment by lbenicio** [comment]
Same here on beta39 but I have 100 tweaks installed.... Maybe it is a tweak
