### ISSUE TITLE
How can I use debugserver on iOS12

### ISSUE THREAD

**Issue by eziochiu** [pwn20wndstuff/Undecimus#591]
iPhone-6s:~ root# debugserver localhost:6666 -a "SpringBoard"
/usr/local/bin/debugserver: line 11:  5847 Killed: 9               
/usr/bin/debugserver > /dev/null 2>&1
WARNING: -H is only present for compatibility with a fork of ldid  you should NOT be manually specifying the hash algorithm
Killed: 9

How can I use debugserver on iOS12 ? Please help

**Comment by holyswordman** [comment]
i can run but got "Failed to get connection from a remote gdb process." error
i think it's something related to entitlement or kernel patching?

iPhone:~ root# debugserver *:6666 --attach=Reddit
debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
for arm64.
Attaching to process Reddit...
Listening to port 6666 for a connection from *...
Failed to get connection from a remote gdb process.
Exiting.
iPhone:~ root#

Console log in mac:
預設值 20:31:26.086394 +0800 debugserver debugserver will use ASL for internal logging.
預設值 20:31:26.159243 +0800 debugserver debugserver will use ASL for internal logging.
預設值 20:31:26.512377 +0800 debugserver Warning: Libinfo call to mDNSResponder on main thread
錯誤 20:31:26.512834 +0800 kernel Sandbox: debugserver(997) deny(1) network-outbound /private/var/run/mDNSResponder
預設值 20:31:26.513454 +0800 debugserver dnssd_clientstub ConnectToServer: connect()-> No of tries: 1
預設值 20:31:27.550943 +0800 debugserver dnssd_clientstub ConnectToServer: connect()-> No of tries: 2
預設值 20:31:28.553120 +0800 debugserver dnssd_clientstub ConnectToServer: connect()-> No of tries: 3
預設值 20:31:29.570938 +0800 debugserver dnssd_clientstub ConnectToServer: connect() failed path:/var/run/mDNSResponder Socket:6 Err:-1 Errno:1 Operation not permitted
預設值 20:31:29.575520 +0800 kernel Sandbox: 3 duplicate reports for debugserver deny(1) network-outbound /private/var/run/mDNSResponder
錯誤 20:31:29.575619 +0800 kernel Sandbox: debugserver(997) deny(1) system-socket
錯誤 20:31:29.575772 +0800 debugserver socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: Operation not permitted
錯誤 20:31:29.576274 +0800 debugserver socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: Operation not permitted
預設值 20:31:29.577772 +0800 kernel Sandbox: 1 duplicate report for debugserver deny(1) system-socket
錯誤 20:31:29.577819 +0800 kernel Sandbox: debugserver(997) deny(1) network-bind:6666*
預設值 20:31:29.578459 +0800 debugserver 1 +0.000000 sec [03e5/0403]: ::listen or ::bind failed err = 0x00000000
預設值 20:32:02.300697 +0800 kernel Sandbox: 3 duplicate reports for debugserver deny(1) network-bind:6666*

**Comment by MartinPrusa** [comment]
@eziochiu look on my issue, I've solved some of your issues there https://github.com/pwn20wndstuff/Undecimus/issues/531

**Comment by yuripe-murmur** [comment]
I got same error too.

root# debugserver *:1234 -a AppStore
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-900.3.86
 for arm64.
Attaching to process AppStore...
Listening to port 1234 for a connection from *...
Failed to get connection from a remote gdb process.
Exiting.

@holyswordman 您好，請問您是台灣人嗎？
冒昧地請問您，不知道能不能與您做越獄開發的交流呢？謝謝。

**Comment by holyswordman** [comment]
i have figured it out. debugserver actually works.

1. To solve failed to get connection from a remote gdb process issue: resign debugserver without "seatbelt-profiles" entitlement xml.

 (They fixed now, so just updates "Unc0ver Jailbreak Resources" in Cydia and reload the new debugserver)

2. To solve another EXC_BAD_ACCESS issue: The target process being debugged needs the get-task-allow entitlement . you can resign the app (your target app being debugged, not debugserver) with get-task-allow entitlement as a temporary workaround. then debugserver will works!

I believe they have fixed it already.
Next "Unc0ver Jailbreak Resources" update in Cydia App should solve it.

**Comment by holyswordman** [comment]
> 
> 
> I got same error too.
> 
> root# debugserver *:1234 -a AppStore
> debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
> for arm64.
> Attaching to process AppStore...
> Listening to port 1234 for a connection from *...
> Failed to get connection from a remote gdb process.
> Exiting.
> 
> @holyswordman 您好，請問您是台灣人嗎？
> 冒昧地請問您，不知道能不能與您做越獄開發的交流呢？謝謝。

都可以的

**Comment by lixianshen** [comment]
> I got same error too.
> 
> root# debugserver *:1234 -a AppStore
> debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
> for arm64.
> Attaching to process AppStore...
> Listening to port 1234 for a connection from *...
> Failed to get connection from a remote gdb process.
> Exiting.
> 

越狱交流

> I got same error too.
> 
> root# debugserver *:1234 -a AppStore
> debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
> for arm64.
> Attaching to process AppStore...
> Listening to port 1234 for a connection from *...
> Failed to get connection from a remote gdb process.
> Exiting.
> 
> @holyswordman 您好，請問您是台灣人嗎？
> 冒昧地請問您，不知道能不能與您做越獄開發的交流呢？謝謝。



> I got same error too.
> 
> root# debugserver *:1234 -a AppStore
> debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
> for arm64.
> Attaching to process AppStore...
> Listening to port 1234 for a connection from *...
> Failed to get connection from a remote gdb process.
> Exiting.
> 
> @holyswordman 您好，請問您是台灣人嗎？
> 冒昧地請問您，不知道能不能與您做越獄開發的交流呢？謝謝。
