### ISSUE TITLE
Can't Jailbreak with Reload System Daemons iPhone SE 12.1.1

### ISSUE THREAD

**Issue by sharjeel-k** [pwn20wndstuff/Undecimus#592]
tried rootfs but worked for the first time with b34. After restart its not 
updated to 36 but still stuck on respring . Working fine without Reload System Daemons .

**Comment by king4q** [comment]
RootFS Restore with Beta 36 & then rejailbreak it’ll fix the issue I personally had this fix my respring loop issue.

**Comment by sharjeel-k** [comment]
worked for the first time only after rootfs restore

**Comment by zyan910** [comment]
It’s a known issue, and pwn is working on it. Close the issue

**Comment by king4q** [comment]
Can confirm after the first jailbreak it won’t repring with “Reload System Daemons” on. @samgisaninja
