### ISSUE TITLE
battery drain

### ISSUE THREAD

**Issue by Phukit** [pwn20wndstuff/Undecimus#594]
I have iphone 6S on ios 12.1 and the battery gets drained pretty fast! 

I am using unc0ver 3.0.0 b36

Let me know if you need anything.

**Comment by zyan910** [comment]
Get system info from cydia and see what exactly is draining the battery

**Comment by Phukit** [comment]
its definitely the JB.

I can sit here and just watch the battery percentage drop as if its just counting down.  also I think its just reporting wrong.   as it drops 5% as soon as the jailbreak completes and resprings.

**Comment by saminista7** [comment]
Phukit did you fix the issue? I'm having the same problem
