### ISSUE TITLE
Device resprings before the user can view log or press OK

### ISSUE THREAD

**Issue by GeoSn0w** [pwn20wndstuff/Undecimus#596]
After the jailbreak runs, the device shows the alert which gives two options. Either "OK" or "View log". One cannot view the log because 1 second later the device resprings.

Proposed solution: The respring should happen after the user presses "OK" on the alert.

**Comment by coupedeebaybee** [comment]
Same issue here, but you know inside the unc0ver app, there is a pretty substantial logfile.txt
/var/mobile/Containers/Data/Application/{app-name here}/Documents/
