### ISSUE TITLE
Bundle OpenSSH with unc0ver and add a setting to change password without terminal

### ISSUE THREAD

**Issue by KMamedoff** [pwn20wndstuff/Undecimus#60]

**Comment by Samgisaninja** [comment]
personally I like this idea, but I actually suggested it several weeks ago during testing, I don't think it's gonna happen.

**Comment by KMamedoff** [comment]
With optional enable/disable switch for OpenSSH it would be very useful.

**Comment by blanxd** [comment]
if ever implemented, it Must be off by default !!! Else most will be walking around with 22 waiting for alpine.

**Comment by pwn20wndstuff** [comment]
It’s security issue and would make the app take up more space.
