### ISSUE TITLE
libcc install error

### ISSUE THREAD

**Issue by SwedishPrxck** [pwn20wndstuff/Undecimus#605]
I tried to look before I posted this and didn't find anything.

When I try to install the libgcc package through cydia, I end up getting:

"ldid failed to sign libraries"
"Sub-process /usr/libexec/cydia/cydo returned an error code (1)"

Any help would be greatly appreciated!

I'm on an iPx running 12.1.1 b3

**Comment by TempAccountNull** [comment]
Jake has said here: https://github.com/pwn20wndstuff/Undecimus/issues/423 | That it can result due to corrupted / invalid libraries. Try re downloading libcc.

**Comment by SwedishPrxck** [comment]
It's not currently installed, my fault. It's asking to install, not upgrade

**Comment by SwedishPrxck** [comment]
> Jake has said here: #423 | That it can result due to corrupted / invalid libraries. Try re downloading libcc.

It's not currently installed, my fault. It's asking to install not upgrade
