### ISSUE TITLE
Reloading System Daemons issue is still affecting me even on b37.

### ISSUE THREAD

**Issue by mohitt01p** [pwn20wndstuff/Undecimus#609]
[iPhone 7 Plus, iOS 12.1.1b3] Using u0 b37, I ran RootFS to fix the Reloading System Daemons issue I previously had. I was then able to jailbreak. Half a day later, when respringing, I have run into the same issue again! Is it just me or is there something up?

**Comment by xMilesManx** [comment]
Do you have rocketbootstrap? pwn said its due to that or a tweak that hasnt properly been updated.

**Comment by king4q** [comment]
This is a known issue & a duplicate. @Cryptiiiic please merge issue with issue #381 or close this issue.
