### ISSUE TITLE
stuck at 24/49 device will restart since first attempt using RC8 iOS 11.3.1 on i7 Plus (more than 150 attempts)

### ISSUE THREAD

**Issue by HELLACOOT** [pwn20wndstuff/Undecimus#61]
a lot of other people on the discord and r/jailbreak are having the same issue.

**Comment by Samgisaninja** [comment]
If there's an error message, can you please screenshot and send here?

Make sure you're on the latest RC9.

**Comment by DropZite** [comment]
It works now for me after using RC9. On RC8 I am stuck on 24/49 as well.
Thanks!

**Comment by zackery1215** [comment]
is it just me or is there no RC9 IPA anywhere?

**Comment by pwn20wndstuff** [comment]
Fixed in V1.
