### ISSUE TITLE
Undecimus-3.0.0-b36/snappy/libsnappy.c lost

### ISSUE THREAD

**Issue by beyondxx3** [pwn20wndstuff/Undecimus#611]
clang: error: no such file or directory: '/Users/mymac/Downloads/Undecimus-3.0.0-b36/snappy/libsnappy.c'
clang: error: no input files

**Comment by king4q** [comment]
Diagnostics Log?

**Comment by clarityzzz** [comment]
Git submodule init && git submodule update
