### ISSUE TITLE
iPhone X (10,6) heating issue with ~b37 | ~b36 does not have this issue

### ISSUE THREAD

**Issue by dodvip123** [pwn20wndstuff/Undecimus#612]
I don't know what is causing the heating but it kicks in after a few minutes of using my iPhone X.

Downgraded back to ~b36 and the heating was gone. I have not changed my tweak list in the meantime (only using essentials like ReProvision, Filza, iCleaner Pro, etc.)

**Comment by king4q** [comment]
@ Cryptiiiic

**Comment by king4q** [comment]
@Cryptiiiic
