### ISSUE TITLE
[GitHub Enhancement] Issue Posting Guidelines

### ISSUE THREAD

**Issue by king4q** [pwn20wndstuff/Undecimus#613]
Make guidelines & to-dos before posting a issue. Such as updating to the latest build, providing diagnostics log, etc

**Comment by airsquared** [comment]
I can help add [Issue Templates](https://help.github.com/en/articles/about-issue-and-pull-request-templates)

**Comment by Cryptiiiic** [comment]
Also done #627 so closing this.
