### ISSUE TITLE
Banking Apps

### ISSUE THREAD

**Issue by Marcel8x8** [pwn20wndstuff/Undecimus#614]
The Banking app „Sparkasse“ 
Dont work anymore. 
Even with NoSub there‘s no change.

**Comment by samtaborsky** [comment]
Not working for me too, and after reinstalling NoSub it just gives "Cannot load the preference bundle.."

**Comment by coenkcore** [comment]
Try using libertylite

**Comment by VanishingTacos** [comment]
This really is not an issue with Unc0ver itself.
