### ISSUE TITLE
Celllular connection dropping from b34

### ISSUE THREAD

**Issue by samtaborsky** [pwn20wndstuff/Undecimus#615]
From b34 I am experiencing dropping of cellular connection, few times an hour the connection just drops and it goes "searching" and then reconnects. I tried using my phone without jb for a few hours and the problem disappeared.
iPhone SE, 12.1.2, b37

**Comment by joseashb** [comment]
It is because of the NoBetaAlert that unc0ver installs, jailbreak and remove it

**Comment by Hackerpunk1** [comment]
It is because of the NoBetaAlert that unc0ver installs, jailbreak and remove it. Should fix the issue

**Comment by Hackerpunk1** [comment]
It is because of the NoBetaAlert that unc0ver installs, jailbreak and remove it

@pwn20wndstuff : Can you please remove NoBetaAlert from the bundle, as it get reinstalled every time.
Thanks in Advance
