### ISSUE TITLE
Version ~b37 jailbreaks, but no Cydia

### ISSUE THREAD

**Issue by artelse** [pwn20wndstuff/Undecimus#616]
Tried version ~b37 on iPad Mini 2 and 5S. Both report to be jailbroken after step 21, but no Cydia (enabled restore in settings). As per forum I tried restoring rootfs, but to no avail. After some more jailbreak attempts cannot get it to jailbreak again.. Hints?

**Comment by tsxmichael** [comment]
Enable reinstall cydia and disable reload system deamons 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WinterXMQ** [comment]
![a1ccaa37065d5371bed7c8d23538519f](https://user-images.githubusercontent.com/3694982/53562810-5987a480-3b8d-11e9-90b7-e49230fa9258.png)
![9b5474b1dd14f15dd61305aaf7aca6c4](https://user-images.githubusercontent.com/3694982/53562818-5f7d8580-3b8d-11e9-8db3-8df7520de221.png)
Still no Cydia

**Comment by SuperBarracuda** [comment]
Try again with wifi and in airplane mode.

**Comment by artelse** [comment]
Same problem here. It reports Jailbroken, resprings and then no Cydia. Unc0ver then says Re-Jailbreak..

**Comment by WinterXMQ** [comment]
![image](https://user-images.githubusercontent.com/3694982/53565145-92c31300-3b93-11e9-98e7-2844b578ecc7.png)
4k(A7 & A8) is still under test. In the code, we can know that it will stop at 21 step(just after jailbreak directory created).

**Comment by coenkcore** [comment]
Unc0ver 3.0.0~b37 on 4K devices for now is partial jailbreak support with no cydia. Please always read notes on every release before installing, so you know what change and new feature on latest vesion
