### ISSUE TITLE
Reload System Daemons not work on clean iOS 12.1.1 b3.

### ISSUE THREAD

**Issue by ConfirmedPlayer** [pwn20wndstuff/Undecimus#617]
Reload System Daemons not work. Version of Unc0ver 3.0.0 b36

**Comment by Steve-luo** [comment]
* Disable all tweaks using iCleaner Pro

* Reboot instead of respring

* Jailbreak with reload system daemons turned on

* Turn the tweaks back on and respring

This did the trick for me.

**Comment by ConfirmedPlayer** [comment]
Thanks you, but jailbreak works fine without this function =)

**Comment by Steve-luo** [comment]
Some tweaks do require reloading system daemons to function properly. It is better to turn it on to avoid possible problem. But if it's causing problem, leave it off for now and wait for the conflicting tweaks (e.g. RocketBootstrap) to be updated.

**Comment by ConfirmedPlayer** [comment]
Okay, Thanks for advice. I will do that.
