### ISSUE TITLE
Jailbreak Failed on iPhone 6 12.1.1 

### ISSUE THREAD

**Issue by Koleman1312** [pwn20wndstuff/Undecimus#620]
Alright, when i try to jailbreak i get this error saying "RootFS is already mounted, delete OTA file from settings..." i already check before hitting jailbreak. I can't do jailbreak my device without getting this error.

Note: When i go to "software update" in settings, there is also an error saying that it was unable to check for an update...

Help! Thank you

**Comment by FelenAmvrosiy** [comment]
You are won't jailbroke your iPhone because if you see "Unable to check" it's signal to impossible jailbreak

**Comment by Koleman1312** [comment]
Any way to fix that?

**Comment by DJCHICKEN4** [comment]
@Koleman1312 The OTA is not under the software update section it's under `Settings>General>iPhone Storage` also make sure airplane mode is on before you jailbreak.
