### ISSUE TITLE
Celllular connection dropping also with NoBetaAlert removed

### ISSUE THREAD

**Issue by samtaborsky** [pwn20wndstuff/Undecimus#626]
I opened an issue today about my cellular connection randomly dropping and going to "Searching" and then for a moment to "Locked SIM" and I was told to remove NoBetaAlert, but the issue still persists.

iOS 12.1.2, b37 iPhone SE

**Comment by airsquared** [comment]
Try taking out your SIM card and putting it back in.(worked for me)

**Comment by Cryptiiiic** [comment]
Nothing to do with unc0ver, 12.1.2 16C101 is a broken update and has potential cellular issues, the only way to fix is to either downgrade to 12.1.1 or upgrade to 12.1.2 16C104 using blobs, closing this.
