### ISSUE TITLE
Third attempt, cellular data dropping in b37

### ISSUE THREAD

**Issue by samtaborsky** [pwn20wndstuff/Undecimus#628]
As I said twice before, after updating unc0ver to b37 my cellular data keeps constantly dropping, and NO, it has never done that both on earlier versions on unc0ver or without jb, and I am running 12.1.2 for quite a long time now. And I have seen at least one identical issue with b37. So please, do not close this issue as soon as you see it, thanks.

**Comment by Cryptiiiic** [comment]
@samtaborsky I responded and closed to your other issue... This has nothing to do with unc0ver. #626.
Also read the guidelines #627. If you open another issue related to this, you will be banned from creating issues.

**Comment by samtaborsky** [comment]
What are you trying to do? I said that the issue appeared AFTER UPDATING to b37, that it has not once appeared before or without jb, so why are you still closing these issues so no one can see them and maybe help or reply with the same issue?

**Comment by samtaborsky** [comment]
If you have the same software for a few months and then you update unc0ver to b37 and this issue appears you really think that there is NO CHANCE it could have something to do with unc0ver?

**Comment by Cryptiiiic** [comment]
What version of 12.1.2 do you have? 16C101 or 16C104. Post proof.
