### ISSUE TITLE
Time display issue on the iPhone X

### ISSUE THREAD

**Issue by nfshp253** [pwn20wndstuff/Undecimus#630]
@pwn20wndstuff 

The time display on the iPhone X (12.1.1) has some issues after jailbreaking with unc0ver (since b29, but now on b38), as it is somehow combined with the carrier name. For example, if the time is 2:45pm and the carrier name is Kaktus, the time display will show '2:4KAK...'. If the time consists of a double-digit hour, such as 12:00pm, it'll show '12:KAK...' instead.

![ogiwf0sg7smovy44ohjx4emoonu26wz5g4zfqijbyhc](https://user-images.githubusercontent.com/34688918/53605844-ff9cd400-3bb8-11e9-87d3-4fa47d080452.jpg)

**Comment by AppleNati0n** [comment]
what 
carrier tweak you use ????

**Comment by nfshp253** [comment]
I'm not using any carrier tweaks.

**Comment by Cryptiiiic** [comment]
Closing, user didn't follow the guidelines or use the template.
