### ISSUE TITLE
A feature after unjailbreak cydia will be deleted from your device .

### ISSUE THREAD

**Issue by mikemike998** [pwn20wndstuff/Undecimus#631]
**Describe the feature you'd like** A feature after unjailbreak cydia will be deleted from your device .

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. When you unjailbreak your device you don't have to reset or restore your device to get cydia off from your device .

**Additional context**

**Comment by Cryptiiiic** [comment]
Cydia isn't actually on the device, just the icon is after you RootFS restore(rec0ver). This might be fixable if uicache is ran after Rec0ver but I'm not 100% sure.

**Comment by mikemike998** [comment]
> Cydia isn't actually on the device, just the icon is after you RootFS restore(rec0ver). This might be fixable if uicache is ran after Rec0ver but I'm not 100% sure.

I try everything to get it remove but nothing work I don't want to restore my iphone yet .

**Comment by Cryptiiiic** [comment]
Well it has to be fixed in order to run uicache after RootFS restore. It's not implemented yet, not 100% if its possible.

**Comment by mikemike998** [comment]
> Well it has to be fixed in order to run uicache after RootFS restore. It's not implemented yet, not 100% if its possible.

Do you have the same issues that some people and I am having ?

**Comment by Cryptiiiic** [comment]
Please understand what I'm saying... Everyone has this problem...

**Comment by mikemike998** [comment]
> Please understand what I'm saying... Everyone has this problem...  I am  that why it need to be fixed .

**Comment by Cryptiiiic** [comment]
I am just acknowledging this enhancement request and saying whats needed to be done.

**Comment by mikemike998** [comment]
> I am just acknowledging this enhancement request and saying whats needed to be done. 

Ok thanks you  .

**Comment by VanishingTacos** [comment]
As a work around to get rid of the Cydia icon you could use rootlessJB and then SSH in and then run uicache. Then just remove rootless. This is a lot more convenient then resting everything.

**Comment by mikemike998** [comment]
> As a work around to get rid of the Cydia icon you could use rootlessJB and then SSH in and then run uicache. Then just remove rootless. This is a lot more convenient then resting everything.

I just wait to see what they do to this issues I open .

**Comment by CoolPersonMaam** [comment]
Actually this is how you fix it.

First go to Cydia delete substrate 
And then get OpenSSH access and delete cydia.app
Then restore RootFS

thank me later

**Comment by mikemike998** [comment]
> Actually this is how you fix it.
> 
> First go to Cydia delete substrate
> And then get OpenSSH access and delete cydia.app
> Then restore RootFS
> 
> thank me later

Show me a video of it ?

**Comment by mikemike998** [comment]
I have fixed it by watching this video https://www.youtube.com/watch?v=lsFGzCvM4dY  .

**Comment by mikemike998** [comment]
But there should be a feature added in cydia or in unc0ver for people who don't have laptops or computers when they unjailbreak cydia will be deleted !

**Comment by CoolPersonMaam** [comment]
60 days in you’re clearly trolling lmao 

What I mean is to delete Cydia.app with filza then running Restore RootFS and then Cydia should gone with the jailbreak

**Comment by mikemike998** [comment]
> 60 days in you’re clearly trolling lmao
> 
> What I mean is to delete Cydia.app with filza then running Restore RootFS and then Cydia should gone with the jailbreak

No I am not if you have read my comment !

**Comment by snowball7241** [comment]
Cydia.app IS removed, but the icon is still in the cache.

**Comment by mikemike998** [comment]
> Cydia.app IS removed, but the icon is still in the cache.

To fix the issue's watch this video to remove the icon from your device I have fixed it by watching this video https://www.youtube.com/watch?v=lsFGzCvM4dY .

**Comment by Assfugil** [comment]
This is a bug,not enchantment.

**Comment by baobaoit** [comment]
You could enable Refesh Icon Cache.

**Comment by Samgisaninja** [comment]
This was implemented in 3.1
