### ISSUE TITLE
iPhone 6 IOS 12.1.1 (16C50) cydia not available after jailbreak 

### ISSUE THREAD

**Issue by forsoftware0044** [pwn20wndstuff/Undecimus#632]

**Comment by penbob3** [comment]
Unfortunately this isn’t a bug, Cydia isn’t installed on A7/A8 devices due to a problem with Substrate, so for now Unc0ver on iPhone 6 and below is just for setting boot nonce and stopping auto updates.

**Comment by Cwoodyard** [comment]
Thank you penbob3, was getting upset that it wasn’t installing last night but then realized the 6 just got support 🤦‍♂️
