### ISSUE TITLE
Cydia fails to extract after using rec0ver.

### ISSUE THREAD

**Issue by nn9dev** [pwn20wndstuff/Undecimus#637]
**Describe the bug**
Cydia fails to extract after using rec0ver.

**To Reproduce**
use rec0ver. without re-installing, re-activate jailbreak. on the second reboot (when installing dependencies and such for Cydia) simply wait and it hangs on installing Cydia. if you scroll up, dependencies for dpkg say they are not being installed and things like tar, lzma, and xz are not installed.

**Screenshots**
the log will not export :/

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone8,4 (SE, board config n69uap)
 - unc0ver Version: 3.0.0~b36+1.g6282389

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Logs will not Export.

EDIT: on latest version of u0, it hangs at 27/38, so actually it doesn't even get there.

**Comment by nn9dev** [comment]
i've seen that if you clear all files that contain "com.saurik.Cydia" using FilzaEscaped12 that it fixes this...? i don't understand this, but it fixes it for me. i also re-installed so i can narrow it down to either of those

**Comment by Cryptiiiic** [comment]
@nn9dev Turn on reset cydia cache and reinstall cydia switch in unc0ver settings before jailbreaking. Also, can't really do much without logs, please use b38.

**Comment by CoolPersonMaam** [comment]
Maybe using reinstall cydia or using deelectra I think this is related to a DPGK error
