### ISSUE TITLE
Bunde ID: com.Saurik.Cydia - Crash log

### ISSUE THREAD

**Issue by Oxycodon-IV** [pwn20wndstuff/Undecimus#639]
**Describe the bug**
- Simply a collection a crash logs that pileup in the background 

**To Reproduce**

- No real way to reproduce = simply something related to "NSinvalidArgumentExeption" 

**Screenshots** log below

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X & iPad Air 2
 - unc0ver Version: v3.0b38

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

ON: iPhone X 12.1.1 - unc0ver-b38
Date: 2019-03-01 15:11:47 +0000
Bundle ID: com.saurik.Cydia
Exception type: NSInvalidArugmentException
Reason: -[NSNull intValue]: unrecognized selector sent to instance 0x1bfae19d0
Parent symbol: CoreFoundation - 0x000000018f38048c_CF_forwarding_prep_0 + 92

ON: iPad Air 2- 12.1.1 - unc0ver-b38
Date: 2019-03-01 15:16:42 +0000
Bundle ID: com.saurik.Cydia
Exception type: NSInvalidArugmentException
Reason: -[UIWebBrowserView stringByEvaluatingJavaScriptFromString:forceUserGesture:]: unrecognized selector sent to instance 0x101b2e200
Parent symbol: CoreFoundation - 0x00000001ce9a27dc <redacted> + 1412

**Comment by Cryptiiiic** [comment]
@Oxycodon-IV Please post unc0ver diagnostics(Export from unc0ver settings).

**Comment by 13XxM1CHA3lxX37** [comment]
I also got some logs (hope they are related) for Cydia.
After refreshing sources it happens irregularly that my device freezes and resprings. 
[Cydia.zip](https://github.com/pwn20wndstuff/Undecimus/files/2921201/Cydia.zip)

**Comment by Cryptiiiic** [comment]
@Oxycodon-IV You have lots of piracy which is probably the problem. CyDown is the most likely to cause the crash. I'm going to close this because it doesn't seem related to unc0ver but it will still allow conversation.
