### ISSUE TITLE
Jail broken but no tweaks

### ISSUE THREAD

**Issue by zackery1215** [pwn20wndstuff/Undecimus#64]
Tried installing barrel as an example on RC9 and there’s no tweaks showing up in settings. Any solutions?

**Comment by zackery1215** [comment]
Actually I don’t think it’s allowing me to respring. That’s what it is

**Comment by DropZite** [comment]
I can respring after installing from Cydia but stll its not showing up in settings for me. Same issue I have on RC9 and V1.

**Comment by zackery1215** [comment]
RC10? 😂

**Comment by zackery1215** [comment]
Does anyone got any ideas?

**Comment by Cryptiiiic** [comment]
make sure you have PreferenceLoader, substitute, and mobilesubstrate dummy package. @DropZite @zackery1215

**Comment by zackery1215** [comment]
Dummy package? I tried reinstalling these names exactly

- Substitute
- Substrate compatibility later
- preference loader

**Comment by zackery1215** [comment]
Nothing happened

**Comment by Cryptiiiic** [comment]
@zackery1215 uh Substrate Compatibility Layer is part of electra, why do you have electra repos and are installing electra packages.

**Comment by zackery1215** [comment]
I used Cydia update helper because there was an update, should I delete it or what is the best way to go about it

**Comment by Cryptiiiic** [comment]
@zackery1215 I'm closing this because you aren't listenting, all that stuff is from electra, you need to probably wipe rootfs then make sure electra repos are gone and make sure you have the default unc0ver apt repo.
