### ISSUE TITLE
Cellular dropping on 12.1 since b36-b38

### ISSUE THREAD

**Issue by wbraffman** [pwn20wndstuff/Undecimus#640]
Cellular data randomly disconnects while in jb state never in non jb state

no known way to reproduce, it is random

I will upload a screenshot when it happens next

**Device (please complete the following information):**
 -iOS 12.1
 -iphone 8
 - unc0ver Version: b~38

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

no logs

Before you close this like the other ones and say it is not related to unc0ver, just think. It doesnt happen in normal mode
it did not start until jb
not tweak related(to my knowledge)
Please just give it some thought, please.

**Comment by Cryptiiiic** [comment]
@wbraffman Please post unc0ver diagnostics. That way I can see if its unc0ver related.

**Comment by wbraffman** [comment]
Of course, where do I find the diagnostic?

**Comment by Cryptiiiic** [comment]
@wbraffman unc0ver settings, scroll down, share diagnostics.

**Comment by wbraffman** [comment]
[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2920793/diagnostics.plist.zip)


here sorry to make u wait, do u need a screenshot as well?

**Comment by Khris09** [comment]
Same issue iPhone X 12.1.1

**Comment by Khris09** [comment]
https://mega.nz/#!04tl2ISa!olF2JePsw7nbIki0aWMq_UJ7c0F8QZcvi1gBqO9tVgM

**Comment by mikigal** [comment]
I have the same problem, iPhone X, iOS 12.1.1 Beta 3, unc0ver b38

**Comment by silentshotghost** [comment]
Same issue iPhone X iOS 12.1.1 
unc0ver 3.0.0~b38

**Comment by josearg** [comment]
Same issue here in b36 and b38

**Comment by wbraffman** [comment]
12.1.1 is buggy as it is, but it happening on 12.1 is odd, we will see, it hasnt happend much recently
for me

**Comment by Cryptiiiic** [comment]
12.1 is buggy because you have pirated tweaks that break your device. Remove packages from pirate repos then remove the pirate repos. See if that fixes the problem.

**Comment by mikigal** [comment]
I have only legit repos, I bought every paid tweak, nothing pirated. I have problem with cellular dropping

**Comment by Cryptiiiic** [comment]
Post diagnostics. @wbraffman @mikigal

**Comment by mikigal** [comment]
I haven't this issue since last reboot (today morning).
Here's my diagnostics from unc0ver: https://loveani.me/diagnostics.plist

**Comment by silentshotghost** [comment]
Haven’t had this issue yet using unc0ver b39 it seems to be patched

**Comment by wbraffman** [comment]
Same
