### ISSUE TITLE
Freezing, Reboot,  Resprings after update of ldid/u0 ressources freezed and b38 was installed

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [pwn20wndstuff/Undecimus#642]
I tried to update the mandatory packages i.e. ldid, unc0ver jb resources etc, but the installation froze and my phone rebooted.

Then I installed b38 over b34 and there the real problems began. 
First "failed to extract bootstrap" for 5 times.
I checked reinstall Cydia, delete Cydia cache, got the same error again, but was able to open Cydia. So I updated the mandatory tweaks again and got into jb mode after respring.

Then my phone started lagging after opening some apps - to completely freeze afterwards, trying to respring after some time, but failing and rebooting.
Then in nojb mode the jailbreak worked on first try. But the freezing persists. Can't even use my phone for more than 5 minutes without freezing and rebooting

edit: downgraded to b36 and seems to run fine now. Some users on reddit reported the same issue.
edit2: nope. Still the same, but it runs for a longer time

iPhone 8 12.1.1 b38
edit: crashlogs+unc0ver Diagnostics Data (b36): [CrashReporter.zip](https://github.com/pwn20wndstuff/Undecimus/files/2921156/CrashReporter.zip) (count: 55+1)
most prominent: stacks+backboardd and panic-full

Some users on reddit reported the same issue.
https://www.reddit.com/r/jailbreak/comments/aw6m5a/question_random_crashes_on_b38/
https://www.reddit.com/r/jailbreak/comments/aw8x3z/help_springboard_keeps_restarting/
https://www.reddit.com/r/jailbreak/comments/aw8rhd/help_last_update_on_cydia_freeze_my_device_after/
https://www.reddit.com/r/jailbreak/comments/aw9u58/help_having_issues_reinstalling_jailbreak/

**Comment by Cryptiiiic** [comment]
@13XxM1CHA3lxX37 please post logs and screenshots stated in the guidelines: #627 .

**Comment by 13XxM1CHA3lxX37** [comment]
Downgraded to b36, but still the same issue. I'm trying to get the crashlogs, but kinda difficult if the device keeps rebooting after a short time

**Comment by Cryptiiiic** [comment]
@13XxM1CHA3lxX37 read the guidelines, it doesn't just ask for crash logs.

**Comment by 13XxM1CHA3lxX37** [comment]
This are all crashlogs generated today + diagnostics data from unc0ver. Some may be redundant, but I can't differentiate. 

[CrashReporter.zip](https://github.com/pwn20wndstuff/Undecimus/files/2921144/CrashReporter.zip)

**Comment by 13XxM1CHA3lxX37** [comment]
#669 
#658

**Comment by 13XxM1CHA3lxX37** [comment]
culprit found: cr4shed. 
The freezing occured with a libbulletin update that was updated along with ldid and u0 ressources.
