### ISSUE TITLE
Error when I'm trying to upgrade Debian Packager

### ISSUE THREAD

**Issue by LaxusiC** [pwn20wndstuff/Undecimus#645]
iPad Pro 2017 running iOS 11.2.6, never install anything totally fresh device. I jailbroke with unc0ver today and went to Cydia to upgrade stuff. Getting this error when I'm trying to upgrade Debian Packager

unc0ver version 2.2.6

https://prnt.sc/ms58yi

**Comment by TempAccountNull** [comment]
Try to restore the SnapshotFS, I had to when I had this issue on my iPhone 7.

**Comment by LaxusiC** [comment]
> Try to restore the SnapshotFS, I had to when I had this issue on my iPhone 7.

Tried, doesn't work. You can fix this by upgrading to latest version of unc0ver which is 300b38 right now. But I don't want to cause some hacking tools doesn't work on that version for example lldb native by Proteas

**Comment by Cryptiiiic** [comment]
@LaxusiC Reset cydia cache, also post /tmp/cydia.log.
