### ISSUE TITLE
AdGuard doesn’t work with Safari when in jailbroken state

### ISSUE THREAD

**Issue by BaselT95** [pwn20wndstuff/Undecimus#647]
When using AdGuard Pro in jailbroken state, I keep getting all kinds of errors trying to update or add/remove filters. It works just fine when in stock OS. 

“Reload System Daemons” is on, and RocketBootStrap is not installed. 

https://i.imgur.com/5Kyme57.png

⚪️ I have a useful screenshot that shows the full log(After pressing the view log button) and will post it.
⚪️ I have exported my Diagnostics file immediately after jailbreak failed or succeeded and will post it.
🔘 I have checked other issues to make sure its not a duplicate issue.
🔘 I am using the latest unc0ver beta.
🔘 I have checked to see if my device and iOS version are supported.
 🔘I can accurately describe the issue in the description and maintain a descriptive but short title.
🔘 I will not have more than one issue actively open at once.
🔘 I will not be entitled, spam, or use ??? or !!!.

**Comment by BaselT95** [comment]
Ok so I restored RootFS and installed no tweaks at all, but The issue is still persistent unfortunately.

**Comment by BaselT95** [comment]
Issue still persistent after b39

**Comment by Samgisaninja** [comment]
This is not a code-level issue with unc0ver, and there’s nothing we can do about this. please wait for the tweak to be updated.

**Comment by BaselT95** [comment]
@samgisaninja it’s not a tweak, it’s an app from the AppStore. This issue only occurs when I’m in the Jailbreak state for some reason

**Comment by AppleNati0n** [comment]
> @Samgisaninja it’s not a tweak, it’s an app from the AppStore. This issue only occurs when I’m in the Jailbreak state for some reason

you have to install jailbreak detection bypass tweak , its not issue from #Uncover Error :D

**Comment by BaselT95** [comment]
@AppleNati0n hmm I’ve tried liberty lite but that didn’t work. Any idea?

**Comment by AppleNati0n** [comment]
> @AppleNati0n hmm I’ve tried liberty lite but that didn’t work. Any idea?

same here because @umanghere his tweak is not updated , wait and watch :D :P
