### ISSUE TITLE
cydia not showing up after jailbreak iphone 6

### ISSUE THREAD

**Issue by BjrdTouz** [pwn20wndstuff/Undecimus#648]
iPhone 6 IOS 12.1.1 (a1586) cydia not showing up after jailbreak

**Comment by ConfirmedPlayer** [comment]
Because iPhone 6 not supported yet.

**Comment by coenkcore** [comment]
It's not bug or issue dude. 

https://github.com/pwn20wndstuff/Undecimus/issues/660#issuecomment-468975885

**Comment by coenkcore** [comment]
@cryptiiiic please cloe this issue
