### ISSUE TITLE
Random Wifi & Cellular Disconnects 3.0.0~b38

### ISSUE THREAD

**Issue by silentshotghost** [pwn20wndstuff/Undecimus#650]
**Describe the bug**
Random Wifi & Cellular disconnects using unc0ver.
Where the bars of signal are they just disappear and drop to flat (0)
and when you are on a facetime call or using wifi/cellular service it makes the call reconnect 
the bug is being consistent to the point it's annoying

**Screenshots**
No screenshots 

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: 3.0.0~b38

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

This is the same bug persistent in https://github.com/pwn20wndstuff/Undecimus/issues/640

**Comment by josearg** [comment]
Happening to me also but only for WiFi connection. Without jailbreak all works fine

**Comment by BaselT95** [comment]
It could be due to RocketBootStrap. Try uninstalling it and tweaks depending on it and see what happens
