### ISSUE TITLE
Error Update Cydia

### ISSUE THREAD

**Issue by Funn1** [pwn20wndstuff/Undecimus#651]
**Describe the bug**
When updating unc0ver Jailbreak Resources gives an error

Could not configure 'dpkg:iphoneos-arm'
Could not perform immediate configuration on 'dpkg:iphoneos-arm'
Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
Could not configure 'dpkg:iphoneos-arm'

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 11.1.2
 - iOS Device: iPhone 6S +
 - unc0ver Version:  2.2.6

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by sbingner** [comment]
This isn't an unc0ver issue but rather elucubratus by the look of it, if anything.  Can you email me via the maintainer link in cydia on dpkg?  Maybe I can look at it with teamviewer if you have a computer nearby that I can use to connect.  This all works fine on my test devices, it seems like it would be a strange depends confusion or something.

**Comment by Funn1** [comment]
Guys, but the latest version 3.0.0 beta, no problems, everything works

воскресенье, 3 марта 2019 г. пользователь Sam Bingner <
notifications@github.com> написал:
