### ISSUE TITLE
Something happened, now I can’t open cydia and my tweaks all are gone

### ISSUE THREAD

**Issue by Pobs313** [pwn20wndstuff/Undecimus#652]
My phone turned off and went back on and said I was in safe mode but no notification popped up so I could cancel it I tried everything. Now I can’t open cydia( tap to open and it wants to but then it closes) and all my tweaks are gone

**Comment by chrisderwahre** [comment]
If your phone reboots you have to enable the jailbreak again, in the unc0ver app.

**Comment by coenkcore** [comment]
You must open unc0ver and press jailbreak button
After device restart or turn off you must rejailbreak again your device
