### ISSUE TITLE
A7 jb success and no cydia

### ISSUE THREAD

**Issue by lin-xiong** [pwn20wndstuff/Undecimus#654]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iphone 5s
 - unc0ver Version: b38

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ireallydontwantthisaccount** [comment]
It's not supposed to include Cydia.

**Comment by lin-xiong** [comment]
really？？
so, i can't us any plug-in ？
