### ISSUE TITLE
Fails with error 0, says dpkg was interrupted

### ISSUE THREAD

**Issue by ireallydontwantthisaccount** [pwn20wndstuff/Undecimus#655]
**Describe the bug**
After force restarting while installing a package in Cydia, unc0ver fails to jailbreak because dpkg was interrupted. There should be some safety feature that can run `dpkg --configure -a` to correct this problem inside unc0ver. I've tried disabling tweaks, installing OpenSSH (the jailbreak fails before it's loaded), and reinstalling Cydia. I don't want to use rec0ver because I have a lot of tweaks and it would be so annoying to lose them all.

**To Reproduce**
1. Install a package that takes a while to install in Cydia
2. Force restart the device
3. Try jailbreaking again using unc0ver
4. It should fail to jailbreak

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPad mini 4 (iPad 5,1)
 - unc0ver Version: 3.0.0~b38

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled (except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Fails with error 0 (failed to extract bootstrap) and the logs say that dpkg was interrupted and to run `dpkg --configure -a` to correct the problem.

**Comment by pwn20wndstuff** [comment]
Already fixed in the develop branch. - Need to release a new version but it is fixed so I will close the issue.

**Comment by ireallydontwantthisaccount** [comment]
Thanks, does it automatically fix this or is there something special I'll need to do?

**Comment by pwn20wndstuff** [comment]
It does it.

**Comment by ireallydontwantthisaccount** [comment]
Awesome, one more question: If I use the version from the develop branch then switch back to the one from the latest IPA, will that cause any issues?

**Comment by pwn20wndstuff** [comment]
No.

**Comment by ireallydontwantthisaccount** [comment]
Sorry to keep bothering you but could you send me an IPA for the develop branch? When I try to build it myself, it says my development team doesn't support the multipath capability which I assume comes with the $100 developer program.

**Comment by ireallydontwantthisaccount** [comment]
@pwn20wndstuff Actually, looks like that's for iOS 11 because it said Unsupported instead of Jailbreak when it finally worked. Would you be able to add this to the next beta release of Unc0ver?

**Comment by Lordie12** [comment]
This is still happening on unc0ver 3.5.2, iPhone X, iOS 12.4

[*] runCommandv(290): E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 

Is this fix in some other newer version?
