### ISSUE TITLE
b38 does not show anything for me, just a white background

### ISSUE THREAD

**Issue by lamcoo3** [pwn20wndstuff/Undecimus#656]
**Describe the bug**
I installed IPA b38 then opened and just got the white background

**Device (please complete the following information):**
 - iOS Version: 12
 - iOS Device: iPhone 6s+
 - unc0ver Version: b38

**Comment by Cryptiiiic** [comment]
Try rebooting. Also, where did you install it from.

**Comment by lamcoo3** [comment]
@Cryptiiiic I installed b39 already and got error fatal line 1223, like a bug posted above
