### ISSUE TITLE
Device randomly freezing on b38

### ISSUE THREAD

**Issue by samtaborsky** [pwn20wndstuff/Undecimus#658]
**Describe the bug**
My device freezes randomly after b38 update and then either restarts itself or requires me to hard reset it.

**To Reproduce**
It is random, while using apps, once it appeared when I was on home screen.

**Screenshots**
I have none, just frozen phone.

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone SE
 - unc0ver Version: v3.0.0~b38

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
This is log from just after the freezing and reboot.
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2922409/diagnostics.zip)

**Comment by pwn20wndstuff** [comment]
Do you have RocketBootstrap or AFC2?

**Comment by samtaborsky** [comment]
Yeah, I have RocketBootstrap.

**Comment by TempAccountNull** [comment]
Make sure you remove it. For the longest time on 10.3.3 before Ryan updated to 1.06, if you had 1.06 installed, it wasn't compatible with 10.3.3 (for the iPhone 5c) it always errored or froze the device. I always had to downgrade to 1.05 in order to prevent that.

Case in point: 1.06 is currently incompatible with iOS 12.

**Comment by samtaborsky** [comment]
I will not remove it yet, because I found out that once I removed Notifica tweak it did not freeze again, though I do not know why it had frozen before with all tweaks disabled. So I will keep watching it and as soon as it freezes again RockecBootstrap is going to trash.
