### ISSUE TITLE
Safe Mode After Re-enabling JB

### ISSUE THREAD

**Issue by zackery1215** [pwn20wndstuff/Undecimus#659]
I jailbroke my phone using a third part app and installed uncover from there and it was revoked, prior to this everything was working properly tweaks and all.

Now I rejailbreak and it takes me into safe mode every time.

I tried:
1. Restore Root FS
2. Refresh Icon Cache 

Both were successful because it prompted so but yet it still does that,

It just takes me to safe mode every time it says successful,

What would you recommend I do.

**Comment by zackery1215** [comment]
The weird thing is even now it says “rejailbreak” but I can open Cydia.

**Comment by TempAccountNull** [comment]
it may say that you're not jailbroken, but you are technically jailbroken if cydia is opening.

**Comment by zackery1215** [comment]
It just goes into safe mode every time now. That’s what I mean, that’s the problem here.

**Comment by coupedeebaybee** [comment]
🤦🏻‍♂️Start uninstalling tweaks you have installed until it resprings without going into safe mode. You should really find a better place to ask questions, especially when they have nothing to do with this code

**Comment by zackery1215** [comment]
How can I delete the tweaks when they’re not showing up anymore. Is there something I can do to just remove the JB

**Comment by Cryptiiiic** [comment]
@zackery1215 post you information. Device, version, unc0ver version, also diagnostics.

**Comment by coenkcore** [comment]
Try to re-jailbreak with load tweak off 
And see device going to safemode or not.
If not going to safemode you must uninstall incompatible tweak.
Device going to safemode because you have incompatible or partially support of tweak installed.
