### ISSUE TITLE
Cydia does not show up after many trials, iPhone 5S

### ISSUE THREAD

**Issue by hans685** [pwn20wndstuff/Undecimus#660]
**Describe the bug**
Unc0ver was side loaded and launched many times. 
'Jailbreak completed' screen was obtained. 
After that no Cydia.
![img_0001](https://user-images.githubusercontent.com/48166533/53689156-8388c480-3d4f-11e9-8409-6ff8532afe74.PNG)

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1 beta 3
 - iOS Device: iPhone 5S
 - unc0ver Version: 3.0.0 beta 38

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by coenkcore** [comment]
Hey dude you must read notes on latest release.
It's not bug or issue on A7-A8 devices, for now jailbreak for A7-A8 devices is partial jailbreak with no cydia installed. Once again please read all notes on every release before installing and create issue

**Comment by coenkcore** [comment]
@cryptiiiic please close this issue

**Comment by coenkcore** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/616#issuecomment-468268878

https://github.com/pwn20wndstuff/Undecimus/issues/603#issuecomment-468269863
