### ISSUE TITLE
iPhone 6s and can not upgrade to unc0ver 3.0.0 b38

### ISSUE THREAD

**Issue by bundyal** [pwn20wndstuff/Undecimus#661]
I have an iPhone 6s and can not upgrade to unc0ver 3.0.0 b38.
I install unc0ver 3.0.0 b38 with Appdb, and then I see wait,
and if I click on it, there is no download, and click again.
Then he updates to version unc0ver 3.0.0 b38, but app installed but greyed out and can not be opened.
If I reboot my iPhone, and click on unc0ver Jailbreak I see installing unc0ver and then have unc0ver 3.0.0 b37 on my iPhone again.
So I can not install unc0ver 3.0.0 b38.
I have also try to install unc0ver 3.0.0 b38 from /var/mobile/Documents/AppcakeIPAs/Downloaded, then I will fail.

**Comment by coupedeebaybee** [comment]
I use tweakbox until I get Cydia, then remove tweakbox, profile, & unc0ver app & use ReProvision to install a copy of the ipa I get directly from here.
If tweakbox doesn’t work, then go back to the beta you were on, use restore rootFS, then install newest beta & rejailbreak.

**Comment by howmanymeninthenorth** [comment]
Coupedeebaybee how do you use tweakbox? Is it like Cydia?

**Comment by CoolPersonMaam** [comment]
@howmanymeninthenorth tweakbox is a signing service

**Comment by bundyal** [comment]
user_hidden say to me install unc0ver with Impactor.
It now works perfectly.
I have an iPhone 6s iOS12.1.2

Here is the explanation
Start impactor_0.9.51 (not as administrator.)
Undecimus-v3.0.0-b39.ipa drag on Impactor, then he asks for your appleid
Then you will create another appleid at,
https://appleid.apple.com/account#!&page=create
no fake email address because you have to verify with a code.
Then fill this in Impactor, and then he installs unc0ver,
then click on install Cydia Extender in Impactor.
if you succeed, click on unc0ver on your phone.
Then you get an error message about management,
then you go to Settings, General, Device Manager on your iPhone,
App From Developer, and click on trust.
