### ISSUE TITLE
Jailbreaked device b38 but no cydia 

### ISSUE THREAD

**Issue by NiMalachena** [pwn20wndstuff/Undecimus#662]
Installed Uncover B38 (Impactor) on Iphone 6, jailbreak done but when I look for cydia, theres no cydia.

 - iOS Version: 12.1.2
 - iOS Device:Iphone 6 
 - unc0ver Version: b38

 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by CoolPersonMaam** [comment]
install ssh or use newterm 2 what ever you perfer and run uicache see if that fixes your problems or you can rejailbreak with refresh icome cache

**Comment by xMilesManx** [comment]
Cydia is not included in this version of unc0ver. We are waiting for a Cydia substrate update before it will be released. Please close this, as this is intentional behavior

**Comment by DJCHICKEN4** [comment]
@NiMalachena Already answered #654 #660 #648 #616 #603

**Comment by Mas9311** [comment]
4K devices do not have Cydia just yet. 4K includes A7(iPhone 5S like me) and A8(iPhone 6) and are not _complete jailbreaks_ yet.

Also, you should update to b39 in order to add the "[x ] this issue is present on the latest version of unc0ver" to your issue/bug.
