### ISSUE TITLE
Any tweak with com.apple.Security in the bundle filter will cause respring loop on ldrestart

### ISSUE THREAD

**Issue by Muirey03** [pwn20wndstuff/Undecimus#663]
**Describe the bug**
If a tweak is installed with `com.apple.Security` in the bundle filter, the device will enter a respring loop that can only be escaped by rebooting upon calling ldrestart.

**To Reproduce**
1. Create a tweak with a completely empty Tweak.xm but with `{ Filter = { Bundles = ( "com.apple.Security" ); }; }` as the bundle filter. (Here is one that you can use for testing: https://github.com/Muirey03/CrashTest)
2. Install the tweak on a device running unc0ver on iOS 12.
3. Run the command `killall -9 backboardd; rm -rf /var/root/Library/Caches/com.apple.coresymbolicationd; ldrestart` via SSH
4. Watch as the device enters a respring loop that can only be escaped by rebooting.

**Screenshots**
N/A

**Device (please complete the following information):**
 - iOS Version: 12.1.1 beta 3
 - iOS Device: iPhone 8
 - unc0ver Version: 3.0.0~b38

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
N/A

**Comment by pwn20wndstuff** [comment]
So I believe this may be happening because Substrate attempts to use securityd to sign object files on fly with the enterprise certificate that is provided by the jailbreak.

Pinging @saurik on this issue.

**Comment by Muirey03** [comment]
Here is the syslog: https://pastebin.com/4AHSwHuh

```
<Error>: MS:Error: unable to open()
```could be interesting
