### ISSUE TITLE
Random freezing on Unc0ver 3.0.0 b38

### ISSUE THREAD

**Issue by ConfirmedPlayer** [pwn20wndstuff/Undecimus#669]
**Describe the bug**
Device have random freezes after upgrading b36 to b38

**Device (please complete the following information):**
 - iOS Version: 12.1.1 b3
 - iOS Device: iPhone 6s Plus
 - unc0ver Version: 3.0.0 b38

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by ConfirmedPlayer** [comment]
Apparently, I'm not the only one who ran into this bug. https://github.com/pwn20wndstuff/Undecimus/issues/658#issue-416428100

**Comment by 13XxM1CHA3lxX37** [comment]
I got Crashlogs+u0 diagnostics from 2 devices: iPhone 8 12.1.1 and iPhone X 12.1.2
Got better after uninstalling AFC2, Cephei, libbulletin, libsparkAppList on my iPhone8. But before b38 there were rarely problems.
On the X some of my personal suspects are still installed. Will report later if there is a crash again.
[iPhone X.zip](https://github.com/pwn20wndstuff/Undecimus/files/2923595/iPhone.X.zip)
[iPhone8.zip](https://github.com/pwn20wndstuff/Undecimus/files/2923596/iPhone8.zip)

**Comment by Mas9311** [comment]
Can you update to b39? If this problem persists, then update the issue.
Please and thank you!

**Comment by ConfirmedPlayer** [comment]
I am so sorry, but I cannot test it on b39 because I deleted the Jailbreak and I unfortunately do not have time to jailbreak and test again.

**Comment by VanishingTacos** [comment]
I started to run into reboot issues last and and then woke up with my phone in a non jailbroken state.  I updated to the latest version of Unc0ver today. I will report here if it happens again.

**Comment by josearg** [comment]
Freezes are happening to me every day without any tweak installed. I did a restore FS also and it's still happening. My suspect is in Substrate. Happening in many versions like b36 or b43 as far as I remember. For now Im using my phone unjailbroken because it was really frustrating having freezes or apps that crash or don't open every day... I hope this can be fixed!

**Comment by RakDuhl** [comment]
iphone 8
ios 12.1.2
unc0ver b46
the same issue is on my phone and it doesnt matter which version of unc0ver i use. My phone always crashes at random times in random situations either to a resping or a full reboot. The causes are completely unknown, Crashreporter doesnt show any crashlogs and i dont know how to view them or something similar
