### ISSUE TITLE
Errno 2: Failed to copy over our resources to RootFS

### ISSUE THREAD

**Issue by AAgamesnl** [pwn20wndstuff/Undecimus#670]
**Describe the bug**
Following way 2 of this tip : [https://www.reddit.com/r/jailbreak/comments/awgqi4/tip_how_to_reload_system_daemons_and_reduce](https://www.reddit.com/r/jailbreak/comments/awgqi4/tip_how_to_reload_system_daemons_and_reduce/)

 gave me a Failed to copy over our resources to RootFS error on jailbreaking on Unc0ver.

**To Reproduce**

1- Download iCleaner pro
2- reboot and then open unc0ver and select disable load tweaks and also enable reload system deamons and then tap on jailbreak.
3- After it successfully jailbreaks go back to icleaner pro and disable substrate tweaks and run a cleanup.
4- open unc0ver and enable load tweaks then tap on re-jailbreak.
5- voilla... error

**Screenshots**
![img_7046](https://user-images.githubusercontent.com/19744374/53698980-c300f080-3de3-11e9-91f3-9ebd2f0fc22b.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.0.1
 - iOS Device: Iphone X 
 - unc0ver Version: 3.0.0b38

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
_assert(2:substrateDeb != nil)@jailbreakViewController.m:1475[Jailbreak]

**Comment by AAgamesnl** [comment]
update 1 - currently updating to 12.1.1b3

**Comment by AAgamesnl** [comment]
update 2 - Updating to ios 12.1.1b3 completed, trying to download newest version of unc0ver....

**Comment by AAgamesnl** [comment]
UPDATE 3 - 
### **§§Jailbreak Succeeded with Reload System daemons Enabled§§**

will not close this thread, i first want you guys to see this ;)
feel free to close this thread yourself :)

**Comment by Oxycodon-IV** [comment]
I have the same error!

**Comment by AAgamesnl** [comment]
Ow.. you’re too late to downgrade/upgrade to 12.1.1b3, I would suggest to futuerestore if you have blobs :).  Or wait for an proper answer from the team

**Comment by Oxycodon-IV** [comment]
yea im just thinking to future restore...just dont want too go through that entire hassle

I just dont know why this occurred

**Comment by AAgamesnl** [comment]
Can I also know what you did to get this error?
