### ISSUE TITLE
IPAD : Failed to Copy Over our resources to RootFS

### ISSUE THREAD

**Issue by Amoystyle** [pwn20wndstuff/Undecimus#677]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'Jailbreak'
3. See error

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.0
 - iOS Device:  IPAD
 - unc0ver Version: b39
![_20190304174132](https://user-images.githubusercontent.com/5343265/53724407-c5774f00-3ea4-11e9-8356-c9b01aba2051.jpg)

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment]
Post diagnostics.

**Comment by Amoystyle** [comment]
> Post diagnostics.

diagnostics

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2928937/diagnostics.zip)

**Comment by Amoystyle** [comment]
I found the error ([*] Unable to resolve lzma to a debs) at /Undecimus.app/apt/Packages :
```
Package: lzma
Version: 2:4.32.7-2
Architecture: iphoneos-arm
Maintainer: Sam Bingner <maintainer@sbdhi.com>
Installed-Size: 736
Conflicts: com.mc.xz
Filename:  ./lzma_2:4.32.7-2_iphoneos-arm.deb   <-- this path is error, replace:./lzma_2_4.32.7-2_iphoneos-arm.deb
Size: 71624
MD5sum: 1eff2a2bfed451132f417f757e2f5316
SHA1: 52a5b1cadd8992a3c522ff4e9485eb7b7e6264d9
SHA256: a67c3c0e5982c8ac46b24238e90ae6aa373775bfbcf1b6a4a43f65dc1fd12490
Section: Archiving
Priority: important
Homepage: http://tukaani.org/lzma/
Description: slower, but better, compression algorithm
Name: LZMA Utils
```
