### ISSUE TITLE
Failed to jailbreak

### ISSUE THREAD

**Issue by acegoal07** [pwn20wndstuff/Undecimus#681]
If I reboot or my phone dies when I go to use Unc0ver it gets stuck in a boot loop unless I turn off load tweaks and then when in JB state I then have to respiring to turn the tweaks on

**Comment by SarahH12099** [comment]
Turn off reload system daemons

**Comment by acegoal07** [comment]
That works as well but that puts me in no substrate mode and it’s not a issue with a tweak

**Comment by acegoal07** [comment]
That works as well but that puts me in no substrate mode and it’s not a issue with a tweak well i dont think its is.
@SarahH12099

**Comment by acegoal07** [comment]
it is not being caused by a bad tweak
