### ISSUE TITLE
OTA Update errno: 17 line: 1230

### ISSUE THREAD

**Issue by cheech1789** [pwn20wndstuff/Undecimus#683]
Have no OTA update downloaded and keep getting this error. Even restored my phone to make sure and keep getting the same error. 
https://imgur.com/gallery/SoTvrGU

**Comment by cheech1789** [comment]
Running iOS 12.0 btw

**Comment by sfernandez2013** [comment]
I am having the same issue I have tried just about everything I can think of, short of wiping the whole phone, let me know if you figure anything out
