### ISSUE TITLE
No offsets for iPhone 10, 6

### ISSUE THREAD

**Issue by Charley1225** [pwn20wndstuff/Undecimus#684]
**Describe the bug**
Whenever I try to jailbreak my phone, it always crashes at 2/38. Last message displayed on the log is always [-]no offsets for iPhone 10, 6 I tried turning on and off different features at the setting page but no luck.

When I first successfully jailbroke, I installed Filza and changed my shutter sound behaviour (to go silent on silent mode because my phone was bought in Korea and it stayed loud due to some regional thing). Then I think I rebooted my phone or something, and now I want to jailbreak again but I can't.

I cannot access Cydia or Filza, nor I can delete any of them.

**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'jailbreak'
3. See Exploting 2/38
4. The log window displays [-]no offsets for iPhone 10, 6

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone X
 - unc0ver Version: b39

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
[-]no offsets for iPhone 10, 6

**Comment by clarityzzz** [comment]
This should be an easy fix but can you please add diagnostics? Just want to be sure about one thing because it theoretically should be supported.

**Comment by Charley1225** [comment]
Diagnostic as in this?

[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2928308/diagnostics.txt)

**Comment by clarityzzz** [comment]
yes
https://github.com/pwn20wndstuff/Undecimus/blob/182a79fe005404bda93cb8146f4ee440dce6debf/Undecimus/source/parameters.c#L184
changing 10,1 to 10,* here should fix the issue, but this is an issue with comparing builds
If you have a Mac, compile latest develop with this change and tell me if it works.

**Comment by Charley1225** [comment]
Erm..

sorry for a basic question but how do I change the zip file into ipa file?

**Comment by clarityzzz** [comment]
@Charley1225 you need a Mac and Xcode to play around with Source Code. You can't just simply edit the binary.

**Comment by Charley1225** [comment]
Right... Well I don't have any of them :(

I did the fools way of downloading the source code file, finding the parameter.c and changing it to txt file then making the changes. But I guess I cannot do that?

**Comment by clarityzzz** [comment]
@Charley1225 message Clarity#5912 and I'll give you a test iPA.

**Comment by Charley1225** [comment]
@clarityzzz  seems like i cannot add you on discord

**Comment by clarityzzz** [comment]
@Charley1225 try now

**Comment by Charley1225** [comment]
@pwn20wndstuff this issue is still not dealt. Would it be possible for you to update this? sorry for the trouble :(
