### ISSUE TITLE
-canOpenURL: failed for URL: "Cydia://" - error: "This app is not allowed to query for scheme cydia"

### ISSUE THREAD

**Issue by MaistroX** [pwn20wndstuff/Undecimus#686]
I trying to jailbreak my Iphone 6 on a Clean installation of iOS 12.1.2, and all works fine but after 30 times still no Cydia, all I see Before I jailbreak is "-canOpenURL: failed for URL: "Cydia://" - error: "This app is not allowed to query for scheme cydia""

It does´nt help to run different switches on or off inkl. "Restore RootFS".
Can it be fixed? 

I use Undecimus-v3.0.0-b39

Regards MaistroX

**Comment by Cryptiiiic** [comment]
Wait for b40, it will support 4k devices.

**Comment by amirber** [comment]
i have same issue on b40

**Comment by ChenNotFoundException** [comment]
after restore from chimera ，same on my iPhone6S 12.0.  and the plugs installed before still work.that is strange
