### ISSUE TITLE
Problems restarting the device and redo Jailbreak

### ISSUE THREAD

**Issue by patrycklm** [pwn20wndstuff/Undecimus#689]
Every time it is necessary to restart the iphone and redo the jailbreak with unc0ver, the iphone hangs and stays in the symbol of respring, sometimes for a certain period it starts with the jailbreak, and most of the time it does not start, being necessary to restart the device with the volume + - and turn on and redo again, no matter the version of Unc0ver, this happens a long time, since the first version, the device always keeps the wheel spinning and does not start, apparently it is a problem when recharging the jailbreak or with the model? I am in version 12.1.1 b3, and Unc0ver b40, my iphone is an iphone X.

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x
![e3-2018-predictions-1](https://user-images.githubusercontent.com/44373454/53764453-16d70c80-3eac-11e9-9689-ac21d34fb4cf.jpg)
 ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by AppleNati0n** [comment]
just rejailbreak it,its not a issue or bug

**Comment by JoshThomasx20** [comment]
tried this on my IPhone SE doing exact same thing hanging in re spring mode for like 10 seconds then reboots my device completely wont even get past re spring

**Comment by patrycklm** [comment]
After reboot respring simbol keeps spining infinitely and have noting to do.

**Comment by jamzsjimmy** [comment]
Same problem with me also. on iphone 7+ and ipad mini 4. iOS 12.1.1 & used uncOver v3.0.0-b39 and v3.0.0-b40

**Comment by dallasgroot** [comment]
Same here. I am only able to disable reload system deamons.

**Comment by coenkcore** [comment]
Update to unc0ver 3.0.0~b43
If issue still exist turn off your device
Wait a second then turn on again then try with rootfs restore

- open unc0ver and wait a minute
- open unc0ver setting - turn on rootfs restore (rec0ver)
- press jailbreak button and wait until rpotfs restore completed and device going to restart
- after restart open unc0ver again and wait a minute
- press jailbreak button
- wait till procces to complete

**Comment by moks84** [comment]
Did you have any solution ? I'm having the same issue here
after restart, tried re-jailbreaking but spinning wheel wont stop. 

I tried the new unc0ver 3.0.0~b48 with the same result

**Comment by moks84** [comment]
> Did you have any solution ? I'm having the same issue here
> after restart, tried re-jailbreaking but spinning wheel wont stop.
> 
> I tried the new unc0ver 3.0.0~b48 with the same result

mine was resolved when rejailbreaking with unselecting "Reload Daemon" it then get into the safe mode.

I was then be able to open Cydia, and deleted suspected repos and packages. then back to the normal mode with jailbreak.
