### ISSUE TITLE
Respring loop when coming from newest Electra

### ISSUE THREAD

**Issue by qwertyuiop1379** [pwn20wndstuff/Undecimus#690]
**Respring loop when switching to unc0ver**
The phone will continuously respring until it reboots.

**To Reproduce**
1. Jailbreak with Electra
2. Install Anemone 3.0
3. Use Anemone 3.0, enable some themes, etc.
4. Jailbreak with unc0ver, preferences are kept
5. Install Anemone (not 3.0) with unc0ver
6. Phone will respring loop upon jailbreaking

**Device (please complete the following information):**
 - iOS Version: 11.3.1
 - iOS Device: iPhone7,2
 - unc0ver Version: 3.0.0~b28

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

The only fix I have found is just to delete Anemone's preference file and reinstall it.

**Comment by 13XxM1CHA3lxX37** [comment]
Does this also happen with "reload system daemons" disabled?
