### ISSUE TITLE
Removing the iOS Beta "Feedback" App.

### ISSUE THREAD

**Issue by pmo-19** [pwn20wndstuff/Undecimus#692]
**Describe the feature you'd like**
Removing the iOS Beta "Feedback" App.

**Describe alternatives you've considered**
This App. is part of the Beta iOS 12.1.1

**Additional context**
Cannot be removed by the User following standard procedures.

**Comment by pmo-19** [comment]
Is it possible in a further release to delete the iOS Beta installed "Feedback" App ?
This App. is part of the Beta iOS 12.1.1 and cannot be removed by the User following standard procedures.

**Comment by tehuno** [comment]
There is a tweak for this called No Feedback on bigboss repo.
