### ISSUE TITLE
Failed to extract bootstrap

### ISSUE THREAD

**Issue by brianvis** [pwn20wndstuff/Undecimus#694]
**Describe the bug**
![1218987b-9ce8-4ebf-b54a-260097909c4d](https://user-images.githubusercontent.com/30999137/53768568-89121600-3ed9-11e9-90a0-7837e72c6089.png)

Gets stuckhere everytimr

**To Reproduce**
Get ipad mini 2
Use b40

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: Ipad mini 2
 - unc0ver Version: b40

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cadbob** [comment]
This Worked for me, try and confirm please.

1    Open unc0ver and go to the settings page

2    Turn «Load Tweaks» off and then jailbreak as you usually would

3    Once Jail Broke and respring, go to Settings in Uncover turn on tweaks
    rejailbreak and cydia is loaded

**Comment by JmTexas19** [comment]
> 
> 
> This Worked for me, try and confirm please.
> 
> Airplane Mode "ON"
> 
> 1 Open unc0ver and go to the settings page
> 
> 2 Turn «Load Tweaks» off and then jailbreak as you usually would
> 
> 3 Once Jail Broke and respring, go to Settings in Uncover turn on tweaks
> rejailbreak and cydia is loaded

Same error as above, IPhone 6 12.1.1 b3

Unfortunately fix didn't work.

**Comment by bigmoof** [comment]
Duplicate issue [#530](https://github.com/pwn20wndstuff/Undecimus/issues/530)
