### ISSUE TITLE
Ipad Mini 2 Ios 12.1.1b3 UnCover b40

### ISSUE THREAD

**Issue by cadbob** [pwn20wndstuff/Undecimus#696]
To Jailbreak:

Ipad MINI 2 A7 IOS 12.1.1b3 I side loaded Uncover b40 I have Airplane mode on and disabled Passcode but the dang Ipad will not JB. It will just reboot back to IOS

This Worked

  1.   Open unc0ver and go to the settings page

   2.  Turn «Load Tweaks» off and then jailbreak as you usually would

    3.  Once Jail Broke and respring, go to Settings in Uncover turn on tweaks
         rejailbreak and cydia is loaded

**Comment by Giordi9** [comment]
Thanks, finally I jailbreaked my iPad :D
