### ISSUE TITLE
Rootfs already mounted 

### ISSUE THREAD

**Issue by w4nji** [pwn20wndstuff/Undecimus#697]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to 'just click on jailbreak'

**Screenshots**
![uncover](https://user-images.githubusercontent.com/48195334/53771848-1fb4f600-3f1f-11e9-996e-3c65a01f0ff4.jpg)

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone X
 - unc0ver Version: tried with b37,b38,b39,b40

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
Rootfs already mounted, already clear OTA update.
attached is the diagnostic from unc0ver
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2928711/diagnostics.zip)

**Comment by w4nji** [comment]
@sbingner @pwn20wndstuff hope you can help me on this issue

**Comment by Amoystyle** [comment]
settings -> General -> Reset ->Erase All Content and Settings. It will be OK

**Comment by grahamcracker1234** [comment]
Reinstalling the current OS worked for me.

**Comment by CoolPersonMaam** [comment]
Looked at the logs and it looks like your RootfS is 12.1.4 which is not what it’s suppose to be. Since you’re not jailbroken yet. You can safely do a reset alll content and settings and this will not boot loop your devix

**Comment by TheChatty** [comment]
See #707 for solution.

**Comment by Filipendo** [comment]
grahamcracker123 Do you have Restore.ipsw file ios 12.1.2?
i

**Comment by CoolPersonMaam** [comment]
The IPSW is no longer signed.... unless you’re upgrading with blobs
