### ISSUE TITLE
Failed to extract bootstrap

### ISSUE THREAD

**Issue by vitalik2187836** [pwn20wndstuff/Undecimus#699]
**Describe the bug**
Error appears every time i want to jailbreak.

**To Reproduce**
1. Click on 'Jailbreak' on the main page.
2. See error

**Screenshots**
![8ab603d2-4d94-4d9e-bb82-e4994fef85db](https://user-images.githubusercontent.com/42221931/53773970-a22cbe00-3efd-11e9-9aea-d494cac1cef0.jpeg)

**Device (please complete the following information):**
 - iOS 12.1.1b3: 
 - iPhone 6s: 
 - unc0ver b41: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

[diagnostics-4.zip](https://github.com/pwn20wndstuff/Undecimus/files/2928857/diagnostics-4.zip)

**Comment by JmTexas19** [comment]
Your error is slightly different, but it might be worth trying the solution I posted in #694

**Comment by vitalik2187836** [comment]
Nope. Exactly the same error.

**Comment by vitalik2187836** [comment]
@Cryptiiiic Guys, please, look at this issue. I've had some problems with substrate on iOS 11 because of broken volume up button but Sam fixed it somehow. He said Saurik should fix it in substrate. So can it be the same issue again? I've tried to do everything that guys with slightly different error suggest to do but still got nothing. 
Help me, please.

**Comment by maddyo01** [comment]
Why the develoments doesnt have any solution to this problem?!?!
Please help! I have the same error!

**Comment by vitalik2187836** [comment]
The best thing you can do for now is make a screenshot and add your diagnostics file.

**Comment by maddyo01** [comment]
[
![img_5185](https://user-images.githubusercontent.com/48225702/53847778-5b37da80-3f88-11e9-8eff-f316245ad8b0.PNG)
](url)

**Comment by maddyo01** [comment]
[
[diagnostics (1).zip](https://github.com/pwn20wndstuff/Undecimus/files/2933878/diagnostics.1.zip)
](url)

**Comment by sbingner** [comment]
If you have a broken volume button you can install and run this IPA _ONE TIME_ - don't keep running it because every time it runs it will reinstall substrate.  Until substrate is updated again you should be ok if that is the issue.

https://www.bingner.com/Undecimus-forcesubstrate.ipa

**Comment by vitalik2187836** [comment]
> If you have a broken volume button you can install and run this IPA _ONE TIME_ - don't keep running it because every time it runs it will reinstall substrate. Until substrate is updated again you should be ok if that is the issue.
> 
> https://www.bingner.com/Undecimus-forcesubstrate.ipa

Suddenly it didn't help. I always see some error about system-cmds_790.30.1-2. 
I tried to make rootfs a couple of times, tried to jailbreak with different options turned on and off and still nothing.
If you can take a look at that error, here is the log file
[diagnostics-5.zip](https://github.com/pwn20wndstuff/Undecimus/files/2948263/diagnostics-5.zip)
Thank you a lot, you are great guys :)

**Comment by maddyo01** [comment]
Yeah I do have  a broken volume button, and the cams also. I had hope this might work but  no still showing the same error after it goes on 27/38 :(

**Comment by maddyo01** [comment]
@vitalik2187836 can you ask them about other solutions?

**Comment by maddyo01** [comment]
@sbingner any other idea?

**Comment by vitalik2187836** [comment]
I'm not sure if sbingner reading

**Comment by vitalik2187836** [comment]
I don't think sbingner or any other devs looking on issues on github. I have asked him in Twitter to look at this and help if he can. Actually I don't to disturb him a lot too.

**Comment by maddyo01** [comment]
:( not jb for us then

**Comment by vitalik2187836** [comment]
Let's wait a bit, maybe he will answer.

**Comment by maddyo01** [comment]
Do you have a broken volume too?  Or had rootlessjb installed before using uncover? I did and i think it has something to do with some missing files i have deleted trying to erase roots with filza, because in my diagnostic logs says something about install Fwdebs.

**Comment by vitalik2187836** [comment]
I suggest you not to delete anything with filza because everything you wool achieve is fucked up system. 
And yes I have broken volume up button.

**Comment by sbingner** [comment]
Please download again from the same URL and try again.  I removed the wrong version of substrate when I packaged that.  Essentially, I patched substrate to ignore the dead mode combination, packaged it up, copied it into my source... then deleted it and made that ipa.  *facepalm*

Again, make sure you delete this version after it works and go back to the normal version because it keeps re-extracting substrate.

**Comment by vitalik2187836** [comment]
Wow, that works! Man, you, pwn and saurik are the best guys on the jailbreak scene. Thank you a lot i really appreciate your help :)

**Comment by maddyo01** [comment]
Yay!! it finally works! thank you so much =)

**Comment by vitalik2187836** [comment]
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2948967/diagnostics.zip)
That's what happens if I try to rejailbreak with "official" b43. However even after this error all my tweaks work fine. I have installed your fixed version, rebooted and ran jailbreak again. With fixed version everything worked fine.

**Comment by maddyo01** [comment]
@vitalik2187836  could you jb with the Official uncover version? my phone went off and i lost my jb and i am trying to reinstall this uncover version with cydia impactor but i cant install it, seems like apple is unsigning this . anywhay of how to install it back?? @sbingner

**Comment by maddyo01** [comment]
@sbingner  
Hii! I am trying to jailbreak with the new uncover tool in the same device with the broken volume up and i keep getting this error ' failed to download firmware debs '' do I need an special version like the one you gave us to make the previous jailbreak? Or any other soluions please!! 
Ios 12.2 iphone 6s plus
