### ISSUE TITLE
iOS 12.1.4 update queued while tvOS profile is installed...

### ISSUE THREAD

**Issue by JSeredick** [pwn20wndstuff/Undecimus#700]
**Describe the bug**
Was just roaming on my phone got a popup stating that the ios 12.1.4 update had been queued. After I checked the settings and the iOS 12.1.4 update had started "requesting" can't cancel or delete any updates in the storage. Tried everything I could and can't get out of this "requesting" stage. No estimated time remaining is shown either, seen in the screen shot.

**To Reproduce**
1. Jailbroken with beta 38 uncover, haven't updated since I don't want to lose tweaks
2. tvOS profile still installed
3. Update has been "requesting" for about 10 minutes (can't cancel or delete in storage)
**Screenshots**
https://twitter.com/comicallybad/status/1102746488122339329
**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone 10,6
 - unc0ver Version: beta 38

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Xtorsion** [comment]
same happened to me... we not alone

https://www.reddit.com/r/jailbreak/comments/aux1ah/question_need_help_cancelling_the_update_progress/

**Comment by CoolPersonMaam** [comment]
Have you ever try turning on airplane mode

**Comment by Xtorsion** [comment]
Tes,still the same issue, nothing changes

El 7 març 2019, a les 1:08, CoolPersonMaam <notifications@github.com> va escriure:
