### ISSUE TITLE
Device froze while in wiggle mode and I hard reset it, now it's like it is unjailbroken. 

### ISSUE THREAD

**Issue by elusurpo** [pwn20wndstuff/Undecimus#701]
I was editing my homescreen in wiggle mode and the device froze completely. I hard reset the device and when it restarted it was not in safe mode, It was like the jailbreak left. I turn the device off and on again, and it still resets normally like it has no jailbreak. I don't know if there is a way to respring the device or something. Please help.

**Comment by yovannymontelongo** [comment]
This happens. The jailbreak is semi-tethered. Meaning when the device is fully rebooted, the jailbreak has to be run all over again. You can simply just open unc0ver and hit the jailbreak button. The app will respring your phone into the jailbroken state and all your tweaks will work just fine.
