### ISSUE TITLE
Delete substrate when restoring rootfs

### ISSUE THREAD

**Issue by zebedeeh7** [pwn20wndstuff/Undecimus#703]
**Describe the feature you'd like**
When restoring rootfs, if you have app icons from the jailbreak, they will remain there as white icons that you cannot delete. Not sure if deleting substrate is the right way to do it but it would be nice to have all those icons gone after restoring rootfs

**Describe alternatives you've considered**
Not really sure there's an alternative other than maybe running UIcache beforehand?

**Additional context**
n/a

**Comment by pwn20wndstuff** [comment]
RootFS Restore completely restores the file system and deletes everything involved with the jailbreak, so does it delete Substrate. - Icon cached are preserved by the system and there is no safe way to delete them before the reboot. - Closing as this is an invalid issue.
