### ISSUE TITLE
Error: RootFS already mounted: BuildVersions don't match 12.1.2 vs. 12.1.4

### ISSUE THREAD

**Issue by TheChatty** [pwn20wndstuff/Undecimus#707]
No OTA file, fresh reboot, but always the same error:
```
[*] Snapshots on newly mounted RootFS:
[*] 	com.apple.os.update-F1CFF5A4FAF7AD63D0BBBA9092C348CB4A5208CC5F23D1F864B61816C0045AE06775A1AE92E93DC6CFB522E327FB52FD
[*] 	com.apple.os.update-MSUPrepareUpdate
[*] snapshot VersionPlist: {
    BuildID = "4B4F80DA-FEAD-11E8-8758-EE1D232787AC";
    ProductBuildVersion = 16C101;
    ProductCopyright = "1983-2018 Apple Inc.";
    ProductName = "iPhone OS";
    <ProductVersion = "12.1.2";
    SystemImageID = "D94F0DBF-0332-4A74-BB55-907D39D22030";
}
[*] rootfs VersionPlist: {
    BuildID = "523EBB10-28F9-11E9-ABB4-920B8C797186";
    ProductBuildVersion = 16D57;
    ProductCopyright = "1983-2019 Apple Inc.";
    ProductName = "iPhone OS";
    ProductVersion = "12.1.4";
    SystemImageID = "F67A43D3-2ED4-4776-9A03-B23B4F809363";
}
[*] __assert(2:"BuildVersions match"==NULL)@JailbreakViewController.m:1175[jailbreak]
```
Please add an option to remove the **com.apple.os.update-MSUPrepareUpdate** snapshot.
[unc0ver-b41-iPhoneX.log](https://github.com/pwn20wndstuff/Undecimus/files/2931144/unc0ver-b41-iPhoneX.log)

**Comment by Scouseyerr** [comment]
Open uncover untick disable auto updates run the jailbreak then when it reboots the software update will be there then put in airplane mode and delete the iOS update an run jailbreak normal

**Comment by Scouseyerr** [comment]
Because the new iOS has not fully downloaded but it is there and when you run jailbreak it disables updates but doesn't delete the partial file

**Comment by TheChatty** [comment]
Disabling auto updates did not solve the problem - same error.

**Comment by TheChatty** [comment]
Problem solved.

**Comment by TheChatty** [comment]
@pwn20wndstuff: Because you recently suggested to restore to 12.1.1b3 - it's not necessary (see above).

**Comment by Scouseyerr** [comment]
Download update again then delete it with airplane mode turned on then reboot an jailbreak

**Comment by topaztopaz** [comment]
Hello I am having the same issue but there is no OTA download. Help?!
