### ISSUE TITLE
cydia crshing 

### ISSUE THREAD

**Issue by AppleNati0n** [pwn20wndstuff/Undecimus#711]
Date: 2019-03-05 13:50:16 +0000
Process: Cydia
Bundle id: com.saurik.Cydia
Exception type: NSInvalidArgumentException
Reason: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]
Culprit: tweakCompatible.dylib
Device: iPhone 7, iOS 12.1.2
Call stack:
0 CoreFoundation 0x00000001a7400edc __exceptionPreprocess
1 libobjc.A.dylib 0x00000001a65d1a40 objc_exception_throw
2 CoreFoundation 0x00000001a7378494 _CFArgv
3 CoreFoundation 0x00000001a72fe980 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
4 CoreFoundation 0x00000001a72ef4c4 +[NSDictionary dictionaryWithObjects:forKeys:count:]
5 tweakCompatible.dylib 0x00000001043c24b4 tweakCompatible.dylib + 25780
6 Foundation 0x00000001a7eb442c __NSThreadPerformPerform
7 CoreFoundation 0x00000001a73911f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
8 CoreFoundation 0x00000001a7391170 __CFRunLoopDoSource0
9 CoreFoundation 0x00000001a7390a54 __CFRunLoopDoSources0
10 CoreFoundation 0x00000001a738b920 __CFRunLoopRun
11 CoreFoundation 0x00000001a738b1f0 CFRunLoopRunSpecific
12 GraphicsServices 0x00000001a9604584 GSEventRunModal
13 UIKitCore 0x00000001d46e2d40 UIApplicationMain
14 Cydia 0x0000000100b35214 main
15 libdyld.dylib 0x00000001a6e4abb4 start
​,
iphone 7, ios 12.1.2

**Comment by airsquared** [comment]
You didn't fill out the bug report template and didn't follow the issue guidelines. Please close this issue and create a new one with the template filled out.

**Comment by king4q** [comment]
@cryptiiiic close this issue
