### ISSUE TITLE
Errno: 1 Failed to initialize Patchfinder64

### ISSUE THREAD

**Issue by mac-user669** [pwn20wndstuff/Undecimus#712]
**Describe the bug**
When I run Unc0ver compiled from Xcode, my iPhone 5s gives me this error:

![img_c66d567577c0-1](https://user-images.githubusercontent.com/36574329/53818679-7548cd00-3f36-11e9-9ce7-51f0cf7b13ab.jpeg)

**To Reproduce**
1. Compile Unc0ver 3.0.0b41
2. Click on Jailbreak
3. See error

**Screenshots**
![img_c66d567577c0-1](https://user-images.githubusercontent.com/36574329/53818773-9c9f9a00-3f36-11e9-93d0-6907204645ea.jpeg)

**Device (please complete the following information):**
 - iOS Version: 12.1.1b3
 - iOS Device: iPhone 5s
 - unc0ver Version: 3.0.0b41

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/pN1fBr9B

**Comment by me246813579** [comment]
Update: This same error happens when I download it from ignition.fun

**Comment by cr419** [comment]
This has been an issue for myself and some others since b34 

https://github.com/pwn20wndstuff/Undecimus/issues/574

Linking simply in hope it will be fixed.

**Comment by me246813579** [comment]
Somehow got fixed, idk how

**Comment by mac-user669** [comment]
For some reason, it started happening again

**Comment by wcameronmartin** [comment]
Same

**Comment by HelloDefender12** [comment]
same problem on unc0ver dark

**Comment by Amzd** [comment]
Had the same issue, restarting my iPhone X fixed it. (iOS 12.1.1)
