### ISSUE TITLE
UI icon layout & Refresh UI cache

### ISSUE THREAD

**Issue by Potterd** [pwn20wndstuff/Undecimus#715]
Rejailbreak not restoring correct icon layout, Using “Refresh UI Cache” option causes JB to hang during restart

**Comment by Mas9311** [comment]
Can you elaborate on "Rejailbreak not restoring correct icon layout". Are there extra icons, less icons, blank icons, icons switched places, etc?

Also, <code>uicache</code> always takes a while because it has to reset every icon's cache on the Springboard.

**Comment by airsquared** [comment]
You didn't fill out the bug report template and didn't follow the issue guidelunes. Please close this issue and create a new one with the template filled out.

**Comment by king4q** [comment]
@cryptiiiic close this issue

**Comment by Potterd** [comment]
About 8-10 icons are moved to a new page.  It’s not difficult to move them back but would be an advantage if Unc0ver can restore the exact layout from the previous jailbreak session IMHO.

 

Setting the “Refresh Icon Cache” option in Unc0ver causes the spinning wheel to continue indefinitely on my device during the restart – Need to hard reset and Re-Jailbreak to correct.

 

Hope this helps !

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 <mailto:David@dpotterconsulting.com> David@dpotterconsulting.com

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting

**Comment by Potterd** [comment]
If someone can please provide the "issue guidelines" that airsquared has referred to .....

**Comment by Potterd** [comment]
Please provide instructions …..

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 <mailto:David@dpotterconsulting.com> David@dpotterconsulting.com

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting

**Comment by blanxd** [comment]
This would be easier to read if you didn't reply to the email messages but used the web (or at least delete the rest of the text so only your reply remains in the messages). Also if you start a new bug on a mobile device, better use the "Desktop version" here, then you'll see the template.

**Comment by Potterd** [comment]
Additional:

Having Boxy 3 installed seems to resolve the issue.  After Re-JB all icon locations are restored to previous locations.

David Potter
DPotter Consulting Inc
(415) 485-5876 (office)
(415) 608-7797 (mobile)
David@dpotterconsulting.com

You can view me on LinkedIn: www.linkedin.com/in/dpotterconsulting

**Comment by airsquared** [comment]
@Potterd The issue guidelines are at #627, and the template should show up when you create a new issue.

**Comment by Potterd** [comment]
Done – Closed and reopened as #737

 

Thanks for your help !

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 <mailto:David@dpotterconsulting.com> David@dpotterconsulting.com

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting
