### ISSUE TITLE
b40/b41 issues

### ISSUE THREAD

**Issue by theLaxerz** [pwn20wndstuff/Undecimus#716]
b40 and b41 cannot clear my messages after being read the badge shows, and b40 cannot JB unless not in Airplane Mode. 

Also other tweaks are not working.

**Comment by airsquared** [comment]
You didn't fill out the bug report template and didn't follow the issue guidelunes. Close this issue and create a new one.

**Comment by king4q** [comment]
@cryptiiiic close this issue
