### ISSUE TITLE
unc0ver resprings into jailbreak mode but then reboots.

### ISSUE THREAD

**Issue by iTNZPP** [pwn20wndstuff/Undecimus#719]
**Describe the bug**
When I went to Cydia I added a repo then while it was reloading data it froze so i hard reboot. When i clicked on Jailbreak it succeeded. So it was respringing for like 2 minutes and then it reboots.  

**To Reproduce**
1. Go to 'Cydia'
2. Click on 'Sources'
3. Scroll down to 'Edit then Add'
4. Added repo 
5. It freezes.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.0.1
 - iOS Device: iPhone 5S
 - unc0ver Version: 3.0.0~b41

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by MaDMAn0** [comment]
go to Unc0ver in settings and disable Reload System Deamons then do the jailbreak again and it will work now
