### ISSUE TITLE
[*] Unable to resolve lzma to a debs

### ISSUE THREAD

**Issue by Amoystyle** [pwn20wndstuff/Undecimus#720]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to 'unc0ver'
2. Click on 'Jailbreak'
3. See error

**Screenshots**
![53724407-c5774f00-3ea4-11e9-8356-c9b01aba2051](https://user-images.githubusercontent.com/5343265/53871937-21261180-4038-11e9-8e62-7aed24049157.jpg)

**Device (please complete the following information):**
 - iOS Version: 12.0
 - iOS Device: IPAD, iphone X
 - unc0ver Version: b39, b40, b41

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2935535/diagnostics.zip)

Fix[x]:

```
Package: lzma
Version: 2:4.32.7-2
Architecture: iphoneos-arm
Maintainer: Sam Bingner <maintainer@sbdhi.com>
Installed-Size: 736
Conflicts: com.mc.xz
Filename: ./lzma_2:4.32.7-2_iphoneos-arm.deb  <-- this path is error, replace: ./lzma_2_4.32.7-2_iphoneos-arm.deb
Size: 71624
MD5sum: 1eff2a2bfed451132f417f757e2f5316
SHA1: 52a5b1cadd8992a3c522ff4e9485eb7b7e6264d9
SHA256: a67c3c0e5982c8ac46b24238e90ae6aa373775bfbcf1b6a4a43f65dc1fd12490
Section: Archiving
Priority: important
Homepage: http://tukaani.org/lzma/
Description: slower, but better, compression algorithm
Name: LZMA Utils
```

**Comment by chiefx2** [comment]
Hi,

I am on ios 12.1.2 IphoneX and just have this exact same issue on Undecimus-v3.8.0.b1.ipa

If it helps, I used AltStore to install it.

What can I do to fix it?


Edit: It is definitely AltStore or the .ipa it is patched with to install. Although the .ipa it is installing has the same size as the official unc0ver.ipa

I used 3utools to install the jailbreak and it is working fine.

**Comment by Amoystyle** [comment]
> Hi,
> 
> I am on ios 12.1.2 IphoneX and just have this exact same issue on Undecimus-v3.8.0.b1.ipa
> 
> If it helps, I used AltStore to install it.
> 
> What can I do to fix it?
> 
> Edit: It is definitely AltStore or the .ipa it is patched with to install. Although the .ipa it is installing has the same size as the official unc0ver.ipa
> 
> I used 3utools to install the jailbreak and it is working fine.

**path:** Undecimus.app\apt\Packages

**Replace the following strings：**

```
Filename: ./apt7_1:0-2_iphoneos-arm.deb
Filename: ./apt7-key_1:0_iphoneos-arm.deb
Filename: ./apt7-lib_1:0_iphoneos-arm.deb
Filename: ./lzma_2:4.32.7-2_iphoneos-arm.deb
```
as

```
Filename: ./apt7_1_0-2_iphoneos-arm.deb
Filename: ./apt7-key_1_0_iphoneos-arm.deb
Filename: ./apt7-lib_1_0_iphoneos-arm.deb
Filename: ./lzma_2_4.32.7-2_iphoneos-arm.deb
```

**Comment by MikeeI** [comment]
Can somebdoy do this and post the IPA here?

**Comment by sahilsingh39** [comment]
https://bit.ly/2HrxxPJ
Here's the ipa after trying as mentioned above but after I do this AltServer won't install the ipa anymore.

**Comment by CaiMiao** [comment]
same problem here
