### ISSUE TITLE
Fatal Error : Errno 2

### ISSUE THREAD

**Issue by omaemaru** [pwn20wndstuff/Undecimus#723]
**Describe the bug**
Fatal Error
Test: "Buildversions match"==NULL 
Filename: JailbreakViewController.m
Line: 1227
Function: jailbreak
Description: RootFS already mounted, delete OTA file from Settings - Storeage if present and reboot

**Device (please complete the following information):**
 - iOS Version: 12.0 
 - iOS Device: iPhone 6
 - unc0ver Version: 40b

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
See attached zip
[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2935968/diagnostics.plist.zip)

**Comment by coenkcore** [comment]
Update to unc0ver 3.0.0~b43
And check here
https://twitter.com/jakeashacks/status/1103747007745835011?s=21

**Comment by omaemaru** [comment]
Great, updated to the latest version and works perfectly, good job!
