### ISSUE TITLE
no offset for ipad

### ISSUE THREAD

**Issue by luosuonan** [pwn20wndstuff/Undecimus#724]

**Comment by WalshyDev** [comment]
Wow such detail, I'm so glad you want this "issue" resolved.

**Comment by CoolPersonMaam** [comment]
I know right WHAT KIND OF OFFSETS ARE YOU TALKIBG ABOUT WHAT DEVICE IM SO GLAD YOU DIDNT HSE THIS TEMPLATE. Provide more information and close this ticket please with template

**Comment by ConfirmedPlayer** [comment]
Thank you very much for describing the problem in detail!

**Comment by luosuonan** [comment]
i use tweak change watchdog info.plist，then root ，cant jailbreak
