### ISSUE TITLE
iMessage crashes during Voice Messages

### ISSUE THREAD

**Issue by dannyderito** [pwn20wndstuff/Undecimus#725]
Devices: iPhone 10,4 @ 12.1.1, latest unc0ver (see attached log)
iPhone 9,4 12.1.1 Beta 3, latest unc0ver

As soon as you start recording or sometimes when you send it, it crashes to Springboard. It does not crash during the voicemessage. Super rarely the voice message gets recorded and sent.
Log file at: https://pastebin.com/K54TQhKc

**Comment by amandamana** [comment]
#604

**Comment by the-eric-kwok** [comment]
I think this is the reason why QQ crash when voice call incoming

**Comment by wesmosis** [comment]
Same here

**Comment by ciubaca666** [comment]
occurs also on b45 on iphone 6s and iphone 7

**Comment by john6155** [comment]
I think it is happening to everyone. I can't find a person who doesn't have this issue. Please fix as soon as you can. 

Thank you for the hard work!

**Comment by silentshotghost** [comment]
Same Here
