### ISSUE TITLE
ERROR (FATAL) Errno 2: Failed to copy over our resources to RootFS

### ISSUE THREAD

**Issue by Oxycodon-IV** [pwn20wndstuff/Undecimus#726]
**Describe the bug**
Simply tried running LdRestart on device...device rebooted back into stock mode (not JB state)...went into unCover to Jailbreak again...and go this error.

Tried to Recover RootFS, which was successful, then phone restarted like it usually does, opened unc0ver to continue to process...and now I keep getting this error.

**To Reproduce**
1. LdRestart
2. Try to jailbreak

**Screenshots**

![img_1770](https://user-images.githubusercontent.com/20485643/53885364-8b649500-3feb-11e9-9fe4-92a52c4afb0a.png)

![img_1771](https://user-images.githubusercontent.com/20485643/53885385-94edfd00-3feb-11e9-9abf-50aef2033d76.png)

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: v3.0.0 beta 41

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2936482/diagnostics.plist.zip)

**Comment by Oxycodon-IV** [comment]
SOLVED!

Simply, Remove unC0ver application from Homescreen (like you would remove any application) and simply redownload it.

And Jailbreak

(I did Recover RootFS earlier trying to fix this error, soo I dont know if that was needed to fix the issue or not, soo attempt too delete & reinstall before attempting Recover RootFS)

Goodluck

**Comment by WalshyDev** [comment]
Please close if solved @Oxycodon-IV
