### ISSUE TITLE
App Store and Apple Music app lose internet connection and unable to connect

### ISSUE THREAD

**Issue by kharder69** [pwn20wndstuff/Undecimus#730]
**Describe the bug**
After jailbreak I am able to use the App Store and Apple Music and can connect to Internet with those apps but after a while I try to use the apps again they appear to lose connection to the Internet.  I have tried to enable airplane mode and disable airplane mode but it does not resolve the issue.  If I re-jailbreak the iPad it will then work again for a while before it stops working again.

**To Reproduce**
1. Go to App Store and get message "Cannot connect to App Store, retry
2. Go to Apple Music app and try to play a song in the cloud that is not downloaded and eventually get error message "
3. Re-jailbreak
4. Apps then work for a while.

**Screenshots**
Not required.

**Device (please complete the following information):**
 - iOS Version: 12.1.1b3
 - iOS Device: iPad 12.9 1st Gen
 - unc0ver Version: v3.0.0b41

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by bobbypin17** [comment]
Same issue. After a while I can’t connect to AppStore. I have to rejailbreak to connect to AppStore again.

**Comment by onisimus** [comment]
i have this issue with google maps, "no location detected." Apple maps works tho
