### ISSUE TITLE
Unc0ver won't open when installed on pc but works from Ignition app

### ISSUE THREAD

**Issue by amolsdhaliwal** [pwn20wndstuff/Undecimus#731]
I've used impactor to attempt to install unc0ver but every time I do this, the app won't open. When I download it from Ignition, it works every time. I'm on iPhone 6S ios 12.1.1 b3

**Comment by snowball7241** [comment]
Did you trust the app in settings?

**Comment by amolsdhaliwal** [comment]
Yeah I have
