### ISSUE TITLE
find & delete dpkg "lock" file at the end of the JB script

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pwn20wndstuff/Undecimus#735]
**Describe the feature you'd like**
find & delete dpkg "lock" file at the end of the JB script

**Additional context**
found in /var/lib/dpkg/lock <--

its getting frustrating in Cydia DPKG is locked error & using fiza or terminal to delete lock file every time unc0ver is used to re-jail. 
I do a lot tweak debugging to see which one causes conflicts or causes unc0ver to crash or not respring from the app. the locked DPKG error is getting really annoying so if unc0ver could check for this every time it's done running the main script to delete the lock file would be great.

**Comment by Amplespencer** [comment]
this would be nice for when dpkg randomly breaks everything
