### ISSUE TITLE
Unc0ver not restoring icon layout

### ISSUE THREAD

**Issue by Potterd** [pwn20wndstuff/Undecimus#737]
**Describe the bug**
Unc0ver Jailbreak does not restore completely prior icon layout.  Some icons need to be moved to original locations after processing.  Does not occur if Boxy 3 is installed (workaround).

**To Reproduce**
1. Reboot
2. Run Unc0ver Jailbreak

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone SE
 - unc0ver Version: b42

**Place an "x" between the brackets if true:**
 - [X ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by viggou** [comment]
This is normal, you have to install the tweak "IconSupport".

**Comment by Potterd** [comment]
IconSupport is described as a “support” program that needs to be invoked by a calling program.  Please confirm that you have resolved this issue by only installing IconSupport (no calling program) and that you have tested this solution.

**Comment by DistinctCancer** [comment]
Does the icon looks like (grid icon)
I got the same problem even with icon support is installed
