### ISSUE TITLE
failed to copy over our resources to RootFS

### ISSUE THREAD

**Issue by chenxustu1** [pwn20wndstuff/Undecimus#739]
**Describe the bug**
failed to copy over our resources to RootFS

**To Reproduce**
1. Go to unc0ver app
2. Click on 'Jailbreak'

**Screenshots**
![image](https://user-images.githubusercontent.com/1113400/53934370-8da71c00-40dd-11e9-883c-3220a2222037.png)

**Device (please complete the following information):**
 - iOS Version: 12.1.1beta3
 - iOS Device: iphone 5s
 - unc0ver Version: b42

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Oxycodon-IV** [comment]
Had this problem....try deleting the actually unc0ver application and reinstalling it...and try again 

Good luck :)

**Comment by chenxustu1** [comment]
> Had this problem....try deleting the actually unc0ver application and reinstalling it...and try again
> 
> Good luck :)

after three times reinstall and reboot,i still not get succes.

**Comment by anderson200tan** [comment]
use unc0ver 3.0.0~b31

**Comment by chenxustu1** [comment]
> use unc0ver 3.0.0~b31

b31 not work with iphone 5s(a7 cpu).
