### ISSUE TITLE
debugserver  Failed to get connection from a remote gdb process.

### ISSUE THREAD

**Issue by s84088722** [pwn20wndstuff/Undecimus#740]
unc0ver 3.00 beta 41
Device: iPhone9,3 
iPhone:~ root# debugserver *:6666 “Preference”
debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
for arm64.
Attaching to process Preference...
Listening to port 6666 for a connection from *...
Failed to get connection from a remote gdb process.
Exiting.
iPhone:~ root#

Console:
kernel	Sandbox: 3 duplicate reports for debugserver deny(1) network-outbound /private/var/run/mDNSResponder
kernel	Sandbox: debugserver(997) deny(1) system-socket
debugserver	socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: Operation not permitted
debugserver	socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: Operation not permitted
kernel	Sandbox: 1 duplicate report for debugserver deny(1) system-socket
kernel	Sandbox: debugserver(997) deny(1) network-bind:6666*
debugserver	1 +0.000000 sec [03e5/0403]: ::listen or ::bind failed err = 0x00000000
kernel	Sandbox: 3 duplicate reports for debugserver deny(1) network-bind:6666*

**Comment by s84088722** [comment]
> Device: iPhone9,3
> iPhone:~ root# debugserver *:6666 “Preference”
> debugserver-@(#)PROGRAM:LLDB PROJECT:lldb-900.3.86
> for arm64.
> Attaching to process Preference...
> Listening to port 6666 for a connection from *...
> Failed to get connection from a remote gdb process.
> Exiting.
> iPhone:~ root#
> 
> kernel	Sandbox: 3 duplicate reports for debugserver deny(1) network-outbound /private/var/run/mDNSResponder
> kernel	Sandbox: debugserver(997) deny(1) system-socket
> debugserver	socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: Operation not permitted
> debugserver	socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: Operation not permitted
> kernel	Sandbox: 1 duplicate report for debugserver deny(1) system-socket
> kernel	Sandbox: debugserver(997) deny(1) network-bind:6666*
> debugserver	1 +0.000000 sec [03e5/0403]: ::listen or ::bind failed err = 0x00000000
> kernel	Sandbox: 3 duplicate reports for debugserver deny(1) network-bind:6666*

**Comment by qrx** [comment]
Same issue here. It doesn't allow a connection and just fails and exists within seconds of 'waiting'.

**Comment by s84088722** [comment]
@pwn20wndstuff

**Comment by yuripe-murmur** [comment]
Same issue.

**Comment by lslfly** [comment]
Same issue

**Comment by s84088722** [comment]
Same issue@pwn20wndstuff

**Comment by Daemonceltics** [comment]
Codesign or ldid enetitlements

**Comment by holyswordman** [comment]
i have figured it out. debugserver actually works.

1. To solve failed to get connection from a remote gdb process issue: resign debugserver without "seatbelt-profiles" entitlement xml.

 (They fixed now, so just updates Unc0ver Jailbreak Resources in Cydia and reload the new debugserver)

2. To solve another EXC_BAD_ACCESS issue: The target process being debugged needs the get-task-allow entitlement . you can resign the app (your target app being debugged, not debugserver) with get-task-allow entitlement as a temporary workaround. then debugserver will works!

I believe they have fixed it already.
Next "Unc0ver Jailbreak Resources" update in Cydia App should solve it.

**Comment by jeffli678** [comment]
Same issue. Really wish to get a fix for it, thx!

**Comment by zhangxistudy11** [comment]
Same issue.
