### ISSUE TITLE
Keeps rebooting at 27/38    RootFS already mounted,Error (Fatal) line 1656

### ISSUE THREAD

**Issue by 0nikin9** [pwn20wndstuff/Undecimus#741]
**Describe the bug**
Always get the Error (Fatal) line 1656 when clicking on Jailbreak button

**To Reproduce**
Go to 'unc0ver'
Click on 'Jailbreak'
See error
Screenshots

**Screenshots**
![_20190307171926](https://user-images.githubusercontent.com/48313974/53946315-73ca0100-40fe-11e9-9231-55d96d88d8b5.jpg)
![_201903071719261](https://user-images.githubusercontent.com/48313974/53946320-76c4f180-40fe-11e9-9c3c-688e2e23a74e.jpg)

**Device (please complete the following information):**

iOS Version: 12.0
iOS Device: iPhone 6
unc0ver Version: b40、b41、b42

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

[diagnostics.log](https://github.com/pwn20wndstuff/Undecimus/files/2940449/diagnostics.log)

**Comment by vitalik2187836** [comment]
Nobody gonna help you, suddenly. You are the fourth who posted similar error. No answers yet. 
On iOS 11.3 I had errors because of messed up volume up button. Is it working on you phone?

**Comment by 0nikin9** [comment]
I think what you said makes sense.  My volume up button is really bad!

**Comment by vitalik2187836** [comment]
What iOS do you have?

**Comment by vitalik2187836** [comment]
San Bingner made a temporary fix for this issue for old beta version of uncover which doesn't support iOS 12 so we can't use it now.

**Comment by Wanqed** [comment]
@vitalik2187836 , @0nikin9 please refer to issue #699 there is a fix, on the latest version. Look for sbingner’s post in that issue. (IF VOLUME BUTTON IS STUCK OR BROKEN)

**Comment by Wanqed** [comment]
And do not Restore RoofFS if using this because it may reupdate substrate. And only run once, then u can use other versions of unc0ver unless there is another substrate update

**Comment by 0nikin9** [comment]
> And do not Restore RoofFS if using this because it may reupdate substrate. And only run once, then u can use other versions of unc0ver unless there is another substrate update

thx，testing.
