### ISSUE TITLE
iPhone 6 keeps unjailbreaking itself

### ISSUE THREAD

**Issue by Krobix** [pwn20wndstuff/Undecimus#742]
My iPhone 6 12.0.1 keeps unjailbreaking itself when I install a tweak just around 9 PM. All of the tweaks are gone, and cydia and the other jailbroken apps will not open. Following that, I am only able to rejailbreak without my phone rebooting in the middle after 7:45 AM. Can someone please help me?

**Comment by Xamanthas** [comment]
You need to give more details than this. What tweak did you install? What version of unc0ver? Have you tried restoring rootfs? This isnt for user help, go to the jailbreak discord for that https://discord.gg/bHdzaab

**Comment by Krobix** [comment]
I was able to rejailbreak it, but only after about twenty tries. This happened at the last time when I installed apple file conduit 2, and a respiring logo changer (don't remember the name). Note that I only installed tweaks that TweakCompatible confirmed to be supported.

**Comment by Xamanthas** [comment]
Are you on unc0ver b43?

**Comment by Krobix** [comment]
I don goofed. Was on b40. Thanks for the help @Xamanthas !

**Comment by Xamanthas** [comment]
No problems. In the future please submit bug reports with **all** pertinent information and always troubleshoot first. (check for updates, disable tweaks etc)
