### ISSUE TITLE
Failed to extract bootstrap after respring during hard reset

### ISSUE THREAD

**Issue by arseny2606** [pwn20wndstuff/Undecimus#744]
Failed to extract bootstrap error after hard reset during respring. After this error, the tweaks that don't work on springboard are loaded. If you do a respring using any tweak, then it will work. It turns out, unc0ver can't do respring after a successful jailbreak. iPhone 7,2; iOS 12.0.1; u0 v3.0.0~b43. Screenshot: https://imgur.com/a/iYZ41UQ Diagnostics data: https://drive.google.com/file/d/1RBCaNoB_XLA-tGNikGWwJPsNnGnDFOjT/view?usp=drivesdk

**Comment by Cryptiiiic** [comment]
Reopen a new issue after following guidelines and template.
