### ISSUE TITLE
OTA file could not be found in the iPhone storage 

### ISSUE THREAD

**Issue by Chineeleg** [pwn20wndstuff/Undecimus#746]
Jail breaking in the half and it says error, needs to delete OTA update files. However I cannot find it and the update checking doesn’t work anymore. Tried many times it still says I need to delete the OTA. However I cannot find it on my phone. From IOS 12.1. iPhone 6.

**Comment by Mas9311** [comment]
I bet you probably know what you're doing, but just to double check:
Settings > General > iPhone Storage > find the Settings icon "iOS 12.1.4" near the top.
If it's not present, then this is a legitimate issue. Troubleshoot by hard resetting your phone (press and hold the sleep and home button until you see Apple logo again)

**Comment by nraiha** [comment]
Does it say that RootFS is already mounted?

If it does do the following steps:

- delete ota updates if any
- jb with "disable updates" turned OFF
- let it fail
- reboot
- open settings and start downloading OTA
- when it starts, enter AIRPLANE MODE!
- reboot
- try jailbreaking again with "disable updates" ON
