### ISSUE TITLE
Overnight charging causes reboot

### ISSUE THREAD

**Issue by sag24ar** [pwn20wndstuff/Undecimus#749]
**Describe the bug**
The phone seems to reboot itself if left on charging overnight, to wake up with an unjailbroken phone. I found people with similar issue on searching on r/jailbreak.

**To Reproduce**
1. Leave your jailbroken iphone on charge for the night. Or for a very long time?!

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone 6
 - unc0ver Version: beta 43

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
No logs

**Comment by bernaction** [comment]
Same here.
iPhone 6 Plus @ iOS 12.0

**Comment by Unicorn666911** [comment]
Same, but mines worse. When it reboots it causes the jailbreak not to be able to jailbreak anymore unless i disable tweaks and daemons. This has been persistent for 3 days in a row.
iPhone 6 128GB on iOS 12.1

**Comment by atifchy** [comment]
Install cappd

**Comment by Unicorn666911** [comment]
> Install cappd

I installed it. I'll test it tonight.

**Comment by cortexm333** [comment]
same here.
iPhone 6Plus @ iOS12.1.1
unc0ver Version: beta 41

**Comment by Moddingmad** [comment]
I am also having the same issues , since b38 (A7/A8 Support was added . And I jailbroke my A7 iPad mini 2 (12.1.1) . 
See following OPEN issue = For testing that has been done in relation to this.
https://github.com/pwn20wndstuff/Undecimus/issues/635#issue-416052708

**Comment by Potterd** [comment]
I also have this problem

**Comment by sag24ar** [comment]
The only solution for me is to respring into safe mode when I go to sleep. That seem to prevent this from happening.

**Comment by iSnowish** [comment]
Same issue. 

Type of Device : iphone 6+ 

iOS version: 12.1.1 b3 

Jailbreaking with uncover b43 

The issue is , when i leave my iPhone charging at night for a long period. I  woke up  With unJailbroken device  or some times a frozen black  screen. So i have to manually hardReboot the phone and reJailbreak again . 
Its been happening every night when the phone is charging.

**Comment by iSnowish** [comment]
Update: ihave removed letMeBlock tweak. It seems not solveing out the issue of overnight reboot.
