### ISSUE TITLE
Error (Fatal) :ErrNo 2

### ISSUE THREAD

**Issue by extreme855** [pwn20wndstuff/Undecimus#750]
I can’t re-jailbreak , restored RootFS , iPhone 7 @ iOS 12.1.2. 
No OTA file, very first time jailbreak was success’s now I am unable to re-jailbreak. Tried many many times. 

Unc0ver version : b43

![d10c7e85-610d-41ab-8a8f-1692443817fe](https://user-images.githubusercontent.com/48354041/54027788-5acb5980-41ab-11e9-9fd8-b49da0e4eabe.png)

**Comment by Mrlobbies** [comment]
Hello!  I was having this same issue .  I followed some steps to try and re- initiate apples OTA update and put it into airplane mode right after it starts to download with no luck.  They only way i was able to successfully JB was by going into setting and erase all settings and content .  Set up as new phone , i then restored from my icloud back up and ran the jailbreak again with success.  Hope this helps .   Seems like the rootfs still has some partial file that wont remove it's self idk.

**Comment by anderson200tan** [comment]
Uncover 3.0.0~b31
Fixed the issue for me.
