### ISSUE TITLE
[Question] Importance of Reload System Daemons?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pwn20wndstuff/Undecimus#751]
could someone explain the importance of reloading system Daemons within unc0ver? how badly does this impact the system? does it break anything within the jailbroken state if system Daemons are not reloaded?

because I have noticed that respringing tends to be super quick & doesnt fail to respring if this option is disabled..

also reloading system Daemons tends to kill the Universal Clipboard function on the iDevice (handoff feature) - probably a bug in the reload function not reloading the service that controls Universal Clipboard from working.

**Comment by deot** [comment]
the same problem
