### ISSUE TITLE
How to Codesign?

### ISSUE THREAD

**Issue by TrungNguyen1909** [pwn20wndstuff/Undecimus#752]
**Describe the bug**
How to codesign the binaries? I need to sign clang because inject everything will overflow the trustcache(also unstable).
**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone6S
 - unc0ver Version: b43

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by pwn20wndstuff** [comment]
ldid -e /path/to/binary > /var/tmp/_ents.xml
ldid -S/var/tmp/_ents.xml /path/to/binary
rm /var/tmp/_ents.xml

With the latest version of ldid.

**Comment by TrungNguyen1909** [comment]
Not working, output:
iPhone:~/jtool2 mobile$ ldid -e jtool2             
iPhone:~/jtool2 mobile$ ldid                       
usage: ldid -S[entitlements.xml] <binary>          
   ldid -e MobileSafari                            
   ldid -S cat                                     
   ldid -Stfp.xml gdb                              
iPhone:~/jtool2 mobile$ ldid -e ./jtool2           
iPhone:~/jtool2 mobile$ ldid -e ./jtool2 > ent.xml 
iPhone:~/jtool2 mobile$ ldid -Sent.xml ./jtool2    
ldid.cpp(1160): _assert(): errno=22                
libc++abi.dylib: terminating with uncaught exception of type char const*                               
Abort trap: 6                                      
iPhone:~/jtool2 mobile$ ./jtool2                   
Killed: 9                                          
iPhone:~/jtool2 mobile$

**Comment by SaeedHaidar** [comment]
try it with out ./ just type jtool2

**Comment by SaeedHaidar** [comment]
it should work

**Comment by SaeedHaidar** [comment]
can you give me the link to jtool2 pls

**Comment by TrungNguyen1909** [comment]
none of them work. Killed 9 jtool2 can be found on J’s twitter

**Comment by SaeedHaidar** [comment]
can you tell me pls which entitlements do i need for jtool2
