### ISSUE TITLE
canOpenURL: failed for URL: "Cydia://" - error: "This app is not allowed to query for scheme cydia"

### ISSUE THREAD

**Issue by amirber** [pwn20wndstuff/Undecimus#753]
I trying to jailbreak my Iphone 6 plus on ios 12.1, and all works fine but after jailbreak  still no Cydia, all I see Before I jailbreak is "-canOpenURL: failed for URL: "Cydia://" - error: "This app is not allowed to query for scheme cydia"

how fix this error???

I use Undecimus-v3.0.0-b43

**Comment by WalshyDev** [comment]
Not an error, just means there's no Cydia there. Normal to see before a jailbreak. 

Can you confirm it definitely jailbreaks? Do you see it respring? Does it restart? When in unc0ver does it show "Re-Jailbreak"?

**Comment by snowball7241** [comment]
It's not an error, its unc0ver checking if it has root access

**Comment by alshubaily007** [comment]
I wil download  it

**Comment by snowball7241** [comment]
@fallton13 unc0ver does not have cydia for XS/A12 devices yet.

**Comment by alshubaily007** [comment]
Okk

**Comment by frakman1** [comment]
So how do I install Cydia on my iPhone SE (A9) after successfully running the unc0ver jailbreak (It says Re-Jailbreak when I launch it)
