### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by asce321** [pwn20wndstuff/Undecimus#755]
when restart device jailbreak is nomore

**Comment by MegaminxCode** [comment]
That is normal behavior. It is a semi-untethered jailbreak. Meaning when the device turns off you have to re-jailbreak it everytime.

**Comment by MegaminxCode** [comment]
Please close this issue

**Comment by coenkcore** [comment]
It's not an issue or bug
It is normal. You must re-jailbreak after device restart.

So close this isseu
