### ISSUE TITLE
Uncover won’t work

### ISSUE THREAD

**Issue by Zane285** [pwn20wndstuff/Undecimus#759]
Every time I try to jailbreak it gets done with everything then it resprings for about 5min then it resets. It has been jailbroken before and has Cydia

**Comment by snowball7241** [comment]
Try turning reload system daemons off

**Comment by king4q** [comment]
@Cryptiiiic

**Comment by jweinraub** [comment]
@snowball7241 - why did this work?  is it a bug?

**Comment by Zane285** [comment]
Snowball it didn’t work
