### ISSUE TITLE
No Cydia after jailreak 

### ISSUE THREAD

**Issue by zackery1215** [pwn20wndstuff/Undecimus#76]
After cryptiic told me I had Electra components on my Cydia I used Electra remover and got rid of the jailbreak

Now when I jailbreak it says “jail broken” but I have no Cydia

Any thoughts or what is my next move? And I’ve seen there are threads on it but no answers

**Comment by jakeajames** [comment]
Rootfs restore

**Comment by zackery1215** [comment]
How do I do that or can you point me somewhere to figure out how.

**Comment by Cryptiiiic** [comment]
@zackery1215 you need to read for a change lol. (Hint it's on the unc0ver settings page.)

**Comment by zackery1215** [comment]
On the app?
