### ISSUE TITLE
No OTA error

### ISSUE THREAD

**Issue by cheech1789** [pwn20wndstuff/Undecimus#762]
https://imgur.com/gallery/WeupQSp
No OTA update on phone. All log is on the link provided. Any help would be greatly appreciated!

**Comment by pwn20wndstuff** [comment]
See this https://twitter.com/jakeashacks/status/1103747007745835011?s=21.

**Comment by cheech1789** [comment]
Still no luck chief. No worries. Will be patiently waiting until an update fixes the issue. Thanks!

**Comment by MegaminxCode** [comment]
If you have the tv profile installed delete it and do the steps again

**Comment by cheech1789** [comment]
I don't have the tvos downloaded but thanks for the help!
