### ISSUE TITLE
Overnight reboot

### ISSUE THREAD

**Issue by aysyyld** [pwn20wndstuff/Undecimus#764]
**Describe the bug**
Every time I put my phone on charge and go to sleep the phone reboots, and it's been happening almost everyday

**Device**
 - iOS Version: iOS 12.0.1
 - iOS Device: iPhone 6
 - unc0ver Version: Latest version 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/dl/gfutc0S1

**Comment by FrAcTi0N** [comment]
I am experiencing the same problem on ios 12.1.2, iPhone 6. The only one night it did not happen was when i disabled icloud backup.

**Comment by jweinraub** [comment]
My phone rebooted last night, I am unable to rejailbreak with tweaks enabled.  I have b42 and problem persists.  I never had overnight reboot issue until today.

**Comment by iSnowish** [comment]
Same issue. 
Iphone: 6+ 
Version : 12.1.1 b3 
Jailbreaking with uncover b43
Issue: the phone reboots at night while am leaving it charging. 
By the way, I have installed the ios blocker profile update to prevent the phone from updating suddenly if the phone reboot.

**Comment by DarkRagnarok** [comment]
Jweimraub, do you by any chance have a tweak installed in the recent tab on Cydia when jailbreaking without tweaks?

**Comment by mcn2004** [comment]
Same... iPhone 7,2 iOS 12.1.1~b3 unc0ver~b45

**Comment by DarkRagnarok** [comment]
This issue is caused by LetMeBlock, it constantly re installs itself everytime I uninstall, and re enables itself when I use iCleaner to disable it 
@pwn20wndstuff

**Comment by iSnowish** [comment]
I will remove the LetMeBlock tweak and i will test the phone to see if it’s rebooting or not.

**Comment by DarkRagnarok** [comment]
Good luck with that lmao, it auto installs every time you jailbreak

**Comment by iSnowish** [comment]
Hehehe. 
The point is , i want to prevent my phone from overnight rebooting. If the LetMeBlock tweak is causing the problem. Then logically no need to reJailbreak unless I ran out of battery. 
So , lets give it a try and i will give a feedback on that.

**Comment by DarkRagnarok** [comment]
Ah that makes sense, the only way I can jailbreak is when I disable it with iCleaner after using unc0ver without tweaks

**Comment by mcn2004** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/772

**Comment by iSnowish** [comment]
update: just removed the LetmeBlock tweak. And it seems not solving out the overnight reboot.

**Comment by DarkRagnarok** [comment]
Damn sorry, I thought I had it
