### ISSUE TITLE
Applying a BootNonce in Unc0ver does not work.

### ISSUE THREAD

**Issue by PwnedC99** [pwn20wndstuff/Undecimus#766]
When using Unc0ver to set a Generator Nonce it does not actually apply it in nvram. Using "nvram -p" and System Info, both proof that there is no BootNonce applied, even the by standard 0x1111111111111111 is not present.

Device used was an iPhone9,4 (7+) 12.1.2 running the latest beta 43 of Unv0ver.

 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by pwn20wndstuff** [comment]
The nonce *is* applied. Using nvram -p will not show it because the boot nonce is not supposed to be readable or writeable. unc0ver momentarily patches nvram, sets the nonce and unpatches. So you won’t be able to read it or set it and that’s the expected behavior.
