### ISSUE TITLE
Bootlogo loop

### ISSUE THREAD

**Issue by 6papi** [pwn20wndstuff/Undecimus#768]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to 'cydia'
2. Click on 'search, download app cake '
3. Scroll down to 'cant even click restring after it was done downloading just went blank'

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device :I phone 8 plus 
 - unc0ver Version: 41

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
After the blank screen was there I couldn't do nothing so I double clicked home button went to another app and all my icons were randomized and I was like wtf, I didn't have safari messages or music app even Lydia app so how am I going to delete that tweak...so it went into safemode after it crashed and still no cydia... I restarted to go back regular still no cydia I clicked on a app and it respringed and after it just went black and went into a boot loop and bam. I'm stuck on it right now did the up down power button trick didn't work so I'm stuck here I don't want to update cause I still got hope. need some help

**Comment by WalshyDev** [comment]
You say "see error" but don't provide what the error was, can you please provide that.

**Comment by 6papi** [comment]
No error ,just when I was about to click respiring the screen went blank and I couldn’t click the home button and just went to safe mode after safe mode no Cyrus or safari etc,every time I clicked on uncover app it crashed and bamn boot loop

**Comment by 6papi** [comment]
It’s all good updated my shit
