### ISSUE TITLE
Reload System Daemons Causes Universal Clipboard to stop working

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pwn20wndstuff/Undecimus#769]
**Describe the bug**
this is kind hard to troubleshoot but when reload system daemons are on & when doing copying links from my Mac & trying to paste on my iOS device it doesnt work. but with Reload System Daemons set to OFF, there are no issues but then afc2d fails to work unless I re-install it or use the Reload System Daemons option.

there are not any logs but easy to re-produce
it could be tweak specific but unsure feels like tweaks should be loaded last after system Daemons are reloaded or some kind of timer should be introduced..

**To Reproduce**
Just enable Reload System Daemons option & load Tweaks Option
and maybe also have a handful of tweaks installed from Cydia <-- as I'm not sure what is triggering this
copy text or link from Mac & try to paste in notes, should fail.

**Workaround**
disable all tweaks via iCleaner Pro, respring
use universal clipboard to copy & paste something from Mac or from iDevice to Mac to ensure its working.
then re-enable all tweaks again on iCleaner pro, Respring
Universal Clipboard should be still working.

Notes: I'm not sure how this could be fixed, seems like whatever process controls the Universal Clipboard needs to be utilised before any tweaks are loaded for it to continue to work after tweaks are loaded.

Suggestion: allow for selective Daemons to be reloaded like the ones responsible for making Apple File Conduit "2" (arm64/KPPLess) work.

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 7 (iPhone9,3)
 - unc0ver Version: Beta43

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Comment by comicchang** [comment]
the same happens to me, jailbreak without "Reload System Daemons" resolves this.

- iOS Version: 12.1
- iOS Device: iPhone 7 (iPhone9,3)
- unc0ver Version: 3.1.3

**Comment by deot** [comment]
still not work

- iOS Version: 12.4
- iOS Device: iPhone 7 Plus (iPhone9,2)
- unc0ver Version: 3.5.6
