### ISSUE TITLE
XS Max on 12.1.1b3 fails

### ISSUE THREAD

**Issue by eskimo** [pwn20wndstuff/Undecimus#771]
Phone reboots at 2/37, right after the "received fake port..." etc

**Comment by WalshyDev** [comment]
Did you try again? Mine did the same and next attempt renamed the snapshot successfully. 

Just make sure airplane mode is on and try again.

**Comment by eskimo** [comment]
Tried about 30 times now, all with airplane mode on.

**Comment by Chaottiic** [comment]
> Did you try again? Mine did the same and next attempt renamed the snapshot successfully.
> 
> Just make sure airplane mode is on and try again.
I'm having the same issue, but normal XS. I've attempted a couple times w/o airplane mode and couple times with airplane mode.

**Comment by eskimo** [comment]
> > Did you try again? Mine did the same and next attempt renamed the snapshot successfully.
> > Just make sure airplane mode is on and try again.
> 
> I'm having the same issue, but normal XS. I've attempted a couple times w/o airplane mode and couple times with airplane mode.

Also on 12.1.1b3?

**Comment by Chaottiic** [comment]
> > > Did you try again? Mine did the same and next attempt renamed the snapshot successfully.
> > > Just make sure airplane mode is on and try again.
> > 
> > 
> > I'm having the same issue, but normal XS. I've attempted a couple times w/o airplane mode and couple times with airplane mode.
> 
> Also on 12.1.1b3?

Yes, forgot to add that.

**Comment by bdemmy** [comment]
Same here. Normal XS, 12.1.1b3.

**Comment by NatsuDzn** [comment]
I have the same issue with the XS Max runnin 12.1.1 b3

**Comment by WalshyDev** [comment]
Pwn just released a new update which should fix it - https://github.com/pwn20wndstuff/Undecimus/releases

**Comment by eskimo** [comment]
Fixed.
