### ISSUE TITLE
Device rebooting overnight - recurrent issue (iPhone6,2 - 12.1.2 [16C104]) (several logs attached)

### ISSUE THREAD

**Issue by UnderEu** [pwn20wndstuff/Undecimus#772]
**Describe the bug**
Even if the device and all my installed apps/tweaks work perfectly fine during the day, evey single night it reboots. That's a problem I've been issuing since 11.4.1 ( #382 ) and now, in 12.1.2, the same happens - the difference is it didn't bootloop. Yet.
My tweak list is exactly the same, my settings are exactly the same

**To Reproduce**
1. Leave the phone sit overnight. Tested when charging and not charging, tested with Airplane Mode ON and OFF, results are the same.

**Screenshots**
Does not apply

**Device (please complete the following information):**
 - iOS Version: 12.1.2 [16C104]
 - iOS Device: iPhone 5s (Global) - N53AP / iPhone6,2
 - unc0ver Version: 3.0.0b41, b42, b43, b46, b48

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
[unc0ver_diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2954365/unc0ver_diagnostics.plist.txt)
[unc0ver-diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968673/unc0ver-diagnostics.plist.txt)
[u0-b48-diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/3018318/u0-b48-diagnostics.plist.txt)
[panic-full-2019-03-09-025803.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968622/panic-full-2019-03-09-025803.ips.txt)
[panic-full-2019-03-09-030153.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968627/panic-full-2019-03-09-030153.ips.txt)
[panic-full-2019-03-10-082141.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968628/panic-full-2019-03-10-082141.ips.txt)
[panic-full-2019-03-11-191830.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968629/panic-full-2019-03-11-191830.ips.txt)
[panic-full-2019-03-12-135309.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968630/panic-full-2019-03-12-135309.ips.txt)
[panic-full-2019-03-16-205058.808.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2975576/panic-full-2019-03-16-205058.808.ips.txt)
[panic-full-2019-03-26-185521.ips.synced.txt](https://github.com/pwn20wndstuff/Undecimus/files/3018315/panic-full-2019-03-26-185521.ips.synced.txt)
[panic-full-2019-03-26-185920.ips.synced.txt](https://github.com/pwn20wndstuff/Undecimus/files/3018316/panic-full-2019-03-26-185920.ips.synced.txt)
[panic-full-2019-03-28-110206.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3018317/panic-full-2019-03-28-110206.ips.txt)

EDIT: Consolidated all panic-full and u0 diagnostics logs on the 1st thread - and provide new ones as they show up.

**Comment by UnderEu** [comment]
Add: Phone rebooted instead of powering-off completely during a test.

**Comment by mcn2004** [comment]
Same...

**Comment by mcn2004** [comment]
What is your tweak's list?

**Comment by UnderEu** [comment]
Additional log (System daemon one):
[searchd_CrashReporter.txt](https://github.com/pwn20wndstuff/Undecimus/files/2954768/searchd_CrashReporter.txt)

**Comment by UnderEu** [comment]
@mcn2004 

- 4GwantLTE
- Aerify
- Bloard
- CrashReporter
- Dune
- Eclipse 12
- FingerTouch
- FingerTouchReachabilityFix12
- iCleaner
- NiceNotes
- NoStatusWhatsApp
- NoVoiceMail
- SpringPlus11
- SugarCane
- SwipeSelection
- System Info
- WARemoveCameraTabBar
- WiFi Passwords
- WiFiScanner
- YouTube Tools

**Comment by mcn2004** [comment]
Check iCleaner, which was the repo that you have used to download icleaner?

**Comment by UnderEu** [comment]
@mcn2004 BigBoss

**Comment by mcn2004** [comment]
@UnderEu Delete iCleaner and install iCleaner Pro from https://ib-soft.net/cydia/ and run it.

**Comment by iSnowish** [comment]
Am trying to figure out the issue. 

I have the same issue. But mine is when I leave my phone charging at night. When i woke up everyday i find it unJailbroke or its stuck on a black secreen. So i have to reJailbreak it again.

**Comment by mcn2004** [comment]
I understand you. I went through that too. If you can, send me the list of your tweaks, and I will help you to fix it. I can fix my iPhone. In my case, the problems were iCleaner and HomeGesture, changing them to iCleaner Pro (from https://ib-soft.net/cydia/ ) and HomeGesture Lite.

**Comment by mcn2004** [comment]
@UnderEu Can you fix your issues??

**Comment by iSnowish** [comment]
@mcn2004
I have 2 phones witg the same issue and the common tweaks in both devices are

- ICleaner pro from the offical source 
- Colorbadges 
-  applist
- preferenceloader 
- cercube 
- flipconvert 
- ccsupport 

Igues its icleaner

**Comment by UnderEu** [comment]
New system daemon logs from CrashReporter:
[bluetoothd_CrashReporter.txt](https://github.com/pwn20wndstuff/Undecimus/files/2961423/bluetoothd_CrashReporter.txt)
[wirelessproxd_CrashReporter.txt](https://github.com/pwn20wndstuff/Undecimus/files/2961424/wirelessproxd_CrashReporter.txt)

**Comment by UnderEu** [comment]
Attaching latest **panic-full** reports:
[panic-full-2019-03-09-025803.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968622/panic-full-2019-03-09-025803.ips.txt)
[panic-full-2019-03-09-030153.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968627/panic-full-2019-03-09-030153.ips.txt)
[panic-full-2019-03-10-082141.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968628/panic-full-2019-03-10-082141.ips.txt)
[panic-full-2019-03-11-191830.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968629/panic-full-2019-03-11-191830.ips.txt)
[panic-full-2019-03-12-135309.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968630/panic-full-2019-03-12-135309.ips.txt)

**Comment by UnderEu** [comment]
Attaching SystemMemoryReset logs (not sure if useful but...): 
[SystemMemoryReset-2019-03-09-020200.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968649/SystemMemoryReset-2019-03-09-020200.ips.txt)
[SystemMemoryReset-2019-03-10-020024.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968650/SystemMemoryReset-2019-03-10-020024.ips.txt)
[SystemMemoryReset-2019-03-11-021339.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968651/SystemMemoryReset-2019-03-11-021339.ips.txt)
[SystemMemoryReset-2019-03-14-020003.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968652/SystemMemoryReset-2019-03-14-020003.ips.txt)

**Comment by UnderEu** [comment]
Latest unc0ver diagnostics log:
[unc0ver-diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2968673/unc0ver-diagnostics.plist.txt)

**Comment by mcn2004** [comment]
I study the logs, and I believe that is a monolithic kernel error, I try to change the allocated memory for the kernel and I saw a increament in the tweak loading but I didn't find the overnight reboot issue. I will stay looking for the error code.

**Comment by UnderEu** [comment]
New panic-full log: 
[panic-full-2019-03-16-205058.808.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2975576/panic-full-2019-03-16-205058.808.ips.txt)

Updated to 3.0.0-b46 last thursday (I think) and it didn't reboot overnight since then... until last night -> it rebooted while opening the camera from the lock screen.

**Comment by UnderEu** [comment]
> I study the logs, and I believe that is a monolithic kernel error or a substrate error, I try to change the allocated memory for the kernel and I saw a increament in the tweak loading but I didn't find the overnight reboot issue. I will be looking for the error code.

@mcn2004 Need any additional log to make your analysis?

**Comment by mcn2004** [comment]
Thanks, but I use my iphone's logs to study this issue. If i need your help, i will tell u
