### ISSUE TITLE
ARM64e

### ISSUE THREAD

**Issue by TouGBao** [pwn20wndstuff/Undecimus#775]
**Describe the bug**
JB-app  crashed when installed in device.

**Device (please complete the following information):**
ios12.1.1 bata3
iphone xs

**Logs**
/private/var/containers/Bundle/Application/34B83DCF-F1DD-4B40-94D8-B472BBC22303/Un.app/Frameworks/libUnDylib.dylib: arm64 dylibs cannot be loaded into arm64e processes

**Comment by WalshyDev** [comment]
Using latest version?

**Comment by TouGBao** [comment]
YES，bata 45

> Using latest version?

Yes,Bata 45

**Comment by TouGBao** [comment]
> Using latest version?

I have solved it,because my cydia impactor is not the latest version.😓
