### ISSUE TITLE
Failed to extract bootstrap

### ISSUE THREAD

**Issue by disappointedbra** [pwn20wndstuff/Undecimus#777]
Tried everything that some guys said but it still doesnt work iphone 5s ios 12.0

**Comment by Azrty** [comment]
Enable airplane mode

**Comment by disappointedbra** [comment]
@Azrty i had it on everytime i tried to jb

**Comment by Azrty** [comment]
Disable it ?

**Comment by Azrty** [comment]
Jailbreaking work for me: ios 12.0 iPad Air A7 Unc0ver 3.0.0 beta 43

**Comment by Azrty** [comment]
Oh I know:

Disable « enable tweaks » option
Enable airplane mode

It should work

**Comment by Azrty** [comment]
(It worked for me)

**Comment by MichaelHelmers** [comment]
@Azrty I'm getting the same error as OP.  Tried with tweaks enabled and disable with airplane on and off like you suggested but no luck.  Log looks like it's erroring out when trying to install openssl:

libssl1.0 conflicts with openssl (<< 1.0.2q)
openssl (version 1.0.2n) is present and installed
dpkg: error processing archive ...
conflicting packages - not installing libssl1.0

After reboot I tried running with reinstall openssh option on (tweaks off) but ended up with the same error.  I've tried a bunch of different configurations of options but it seems to always throw that error...

Any suggestions from anyone?

I'm wondering if it could be that I previously jailbroke using cydia impactor and eletra.

**Comment by JmTexas19** [comment]
Going to need more information since there are multiple variations of this error. Take a look at other duplicate issues already opened.
#694 
#699

**Comment by MichaelHelmers** [comment]
@JmTexas19 I tried what you suggested in #694 still getting the error.
Info:
Iphone 7 plus ios 11.3
Uncover Version 3.0.0~b46

Here's what happened when following the steps you suggested
1) When jailbreaking with RootFS on it reboots at step 20/37 
2) Jailbreaking again reboots at step 16/37 with a successful snapshot message
3) Jailbreaking again if fails on step 26/37 with the same error but different error message 
![IMG_2479](https://user-images.githubusercontent.com/20238520/54326660-26a1cf80-45d5-11e9-9bf1-3e786b71dd41.PNG)

I've tried that process a bunch of times now and each time it comes to the same point and fails, doesn't really matter what options I have (de)selected, tried with the various combinations of reinstall openssh, reinstall cydia and reload system daemons (de)selected.

I can provide the full log file if you think it's needed.

**Comment by JmTexas19** [comment]
I recommend you go ahead and post the full diagnostic file and hope someone more knowledgeable comes along and helps you. I don't know much about the inner workings of Undecimus but here are some things I would try.

If you have a faulty volume button, take a look at #699. 
Might be worth taking a look at older issues such as #290 or try using an older version of uncover since you are on 11.3 as most of the recent updates are focused on IOS12.

**Comment by mghajos** [comment]
@MichaelHelmers following @JmTexas19 hint with faulty volume button: i had my iPad in a not perfectly fitting cover -> volume button seemed to be pressed. jailbroke fine without cover :-)

Márton

**Comment by itstragicz** [comment]
> @MichaelHelmers following @JmTexas19 hint with faulty volume button: i had my iPad in a not perfectly fitting cover -> volume button seemed to be pressed. jailbroke fine without cover :-)
> 
> Márton

holy heck, this actually fixed it for me. im not gonna question it.
