### ISSUE TITLE
Cannot jailbreak anymore, b44 and b45

### ISSUE THREAD

**Issue by samtaborsky** [pwn20wndstuff/Undecimus#779]
**Describe the bug**
After an update to b44 and now to b45, I can not jailbreak anymore, even after downgrading to b43. I tried to jb with or without Reload System Daemons, not worked either. On b44, I had some issues, but after disabling Reload System Daemons, jailbreaking and then re-jailbreaking and enabling them, everything worked. No new tweaks installed for at least a week, so I do not think it is tweak related.

**To Reproduce**
Try jailbreaking with or without Reload System Daemons

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone SE
 - unc0ver Version: currently b45, but also b43 and b44

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
Log from unc0ver - https://pastebin.com/CPP9EW8F

**Comment by samtaborsky** [comment]
And FYI I never had a single issue with Reload System Daemons, yesterday was the first time and now I am trying to jailbreak with various settings combinations, unsuccessfully every single time.

**Comment by alshubaily007** [comment]
Good

**Comment by samtaborsky** [comment]
Restored RootFS once more, finally jailbroken with Load Tweaks turned off, reinstalled all the tweaks and removed some of them that I did not use much and hopefully it will now be stable.
