### ISSUE TITLE
IPHONE XR 12.1.1 BETA  STOP ON 20/37 USE B45

### ISSUE THREAD

**Issue by yf2015** [pwn20wndstuff/Undecimus#781]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
![微信图片_20190313094850](https://user-images.githubusercontent.com/43029654/54249086-e3664300-4579-11e9-8ab1-d699a4adc046.png)

**Comment by CMTFrostyy** [comment]
uh.. It says jailbreak completed. Literally no bugs here

**Comment by yf2015** [comment]
> 呃..它说越狱完成了。字面上没有错误

RUN 20/37 IS OK ?
