### ISSUE TITLE
Freezing of random apps 

### ISSUE THREAD

**Issue by desiwarrior** [pwn20wndstuff/Undecimus#784]
**Describe the bug**
Phone freezes while launching certain apps.. but rest of the apps work fine.. sometimes its Discord and Apollo... other times it’s another random app.. each time it's a different app... the only resolution is to reboot and rejailbreak ... App basically just stays on the loading screen for roughly 15/20 seconds and then crashes. This even happens after rootFS restore and no tweaks installed. 

**To Reproduce**
Happens randomly unfortunately and hence it's hard to reproduce. There are also many posts on reddit in regards to this. 

**Screenshots**
App basically just stays on the loading screen for roughly 15/20 seconds and then crashes.

**Device (please complete the following information):**
 - iOS 12.1.1 B3: 
 - iOS Device: IPX
 - unc0ver Version: B41

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by mikigal** [comment]
I have the same issue (the same iOS version and device), on Discord too. Try downgrade unc0ver to b38, I haven't this issue on this version.

**Comment by NinjaBG** [comment]
I’m also experiencing this bug. Device is iPhone X(10,6 Global) on iOS 12.0. The first week it wasn’t present. Viber started crashing last saturday(09.03), now Safari has joined the party. What can I do?

**Comment by mikigal** [comment]
> I’m also experiencing this bug. Device is iPhone X(10,6 Global) on iOS 12.0. The first week it wasn’t present. Viber started crashing last saturday(09.03), now Safari has joined the party. What can I do?

Downgrade unc0ver to b38. Read @up

**Comment by NinjaBG** [comment]
How?

**Comment by mikigal** [comment]
> How? Forgot to mention it started on b35

Ohh, for me b38 works.  Maybe try upgrade to this version. Simply remove your unc0ver app and install b38 with Cydia Impactor and rejailbreak

**Comment by NinjaBG** [comment]
Updated to b46, will report soon;)

**Comment by desiwarrior** [comment]
Glad to see that I'm not the only one with this issue. I just upgraded to b46...let's see how it goes...otherwise I'll go back to b29 where I never had this issue... hopefully pwn20wnd is aware of this issue.... even happens on a clean system after restore rootFS....

**Comment by desiwarrior** [comment]
> Updated to b46, will report soon;)

me too...fingers crossed... :)

**Comment by NinjaBG** [comment]
The issue appears to be fixed:)
