### ISSUE TITLE
Cydia Impactor Installation issue cpp 42

### ISSUE THREAD

**Issue by ProBlauw** [pwn20wndstuff/Undecimus#788]
Hello, every time I try to install an .ipa file I get this error message: file: installation.cpp; line: 42. 
I made sure my date and time are correct, tried other Apple-ID's without 2FA and rebooting and installing in airplane mode. Please help me! 

Thanks

**Comment by Cryptiiiic** [comment]
Issue with impactor/xcode/apple servers, not unc0ver releted, please only make issues related to unc0ver itself. Closing.

**Comment by frankrazzy** [comment]
This link helped me to install unc0ver without Cydia Impactor, iPhone 5s, 12.1.1 beta 3.
https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new
