### ISSUE TITLE
Respring loop b46

### ISSUE THREAD

**Issue by baobaoit** [pwn20wndstuff/Undecimus#791]
## Checklist
- [ ] I have a useful screenshot that shows the full log(After pressing the view log button) and will post it.
- [ ] I have exported my Diagnostics file immediately after jailbreak failed or succeeded and will post it.
- [x] I have checked other issues to make sure its not a duplicate issue.
- [x] I am using the latest unc0ver beta.
- [x] I have checked to see if my device and iOS version are supported.
- [x] I can accurately describe the issue in the description and maintain a descriptive but short title.
- [x] I will not have more than one issue actively open at once.
- [x] I will not be entitled, spam, or use ??? or !!!.
## Describe the bug
On b46, when I reboot my iPhone to the non-jailbreak stage, then if I have Reload System Daemons turn on and click Jailbreak button then my phone could get a respring loop.
Else if I turn it on after I had jailbroken my phone and clicked Re-jailbreak button then it would work.
## Device
- iOS Version: 12.1.1
- iOS Device: iPhone 8,1
- unc0ver Version: b46

**Comment by loweets** [comment]
I am also like this
so, I can only turn off this option.
