### ISSUE TITLE
here is to solve the problem with reinstalling uncover. 

### ISSUE THREAD

**Issue by Gabellll69** [pwn20wndstuff/Undecimus#794]
for the failed to verify 
https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new

**Comment by Kiaos** [comment]
Once I have jailbreak again how do i fix the uncover so it can be installed with impactor again. The reason this happened is I tried installing unc0ver ipa with filza after i deleted an old signed version of unc0ver then it broke everyhing. I have a jailbreak again but how do I fix this?

**Comment by baobaoit** [comment]
You can not use Filza for installing unc0ver because it can not create provisions.
