### ISSUE TITLE
Cydia is not installing after successful jailbreak.

### ISSUE THREAD

**Issue by bigpapanick** [pwn20wndstuff/Undecimus#795]
Cydia is not installing after successful jailbreak. 

I have Siri, find my iphone, and password disabled, also running in airplane mode when running the jailbreak. I've also tried reinstalling cydia and refresh icon cache. I am also unable to SSH because the connection is always refused. I have attached an image of my iphones info as well as a video of everything that happens. I am also unable to look or pull my logs.

![20190313_073557](https://user-images.githubusercontent.com/48544065/54334623-f2420980-45fc-11e9-8ee6-366337c7358c.jpg)

Youtube video link if video doesn't post on here.

https://www.youtube.com/watch?v=SnahZ1yYgVo

**Device (please complete the following information):**
 - iOS Version: 12.0
 - iOS Device: Verizon iPhone XS Max 256GB Gold
 - unc0ver Version: 3.0.0b46

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
Unable to access the logs.

**Comment by andrewlove1** [comment]
Cydia is not out for the iPhone XS Max yet. It's only a PARTIAL jailbreak. Wait for Pwn to update the jailbreak for Cydia support.

**Comment by bigpapanick** [comment]
@andrewlove1 makes sense now, thank you.

**Comment by Merculous** [comment]
I'd suggest closing this issue since this wont help them.
