### ISSUE TITLE
Please push the newest source.

### ISSUE THREAD

**Issue by swigger** [pwn20wndstuff/Undecimus#796]
I found that the Unresitrict.dylib binary is updated in this project.
But the source code of it at project MeridianJB is still old.

Please push the newest code to MeridianJB, thanks.

I have also fired an issue at project MeridianJB.

**Comment by SPTweaksiOS12** [comment]
Seriously? This is unc0ver jailbreak not meridian.

**Comment by jakeajames** [comment]
@SPTweaksiOS12 unrestrict is available on the Meridian fork of pwn20wnd, so he's not wrong. Unc0ver initially started as a Meridian fork (not the app, but jailbreakd, pspawn etc.), right now it isn't anymore but Unrestrict is still on the Meridian repo
