### ISSUE TITLE
How do I codesign *without* ldid

### ISSUE THREAD

**Issue by LIJI32** [pwn20wndstuff/Undecimus#798]
ldid is fragmented and broken, and tends to die with useless assertions effectively every time it's used (Please stop using this :(). I'd like a sign a newly compiled binary with codesign/jtool.

When trivially signing with `codesign -fs -` and these entitlements:

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">
	<dict>
		<key>platform-application</key>
		<true/>
		<key>com.apple.private.security.container-required</key>
		<false/>
	</dict>
</plist> 
```

I get:

```
kernel	AMFI: '/a.out' is adhoc signed.
kernel	AMFI: '/a.out': unsuitable CT policy 0 for this platform/device, rejecting signature.
kernel	AMFI: code signature validation failed.
```

What's the proper way to sign for this jailbreak?

**Comment by jakeajames** [comment]
just do:

    ldid -Sents.xml binary

If that causes issues like you said, explain what issues. We don't care whether you sign it successfully with weird tricks or not, we care whether ldid works or not.

**Comment by LIJI32** [comment]
Signing with the `ldid` copy provided with unc0ver dies with `ldid.cpp(1749): _assert(): errno=21`. Weirdly enough, creating a `.deb` package to force `dpkg` to sign it works, so it'd be helpful to know what `dpkg` uses. In any case, I'd like to know how to sign on binaries with `codesign` as I prefer to sign my binaries on my Mac and not locally on my iPhone.

**Comment by jakeajames** [comment]
Apparently using ents is broken, you'd have to use the original ldid how it's done by dpkg, the one in PATH is just a dummy so "ldid -S" works, at least, supposed to

**Comment by pwn20wndstuff** [comment]
Pinging @sbingner on this issue since he made the ldid wrapper.

**Comment by LIJI32** [comment]
Still relevant. It's *still* impossible to run executables without going through `dpkg`.

**Comment by jakeajames** [comment]
if you're on substrate:

ldid -K/usr/share/jailbreak/signcert.p12 -Sents /path/to/binary (path can't be /, for some reason that doesn't work, put it in a sub-directory like /usr/bin or something)

On substitute: it'll just work, no need to resign

**Comment by LIJI32** [comment]
Thanks, I'll give it a try and let you know if it worked.

**Comment by LIJI32** [comment]
Works perfectly, thanks!
