### ISSUE TITLE
Overnight reboot on b46 iPhone X 11.1.2 (panic-full attached)

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [pwn20wndstuff/Undecimus#800]
**Describe the bug**
Left device charging, found it in nonjb mode after wakeup

**To Reproduce**
0. Maybe important to mention: I jailbroke with "reload System daemons" off and did no ldrestart afterwards, as I get a respring loop when jailbreaking with it enabled
1. Leave device charging
2. wakeup to see in in nonjbmode
3. check for crashlog
4. Find one panic-full

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone X
 - unc0ver Version: b46

**Place an "x" between the brackets if true:**
 - [~] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
[panic-full-2019-03-14-073943.874.txt](https://github.com/pwn20wndstuff/Undecimus/files/2966498/panic-full-2019-03-14-073943.874.txt)
[panic-full-2019-03-14-073943.874 — копия.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2966515/panic-full-2019-03-14-073943.874.ips.txt)
[diagnostics.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2966505/diagnostics.plist.txt)

#764 #772 #749 #770

**Comment by MegaminxCode** [comment]
@Cryptiiiic  @pwn20wndstuff Ive seen this a couple of times on the discord.

**Comment by JSeredick** [comment]
After updating to beta 46 I had more issues with the stuck on spinning respring logo. This update didn't fix the stuck respring, it bought it back

**Comment by 13XxM1CHA3lxX37** [comment]
Update: No reboot this Night. Only one unrelated crashlog (_.wakeups_ressource) for some AppStore app tonight.

**Comment by LLRI** [comment]
Same issue here reboot **every** night when charging

Iphone 6
iOS 12.1.1 (beta3)
unc0ver Version: b46 (but same issue happened on older version too)

Error message according to attached log is: **_"eventReason" : "User reclaimable memory dropped below the limit. User reclaimable current: 54%. User reclaimable minimum: 55%",_**


[SystemMemoryReset-2019-03-15-020007.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2975280/SystemMemoryReset-2019-03-15-020007.ips.txt)

**Comment by thehappydinoa** [comment]
I also have the same issue.

iPhone 6
iOS 12.1.1 beta3
unc0ver Version: b46

**Comment by InFlamesHell** [comment]
I also have the same issue. 

iPhone 6
iOS 12.1.2
unc0ver Version: b46

**Comment by miki38501** [comment]
I also have the same issue.

iPhone 6s Plus
iOS 12.1.2
unc0ver Version: b46
