### ISSUE TITLE
Cellular and wifi connections do not actually work b46

### ISSUE THREAD

**Issue by sippinjuice** [pwn20wndstuff/Undecimus#802]
**Describe the bug**
Upon jailbreaking with beta46 with reload system daemons on, i cannot use cellular or wifi even though it says i am connected. 

**To Reproduce**
1. Go to unc0ver app
2. Click on jailbreak. wait for the respring and the device should be jailbroken, however wifi and cellular do not work.

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iphone X
 - unc0ver Version: b46

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by LuluBeaCreative** [comment]
Having the same connectivity issues as well on 12.1.1 b46 iPhone 8 Plus

**Comment by forzabatur** [comment]
Tweaklist?

**Comment by silentshotghost** [comment]
Got this issue once had to restore rootfs be sure to backup tweaks with any backup tweak it currently using BackupAZ

**Comment by sippinjuice** [comment]
7-zip (POSIX): 16.02-1
Activator: 1.9.13~beta4
AdBlock for YouTube: 1.0.7
AnimationsBeFast: 1.4.5
Aporeo: 2.3
AppList: 1.5.14
APT (apt-key): 1.4.8-3
APT 0.7 Transitional: 1:0-2
APT 1.4 Strict (libapt-pkg): 1.4.8-4
APT Command Line: 1:0-2
APT Strict (lib): 1.4.8-7
APT Strict: 1.4.8-3
Artworkify: 0.0~beta4
Assuan: 2.5.1-1
AutoUnlockX: 1.0.1
Barmoji: 1.3.2
Base Structure: 1-5
Bazzi: 2.0.0
Berkeley DB: 6.2.32-1
BetterCCXI: 1.4.8
BigBoss Icon Set: 1.0
Bourne-Again SHell: 4.4.23-2
bzip2: 1.0.6-1
CA Certs: 0.0.1-1
CallDismiss: 1.0.0~beta6
CarBridge: 1.0.4
CCModules: 1.3-3
CCSupport: 1.2-2
Cephei: 1.12
ClearBadges3DTouch10: 1.0.1
ColorFlow 4 (iOS 11 – 12): 1.2.2
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Crayola X: 0.0.1
Cydia Installer: 1.1.32~b12
Cydia Repo Icon: 2.3
Cydia Substrate: 0.9.7032
Cydia Translations: 1.1.32~b1
CySpring: 0.0.2
DarkKeysXII: 1.0.1
DarkMessages (iOS 10): 1.2.0-1
Darwin Tools: 1-6
Debian Packager: 1.18.25-10
Debian Utilities: 4.8.6-1
DetailedBatteryUsage: 1.1.1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DontKillMyMusic: 1.2.0
DoubleTapLock: 1.0.0
Eclipse 12 (iOS 12): 6.0.3-1
Essential: 0-1
FDots: 1.0.0-4
file: 5.35-2
Filza File Manager 64-bit: 3.6.5-12
Find Utilities: 4.6.0-1
Flame: 1.3
Flipswitch: 1.0.16~beta4
FloatyDock: 1.4.1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
GoodWiFi: 0.0~beta4
grep: 3.1-1
gzip: 1.9-1
hid-support: 1.3.1-1
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.7.2
IconSupport: 1.11.1
iOS Firmware: 12.1.1
iPhone Firmware (/sbin): 0-1
KarenLocalizer: 1.0.4
KarenPrefs: 1.4
KSBA: 1.3.5-1
LeaveMeAlone: 2.1.0
LetMeBlock: 0.0.4.2
libcolorpicker: 1.6-1
libCSColorPicker: 0.7.9
libidn2: 6.1.2-1
libnepeta: 0.1.0
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libSparkAppList: 1.0.1-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Melior [Public]: 1.0.8-1
MTerminal: 1.4-5
Nebula: 1.0.0-3
Nettle: 3.4-2
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NoCCGrabber12: 1.0
Noctis12: 1.3.2
NoLowPowerAutoLock [Public]: 0.0.2
NoMoreSmallApps [Public]: 0.0.2
NoSub (PalBreak w/ options): 1.3
Notifica: 0.1.10
OpenSSL 1.0 Libraries: 1.0.2q-1
p11-kit: 0.23.12-1
PhotoSize: 1.0
Pikabu Lite: 1.1.0
plutil: 0.1.0
PowerSelector (iOS 11 & 12): 1.1-7
PreferenceLoader: 2.2.4~alpha1
PreferenceOrganizer 2: 4.0.5
PrefixUI: 1.0-1+debug
Profile Directory: 0-1
readline: 7.0.5-2
RealCC: 1.0.1
RocketBootstrap: 1.0.7~beta2
Saw: 1.2.0
SCloudlife: 0.8a
sed: 4.5-1
shell-cmds: 118-8
Signing Certificate: 0.0.1
SmoothCursor: 1.1.2
Speed Intensifier: 10.1-1
Stygian: 0.5
Substrate Safe Mode: 0.9.6001.1
SwipeSelection: 1.5.2-1
System Info: 2.0.0-1
system-cmds: 790.30.1-2
TapController: 0.0.4
Tape Archive: 1.30-2
TapTapFlip: 1.4.2
TapVideoConfig: 0.0.4
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4~b3
tweakCompatible: 0.1.4
UHB - iOS 9/10/11/12 (Untrusted Hosts Blocker): 1.5.7
UIKit Tools: 1.1.13-5
Unc0ver Jailbreak Resources: 1.0~b6
unrar: 5.6.4-1
unzip: 6.0-1
WhatAboutThis: 1.1
XZ Utils: 5.2.4-4
YouTubed: 1.7.2-1
zip: 2.32-1
