### ISSUE TITLE
Audio Recorder In iMessage Crash

### ISSUE THREAD

**Issue by silentshotghost** [pwn20wndstuff/Undecimus#803]
**Describe the bug**
When you go in iMessage and try to record an audio message it crashes iMessage 

Many other users are getting this issue #691 #725 

**To Reproduce**
1. Go to iMessage
2. Click on Audio recorder
4. See the error in crash reporter or any other crash logging app

**Screenshots**
it's a crash so no screenshots

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: 3.0.0~b46

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/6fKqXv8y
 
https://pastebin.com/UbQBrkM4
 
https://pastebin.com/H2R1iL1p
 
https://pastebin.com/6VzQ9efs

https://pastebin.com/K54TQhKc

**Comment by kehawaxec** [comment]
same here

**Comment by dodovar** [comment]
iPhone X 12.1.2 same problem

**Comment by medolero** [comment]
#604 same issue

**Comment by tehuno** [comment]
same

**Comment by justsandro** [comment]
same issue

**Comment by jasonv69** [comment]
Install VoiceMSGfix in cydia, problem
Solved until an update fixing this gets released.
