### ISSUE TITLE
Remove Cydia-gui/icon

### ISSUE THREAD

**Issue by matbrik** [pwn20wndstuff/Undecimus#804]
How can I modify JailbreakViewController.m in order to not install the gui of cydia?
I'm interested only in substrate and its dependencies

**Comment by matbrik** [comment]
I removed cydia and cydia-lproj from here https://github.com/pwn20wndstuff/Undecimus/blob/30cfc5cb71a9dcb95406ef14e3e51481767ac434/Undecimus/source/JailbreakViewController.m#L1399

I set this to NO https://github.com/pwn20wndstuff/Undecimus/blob/30cfc5cb71a9dcb95406ef14e3e51481767ac434/Undecimus/source/JailbreakViewController.m#L1547

I forced uncover to enter in these ifs https://github.com/pwn20wndstuff/Undecimus/blob/30cfc5cb71a9dcb95406ef14e3e51481767ac434/Undecimus/source/JailbreakViewController.m#L1660

I set prefs.installcydia to false https://github.com/pwn20wndstuff/Undecimus/blob/30cfc5cb71a9dcb95406ef14e3e51481767ac434/Undecimus/source/JailbreakViewController.m#L1728

but it seems that cydia get installed and continues to work anyway if I tap on the icon

Am I missing something?

**Comment by Meowcat285** [comment]
You could run "Restore RootFS" if thats what I think you mean.
