### ISSUE TITLE
Unc0ver won't open when installed on Ignition app

### ISSUE THREAD

**Issue by AhrimanSefid** [pwn20wndstuff/Undecimus#806]
hi & thank you
me install Undecimus-v3.0.0-b46 in Ignition app but not run cydia.
ios 12.0.1
iPhone 8+

**Comment by hovikgas** [comment]
Why was this issue closed? I’m having issues installing 3.1.2 through ignition... it loads, but once it switches to installing, it just stops and the app remains greyed out...
