### ISSUE TITLE
unc0ver help .46

### ISSUE THREAD

**Issue by AhrimanSefid** [pwn20wndstuff/Undecimus#807]
hi all
can help me fixed
_http://i63.tinypic.com/4kk1mb.jpg
not work force reboot.
can help me ...............

ios 12.0.1
iPhone 8+

**Comment by MegaminxCode** [comment]
Turn off load tweaks and jailbreak. delete the most recent tweak in Cydia. Turn off and on the phone.
Turn load tweaks back on and jailbreak

**Comment by MegaminxCode** [comment]
@AhrimanSefid

**Comment by AhrimanSefid** [comment]
not work shutdown or force reboot

**Comment by Timeraa** [comment]
Did you update Unc0ver? And since then you have these issues? If so enable **Restore RootFS**, re-jailbreak then jailbreak without it. If it still doesn't work disable **Reload System Daemons** (I had to disable it in order to get into a jailbroken state on the new beta)

**Comment by marcnhl15** [comment]
Hi, hi have the same problem on my iphone xs on ios 12.0 , i dont see OTA update in my settings for delete... so how i can fix this problem?

**Comment by XHINNEXD** [comment]
@Timerra

Thanks for the tutorial. Its worke for me the enable rootfs
