### ISSUE TITLE
Beta 46 device freezes when I turn it on in the morning 

### ISSUE THREAD

**Issue by A13X23** [pwn20wndstuff/Undecimus#808]
Sometimes when I turn on my device in the morning, it’s just frozen with the time and status bar being hidden and only the notification banners showing, and the brightness is all the way down. It stays frozen until a reboot also, and it looks like it freezes right as I turn it on, because i checked the other day(as in lifted up the phone but didn’t let raise to wake turn it on yet) and the screen was still off, but when I brought it up and it turned on with raise to wake it froze. I had the issue, then downgraded to beta 36, then it stopped but recently updated again and now it’s back. Great job on the great work! Unc0ver is amazing!

**Comment by youknowdavibes** [comment]
> Sometimes when I turn on my device in the morning, it’s just frozen with the time and status bar being hidden and only the notification banners showing, and the brightness is all the way down. It stays frozen until a reboot also, and it looks like it freezes right as I turn it on, because i checked the other day(as in lifted up the phone but didn’t let raise to wake turn it on yet) and the screen was still off, but when I brought it up and it turned on with raise to wake it froze. I had the issue, then downgraded to beta 36, then it stopped but recently updated again and now it’s back. Great job on the great work! Unc0ver is amazing!

I'm having that issue too, it's really annoying and I hope @pwn20wndstuff fixes it in a future update, I'm going to downgrade to b45 because that was stable.
