### ISSUE TITLE
IOS 12.1.1~b3 with Unc0ver~b46 resprings randomly!

### ISSUE THREAD

**Issue by youknowdavibes** [pwn20wndstuff/Undecimus#810]
Hey all,

So I’m having an issue with my iPhone 8, jailbroken on beta 46 with iOS 12.1.1 beta 3. 

The issue is when I go to launch an app sometimes (mainly the camera & ignition), my phone will respring. All my tweaks are optimized for IOS 12 and are installed from safe sources. I’ve tried removing some but to no luck. If anyone can advise me on a good troubleshooting method, that would we be amazing. Thanks to Pwn20wnd for this JB and I hope I can find a soloution :)

**Comment by youknowdavibes** [comment]
(Side note), I’m pretty new to this so I’m gonna ask this probably stupid question, I have SHSH blobs saved for 12.1.2, would it be better if I were to upgrade? This is more a question than an addition but just seeing if this could be a soloution

**Comment by johngrov** [comment]
post your tweak list, others have been having the same issue and we can help narrow it down if we have tweak lists

**Comment by youknowdavibes** [comment]
https://imgur.com/gallery/oNysNx1

^^ Tweak List

Also I have other issues, every morning when I wake up and unplug my phone, it freezes and I have to rejailbreak. SpringBoard also crashes a lot so idk. I also can’t jailbreak or rejailbreak without turning off Reload Daemons.

**Comment by youknowdavibes** [comment]
@johngrov I’ve uninstalled MANY tweaks, like most of them. Springboard, CallBar XS, and other things. I’ve cleared out my repos so I hope I can fix this

**Comment by johngrov** [comment]
> @johngrov I’ve uninstalled MANY tweaks, like most of them. Springboard, CallBar XS, and other things. I’ve cleared out my repos so I hope I can fix this

both xenhtml and lockanim have been implicated over and over in instability/resprings, id try those next

**Comment by youknowdavibes** [comment]
@johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later

**Comment by johngrov** [comment]
> @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later

haha right, it be like the sometimes 

hope that fixes it for you, let me know. godspeed

**Comment by youknowdavibes** [comment]
> > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> 
> haha right, it be like that sometimes
> 
> hope that fixes it for you, let me know. godspeed

:) Thanks man, you have a good one.

**Comment by youknowdavibes** [comment]
> > > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> > 
> > 
> > haha right, it be like that sometimes
> > hope that fixes it for you, let me know. godspeed
> 
> :) Thanks man, you have a good one.

Also I hate to ask but can you answer my question after my original? Would it be better to update to a stable 12.1.2?

**Comment by johngrov** [comment]
> > > > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> > > 
> > > 
> > > haha right, it be like that sometimes
> > > hope that fixes it for you, let me know. godspeed
> > 
> > 
> > :) Thanks man, you have a good one.
> 
> Also I hate to ask but can you answer my question after my original? Would it be better to update to a stable 12.1.2?

im no expert in this area but id assume there would be no/minimal differences between versions and almsot certainly would not solve our random respring/jailbreak instability issues... those are more likely unc0ver or tweak related. just my 2 cents tho id yield to the pros

**Comment by youknowdavibes** [comment]
> > > > > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> > > > 
> > > > 
> > > > haha right, it be like that sometimes
> > > > hope that fixes it for you, let me know. godspeed
> > > 
> > > 
> > > :) Thanks man, you have a good one.
> > 
> > 
> > Also I hate to ask but can you answer my question after my original? Would it be better to update to a stable 12.1.2?
> 
> im no expert in this area but id assume there would be no/minimal differences between versions and almsot certainly would not solve our random respring/jailbreak instability issues... those are more likely unc0ver or tweak related. just my 2 cents tho id yield to the pros

@johngrov I'm about to kill someone 😂. Just rebooted into safe mode, said SpringBoard crashed. What should I do now?

**Comment by johngrov** [comment]
> > > > > > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> > > > > 
> > > > > 
> > > > > haha right, it be like that sometimes
> > > > > hope that fixes it for you, let me know. godspeed
> > > > 
> > > > 
> > > > ![:)](https://static-cdn.jtvnw.net/jtv_user_pictures/chansub-global-emoticon-ebf60cd72f7aa600-24x18.png) Thanks man, you have a good one.
> > > 
> > > 
> > > Also I hate to ask but can you answer my question after my original? Would it be better to update to a stable 12.1.2?
> > 
> > 
> > im no expert in this area but id assume there would be no/minimal differences between versions and almsot certainly would not solve our random respring/jailbreak instability issues... those are more likely unc0ver or tweak related. just my 2 cents tho id yield to the pros
> 
> @johngrov I'm about to kill someone 😂. Just rebooted into safe mode, said SpringBoard crashed. What should I do now?

thats safe mode, in the top left you should hit exit and a menu should open with one of the options being "restart"

that triggered after having uninstalled xenhtml and lockanim?

**Comment by youknowdavibes** [comment]
> > > > > > > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> > > > > > 
> > > > > > 
> > > > > > haha right, it be like that sometimes
> > > > > > hope that fixes it for you, let me know. godspeed
> > > > > 
> > > > > 
> > > > > ![:)](https://camo.githubusercontent.com/a60fd8395d54b536b849a9c4dd3d76b013f9081c/68747470733a2f2f7374617469632d63646e2e6a74766e772e6e65742f6a74765f757365725f70696374757265732f6368616e7375622d676c6f62616c2d656d6f7469636f6e2d656266363063643732663761613630302d32347831382e706e67) Thanks man, you have a good one.
> > > > 
> > > > 
> > > > Also I hate to ask but can you answer my question after my original? Would it be better to update to a stable 12.1.2?
> > > 
> > > 
> > > im no expert in this area but id assume there would be no/minimal differences between versions and almsot certainly would not solve our random respring/jailbreak instability issues... those are more likely unc0ver or tweak related. just my 2 cents tho id yield to the pros
> > 
> > 
> > @johngrov I'm about to kill someone 😂. Just rebooted into safe mode, said SpringBoard crashed. What should I do now?
> 
> thats safe mode, in the top left you should hit exit and a menu should open with one of the options being "restart"
> 
> that triggered after having uninstalled xenhtml and lockanim?

Yes I deleted XenHTML and LockAnim, and I did restart it but it's annoying that it keeps on crashing, also, here is another issue I'm having described amazingly by another person

>Sometimes when I turn on my device in the morning, it’s just frozen with the time and status bar being hidden and only the notification banners showing, and the brightness is all the way down. It stays frozen until a reboot also, and it looks like it freezes right as I turn it on, because i checked the other day(as in lifted up the phone but didn’t let raise to wake turn it on yet) and the screen was still off, but when I brought it up and it turned on with raise to wake it froze. I had the issue, then downgraded to beta 36, then it stopped but recently updated again and now it’s back. Great job on the great work! Unc0ver is amazing!

**Comment by johngrov** [comment]
> > > > > > > > @johngrov Lol ofc two of my fav tweaks... I’ll uninstall and follow up later
> > > > > > > 
> > > > > > > 
> > > > > > > haha right, it be like that sometimes
> > > > > > > hope that fixes it for you, let me know. godspeed
> > > > > > 
> > > > > > 
> > > > > > ![:)](https://camo.githubusercontent.com/a60fd8395d54b536b849a9c4dd3d76b013f9081c/68747470733a2f2f7374617469632d63646e2e6a74766e772e6e65742f6a74765f757365725f70696374757265732f6368616e7375622d676c6f62616c2d656d6f7469636f6e2d656266363063643732663761613630302d32347831382e706e67) Thanks man, you have a good one.
> > > > > 
> > > > > 
> > > > > Also I hate to ask but can you answer my question after my original? Would it be better to update to a stable 12.1.2?
> > > > 
> > > > 
> > > > im no expert in this area but id assume there would be no/minimal differences between versions and almsot certainly would not solve our random respring/jailbreak instability issues... those are more likely unc0ver or tweak related. just my 2 cents tho id yield to the pros
> > > 
> > > 
> > > @johngrov I'm about to kill someone 😂. Just rebooted into safe mode, said SpringBoard crashed. What should I do now?
> > 
> > 
> > thats safe mode, in the top left you should hit exit and a menu should open with one of the options being "restart"
> > that triggered after having uninstalled xenhtml and lockanim?
> 
> Yes I deleted XenHTML and LockAnim, and I did restart it but it's annoying that it keeps on crashing, also, here is another issue I'm having described amazingly by another person
> 
> > Sometimes when I turn on my device in the morning, it’s just frozen with the time and status bar being hidden and only the notification banners showing, and the brightness is all the way down. It stays frozen until a reboot also, and it looks like it freezes right as I turn it on, because i checked the other day(as in lifted up the phone but didn’t let raise to wake turn it on yet) and the screen was still off, but when I brought it up and it turned on with raise to wake it froze. I had the issue, then downgraded to beta 36, then it stopped but recently updated again and now it’s back. Great job on the great work! Unc0ver is amazing!

hmm i dont have notifica, xeninfo, or alkaline of your tweaks

as far as the morning freezes, ive been having those too, and so have people on reddit. they have suggested opening icleaner pro, hitting + in bottom left, launch daemons, and toggling off the log dump crash reports option. also installing cappd from depkgs repo (dpkg9510.github.io/) has helped me so far

**Comment by youknowdavibes** [comment]
@johngrov let me do all of those things and tomorrow I will see if it works, your the best man thanks a ton!

**Comment by johngrov** [comment]
> @johngrov let me do all of those things and tomorrow I will see if it works, your the best man thanks a ton!

no worries bro im trying to figure it out myself! this jailbreak is so close to being perfect for me, if we can just fix these few issues

**Comment by youknowdavibes** [comment]
> > @johngrov let me do all of those things and tomorrow I will see if it works, your the best man thanks a ton!
> 
> no worries bro im trying to figure it out myself! this jailbreak is so close to being perfect for me, if we can just fix these few issues

For sure, just cleaned up using icleaner with those settings, now installing Cappd

**Comment by youknowdavibes** [comment]
@johngrov Also, you have a discord? Ik this isn't the place to ask but I hate this interface for github since they don't have a phone app :)

**Comment by johngrov** [comment]
> @johngrov let me do all of those things and tomorrow I will see if it works, your the best man thanks a ton!

dont use discord much tbh but i think my tag is Blueface#0062

**Comment by youknowdavibes** [comment]
> > @johngrov let me do all of those things and tomorrow I will see if it works, your the best man thanks a ton!
> 
> dont use discord much tbh but i think my tag is Blueface#0062

jesus christ, it happened again :((((. It froze while unlocking. Beta 45 here I come!

**Comment by johngrov** [comment]
> > > @johngrov let me do all of those things and tomorrow I will see if it works, your the best man thanks a ton!
> > 
> > 
> > dont use discord much tbh but i think my tag is Blueface#0062
> 
> jesus christ, it happened again :((((. It froze while unlocking. Beta 45 here I come!

damn bro that sucks wish i could help, cylinder might be another culprit to look into

you should also look into getting cr4shed to help identify your culprit

**Comment by youknowdavibes** [comment]
@johngrov repo?

**Comment by johngrov** [comment]
> @johngrov repo?

cr4shed is in packix

also these are my tweaks, i had the freezing and respringing problem like you but ive been going on ~1 day with none of either. might help to see where we differ and problem solve

animationsbefast

app admin

app list

autounlockx

barmoji

batterypercentx

blackout

crashreporter

customizemydock

deluminator

eclipse dark mode ios 12

filza

icleaner pro

laetus

letmeblock

libbulletin

libcscolorpicker

librocket

libsparkapplist

melior

nebula

neonboard

power selector

pull to respring

rocket for ig

safari plus

signing certificate

sleepytime

substrate

safe mode

swipeformore

uikit tools

u0 jb resources

youtube tools

**Comment by youknowdavibes** [comment]
Ima start fresh lol, let me find out how to do that and ill brb

**Comment by johngrov** [comment]
> Ima start fresh lol, let me find out how to do that and ill brb

toggling on "restore rootfs" and rejailbreaking will start fresh but **youll lose all your tweaks**, hence "starting fresh"

**Comment by youknowdavibes** [comment]
> > Ima start fresh lol, let me find out how to do that and ill brb
> 
> toggling on "restore rootfs" and rejailbreaking will start fresh but **youll lose all your tweaks**, hence "starting fresh"

Is it normal that I have to turn off reload daemons?

**Comment by youknowdavibes** [comment]
@johngrov ^^, if I don't it crashes then restarts my phone
