### ISSUE TITLE
Unc0ver b46 Freeze On Ramdom App 

### ISSUE THREAD

**Issue by StigiTT** [pwn20wndstuff/Undecimus#813]
Hello
My IPhone SE IOS 12.1.1 b3 unc0ver b 46  freeze on ramdom apps but more specifically in cydia

**Comment by JSeredick** [comment]
I have this issue still too. For me it's almost always after using control center (with no cc tweaks). Often if I open calculator from cc I cannot use the app until I lock and unlock my device. I was also having another issue where my apps would not open, I just rejailbroke my device and they seemed to work, you can also try 3D touching the app and opening one of the options in the drop down. However they continue to close my issues when I post this issue so good luck getting a fix

**Comment by StigiTT** [comment]
I'm not all you've done like you basically I'm going to cydia it works very well and sometimes during my navigation in cydia my iphone freeze and so I'm forced to restart it

**Comment by johngrov** [comment]
> I have this issue still too. For me it's almost always after using control center (with no cc tweaks). Often if I open calculator from cc I cannot use the app until I lock and unlock my device. I was also having another issue where my apps would not open, I just rejailbroke my device and they seemed to work, you can also try 3D touching the app and opening one of the options in the drop down. However they continue to close my issues when I post this issue so good luck getting a fix

was having this same issue w the cc/calculator and narrowed it down to batterypercentx. could you post your tweak list so we can compare?
