### ISSUE TITLE
Random Resprings on b46 iPhone X 12.1

### ISSUE THREAD

**Issue by johngrov** [pwn20wndstuff/Undecimus#814]
**Describe the bug**
About every day or so I've been having random resprings for a while now, pretty much ever since b40. From another post on here I gathered that batterypercentx was the cause of resprings (particularly when invoking calculator from control center) and have since uninstalled that - I will update if it fixes in the future.

I can post crash logs in the future but recently I downloaded Cappd and toggled off the crash logs daemon in iCleaner, as I heard that this might help the situation, so I would have to turn it back on and wait for the (random) respring and/or freeze to happen again.

My tweaks are: 

animationsbefast

app admin

app list

autounlockx

barmoji

batterypercentx

blackout

crashreporter

customizemydock

deluminator

eclipse dark mode ios 12

filza

icleaner pro

laetus

letmeblock

libbulletin

libcscolorpicker

librocket

libsparkapplist

melior

nebula

neonboard

power selector

pull to respring

rocket for ig

safari plus

signing certificate

sleepytime

substrate

safe mode

swipeformore

uikit tools

u0 jb resources

youtube tools

Any help is greatly appreciated!

**To Reproduce**

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone X
 - unc0ver Version: b46

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by alessio-zamparelli** [comment]
same

**Comment by lancerevodrifter** [comment]
I have the same issue, but I have significantly less tweaks installed since I kept thinking it was something with the tweaks, the following is what I have on mine
- AdBlock for Youtube
- Aperturize
- Applist
- Barmoji
- BatteryPercentX
- ByeVSD
- CarrierCrack - T-Mobile USA
- Cercube for Youtube
- CommCenter patch 
- CrashReporter
- Filza File Manager
- HideBarX
- iCleaner Pro
- LetMeBlock
- Liberty Lite (might get rid of this since I don't have anything to use it on)
- Mega UHB
- Melior
- RealCC
- ReProvison
- Rocket for Instagram
- UHB
-WhatAboutThis
-Wifi Passwords

But my resprings happen at random times, but primarily when I play music and I want to go to home screen or task switcher.

**Comment by johngrov** [comment]
> I have the same issue, but I have significantly less tweaks installed since I kept thinking it was something with the tweaks, the following is what I have on mine
> 
> * AdBlock for Youtube
> * Aperturize
> * Applist
> * Barmoji
> * BatteryPercentX
> * ByeVSD
> * CarrierCrack - T-Mobile USA
> * Cercube for Youtube
> * CommCenter patch
> * CrashReporter
> * Filza File Manager
> * HideBarX
> * iCleaner Pro
> * LetMeBlock
> * Liberty Lite (might get rid of this since I don't have anything to use it on)
> * Mega UHB
> * Melior
> * RealCC
> * ReProvison
> * Rocket for Instagram
> * UHB
> * WhatAboutThis
> * Wifi Passwords
> 
> But my resprings happen at random times, but primarily when I play music and I want to go to home screen or task switcher.

sounds exactly my issue, i uninstalled batterypercentx and things have been flawless ever since

try to invoke the calculator by going through the control center from pulling down on the space to the right of the notch, then dismissing calculator. this caused a respring every time without fail for me and i narrowed it down to batterypercentx

**Comment by johngrov** [comment]
> same

post your tweaks. this appears to be tweak related, many over on /r/jailbreak are noticing the same thing.

could someone who knows sparkdev get in contact with him and let him know of the issue?

**Comment by lancerevodrifter** [comment]
I uninstalled BatteryPercentX and I haven’t had the issue since, So I can assume its only that one particular tweak thats causing the issue.

**Comment by johngrov** [comment]
> I uninstalled BatteryPercentX and I haven’t had the issue since, So I can assume its only that one particular tweak thats causing the issue.

[the dev is aware of the bug](https://twitter.com/SparkDev_/status/1108737753334853632)
