### ISSUE TITLE
Freeze (for ~5min) when waking my device [b46]

### ISSUE THREAD

**Issue by PcmciaKai** [pwn20wndstuff/Undecimus#817]
Upon waking my iPad Air (1) on iOS 12.1.1 the screen turns on and I see the notifications but then I can't interact with the device. The screen turns off again but after about 5 minutes I can enter my screen lock pin and I can use the device just fine.
This issue occured on b41 and is still present on b46. Anyone else?

**Comment by CoolPersonMaam** [comment]
Turn on increase memory limit this may help and also you didn’t use proper template and lastly provide more info like logs so I can help u. Also, does this occur only when you are jailbreakjjg?

**Comment by PcmciaKai** [comment]
Re-jailbreaking with the memory limit increased really seemed to do something, at least reduce the issue by a lot. This morning it happened again but I was too sleepy to save the log.
I'll provide it whenever it happens again, sorry for not doing this in the first place. Thanks for the help so far! :)

**Comment by PcmciaKai** [comment]
It seems to be fine now when unlocking my device within ~idk 30min of it locking, but trying to unlock after a longer period resulted again in a freeze. When it happened I saved the diagnostics.plist file. However I kinda don't think that this is logging freezes/resprings, at least after having a quick look at the file. Maybe it will prove helpful, anyways. 

[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/3005515/diagnostics.zip)
