### ISSUE TITLE
iPad 11" supported?

### ISSUE THREAD

**Issue by Me1sterLampe** [pwn20wndstuff/Undecimus#818]
Hello everybody

First of all, thank you very much for your precious work. You hard working guys are awesome. 

Cydia does not appear after "successful jailbreak" on my iPad 11". If I got the other issues right the following message means that unc0ver did not get root access yet:
canOpenURL: failed for URL: "Cydia://" - error: "This app is not allowed to query for scheme cydia"

Oddly, it sais "successfully Jailbreaked". Can anybody tell me where I can find the supported devices?

Cheerio

Me1sterLampe

**Comment by reiazevedo** [comment]
A12 devices (New iPad Pro, iPhones XR/XS/XS Max) aren't supported yet.

**Comment by Me1sterLampe** [comment]
Anyway I can help? Need logs? Where can I donate a coffee?
