### ISSUE TITLE
iPhoneX on 11.3.1 issues

### ISSUE THREAD

**Issue by syhreality** [pwn20wndstuff/Undecimus#82]
I’m running into a continual problem that was also present in Electra using this combo of device+iOS, and others are having similar issues after looking at reddit.

Device works wonderfully after a fresh reboot+jailbreak using unc0ver. Amazing speed, pretty much bliss.

After an extended period of times (usually >24hrs), something causing multitasking to completely break. Switching between applications leaves them in a hung state, the user must kill the app and reopen it for it to load successfully.

At the time this occurs, if the user attempts to take a photo with the camera app, the app will crash and no photo will save. As discussed on reddit, I had this camera issue on Electra too but in that case it would completely freeze out the phone requiring a hard reset. Unc0ver merely leads to the app crashing which is a better situation at least.

Any ideas what may be causing this? It’s occurred on both Electra and unc0ver with/without tweaks installed.

**Comment by Samgisaninja** [comment]
So, this is strange to me considering that I have an iPhone X 11.3.1 as my personal device and I've never had this issue, and I'm concerned this may be modified/missing system files, and that your APFS snapshot doesn't have them. 

Does this issue ever happen while you're jailed, have you ever done any "stop this daemon" or other tutorials with Filza, etc? Trying to reproduce this.

**Comment by syhreality** [comment]
I did the original videosubscriptionsd rename previously on Electra to try and alleviate the issue with no success. I also installed jetslammed and set the jetsam limit at 55% I believe; unsure if either of these would have been reverted during the rollectra process. No other daemons we’re stopped/disabled prior to running rollectra.

After some playing around, I can get the camera to function correctly if I kill the xpcproxy process through CocoaTop. App switching seems to improve a little but still feels buggy with need to constant kill and app and restart it. I just noticed that the phone had 3 instances of xpcproxy running once it started crashing on taking photos; unsure if this is abnormal.

Are there any diagnostics that could be dumped when my phone is in the bugged state to try and assist you in replicating/resolving the issue?

**Comment by Cryptiiiic** [comment]
@syhreality If it happened on electra as well, this seems like and issue xpc issue if unc0ver has the same bug or you messed with the same files on both.

**Comment by palmzz** [comment]
I could affirm that sometimes apps misbehave with Uncover. Never experience such before with Electra.

**Comment by Cryptiiiic** [comment]
@syhreality Closing if you don't respond. @palmzz Does this still occur for you?
