### ISSUE TITLE
Crashing to Safemode - even with tweaks disabled

### ISSUE THREAD

**Issue by DaddyBoard** [pwn20wndstuff/Undecimus#822]
**Describe the bug**
iPhone X iOS 12.1.2 - Normal system actions such as swiping up to go home or bring up app switcher. Rotating screen, etc.

**To Reproduce**
Happens randomly but same as above

**Screenshots**
https://pastebin.com/HmrSJQxK

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone X
 - unc0ver Version: b46 latest

**Place an "x" between the brackets if true:**
 - [?] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [?] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/HmrSJQxK

**Comment by mendel3** [comment]
Probably a tweak issue
