### ISSUE TITLE
iPhone XS Max failed to jailbreak

### ISSUE THREAD

**Issue by flhang** [pwn20wndstuff/Undecimus#823]
iPhone XS Max failed to jailbreak!
At first, everything seems work fine. it shows "jailbreak completed!".But after the app exited, there is not cydia! I restart the app, it shows "Re-Jailbreakl".  I tried serveral times, it still the same. Please help!

**Comment by xxHoBoZxx** [comment]
Cydia is not ready for A12 devices yet.

**Comment by azizzzz2010** [comment]
😩😩😩

**Comment by HonoringBills** [comment]
Keep me posted on if or when they fix this please! Or any other way arounds, thanks!
