### ISSUE TITLE
Random Resprings when playing music/in general

### ISSUE THREAD

**Issue by lancerevodrifter** [pwn20wndstuff/Undecimus#826]
**Describe the bug**
So random times of the day, when I use my iPhone (in the car, or at home), when invoking the guesture to go to multitask or just to go to the home screen, my device would respring and go into safe mode, going into crashreporter does not show what had caused the issue other than (EXC_BAD_ACCESS), this respring would sometimes be triggered by playing music, but sometimes would have no prerequisite to cause this respring. Not sure if this is a problem with a tweak that is known for or what. The following is what I have currently installed

- AdBlock for Youtube
- Aperturize
- Applist
- Barmoji
- BatteryPercentX
- ByeVSD
- CarrierCrack - T-Mobile USA
- Cercube for Youtube
- CommCenter patch
- CrashReporter
- Filza File Manager
- HideBarX
- iCleaner Pro
- LetMeBlock
- Liberty Lite (might get rid of this since I don't have anything to use it on)
- Mega UHB
- Melior
- RealCC
- ReProvison
- Rocket for Instagram
- UHB
- WhatAboutThis
- Wifi Passwords
 
**To Reproduce**
1. Swipe Up to Home or multitask 

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: 3.0.0~b46

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

[SpringBoard CrashLog 3-20-2019.docx](https://github.com/pwn20wndstuff/Undecimus/files/2990214/SpringBoard.CrashLog.3-20-2019.docx)

**Comment by johngrov** [comment]
try uninstalling batterypercentx, worked for me and many other users

type "batterypercentx" in the searchbar on reddit.com/r/jailbreak and youll see a recent trend

**Comment by JSeredick** [comment]
I don't have batterypercentx and I get these random resprings too

**Comment by johngrov** [comment]
Post your tweaks @jseredick

**Comment by JSeredick** [comment]
> Post your tweaks @JSeredick

This problem he is having doesn't bother me as much as it doesn't happen as frequent what bothers me is an issue I have posted where my control center makes me lose app interaction, I have no control center tweaks, I could list out my tweaks but I have quite a few so give me a sec and I can

**Comment by JSeredick** [comment]
- Adblock for youtube
- Aetify
- AlbumHider (photos app)
- Barmoji
- BetterSettomgs
- CircleIcons
- CleanHomeScreen
- ClearBadges3DTouch10
- Cylinder
- Deletecut
- DismissProgress
- DLEasy
- Eclipse 12
- FiveIconDockXI
- HapticKeyboard
- HidebarX
- KeyboardColorXII
- Lockpluspro
- Notifica
- PreferenceOrganizer 2
- Pulltorespring
- RomanPasscode
- SCAdBlock
- SmallSiri
- Snowboard
- TweakConfigurator
- Wallmart
- WeatherVane
- XenHTML
- YouTubed
This crash happens for me as well if I use soundcloud, spotify and youtube, not super frequently but commonly in my car as well  when connected to my aux.

**Comment by johngrov** [comment]
None of those jump out at me as causing resprings except I’ve heard of people having problems w xenhtml.

Also for what it’s worth, I hadn’t had any resprings in a while until I installed Wallmart and lockdock so it’s possible that one of them is causing it, prob Wallmart as it’s old @jseredick

**Comment by JSeredick** [comment]
Yeah I did have issues with wallmart at some point but I found out I had a cycle setting enabled to change every 5 seconds or something. I don't know when I changed it but it was crashing my device, Since using just the on unlock change I haven't had issues caused from it. @johngrov but hey if you see any issues with tweaks making the control center cause issues lmk lol. Because I have posted an issue on it 3 times now and each time it's been closed and the issue persists. As you can see from my tweak list nothing should affect control center, however somehow every time I use it I can't interact with apps until I lock and unlock my device and it's super annoying
