### ISSUE TITLE
Helloooo

### ISSUE THREAD

**Issue by Niview** [pwn20wndstuff/Undecimus#828]
Why I can’t use this app it said « untrusted enterprise developer...... » it show when I click Uncover app https://ibb.co/F6smgH8

**Comment by Meowcat285** [comment]
This is not a issue related to Unc0ver itself. Next time also make sure to make a clear tital. 

**To fix this**: goto setting on your device, then go to general, and then scroll down to device profiles, there will be one item in there, select it and press trust.
