### ISSUE TITLE
Unc0ver b46 randomly resprings

### ISSUE THREAD

**Issue by youknowdavibes** [pwn20wndstuff/Undecimus#830]
https://pastebin.com/raw/gWK46Wi9

^ Cr4shed log... keeps on respringing at random times, I can’t decipher what is says so turning to Github.

**Comment by youknowdavibes** [comment]
iOS 12.1.1 beta 3 on unc0ver b46. iPhone 8 (10,1)

**Comment by johngrov** [comment]
> https://pastebin.com/raw/gWK46Wi9
> 
> ^ Cr4shed log... keeps on respringing at random times, I can’t decipher what is says so turning to Github.

do you have wallmart or lockdock installed?

i had the "cfxnotificationtoken" etc in my crash log and believe wallmart or lockdock to be the cause

**Comment by youknowdavibes** [comment]
I have neither installed... I’m getting really frustrated with this jailbreak cuz all of these people are saying it’s stable but I’m getting all this dumb shit. Beta 45 was fine

**Comment by cadbob** [comment]
I had same issue and went back to B45 for time being
