### ISSUE TITLE
Cydia Freezing and Crashing into Reboot

### ISSUE THREAD

**Issue by johngrov** [pwn20wndstuff/Undecimus#831]
**Describe the bug**
Cydia freezes and ultimately causes a crash/reboot into jailed mode, particularly when refreshing sources. Others have reported the same with no help on reddit. I have tried turning off log dump crash in icleaner pro, refresh icon cache, reset cydia cache, reinstall cydia, rsd all checked on. 

Any chance it's related to unc0ver ram management?

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone X
 - unc0ver Version: b46

**Place an "x" between the brackets if true:**
 - [X ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

TWEAKS:

7-zip (POSIX): 16.02-1
AdBlock for YouTube: 1.0.7
AnimationsBeFast: 1.4.5
App Admin: 1.0r-101
AppList: 1.5.14
APT (apt-key): 1.4.8-3
APT 1.4 Strict (libapt-pkg): 1.4.8-4
APT Command Line: 1:0-2
APT Strict (lib): 1.4.8-7
APT Strict: 1.4.8-3
Assuan: 2.5.1-1
AutoUnlockX: 1.0.1
Barmoji: 1.3.1
Base Structure: 1-5
BatteryNotch: 1.4.1
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Blackout: 1.0.1
Bourne-Again SHell: 4.4.23-2
bzip2: 1.0.6-1
CA Certs: 0.0.1-1
Cappd: 1.0.2
Cephei: 1.12
Cercube for YouTube: 4.2.2.10
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Cr4shed: 2.0.6
Cydia Installer: 1.1.32~b12
Cydia Substrate: 0.9.7032
Cydia Translations: 1.1.32~b1
Darwin Tools: 1-6
Debian Packager: 1.18.25-10
Debian Utilities: 4.8.6-1
Deluminator: 2.1.8
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Eclipse 12 (iOS 12): 6.0.4
Essential: 0-1
file: 5.35-2
Filza File Manager: 3.6.4
Find Utilities: 4.6.0-1
Flame: 1.3
Flipswitch: 1.0.16~beta4
FloatingDockPlus: 1.2.2
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
iCleaner Pro: 7.7.2
iOS Firmware: 12.1
iPhone Firmware (/sbin): 0-1
Jellyfish: 1.1.2
KSBA: 1.3.5-1
Laetus: 0.0.3-1
LetMeBlock: 0.0.1
libbulletin: 0.1-145
libCercube: 1.1.1
libcolorpicker: 1.6-1
libcrashreport: 1.1.0-1
libCSColorPicker: 0.8.1
libidn2: 6.1.2-1
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libRocket: 1.0.5
libSparkAppList: 1.0.1-1
libsymbolicate: 1.9.0-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Melior [Public]: 1.0.8-1
Nebula: 1.0.0-3
NeonBoard: 1.0.2
Nettle: 3.4-2
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
OpenSSL 1.0 Libraries: 1.0.2q-1
p11-kit: 0.23.12-1
PercentageBatteryX: 1.0.4
plutil: 0.1.0
PowerSelector (iOS 11 & 12): 1.1-7
PreferenceLoader: 2.2.4~alpha1
PrefixUI: 1.1
PrimalFolder: 0.0.5
Profile Directory: 0-1
PullToRespring: 1.2
Push For Apollo: 0.0.2
readline: 7.0.5-2
ReProvision: 0.4.2
Rocket for Instagram: 3.3.2
RocketBootstrap: 1.0.7~beta2
Safari Plus: 1.6.7
sed: 4.5-1
shell-cmds: 118-8
Signing Certificate: 0.0.1
SleepyTime: 0.0.1-4
SmartRotate: 1.2.3
Substrate Safe Mode: 0.9.6001.1
SwipeForMore: 1.1.7
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4~b3
UIKit Tools: 1.1.13-5
Unc0ver Jailbreak Resources: 1.0~b6
unrar: 5.6.4-1
unzip: 6.0-1
Wallmart: 2.0-1
WeatherVane: 1.2.0
WorkFFS: 1.0.0-1
XZ Utils: 5.2.4-4
zip: 2.32-1

many users are reporting that this is an issue w unc0ver. not saying theyre right, but does this happen on your test device with unc0ver and if not, how have you fixed it? @pwn20wndstuff

**Comment by adhip94** [comment]
I am getting this issue now everytime I refresh sources in Cydia with the latest production version of unc0ver. In the previous beta versions of unc0ver this used to happen randomly, now its happening frequently (**i.e. everytime I open Cydia to refresh sources**), @pwn20wndstuff Can you/Saurik look into this please?
Device - iPhone 8 Plus (12.1.2)
