### ISSUE TITLE
iPhone 6 Keeps unjailbreaking itself

### ISSUE THREAD

**Issue by Zach10000** [pwn20wndstuff/Undecimus#833]
Hi my iPhone 6 keeps unjailbreaking itself usually overnight. I don’t know why this is happening. But the weird thing is when I was on vacation with my family we were in the states and im from Canada ; while we were at the hotel it didn’t unjailbreak itself! So I’m not sure if it has anything to do with my location.  Also I’m a complete noob to the world of jail breaking.

**Comment by Zach10000** [comment]
Also not sure if this will help but I’m running beta46

**Comment by CoolPersonMaam** [comment]
There is another thread of this happening, this also been happening to many other people. Likely you were charging and the device overheated or something so it randomly restarted try turning on increase memory limit when you jailbreak and about to charge

**Comment by CoolPersonMaam** [comment]
Also this isn’t the correct template but hope this comment above helps!

**Comment by xMilesManx** [comment]
@CoolPersonMaam I've seen that suggested in the other thread, however that does not work for me. With that toggle enabled, it becomes significantly harder to jailbreak, (will reboot instead of respringing) and then it will still reboot itself overnight while charging.

**Comment by Zach10000** [comment]
Ok I’ll try tonight with increase memory on

**Comment by Zach10000** [comment]
Also should I have my phone charging or should I try it without the phone plugged in?

**Comment by CoolPersonMaam** [comment]
If you’re phone charges it’s mostly likely going to restart, if it’s not plugged in, the chances of restarting is a lotmore lower

**Comment by Zach10000** [comment]
So before I jailbreak I should turn on increase memory. Or do I do it when the phone is in its jail broken state

**Comment by Zach10000** [comment]
Also should I turn airplane mode on; and wifi off?

**Comment by Zach10000** [comment]
Sorry for the late response, but it worked! Thanks guys!
