### ISSUE TITLE
Respring loops

### ISSUE THREAD

**Issue by erny165** [pwn20wndstuff/Undecimus#839]
When re-jailbreaking my device, I have to do glitches in order to get into jailbroken state. Otherwhise, it will not be jailbroken because od respring loops and reboots.
Iphone X 12.1.1 b3 on unc0ver b46

**Comment by WalshyDev** [comment]
Please follow the issue template...

Also this is likely due to a tweak, disable them and see if you still have the issue.

**Comment by erny165** [comment]
If I disable my tweaks it works. That's the glitch I use. I use Icelaner pro in order to disable tweaks and get into jailbroken mode. 
Is there anyway I can know which is the tweak that is causing problems?
