### ISSUE TITLE
iPhone X iOS 11.4b3  ERRNO 1 Step 6/48

### ISSUE THREAD

**Issue by Andricq** [pwn20wndstuff/Undecimus#84]
iPhone X iOS 11.4b3  ERRNO 1  Step 6/48

**Comment by Cryptiiiic** [comment]
@Andricq use v1.0.3, your app seems to be outdated

**Comment by Samgisaninja** [comment]
This means the app failed to get root perms for itself, reboot and try again.

also as cryptic said, make sure youre on the latest version of unc0ver.
