### ISSUE TITLE
Device freezes 

### ISSUE THREAD

**Issue by shsh2** [pwn20wndstuff/Undecimus#841]
Device freezing about 3 time in 2 days also respring loop battery drain

**Comment by WalshyDev** [comment]
Some battery drain is expected, if you're seeing a significant amount take a look at your tweaks. Same with the respring loops.

**Comment by Tgod1991** [comment]
Could be due to tweaks you have installed. I removed a few I read on reddit and the freezing stopped.

**Comment by shsh2** [comment]
Thank you guys very kindly, I was on Electra and everything great no issues at all .
I check all the tweak I installed the freezes still
