### ISSUE TITLE
PokemonGo

### ISSUE THREAD

**Issue by Benderrodrigu3z** [pwn20wndstuff/Undecimus#844]
Can’t play Pokémon go it says iPhone is jailbroken even after I reboot the iPhone XS
Please push a patch for the iPhone XS model

**Comment by WalshyDev** [comment]
Install something like Liberty Lite to try and bypass detection. 
It isn't surprising though that it still sees it after a reboot since all the files are still there just not loaded.

**Comment by deucetresthugz** [comment]
just use pokego2.0++. here’s the cydia repo https://pokego2.com/
