### ISSUE TITLE
Messages app crashes when using the audio recording feature

### ISSUE THREAD

**Issue by ethanm10** [pwn20wndstuff/Undecimus#847]
I am on the latest version of Unc0ver
*This happened before I installed any tweaks so I am positive Unc0ver is the problem and not a tweak

**Comment by ethanm10** [comment]
*iPhone X iOS 12.1.1

**Comment by WalshyDev** [comment]
Dupe of #803

**Comment by igsony** [comment]
the same....b46 with   iPhone X  （iPhone 10,3)😭
