### ISSUE TITLE
After respring will break Verification Code Automatic Filling and keychain

### ISSUE THREAD

**Issue by xun188** [pwn20wndstuff/Undecimus#851]
if respring from cydia or plugin， Verification Code Automatic Filling will break，it can get the code，but cannt Automatic Filling，and when login a app use keychain， must tap the key log to select，If  re-jailbreak，the problem can fix，this is on iPhone X，I hope can fix it

**Comment by chefdb** [comment]
I’m having the same issue.  Is there any fix for it ?
