### ISSUE TITLE
RootFS already mounted 

### ISSUE THREAD

**Issue by lorenzmatt** [pwn20wndstuff/Undecimus#853]
There is no OTA File in settings. But there is this error every time.

**Comment by marcnhl15** [comment]
Same thing for me

**Comment by ThaPandaKingg** [comment]
same thing happened to me and i fixed it. here’s how. open the uncover app and in settings unselect disable auto update and select restore rootfs and hit jailbreak, phone will reboot. after it reboots do not open the uncover app at all. instead delete it. go to your settings and let the 12.1.4 update go through until it starts downloading. put your phone in airplane mode and make sure wifi is turned off too. then go into your settings app, general, iphone storage and the OTA update should be there. it took a while for mine to show up. i had to let the update download a bit before it showed up. delete the OTA file. if you used cydia impactor for uncover you can use that to install the app again. i used tweakbox to redownlod it. after you redownload the app, open it up, in settings turn off reload system dameons, and hit jailbreak, it may take a couple tries for it to work. i did it about 2 or 3 times and it fixed it. i’m running ios 12.1.1b3 on iphone XS MAX a12.

**Comment by CharlesDardaman** [comment]
Thanks @ThaPandaKingg that fixed it on mine.

**Comment by akukatala** [comment]
HELP!! I have JB in iOS 12.1.1 but I don't have a PC and when I give the option of unc0ver to remove the JB the option to update software in the iPhone options does not open and if I give it to reset the cell phone it gives me a respring and does not erase anything  

iPhone 6S Plus
