### ISSUE TITLE
iPhone 7+, iOS 12.1.2; Device Not Jailbreaking

### ISSUE THREAD

**Issue by eso22** [pwn20wndstuff/Undecimus#857]
My device doesn’t want to jailbreak with reload system daemons on or off. It just stays in a respring loop. Like an infinite bootloop respring. Haven’t installed any new tweaks or done modifications recently either. Just started doing this yesterday.

**Comment by eso22** [comment]
Also tried deleting and reinstalling B46.

**Comment by Smashmaster52** [comment]
Have you tried earlier versions of unc0ver?
