### ISSUE TITLE
device don't get jailbreak

### ISSUE THREAD

**Issue by shalevshagan1** [pwn20wndstuff/Undecimus#861]
i jailbroke my device , it success, after some time my device did a reboot and then when i come to try to enable the jailbreak it success but after respring  instead of load jailbroke it just show up apple logo and load normal, tried to enable airplane mode but it won't help.
it work after i restore rootfs and jailbreak again .

Iphone 8 / 10,4 
Ios - 12.1.1 beta 3 (16C5050a)
 - unc0ver Version: beta 46

**Place an "x" between the brackets if true:**
 - [x] this issue is present on the latest version of unc0ver

**Comment by dustinduse** [comment]
I had the same issue.

IOS 12.1.2
Iphone 6S

Steps I took to resolve the issue.
1) Disable Siri
2) Turn on Airplane mode
3) Reboot device with these changes
4) Jailbreak.
