### ISSUE TITLE
unc0ver b46

### ISSUE THREAD

**Issue by TommyGrace** [pwn20wndstuff/Undecimus#864]
The device will randomly freeze, unable to operate the main screen, high memory consumption, charging automatic restart into the state of not jailbroken

**Comment by TommyGrace** [comment]
The device will randomly freeze, unable to operate the main screen, high memory consumption, charging automatic restart into the state of not jailbroken

**Comment by TommyGrace** [comment]
iPhone 7plus and iPad Air 2

**Comment by qiuyi21** [comment]
When charging, the device goes black and does not respond, and then automatically restarts. This happened once on my iPhone 7.
