### ISSUE TITLE
Cydia Freeze b46 Iphone X

### ISSUE THREAD

**Issue by jonatansuarez1208** [pwn20wndstuff/Undecimus#865]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by KeyFlyz** [comment]
Same issue iPhone 8+ IOS 12.0.1 uncover b46 when I open cydia the red wheel spins like its checking for updates then just stops in mid spin and the whole phone freezes up and I have to do a hard reset and rejailbreak it doesn’t do it every time just maybe once a day. Can’t provide any crashreports as crashreporter and cr4shed both don’t work properly on my device.

**Comment by johngrov** [comment]
> Same issue iPhone 8+ IOS 12.0.1 uncover b46 when I open cydia the red wheel spins like its checking for updates then just stops in mid spin and the whole phone freezes up and I have to do a hard reset and rejailbreak it doesn’t do it every time just maybe once a day. Can’t provide any crashreports as crashreporter and cr4shed both don’t work properly on my device.

literally exact same here except on iphone x 12.1, i posted it as a bug on this forum but got no response. tons of users are experiencing this

can we get any response on this? is this happening on the devs personal devices and if not, how are you avoiding it? 

any chance the impending substrate update fixes this?

**Comment by Spasix** [comment]
Jailbreak with Reload System Daemons on and click Jailbreak. That should fix it fr you.

**Comment by KeyFlyz** [comment]
>Jailbreak with Reload System Daemons on and click Jailbreak. That should fix it fr you.

@Spasix not the problem you need to think before you reply to people.
