### ISSUE TITLE
Unc0ver b46 system daemons issue

### ISSUE THREAD

**Issue by gael17700** [pwn20wndstuff/Undecimus#867]
Respring loop when rejailbreak with reload system daemons. iPhone 6s, iOS 12.1, unc0ver b46

**Comment by KeyFlyz** [comment]
iPhone 8+ IOS 12.0.1 uncover b46 Have the same issue here as well but in my case only when certain tweaks are installed for example Gif2Ani V2 and UnlockSound but if there installed I have the reload system daemons problem and if there not I don’t. And I’m sure some other tweaks are causing it as well.
