### ISSUE TITLE
Appstore Apps Not Downloading 

### ISSUE THREAD

**Issue by deucetresthugz** [pwn20wndstuff/Undecimus#870]
I’m having lots of trouble downloading apps from the appstore? i’m on 12.1.2 and I can’t download any apps. I’ve signed out of my icloud and signed back in, killed appstore in cocoatop and even restarted and tried to download in an unjailbroken state but still won’t download?

**Comment by tigerban** [comment]
You have the passbook deamon turned off in icleaner
