### ISSUE TITLE
Having issues with respiring 

### ISSUE THREAD

**Issue by migrey21** [pwn20wndstuff/Undecimus#871]
My iPhone X iOS 12.1.2 randomly resprings at random times. I’m using unc0ver 3.0.0~b46 and don’t know why?? Help please.....

**Comment by abod13245** [comment]
I have the same issue as yours with my iPhone X iOS 12.0.1. I’m using unc0ver 3.0.0~b46. Whenever it crashes I go to crashreporter and cr4shed to see for the suspect I always see them blank which means it is from unc0ver

**Comment by johngrov** [comment]
> I have the same issue as yours with my iPhone X iOS 12.0.1. I’m using unc0ver 3.0.0~b46. Whenever it crashes I go to crashreporter and cr4shed to see for the suspect I always see them blank which means it is from unc0ver



> My iPhone X iOS 12.1.2 randomly resprings at random times. I’m using unc0ver 3.0.0~b46 and don’t know why?? Help please.....

post your tweaks
