### ISSUE TITLE
Random resprings

### ISSUE THREAD

**Issue by potatohead309** [pwn20wndstuff/Undecimus#873]
My device has random resprings and not so random respring it could do it randomly in the middle of anything and it can do it right after I use the camera to take a photo

Iphone X 12.1 b46

**Comment by migrey21** [comment]
I also have the same issue. I could open any app and out of nowhere my device would respring. I have a iPhone X running iOS 12.1.2 b46

**Comment by bluegreentree** [comment]
When I’m taking a picture or video sometimes it randomly resprings for myself too. This isn’t to often but does happen. 

iPhone 6
iOS 12.1.2
Version 3.0.0

**Comment by shub0y** [comment]
If you have lockAnim, uninstall it, the tweak is not yet compatible!

**Comment by lbenicio** [comment]
Same issue here with iphone x 12.1.2 b49, any news? Crash reporter didn't report anything...

**Comment by potatohead309** [comment]
As shub0y pointed out lock anim was the one tweak causing the random resprings with the camera and randomly removing it fixed the issue but after updating to b49 I started having random freezes for some reason

**Comment by lbenicio** [comment]
I don't have lockanim installed

**Comment by potatohead309** [comment]
Uncover isn’t the reason for random reboots check your tweaks one of them is incompatible with ios 12 and is causing it check the tweaks that haven’t been updated first

**Comment by lbenicio** [comment]
all are marked as compatible in TweakCompatible. I will try to disable one by one and see what happens

**Comment by potatohead309** [comment]
Tweak compatible is marked by users and many users might have the issue and the tweak looks like it’s working right so they don’t know it’s causing the problem (eg. “lockanim” for me)

I don’t really know about panic logs
