### ISSUE TITLE
overnight reboot iphone 6 12.1

### ISSUE THREAD

**Issue by aksy007x** [pwn20wndstuff/Undecimus#876]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iphone 6
 - unc0ver Version: beta48

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by bluegreentree** [comment]
You plug your phone in over night and by the morning it has restarted and will ask you for your password instead of Touch ID because of restart

**Comment by bluegreentree** [comment]
You plug your phone in over night and by the morning it has restarted and will ask you for your password instead of Touch ID because of restart.

iOS 12.1.2
iPhone 6 
Version 3.0.0

Also, I do not have iOS updates waiting to be installed either.

**Comment by bluegreentree** [comment]
Restarts randomly in the middle of the night is the bug

**Comment by aksy007x** [comment]
well whenever i plug it overnight and by morning it is usually restarted ..i have to jailbreak it again..
