### ISSUE TITLE
IPHONE 5S JailBreak

### ISSUE THREAD

**Issue by robert2jz** [pwn20wndstuff/Undecimus#879]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Flipp3rrr** [comment]
What's the bug? How do we reproduce it? Do you have screenshots? What is your device information? Do you have logs? We can't help you if you don't add any information!
