### ISSUE TITLE
Keep getting error(fatal) errno :2 

### ISSUE THREAD

**Issue by WCHighfill** [pwn20wndstuff/Undecimus#882]
I keep getting an error 
Error (fatal)
Errno:2
Test: “BuildVersions match”==NULL
Filename: Jailbreakviewcontroller.m
Line: 1156
Function: jailbreak
Description: RootFS already mounted, delete OTA file from Settings - Storage it present and reboot

I have never done an OTA update one any of my iPhones EVER. And the file isn’t there even when I go into the file system and check. It’s been happening since beta 44. I’m on iOS 12.0 iPhone XS. I have googled the issue, asked on Facebook jailbreak pages for help and even tweeted pwn about it with no avail

**Comment by Flipp3rrr** [comment]
It has been happening since b44? What version are you currently on?

**Comment by WCHighfill** [comment]
I’m not technically on any version because none will work. But last version I tried was the latest version b48. Also the badge number next to my settings app goes up 1 every time I try to jailbreak. It’s usually at 1 because of the OTA I never do. Currently it says 8 next to it.![GitHawk Upload by WCHighfill](https://i.imgur.com/KTDiEzQ.jpg)
![This is the error by WCHighfill](https://i.imgur.com/lAjiT93.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Yolokung** [comment]
Try turn on Restore RootFS (rec0ver) on unc0ver setting maybe it would fix it, But it will remove all of your tweaks.

**Comment by WCHighfill** [comment]
I tried that. I get the same error then it crashes and the number goes up

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by XxJackiexX** [comment]
Go to general >Iphone storage> and find OTA file then delete it.

**Comment by WCHighfill** [comment]
Like I said in my original post, I don’t even have the OTA file anywhere on my phone. I even used Geofilza and searched my whole phone and it’s not there, that’s the issue. And I can’t even download the OTA then delete it to see if that would help because the OTA just hangs saying estimated time remaining and it will do that for days.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by XxJackiexX** [comment]
Sorry didn’t read everything properly, did u tried enable auto updates in settings?

**Comment by XxJackiexX** [comment]
Disable*

**Comment by d0ntcryb4by** [comment]
I have the same problem, My version is 12.1 (16B92) - Iphone 8 Plus. No OTA update, no rootFS. Turn off update already. Try many version: from B40 - B48.

**Comment by WCHighfill** [comment]
Yes auto update is always off

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WCHighfill** [comment]
I fixed it. I erased all contents and data on my phone and restored it from iCloud. After setting it up the OTA file was in the iPhone storage and I deleted it. I installed unc0ver, ran it and it worked. Now I just have to wait for Saurik to update Cydia and whatnot. Thanks for all the help🤘🏻
