### ISSUE TITLE
Iphone7+ boot loop in the Unc0ver 3.0.0 b46&47&48

### ISSUE THREAD

**Issue by issacgithub** [pwn20wndstuff/Undecimus#888]
Hi
Unc0ver 3.0.0 b46&47&48 can not make iphone7+ a jailbreak, and the phone will restart(boot loop)
Please fix 
Thanks

**Comment by jcheema468** [comment]
It’s not a bootloop it’s called respring loop lol 😂

**Comment by baobaoit** [comment]
Turn on airplane mode beforce you jb. Turn on Refresh Icon Cache.
Or
Turn off Reload System Daemons. Then jb. Finally, turn it on back and re-jb again.

**Comment by issacgithub** [comment]
I found
The tweaks that make respring loop on iPhone are:
StatusTint (libCSpreferences -libSparkAppList)
Gif2Any(libCSPreference)
Yourspring(libdevImagePick)
