### ISSUE TITLE
Unc0ver Errno: 17 failed to rename System snapshot 

### ISSUE THREAD

**Issue by jeydm** [pwn20wndstuff/Undecimus#889]
This error is present since Unc0ver was released for iOS 12 (not fixed on b48)

Hope Pwn20wnd will finally at least state if he is able to fix this error.

Here is the log:
https://pastebin.com/4kQeYe42

**Comment by Flipp3rrr** [comment]
Can you please use the auto-format? We need to know what exactly happened, your device name and exact iOS version, etc.
