### ISSUE TITLE
All versions except RC9 fail at mount_apfs "Failed to remount RootFS" iOS 11.1.1.

### ISSUE THREAD

**Issue by zlxdike** [pwn20wndstuff/Undecimus#89]
iOS11.1.1 7Plus
v1.1.0 errorno 30
![](https://raw.githubusercontent.com/zlxdike/zlxdikeblogimg/master/img/20181029230912.png)

**Comment by zlxdike** [comment]
Note that I don't have 'Restore RootFS (Destructive)' option enabled.

**Comment by Samgisaninja** [comment]
Please provide your device and iOS version

**Comment by zlxdike** [comment]
iOS11.1.1 7Plus

**Comment by zlxdike** [comment]
> Please provide your device and iOS version

iOS11.1.1 7Plus

**Comment by zlxdike** [comment]
v1.1.4 
snapshot_create return -1
iOS11 - ios11.2  maybe can't snapshot_create??

**Comment by ShawnNgDeveloper** [comment]
I got this issue too :(

**Comment by Cryptiiiic** [comment]
@zlxdike does this still occur on v2.1.0? Please post results.
