### ISSUE TITLE
Blaze pizza app crashes

### ISSUE THREAD

**Issue by ehoeve786** [pwn20wndstuff/Undecimus#891]
Blaze pizza app crashes upon opening with jailbreak! Any way to fix this?

**Comment by jkhsjdhjs** [comment]
Have you tried it with tweaks disabled?
If it still doesn't work with tweaks disabled the blaze pizza app may have some sort of jailbreak detection implemented. You could try the tweak `Liberty Lite` from https://ryleyangus.com/repo/ to workaround the issue.

**Comment by ehoeve786** [comment]
Looks like Liberty Lite Beta worked for it. Liberty Lite didn’t but the beta works

**Comment by jkhsjdhjs** [comment]
Great, would be cool if you could close this issue!
