### ISSUE TITLE
Screen will not wake after sleep with Carplay.

### ISSUE THREAD

**Issue by cyberfunk** [pwn20wndstuff/Undecimus#895]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

After using carplay for an indeterminate period of time the screen will not wake from sleep. The phone is still responsive if left plugged into carplay but the screen will not wake either plugged into carplay or unplugged. A hard reboot is required to restore the function and Jailbreak must be reset. Issue repeats....

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: 6s
 - unc0ver Version: Beta 46 and latest Beta 48

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Flipp3rrr** [comment]
Without providing your iOS version, device name and Unc0ver version no one can do anything for you. Can you please add this information in your report?

**Comment by cyberfunk** [comment]
iOS 12.1 iPhone 6s Unc0ver beta 46 and beta 48

**Comment by cyberfunk** [comment]
I've never been able to stay with Unc0ver due to issue deep in the coding/makeup of the Jailbreak. It's so much faster than Electra but these issues with Unc0ver always force me back. Unfortunatey there is no other option at the moment since Electra has not been updated for iOS 12. It's pretty distressing as I use this phone for work and the Jailbreak with CarBridge is essential to my workflow. Everytime I get to a delivery destination and unplug my phone from CarPlay I can't even see the customers information because of the black screen and have to hard reset the phone which take several minutes. 1st world problems I guess... but still I hope to see a relatively bug free version of Unc0ver or any other Jailbreak for that matter. I realize it's much harder nowadays to create and maintain these but I wish the developers would focus on the basics like screen wake from sleep. All of the other bell and whistles are useless if you don't have basics like screen wake, working dialer, cellular connectivity etc. Screen wake seems to be the only issue with my current setup.

**Comment by cyberfunk** [comment]
I also realize the issue could be with any of my installed tweaks including CarBridge but I never had this issue on previous jailbreaks with screen wake failing to respond to buttons. It almost seems as if the phone runs out of memory or some other CPU lockup but as I said if left plugged into CarPlay I can continue to use the device with my car radio display even if the phone display will not wake.

**Comment by cyberfunk** [comment]
Just received an update for CarBridge as I type this message and also Unc0ver resources so will see if the issue is fixed with these updates.

**Comment by cyberfunk** [comment]
Still freezing as of Beta 48. I see beta 49 has changes with regards to memory. Hopefully that will solve my issues:-)
