### ISSUE TITLE
Can't Jailbreak after Overnight Reboot: iPhone 6

### ISSUE THREAD

**Issue by PixelmonGalaxy** [pwn20wndstuff/Undecimus#896]
Unable to re-enable Jailbreak when too many tweaks are installed (Probably a RAM issue)

**To Reproduce**
1. Install 10-20 tweaks (depends on the tweaks)
2. Once your phone does an overnight reboot, you attempt to Jailbreak and it starts respringing for about 2 minutes then crashes

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 6
 - unc0ver Version: 3.0~b48

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

I do wish for this problem to be solved, but I do not know what logs to provide and where to find them.

**Comment by desepticon** [comment]
Jailbreak with "Reload System Daemons off. Then run ldrestart after. You can even install a module for CCSuport to make it easier.
