### ISSUE TITLE
Respring loop iphone 7+ Unc0ver 3.0.0 b46&47&48

### ISSUE THREAD

**Issue by issacgithub** [pwn20wndstuff/Undecimus#898]
The tweaks that make respring loop on iPhone 7+ are:
StatusTint (libCSpreferences -libSparkAppList)
Gif2Any(libCSPreference)
Yourespring(libdevImagePick)
libmitsuha
AppCake v6.1.1 from source:HackYourIphone(you should install from Main source(AppCake Source))

I've tested all of these on my phone

If some of these tweaks are installed from the original source, Or tweaks to be upgraded this issue is likely to be fixed
Thanks

**Comment by Yolokung** [comment]
Yourspring or Yourespring?
Yourespring sometimes lock my screen while in the middle of respring. But it’s not because of unc0ver but it’s because of the developers of Yourespring for not updating it to be fully compatible with iOS 11 which resulted in Stability issues.
