### ISSUE TITLE
Uncover says "Jailbreak Complete" but reboots after that

### ISSUE THREAD

**Issue by Nico2525** [pwn20wndstuff/Undecimus#901]
I´m on iOS 12.1.2 on an iPhone 6s Plus.
[diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/3022667/diagnostics.txt)

Uncover completes all steps and says Jailbreak complete.
The problem is that after that the device resprings for a long time and then shows the apple logo (as if it reboots) and I'm still unjailbroken. I think this bug started appearing after I installed the iOS 12 beta of Activator and it freezing my phone. I have managed to deinstall it as this bug happens only about 70% of the time. Yet the bug persists even after restore and loading a backup that I made after the bug appeared.

**Comment by Nico2525** [comment]
I know the jailbreak can fail but it would say so and not "Jailbreak complete" wouldn't it?

**Comment by BradleyW94** [comment]
what version of Uncover are you using b48? and when you notice the device reboot does it reboot once it hits 38/38? or does it get stuck on a lower number before rebooting?

**Comment by Nico2525** [comment]
Yes I am on b48. I can‘t see the number but I guess it hits 38/38 as Uncover is saying Jailbreak Complete in the popup.

**Comment by BradleyW94** [comment]
Completely removed the current b48 and attempt fresh with b41

**Comment by Nico2525** [comment]
B41 does not change it in any way.
It works normal however when I disable Reload System Daemons or disable "Load Tweaks". 
So I guess it has something to do with my tweaks. I however can not find the tweak responsible for all this. Does anyone know a tweak which is incompatible?

Package List:
7-zip (POSIX): 16.02-1
AppList: 1.5.14
APT (apt-key): 1.4.8-3
APT 1.4 Strict (libapt-pkg): 1.4.8-4
APT Command Line: 1:0-2
APT Strict (lib): 1.4.8-7
APT Strict: 1.4.8-3
Assuan: 2.5.1-1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BetterCCXI (Weather Addon): 1.0.1
BetterCCXI: 1.4.8
BigBoss Icon Set: 1.0
BioProtect XS (iOS 12): 4.0-68
Bourne-Again SHell: 5.0.3-1
bzip2: 1.0.6-1
CA Certs: 0.0.1-1
CCSupport: 1.2-3
Cephei: 1.12
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Cydia Installer: 1.1.32~b12
Cydia Substrate: 0.9.7032
Cydia Translations: 1.1.32~b1
Darwin Tools: 1-6
Debian Packager: 1.18.25-11
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Essential: 0-1
file: 5.35-2
Filza File Manager: 3.6.4
Find Utilities: 4.6.0-1
Flame: 1.3
gettext: 0.19.8-1
Gif2Ani V2: 2.1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
Harbor 2: 1.0.1-1+debug
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.7.2
Instagram ++: 1.8r-250
iOS Firmware: 12.1.2
iPhone Firmware (/sbin): 0-1
KSBA: 1.3.5-1
LetMeBlock: 0.0.1
libbulletin: 0.1-145
libcolorpicker: 1.6-1
libCSColorPicker: 0.8.1
libCSPreferences: 1.0.6
Liberty Lite (Beta): 0.2.11
libidn2: 6.1.2-1
libimagepicker: 1.0.2
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libswift4: 4.2.1-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
Local SSH: 0.0.2
Locale Profiles in UTF-8: 1.0-1
LocalIAPStore: 1.4-2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Neptune for iPhone: 1.0
Nettle: 3.4-2
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm 2 (iOS 7 – 12): 2.1
NFCWriter XS (iOS 11 & 12): 2.0-7
Noctis12: 1.4
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2q-1
p11-kit: 0.23.12-1
PassFaker: 1.0
PreferenceLoader: 2.2.4~alpha1
PrefixUI: 1.1
Profile Directory: 0-1
readline: 8.0-1
ReProvision: 0.4.2
RocketBootstrap: 1.0.7~beta2
sed: 4.5-1
shell-cmds: 118-8
Signing Certificate: 0.0.1
SneakyCam [Members Plus]: 0.0.6-1-2
Substrate Safe Mode: 0.9.6001.1
system-cmds: 790.30.1-2
Tacitus: 1.1
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4~b3
tweakCompatible: 0.1.5
uasharedtools (iOS 11): 2.2r-76
uasharedtools: 2.2r-76
UIKit Tools: 1.1.13-5
Unc0ver Jailbreak Resources: 1.0~b7
unrar: 5.6.4-1
unzip: 6.0-1
XZ Utils: 5.2.4-4
zip: 2.32-1

**Comment by suryoaji** [comment]
Just turn on offline mode when jailbreaking, its work for me.

**Comment by TheRealKeto** [comment]
@Nico2525 This could very well be due to RSD, or a tweak that conflicts with your device/another tweak. Update your app to the latest version of unc0ver, make sure "Reload System Daemons" is toggled on and attempt to jailbreak.  

If that doesn't work, disable "Load Tweaks" and uninstall the tweak you installed before the issue occurred (in which case, this would be Activator), then reboot, enable "Load Tweaks" and jailbreak.
