### ISSUE TITLE
Bluetooth Headset Controls Stop after Jailbreak (long time issue)

### ISSUE THREAD

**Issue by BradleyW94** [pwn20wndstuff/Undecimus#902]
So currently my Hardware setup I'm using 

Hardware & Software
Both devices JB upon availability on beta's and have been since with constant updates 
iPhone X - IOS 12.1.2
iPad Pro 12.9 (2015) - IOS 12.1.1
Sony MDR-XB950N1
----------

So my issue is When I attempt to Use my headset with my iPhone/iPad music plays the pause unpause works fine volume Up/Down but Skip Track and Back track is disabled 

at first as this issue replicated across my iPhone and iPad I thought I isolated the issue to the Sony MDR's

further testing I tried the Sony headset with my Mac and the skip feature works just fine and ignored this issue for some time hoping the issue would get resolved I believe I first noticed this on the first beta for my IOS version came out and since we're on b38 now and issue persists I've made this post

eventually after having issues with my jailbreak I decided to restoreRootFS > Reset all settings > restore backup > re Jailbreak 

after my iPhone & iPad had the Jailbreak removed suddenly both devices worked fine with my Sony Headphones skip and back feature 

Re-jailbreak = features broke again

**Comment by BradleyW94** [comment]
I'd also like to further this by saying yes this feature was disabled before ANY tweaks etc got added after ReJailbreak testing

**Comment by Tylerbb812** [comment]
I have the same problem, I can’t use any buttons in my car to control my music through Bluetooth. I have an iPhone 11 Pro Max 13.3 latest version of uncover
