### ISSUE TITLE
Phone Froze while in Snapchat and then Rebooted after previously randomly rebooting the night before

### ISSUE THREAD

**Issue by WindiestApe21** [pwn20wndstuff/Undecimus#907]
Yesterday my phone had rebooted overnight so I had to go back to Unc0ver and re-jailbreak. After about an hour of being back in a jailbroken state, my device froze and crashed (rebooted) once again. 

**Device (please complete the following information):**
iOS 12.1.1
iPhone 8 Plus
Latest Unc0ver version and latest resources version 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
I installed C4shed today so if it happens again I can provide a log.

**Comment by spikesF** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/927#issuecomment-482536993
