### ISSUE TITLE
Failed to Extract Boostrap (Errno 0)

### ISSUE THREAD

**Issue by Dowz95** [pwn20wndstuff/Undecimus#908]
![Image](https://i.imgur.com/2R2HAvo.jpg)

Hi, i’m on iPhone X 12.0 and i use Unc0ver since b~29, i got succefully jailbreak but yesterday my device reboot and after that i re-try to jailbreak and i got this message now ...
I was on b~46, i update today for b~47 and it still bug :/

Ps: sorry for my english, i’m french

**Comment by corurhaw** [comment]
Your jailbreak was successful but with an error. Open cydia and delete AppCake. Close and restart cydia. If it says ignore or clear, choose forcibly clear. Reboot, then try to jailbreak again.

**Comment by Dowz95** [comment]
Thanks dude ! It works again :)
I just delete AppCake and after Respring i

**Comment by Dowz95** [comment]
i have my tweaks
Thanks for the help ;)
![Image](https://i.imgur.com/OZXvf6j.jpg)

**Comment by Manav978** [comment]
Hey
I have the same problem but I’m not able to find AppCake

**Comment by snowball7241** [comment]
@Manav978 read the log, it should point to a package that's causing the issue.
