### ISSUE TITLE
Fail to extract bootstrap 

### ISSUE THREAD

**Issue by chriskohth** [pwn20wndstuff/Undecimus#909]
IOS 12.1.1 beta 3. Iphone 7plus. 
Phone was airplane mode with wifi after trusting the install. 

App stops at 26/28 and with error prompt. 

Tried to restart. Delete app from settings and redo jailbreak. Same result. Restore roof also caused it to restart a few times but with same error. 

![IMG_8491](https://user-images.githubusercontent.com/49149606/55320530-c4513600-54d3-11e9-967e-880e2f77f721.JPG)
Please help. Thanks.

**Comment by Nahum95** [comment]
try rootfs and re jailbreak again

**Comment by Nixuge** [comment]
I think this error mean you’re jailbroken. Try to respring (Settings>Display and brightness>Bold text>Continue)

**Comment by Nahum95** [comment]
Didnt help

**Comment by chriskohth** [comment]
![A86DAEF1-BC59-4B2A-B3D8-D6944DFD9C2D](https://user-images.githubusercontent.com/49149606/56455127-f527db00-63ae-11e9-8f72-a44ff62462cc.png)


Still can’t jailbreak. 
What I did using the final release v3.0
iOS 12.1.1 beta 3. Iphone 6plus 

1. RoofFs to clear. 
2. Restart a few times on its own 
3. After that press jailbreak and the error msg came back 
4. Tried to respring many times. All stopped at same point 

Please help. Thanks

**Comment by rigs101** [comment]
I have the same exact error. Any help plz
