### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by mrpras** [pwn20wndstuff/Undecimus#910]
I saw that you mentioned you don’t feel so good. For what it’s worth: it’s an amazing act to share your efforts like this and many of us benefit greatly. Maybe we don’t always tell you but we love your work and personally when I can afford to I hope to send some donations. I hope others do too, thank you for your work!

**Comment by bigrck64** [comment]
We love you ! Thanks for all you have done :)

**Comment by TheNoim** [comment]
This all nice. However, this does not belong here. This is an issue tracker. I suggest closing the issue.

**Comment by mrpras** [comment]
I thought it would be nice whilst they were looking through all things wrong to get a positive message. I guess they/he can close it if he wants - don't know why you care to be honest.
