### ISSUE TITLE
Veency bug : no "left click" -> Touch screen

### ISSUE THREAD

**Issue by bigrck64** [pwn20wndstuff/Undecimus#911]
Here is the latest veency problem we have on iOS 11.
I'm sure one good dev / hacker can help :)

How to install veency on iOS 11
- find a clean idevice with iOS 11.x
- install unc0ver 3.0.0 b48 (bundled with mobilesubstrate 0.9.7032)
- jailbreak
- launch cydia and install "OpenSSH" + "MouseSupport 1.0" + "libstatusbar 0.9.9.0-1" + "SpringBoardAccess 0.3-5"
- connect to ssh (alpine) and upload http://apt.saurik.com/cydia/debs/veency_0.9.3500_iphoneos-arm.deb to the device (with WinSCP for example)
- install veency manually with: dpkg -i veency_0.9.3500_iphoneos-arm.deb
- restart device & jailbreak
- device > General > veency > Set one password + [uncheck] "Show Cursor"
- note1: if you try to display the cursor, it will crash SpringBoard into safe mode on VNC client connexion.
- note2: with iOS 12.1.1, loading veency tweak crash system every time, I suspect a coretrust problem, so let's focus on iOS 11.

From here:
- you can connect to veency tcp port 5900 and login with your password
- you can display the idevice screen :)
- you can use "right click" -> Home button
- you can use "middle click" -> Power button
- you can use "keyboard" -> Type text
- but, you CAN NOT use "left click" -> Touch screen

I have confirmed the veency "left click" problem with:
- iOS 11.1.2 (iPhone 5s) + unc0ver 3.0.0 b48
- iOS 11.3.1 (iPhone 5s) + unc0ver 3.0.0 b48
- iOS 11.3.1 (iPhone 6s) + unc0ver 3.0.0 b48

Did anyone have one idea why the "touch screen" basic function is broken with iOS 11 ?
What is the faulty lib here ? jailbreak ? mobilesubstrate ? mousesupport ?

For information, veency "left click" is working well with:
- iOS 10.3.3 (iPhone 5s) + doubleH3lix rc8 + mobilesubstrate 0.9.6301 + jp.ashikase.mousesupport 1.0 + libstatusbar 0.9.9.0-1 + ch.ringwald.springboardaccess 0.3-5
- iOS 10.3.3 (iPhone 5s) + doubleH3lix rc8 + mobilesubstrate 0.9.7020 + jp.ashikase.mousesupport 1.0 + libstatusbar 0.9.9.0-1 + ch.ringwald.springboardaccess 0.3-5

Thanks for any suggestion :)

sources:
https://git.saurik.com/veency.git
https://github.com/mringwal/mouse-support
https://github.com/phoenix3200/libstatusbar
https://github.com/bluekitchen/btstack/tree/master/port/ios/SpringBoardAccess

**Comment by myGitHib26** [comment]
Confirmed on IOS 11.4.1 iPad Pro  10.5" MQEY2LL/A
 unc0ver 3.0.0 b48, you can port 5900 and login with your password, 
you can display the idevice screen :)
you can use "right click" -> Home button
you can use "middle click" -> Power button
you can use "keyboard" -> Type text
but, you **CAN NOT** use "left click" -> Touch screen

**Comment by fatfatson** [comment]
confirmed on IOS 10.3.2 iPhone 6 plus
can only display screen and use keyboard
none of three mouse button work

**Comment by bigrck64** [comment]
> confirmed on IOS 10.3.2 iPhone 6 plus
> can only display screen and use keyboard
> none of three mouse button work

It's Undecimus repo here, so Jailbreak of iOS 11 - 12 :)
Please don't report problem on iOS 10.

Which jailbreak are you using ? because I don't have any problem with the following config:
iOS 10.3.3 (iPhone 5s) + doubleH3lix rc8 + mobilesubstrate 0.9.6301 + jp.ashikase.mousesupport 1.0 + libstatusbar 0.9.9.0-1 + ch.ringwald.springboardaccess 0.3-5

**Comment by Samgisaninja** [comment]
AFAIK veency was never updated to support iOS 11.0+... but I really hope I'm wrong about this.

**Comment by Samgisaninja** [comment]
Either way this is not an issue with unc0ver, so I'm closing, but if it has in fact been updated, please reply and lmk?

**Comment by tbagmoney** [comment]
There is a developer who has re-compiled a veency binary for ios 11 that works on my device. https://github.com/cosmosgenius/screendump/releases

In order for it to work on my 11.4.1 I had to install the three dependencies you listed above "MouseSupport 1.0" + "libstatusbar 0.9.9.0-1" + "SpringBoardAccess 0.3-5", but have no issues clicking left or right mouse. Those three dependencies, the standard PreferenceLoader, and dpkg -i of the debfile that I linked and I was good to go.

So glad to finally have this up and running! I just wish I had a way to incorporate TLS.

**Comment by bigrck64** [comment]
It's one awesome news !
Original thread of this release is here https://www.reddit.com/r/jailbreakdevelopers/comments/blt9y7/release_vnc_ios_11/

Cosmosgenius also want to make it work under iOS12, but he have problem about sandbox and backboardd, can anyone help ?

> I tried to make it work for iOS 12 but for some reason the VNC server doesn't start. The hook, keyboard and mouse are working, just the rfbinitserver doens't start the server. This only happens when injecting into backboardd. If hooked into SpringBoard or any other service the server starts, but then you don't have access to IOMobileFrameBuffer events so no screen.

**Comment by vintendpower** [comment]
Is there Any Update on ios 12 and Backoboardd?

**Comment by Samgisaninja** [comment]
This is *still* not an unc0ver issue, and this thread has apparently become a place for the eta kiddies to ask wen eta. Locked.
