### ISSUE TITLE
FaceTime Live Photo don´t work (FaceTime App)

### ISSUE THREAD

**Issue by Titanius** [pwn20wndstuff/Undecimus#913]
1. When take a "FaceTime Live Photo" in a FaceTime Video Call no LivePhoto saved in Photos app

2. iMessage crashes when recording a voice message

 - iOS Version: 12.1.2
 - iOS Device: iPhone 7 iPhone 8 and other
 - unc0ver Version: on all versions without tweaks installed

Thanks

**Comment by parrotgeek1** [comment]
I think apple disabled FaceTime live photos for anything older than 12.1.4 because of that FaceTime bug

**Comment by UnderEu** [comment]
> I think apple disabled FaceTime live photos for anything older than 12.1.4 because of that FaceTime bug

Exactly - not a u0 issue
