### ISSUE TITLE
Phone randomly hard freezes and takes up to 10 minutes to come back on

### ISSUE THREAD

**Issue by gradyhouston** [pwn20wndstuff/Undecimus#915]
**Describe the bug**
Phone will randomly hard freeze and be unresponsive for sometimes up to 10 minutes and then finally reboot. During the hard freeze, the screen is black and no combination of button-holding helps. When this happens and it finally boots back up, I'm obviously unjailbroken. It's happened 4 times so far and it's all been at random times. One time it happened while the phone was just hanging out in my pocket.

**To Reproduce**
No steps can make this happen

**Device (please complete the following information):**
 - iOS Version:  11.3.1
 - iOS Device:  iPhone X
 - unc0ver Version:  3.0.0-b48

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by WalshyDev** [comment]
Got any logs? Crash reports? Anything that can help find the root cause?

**Comment by gradyhouston** [comment]
CrashReporter doesn’t have any logs for this event. I’ll try to get some
syslogs. I may have to wait until right after it happens again.
