### ISSUE TITLE
unable to activate Face id after rootfs

### ISSUE THREAD

**Issue by Nahum95** [pwn20wndstuff/Undecimus#916]
**Describe the bug**
I was on beta 47 and I reinstalled the unc0ver app for upgrade to beta 48 after that I tapped on re jailbreak and  I got an error something with "failed to extract bootstrap"

(this is not my screenshot but very similar)
![u3g4ilc6vld21](https://user-images.githubusercontent.com/49001304/55668066-0b8d4d00-586d-11e9-8c52-9a730ee43525.jpg)

after tapping on OK the iPhone did a reboot so I had to jailbreak again, I got this error every time since with no one succeeded jailbreak process so I googled about the error and decided to do a rootfs and then re jailbreak again from the beginning
It helps with the error and the jailbreak process became much faster but before all of that, right after the rootfs reboot I started to get this errors about the face id.
I tried respring reboot even erase all contents and settings with no change
Is it possible to do a restore via futurerestore without changing the iOS version?

***recently I had a screen replacement while the iphone was jailbroken*** 
**Screenshots**
![IMG_0135](https://user-images.githubusercontent.com/49001304/55666929-358b4300-585e-11e9-9ce6-2ceb60a9f891.PNG)
![IMG_0137](https://user-images.githubusercontent.com/49001304/55666930-358b4300-585e-11e9-89df-242a0f40ff13.PNG)
![IMG_0136](https://user-images.githubusercontent.com/49001304/55666931-358b4300-585e-11e9-94f4-06316e07f342.PNG)

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone x
 - unc0ver Version: beta 48

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Comment by pugthelouie** [comment]
why are you posting this on Electra? This is a unc0ver issue.

**Comment by Nahum95** [comment]
> 
> 
> why are you posting this on Electra? This is a unc0ver issue.

u sure about it? 
I dont see here a word about electra
if u could give me a link to unc0ver issues I'll appreciate it

**Comment by WalshyDev** [comment]
@pugthelouie You're lost traveller. 

@Nahum95 This is the right place don't worry, sadly I don't know how to resolve your issue. I can't reproduce it myself.

**Comment by Nahum95** [comment]
Is it possible that the rootfs process damaged somehow my face id hardware?

**Comment by WalshyDev** [comment]
Nah it can't damage any hardware, it just restores the /root directory. Removes stuff like tweaks, Substrate etc. 

Does this persist after a reboot?

**Comment by Nahum95** [comment]
No nothing

**Comment by iAppleLuvr** [comment]
@Nahum95 Did you FutureRestore your iPhone X using iOS 12.2's SEP?

**Comment by Nahum95** [comment]
yes but I used 12.1.3's SEP
