### ISSUE TITLE
Anti-Revokes Not Working

### ISSUE THREAD

**Issue by ivanchau14** [pwn20wndstuff/Undecimus#919]
**Describe the bug**
My apps just got revoked after 2 weeks

**To Reproduce**
1. Go to tweakbox or any other app
2. Install and trust certificate
3. Wait 2 weeks

Device
 - iOS Version: 12.1.2
 - iOS Device: iPhone XS Max 
 - unc0ver Version: b49

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Yolokung** [comment]
Are you using Disable App Revokes feature on unc0ver or Anti Revoke app?
If you using Disable App Revokes, turn it off because his method doesn’t work on iOS 12 anymore.
