### ISSUE TITLE
Apt-get update doesn’t work

### ISSUE THREAD

**Issue by ThunderFlame5926** [pwn20wndstuff/Undecimus#920]
**Describe the bug**
Whenever I run apt-get update in mterminal I get this error ‘no sandbox user '_apt' on the system can not drop privileges’

**To Reproduce**
1. Launch a terminal
2. Run apt-get update as root

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1 beta 3
 - iOS Device: iPhone 7(9,3)
 - unc0ver Version: 3.0 beta 49

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
Error message ‘no sandbox user '_apt' on the system can not drop privileges’

**Comment by cakarlen** [comment]
Not able to reproduce this. I’m running the same iOS, iPhone (9,2), and used MTerminal
