### ISSUE TITLE
3rd Party apps

### ISSUE THREAD

**Issue by DarkPanther23** [pwn20wndstuff/Undecimus#923]
I had the Disable app revokes on, in my unc0ver jailbreak and all my 3rd party apps still got revoked so i deleted them and tried installing them again and they wont install anymore, no 3rd party apps like ignition etc are able to be installed they are just a grey box with the name under it and are not able to be opened.
![Image-1](https://user-images.githubusercontent.com/49375784/55689187-d6512f80-593e-11e9-97cc-17345055b9dd.jpg)
![Image-1 (1)](https://user-images.githubusercontent.com/49375784/55689210-0698ce00-593f-11e9-998d-935e9241b711.jpg)

**Comment by Yolokung** [comment]
What iOS version are you on?
If it’s iOS 12 and higher, disable it because Pwn20wnd has said that Apple have fixed his method of disabling App revokes.

**Comment by epicstory1994** [comment]
I’m having the same issue how can I fix my phone is unjailbroken because it died

**Comment by WalshyDev** [comment]
Ignition and other services all got revoked hence why they aren't working. This is not an issue related to unc0ver, please go and check their Twitter's to keep up to date.

**Comment by DarkPanther23** [comment]
Well one of the problems that all of the websites are saying is that usually the reason they don’t install is because there is one of them installed already

**Comment by epicstory1994** [comment]
Got it rejailbroken this morning around 7am the servers must work only during  certain  Hours

**Comment by epicstory1994** [comment]
But it died again so I’m stuck at the same point again

**Comment by DarkPanther23** [comment]
Yep you guys are right I didn’t realize that ignition and alll that was being revoked
