### ISSUE TITLE
iPhone 6+ A1522 Kernel Panic while trying to jailbreak with reload system daemons

### ISSUE THREAD

**Issue by xMilesManx** [pwn20wndstuff/Undecimus#926]
---
name: bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
I've spent extensive time testing the new beta on my phone but it seems that this issue will not go away. I first thought it was a problem with tweaks I have installed so I decided to restore rootFS and test.

This is what happens to my device: the jailbreak process will proceed normally and succeed. The device will then respring. The respring process takes up to anywhere between 30 seconds to 5 minutes and instead of loading springboard normally, the device will kernel panic and reboot. 

It seems inconsistent. Before restoring rootFS, success with reloading system daemons set to ON was nearly impossible. After restoring rootFS the panic occurs roughly 3/10 tries.\

Just to be perfectly clear, these panics are with ZERO tweaks or additional dependencies installed. Only the essential updates from cydia. 

I can't really read these logs, but my guess is that watchdog timer is killing the system after 90 seconds.

The issue was MUCH MUCH more common with tweaks installed. If I had xenhtml, snowboard, and a few that use rocketbootstrap, I simply could not jailbreak with reload system daemons at all without the device rebooting.

**To Reproduce**
1. Install Unc0ver
2. Jailbreak with restore rootfs - phone reboots
3. Jailbreak again - snapshot is saved and reboot
4. jailbreak again - installed cydia and reboots
5 Jailbreak again with load tweaks and reload system daemons ON
6 Device will either succeed or kernel panic.

**Screenshots**
none

**Device (please complete the following information):**
 - iOS Version: 12.1.2 Build 16C104
- iOS Device: iPhone 6+ A1522
 - unc0ver Version: b49

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**

[panic-full-2019-04-07-212717.760.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3052640/panic-full-2019-04-07-212717.760.ips.txt)
[panic-full-2019-04-07-131751.897.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3052641/panic-full-2019-04-07-131751.897.ips.txt)
[panic-full-2019-04-07-105734.689.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3052642/panic-full-2019-04-07-105734.689.ips.txt)

I can do any sort of testing or provide any helpful follow up information if needed.

Thank you for this amazing jailbreak!

**Comment by WalshyDev** [comment]
It's a known issue tweaks can cause this, I believe it had to do with them using old/broken hooks in Substrate. I recommend just updating any tweaks you know cause this (things like RocketBoootstrap and Snowboard are updated for this already). If an app doesn't have an update to fix this but has the issue then contact that developer. 

This isn't something that can be fixed in unc0ver.

**Comment by xMilesManx** [comment]
Hey thanks for your response. 

If you reread the description, I explain that this happens after I have restored rootFS and with zero tweaks installed. 

I will also like to add to this, that I believe this issue has persisted since the a7 support was added.

**Comment by xMilesManx** [comment]
I plan on performing a full restore to 12.1.2 with future restore and installing u0 on my blank device to test over the next few days.

**Comment by kirand777** [comment]
The same on iPhone 6, iOS 12.1.1 beta3

**Comment by datitisev** [comment]
Same to me, was only able to jailbreak once since (and then jb kernel panicked later on).

iPad Air (2,1), iOS 12.1.1

**Comment by xMilesManx** [comment]
For anyone who cares about this, this issue seems to have been finally fixed on the latest release. There are other problems on the iPhone 6 that still persist with random reboots and app freezes.
