### ISSUE TITLE
Cydia freezing my device

### ISSUE THREAD

**Issue by iAppleLuvr** [pwn20wndstuff/Undecimus#927]
**Describe the bug**
While Cydia is refreshing sources, the spinning logo freezes up, and it freezes the whole device up, not just the Cydia app, forcing me to reboot.

**To Reproduce**
1. Open Cydia
2. Refresh sources
3. Sometimes it refreshes like it is supposed to, but sometimes it freezes up.

Happened twice within a 24-hour span.

**Screenshots**
N/A

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: b49

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
panic-full April 7: https://pastebin.com/qNvXD30T

panic-full April 8: https://pastebin.com/xx0c7Krd

**Comment by iPhoneShqip** [comment]
I have same issue iPhone 8 iOS 12.1.2 on beta 48 never have that problem but now have that when i reload Cydia hope is going to fix or need to downgrade beta 48

**Comment by thekio1984** [comment]
Ive never had reboots this bad before (like only 2 since b29) now every couple hours, i was thinking it might be the memory fix in b49, sincee i never had reboots before, that patch imo, wouldnt apply to my device, ive uninstalled it & so far over an hour without even a lag or crash, let alone a reboot 🤞🤞

**Comment by spikesF** [comment]
I think this freeze is not related to cydia, it’s related to jailbreak(u0) or substrate cause after b49 update freezes happen more and more (it’s happen after specific amount of time, total unresponsiveness & freeze).
I dont how to get any log but Ill try.
