### ISSUE TITLE
Having substrate 0.9.7011 induced lockups leading kernel panics on iPhone 6 plus iOS 12.1.1 beta with the latest u0 (b49)

### ISSUE THREAD

**Issue by soum91** [pwn20wndstuff/Undecimus#928]
**Describe the bug**
With the latest update of u0, the substrate induced lockups seem to be reappearing. Had 2/3 such kernel panics. Also had an overnight reboot, which I didn't experience after modifying jetsamproperties plist on iOS 12. Also, **Reload system daemons** still leads infinite respring following reboots just like #927 .

**To Reproduce**

1. Install the latest u0 beta on iPhone 6 plus (most probably on any A7/8 device)
2. Use the phone normally
3. You will encounter this at one point of using the phone

**Screenshots**
N/A

**Device (please complete the following information):**
 - iOS Version: 12.1.1 beta 3
 - iOS Device: iPhone 6 plus
 - unc0ver Version: 3.0.0~b49

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present on the latest version of unc0ver
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore

**Logs**
[panic-full-2019-04-08-071029.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3055992/panic-full-2019-04-08-071029.ips.txt)
[panic-full-2019-04-09-003634.981.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3055993/panic-full-2019-04-09-003634.981.ips.txt)

**Comment by xMilesManx** [comment]
I posted this exact same bug report yesterday. It happens even after a rootfs restore with zero tweaks installed. 

My report was #926

**Comment by heat200** [comment]
I'm also experiencing kernel panics on b49 (iPhone 6s iOS 12.1.1)

**Comment by drifter3179** [comment]
I have the same issue on iphone x ios12.1.1 b3 no tweaks or otherwise and after restore root fs
