### ISSUE TITLE
Safe Mode by switching from wifi to 4G

### ISSUE THREAD

**Issue by sector1979** [pwn20wndstuff/Undecimus#929]
You can try by yourself

Issue present on all Betas from b29 to the last b49

When you are from long time connectecd to a wifi network or 4G data and you switch from them, you will have a Safe Mode Resprings .

**Comment by xMilesManx** [comment]
This is not true. You have a conflicting tweak. Maybe something to do with the networking? Tetherme?
Uninstall your tweaks 1 by 1 to diagnose

**Comment by sector1979** [comment]
i was listening something about CC Support that i have installed , but i need of it.  No other related tweaks for network

**Comment by xMilesManx** [comment]
Well if you uninstall that and it fixes your problem, that is a tweak problem. Contact the developer of the tweak. 

This isn’t related to the jailbreak code itself so you might want to close this issue.
