### ISSUE TITLE
Failed to extract bootstrap : cant remove hackyouriphone.appsyncunified

### ISSUE THREAD

**Issue by devcline** [pwn20wndstuff/Undecimus#931]
ok so the news today i tried a b49 and its no more gives me a libssl error as i had before in https://github.com/pwn20wndstuff/Undecimus/issues/530 ,  but still no success
i reset a ipad settings (not content) before using a unc0ver, i dont know if its a new version or because of my reset.
something new: it cant remove hackyouriphone.appsyncunified
```
errno: 0
appInstall [@[@"-f"])
filename: jailbreakViewController.m
line: 1884
Desc: Failed to extract bootstrap
```
![image](https://user-images.githubusercontent.com/617020/55821479-eb27f180-5afd-11e9-86d8-66ccca83c662.png)

tried to restoreFS and no tweaks , no daemons and dont reload system daemons, reinstall cydia, airplaine is on

cant jailbreak, but the good news, no more libssl error

**Comment by Samgisaninja** [comment]
if you uninstall the stolen version of appsyncunified, it will work. the official repo for ASU is https://cydia.angelxwind.net

Pirated packages are often misconfigured and may unintentionally damage your device. Pirated packages may also contain malware designed to intentionally damage your device. 

Please don't steal. 

Thanks for coming to my TED talk ;P
