### ISSUE TITLE
unc0ver crashes immediately 

### ISSUE THREAD

**Issue by RedPetroleum** [pwn20wndstuff/Undecimus#935]
**Describe the bug**
When trying to open the App it crashes directly. 
I tried various versions via cydia impactor or from jailbreaks.fun. I trusted the profile, no iOS update is downloaded and everything used to work perfectly fine a few days ago... 

**Device (please complete the following information):**
 - iOS Version: iOS 12.1
 - iOS Device: iPhone SE
 - unc0ver Version: 44, 48, 49

**Place an "x" between the brackets if true:**
 - [x] this issue is present on the latest version of unc0ver

**Comment by c0ff3e2r00t** [comment]
Have you updated your Cydia Impactor to the latest version? Earlier on I had the same issue but I realised my Impactor wasn’t updated.

**Comment by RedPetroleum** [comment]
> Have you updated your Cydia Impactor to the latest version? Earlier on I had the same issue but I realised my Impactor wasn’t updated.

This solves it. Thanks. I don't understand why though, because it also didn't work when I tried it over jailbreaks.fun, but this case is closed! :)
