### ISSUE TITLE
Help: uncover on ios 12.1.2  Errno 17 unable to rename system snapshot

### ISSUE THREAD

**Issue by cr7hmood** [pwn20wndstuff/Undecimus#937]
Hey guys 

My phone is x   64gb    

When i try to jailbreak wit uncover 

It is freez on 2   And   End up with :

Error (Fatal)

Errno:17

Test:fs_snapshot,origfs, 0)==ERR_SUCCESS

Filename:jailbreakViewController.m
Line:1191

Function:jailbreak

Description:Unable to rename system snapshot.Delet OTA file from Setting -storage if present and reboot

**Comment by cr7hmood** [comment]
I did every thing on your maind guys and it did not work .. i download the ios ubdate again and delet it  i run uncover with airplan mode   I  reset rootfs but it give me always sam error 17 and freez

**Comment by PenetratingShot** [comment]
Try factory restoring your device?

Then make sure the OTA isn't there. Then install the OTA, switch to airplane mode once it installs, then delete the OTA, and then try clicking 'Jailbreak' again.

I really don't know at this point :/

**Comment by tacion01** [comment]
have you solve this problem? i have the exact problem on my iphone x 64gb too

**Comment by cr7hmood** [comment]
i have not solve this problem i end up with yupdate my ios to 12.2 and now i am waiting for another jailbreak ☺

**Comment by tacion01** [comment]
bruh

**Comment by tacion01** [comment]
have you tried restoring it?

**Comment by cr7hmood** [comment]
Why restoring it ..i update  my iphone so now i can not downgrade it again ...but before that i tryed every thing  you can imaging and still same problem

**Comment by cr7hmood** [comment]
There is no fixing this so  finaly you have to update your phone and no jailbreak for us

**Comment by YRNZero** [comment]
Hey still need help?
