### ISSUE TITLE
can't build success

### ISSUE THREAD

**Issue by LeafMine** [pwn20wndstuff/Undecimus#939]
Can't build success cause there is no offsetcache.h and offsetcache.c file in source code.It's just a reference.

**Comment by Merculous** [comment]
Figured it out. Do 'git submodule update' in the branch. This will fix the issue.

**Comment by vegerot** [comment]
Not working for me :(.  Would someone be able to upload and post the file on their own?

Edit: While `git submodule update` doesn't work, recloning the repo with `git clone --recursive` does work 🤷🏽‍♀️
