### ISSUE TITLE
Unable to connect to VPN

### ISSUE THREAD

**Issue by guofuz410510** [pwn20wndstuff/Undecimus#940]
jailbreak  cannot connect to the VPN 
, but non-jailbreak VPN connect success

**Device (please complete the following information):**
 - iOS Version: 12.1.2 12.1
 - iOS Device: iphoen7
 - unc0ver Version:  b49

**Comment by udomoody** [comment]
Got the same problem. Updated from b46 to b49 and VPN doesn't connect in jailbroken mode anymore. Downgrading back to b46 didn't solve this issue.

**Comment by cdlenfert** [comment]
I'm seeing the same since the b49. More details on my Reddit post. https://www.reddit.com/r/jailbreak/comments/bbo9ya/help_vpn_will_not_connect_when_jailbroken_works/
In short some success has been seen by keeping Reload System Daemons set to OFF, but it's a mixed bag. Newly installed packages in Cydia:

- System Memory Reset Fix 1.0
- Trust Cache Injector 0.4~b5
- Jailbreak Resources 1.0~b11.5
- CA Certs 0.0.2
- OpenSSL 1.0 Libraries 1.0.2r-1

**Comment by udomoody** [comment]
I now removed System Memory Fix and downgraded all the other packages to the version that comes with b46, but the issue still persists. 
I don‘t want to try restore rootfs yet, but maybe that helps

**Comment by tesanovic** [comment]
For me show connecting and never finish but when I try vpn work

**Comment by Zzad** [comment]
Upgrade from b46 to b49 prevents VPN from connecting on both iPhone X and iPad Mini 4.
@tesanovic is correct though - even though it doesn't show connected, it still seems to work.

**Comment by udomoody** [comment]
@tesanovic can‘t confirm that. No matter how long I let it sit on connecting, my IP is still the same. So VPN is not working.

**Comment by cdlenfert** [comment]
@Zzad @tesanovic I also have the same experience as @udomoody, waiting a long time and no change in IP address. Pinwheel graphic by carrier in status bar indicating network activity just keeps spinning so long as "connecting..." status exists in VPN settings.

**Comment by MiRO92** [comment]
I have the same issue with uncover beta 49, any fix yet?

**Comment by neo1728** [comment]
I have the same issue with uncover beta 49 and 50.

**Comment by bridge-1** [comment]
@cdlenfert It seems to work nondeterministic. Sometimes it allows access to VPNed network, sometimes not. But it doesn't change your IP, that's correct, so gateway is not changed to VPN's.

**Comment by Zhoki86** [comment]
Plus, I have the same problem. IOS 12d.1.1 Iphone 6s, unc0ver b49 and b50(

**Comment by neo1728** [comment]
hi,hope this can help you:

1, open your unc0ver, setting--> only  restore rootfs  on ，else off 

2, press  re-jailbreak  then , will restart your iphone

3, use   unc0ver v3 b48 , jailbreak  as usual  ，then in  **jailbroken**  VPN  worked.

4, you will lost all your tweak in cydia, you must reinstall.

**Comment by Zhoki86** [comment]
> привет, надеюсь, это поможет тебе
> 
> 1, откройте unc0ver, установив -> только восстановить rootfs на ， еще отключено
> 
> 2, нажмите повторно джейлбрейк затем перезагрузит ваш iphone
> 
> 3, используйте unc0ver v3 b48, джейлбрейк, как обычно, затем в **взломанном** VPN работал.
> 
> 4, вы потеряете все свои настройки в Cydia, вы должны переустановить.

unfortunately these procedures did not help

**Comment by neo1728** [comment]
> > привет, надеюсь, это поможет тебе
> > 1, откройте unc0ver, установив -> только восстановить rootfs на ， еще отключено
> > 2, нажмите повторно джейлбрейк затем перезагрузит ваш iphone
> > 3, используйте unc0ver v3 b48, джейлбрейк, как обычно, затем в **взломанном** VPN работал.
> > 4, вы потеряете все свои настройки в Cydia, вы должны переустановить.
> 
> unfortunately these procedures did not help

https://www.reddit.com/r/jailbreak/comments/bbo9ya/help_vpn_will_not_connect_when_jailbroken_works/

you need to see shure_peach's reply

**Comment by Zhoki86** [comment]
> > > Привет, надеюсь, это поможет тебе 
> > > 1, открой unc0ver, установил -> только восстановил rootfs на ， еще отключено 
> > > 2, а затем снова перезагрузил ваш iphone 
> > > 3, используйте unc0ver v3 b48, джейлбрейк, как обычно, затем в **взломанном** VPN работал. 
> > > 4, вы должны переустановить.
> > 
> > 
> > к сожалению эти процедуры не помогли
> 
> https://www.reddit.com/r/jailbreak/comments/bbo9ya/help_vpn_will_not_connect_when_jailbroken_works/
> 
> вам нужно увидеть ответ shure_peach

Ооо спасибо боьшое, заработал  ))

**Comment by Macley-Kun** [comment]
So for the people who also are having this problem, the extra thing i did was to disable reload system daemons.

I hope a fix will soon be implemented.

**Comment by Gr8z** [comment]
Tried all the solutions above, not working. Works fine in unjailbroken state.

**Comment by cjsworld** [comment]
Same problem with 3.0.1. For now, restore rootfs and downgrade to b48 is a working solution, hope that will be fixed in new version.

**Comment by Simanias** [comment]
To bad, I'm having the same issue on iPhone X with iOS 10.1.2 and undecimus 3.0.1.
Hopefully a solution is coming quick.....

**Comment by Zzad** [comment]
Glad to report 3.1.0 solved the "VPN stuck on Connecting" issues on my iX as well as ipad mini 4. Connects as if not jailbroken.
Propose to close the issue as resolved.

**Comment by Macley-Kun** [comment]
Can confirm aswell on iPad 2018 12.1.1 (ipad 7,5).
Thank you for solving the issue! @guofuz410510 update, rejailbreak, and try your vpn again, should work for you aswell. Don't forget to close the issue aswell :-)

**Comment by Gr8z** [comment]
Working again after the 3.1 update on iPhone 6s+ (8,2)

**Comment by nidaldz** [comment]
For my I still  have the issue with my iPhone 7 iOS 12.1.2 jailbroken with v3.1.2... tried many vpn types but nothing :( I don’t have restore rootfs because I don’t wont to lose all my personalisation jail break setting!

**Comment by neo1728** [comment]
> 对于我，我仍然有我的iPhone 7 iOS 12.1.2与v3.1.2越狱的问题...尝试了许多vpn类型，但没有:(我没有恢复rootfs因为我不会失去我所有的个性化监狱打破设定！

unc0ver 3.2.1 fixed this issue.
