### ISSUE TITLE
Random Reboots during the day

### ISSUE THREAD

**Issue by TheSniperzzz** [pwn20wndstuff/Undecimus#943]
**Describe the bug**
Phone randomly reboots: a black screen appears, after a couple of seconds the apple logo appears and the phone reboots.
It happens during the 3rd or 4th day of uptime.
The 2 logs happened while using beta49. The first one while taking a photo, the second one while launching the photo app. 

With older betas, I got it while reading a notification and while using reddit, so it looks like it's not related to what I'm doing when the reboot happens. 
I do not have any random respring and with latest beta I do not get night reboots.

**To Reproduce**
No idea what causes it.

**Device (please complete the following information):**
 - iOS Version: iOS 12.1.1 beta 3
 - iOS Device: iPhone 5s
 - unc0ver Version: v3.0.0~b49

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[panic-full-2019-04-09-150930.984.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3073453/panic-full-2019-04-09-150930.984.ips.txt)
[panic-full-2019-04-12-092851.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3073454/panic-full-2019-04-12-092851.ips.txt)

**Comment by spikesF** [comment]
today the issue freeze as black screen then restart(b49 introduce alot of freezes and sluggishness for the device)
