### ISSUE TITLE
Device freezing at black sceeen with the need of reboot

### ISSUE THREAD

**Issue by samtaborsky** [pwn20wndstuff/Undecimus#945]
**Describe the bug**
My device sometimes just freezes and cannot be unlocked or manipulated, I have to hard-reset the phone to use it. Happened to me with the last few betas even with no tweaks installed. It does not reboot, just freezes and I need to hard reset. And sometimes when I hard reset it, for a half a second I the phone unfreezes and reboots. It is really just few miliseconds.

**To Reproduce**
1. Install the latest beta of unc0ver.
2. Use your phone normally.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone SE 
 - unc0ver Version: b49

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce - not sure
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by spikesF** [comment]
https://github.com/pwn20wndstuff/Undecimus/issues/943#issuecomment-482783061

**Comment by cyberfunk** [comment]
I'm still having the black screen unable to wake issue. The phone is still active ( I get notification sounds and vibration) I just can't revive the display. If I plug it back into CarPlay I can get it functioning on my radio screen but the phone itself will not wake without a hard reset.

samtaborsky Is this what happens to you. Can you tell that the phone is still rnuning in the background but can't wake the screen? My phone freezes as well sometimes.

**Comment by samtaborsky** [comment]
@cyberfunk no, my phone hard freezes, I get no notification sounds, no vibrations, nothing. Even when I try to switch the mute button on the iPhone, it does nothing. The only thing that *sometimes* keeps working is the music and bluetooth (I have AirPods and I do not hear the disconnect sound). And after I press the home button and the lock button to hard reset it, for a fraction of a second the phone unfreezes, does its vibrations from the mute switch and restarts.
