### ISSUE TITLE
Random Phone Freezing

### ISSUE THREAD

**Issue by mehrexe** [pwn20wndstuff/Undecimus#946]
**Describe the bug**
Hi, I've been having issues with my iPhone X (A1865) since the late b30 updates of Unc0ver where there's freezing or random rebooting. Now, in b49, so far I haven't experienced the random reboots (then again, I've had it for a day or so). But last night I plugged by phone in at 10:30pm and went to bed setting alarms for around 4am since I had to take care of something at work. I woke up at 10am, and my phone was completely off until I had to use the power up+power down+home combo to restart it. 

My phone also freezes on occasion and crashes some apps like Tetris (the dumb EA one, which is the only one that's legally allowed). 

**To Reproduce**
Use the phone normally. 

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1 beta 3 (16C5050a)
 - iOS Device: iPhone X, A1865
 - unc0ver Version: b49

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**

I'm unsure of how to secure logs; if someone would be willing to help me find them, I could post it.

**Comment by Koleman1312** [comment]
This happens to me also and I’m on iPhone 6. Just sometimes I try to press home button and nothing works. Siri doesn’t open, application switching doesn’t work, screen won’t turn off and I have to hard reset it.

**Comment by batboy710** [comment]
I’m having the same issue on my iPhone X, it usually starts by an app crashing, and all the apps in the app switcher turn white. A few seconds later it stops responding and the only way to fix it is to hard reset.
