### ISSUE TITLE
changes to build on XCode 10.0 vs. XCode 10.1

### ISSUE THREAD

**Issue by resistor4u** [pwn20wndstuff/Undecimus#947]
My laptop has xcode 10.0, and not enough space to upgrade to 10.1. Building from the command line fails because `Undecimus/Undecimus/source/machswap_offsets.m` includes `CPU_SUBTYPE_ARM64E`, which is unidentified on xcode 10.0. I made the following changes on my local files, but I don't know whether the changes would break building on xcode 10.1. Is there a way to consolidate both?

```
...
//     .cpu_subtype = CPU_SUBTYPE_ARM64E,
     .cpu_subtype = CPU_SUBTYPE_ARM64_V8,
     .cpu_subtype = CPU_SUBTYPE_ARM_ALL,
...
```

**Comment by clarityzzz** [comment]
XCode 10.1 brings support for ARM64e.
You can't do it on 10.0 because it doesn't support it.
ARM64e is needed for A12(X) support.
