### ISSUE TITLE
Fatal Error: 0

### ISSUE THREAD

**Issue by Stefanuk12** [pwn20wndstuff/Undecimus#948]
Error Message as follows:

**Error (Fatal)**
Errno: 0
Test: WEXITSTATUS(rv) == ERR_SUCCESS
Filename: JailbreakViewController.m
Line: 1924
Function: jailbreak
Description: Failed to extract bootstrap.

---
It seems to happen after trying to do something with this tweak/theme:
com.hackyouriphone.noctis12

When I disable Tweaks it still errors same with when I disable Deamons. 

---

iOS 12.1.2 | unc0ver b49

**Comment by VinnyK0112** [comment]
don't pirate tweaks

**Comment by sathvik321** [comment]
Have you figured out how to fix this without having to use restore rootfs in unc0ver? I'm having the same problem with the same repo, but I still haven't figured out how to remove tweaks while unjailbroken. Can't go into safe mode either.
