### ISSUE TITLE
Snapchat reboots device 

### ISSUE THREAD

**Issue by Hypnos623** [pwn20wndstuff/Undecimus#951]
About once a day when I open snapchat or take a photo with it, my device reboots. For comparison I probably open the app about 20 ish times a day. I'm on an iphone 6, on ios 12.0 using b49

**Comment by 13XxM1CHA3lxX37** [comment]
Tweaklist?

**Comment by Hypnos623** [comment]
7-zip (POSIX): 16.02-1
AdBlock for YouTube: 1.0.7
AppList: 1.5.14
AppStore++: 0.7-2
AppSync Unified: 32.0
APT (apt-key): 1.4.9-1
APT 1.4 Strict (libapt-pkg): 1.4.9-1
APT Command Line: 1:0-2
APT Strict (lib): 1.4.9-2
APT Strict: 1.4.9-1
Assuan: 2.5.1-1
AudioSnapshotServer: 1.0.0
Badge Customizer: 1.4.3-2
Base Structure: 1-5
BatteryPercentX [Public]: 1.2.1-1
Berkeley DB: 6.2.32-1
BetterCCXI: 1.4.8
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-1
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.3-3
CCSupport: 1.2-3
Cephei: 1.12
Cercube for YouTube: 4.2.2.10
CircleIcons: 1.1.3-15
ClearDock: 1.0-2
ColorFlow 4 (iOS 11 – 12): 1.2.2
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Cydia Installer: 1.1.32~b12
Cydia Substrate: 0.9.7032
Cydia Translations: 1.1.32~b1
Darwin Tools: 1-6
ddlc-ios: 2.0
Debian Packager: 1.18.25-11
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DontKillMyMusic: 1.2.0
Easy Notifications: 1.0-1
Eclipse 12 (iOS12): 6.0.4-7k
Essential: 0-1
FDots: 1.0.0-4
file: 5.35-2
Filza File Manager: 3.6.4
Find Utilities: 4.6.0-2
Flame: 1.3
FlatSafariURL: 0.0.1
Flipswitch: 1.0.15
FloatingDock: 1.5
gettext: 0.19.8-1
Gif2Ani V2: 2.1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
Hide Labels: 0.0.1-10
HighDate: 0.0.1
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.7.1
IconSupport: 1.11.1
iOS Firmware: 12.0
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b11.5
Jellyfish: 1.0.2
KarenLocalizer: 1.0.4
KarenPrefs: 1.4
KSBA: 1.3.5-1
LetMeBlock: 0.0.1
libbulletin: 0.1-145
libCercube: 1.1.1
libcolorpicker: 1.6-1
libCSColorPicker: 1.0
libCSPreferences: 1.1.1
libidn2: 6.1.2-1
libmitsuha: 0.1.5
libnepeta: 0.1.1
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libRocket: 1.0.5
libSparkAppList: 1.0.1-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LocalIAPStore: 1.4-2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MDausch Utils: 0.0.2
Melior [Public]: 1.0.6-1
MessageBubbles: 0.2.2
MessageColors: 1.5
MitsuhaXI: 0.5.5
Muze 4: 1.04
Nettle: 3.4-2
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NoBlur: 1.6.2
Notifica: 0.2.7
OpenSSL 1.0 Libraries: 1.0.2r-1
OwO: 0.2.1
p11-kit: 0.23.12-1
PassBy: 1.8.3
plutil: 0.1.0
PM, really?: 1.2
Poseidon: 2.3.0-1+debug
PreferenceLoader: 2.2.3-3
PreferenceOrganizer 2: 4.0.5
Profile Directory: 0-1
PullToRespring: 1.2
readline: 8.0-1
RealCC: 1.0.1
ReProvision: 0.4.2
Rocket for Instagram: 3.3.5
RocketBootstrap: 1.0.6
RomanPasscode: 2.1
Safari Plus: 1.6.7
sed: 4.5-1
Selector: 0.1.1
shell-cmds: 118-8
Signing Certificate: 0.0.1
SmallSiri: 1.2.1
SnowBoard: 1.0.1
Spotilife: 1.0
Substrate Safe Mode: 0.9.6001.1
Sylph: 1.1~Beta.1
System Memory Reset Fix: 1.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4~b5
tweakCompatible: 0.1.5
TweakConfigurator: 0.3
uasharedtools: 2.1r-66
UIKit Tools: 1.1.13-5
unrar: 5.6.4-1
unzip: 6.0-1
XZ Utils: 5.2.4-4
zip: 2.32-1
