### ISSUE TITLE
Random freeze on A12 partial jailbreak (b49)

### ISSUE THREAD

**Issue by Oakman978** [pwn20wndstuff/Undecimus#956]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
I was just browsing twitter as usually, screen randomly turned black and rebooted. Checked analytics and there was a panic log.

**To Reproduce**
I’m not exactly sure how to reproduce this, as it has never happened before, but I have a panic log.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1 
 - iOS Device: 11,6 XS Max
 - unc0ver Version: 3.0.0b49

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [?] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
https://drive.google.com/file/d/1CPLiXzygzJvWJ_KnWFV6YXqHtBhutxqU/view?usp=drivesdk

**Comment by 2600box** [comment]
I had a similar experience on iPhone XS 12.1 and b49. My phone was in my pocket and when I wanted to open it, it was frozen. See attached log.

[panic-base-2019-04-12-180214.txt](https://github.com/pwn20wndstuff/Undecimus/files/3082560/panic-base-2019-04-12-180214.txt)
