### ISSUE TITLE
Ability to toggle the logging window that's seen on Beta versions in the Release Version.

### ISSUE THREAD

**Issue by Techman749** [pwn20wndstuff/Undecimus#958]
I think it'd be pretty neat to be able to see the logging window in release versions of Unc0ver. 

Make it a toggle or something like that, perhaps? However you want to execute the idea or not at all is fine with me. I just like to watch the text scroll as it's actually jailbreaking. I'd make it opt-in though. If the user wants to see the log window, then they have to go and switch it on.

Call it "Developer Mode", "Verbose Mode", or whatever.

**Comment by clarityzzz** [comment]
Just use the Beta version while it isn't merged with the Master Version? There's no point in using current release versions. Since B29, all of these betas could already be latest release version, but they're not because they chose to only make them release version whenever A12 support is added.

**Comment by Techman749** [comment]
@clarityzzz I was meaning this be a feature in the final version of 3.0.0. I'm using Beta 50 as of this posting. I was just saying that I enjoy seeing the logging window as do many other users of the betas, I'm sure. So I thought it'd be a good idea.

**Comment by Techman749** [comment]
3.0.0 adds this feature. Thanks Unc0ver team!
