### ISSUE TITLE
12.1.2 on Xs. Cydia

### ISSUE THREAD

**Issue by reggie88980** [pwn20wndstuff/Undecimus#962]
Still no cydia after JB. Restart springboard function is also not functional

**Comment by ShotSkydiver** [comment]
🤦‍♀️

**Comment by Techman749** [comment]
@reggie88980 A12 and A12X devices don't currently have any type of Tweak Injection as of this comment. That's why Cydia and Cydia substrate isn't included on A12/A12X. Wait for an update.
