### ISSUE TITLE
Panic on Xs Max ios 12.1.1 latest unc0ver b50

### ISSUE THREAD

**Issue by Akasuo** [pwn20wndstuff/Undecimus#963]
**Describe the bug**
It happens from time to time to freeze then restart. Last time happened when i woke up the phone. I’ve attached a panic log. 

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: Xs Max
 - unc0ver Version: 3.0.0b50

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
https://www.dropbox.com/s/nqmvem0nfy70ao8/panic-full-2019-04-17-133035.900.ips?dl=0

**Comment by 2600box** [comment]
These are the same kind of panics that I get with sks timeout on XS. 

`"panicString" : "panic(cpu 0 caller 0xfffffff01f77d4e4): \"sks request timeout (20 strikes)\"@\/BuildRoot\/Library\/Caches\/com.apple.xbs\/Sources\/AppleKeyStore\/AppleKeyStore-639.230.1\/AppleKeyStore.cpp:2515\nDebugger message: panic\nMemory ID: 0xff\nOS version: 16C50\nKernel `

`"panicString" : "panic(cpu 1 caller 0xfffffff01159d8a4): \"sks request timeout (20 strikes)\"@\/BuildRoot\/Library\/Caches\/com.apple.xbs\/Sources\/AppleKeyStore\/AppleKeyStore-639.220.5\/AppleKeyStore.cpp:2515\nDebugger message: panic\nMemory ID: 0xff\nOS version: 16B92\nKernel`

**Comment by fatall1ty** [comment]
@2600box  @Akasuo  Did you solve the problem?
