### ISSUE TITLE
Refresh icon cache doesn’t work after restoring rootFS on the latest unc0ver.

### ISSUE THREAD

**Issue by pacifico27** [pwn20wndstuff/Undecimus#968]
**Describe the bug**
Whenever I try to restore rootFS, after restoring, it does not delete cydia from the home screen or well refreshes the icon cache.

**To Reproduce**
Restore RootFS
**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: 3.0.0 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Screenshots**

![IMG_0039](https://user-images.githubusercontent.com/41550418/56482048-ead11400-6476-11e9-97d9-f5bb582ec16f.PNG)
![IMG_0040](https://user-images.githubusercontent.com/41550418/56482051-ef95c800-6476-11e9-8439-4e661d06b8f8.PNG)

**Logs**

[diagnostics - Copy.txt](https://github.com/pwn20wndstuff/Undecimus/files/3102067/diagnostics.-.Copy.txt)

**Comment by xMilesManx** [comment]
It works just fine for me...

**Comment by mad2909** [comment]
Same on me, Iphone 8+

**Comment by pacifico27** [comment]
i uploaded the log, is there something wrong?
