### ISSUE TITLE
Cydia freezes and reboots device even on the latest unc0ver (official v3.0.0 release)

### ISSUE THREAD

**Issue by iAppleLuvr** [pwn20wndstuff/Undecimus#977]
**Describe the bug**
I was adding a repo to Cydia, and once I pressed "Add Source," it started adding it for a few seconds then it froze my whole device. I waited for it to reboot completely in order to get a panic-full log, which I will link here.

**To Reproduce**
1. Go to "Sources" tab
2. Click "Edit"
3. Click "Add"
4. Add source URL and press "Add Source"
5. Wait for it to freeze your device while adding the source (doesn't happen all the time, but still happened twice to me so far).

**Screenshots**
N/A

**Device (please complete the following information):**
 - iOS Version: iOS 12.1.1
 - iOS Device: iPhone X
 - unc0ver Version: v3.0.0 official release

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
panic-full: https://gist.githubusercontent.com/iAppleLuvr/3470129caa15adcc7279f1c387d7b152/raw/98d32f4904da1b33006de00da1001425fdcb7800/gistfile1.txt

**Comment by iPhoneShqip** [comment]
I have same issue i move to b46 and no freeze hope that going to fixed soon
