### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by haykam821** [pwn20wndstuff/Undecimus#98]
The [current 3 screenshots](https://github.com/pwn20wndstuff/Undecimus/blob/a993eeddd07d740249748e233863953ff7d4dba3/README.md#screenshots) are on an old version of unc0ver. These should be updated to screenshots on v1.1.1 with an iPhone X to showcase recently added features and support for the bigger screen.

**Comment by Samgisaninja** [comment]
I'll do this shortly.

**Comment by haykam821** [comment]
Don't close an issue when you're going to do it, close it when you *do* in fact do it.

**Comment by Samgisaninja** [comment]
fake news!
