### ISSUE TITLE
hotspot not working

### ISSUE THREAD

**Issue by ff4goods** [pwn20wndstuff/Undecimus#983]
**Describe the bug**
upon installing and jailbreakign using newest uncover ipa (3.0.1) while jailbroken, personal hotspot is no longer working. i must rest phone and get off the jailbreak in order to use the hotpsot, this was not an issue in earlier ipas. please look into this and fix if possible thank you

**To Reproduce**
jailbreak using 3.0.1
turn on personal hotspot
try to connect to internet using another device as a laptop.
will nto connect
reset phone, getting off the jailbreak
try to connect to hotspot
connects no problem

**Device (please complete the following information):**
 - iOS Version: 12.0
 - iOS Device: iphone 7s
 - unc0ver Version: 3.0.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by DimaJedi** [comment]
Same for my device
iPhone x 12.1.2 3.0.1 unc0ver

**Comment by Lascarfo** [comment]
same prblm
iPhone SE, 12.1.2, unc0ver: 3.0.1

**Comment by AliTweel** [comment]
iPhone 8+, 12.1.1, unc0ver: 3.1.1
This one was driving me crazy until I found out by google that is a JB related!
how come it's since 3.0.1 and still not resolved??

**Comment by teefixx** [comment]
Same here
IPhone 7
12.2
Unc0ver 3.3.2 (edit: same on 3.4.2)

Hotspot works randomly, mostly not. 
Hotspot is always visible but devices cannot log in 
„Remote Hotspot Error“

Update: iOs 12.4 and unc0ver 3.5.5 seems to Partially solve the problem

**Comment by f-bone** [comment]
Can't start my iPhone's hotspot from my jailbroken iPad Pro 2015. Running v3.5.6. Seems that there are still issues.

iPhone 8+ not jailbroken.

**Comment by Sufyanpahore** [comment]
Same problem with my iPhone 5s iOS 12.4 . In jailbreak state any other device doesn’t connect by After restart , it’s working in unjailbroke state.plz fix this issue.other devices says that “could not obtain IP address.
