### ISSUE TITLE
Forced to update to 12.2 

### ISSUE THREAD

**Issue by camerontheobald** [pwn20wndstuff/Undecimus#984]
I woke this morning to an update complete on my lock screen I unlocked my phone and followed the instructions of swiping up to complete update then it crashed and went back to home screen so I force restarted my phone where it proceeded to go to the apple logo and just stayed there it would boot or even connect to the computer until I put it recovery mode in which I was forced to update I was using unc0ver 3.0.1 on iPhone X 12.1.1

**Comment by ProfessorRadish** [comment]
Same issue except it happened after a respring from installing a new tweak after using the new release.

**Comment by MysticTheProtogen-TechWiz** [comment]
You Should Have Had A Ota Blocker To Keep Your Phone From Auto Updating No Matter What There is One You Can Download On ZJailbreak.

**Comment by camerontheobald** [comment]
I did I even had the tv os profile installed it was all there yet I still happened

**Comment by MysticTheProtogen-TechWiz** [comment]
What The Hell

**Comment by ProfessorRadish** [comment]
I’m really not sure my device had even actually updated. I had updates disabled where I couldn’t even load up the new update screen and I hadn’t been connected to WiFi to download it. If it hadn’t updated though I don’t see why it got sent into a bootloop like something had been corrupted.

**Comment by Mosa01** [comment]
****

**Comment by Gangster8192** [comment]
Is not a issue, close this.

**Comment by GamingSlimeYT** [comment]
You must have installed something with a tweak that deleted an important file in your system, for example if you deleted /var that problem will happen, it will restart your phone and show the update screen, once you swipe up or press home button, it will restart your phone. And show the same panel over and over...
