### ISSUE TITLE
iphone XR ios 12.1.3 unsupported

### ISSUE THREAD

**Issue by rezabobi** [pwn20wndstuff/Undecimus#985]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by SarahH12099** [comment]
unc0ver is for iOS 12.0-12.1.2 only so obviously 12.1.3 isn’t supported...

**Comment by rezabobi** [comment]
Today I see site final v3.0.1 is add 12.1.3 -12.2

**Comment by rezabobi** [comment]
Last updated at: 04/23/2019

04/23/2019 - v3.0.1 was released for production with the following changes:

    Iterate the proc list with proper data locks in Unrestrict to fix a possible race condition in the kernel (Important stability fix)
    Fix a typo in the app
    Fix a bug in logging
    Add iOS 12.1.3 - 12.2 support for the restart button
but not working XR ios 12.1.3

**Comment by Randomblock1** [comment]
You’re on A12. Unc0ver doesn’t support A12 yet. Wait until Unc0ver supports A12, and try again. And also fix your bug report and put actual information in there. Case closed.

**Comment by Gangster8192** [comment]
For the restart button. Only the restart button works for 12.1.3 - 12.2
