### ISSUE TITLE
Add iOS 12.1.3 - 12.2 support for the restart button

### ISSUE THREAD

**Issue by rezabobi** [pwn20wndstuff/Undecimus#989]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by MysticTheProtogen-TechWiz** [comment]
No Info Provided Please Edit And Fix This

**Comment by Ro0ush** [comment]
لبعالا

**Comment by Gangster8192** [comment]
The restart option works for my non-jailbroken iPad 7,3 (A10X) running 12.1.4.
