### ISSUE TITLE
Boot Loop after clicking the restart button on uncover

### ISSUE THREAD

**Issue by MysticTheProtogen-TechWiz** [pwn20wndstuff/Undecimus#990]
**Describe the bug**
Clicked The Restart Button and it put my device in a boot loop
**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: XR
 - unc0ver Version: 3.1v 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Amplespencer** [comment]
a bootloop or respring loop?

respring loop is a circle spinning

bootloop is apple logo

does it end ever?

if it's a respring loop press vol up vol down and hold power

**Comment by MysticTheProtogen-TechWiz** [comment]
i fixed it thanks

**Comment by Amplespencer** [comment]
so was it a respringloop?

**Comment by moks84** [comment]
May you share the fix with us, I'm having the same issue now and can't solve it
my phone keep restarting and after apple logo the spinning wheel appear then restart and same thing happens again.

**Comment by Amplespencer** [comment]
update your unc0ver app


to leave the spinning circle press vol up then vol down and power for 10
secs

or if you are on a smaller phone home button and power for 10 secs

**Comment by moks84** [comment]
I used the latest uncover.
Now I cannot start the phone, it just restart then followed by spinning wheel then restart again and again.

tried the hard restart (power + Home) but same scenario.

**Comment by Amplespencer** [comment]
that's not possible, you're doing something wrong

make sure you are on v3.0.1 and restore rootfs and increase memory

**Comment by moks84** [comment]
Yes, I think I tried installing old tweak called mywi 8, then I removed it.
The phone restarted and since then I had this issue.

I used the 3.0.1 latest uncover on my 5s device.
accessing any of normal or safe mode is not possible now.

**Comment by Amplespencer** [comment]
RESTORE ROOTFS IN UNC0VER SETTINGS

**Comment by moks84** [comment]
The ios is not starting at all, how  should I use the uncover without being able to access the ios ?

**Comment by Amplespencer** [comment]
are you on an iphone 7? volume up and power for 10-15 seconds

**Comment by moks84** [comment]
No, I'm on iPhone 5S,
I tried Power + Home button, that restarted the phone but then the spinning wheel showed up and started the restarting loop.

**Comment by Amplespencer** [comment]
I mean I can tell you how to restore and get your phone back but you'll
lose your jailbreak, I actually am confused how you managed to do this

wait

did you delete springboard.app
or install a persistent tweak

**Comment by moks84** [comment]
If you meant to restore into next signed ios then I will end with this solution if no way else.
Yes, I installed persistent tweak which I think it cause this but I am unable know to clear it.

**Comment by moks84** [comment]
well I was glad that this was solved without restoring the ios.
I just put the phone onto the DFU mode and was waiting the download of 12.2 ios but the phone fortunatly was restarted and allowed to boot to the ios.
it was unjailbroken of course but that was an easy issue since the system stayed with the 12.1.2 ios.

Thank you for the help
