### ISSUE TITLE
Allow unc0ver to jailbreak (and not stop at 2) when SystemVersion.plist was changed to 12.2 / 16E227

### ISSUE THREAD

**Issue by Jack-Bauer24** [pwn20wndstuff/Undecimus#992]
**Additional context**
I though I was clever, but maybe I was too clever:

Problem: I had to update my jailbroken iP8 to 12.2 because of a boot loop. No chance for downgrade, although I have all blobs (no nonce setteer for 12.2). Lukily I got hold of another iP8 with 12.1.2. However, I could not restore the backup with all my data from the iP8 12.2 to the one with 12.1.2. Apple would not allow, and I found no 3rd party software to do a full restore job on a lower iOS.

I figured, it must be the vesion code in iOS. So I came across this small tutorial: 
[https://www.cydiageeks.com/change-version-iphone-apps-firmware.html]

So, I jailbroke the iP8 12.1.2, changed the SystemVersion.plist to 12.2 and 16E227, iTunes recognised it as 12.2, it restored the backup perfectly (iOS was definately not updated), injected unc0ver again - and then the process stopped @ step 2 ("no offsets for iPhone10,4 16E227"). Meaning, no jailbreak, no chance to change SystemVersion.plist back to 12.1.2, no nothing...

**Describe the feature you'd like**
Could you please allow unc0ver to run the process past step 2 and at least try the jb-method? There must be other areas where the "true" iOS version could be obtained from. Maybe add a switch for a manipulated SystemVersion.plist and then jump over the 12.2 test?
This way a "real" 12.1.2, which pretends to be a 12.2, could still be jailbroken.

**Describe alternatives you've considered**
Same problem with Restore RootFS (rec0ver) - would not get past step 2.
I could reset the whole phone to stock - and hope it reverts the SystemVersion.plist back to the original 12.1.2, but I am not sure if that will work - and I am back at the problem: the 12.2 backup would not restore on an 12.1.2 phone.

**Additional context**
none

**Comment by clarityzzz** [comment]
You'll have to manually build and modify unc0ver. There's no other way.

**Comment by delon5** [comment]
Try this uncover 

https://reddit.com/r/jailbreak/comments/b7mh87/_/ejsq2gu/?context=1

**Comment by parrotgeek1** [comment]
btw you  can modify i think Status.plist in the backup to say 12.1

**Comment by iAppleLuvr** [comment]
> btw you can modify i think Status.plist in the backup to say 12.1

lol that's what you're supposed to do, not modify your systemversion plist on your iPhone.
