### ISSUE TITLE
iPhone X 12.1.1b3 random app crashes and CC freeze

### ISSUE THREAD

**Issue by alrusev** [pwn20wndstuff/Undecimus#994]
So for a while I've had some odd stuff happening on my iPX running u0 beta 50.

Occasionally when I try to open Instagram/Photos/YouTube/Camera, I will get sent into Safe Mode as soon as I click the icon. Then I restart the SpringBoard, try it again and sometimes it works, another it repeats the issue until it resolves itself by 1/2 more SpringBoard restarts.

Onto the second issue - sometimes when I'm turning Data on, or my Wi-FI off from the control center, my entire phone will freeze. The screen will stay on, but it won't respond to touch or turn off by holding down the Power button - it just ignores everything and is stuck like that for a minute or two before respringing and being fine again. I noticed that when it happens the music/podcasts don't stop - the issue has occurred while I was at the gym and despite freezing music kept playing through my wireless earbuds.

**Comment by ZerOneX** [comment]
Same here... anyone knows something about it already?
