### ISSUE TITLE
Snapchat reboots device randomly

### ISSUE THREAD

**Issue by beastronz** [pwn20wndstuff/Undecimus#995]
**Describe the bug**
Device randomly restarts while using snapchat (cannot be replicated but only happens while on snapchat or exiting from snapchat)

**Device (please complete the following information):**
 - iOS Version: iOS 12.1.2
 - iOS Device: iPhone SE
 - unc0ver Version: 3.0.1 (has been present throughtout my unc0ver experience)

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ X] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Comment by 3nge** [comment]
Yes, this has happened to me too. iPhone 6S iOS12.0 and all uncover versions after b35 (that's when I started to use uncover).

**Comment by xd4niel** [comment]
I can also confirm that this indeed happens as far as unc0ver v3.0.0~b29. 
iPhone SE on iOS 12.1.2.

**Comment by PassiveModding** [comment]
Happens to me too, Iphone 8, ios 12.1.2. Typically happens right after sending a snapchat.
I saw somewhere people were saying it's due to high cpu usage from sending things but cannot confirm
